import{useEffect,useState}from'react'
import{BarChart3,BookOpen,Brain,ChevronRight,Copy,Download,Layers,Plus,RotateCcw,Search,Sparkles,Trash2,X}from'lucide-react'
import{useAccount}from'../account/store'
import{createCard,createDeck,deleteCard,deleteDeck,downloadCsv,duplicateCard,exportAnki,fetchStats,listCards,listDecks,moveCard,reviewCard,reviewQueue,updateCard,updateDeck}from'./flashcardsApi'
import type{Flashcard,FlashcardDeck,FlashcardStats,GenerationSource}from'./flashcardsTypes'
import GenerationDialog from'./GenerationDialog'
import'./flashcards.css'

type View='today'|'decks'|'cards'|'stats'
const emptyCard={front:'',back:'',subject:'',chapter:'',tags:[] as string[],deckId:''}
export default function FlashcardsWorkspace({openCourse,openDocument}:{openCourse:(courseId:string,sectionId?:string|null)=>void;openDocument:(documentId:string,sectionId?:string|null)=>void}){
 const account=useAccount(),[view,setView]=useState<View>('today'),[decks,setDecks]=useState<FlashcardDeck[]>([]),[cards,setCards]=useState<Flashcard[]>([]),[stats,setStats]=useState<FlashcardStats|null>(null),[query,setQuery]=useState(''),[deckFilter,setDeckFilter]=useState(''),[subjectFilter,setSubjectFilter]=useState(''),[chapterFilter,setChapterFilter]=useState(''),[tagFilter,setTagFilter]=useState(''),[editor,setEditor]=useState<(typeof emptyCard&{id?:string})|null>(null),[newDeck,setNewDeck]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[review,setReview]=useState<Flashcard[]|null>(null),[reviewIndex,setReviewIndex]=useState(0),[revealed,setRevealed]=useState(false),[reviewStarted,setReviewStarted]=useState(0),[freeText,setFreeText]=useState(''),[generation,setGeneration]=useState<GenerationSource|null>(null),[exportOpen,setExportOpen]=useState(false),[exportScope,setExportScope]=useState<'all'|'due'|'decks'|'course'>('all'),[exportDecks,setExportDecks]=useState<string[]>([]),[exportCourse,setExportCourse]=useState('')
 const refresh=async()=>{if(!account.user)return;setLoading(true);setError('');try{const[d,c,s]=await Promise.all([listDecks(),listCards({limit:100,query,deck:deckFilter,subject:subjectFilter,chapter:chapterFilter,tag:tagFilter}),fetchStats()]);setDecks(d);setCards(c.cards);setStats(s)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void refresh()},[account.user?.id,query,deckFilter,subjectFilter,chapterFilter,tagFilter])
 const startReview=async(deckId?:string)=>{try{const due=await reviewQueue(deckId);setReview(due);setReviewIndex(0);setRevealed(false);setReviewStarted(Date.now())}catch(e){setError((e as Error).message)}}
 const rate=async(rating:'again'|'hard'|'good'|'easy')=>{if(!review?.[reviewIndex])return;await reviewCard(review[reviewIndex].id,rating,Date.now()-reviewStarted);if(reviewIndex===review.length-1){setReview(null);void refresh()}else{setReviewIndex(i=>i+1);setRevealed(false);setReviewStarted(Date.now())}}
 const saveCard=async()=>{if(!editor)return;try{const value={...editor,tags:typeof editor.tags==='string'?(editor.tags as unknown as string).split(',').map(t=>t.trim()).filter(Boolean):editor.tags};if(editor.id)await updateCard(editor.id,value);else await createCard(value);setEditor(null);await refresh()}catch(e){setError((e as Error).message)}}
 const addDeck=async()=>{if(!newDeck.trim())return;try{await createDeck({name:newDeck});setNewDeck('');await refresh()}catch(e){setError((e as Error).message)}}
 const current=review?.[reviewIndex]
 const masteredPercent=stats?.total?Math.round(stats.mastered/stats.total*100):0
 const sourceAction=(card:Flashcard)=>{if(card.source.courseId)openCourse(card.source.courseId,card.source.sectionId);else if(card.source.documentId)openDocument(card.source.documentId,card.source.sectionId)}
 if(!account.user)return <section className="study-workspace flash-workspace"><header className="flash-hero"><div><span className="study-eyebrow">MÉMORISER AVEC RÉGULARITÉ</span><h1>Vos flashcards.<br/><em>Une notion à la fois.</em></h1><p>Connectez-vous pour créer vos decks, synchroniser vos cartes et retrouver vos révisions sur tous vos appareils.</p></div><Brain size={90}/></header><div className="mycourses-alert mycourses-alert-warning"><strong>Connexion nécessaire</strong><p>La création et la progression sont isolées dans votre compte MyCorpus.</p></div></section>
 if(review)return <section className="study-workspace flash-workspace flash-review"><header><button className="study-text-link" onClick={()=>setReview(null)}><X size={16}/>Quitter</button><span>{reviewIndex+1} / {review.length}</span></header>{current?<article className="review-card"><span className="study-eyebrow">{decks.find(d=>d.id===current.deckId)?.name||'Flashcard'}</span><div className="review-face"><small>RECTO</small><h1>{current.front}</h1></div>{revealed?<><div className="review-answer"><small>VERSO</small><p>{current.back}</p></div><div className="review-ratings"><button onClick={()=>rate('again')}><strong>À revoir</strong><small>≈ 10 min</small></button><button onClick={()=>rate('hard')}><strong>Difficile</strong><small>intervalle court</small></button><button onClick={()=>rate('good')}><strong>Correct</strong><small>progression normale</small></button><button onClick={()=>rate('easy')}><strong>Facile</strong><small>intervalle long</small></button></div></>:<button className="study-primary" onClick={()=>setRevealed(true)}>Afficher la réponse</button>}</article>:<div className="flash-empty"><h2>Révision terminée</h2><button onClick={()=>setReview(null)}>Retour aux flashcards</button></div>}</section>
 return <section className="study-workspace flash-workspace" aria-label="Flashcards"><header className="flash-hero"><div><span className="study-eyebrow">RÉPÉTITION ESPACÉE · SYNCHRONISÉE</span><h1>Vos flashcards.<br/><em>Retenir durablement.</em></h1><p>Créez vos cartes, transformez vos cours en brouillons relus, puis révisez au bon moment.</p></div><div className="flash-hero-score"><strong>{stats?.dueToday||0}</strong><span>à revoir aujourd’hui</span><button className="study-primary" disabled={!stats?.dueToday} onClick={()=>startReview()}>Commencer<ChevronRight size={17}/></button></div></header>
 <nav className="flash-tabs" aria-label="Sections flashcards">{([['today','Aujourd’hui',RotateCcw],['decks','Mes decks',Layers],['cards','Toutes mes cartes',BookOpen],['stats','Statistiques',BarChart3]]as const).map(([id,label,Icon])=><button key={id} aria-pressed={view===id} onClick={()=>setView(id)}><Icon size={17}/>{label}</button>)}</nav>
 {error&&<p className="flash-error" role="alert">{error}</p>}{loading?<p className="flash-loading">Chargement de vos flashcards…</p>:view==='today'?<div className="flash-dashboard"><div className="flash-stat-grid"><article><strong>{stats?.dueToday||0}</strong><span>À réviser</span></article><article><strong>{stats?.newCards||0}</strong><span>Nouvelles</span></article><article><strong>{stats?.mastered||0}</strong><span>Maîtrisées</span></article><article><strong>{stats?.streak||0} j</strong><span>Série actuelle</span></article></div><section className="flash-free-generator"><div><Sparkles size={24}/><h2>Générer depuis un texte</h2><p>Collez vos notes ou un extrait de cours. Le texte sert uniquement à produire l’aperçu et n’est pas conservé.</p></div><textarea aria-label="Texte à transformer en flashcards" placeholder="Collez ici le contenu à mémoriser…" value={freeText} onChange={e=>setFreeText(e.target.value)} maxLength={300000}/><button className="study-primary" disabled={freeText.trim().length<40} onClick={()=>setGeneration({kind:'text',title:'Texte libre',text:freeText})}><Sparkles size={16}/>Générer des flashcards</button></section><section><div className="flash-section-heading"><h2>Vos decks</h2><button onClick={()=>setView('decks')}>Tout afficher</button></div><div className="deck-grid">{decks.slice(0,6).map(deck=><article key={deck.id}><span>{deck.subject||'Deck personnel'}</span><h3>{deck.name}</h3><p>{deck.cardCount} cartes · {deck.dueCount} dues</p><button disabled={!deck.dueCount} onClick={()=>startReview(deck.id)}>Réviser ce deck</button></article>)}</div></section></div>:
 view==='decks'?<div><div className="flash-create-deck"><input aria-label="Nom du nouveau deck" placeholder="Nom du nouveau deck" value={newDeck} onChange={e=>setNewDeck(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void addDeck()}}/><button className="study-primary" onClick={addDeck}><Plus size={16}/>Créer un deck</button></div><div className="deck-grid">{decks.map(deck=><article key={deck.id}><span>{deck.subject||'Deck personnel'}</span><h3>{deck.name}</h3><p>{deck.cardCount} cartes · {deck.dueCount} à revoir</p><div><button onClick={()=>{const name=prompt('Nouveau nom du deck',deck.name);if(name)void updateDeck(deck.id,{name}).then(refresh)}}>Renommer</button><button onClick={()=>{if(confirm(`Supprimer « ${deck.name} » et ses cartes ?`))void deleteDeck(deck.id).then(refresh)}}><Trash2 size={14}/>Supprimer</button></div></article>)}</div></div>:
 view==='cards'?<div><div className="flash-card-toolbar"><div><Search size={16}/><input aria-label="Rechercher dans les flashcards" placeholder="Rechercher recto, verso, matière, tag…" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="Filtrer par deck" value={deckFilter} onChange={e=>setDeckFilter(e.target.value)}><option value="">Tous les decks</option>{decks.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><input aria-label="Filtrer par matière" placeholder="Matière" value={subjectFilter} onChange={e=>setSubjectFilter(e.target.value)}/><input aria-label="Filtrer par chapitre" placeholder="Chapitre" value={chapterFilter} onChange={e=>setChapterFilter(e.target.value)}/><input aria-label="Filtrer par tag" placeholder="Tag" value={tagFilter} onChange={e=>setTagFilter(e.target.value)}/><button className="study-primary" disabled={!decks.length} onClick={()=>setEditor({...emptyCard,deckId:deckFilter||decks[0].id})}><Plus size={16}/>Nouvelle carte</button></div><div className="flash-card-list">{cards.map(card=><article key={card.id}><div><span>{decks.find(d=>d.id===card.deckId)?.name} · {card.subject||'Sans matière'}</span><h3>{card.front}</h3><p>{card.back}</p>{card.tags.length?<div className="flash-tags">{card.tags.map(tag=><em key={tag}>{tag}</em>)}</div>:null}</div><div className="flash-card-actions">{(card.source.courseId||card.source.documentId)&&<button onClick={()=>sourceAction(card)}>Voir dans {card.source.documentId?'le PDF':'le cours'}</button>}<button onClick={()=>setEditor({...card,tags:card.tags})}>Modifier</button><select aria-label={'Déplacer '+card.front} value={card.deckId} onChange={e=>void moveCard(card.id,e.target.value).then(refresh)}>{decks.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><button title="Dupliquer" onClick={()=>void duplicateCard(card.id).then(refresh)}><Copy size={15}/></button><button title="Supprimer" onClick={()=>void deleteCard(card.id).then(refresh)}><Trash2 size={15}/></button></div></article>)}</div>{!cards.length&&<p className="flash-empty">Aucune carte ne correspond à ces filtres.</p>}</div>:
 <div className="flash-stats"><div className="flash-stat-grid"><article><strong>{stats?.total||0}</strong><span>Cartes</span></article><article><strong>{stats?.successRate||0}%</strong><span>Taux de réussite</span></article><article><strong>{stats?.mastered||0}</strong><span>Maîtrisées</span></article><article><strong>{masteredPercent}%</strong><span>Progression</span></article></div><section><h2>Progression par deck</h2>{stats?.decks.map(deck=><div className="deck-progress" key={deck.id}><span><strong>{deck.name}</strong><small>{deck.mastered}/{deck.total} maîtrisées · {deck.due} dues</small></span><progress max={Math.max(1,deck.total)} value={deck.mastered}/></div>)}</section><section><h2>Progression par matière</h2>{stats?.subjects.map(subject=><div className="deck-progress" key={subject.name}><span><strong>{subject.name}</strong><small>{subject.mastered}/{subject.total} maîtrisées</small></span><progress max={Math.max(1,subject.total)} value={subject.mastered}/></div>)}</section><button className="study-secondary" onClick={()=>setExportOpen(true)}><Download size={16}/>Exporter vers Anki</button></div>}
 {editor&&<div className="flash-modal-backdrop"><section className="flash-modal flash-card-editor" role="dialog" aria-modal="true"><header><h2>{editor.id?'Modifier la carte':'Nouvelle carte'}</h2><button className="icon-button" onClick={()=>setEditor(null)}><X/></button></header><label>Deck<select value={editor.deckId} onChange={e=>setEditor({...editor,deckId:e.target.value})}>{decks.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Recto<textarea value={editor.front} onChange={e=>setEditor({...editor,front:e.target.value})}/></label><label>Verso<textarea value={editor.back} onChange={e=>setEditor({...editor,back:e.target.value})}/></label><div className="flash-setting-grid"><label>Matière <small>(facultatif)</small><input value={editor.subject} onChange={e=>setEditor({...editor,subject:e.target.value})}/></label><label>Chapitre <small>(facultatif)</small><input value={editor.chapter} onChange={e=>setEditor({...editor,chapter:e.target.value})}/></label></div><label>Tags séparés par des virgules<input value={Array.isArray(editor.tags)?editor.tags.join(', '):editor.tags} onChange={e=>setEditor({...editor,tags:e.target.value as unknown as string[]})}/></label><button className="study-primary" disabled={!editor.deckId||!editor.front.trim()||!editor.back.trim()} onClick={saveCard}>Enregistrer</button></section></div>}
 {generation&&<GenerationDialog source={generation} onClose={()=>setGeneration(null)} onSaved={()=>{setFreeText('');void refresh()}}/>}
 {exportOpen&&<div className="flash-modal-backdrop"><section className="flash-modal flash-card-editor" role="dialog" aria-modal="true"><header><h2>Exporter vers Anki</h2><button className="icon-button" onClick={()=>setExportOpen(false)}><X/></button></header><label>Contenu<select value={exportScope} onChange={e=>setExportScope(e.target.value as typeof exportScope)}><option value="all">Toutes mes flashcards</option><option value="due">Uniquement les cartes à réviser</option><option value="decks">Un ou plusieurs decks</option><option value="course">Les cartes d’un cours</option></select></label>{exportScope==='decks'&&<fieldset>{decks.map(deck=><label className="flash-check" key={deck.id}><input type="checkbox" checked={exportDecks.includes(deck.id)} onChange={e=>setExportDecks(ids=>e.target.checked?[...ids,deck.id]:ids.filter(id=>id!==deck.id))}/>{deck.name}</label>)}</fieldset>}{exportScope==='course'&&<label>Cours<select value={exportCourse} onChange={e=>setExportCourse(e.target.value)}><option value="">Choisir un cours</option>{stats?.courses.map(course=><option key={course.id} value={course.id}>{course.title||course.id} · {course.total} cartes</option>)}</select></label>}<button className="study-primary" disabled={exportScope==='decks'&&!exportDecks.length||exportScope==='course'&&!exportCourse} onClick={async()=>{try{const filters=exportScope==='due'?{due:true}:exportScope==='decks'?{deckIds:exportDecks}:exportScope==='course'?{courseId:exportCourse}:{};downloadCsv(await exportAnki(filters),'mycorpus-flashcards.csv');setExportOpen(false)}catch(e){setError((e as Error).message)}}}><Download size={16}/>Télécharger le fichier Anki</button></section></div>}
</section>
}
