import {useEffect,useRef,useState} from 'react'
import {Check,Plus,Sparkles,Trash2,X} from 'lucide-react'
import {createCards,createDeck,generateDrafts,listDecks} from './flashcardsApi'
import type {FlashcardDeck,FlashcardDraft,GenerationSource} from './flashcardsTypes'

export default function GenerationDialog({source,onClose,onSaved}:{source:GenerationSource;onClose:()=>void;onSaved?:(info:{count:number;deckName:string})=>void}) {
 const [decks,setDecks]=useState<FlashcardDeck[]>([]),[deckId,setDeckId]=useState('')
 const [level,setLevel]=useState<'essential'|'standard'|'complete'>('standard'),[count,setCount]=useState(12)
 const [selectedSections,setSelectedSections]=useState(()=>source.sections?.map(section=>section.id)||[])
 const [startPage,setStartPage]=useState(1),[endPage,setEndPage]=useState(source.pageCount||1)
 const lock=useRef(false)
 const saveRequest=useRef<{payload:string;id:string}|null>(null)
 const [preview,setPreview]=useState(false)
 const [drafts,setDrafts]=useState<FlashcardDraft[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[newDeck,setNewDeck]=useState('')
 useEffect(()=>{void listDecks().then(value=>{setDecks(value);setDeckId(value[0]?.id||'')}).catch(problem=>setError(problem.message))},[])
 const generate=async()=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const result=await generateDrafts(source,level,count,selectedSections,source.kind==='study'?{startPage,endPage}:undefined);setDrafts(result.drafts);setPreview(result.drafts.length>0);if(!result.drafts.length)setError('Le contenu ne contient pas assez de notions explicites pour produire des cartes utiles.')}catch(problem){setError((problem as Error).message)}finally{lock.current=false;setBusy(false)}}
 const addDeck=async()=>{if(lock.current||!newDeck.trim())return;lock.current=true;setBusy(true);setError('');try{const deck=await createDeck({name:newDeck});setDecks(value=>[deck,...value]);setDeckId(deck.id);setNewDeck('')}catch(problem){setError((problem as Error).message)}finally{lock.current=false;setBusy(false)}}
 const selected=drafts.filter(draft=>draft.selected)
 const invalid=selected.some(draft=>!draft.front.trim()||!draft.back.trim()||draft.front.length>2000||draft.back.length>8000)
 const save=async()=>{if(lock.current||!deckId||!selected.length)return;if(invalid){setError('Complétez le recto et le verso de chaque carte sélectionnée, ou désélectionnez-la.');return}lock.current=true;setBusy(true);setError('');try{const cards=selected.map(draft=>({...draft,deckId}));const payload=JSON.stringify(cards);if(saveRequest.current?.payload!==payload)saveRequest.current={payload,id:crypto.randomUUID()};await createCards(cards,saveRequest.current.id);const targetDeck=decks.find(d=>d.id===deckId);onSaved?.({count:selected.length,deckName:targetDeck?.name||'Inconnu'});onClose()}catch(problem){setError((problem as Error).message)}finally{lock.current=false;setBusy(false)}}
 const close=()=>{if(busy)return;if(preview&&drafts.length&&!confirm('Fermer sans enregistrer les brouillons ?'))return;onClose()}
 return <div className="flash-modal-backdrop" role="presentation"><section className="flash-modal" role="dialog" aria-modal="true" aria-label="Générer des flashcards">
  <header><div><span className="study-eyebrow">GÉNÉRATION EN BROUILLON</span><h2>Créer depuis « {source.title} »</h2></div><button className="icon-button" aria-label="Fermer" disabled={busy} onClick={close}><X/></button></header>
  {!preview?<div className="flash-generator-settings">
   {source.sections?.length?<fieldset><legend>Contenu à utiliser</legend><label className="flash-check"><input type="checkbox" checked={selectedSections.length===source.sections.length} onChange={event=>setSelectedSections(event.target.checked?source.sections!.map(section=>section.id):[])}/><strong>Tout sélectionner</strong></label>{source.sections.map(section=><label className="flash-check" key={section.id}><input type="checkbox" checked={selectedSections.includes(section.id)} onChange={event=>setSelectedSections(ids=>event.target.checked?[...ids,section.id]:ids.filter(id=>id!==section.id))}/><span>{section.title}{section.startPage?` · p. ${section.startPage}${section.endPage!==section.startPage?'–'+section.endPage:''}`:''}</span></label>)}</fieldset>:null}
   {source.kind==='study'&&<div className="flash-setting-grid"><label>Première page<input type="number" min="1" max={source.pageCount||1} value={startPage} onChange={event=>setStartPage(Math.max(1,Number(event.target.value)))}/></label><label>Dernière page<input type="number" min={startPage} max={source.pageCount||1} value={endPage} onChange={event=>setEndPage(Math.min(source.pageCount||1,Number(event.target.value)))}/></label></div>}
   <div className="flash-setting-grid"><label>Niveau<select value={level} onChange={event=>setLevel(event.target.value as typeof level)}><option value="essential">Essentiel</option><option value="standard">Standard</option><option value="complete">Complet</option></select></label><label>Nombre approximatif<input type="number" min="1" max="80" value={count} onChange={event=>setCount(Number(event.target.value))}/></label></div>
   <p>Le nombre est une cible : MyCorpus ne créera pas de cartes artificielles pour l’atteindre.</p><button className="study-primary" disabled={busy||!Number.isInteger(count)||count<1||count>80||Boolean(source.sections?.length&&!selectedSections.length)||startPage>endPage} onClick={generate}><Sparkles size={17}/>{busy?'Analyse en cours…':'Générer les brouillons'}</button>
  </div>:<div className="flash-draft-stage">
   <div className="flash-draft-toolbar"><strong>{drafts.filter(draft=>draft.selected).length} carte(s) sélectionnée(s)</strong><button disabled={busy} onClick={()=>setDrafts(items=>items.map(item=>({...item,selected:true})))}>Tout sélectionner</button><button disabled={busy} onClick={()=>setDrafts(items=>items.map(item=>({...item,selected:false})))}>Tout désélectionner</button></div>
   <p>Relisez chaque carte avant de l’enregistrer. Les cartes sélectionnées doivent toutes être complètes.</p><div className="flash-draft-list">{drafts.map((draft,index)=><article className={draft.selected?'is-selected':''} key={draft.temporaryId}><label className="flash-check"><input type="checkbox" disabled={busy} checked={draft.selected} onChange={event=>setDrafts(items=>items.map((item,itemIndex)=>itemIndex===index?{...item,selected:event.target.checked}:item))}/><span>Carte {index+1}</span></label><label>Recto<textarea disabled={busy} maxLength={2000} value={draft.front} onChange={event=>setDrafts(items=>items.map((item,itemIndex)=>itemIndex===index?{...item,front:event.target.value}:item))}/></label><label>Verso<textarea disabled={busy} maxLength={8000} value={draft.back} onChange={event=>setDrafts(items=>items.map((item,itemIndex)=>itemIndex===index?{...item,back:event.target.value}:item))}/></label>{draft.source.excerpt&&<details><summary>Passage source</summary><p>{draft.source.excerpt}</p></details>}<button className="flash-remove-draft" disabled={busy} onClick={()=>setDrafts(items=>items.filter((_,itemIndex)=>itemIndex!==index))}><Trash2 size={14}/>Supprimer</button></article>)}</div>
   <button className="study-secondary" disabled={busy} onClick={()=>setDrafts(items=>[...items,{temporaryId:crypto.randomUUID(),front:'',back:'',subject:source.subject||'',chapter:source.chapter||source.title,tags:[],selected:true,source:{type:source.kind==='catalog'?'catalog_course':source.kind==='study'?'study_document':source.kind==='qcm-error'?'qcm_error':'free_text',courseId:source.courseId,documentId:source.documentId}}])}><Plus size={16}/>Ajouter une carte</button>
   <div className="flash-save-row"><label>Deck de destination<select disabled={busy} value={deckId} onChange={event=>setDeckId(event.target.value)}><option value="">Choisir un deck</option>{decks.map(deck=><option key={deck.id} value={deck.id}>{deck.name}</option>)}</select></label><div><input disabled={busy} maxLength={100} aria-label="Nouveau deck" placeholder="Nouveau deck…" value={newDeck} onChange={event=>setNewDeck(event.target.value)}/><button disabled={busy||!newDeck.trim()} onClick={addDeck}>Créer</button></div><button className="study-primary" disabled={busy||!deckId||!selected.length} onClick={save}><Check size={17}/>{busy?'Enregistrement…':'Enregistrer la sélection'}</button></div>
  </div>}
  {error&&<p className="flash-error" role="alert">{error}</p>}
 </section></div>
}
