import {useEffect,useState} from 'react'
import {Check,Plus,Sparkles,Trash2,X} from 'lucide-react'
import {createCards,createDeck,generateDrafts,listDecks} from './flashcardsApi'
import type {FlashcardDeck,FlashcardDraft,GenerationSource} from './flashcardsTypes'

export default function GenerationDialog({source,onClose,onSaved}:{source:GenerationSource;onClose:()=>void;onSaved?:()=>void}) {
 const [decks,setDecks]=useState<FlashcardDeck[]>([]),[deckId,setDeckId]=useState('')
 const [level,setLevel]=useState<'essential'|'standard'|'complete'>('standard'),[count,setCount]=useState(12)
 const [selectedSections,setSelectedSections]=useState(()=>source.sections?.map(section=>section.id)||[])
 const [startPage,setStartPage]=useState(1),[endPage,setEndPage]=useState(source.pageCount||1)
 const [drafts,setDrafts]=useState<FlashcardDraft[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[newDeck,setNewDeck]=useState('')
 useEffect(()=>{void listDecks().then(value=>{setDecks(value);setDeckId(value[0]?.id||'')}).catch(problem=>setError(problem.message))},[])
 const generate=async()=>{setBusy(true);setError('');try{const result=await generateDrafts(source,level,count,selectedSections,source.kind==='study'?{startPage,endPage}:undefined);setDrafts(result.drafts);if(!result.drafts.length)setError('Le contenu ne contient pas assez de notions explicites pour produire des cartes utiles.')}catch(problem){setError((problem as Error).message)}finally{setBusy(false)}}
 const addDeck=async()=>{if(!newDeck.trim())return;try{const deck=await createDeck({name:newDeck});setDecks(value=>[deck,...value]);setDeckId(deck.id);setNewDeck('')}catch(problem){setError((problem as Error).message)}}
 const save=async()=>{const chosen=drafts.filter(draft=>draft.selected&&draft.front.trim()&&draft.back.trim());if(!deckId||!chosen.length)return;setBusy(true);try{await createCards(chosen.map(draft=>({...draft,deckId})));onSaved?.();onClose()}catch(problem){setError((problem as Error).message)}finally{setBusy(false)}}
 return <div className="flash-modal-backdrop" role="presentation"><section className="flash-modal" role="dialog" aria-modal="true" aria-label="Générer des flashcards">
  <header><div><span className="study-eyebrow">GÉNÉRATION EN BROUILLON</span><h2>Créer depuis « {source.title} »</h2></div><button className="icon-button" aria-label="Fermer" onClick={onClose}><X/></button></header>
  {!drafts.length?<div className="flash-generator-settings">
   {source.sections?.length?<fieldset><legend>Contenu à utiliser</legend><label className="flash-check"><input type="checkbox" checked={selectedSections.length===source.sections.length} onChange={event=>setSelectedSections(event.target.checked?source.sections!.map(section=>section.id):[])}/><strong>Tout sélectionner</strong></label>{source.sections.map(section=><label className="flash-check" key={section.id}><input type="checkbox" checked={selectedSections.includes(section.id)} onChange={event=>setSelectedSections(ids=>event.target.checked?[...ids,section.id]:ids.filter(id=>id!==section.id))}/><span>{section.title}{section.startPage?` · p. ${section.startPage}${section.endPage!==section.startPage?'–'+section.endPage:''}`:''}</span></label>)}</fieldset>:null}
   {source.kind==='study'&&<div className="flash-setting-grid"><label>Première page<input type="number" min="1" max={source.pageCount||1} value={startPage} onChange={event=>setStartPage(Math.max(1,Number(event.target.value)))}/></label><label>Dernière page<input type="number" min={startPage} max={source.pageCount||1} value={endPage} onChange={event=>setEndPage(Math.min(source.pageCount||1,Number(event.target.value)))}/></label></div>}
   <div className="flash-setting-grid"><label>Niveau<select value={level} onChange={event=>setLevel(event.target.value as typeof level)}><option value="essential">Essentiel</option><option value="standard">Standard</option><option value="complete">Complet</option></select></label><label>Nombre approximatif<input type="number" min="1" max="80" value={count} onChange={event=>setCount(Number(event.target.value))}/></label></div>
   <p>Le nombre est une cible : MyCorpus ne créera pas de cartes artificielles pour l’atteindre.</p><button className="study-primary" disabled={busy||Boolean(source.sections?.length&&!selectedSections.length)||startPage>endPage} onClick={generate}><Sparkles size={17}/>{busy?'Analyse en cours…':'Générer les brouillons'}</button>
  </div>:<div className="flash-draft-stage">
   <div className="flash-draft-toolbar"><strong>{drafts.filter(draft=>draft.selected).length} carte(s) sélectionnée(s)</strong><button onClick={()=>setDrafts(items=>items.map(item=>({...item,selected:true})))}>Tout sélectionner</button><button onClick={()=>setDrafts(items=>items.map(item=>({...item,selected:false})))}>Tout désélectionner</button></div>
   <div className="flash-draft-list">{drafts.map((draft,index)=><article className={draft.selected?'is-selected':''} key={draft.temporaryId}><label className="flash-check"><input type="checkbox" checked={draft.selected} onChange={event=>setDrafts(items=>items.map((item,itemIndex)=>itemIndex===index?{...item,selected:event.target.checked}:item))}/><span>Carte {index+1}</span></label><label>Recto<textarea value={draft.front} onChange={event=>setDrafts(items=>items.map((item,itemIndex)=>itemIndex===index?{...item,front:event.target.value}:item))}/></label><label>Verso<textarea value={draft.back} onChange={event=>setDrafts(items=>items.map((item,itemIndex)=>itemIndex===index?{...item,back:event.target.value}:item))}/></label><button className="flash-remove-draft" onClick={()=>setDrafts(items=>items.filter((_,itemIndex)=>itemIndex!==index))}><Trash2 size={14}/>Supprimer</button></article>)}</div>
   <button className="study-secondary" onClick={()=>setDrafts(items=>[...items,{temporaryId:crypto.randomUUID(),front:'',back:'',subject:source.subject||'',chapter:source.chapter||source.title,tags:[],selected:true,source:{type:source.kind==='catalog'?'catalog_course':source.kind==='study'?'study_document':source.kind==='qcm-error'?'qcm_error':'free_text',courseId:source.courseId,documentId:source.documentId}}])}><Plus size={16}/>Ajouter une carte</button>
   <div className="flash-save-row"><label>Deck de destination<select value={deckId} onChange={event=>setDeckId(event.target.value)}><option value="">Choisir un deck</option>{decks.map(deck=><option key={deck.id} value={deck.id}>{deck.name}</option>)}</select></label><div><input aria-label="Nouveau deck" placeholder="Nouveau deck…" value={newDeck} onChange={event=>setNewDeck(event.target.value)}/><button onClick={addDeck}>Créer</button></div><button className="study-primary" disabled={busy||!deckId||!drafts.some(draft=>draft.selected&&draft.front.trim()&&draft.back.trim())} onClick={save}><Check size={17}/>{busy?'Enregistrement…':'Enregistrer la sélection'}</button></div>
  </div>}
  {error&&<p className="flash-error" role="alert">{error}</p>}
 </section></div>
}
