import type { Course } from '../../curriculum'
import type { Question } from '../../questions'
import { canonicalCourses } from '../../taxonomy/canonicalCourses'

const info = new Map(canonicalCourses.filter(item => item.subject === 'Histologie').map(item => [item.id, item]))
const s = (title: string, text: string) => ({ title, text })
type Draft = { objectives: string[]; sections: Course['sections']; trap: string; recall: string; answer: string; ref: string; prompt: string; caseAnswer: string }
const make = (id: string, d: Draft): Course => {
  const c = info.get(id); if (!c) throw new Error(`Cours canonique absent : ${id}`)
  const source = `https://openstax.org/books/anatomy-and-physiology-2e/pages/${d.ref}`
  return { id, title: c.title, category: c.subject, tag: c.module, minutes: 14, structure: null, objectives: d.objectives, sections: d.sections,
    trap: d.trap, recall: d.recall, answer: d.answer, source, sources: [{ label: 'OpenStax · Anatomy & Physiology 2e', url: source }],
    prerequisites: ['Les tissus fondamentaux', 'Cellules et matrice extracellulaire'],
    glossary: [['Matrice extracellulaire', 'Composants non cellulaires sécrétés qui organisent le tissu.'], ['Tissu avasculaire', 'Tissu dépourvu de vaisseaux sanguins propres.'], ['Polarité', 'Organisation fonctionnelle en domaines cellulaires orientés.']],
    caseStudy: { prompt: d.prompt, answer: d.caseAnswer }, review: { status: 'unreviewed', updatedAt: '2026-09-23', sourcesUpdatedAt: '2026-09-23' } }
}
export const additionalHistologyCourses: Course[] = [
  make('histo-epithelia-covering', { objectives: ['Classer les épithéliums selon le nombre de couches et la forme apicale', 'Associer un type de revêtement à sa fonction', 'Distinguer les épithéliums stratifiés des pseudostratifiés'], ref: '4-2-epithelial-tissue',
    sections: [s('Polarité et lame basale', 'Les cellules épithéliales sont polarisées en domaines apical, latéral et basal. Elles reposent sur une lame basale qui les sépare du tissu conjonctif sous-jacent. Le feuillet est avasculaire et reçoit ses nutriments par diffusion. Les jonctions assurent cohésion, barrière et organisation des échanges.'), s('Nombre de couches', 'Un épithélium simple comporte une seule couche et toutes ses cellules reposent sur la membrane basale. Un épithélium stratifié en comporte plusieurs ; seules les cellules basales touchent cette membrane. Le pseudostratifié semble multicouche car les noyaux sont décalés, mais chaque cellule atteint la lame basale.'), s('Forme cellulaire', 'Les formes décrites sont pavimenteuse, cubique ou cylindrique. Dans les épithéliums stratifiés, la forme des cellules superficielles détermine le nom même si les couches profondes ont une autre forme. La classification combine donc le nombre de couches et l’aspect apical.'), s('Sites et fonctions', 'Le pavimenteux simple favorise diffusion et filtration dans les alvéoles et l’endothélium. Le cubique simple se rencontre notamment dans des tubules et conduits. Le cylindrique simple participe souvent à absorption et sécrétion intestinales. Le stratifié pavimenteux protège les surfaces exposées aux frottements.'), s('Revêtements spécialisés', 'Les voies respiratoires présentent souvent un épithélium cylindrique pseudostratifié cilié avec cellules caliciformes. L’urothélium s’adapte à la distension des voies urinaires. Les microvillosités augmentent la surface d’absorption tandis que les cils déplacent du matériel à la surface : leurs rôles diffèrent.')], trap: 'Le pseudostratifié n’est pas un vrai épithélium stratifié : toutes ses cellules touchent la lame basale.', recall: 'Quel épithélium cilié tapisse classiquement une partie des voies aériennes ?', answer: 'Un épithélium cylindrique pseudostratifié cilié, souvent avec cellules caliciformes.', prompt: 'Une biopsie respiratoire montre des cils, des cellules caliciformes et des noyaux à différentes hauteurs. Comment classer le revêtement ?', caseAnswer: 'Comme épithélium cylindrique pseudostratifié cilié ; l’aspect étagé des noyaux ne correspond pas à plusieurs couches complètes.' }),
  make('histo-cartilage', { objectives: ['Comparer les cartilages hyalin, élastique et fibreux', 'Décrire chondrocytes et matrice cartilagineuse', 'Expliquer nutrition et potentiel de réparation'], ref: '4-3-connective-tissue-supporting-tissues',
    sections: [s('Cellules et matrice', 'Les chondroblastes synthétisent la matrice et deviennent des chondrocytes logés dans des lacunes. Collagène, protéoglycanes et eau donnent au tissu ses propriétés mécaniques. Les groupes isogéniques sont des amas de cellules issues de divisions locales.'), s('Cartilage hyalin', 'Le cartilage hyalin est riche en collagène de type II et protéoglycanes. Il recouvre les surfaces articulaires, forme les cartilages costaux et soutient plusieurs voies aériennes. Le cartilage articulaire n’a pas de périchondre et dépend notamment du liquide synovial pour les échanges.'), s('Cartilage élastique', 'Le cartilage élastique contient un réseau abondant de fibres élastiques et garde une capacité de déformation réversible. Il se trouve notamment dans le pavillon de l’oreille et l’épiglotte. Il est généralement entouré d’un périchondre.'), s('Fibrocartilage', 'Le fibrocartilage contient de gros faisceaux de collagène de type I et des chondrocytes entre les fibres. Il résiste à la traction et à la compression dans les disques intervertébraux, les ménisques et la symphyse pubienne. Il est dépourvu de périchondre.'), s('Nutrition et réparation', 'Le cartilage est avasculaire, ses cellules reçoivent donc les nutriments par diffusion depuis les tissus voisins, le périchondre ou le liquide synovial selon le site. La réparation est limitée, en particulier dans le cartilage articulaire. La croissance peut être interstitielle ou appositionnelle.')], trap: 'Le cartilage articulaire et le fibrocartilage sont dépourvus de périchondre ; la réparation reste limitée.', recall: 'Quel type cartilagineux se trouve dans les disques intervertébraux ?', answer: 'Le fibrocartilage, riche en faisceaux de collagène de type I.', prompt: 'Une coupe de ménisque montre des chondrocytes entre de forts faisceaux de collagène. Quel tissu reconnaît-on ?', caseAnswer: 'Du fibrocartilage, adapté aux contraintes combinées de traction et de compression.' }),
  make('histo-vascular-wall', { objectives: ['Décrire les tuniques des parois vasculaires', 'Comparer artères élastiques, musculaires et artérioles', 'Relier la structure veineuse au retour du sang'], ref: '20-1-structure-and-function-of-blood-vessels',
    sections: [s('Organisation générale', 'La plupart des vaisseaux comportent une tunique intime, une média et une adventice. Leur épaisseur varie selon le calibre, la pression et la fonction. Les capillaires ont une paroi simple centrée sur l’endothélium et adaptée aux échanges avec les tissus.'), s('Intima et endothélium', 'L’intima comprend l’endothélium pavimenteux simple au contact du sang et une lame basale. L’endothélium participe aux échanges, à l’hémostase, à l’inflammation et au tonus vasculaire. Une limitante élastique interne est visible dans plusieurs artères musculaires.'), s('Artères élastiques et musculaires', 'Les artères élastiques proches du cœur, telle l’aorte, possèdent une média riche en lames élastiques et amortissent les variations de pression. Les artères musculaires distribuent le sang vers les organes et ajustent leur calibre grâce au muscle lisse. Leur architecture répond aux contraintes hémodynamiques.'), s('Artérioles et capillaires', 'Les artérioles, constituées d’une ou de quelques couches de muscle lisse, règlent fortement la résistance périphérique et l’entrée du sang dans les réseaux capillaires. Les capillaires permettent diffusion, filtration et transport vésiculaire selon leur type et les besoins du tissu.'), s('Veines', 'À calibre comparable, les veines ont souvent une lumière plus large et une paroi plus mince que les artères ; leur média est moins développée et l’adventice peut être prédominante. Des valvules limitent le reflux dans certains territoires. La pompe musculaire et les variations de pression thoracique aident le retour veineux.')], trap: 'Les artérioles règlent la résistance périphérique ; les veines sont des vaisseaux capacitifs avec une paroi adaptée à une pression plus basse.', recall: 'Quelle tunique est directement en contact avec le sang ?', answer: 'La tunique intime, dont la surface luminale est formée par l’endothélium.', prompt: 'Une artère de gros calibre présente de nombreuses lames élastiques dans sa média. Quelle adaptation cela reflète-t-il ?', caseAnswer: 'L’amortissement de l’onde de pression pulsatile à proximité du cœur, caractéristique des artères élastiques.' })
]

const notes: Record<string, string> = {
  'histo-epithelia-covering': 'Les jonctions serrées limitent le passage paracellulaire, les jonctions d’ancrage résistent aux tensions et les jonctions communicantes permettent certains échanges entre cellules. Leur distribution varie avec la fonction de barrière ou de transport. La lame basale participe aussi à l’adhérence, à la polarité et à la régénération après lésion.',
  'histo-cartilage': 'Le périchondre comporte une couche fibreuse externe et une région interne plus cellulaire, capable de fournir des chondroblastes lors de la croissance appositionnelle. Il est absent des surfaces articulaires et du fibrocartilage. Les chondrocytes maintiennent leur matrice dans un environnement pauvre en oxygène, mais leur faible renouvellement explique en partie les limites de réparation.',
  'histo-vascular-wall': 'Les vasa vasorum nourrissent les parois des gros vaisseaux lorsque la diffusion depuis la lumière ne suffit plus. Les nervi vasorum contribuent à la régulation du muscle lisse dans plusieurs territoires. En histologie, le diamètre et la forme de la lumière dépendent aussi de la pression, de la fixation et de la coupe, et doivent être interprétés avec les tuniques.'
}
for (const course of additionalHistologyCourses) course.sections.push(s('Organisation complémentaire', notes[course.id]))

const content: Record<string, { prompts: string[]; answers: string[] }> = {
  'histo-epithelia-covering': { prompts: ['Toutes les cellules pseudostratifiées atteignent-elles la lame basale ?', 'Comment nomme-t-on un épithélium stratifié ?', 'Quel revêtement protège les surfaces soumises aux frottements ?', 'Quelle spécialisation augmente la surface d’absorption ?', 'Quel épithélium s’adapte à la distension urinaire ?'], answers: ['Oui, même si leurs noyaux sont à des hauteurs différentes.', 'D’après la forme des cellules superficielles.', 'L’épithélium stratifié pavimenteux.', 'Les microvillosités.', 'L’urothélium ou épithélium transitionnel.'] },
  'histo-cartilage': { prompts: ['Quel collagène domine dans le fibrocartilage ?', 'Quel cartilage trouve-t-on dans l’épiglotte ?', 'Le cartilage articulaire possède-t-il un périchondre ?', 'Quelle cellule mature réside dans une lacune ?', 'Comment les nutriments atteignent-ils le cartilage ?'], answers: ['Le collagène de type I.', 'Le cartilage élastique.', 'Non.', 'Le chondrocyte.', 'Par diffusion depuis le périchondre, le liquide synovial ou les tissus voisins selon le site.'] },
  'histo-vascular-wall': { prompts: ['Quelle tunique porte l’endothélium ?', 'Quelle tunique est riche en muscle lisse ?', 'Quel type artériel contient de nombreuses lames élastiques ?', 'Quel petit vaisseau musculaire ajuste finement la résistance à l’écoulement ?', 'Quel mécanisme contribue au retour veineux des membres ?'], answers: ['La tunique intime.', 'La média.', 'L’artère élastique, telle que l’aorte.', 'L’artériole.', 'Les valvules et la pompe musculaire.'] }
}
const distractors = ['La tunique séreuse.', 'Le cartilage de croissance.', 'La couche cornée seule.']
export const additionalHistologyQuestions: Question[] = additionalHistologyCourses.flatMap((course, ci) => content[course.id].prompts.map((prompt, i) => {
  const options = [content[course.id].answers[i], distractors[(i + ci) % 3], distractors[(i + ci + 1) % 3], distractors[(i + ci + 2) % 3]]
  return { id: `${course.id}-q${i + 1}`, course: course.id, topic: 'Histologie', prompt, options, correct: [0], why: options.map((_, j) => j === 0 ? `Cette réponse correspond au repère histologique expliqué dans le cours : ${content[course.id].answers[i]}` : 'Cette proposition ne décrit pas la structure tissulaire demandée.'), difficulty: i < 2 ? 'essentiel' as const : 'application' as const, format: 'single' as const }
}))
