import type { Course } from '../../curriculum'
import type { Question } from '../../questions'
import { canonicalCourses } from '../../taxonomy/canonicalCourses'

const metadata = new Map(canonicalCourses.filter(item => item.subject === 'Histologie').map(item => [item.id, item]))
const base = 'https://openstax.org/books/anatomy-and-physiology-2e/pages/'
type Draft = { objectives: string[]; sections: Course['sections']; trap: string; recall: string; answer: string; source: string; caseStudy: NonNullable<Course['caseStudy']>; glossary: NonNullable<Course['glossary']> }
const s = (title: string, text: string, bullets?: string[]) => ({ title, text, ...(bullets ? { bullets } : {}) })
function course(id: string, d: Draft): Course {
  const c = metadata.get(id)
  if (!c) throw new Error(`Chapitre canonique d’histologie introuvable : ${id}`)
  return { id, title: c.title, category: c.subject, tag: c.module, minutes: 13, structure: null, objectives: d.objectives,
    sections: d.sections, trap: d.trap, recall: d.recall, answer: d.answer, source: base + d.source,
    sources: [{ label: 'OpenStax · Anatomy & Physiology 2e', url: base + d.source }],
    prerequisites: ['Les quatre familles tissulaires', 'Organisation cellulaire et matrice extracellulaire'], glossary: d.glossary, caseStudy: d.caseStudy,
    review: { status: 'unreviewed', updatedAt: '2026-09-23', sourcesUpdatedAt: '2026-09-23' } }
}
export const histologyCourses: Course[] = [
  course('histo-blood-cells', {
    objectives: ['Distinguer plasma et éléments figurés du sang', 'Identifier les grandes lignées cellulaires sanguines', 'Relier hématopoïèse et fonctions de transport ou défense'],
    sections: [
      s('Le sang comme tissu conjonctif spécialisé', 'Le sang comprend une matrice extracellulaire liquide, le plasma, et des éléments figurés : érythrocytes, leucocytes et plaquettes. Il transporte gaz, nutriments, déchets, hormones et chaleur tout en participant à l’hémostase et à la défense. L’hématocrite correspond à la fraction volumique occupée principalement par les globules rouges.'),
      s('Plasma et sérum', 'Le plasma contient eau, électrolytes, nutriments, déchets et protéines, dont albumine, globulines et fibrinogène. L’albumine contribue fortement à la pression oncotique et transporte diverses molécules ; le fibrinogène intervient dans la coagulation. Le sérum est le liquide obtenu après coagulation et ne contient plus le fibrinogène consommé dans le caillot.'),
      s('Érythrocytes', 'Les globules rouges matures humains n’ont pas de noyau et sont riches en hémoglobine. Leur forme biconcave facilite les échanges et leur déformabilité permet le passage dans les capillaires. Ils transportent l’oxygène et contribuent au transport du dioxyde de carbone et au tamponnement acido-basique. Leur durée de vie moyenne est d’environ 120 jours.'),
      s('Leucocytes et plaquettes', 'Les leucocytes comprennent granulocytes, monocytes et lymphocytes, aux rôles complémentaires dans inflammation, immunité innée et adaptative. Les plaquettes sont des fragments cytoplasmiques dérivés des mégacaryocytes et participent au clou plaquettaire puis à la coagulation. Les proportions varient selon l’âge, l’état physiologique et les maladies.'),
      s('Hématopoïèse et lecture biologique', 'Les cellules sanguines dérivent de cellules souches hématopoïétiques médullaires qui s’engagent dans des lignées myéloïdes ou lymphoïdes. La production est régulée par cytokines et facteurs de croissance, notamment l’érythropoïétine dans l’érythropoïèse. Une numération s’interprète avec indices, contexte clinique, hydratation et intervalles adaptés au laboratoire.'),
    ], trap: 'Le plasma est prélevé sur sang anticoagulé ; le sérum est obtenu après coagulation et diffère notamment par le fibrinogène.', recall: 'Quels éléments figurés retrouve-t-on dans le sang ?', answer: 'Érythrocytes, leucocytes et plaquettes, baignés dans le plasma.', source: '18-1-an-overview-of-blood', glossary: [['Hématocrite', 'Fraction volumique du sang occupée principalement par les érythrocytes.'], ['Sérum', 'Fraction liquide après coagulation, appauvrie en fibrinogène.'], ['Mégacaryocyte', 'Grande cellule médullaire dont des fragments cytoplasmiques forment les plaquettes.']], caseStudy: { prompt: 'Pourquoi une numération érythrocytaire ne suffit-elle pas à caractériser une anémie ?', answer: 'Il faut aussi examiner hémoglobine, hématocrite, indices érythrocytaires, réticulocytes, contexte clinique et seuils adaptés.' } }),
  course('histo-bone-architecture', {
    objectives: ['Comparer cartilage et tissu osseux', 'Décrire les composants de leur matrice extracellulaire', 'Relier les cellules osseuses au remodelage'],
    sections: [
      s('Deux tissus conjonctifs spécialisés', 'Cartilage et os associent des cellules à une matrice extracellulaire abondante mais ont des propriétés différentes. Le cartilage est avasculaire et possède une matrice hydratée déformable ; l’os est vascularisé, minéralisé et remodelé continuellement. Leur architecture reflète les contraintes mécaniques auxquelles ils répondent.'),
      s('Cartilage et chondrocytes', 'Les chondroblastes synthétisent la matrice puis deviennent des chondrocytes logés dans des lacunes. Collagène, protéoglycanes et eau donnent au cartilage résistance à la compression et élasticité variable selon le type. Cartilages hyalin, élastique et fibreux diffèrent par leur organisation et leurs fibres dominantes. La nutrition des chondrocytes dépend surtout de la diffusion.'),
      s('Matrice osseuse', 'La matrice organique, riche en collagène de type I et protéines non collagéniques, confère une résistance à la traction ; les cristaux minéraux, surtout hydroxyapatite, apportent rigidité et résistance à la compression. L’os compact s’organise en ostéons dans de nombreux os longs, tandis que l’os spongieux présente des travées et des espaces médullaires.'),
      s('Cellules osseuses', 'Les ostéoblastes déposent la matrice ostéoïde et favorisent sa minéralisation. Certains deviennent des ostéocytes emprisonnés dans la matrice, connectés par des canalicules et capables de détecter les contraintes. Les ostéoclastes multinucléés résorbent l’os dans un microenvironnement acide et enzymatique. L’équilibre entre formation et résorption adapte le squelette.'),
      s('Remodelage et réparation', 'Le remodelage associe résorption puis formation dans des unités fonctionnelles, sous influence mécanique, hormonale et locale. Il participe à l’homéostasie du calcium et au renouvellement de l’os. Une fracture déclenche hématome, cal fibrocartilagineux, cal osseux puis remodelage ; les délais dépendent du site, de l’âge, de la vascularisation et des conditions cliniques.'),
    ], trap: 'Le cartilage n’est pas directement vascularisé : ses cellules reçoivent les nutriments principalement par diffusion à travers la matrice.', recall: 'Quelle cellule résorbe l’os et laquelle dépose la matrice osseuse ?', answer: 'L’ostéoclaste résorbe l’os ; l’ostéoblaste synthétise la matrice ostéoïde et favorise sa minéralisation.', source: '6-3-bone-structure', glossary: [['Ostéoïde', 'Matrice organique osseuse non encore minéralisée.'], ['Ostéon', 'Unité structurale concentrique de l’os compact.'], ['Lacune', 'Logette matricielle occupée notamment par un chondrocyte ou un ostéocyte.']], caseStudy: { prompt: 'Pourquoi une matrice cartilagineuse riche en protéoglycanes résiste-t-elle à la compression ?', answer: 'Les glycosaminoglycanes chargés retiennent l’eau et créent une matrice hydratée qui s’oppose à la compression, en coopération avec le réseau de collagène.' } }),
  course('histo-glands-exocrine-endocrine', {
    objectives: ['Distinguer glandes endocrines et exocrines', 'Décrire les modes de sécrétion', 'Relier organisation glandulaire au produit libéré'],
    sections: [
      s('Épithélium glandulaire', 'Les glandes sont formées de cellules épithéliales spécialisées dans la synthèse et la libération d’un produit. Elles peuvent provenir d’un bourgeonnement épithélial qui conserve ou perd sa connexion avec la surface. L’unité sécrétrice peut être unicellulaire, comme une cellule caliciforme, ou former un organe glandulaire complexe.'),
      s('Glandes exocrines', 'Les glandes exocrines conservent un conduit qui déverse leur sécrétion à la surface du corps ou dans une lumière. Elles sont classées par architecture simple ou composée, forme tubulaire ou acineuse, et nature séreuse, muqueuse ou mixte du produit. La polarité cellulaire organise synthèse, maturation et exocytose vers la lumière.'),
      s('Glandes endocrines', 'Les glandes endocrines n’ont pas de conduit excréteur et libèrent des hormones dans le milieu interstitiel puis le sang. Elles sont souvent richement vascularisées pour distribuer rapidement leurs produits. Les hormones hydrosolubles sont stockées dans des vésicules ; les stéroïdes diffusent après leur synthèse et circulent fréquemment liés à des protéines.'),
      s('Modes de sécrétion', 'La sécrétion mérocrine libère le produit par exocytose sans perte majeure de cytoplasme. La sécrétion apocrine emporte une portion apicale de cytoplasme ; la sécrétion holocrine libère le contenu lors de la désintégration de la cellule, ensuite renouvelée. Les glandes peuvent associer plusieurs produits et modes selon le tissu et l’état fonctionnel.'),
      s('Régulation et histologie fonctionnelle', 'La sécrétion peut être régulée par influx nerveux, hormones, facteurs locaux ou composition du contenu luminal. Au microscope, on repère la lumière, les unités sécrétrices, les conduits et l’organisation des noyaux, mais la coloration seule ne prouve pas une fonction moléculaire précise. Le prélèvement et l’orientation tissulaire influencent l’aspect observé.'),
    ], trap: 'La classification endocrine/exocrine dépend de la voie de libération et de la présence d’un conduit, pas seulement de la nature du produit.', recall: 'Quelle différence fondamentale distingue une glande endocrine d’une glande exocrine ?', answer: 'La glande endocrine déverse ses hormones vers le milieu interstitiel et le sang sans conduit ; la glande exocrine évacue son produit par un conduit vers une surface ou une lumière.', source: '4-2-epithelial-tissue', glossary: [['Acinus', 'Unité glandulaire sécrétrice arrondie autour d’une petite lumière.'], ['Mérocrine', 'Sécrétion par exocytose sans perte significative de cytoplasme.'], ['Cellule caliciforme', 'Cellule épithéliale unicellulaire sécrétrice de mucus.']], caseStudy: { prompt: 'Une glande déverse une enzyme digestive dans la lumière intestinale par un réseau de conduits. De quel type général s’agit-il ?', answer: 'Une glande exocrine, dont le produit rejoint une lumière par un conduit.' } }),
  course('histo-connective-tissues', {
    objectives: ['Identifier cellules et matrice des tissus conjonctifs', 'Comparer tissu adipeux blanc et brun', 'Expliquer le rôle des fibres et de la substance fondamentale'],
    sections: [
      s('Une matrice extracellulaire abondante', 'Les tissus conjonctifs associent cellules dispersées, fibres et substance fondamentale extracellulaire. Les fibroblastes synthétisent plusieurs composants matriciels ; macrophages, mastocytes et autres cellules participent défense et remodelage. La composition varie selon l’organe et les forces mécaniques ou besoins de transport.'),
      s('Fibres et substance fondamentale', 'Les fibres de collagène résistent à la traction, les fibres élastiques permettent déformation et retour, et les fibres réticulaires forment des réseaux fins. La substance fondamentale contient glycosaminoglycanes, protéoglycanes et glycoprotéines d’adhérence, qui organisent hydratation, diffusion et interactions cellulaires. Les proportions déterminent des propriétés tissulaires distinctes.'),
      s('Tissu adipeux blanc', 'Les adipocytes blancs possèdent généralement une grande goutte lipidique, un noyau repoussé à la périphérie et un cytoplasme peu abondant. Ils stockent les triacylglycérols, libèrent des acides gras selon les besoins et sécrètent des adipokines. Le tissu adipeux joue aussi un rôle endocrine et contribue isolation, protection mécanique et réserve énergétique.'),
      s('Tissu adipeux brun', 'Les adipocytes bruns contiennent plusieurs petites gouttelettes lipidiques et de nombreuses mitochondries, d’où leur aspect plus coloré. La protéine découplante UCP1 dissipe le gradient de protons et permet une thermogenèse sans frisson. Le tissu brun est particulièrement développé chez le nouveau-né ; sa présence et son activité persistent à des degrés variables chez l’adulte.'),
      s('Réparation et inflammation', 'Les cellules conjonctives répondent aux lésions en recrutant cellules immunitaires, remodelant matrice et déposant collagène. Une cicatrice mature restaure une continuité mécanique mais ne reproduit pas toujours l’organisation fonctionnelle initiale. Fibrose, inflammation chronique et défaut de matrice perturbent les échanges et les propriétés des tissus.'),
    ], trap: 'Les adipocytes ne sont pas de simples cellules passives de stockage : ils sécrètent des médiateurs et influencent le métabolisme systémique.', recall: 'Quelle molécule permet au tissu adipeux brun de produire de la chaleur en découplant la phosphorylation oxydative ?', answer: 'UCP1, aussi appelée thermogénine, dissipe une partie du gradient protonique sous forme de chaleur.', source: '4-3-connective-tissue-supporting-tissues', glossary: [['Substance fondamentale', 'Partie hydratée non fibrillaire de la matrice extracellulaire.'], ['Adipokine', 'Médiateur sécrété par le tissu adipeux.'], ['UCP1', 'Protéine mitochondriale de découplage impliquée dans la thermogenèse du tissu brun.']], caseStudy: { prompt: 'Pourquoi une cicatrice peut-elle être mécaniquement solide mais moins fonctionnelle que le tissu initial ?', answer: 'Le dépôt de collagène restaure une continuité, mais l’architecture spécialisée, les cellules et les propriétés élastiques ou fonctionnelles peuvent ne pas être entièrement reconstituées.' } }),
]
const prompts: Record<string, string[]> = {
  'histo-blood-cells': ['Quels éléments composent les éléments figurés du sang ?', 'Quelle protéine plasmatique contribue fortement à la pression oncotique ?', 'Qu’est-ce qui distingue sérum et plasma ?', 'Quelle est la forme des globules rouges humains matures ?', 'De quelles cellules dérivent les plaquettes ?'],
  'histo-bone-architecture': ['Quel type cellulaire dépose l’ostéoïde ?', 'Quel type cellulaire résorbe l’os ?', 'Pourquoi le cartilage dépend-il de la diffusion pour sa nutrition ?', 'Quel composant organique majeur contribue à la résistance à la traction de l’os ?', 'Que désigne un ostéon ?'],
  'histo-glands-exocrine-endocrine': ['Une glande endocrine possède-t-elle un conduit excréteur ?', 'Quel mode de sécrétion utilise l’exocytose ?', 'Quel produit une cellule caliciforme sécrète-t-elle ?', 'Quel est le trajet général d’une sécrétion exocrine ?', 'À quoi correspond la sécrétion holocrine ?'],
  'histo-connective-tissues': ['Quelle fonction mécanique assure principalement le collagène ?', 'Quelle protéine découplante participe à la thermogenèse du tissu brun ?', 'Quel aspect lipidique caractérise souvent un adipocyte blanc ?', 'Citez un rôle endocrine du tissu adipeux.', 'Une cicatrice restaure-t-elle toujours l’architecture initiale ?'],
}
const answers: Record<string, string[]> = {
  'histo-blood-cells': ['Érythrocytes, leucocytes et plaquettes.', 'L’albumine, protéine majoritaire contribuant à la pression oncotique.', 'Le sérum est obtenu après coagulation et contient beaucoup moins de fibrinogène que le plasma.', 'Une forme biconcave, sans noyau.', 'Des fragments cytoplasmiques de mégacaryocytes.'],
  'histo-bone-architecture': ['L’ostéoblaste.', 'L’ostéoclaste.', 'Il est avasculaire et les nutriments diffusent dans sa matrice hydratée.', 'Le collagène de type I.', 'Une unité structurale concentrique de l’os compact.'],
  'histo-glands-exocrine-endocrine': ['Non, elle libère vers le milieu interstitiel puis le sang.', 'La sécrétion mérocrine.', 'Du mucus, qui protège et lubrifie les surfaces épithéliales.', 'Par un conduit vers une surface ou une lumière.', 'La libération du produit lors de la désintégration de la cellule sécrétrice.'],
  'histo-connective-tissues': ['Résister aux forces de traction.', 'UCP1, ou thermogénine.', 'Une grande goutte lipidique unique qui repousse le noyau vers la périphérie.', 'Il sécrète des adipokines qui modulent notamment métabolisme et signaux endocriniens.', 'Non, la cicatrice peut restaurer la continuité sans reconstituer la spécialisation d’origine.'],
}
const distractors = ['Elle est toujours formée d’un seul type de cellule.', 'Elle ne contient aucune matrice extracellulaire.', 'Elle se trouve exclusivement dans le système nerveux.', 'Elle n’a aucune fonction de transport ou de soutien.']
export const histologyQuestions: Question[] = histologyCourses.flatMap((c, ci) => prompts[c.id].map((prompt, qi) => {
  const answer = answers[c.id][qi]
  const options = [answer, distractors[(qi + ci) % 4], distractors[(qi + ci + 1) % 4], distractors[(qi + ci + 2) % 4]]
  return { id: `${c.id}-q${qi + 1}`, course: c.id, topic: c.category, prompt, options, correct: [0],
    why: options.map((option, oi) => oi === 0 ? answer : `${option} Cette proposition ne correspond pas à l’organisation tissulaire étudiée.`), difficulty: qi < 2 ? 'essentiel' as const : 'application' as const, format: 'single' as const }
}))
