import type { Course } from '../../curriculum'
import type { Question } from '../../questions'
import { canonicalCourses } from '../../taxonomy/canonicalCourses'

const metadata = new Map(canonicalCourses.filter(item => item.subject === 'Génétique & Biologie moléculaire').map(item => [item.id, item]))
const base = 'https://openstax.org/books/biology-2e/pages/'
type Draft = { objectives: string[]; sections: Course['sections']; trap: string; recall: string; answer: string; source: string; caseStudy: NonNullable<Course['caseStudy']>; glossary: NonNullable<Course['glossary']> }
const s = (title: string, text: string, bullets?: string[]) => ({ title, text, ...(bullets ? { bullets } : {}) })
function course(id: string, d: Draft): Course {
  const c = metadata.get(id)
  if (!c) throw new Error(`Chapitre canonique de génétique introuvable : ${id}`)
  return { id, title: c.title, category: c.subject, tag: c.module, minutes: 14, structure: null, objectives: d.objectives,
    sections: d.sections, trap: d.trap, recall: d.recall, answer: d.answer, source: base + d.source,
    sources: [{ label: 'OpenStax · Biology 2e', url: base + d.source }],
    prerequisites: ['Structure de l’ADN et des chromosomes', 'Cycle cellulaire et synthèse des protéines'], glossary: d.glossary, caseStudy: d.caseStudy,
    review: { status: 'unreviewed', updatedAt: '2026-09-23', sourcesUpdatedAt: '2026-09-23' } }
}
export const geneticsCourses: Course[] = [
  course('genetics-mendelian-inheritance', {
    objectives: ['Distinguer génotype et phénotype', 'Appliquer les lois de ségrégation à un croisement simple', 'Interpréter les limites d’un modèle mendélien'],
    sections: [
      s('Caractères, allèles et génotypes', 'Un gène peut exister sous plusieurs versions appelées allèles. Le génotype décrit les allèles d’un individu à un locus ; le phénotype désigne les caractères observables résultant du génotype et de son environnement. Un individu homozygote porte deux allèles identiques, hétérozygote deux allèles différents. Ces termes s’appliquent à un locus défini.'),
      s('Ségrégation des allèles', 'Lors de la méiose, les deux copies d’un locus se séparent et chaque gamète reçoit habituellement un seul allèle. À la fécondation, les contributions parentales se réunissent. Pour un hétérozygote Aa, les gamètes A et a sont produits en proportions égales dans le modèle sans distorsion de ségrégation.'),
      s('Dominance et croisement monohybride', 'Si A est dominant sur a dans un modèle complet, les génotypes AA et Aa partagent le phénotype dominant, tandis que aa exprime le phénotype récessif. Un croisement Aa × Aa donne les génotypes 1 AA : 2 Aa : 1 aa et un rapport phénotypique 3:1 sous les hypothèses classiques. Dominance ne signifie ni fréquence ni avantage.'),
      s('Assortiment indépendant', 'Deux paires d’allèles sur des chromosomes différents s’assortissent indépendamment en méiose, produisant des combinaisons équiprobables si les loci ne sont pas liés et si aucun biais n’intervient. Des gènes proches sur le même chromosome peuvent être transmis ensemble ; les crossing-over génèrent néanmoins des recombinants, dont la fréquence renseigne sur la distance génétique.'),
      s('Lire un arbre généalogique', 'La transmission autosomique dominante apparaît souvent sur plusieurs générations, tandis qu’une transmission récessive peut toucher des enfants de parents non atteints porteurs. Ces motifs orientent mais ne suffisent pas toujours : petite famille, pénétrance incomplète, phénocopies ou données manquantes brouillent les schémas. Toute interprétation doit préciser les hypothèses et probabilités.'),
    ], trap: 'Un allèle dominant n’est pas nécessairement fréquent, bénéfique ou plus « fort » au niveau moléculaire.', recall: 'Dans Aa × Aa avec dominance complète, quels sont les génotypes attendus et leurs proportions ?', answer: 'Un quart AA, la moitié Aa et un quart aa ; le rapport phénotypique est 3:1 si les hypothèses mendéliennes classiques sont respectées.', source: '12-3-laws-of-inheritance', glossary: [['Allèle', 'Version d’un locus génétique.'], ['Pénétrance', 'Proportion de porteurs d’un génotype qui expriment le phénotype associé.'], ['Locus', 'Position d’un gène ou marqueur sur un chromosome.']], caseStudy: { prompt: 'Deux parents non atteints ont un enfant atteint d’une maladie rare récessive autosomique. Quelle hypothèse simple explique ce cas ?', answer: 'Les parents peuvent être hétérozygotes porteurs ; chaque grossesse présente alors, sous les hypothèses usuelles, une probabilité de un quart d’enfant homozygote atteint.' } }),
  course('genetics-meiosis-recombination', {
    objectives: ['Définir liaison génétique et recombinaison', 'Interpréter une fréquence de recombinaison', 'Comprendre les limites de la cartographie génétique'],
    sections: [
      s('Des loci sur un même chromosome', 'Deux loci situés sur le même chromosome peuvent être transmis ensemble plus souvent que prévu par un assortiment indépendant. La liaison dépend de leur proximité : les loci proches ont moins de chances d’être séparés par un crossing-over. Le terme décrit une tendance statistique, pas une impossibilité absolue de recombinaison.'),
      s('Crossing-over en méiose', 'Durant la prophase I, des échanges entre chromatides non sœurs d’une paire d’homologues recombinent des segments. Un crossing-over entre deux loci peut produire des gamètes recombinants ; des échanges multiples peuvent masquer la recombinaison lorsqu’ils rétablissent la configuration parentale.'),
      s('Fréquence de recombinaison', 'La fréquence de recombinaison est le nombre de descendants recombinants divisé par le nombre total informatif. Elle varie entre 0 et 50 % : une fréquence proche de 50 % ne distingue pas toujours loci très éloignés et loci non liés. Pour des intervalles courts, un centimorgan correspond approximativement à 1 % de recombinants.'),
      s('Établir une carte', 'Dans un croisement test, l’hétérozygote est croisé avec un homozygote récessif afin que les classes de descendants reflètent les gamètes produits. Les classes parentales sont généralement plus nombreuses lorsque les loci sont liés ; les classes recombinantes permettent d’estimer leur distance génétique. Il faut un effectif suffisant et identifier les phénotypes sans ambiguïté.'),
      s('Carte génétique et chromosome réel', 'La distance en centimorgans n’est pas une longueur physique uniforme : les taux de crossing-over varient selon les régions, le sexe et les organismes. Les cartes sont utiles pour ordonner des loci et suivre leur co-ségrégation, mais ne remplacent pas le séquençage ni une mesure directe en paires de bases.'),
    ], trap: 'Une fréquence de recombinaison de 50 % ne prouve pas à elle seule que deux gènes sont sur des chromosomes différents.', recall: 'Un croisement test produit 18 % de descendants recombinants. Quelle estimation simple de distance génétique obtient-on ?', answer: 'Environ 18 cM pour l’intervalle court étudié, en gardant à l’esprit que les doubles crossing-over peuvent sous-estimer la distance réelle.', source: '15-1-the-chromosomal-theory-of-inheritance', glossary: [['Liaison', 'Co-transmission préférentielle de loci portés par le même chromosome.'], ['Recombinant', 'Combinaison allélique différente des combinaisons parentales.'], ['Centimorgan', 'Unité de carte correspondant approximativement à 1 % de recombinants dans un intervalle court.']], caseStudy: { prompt: 'Pourquoi deux gènes très éloignés sur un même chromosome peuvent-ils sembler indépendants ?', answer: 'Des crossing-over simples et multiples produisent jusqu’à environ 50 % de gamètes recombinants, valeur comparable à l’assortiment indépendant.' } }),
  course('genetics-translation-code', {
    objectives: ['Suivre l’information de l’ADN à la protéine', 'Distinguer transcription et traduction', 'Expliquer maturation et contrôle de l’expression eucaryote'],
    sections: [
      s('Le flux de l’information', 'Un gène est transcrit en ARN par une ARN polymérase ; certains ARN, comme les ARNm, sont ensuite traduits par les ribosomes en polypeptides. L’expression comprend transcription, maturation, localisation, traduction et devenir de la protéine. Tous les gènes ne codent pas une protéine : des ARN fonctionnels ont un rôle structural ou régulateur.'),
      s('Transcription', 'L’ARN polymérase lit le brin matrice d’ADN en sens 3′ vers 5′ et synthétise un ARN 5′ vers 3′. La séquence de l’ARN ressemble au brin codant, avec l’uracile à la place de la thymine. Des promoteurs et facteurs de transcription déterminent le recrutement et l’activité de la machinerie.'),
      s('Maturation de l’ARNm eucaryote', 'Le pré-ARNm reçoit une coiffe en 5′ et une queue poly-A en 3′ ; l’épissage retire les introns et relie les exons. L’épissage alternatif permet plusieurs ARNm à partir d’un même transcrit primaire, selon le type cellulaire ou les signaux. La maturation influence stabilité, export nucléaire et traduction.'),
      s('Code génétique et traduction', 'Le ribosome lit l’ARNm par groupes de trois nucléotides, les codons. Les ARNt apportent les acides aminés correspondants via un anticodon et sont chargés par des aminoacyl-ARNt synthétases. La traduction progresse de l’extrémité N vers C du polypeptide, commence à un codon initiateur et se termine sur un codon stop reconnu par un facteur de relargage.'),
      s('Réguler et contrôler', 'L’expression peut être contrôlée par accessibilité de la chromatine, facteurs de transcription, stabilité de l’ARN, microARN, efficacité de traduction ou dégradation des protéines. Des contrôles qualité retiennent certains ARN ou polypeptides aberrants. Une mutation peut affecter l’abondance, la séquence, le repliement ou la localisation, avec un effet dépendant du contexte.'),
    ], trap: 'L’ARN polymérase synthétise l’ARN 5′ vers 3′ tout en lisant le brin matrice dans le sens opposé.', recall: 'Quelle différence entre brin matrice et brin codant permet d’interpréter une séquence d’ARN ?', answer: 'L’ARN est complémentaire et antiparallèle au brin matrice, mais partage la séquence du brin codant en remplaçant T par U.', source: '15-4-rna-processing-in-eukaryotes', glossary: [['Épissage', 'Retrait des introns et jonction des exons dans un transcrit.'], ['Codon', 'Triplet de nucléotides de l’ARNm lu lors de la traduction.'], ['Aminoacyl-ARNt synthétase', 'Enzyme qui charge un ARNt avec son acide aminé correspondant.']], caseStudy: { prompt: 'Une mutation touche le site d’épissage d’un intron. Quel type de conséquence moléculaire est possible ?', answer: 'Rétention d’intron ou jonction anormale d’exons, pouvant modifier le cadre de lecture, introduire un stop prématuré ou changer la quantité d’ARNm.' } }),
  course('genetics-dna-repair-pathways', {
    objectives: ['Classer mutations ponctuelles et chromosomiques', 'Relier mutation et conséquence protéique possible', 'Décrire les grandes catégories de réparation de l’ADN'],
    sections: [
      s('Sources de variation de séquence', 'Les mutations apparaissent spontanément lors de réplication ou sous l’effet d’agents endogènes et environnementaux. Une substitution remplace une base ; une insertion ou délétion ajoute ou retire des bases. Les mutations germinales peuvent être transmises à la descendance, tandis que les mutations somatiques se propagent au sein d’un clone cellulaire.'),
      s('Conséquences sur une séquence codante', 'Une substitution peut être silencieuse, faux-sens ou non-sens selon son effet sur le codon. Une insertion ou délétion d’un nombre de bases non multiple de trois décale souvent le cadre de lecture, alors qu’un multiple de trois ajoute ou supprime des acides aminés sans décalage global. L’effet réel dépend du gène et du contexte.'),
      s('Réparation des mésappariements', 'La réparation des mésappariements corrige des erreurs de réplication qui échappent à la relecture. Le système identifie le brin nouvellement synthétisé, retire le segment contenant l’erreur, puis resynthétise et ligature l’ADN. Une défaillance augmente le taux de mutations et peut contribuer à l’instabilité génomique.'),
      s('Réparation par excision', 'La réparation par excision de base retire certaines bases endommagées grâce à une glycosylase, puis restaure le site. L’excision de nucléotides élimine un oligonucléotide contenant une lésion volumineuse qui déforme l’hélice, comme certains dimères induits par les UV. La resynthèse remplit la lacune en utilisant le brin intact comme modèle.'),
      s('Cassures double brin et interprétation', 'Les cassures double brin peuvent être réparées par recombinaison homologue, généralement fidèle si une chromatide sœur est disponible, ou par jonction d’extrémités non homologues, plus rapide mais parfois mutagène. Une mutation détectée n’est pas automatiquement pathogène : fréquence, ségrégation, fonction et données cliniques sont nécessaires à l’interprétation.'),
    ], trap: 'Une mutation silencieuse au niveau protéique peut tout de même affecter épissage, stabilité ou traduction de l’ARN.', recall: 'Quelle réparation cible une lésion volumineuse déformant la double hélice ?', answer: 'La réparation par excision de nucléotides retire un segment contenant la lésion, puis l’ADN est resynthétisé et ligaturé.', source: '14-5-dna-repair', glossary: [['Faux-sens', 'Substitution modifiant un acide aminé codé.'], ['Décalage du cadre', 'Changement de regroupement des codons après insertion ou délétion non multiple de trois.'], ['Recombinaison homologue', 'Réparation utilisant une séquence homologue, souvent la chromatide sœur, comme matrice.']], caseStudy: { prompt: 'Une délétion de deux nucléotides se produit au début d’un exon codant. Quel effet est particulièrement probable ?', answer: 'Un décalage du cadre de lecture, pouvant changer de nombreux codons en aval et introduire un codon stop prématuré.' } }),
]
const prompts: Record<string, string[]> = {
  'genetics-mendelian-inheritance': ['Que décrit le génotype ?', 'Lors de la méiose, que devient chaque paire d’allèles d’un locus ?', 'Dans Aa × Aa, quelle proportion attendue est aa ?', 'Un allèle dominant est-il forcément fréquent ?', 'Que signifie pénétrance ?'],
  'genetics-meiosis-recombination': ['Pourquoi deux loci proches sont-ils plus souvent transmis ensemble ?', 'Quel événement produit des chromatides recombinantes ?', 'À quoi correspond approximativement 1 cM pour un intervalle court ?', 'Que suggère environ 50 % de recombinants ?', 'Un croisement test sert principalement à observer quoi ?'],
  'genetics-translation-code': ['Dans quel sens l’ARN est-il synthétisé ?', 'Quel brin d’ADN est complémentaire à l’ARN ?', 'Que retire l’épissage du pré-ARNm ?', 'Combien de nucléotides comporte un codon ?', 'Quelle enzyme charge un ARNt ?'],
  'genetics-dna-repair-pathways': ['Qu’est-ce qu’une mutation faux-sens ?', 'Pourquoi une insertion d’une base peut-elle fortement modifier une protéine ?', 'Quel système corrige des erreurs échappant à la relecture de réplication ?', 'Quelle réparation retire des lésions volumineuses déformant l’hélice ?', 'La détection d’une variante suffit-elle à établir sa pathogénicité ?'],
}
const answers: Record<string, string[]> = {
  'genetics-mendelian-inheritance': ['La combinaison d’allèles d’un individu à un locus donné.', 'Elles se séparent, chaque gamète recevant habituellement un allèle.', 'Un quart, selon les hypothèses mendéliennes usuelles.', 'Non ; dominance décrit une relation phénotypique dans un génotype hétérozygote.', 'La proportion de porteurs du génotype qui expriment le phénotype associé.'],
  'genetics-meiosis-recombination': ['Un crossing-over a moins de probabilité de se produire entre eux.', 'Un crossing-over entre chromatides non sœurs en prophase I.', 'Environ 1 % de descendants recombinants.', 'Une absence apparente de liaison ou des loci très éloignés, sans les distinguer à elle seule.', 'Les gamètes produits par l’hétérozygote à partir des phénotypes des descendants.'],
  'genetics-translation-code': ['Dans le sens 5′ vers 3′.', 'Le brin matrice, lu en sens antiparallèle.', 'Les introns, en reliant les exons.', 'Trois nucléotides.', 'Une aminoacyl-ARNt synthétase.'],
  'genetics-dna-repair-pathways': ['Une substitution qui change l’acide aminé codé.', 'Elle décale le cadre et modifie les codons en aval.', 'La réparation des mésappariements.', 'La réparation par excision de nucléotides.', 'Non, il faut des données génétiques, fonctionnelles et cliniques pour l’interpréter.'],
}
const distractors = ['Elle copie directement une protéine à partir de l’ADN.', 'Elle modifie toujours tous les tissus de la même manière.', 'Elle dépend uniquement du nombre de chromosomes.', 'Elle supprime toute variation génétique de la population.']
export const geneticsQuestions: Question[] = geneticsCourses.flatMap((c, ci) => prompts[c.id].map((prompt, qi) => {
  const answer = answers[c.id][qi]
  const options = [answer, distractors[(qi + ci) % 4], distractors[(qi + ci + 1) % 4], distractors[(qi + ci + 2) % 4]]
  return { id: `${c.id}-q${qi + 1}`, course: c.id, topic: c.category, prompt, options, correct: [0],
    why: options.map((option, oi) => oi === 0 ? answer : `${option} Cette réponse ne décrit pas le mécanisme demandé.`), difficulty: qi < 2 ? 'essentiel' as const : 'application' as const, format: 'single' as const }
}))
