import type { Course } from '../../curriculum'
import type { Question } from '../../questions'
import { canonicalCourses } from '../../taxonomy/canonicalCourses'

const metadata = new Map(canonicalCourses.filter(item => item.subject === 'Immunologie').map(item => [item.id, item]))
const base = 'https://openstax.org/books/microbiology/pages/'
type Draft = { objectives: string[]; sections: Course['sections']; trap: string; recall: string; answer: string; source: string; caseStudy: NonNullable<Course['caseStudy']>; glossary: NonNullable<Course['glossary']> }
const s = (title: string, text: string, bullets?: string[]) => ({ title, text, ...(bullets ? { bullets } : {}) })
function course(id: string, d: Draft): Course {
  const c = metadata.get(id)
  if (!c) throw new Error(`Chapitre canonique d’immunologie introuvable : ${id}`)
  return { id, title: c.title, category: c.subject, tag: c.module, minutes: 14, structure: null,
    objectives: d.objectives, sections: d.sections, trap: d.trap, recall: d.recall, answer: d.answer,
    source: base + d.source, sources: [{ label: 'OpenStax · Microbiology', url: base + d.source }],
    prerequisites: ['Cellules et médiateurs de l’immunité', 'Notions d’antigène et de reconnaissance moléculaire'],
    glossary: d.glossary, caseStudy: d.caseStudy, review: { status: 'unreviewed', updatedAt: '2026-09-23', sourcesUpdatedAt: '2026-09-23' } }
}
export const immunologyCourses: Course[] = [
  course('immuno-innate', {
    objectives: ['Identifier les barrières de l’immunité innée', 'Expliquer la reconnaissance par les PRR', 'Relier inflammation et recrutement cellulaire'],
    sections: [
      s('Une défense rapide et distribuée', 'L’immunité innée répond rapidement à des motifs associés aux microbes ou aux dommages tissulaires. Elle comprend les barrières épithéliales, des protéines solubles et des cellules sentinelles ou effectrices. Elle ne requiert pas de rencontre préalable avec un antigène et contribue à orienter la réponse adaptative.'),
      s('Barrières physiques et chimiques', 'La peau forme une barrière kératinisée et les muqueuses utilisent jonctions cellulaires, mucus et clairance mécanique. Acidité gastrique, enzymes, peptides antimicrobiens et microbiote limitent la colonisation. Une barrière ne fonctionne pas seule : son renouvellement, son hydratation et les comportements mécaniques comme le battement ciliaire participent à sa protection.'),
      s('Reconnaissance par les PRR', 'Les récepteurs de reconnaissance de motifs détectent des structures conservées de microbes, les PAMP, et des signaux de dommage, les DAMP. Les récepteurs TLR, NLR et autres familles sont exprimés selon les cellules et compartiments. Leur activation déclenche des voies de signalisation qui produisent cytokines, chimiokines et médiateurs antimicrobiens.'),
      s('Inflammation locale', 'Vasodilatation et augmentation de perméabilité facilitent l’arrivée de protéines plasmatiques et de leucocytes. Les chimiokines guident le recrutement ; neutrophiles et monocytes traversent l’endothélium puis phagocytent ou libèrent des molécules effectrices. Rougeur, chaleur, douleur et œdème résultent de mécanismes locaux et n’identifient pas à eux seuls une cause infectieuse.'),
      s('Complément et cellules effectrices', 'Le complément est activé par plusieurs voies et converge vers le dépôt de C3b, l’inflammation et, pour certaines cibles, la formation du complexe d’attaque membranaire. Macrophages, neutrophiles, cellules NK et dendritiques ont des fonctions distinctes. Les cellules dendritiques relient détection innée et activation de lymphocytes en présentant des antigènes dans un contexte de co-stimulation.'),
    ], trap: 'L’immunité innée reconnaît des motifs et contextes de danger ; elle ne signifie pas une absence totale de spécificité moléculaire.', recall: 'Que détectent les PRR et quelles réponses peuvent-ils déclencher ?', answer: 'Ils reconnaissent des PAMP microbiens ou DAMP liés à des dommages, activant notamment cytokines, chimiokines, inflammation et fonctions antimicrobiennes.', source: '17-1-overview-of-the-immune-system', glossary: [['PAMP', 'Motif moléculaire conservé associé à des microorganismes.'], ['DAMP', 'Signal moléculaire libéré ou exposé lors de dommages cellulaires.'], ['PRR', 'Récepteur inné détectant des motifs microbiens ou de dommage.']], caseStudy: { prompt: 'Une bactérie franchit un épithélium et active des cellules sentinelles. Quel type de signaux facilite le recrutement des neutrophiles ?', answer: 'Les chimiokines produites localement établissent des signaux de recrutement et de chimiotactisme ; les molécules endothéliales favorisent adhésion et transmigration.' } }),
  course('immuno-adaptive', {
    objectives: ['Distinguer fonctions des lymphocytes B et T', 'Expliquer sélection clonale et mémoire', 'Décrire la présentation de l’antigène par CMH I et II'],
    sections: [
      s('Spécificité et clones', 'L’immunité adaptative repose sur des récepteurs diversifiés des lymphocytes B et T. Chaque clone exprime un récepteur de spécificité donnée ; la sélection et l’expansion clonales augmentent les cellules capables de répondre à l’antigène. Après la réponse, des cellules mémoire persistent et réagissent plus rapidement lors d’une exposition ultérieure.'),
      s('Lymphocytes B et anticorps', 'Un lymphocyte B reconnaît directement certaines formes natives d’antigène via son récepteur. Avec l’aide de lymphocytes T auxiliaires dans de nombreuses réponses, il prolifère et se différencie en plasmocytes producteurs d’anticorps et cellules mémoire. Les anticorps neutralisent, opsonisent ou activent le complément ; leurs fonctions varient selon la classe.'),
      s('Lymphocytes T et présentation', 'Les lymphocytes T reconnaissent un peptide présenté par une molécule du complexe majeur d’histocompatibilité. Le CMH I présente surtout des peptides issus de protéines cytosoliques aux T CD8 ; le CMH II présente surtout des antigènes internalisés aux T CD4. Ces règles générales comportent des mécanismes spécialisés, comme la présentation croisée.'),
      s('Activation et co-stimulation', 'La reconnaissance du complexe peptide-CMH est un signal nécessaire mais souvent insuffisant. Les cellules présentatrices professionnelles fournissent co-stimulation et cytokines, qui orientent prolifération et différenciation. L’absence de signaux adéquats peut entraîner anergie ou tolérance plutôt qu’une activation complète, ce qui participe à prévenir des réponses inappropriées.'),
      s('Réponse et mémoire', 'Les T CD4 coordonnent d’autres cellules par cytokines ; les T CD8 peuvent tuer des cellules infectées ou anormales. La réponse primaire comporte une phase de latence puis expansion ; des plasmocytes à longue durée de vie et lymphocytes mémoire persistent. La mémoire améliore souvent rapidité et ampleur sans garantir une protection absolue contre toute variante d’agent.'),
    ], trap: 'Le lymphocyte T ne reconnaît généralement pas l’antigène soluble natif : son récepteur reconnaît un peptide associé au CMH.', recall: 'Quel couple CMH / sous-population T associer aux peptides cytosoliques ?', answer: 'Le CMH I présente surtout des peptides cytosoliques aux lymphocytes T CD8.', source: '17-4-adaptive-immunity', glossary: [['Sélection clonale', 'Expansion des lymphocytes portant un récepteur adapté à l’antigène rencontré.'], ['Opsonisation', 'Marquage d’une cible facilitant sa phagocytose.'], ['Co-stimulation', 'Signal supplémentaire nécessaire à l’activation complète de nombreux lymphocytes T.']], caseStudy: { prompt: 'Une cellule infectée présente un peptide viral sur CMH I. Quelle population lymphocytaire peut reconnaître ce complexe ?', answer: 'Les lymphocytes T CD8, qui peuvent ensuite exercer une fonction cytotoxique après activation appropriée.' } }),
  course('immuno-clinical', {
    objectives: ['Comparer immunisation active et passive', 'Distinguer détection d’anticorps et d’antigène', 'Interpréter limites d’une sérologie selon le délai'],
    sections: [
      s('Immunisation active', 'La vaccination expose le système immunitaire à un antigène ou à son information sans reproduire nécessairement la maladie. Elle active des lymphocytes spécifiques et peut créer des cellules mémoire. La réponse dépend de la plateforme, du schéma, de l’âge, de l’immunité de départ et des rappels ; protection individuelle et réduction de transmission ne sont pas identiques.'),
      s('Immunisation passive', 'Une immunisation passive fournit directement des anticorps ou immunoglobulines. La protection peut être immédiate mais décroît au cours du temps et ne crée généralement pas la même mémoire immunitaire. Les indications, produits, risques et durées varient ; une décision clinique relève des recommandations en vigueur et du contexte individuel.'),
      s('Antigènes et anticorps en sérologie', 'Un test peut détecter un antigène du microorganisme, des anticorps de l’hôte ou un autre marqueur. Un résultat positif indique uniquement que le seuil et la cible du test sont satisfaits dans les conditions de validation. Sensibilité, spécificité, prévalence et fenêtre diagnostique influencent l’interprétation.'),
      s('Fenêtre et cinétique', 'Après une infection ou vaccination, les marqueurs apparaissent et évoluent selon des délais distincts. Un test d’anticorps négatif trop tôt n’exclut pas toujours une exposition récente ; un anticorps persistant ne prouve pas nécessairement une infection active. Répéter, associer plusieurs marqueurs ou utiliser une méthode directe peut être indiqué selon la question clinique.'),
      s('Faux résultats et décision', 'Réactions croisées, prélèvement, traitement, immunodépression et caractéristiques de population peuvent modifier les performances. La valeur prédictive positive dépend de la probabilité prétest : un même test peut avoir des implications différentes selon le contexte. Aucun résultat sérologique isolé ne remplace l’interprétation clinique ni le conseil professionnel.'),
    ], trap: 'Un anticorps détecté ne signifie pas toujours une infection active : il peut persister après guérison ou vaccination.', recall: 'Quelle différence entre immunisation active et passive concernant la mémoire ?', answer: 'L’immunisation active stimule la réponse propre et peut créer une mémoire ; l’immunisation passive apporte des anticorps préformés, agit rapidement mais ne crée généralement pas la même mémoire.', source: '17-5- adaptive-immune-response', glossary: [['Immunisation active', 'Stimulation de la réponse immunitaire propre par un antigène ou une vaccination.'], ['Immunisation passive', 'Apport direct d’anticorps préformés.'], ['Fenêtre sérologique', 'Période durant laquelle un marqueur peut ne pas encore être détectable.']], caseStudy: { prompt: 'Une sérologie est négative quelques jours après une exposition suspectée. Pourquoi ce résultat peut-il être insuffisant ?', answer: 'Les anticorps peuvent ne pas avoir atteint le seuil de détection ; il faut tenir compte du délai, du test, de la probabilité prétest et des autres méthodes disponibles.' } }),
]
const prompts: Record<string, string[]> = {
  'immuno-innate': ['Que détectent les récepteurs PRR ?', 'Quelle cellule peut relier immunité innée et activation adaptative par présentation antigénique ?', 'Quel médiateur guide le chimiotactisme des leucocytes ?', 'Le complément participe-t-il à l’opsonisation ?', 'L’inflammation prouve-t-elle à elle seule une infection ?'],
  'immuno-adaptive': ['Que reconnaît le récepteur d’un lymphocyte T ?', 'Quel couple associer au CMH I ?', 'Quelles cellules produisent des anticorps ?', 'Quel processus augmente les lymphocytes spécifiques après exposition ?', 'La mémoire immunitaire assure-t-elle une protection absolue contre toute variante ?'],
  'immuno-clinical': ['Quelle forme d’immunisation tend à créer une mémoire ?', 'L’immunisation passive fournit-elle des anticorps préformés ?', 'Un anticorps positif démontre-t-il toujours une infection active ?', 'Que peut signifier une sérologie négative très précoce ?', 'De quoi dépend la valeur prédictive positive d’un test ?'],
}
const answers: Record<string, string[]> = {
  'immuno-innate': ['Des motifs microbiens conservés et des signaux de dommage, PAMP et DAMP.', 'La cellule dendritique.', 'Les chimiokines.', 'Oui, C3b peut opsoniser des cibles.', 'Non, elle peut avoir plusieurs causes et s’interprète dans son contexte.'],
  'immuno-adaptive': ['Un peptide présenté par une molécule du CMH.', 'CMH I et lymphocyte T CD8.', 'Les plasmocytes issus de lymphocytes B activés.', 'La sélection et l’expansion clonales.', 'Non, une protection peut diminuer ou varier selon les antigènes et les personnes.'],
  'immuno-clinical': ['L’immunisation active, qui stimule les lymphocytes et la mémoire.', 'Oui, elle apporte directement des immunoglobulines.', 'Non, il peut persister après une infection résolue ou une vaccination.', 'Les anticorps peuvent ne pas être encore détectables pendant la fenêtre sérologique.', 'De la sensibilité, spécificité et probabilité prétest ou prévalence dans la population testée.'],
}
const distractors = ['Elle est identique à toutes les autres réponses immunitaires.', 'Elle se produit sans cellule ni médiateur soluble.', 'Elle supprime nécessairement toute mémoire immunitaire.', 'Elle est indépendante du délai entre exposition et prélèvement.']
export const immunologyQuestions: Question[] = immunologyCourses.flatMap((c, ci) => prompts[c.id].map((prompt, qi) => {
  const answer = answers[c.id][qi]
  const options = [answer, distractors[(qi + ci) % 4], distractors[(qi + ci + 1) % 4], distractors[(qi + ci + 2) % 4]]
  return { id: `${c.id}-q${qi + 1}`, course: c.id, topic: c.category, prompt, options, correct: [0],
    why: options.map((option, oi) => oi === 0 ? answer : `${option} Cette proposition ne décrit pas le principe immunologique interrogé.`), difficulty: qi < 2 ? 'essentiel' as const : 'application' as const, format: 'single' as const }
}))
