import{test,expect}from'@playwright/test'
const password='Flashcards-test-solide-2026'
async function register(page:any){await page.goto('/#tab=flashcards');await page.getByRole('button',{name:'Mon compte',exact:true}).click();await page.getByRole('button',{name:'Créer un compte',exact:true}).click();await page.getByLabel('Prénom ou pseudonyme').fill('Lina');await page.getByLabel('Adresse e-mail').fill(`flash-${crypto.randomUUID()}@example.test`);await page.getByLabel('Mot de passe',{exact:true}).fill(password);await page.getByRole('button',{name:'Créer mon compte',exact:true}).click();await page.getByRole('button',{name:'J’ai conservé mon code'}).click();await page.getByRole('button',{name:'Fermer le profil'}).click()}

test('flashcards : deck, carte manuelle, génération en brouillon et révision persistante',async({page})=>{
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await register(page)
 await page.getByRole('button',{name:'Mes decks'}).click();await page.getByLabel('Nom du nouveau deck').fill('Cardiologie');await page.getByRole('button',{name:'Créer un deck'}).click();await expect(page.getByRole('heading',{name:'Cardiologie'})).toBeVisible()
 await page.getByRole('button',{name:'Toutes mes cartes'}).click();await page.getByRole('button',{name:'Nouvelle carte'}).click();await page.getByLabel('Recto').fill('Quelle est la formule du débit cardiaque ?');await page.getByLabel('Verso').fill('DC = fréquence cardiaque × volume d’éjection systolique.');await page.getByLabel(/Matière/).fill('Physiologie');await page.getByLabel('Tags séparés par des virgules').fill('cœur, formule');await page.getByRole('button',{name:'Enregistrer'}).click();await expect(page.getByText('Quelle est la formule du débit cardiaque ?')).toBeVisible()
 await page.getByRole('button',{name:'Aujourd’hui'}).click();const text='Le nœud sinusal assure normalement le rythme du cœur. Le débit cardiaque est le produit de la fréquence cardiaque par le volume d’éjection systolique. La pression artérielle dépend du débit cardiaque et des résistances périphériques.';await page.getByLabel('Texte à transformer en flashcards').fill(text);await page.getByRole('button',{name:'Générer des flashcards'}).click();await page.getByRole('button',{name:'Générer les brouillons'}).click();await expect(page.getByText(/carte\(s\) sélectionnée\(s\)/)).toBeVisible();await page.getByLabel('Deck de destination').selectOption({label:'Cardiologie'});await page.getByRole('button',{name:'Enregistrer la sélection'}).click()
 await expect(page.locator('.flash-hero-score strong')).toHaveText(/[2-9]/);await page.getByRole('button',{name:'Commencer'}).click();await expect(page.getByText('RECTO')).toBeVisible();await page.getByRole('button',{name:'Afficher la réponse'}).click();await page.getByRole('button',{name:/Correct/}).click();await page.reload();await expect(page.getByRole('button',{name:'Flashcards'})).toHaveAttribute('aria-pressed','true');await page.setViewportSize({width:393,height:852});await expect(page.getByText('Générer depuis un texte')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(393);expect(errors).toEqual([])
})

test('un cours MyCorpus ouvre toujours un aperçu avant enregistrement',async({page})=>{
 await register(page);await page.goto('/#tab=cours&cours=FMA7088');await page.getByRole('button',{name:'Générer des flashcards'}).click();await expect(page.getByRole('dialog',{name:'Générer des flashcards'})).toBeVisible();await expect(page.getByText('GÉNÉRATION EN BROUILLON')).toBeVisible();await expect(page.getByText('Tout sélectionner')).toBeVisible();await page.getByRole('button',{name:'Fermer'}).click()
})
