import {expect,test} from '@playwright/test'
const state=(page:any)=>page.evaluate(()=>(window as any).__CORPUS_TEST__.state())
const loaded=async(page:any)=>{await expect(page.locator('main')).toHaveAttribute('data-loaded','true',{timeout:90000})}
const ready=async(page:any)=>{await page.goto('/');await loaded(page)}

test('API contextuelle : commandes, cours, erreurs et validation',async({request})=>{
 const ask=(body:unknown)=>request.post('/api/chat',{data:body})
 expect((await request.get('/api/status')).status()).toBe(200)
 const command=await ask({message:'Montre-moi le pancréas',learning_level:'student'})
 expect((await command.json()).actions).toEqual([{action:'focus_structure',structure:'FMA7198'}])
 const course=await ask({message:'Pourquoi le ventricule gauche est plus épais ?',selected_structure:'FMA7088',learning_level:'advanced'})
 expect((await course.json()).message).toMatch(/pression/)
 expect((await ask(null)).status()).toBe(400)
 expect((await ask({message:'Bonjour',selected_structure:'intrus',learning_level:'student'})).status()).toBe(400)
 expect((await request.get('/api/chat')).status()).toBe(405)
 expect((await ask({message:'a'.repeat(22000),learning_level:'student'})).status()).toBe(413)
})

test('coupe, repères, opacité et restauration exacte de la caméra',async({page})=>{
 await ready(page)
 await page.getByRole('button',{name:'Outils d’exploration',exact:true}).click()
 await page.getByLabel('Étiquettes anatomiques').selectOption('names')
 await expect(page.locator('.anatomy-label:visible').first()).toBeVisible()
 await page.getByLabel('Activer la coupe',{exact:true}).check()
 await page.getByLabel('Plan de coupe',{exact:true}).selectOption('y')
 await page.getByLabel('Position de coupe',{exact:true}).fill('35')
 await page.getByLabel('Opacité Squelette',{exact:true}).fill('0')
 await expect.poll(async()=> (await state(page)).opacity.skeleton).toBe(0)
 expect((await state(page)).cut.axis).toBe('y')
 await page.getByRole('button',{name:'Inverser le côté conservé'}).click()
 await page.waitForTimeout(1300)
 const before=await state(page)
 await page.getByRole('button',{name:'Partager cette vue exacte'}).click()
 await expect(page).toHaveURL(/view=/)
 const url=page.url()
 await page.goto(url);await loaded(page);await page.waitForTimeout(1400)
 const after=await state(page)
 expect(after.cut).toEqual(before.cut);expect(after.opacity).toEqual(before.opacity);expect(after.labels).toBe('names')
 for(let i=0;i<3;i++)expect(after.camera[i]).toBeCloseTo(before.camera[i],3)
 await page.screenshot({path:'tests/artifacts/study-cut.png'})
})

test('cours séparés, rappel actif, pathologies et progression locale',async({page})=>{
 await page.goto('/#structure=FMA7088');await loaded(page)
 await page.getByRole('button',{name:'Apprendre cette structure'}).click()
 await expect(page.locator('.courses-workspace')).toBeVisible()
 await expect(page.locator('.stage')).not.toBeVisible()
 await expect(page.locator('.course-article')).toContainText('pression')
 await page.getByRole('button',{name:'Vérifier ma réponse'}).click()
 await expect(page.locator('.recall-answer')).toBeVisible()
 await page.getByRole('button',{name:'Infarctus du myocarde'}).click()
 await expect(page.locator('.disease-reading>section')).toHaveCount(6)
 await page.getByRole('button',{name:'Marquer ce cours terminé'}).click()
 await expect(page.getByRole('button',{name:'Cours terminé',exact:true})).toBeDisabled()
 await page.reload();await expect(page.locator('.course-article')).toBeVisible()
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('corpus-completed')||'[]'))).toContain('FMA7088')
})

test('quiz : réponse sur une structure réelle, indice et bilan',async({page})=>{
 await ready(page);await page.getByRole('button',{name:'Entraînement',exact:true}).click();await page.getByRole('button',{name:/Reconnaissance 3D/}).click();await loaded(page)
 await expect(page.getByRole('combobox')).toBeDisabled()
 await page.waitForTimeout(1400)
 const point=await page.evaluate(()=>(window as any).__CORPUS_TEST__.project('FMA7197'))
 await page.mouse.click(point.x,point.y)
 await expect(page.locator('.quiz-feedback')).toContainText('Exact !')
 await page.getByRole('button',{name:'Question suivante'}).click()
 await page.getByRole('button',{name:'Un indice'}).click();await expect(page.locator('.quiz-hint')).toBeVisible()
 for(let i=1;i<10;i++){
   await page.getByRole('button',{name:'Voir la réponse',exact:true}).click()
   await page.getByRole('button',{name:i===9?'Voir mon bilan':'Question suivante',exact:true}).click()
 }
 await expect(page.locator('.quiz-score')).toHaveText('1 / 10')
})

test('assistant : sélection et isolation effectives dans la scène',async({page})=>{
 await ready(page)
 const input=page.locator('.chat-composer input')
 await input.fill('Montre-moi le pancréas');await input.press('Enter')
 await expect(page.locator('main')).toHaveAttribute('data-selected','FMA7198')
 await expect(page.locator('.chat-message.assistant').last()).toContainText('mise à jour')
 await input.fill('Isole le pancréas');await input.press('Enter')
 await expect(page.getByRole('button',{name:'Voir le contexte',exact:true,includeHidden:true})).toHaveAttribute('aria-pressed','true')
 await page.waitForTimeout(1400)
 await page.screenshot({path:'tests/artifacts/study-chat.png'})
})

test('mobile : apprentissage et outils gardent une scène visible sans débordement',async({page})=>{
 await page.setViewportSize({width:375,height:667});await ready(page)
 await page.getByRole('button',{name:'Cours',exact:true}).click()
 await expect(page.locator('.courses-workspace')).toBeVisible()
 await expect(page.locator('.stage')).not.toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(375)
 await page.waitForTimeout(1400)
 await page.screenshot({path:'tests/artifacts/study-mobile-learning.png'})
 await page.getByRole('button',{name:'Atlas 3D',exact:true}).click()
 await page.getByRole('button',{name:'Outils d’exploration',exact:true}).click()
 await expect(page.locator('.tools-panel')).toBeVisible()
 expect((await page.locator('.stage').boundingBox())!.height).toBeGreaterThan(70)
 await page.waitForTimeout(1400)
 await page.screenshot({path:'tests/artifacts/study-mobile-tools.png'})
})

test('systèmes combinables et sélection limitée à la portion conservée',async({page})=>{
 await ready(page)
 await page.getByRole('button',{name:'Systèmes',exact:true}).click()
 await page.getByRole('switch',{name:'Système Digestif',exact:true}).click();await loaded(page)
 const digestive=(await state(page)).visibleMeshes
 expect(digestive).toBeGreaterThan(5);expect(digestive).toBeLessThan(150)
 await page.getByRole('switch',{name:'Système Urinaire',exact:true}).click();await loaded(page)
 expect((await state(page)).visibleMeshes).toBeGreaterThan(digestive)
 await page.getByRole('button',{name:'Vue squelette',exact:true}).click();await loaded(page);await page.waitForTimeout(1300)
 const point=await page.evaluate(()=>(window as any).__CORPUS_TEST__.project('FMA24474'))
 expect(await page.evaluate(p=>(window as any).__CORPUS_TEST__.pick(p.x,p.y),point)).toBe('FMA24474')
 await page.getByRole('button',{name:'Outils d’exploration',exact:true}).click()
 await page.getByLabel('Activer la coupe',{exact:true}).check()
 await page.getByLabel('Plan de coupe',{exact:true}).selectOption('y')
 await page.getByLabel('Position de coupe',{exact:true}).fill('90')
 expect(await page.evaluate(p=>(window as any).__CORPUS_TEST__.pick(p.x,p.y),point)).toBe(null)
})

test('animation réversible et révélation d’un ensemble masqué par un système',async({page})=>{
 await ready(page)
 await page.getByRole('button',{name:'Systèmes',exact:true}).click()
 await page.getByRole('switch',{name:'Système Digestif',exact:true}).click();await loaded(page)
 const input=page.locator('.chat-composer input')
 await input.fill('Isole le cœur');await input.press('Enter');await loaded(page)
 await expect(page.locator('main')).toHaveAttribute('data-selected','FMA7088')
 await expect.poll(async()=>(await state(page)).visibleMeshes).toBeGreaterThan(1)
 await page.getByRole('button',{name:'Fermer la conversation'}).click()
 await page.getByRole('button',{name:'Battement illustratif',exact:true}).click()
 await expect.poll(async()=> (await state(page)).animatedScales.some((s:number[])=>Math.abs(s[0]-1)>.002)).toBe(true)
 await page.getByRole('button',{name:'Arrêter l’animation',exact:true}).click()
 await expect.poll(async()=> (await state(page)).animatedScales.length).toBe(0)
 await expect(page.getByRole('button',{name:'Voir le contexte',exact:true})).toBeVisible()
})
