import { chromium } from '@playwright/test'
const browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage({viewport:{width:1440,height:900}})
const errors=[], external=[], failed=[]
page.on('pageerror',e=>errors.push(e.message))
page.on('response',r=>{if(r.status()>=400)failed.push([r.url(),r.status()])})
await page.route('**/*',route=>{const url=new URL(route.request().url());if(!['127.0.0.1','localhost'].includes(url.hostname)){external.push(url.href);return route.abort()}return route.continue()})
await page.goto(process.env.CORPUS_URL||'http://127.0.0.1:4173')
await page.locator('main[data-loaded="true"]').waitFor({timeout:90000})
await page.waitForTimeout(400)
if(await page.getByRole('alert').count())throw new Error(await page.getByRole('alert').innerText())
await page.screenshot({path:'tests/artifacts/white-production.png'})
await page.getByRole('combobox').fill('poumon')
await page.getByRole('option').first().click()
await page.locator('main[data-loaded="true"]').waitFor({timeout:90000})
await page.waitForTimeout(1300)
await page.screenshot({path:'tests/artifacts/white-production-lung.png'})
const detail=await page.locator('.detail-content h2').innerText()
await page.reload()
await page.locator('main[data-loaded="true"]').waitFor({timeout:90000})
if(await page.locator('.detail-content h2').innerText()!=='Poumon droit')throw new Error('Deep link reload failed')
if(detail!=='Poumon droit')throw new Error('Lung selection failed')
if(await page.evaluate(()=>Boolean(window.__CORPUS_TEST__)))throw new Error('Development instrumentation leaked into production')
await page.getByRole('button',{name:'Fermer la fiche'}).click()
await page.getByRole('button',{name:'Vue muscles',exact:true}).click()
await page.locator('main[data-loaded="true"]').waitFor({timeout:90000})
await page.getByRole('button',{name:'Activer le thème sombre'}).click()
await page.waitForTimeout(1400)
await page.screenshot({path:'tests/artifacts/final-dark-muscles.png'})
await page.setViewportSize({width:375,height:667})
await page.waitForTimeout(500)
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw new Error('Mobile overflow')
await page.screenshot({path:'tests/artifacts/final-dark-mobile.png'})
await page.getByRole('button',{name:'Visite guidée',exact:true}).click()
await page.locator('main[data-loaded="true"]').waitFor({timeout:90000})
await page.waitForTimeout(1400)
await page.screenshot({path:'tests/artifacts/final-mobile-tour.png'})
await page.setViewportSize({width:1440,height:900})
await page.getByRole('button',{name:'Activer le thème clair'}).click()
await page.locator('.chat-composer input').fill('Montre-moi le cœur')
await page.locator('.chat-composer input').press('Enter')
await page.locator('main[data-selected="FMA7088"]').waitFor()
await page.waitForTimeout(1400)
await page.screenshot({path:'tests/artifacts/platform-production-chat.png'})
await page.getByRole('button',{name:'Fermer la conversation'}).click()
await page.getByRole('button',{name:'Battement illustratif',exact:true}).click()
await page.waitForTimeout(1200)
await page.getByRole('button',{name:'Arrêter l’animation',exact:true}).click()
await page.getByRole('button',{name:'Apprendre cette structure'}).click()
await page.locator('.course-article').waitFor()
await page.getByRole('button',{name:'Vérifier ma réponse'}).click()
await page.waitForTimeout(400)
await page.screenshot({path:'tests/artifacts/platform-production-learning.png'})
await page.setViewportSize({width:375,height:667})
await page.waitForTimeout(1200)
await page.screenshot({path:'tests/artifacts/platform-production-mobile.png'})
console.log(JSON.stringify({detail,errors,externalRequests:external,failedResponses:failed,visible:await page.locator('.model-status').innerText()},null,2))
await browser.close()
if(errors.length||external.length||failed.length)process.exit(1)
