import { chromium } from '@playwright/test'
const browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage({viewport:{width:1440,height:900}})
const errors=[], external=[], failed=[]
page.on('pageerror',e=>errors.push(e.message))
page.on('response',r=>{if(r.status()>=400)failed.push([r.url(),r.status()])})
await page.route('**/*',route=>{const url=new URL(route.request().url());if(!['127.0.0.1','localhost'].includes(url.hostname)){external.push(url.href);return route.abort()}return route.continue()})
await page.goto('http://127.0.0.1:4173')
await page.locator('main[data-loaded="true"]').waitFor({timeout:90000})
await page.waitForTimeout(400)
if(await page.getByRole('alert').count())throw new Error(await page.getByRole('alert').innerText())
await page.screenshot({path:'tests/artifacts/white-production.png'})
await page.getByRole('combobox').fill('poumon')
await page.getByRole('option').first().click()
await page.locator('main[data-loaded="true"]').waitFor({timeout:90000})
await page.waitForTimeout(1300)
await page.screenshot({path:'tests/artifacts/white-production-lung.png'})
const detail=await page.locator('.detail-content h2').innerText()
if(detail!=='Poumon droit')throw new Error('Lung selection failed')
if(await page.evaluate(()=>Boolean(window.__CORPUS_TEST__)))throw new Error('Development instrumentation leaked into production')
console.log(JSON.stringify({detail,errors,externalRequests:external,failedResponses:failed,visible:await page.locator('.model-status').innerText()},null,2))
await browser.close()
if(errors.length||external.length||failed.length)process.exit(1)
