import {useEffect,useState} from 'react'
import {ArrowRight,BookOpen,Brain,Clock3,Flag,Target,CheckCircle2} from 'lucide-react'
import {storageScope,useAccount} from '../account/store'
import {fetchStats} from '../flashcards/flashcardsApi'
import type {FlashcardStats} from '../flashcards/flashcardsTypes'
import catalog from './catalog.json'
import {buildDailySession,readJson,summarize,type Reading,type Records} from './progress'
import {beginDailySession,dailyPlan,advanceDailySession,stepRoute} from './session'
import './dashboard.css'
export default function DashboardWorkspace() {
  const account=useAccount(),scope=storageScope()
  const [view,setView]=useState('today'),[flash,setFlash]=useState<FlashcardStats|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(Boolean(account.user)),[now,setNow]=useState(Date.now)
  useEffect(()=>{if(!account.user)return;let live=true;setLoading(true);fetchStats().then(s=>{if(live)setFlash(s)}).catch(()=>{if(live)setError('Les statistiques flashcards sont indisponibles. Votre progression QCM et cours reste accessible.')}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[account.user?.id])
  useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(id)},[])
  const summary=summarize(catalog,readJson<Records>(scope,'corpus-practice-v1',{}),readJson<Reading>(scope,'corpus-reading-v1',{}),readJson<string[]>(scope,'corpus-completed',[]),now)
  const flashDue=flash?.eligibleDue??flash?.dueToday??0,steps=buildDailySession(summary,flashDue),plan=dailyPlan()
  const go=(tab:string,course?:string,revision?:string,count?:number)=>{const p=new URLSearchParams({tab});if(course){p.set('cours',course);if(tab==='cours'){const section=summary.chapters.find(c=>c.id===course)?.reading?.section;if(section)p.set('section',section)}}if(revision)p.set('revision',revision);if(count)p.set('count',String(count));location.hash=p.toString()}
  const flashByCourse=new Map(flash?.courses.map(c=>[c.id,c])??[])
  const state=(score:number|null,worked=false)=>score===null?(worked?'Sans données récentes':'Jamais travaillé'):score>=85?'Maîtrisé':score>=70?'À consolider':'Faible'
  const actions=(id:string)=><div className="dashboard-actions"><button className="study-secondary" onClick={()=>go('entrainement',id,'errors')}>Réviser cette faiblesse</button><button className="study-secondary" onClick={()=>go('entrainement',id,'chapter',5)}>Faire 5 QCM</button><button className="study-text-link" onClick={()=>go('cours',id)}>Voir le cours <ArrowRight size={14}/></button></div>
  return <section className="study-workspace dashboard-workspace" aria-label="Pilotage étudiant">
    <header className="dashboard-heading"><div><span className="study-eyebrow">VOTRE RYTHME. VOS PROGRÈS.</span><h1>Aujourd’hui,<br/><em>une étape à la fois.</em></h1><p>{account.user?`${account.user.name}, voici votre prochaine étape.`:'Votre espace de révision, même en mode invité.'}</p></div><span className="dashboard-date">{new Date(now).toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'})}</span></header>
    <nav className="dashboard-tabs" aria-label="Vues du pilotage"><button aria-pressed={view==='today'} onClick={()=>setView('today')}>Aujourd’hui</button><button aria-pressed={view==='mastery'} onClick={()=>setView('mastery')}>Maîtrise</button><button aria-pressed={view==='weakness'} onClick={()=>setView('weakness')}>Mes faiblesses</button><button onClick={()=>go('entrainement',undefined,'exam')}>Examen blanc <ArrowRight size={14}/></button></nav>
    {error&&<p role="status" className="dashboard-notice">{error}</p>}
    {plan&&<aside className="dashboard-session" aria-label="Session du jour"><CheckCircle2 size={22}/><div><strong>{plan.index>=plan.steps.length?'Session du jour terminée':`Étape ${plan.index+1} sur ${plan.steps.length} · ${plan.steps[plan.index].title}`}</strong><p>{plan.index>=plan.steps.length?'Votre progression est enregistrée dans les espaces habituels.':'Reprenez l’étape en cours, puis continuez votre parcours.'}</p></div>{plan.steps[plan.index]&&<><button className="study-primary" onClick={()=>{location.hash=stepRoute(plan.steps[plan.index])}}>Reprendre</button><button className="study-secondary" onClick={advanceDailySession}>Passer cette étape</button></>}</aside>}
    {view==='today'?<>
      <section className="dashboard-today"><div className="dashboard-section-title"><div><span className="study-eyebrow">QUOI FAIRE MAINTENANT</span><h2>À faire aujourd’hui</h2></div><button className="study-primary" disabled={!steps.length||loading} onClick={()=>beginDailySession(steps)}>Commencer ma session <ArrowRight size={17}/></button></div>
        {(steps.length>0||loading)&&<div className="dashboard-task-grid">
          <button className="dashboard-task" disabled={!account.user||loading||!flashDue} onClick={()=>go('flashcards',undefined,'due')}><Brain size={24}/><strong>{loading?'Chargement…':!account.user?'Vos flashcards':!flash?'Flashcards indisponibles':`Réviser ${flashDue} flashcards`}</strong><small>{!account.user?'Les flashcards synchronisées nécessitent un compte.':`${flash?.mastered??0} cartes maîtrisées · échéances FSRS`}</small></button>
          <button className="dashboard-task" disabled={!summary.errorsDue} onClick={()=>go('entrainement',undefined,'errors-due',20)}><Flag size={24}/><strong>Revoir {summary.errorsDue} {summary.errorsDue===1?'erreur due':'erreurs dues'}</strong><small>Vos questions ratées arrivées à échéance</small></button>
          <button className="dashboard-task" disabled={!summary.due} onClick={()=>go('entrainement',undefined,'due',20)}><Clock3 size={24}/><strong>{summary.due} QCM à échéance</strong><small>Répétition espacée existante · erreurs incluses</small></button>
          {summary.started[0]&&<button className="dashboard-task" onClick={()=>go('cours',summary.started[0].id)}><BookOpen size={24}/><strong>Continuer {summary.started[0].title}</strong><small>{summary.started[0].reading!.percent}% lu · cours non terminé</small></button>}
          {summary.weak[0]&&<button className="dashboard-task" onClick={()=>go('entrainement',summary.weak[0].id,'chapter',10)}><Target size={24}/><strong>Faire 10 QCM ciblés</strong><small>{summary.weak[0].subject} · {summary.weak[0].title}</small></button>}
        </div>}
        {!steps.length&&!loading&&<div className="dashboard-empty"><h3>{error?'Vos révisions flashcards restent à vérifier.':summary.chapters.some(c=>c.attempts||c.completed)?'Aucune révision due. Gardez votre rythme.':'Votre première étape commence ici.'}</h3><p>Ouvrez un cours ou répondez à quelques QCM. Votre programme se construira à partir de votre activité réelle.</p><button className="study-secondary" onClick={()=>go('cours')}>Découvrir les cours</button><button className="study-text-link" onClick={()=>go('entrainement')}>Choisir un entraînement</button></div>}
      </section>
      <div className="dashboard-bottom-grid"><section className="dashboard-card"><span className="study-eyebrow">VOTRE PROGRESSION DU JOUR</span><h2>{summary.reviewedToday} QCM revisités</h2><p>Questions distinctes travaillées aujourd’hui · {flash?.reviewedToday??0} réponses flashcards enregistrées.</p><p>{summary.chapters.filter(c=>c.completed).length} cours terminés au total. La lecture est un repère, pas une mesure de maîtrise.</p></section><section className="dashboard-card"><span className="study-eyebrow">POUR REPRENDRE</span>{summary.last?<><h2>{summary.last.chapter.title}</h2><p>Dernière activité {summary.last.kind==='course'?'de lecture':'QCM'}.</p><button className="study-secondary" onClick={()=>go(summary.last!.kind==='course'?'cours':'entrainement',summary.last!.chapter.id)}>Reprendre <ArrowRight size={15}/></button></>:<><h2>Un nouveau départ</h2><p>Votre dernière activité apparaîtra ici.</p></>}</section></div>
      <section className="dashboard-card"><h2>Matières à consolider</h2>{summary.subjects.filter(s=>s.score!==null&&s.score<85).length?summary.subjects.filter(s=>s.score!==null&&s.score<85).map(s=><button className="dashboard-subject-link" key={s.name} onClick={()=>setView('mastery')}><strong>{s.name}</strong><span>{s.score}% · {s.observed} questions observées <ArrowRight size={14}/></span></button>):<p>Pas encore de faiblesse mesurable sur les QCM des 30 derniers jours.</p>}</section>
    </>:view==='mastery'?<section><div className="dashboard-section-title"><h2>Votre carte de maîtrise</h2></div><details className="dashboard-formula"><summary>Comment ce score est-il calculé ?</summary><p>100 × questions réussies au dernier essai ÷ questions travaillées au cours des 30 derniers jours. Une question compte une fois, au niveau du chapitre et de la matière. Sans observation récente, aucun score n’est attribué. Les cours et les flashcards sont affichés séparément.</p><p>Maîtrisé : ≥ 85 %. À consolider : 70–84 %. Faible : &lt; 70 %. Ce repère d’entraînement ne prédit pas une note de concours.</p></details><div className="dashboard-mastery-grid">{summary.subjects.map(s=><details className="dashboard-card" key={s.name} open={s.score!==null&&s.score<70}><summary><strong>{s.name}</strong><span>{s.score===null?'—':s.score+'%'} · {state(s.score,s.chapters.some(c=>c.attempts>0))}</span></summary><p>{s.observed} questions distinctes observées · Flashcards : {(()=>{const f=flash?.subjects.find(f=>f.name===s.name);return f?`${f.mastered}/${f.total} maîtrisées`:'aucune donnée'})()}</p>{[...s.chapters].sort((a,b)=>(a.score??101)-(b.score??101)).map(c=><article className="dashboard-chapter" key={c.id}><div><strong>{c.title}</strong><span>{c.score===null?'—':c.score+'%'} · {state(c.score,c.attempts>0)}</span><small>{c.observed} QCM récents · {c.completed?'Cours terminé':c.reading?c.reading.percent+'% lu':'Cours non commencé'}{flashByCourse.has(c.id)&&` · Flashcards : ${flashByCourse.get(c.id)!.mastered??0}/${flashByCourse.get(c.id)!.total} maîtrisées`}</small></div><div><button className="study-text-link" onClick={()=>go('entrainement',c.id,'chapter',5)}>Réviser</button><button className="study-text-link" onClick={()=>go('cours',c.id)}>Cours</button></div></article>)}</details>)}</div></section>:<section><h2>Mes faiblesses</h2><p>Les erreurs du carnet QCM existant, regroupées par chapitre. Une réussite retire la question de ce carnet selon les règles habituelles.</p><div className="dashboard-mastery-grid">{summary.chapters.filter(c=>c.errors).map(c=><article className="dashboard-card" key={c.id}><span className="study-eyebrow">{c.subject}</span><h3>{c.title}</h3><p>{c.errors} erreurs actuelles · {c.attempts} tentatives · {c.attempts?Math.round(c.correct/c.attempts*100):0}% de réussite historique.</p><p>Dernière erreur : {c.lastError?new Date(c.lastError).toLocaleDateString('fr-FR'):'date non disponible'}<br/>Prochaine révision : {Number.isFinite(c.nextDue)?new Date(c.nextDue).toLocaleString('fr-FR'):'non disponible'}<br/>Maîtrise récente : {c.score===null?'non mesurée':c.score+'%'}</p>{actions(c.id)}</article>)}</div>{!summary.chapters.some(c=>c.errors)&&<div className="dashboard-empty"><h3>Aucune erreur à retravailler.</h3><p>Vos futures erreurs QCM apparaîtront ici, sans deuxième système de progression.</p><button className="study-secondary" onClick={()=>go('entrainement')}>Faire des QCM</button></div>}</section>}
  </section>
}
