import { chemistryCourses, chemistryQuestions, curatedChemistryCourseIds } from './chemistry'
import { cellBiologyCourses, cellBiologyQuestions, cellBiologyQuestionCourseIds } from './cellBiology'
import { biochemistryCourses, biochemistryQuestions } from './biochemistry'
import { geneticsCourses, geneticsQuestions } from './genetics'
import { embryologyCourses, embryologyQuestions } from './embryology'
import { histologyCourses, histologyQuestions } from './histology'
import { biophysicsCourses, biophysicsQuestions } from './biophysics'
import { physiologyCourses, physiologyQuestions } from './physiology'
import { immunologyCourses, immunologyQuestions } from './immunology'
import { statisticsCourses, statisticsQuestions } from './statistics'
import { pharmacologyCourses, pharmacologyQuestions } from './pharmacology'
import { publicHealthCourses, publicHealthQuestions } from './publicHealth'
import { shsCourses, shsQuestions } from './shs'
import { upperLimbCourses, upperLimbQuestions } from './anatomy/upperLimb'
import { lowerLimbCourses, lowerLimbQuestions } from './anatomy/lowerLimb'
import { upperNeurovascularCourses, upperNeurovascularQuestions } from './anatomy/upperNeurovascular'
import { lowerNeurovascularCourses, lowerNeurovascularQuestions } from './anatomy/lowerNeurovascular'
import { trunkWallCourses, trunkWallQuestions } from './anatomy/trunkWalls'
import { thoraxVisceraCourses, thoraxVisceraQuestions } from './anatomy/thoraxViscera'
import { abdominalCourses, abdominalQuestions } from './anatomy/abdomen'
import { pelvisHeadNeckCourses, pelvisHeadNeckQuestions } from './anatomy/pelvisHeadNeck'
import { additionalHistologyCourses, additionalHistologyQuestions } from './histology/additional'
import { additionalEmbryologyCourses, additionalEmbryologyQuestions } from './embryology/additional'
import { developmentEmbryologyCourses, developmentEmbryologyQuestions } from './embryology/development'
import { additionalGeneticsCourses, additionalGeneticsQuestions } from './genetics/additional'
import { additionalBiochemistryCourses, additionalBiochemistryQuestions } from './biochemistry/additional'
import { imagingCourses, imagingQuestions } from './biophysics/imaging'
import { fluidCourses, fluidQuestions } from './biophysics/fluids'
import { radiationCourses, radiationQuestions } from './biophysics/radiation'
import { waveCourses, waveQuestions } from './biophysics/waves'
import { cellNeuromuscularCourses, cellNeuromuscularQuestions } from './physiology/cellNeuromuscular'
import { cardiorespiratoryCourses, cardiorespiratoryQuestions } from './physiology/cardiorespiratory'
import { renalEndocrineCourses, renalEndocrineQuestions } from './physiology/renalEndocrine'
import { firstImmunologyCourses, firstImmunologyQuestions } from './immunology/first'
import { secondImmunologyCourses, secondImmunologyQuestions } from './immunology/second'
import { advancedStatisticsCourses, advancedStatisticsQuestions } from './statistics/advanced'
import { additionalPharmacologyCourses, additionalPharmacologyQuestions } from './pharmacology/additional'
import { additionalPublicHealthCourses, additionalPublicHealthQuestions } from './publicHealth/additional'
import { additionalShsCourses, additionalShsQuestions } from './shs/additional'
import { drugSocietyCourses, drugSocietyQuestions } from './drugSociety'
import { researchCourses, researchQuestions } from './research/additional'
import { odontologyCourses, odontologyQuestions } from './odontology/additional'
import { medicalEnglishCourses, medicalEnglishQuestions } from './english/medical'

export const authoredCanonicalCourses = [...chemistryCourses, ...cellBiologyCourses, ...biochemistryCourses, ...additionalBiochemistryCourses, ...geneticsCourses, ...additionalGeneticsCourses, ...embryologyCourses, ...additionalEmbryologyCourses, ...developmentEmbryologyCourses, ...histologyCourses, ...additionalHistologyCourses, ...biophysicsCourses, ...imagingCourses, ...fluidCourses, ...radiationCourses, ...waveCourses, ...physiologyCourses, ...cellNeuromuscularCourses, ...cardiorespiratoryCourses, ...renalEndocrineCourses, ...immunologyCourses, ...firstImmunologyCourses, ...secondImmunologyCourses, ...statisticsCourses, ...advancedStatisticsCourses, ...pharmacologyCourses, ...additionalPharmacologyCourses, ...publicHealthCourses, ...additionalPublicHealthCourses, ...shsCourses, ...additionalShsCourses, ...drugSocietyCourses, ...researchCourses, ...odontologyCourses, ...medicalEnglishCourses, ...upperLimbCourses, ...lowerLimbCourses, ...upperNeurovascularCourses, ...lowerNeurovascularCourses, ...trunkWallCourses, ...thoraxVisceraCourses, ...abdominalCourses, ...pelvisHeadNeckCourses]
export const authoredCanonicalQuestions = [...chemistryQuestions, ...cellBiologyQuestions, ...biochemistryQuestions, ...additionalBiochemistryQuestions, ...geneticsQuestions, ...additionalGeneticsQuestions, ...embryologyQuestions, ...additionalEmbryologyQuestions, ...developmentEmbryologyQuestions, ...histologyQuestions, ...additionalHistologyQuestions, ...biophysicsQuestions, ...imagingQuestions, ...fluidQuestions, ...radiationQuestions, ...waveQuestions, ...physiologyQuestions, ...cellNeuromuscularQuestions, ...cardiorespiratoryQuestions, ...renalEndocrineQuestions, ...immunologyQuestions, ...firstImmunologyQuestions, ...secondImmunologyQuestions, ...statisticsQuestions, ...advancedStatisticsQuestions, ...pharmacologyQuestions, ...additionalPharmacologyQuestions, ...publicHealthQuestions, ...additionalPublicHealthQuestions, ...shsQuestions, ...additionalShsQuestions, ...drugSocietyQuestions, ...researchQuestions, ...odontologyQuestions, ...medicalEnglishQuestions, ...upperLimbQuestions, ...lowerLimbQuestions, ...upperNeurovascularQuestions, ...lowerNeurovascularQuestions, ...trunkWallQuestions, ...thoraxVisceraQuestions, ...abdominalQuestions, ...pelvisHeadNeckQuestions]
export const authoredCanonicalCourseIds = new Set(authoredCanonicalCourses.map(course => course.id))
export const authoredQuestionCourseIds = new Set([...curatedChemistryCourseIds, ...cellBiologyQuestionCourseIds, ...biochemistryQuestions.map(question => question.course), ...additionalBiochemistryQuestions.map(question => question.course), ...geneticsQuestions.map(question => question.course), ...additionalGeneticsQuestions.map(question => question.course), ...embryologyQuestions.map(question => question.course), ...additionalEmbryologyQuestions.map(question => question.course), ...developmentEmbryologyQuestions.map(question => question.course), ...histologyQuestions.map(question => question.course), ...additionalHistologyQuestions.map(question => question.course), ...biophysicsQuestions.map(question => question.course), ...imagingQuestions.map(question => question.course), ...fluidQuestions.map(question => question.course), ...radiationQuestions.map(question => question.course), ...waveQuestions.map(question => question.course), ...physiologyQuestions.map(question => question.course), ...cellNeuromuscularQuestions.map(question => question.course), ...cardiorespiratoryQuestions.map(question => question.course), ...renalEndocrineQuestions.map(question => question.course), ...immunologyQuestions.map(question => question.course), ...firstImmunologyQuestions.map(question => question.course), ...secondImmunologyQuestions.map(question => question.course), ...statisticsQuestions.map(question => question.course), ...pharmacologyQuestions.map(question => question.course), ...additionalPharmacologyQuestions.map(question => question.course), ...publicHealthQuestions.map(question => question.course), ...additionalPublicHealthQuestions.map(question => question.course), ...shsQuestions.map(question => question.course), ...additionalShsQuestions.map(question => question.course), ...drugSocietyQuestions.map(question => question.course), ...researchQuestions.map(question => question.course), ...odontologyQuestions.map(question => question.course), ...medicalEnglishQuestions.map(question => question.course), ...upperLimbQuestions.map(question => question.course), ...lowerLimbQuestions.map(question => question.course), ...upperNeurovascularQuestions.map(question => question.course), ...lowerNeurovascularQuestions.map(question => question.course), ...trunkWallQuestions.map(question => question.course), ...thoraxVisceraQuestions.map(question => question.course), ...abdominalQuestions.map(question => question.course), ...pelvisHeadNeckQuestions.map(question => question.course)])
