import { chemistryCourses, chemistryQuestions, curatedChemistryCourseIds } from './chemistry'
import { cellBiologyCourses, cellBiologyQuestions, cellBiologyQuestionCourseIds } from './cellBiology'
import { biochemistryCourses, biochemistryQuestions } from './biochemistry'
import { geneticsCourses, geneticsQuestions } from './genetics'
import { embryologyCourses, embryologyQuestions } from './embryology'
import { histologyCourses, histologyQuestions } from './histology'
import { biophysicsCourses, biophysicsQuestions } from './biophysics'
import { physiologyCourses, physiologyQuestions } from './physiology'
import { immunologyCourses, immunologyQuestions } from './immunology'
import { statisticsCourses, statisticsQuestions } from './statistics'
import { pharmacologyCourses, pharmacologyQuestions } from './pharmacology'
import { publicHealthCourses, publicHealthQuestions } from './publicHealth'
import { shsCourses, shsQuestions } from './shs'
import { upperLimbCourses, upperLimbQuestions } from './anatomy/upperLimb'
import { lowerLimbCourses, lowerLimbQuestions } from './anatomy/lowerLimb'
import { upperNeurovascularCourses, upperNeurovascularQuestions } from './anatomy/upperNeurovascular'
import { lowerNeurovascularCourses, lowerNeurovascularQuestions } from './anatomy/lowerNeurovascular'
import { trunkWallCourses, trunkWallQuestions } from './anatomy/trunkWalls'
import { thoraxVisceraCourses, thoraxVisceraQuestions } from './anatomy/thoraxViscera'
import { abdominalCourses, abdominalQuestions } from './anatomy/abdomen'
import { pelvisHeadNeckCourses, pelvisHeadNeckQuestions } from './anatomy/pelvisHeadNeck'
import { additionalHistologyCourses, additionalHistologyQuestions } from './histology/additional'
import { additionalEmbryologyCourses, additionalEmbryologyQuestions } from './embryology/additional'
import { developmentEmbryologyCourses, developmentEmbryologyQuestions } from './embryology/development'
import { additionalGeneticsCourses, additionalGeneticsQuestions } from './genetics/additional'
import { additionalBiochemistryCourses, additionalBiochemistryQuestions } from './biochemistry/additional'
import { imagingCourses, imagingQuestions } from './biophysics/imaging'

export const authoredCanonicalCourses = [...chemistryCourses, ...cellBiologyCourses, ...biochemistryCourses, ...additionalBiochemistryCourses, ...geneticsCourses, ...additionalGeneticsCourses, ...embryologyCourses, ...additionalEmbryologyCourses, ...developmentEmbryologyCourses, ...histologyCourses, ...additionalHistologyCourses, ...biophysicsCourses, ...imagingCourses, ...physiologyCourses, ...immunologyCourses, ...statisticsCourses, ...pharmacologyCourses, ...publicHealthCourses, ...shsCourses, ...upperLimbCourses, ...lowerLimbCourses, ...upperNeurovascularCourses, ...lowerNeurovascularCourses, ...trunkWallCourses, ...thoraxVisceraCourses, ...abdominalCourses, ...pelvisHeadNeckCourses]
export const authoredCanonicalQuestions = [...chemistryQuestions, ...cellBiologyQuestions, ...biochemistryQuestions, ...additionalBiochemistryQuestions, ...geneticsQuestions, ...additionalGeneticsQuestions, ...embryologyQuestions, ...additionalEmbryologyQuestions, ...developmentEmbryologyQuestions, ...histologyQuestions, ...additionalHistologyQuestions, ...biophysicsQuestions, ...imagingQuestions, ...physiologyQuestions, ...immunologyQuestions, ...statisticsQuestions, ...pharmacologyQuestions, ...publicHealthQuestions, ...shsQuestions, ...upperLimbQuestions, ...lowerLimbQuestions, ...upperNeurovascularQuestions, ...lowerNeurovascularQuestions, ...trunkWallQuestions, ...thoraxVisceraQuestions, ...abdominalQuestions, ...pelvisHeadNeckQuestions]
export const authoredCanonicalCourseIds = new Set(authoredCanonicalCourses.map(course => course.id))
export const authoredQuestionCourseIds = new Set([...curatedChemistryCourseIds, ...cellBiologyQuestionCourseIds, ...biochemistryQuestions.map(question => question.course), ...additionalBiochemistryQuestions.map(question => question.course), ...geneticsQuestions.map(question => question.course), ...additionalGeneticsQuestions.map(question => question.course), ...embryologyQuestions.map(question => question.course), ...additionalEmbryologyQuestions.map(question => question.course), ...developmentEmbryologyQuestions.map(question => question.course), ...histologyQuestions.map(question => question.course), ...additionalHistologyQuestions.map(question => question.course), ...biophysicsQuestions.map(question => question.course), ...imagingQuestions.map(question => question.course), ...physiologyQuestions.map(question => question.course), ...immunologyQuestions.map(question => question.course), ...statisticsQuestions.map(question => question.course), ...pharmacologyQuestions.map(question => question.course), ...publicHealthQuestions.map(question => question.course), ...shsQuestions.map(question => question.course), ...upperLimbQuestions.map(question => question.course), ...lowerLimbQuestions.map(question => question.course), ...upperNeurovascularQuestions.map(question => question.course), ...lowerNeurovascularQuestions.map(question => question.course), ...trunkWallQuestions.map(question => question.course), ...thoraxVisceraQuestions.map(question => question.course), ...abdominalQuestions.map(question => question.course), ...pelvisHeadNeckQuestions.map(question => question.course)])
