import type { Course } from '../../curriculum'
import type { Question } from '../../questions'
import { canonicalCourses } from '../../taxonomy/canonicalCourses'

const catalog = new Map(canonicalCourses.filter(c => c.subject === 'Embryologie & Reproduction').map(c => [c.id, c]))
const s = (title: string, text: string) => ({ title, text })
type Draft = { goals: string[]; parts: Course['sections']; pitfall: string; recall: string; answer: string; url: string; case: string; caseAnswer: string; questions: string[]; answers: string[]; wrong: string[][] }
const make = (id: string, d: Draft): Course => {
  const c = catalog.get(id); if (!c) throw new Error(`Identifiant embryologique inconnu : ${id}`)
  const url = `https://openstax.org/books/anatomy-and-physiology-2e/pages/${d.url}`
  return { id, title: c.title, category: c.subject, tag: c.module, minutes: 17, structure: null, objectives: d.goals, sections: d.parts, trap: d.pitfall, recall: d.recall, answer: d.answer,
    source: url, sources: [{ label: 'OpenStax · Anatomy & Physiology 2e', url }], prerequisites: ['Gamétogenèse et fécondation', 'Organisation des feuillets embryonnaires'],
    glossary: [['Blastomère', 'Cellule produite par les divisions précoces du zygote.'], ['Trophoblaste', 'Lignée externe du blastocyste impliquée dans l’implantation et les échanges placentaires.'], ['Masse cellulaire interne', 'Population embryonnaire à l’origine de l’embryon proprement dit.']],
    caseStudy: { prompt: d.case, answer: d.caseAnswer }, review: { status: 'unreviewed', updatedAt: '2026-09-23', sourcesUpdatedAt: '2026-09-23' } }
}
const item = (_id: string, goals: string[], parts: Course['sections'], pitfall: string, recall: string, answer: string, url: string, caseText: string, caseAnswer: string, questions: string[], answers: string[], wrong: string[][]): Draft => ({ goals, parts, pitfall, recall, answer, url, case: caseText, caseAnswer, questions, answers, wrong })

export const additionalEmbryologyCourses: Course[] = [
  make('embryo-early-cleavage-blastocyst', item('embryo-early-cleavage-blastocyst', ['Ordonner fécondation, segmentation et blastulation', 'Décrire la compaction et la différenciation du blastocyste', 'Relier le transport tubaire au calendrier d’implantation'], [
    s('Zygote et premières divisions', 'Après la fusion des gamètes, le zygote diploïde commence des divisions mitotiques successives sans croissance globale notable. Les cellules filles, ou blastomères, deviennent progressivement plus petites tandis que l’embryon chemine dans la trompe. Le calendrier varie légèrement ; les repères en jours sont approximatifs.'),
    s('Compaction et morula', 'Autour du stade de huit cellules, l’augmentation des contacts et des jonctions rend la morula plus compacte. Une première différenciation distingue des cellules externes polarisées et des cellules internes. La morula atteint la cavité utérine plusieurs jours après la fécondation.'),
    s('Formation du blastocyste', 'L’entrée de liquide crée le blastocèle et transforme la morula en blastocyste. Celui-ci comprend une masse cellulaire interne, ou embryoblaste, et un trophoblaste externe. L’expansion du blastocyste et la différenciation de ses lignées préparent l’implantation.'),
    s('Éclosion de la zone pellucide', 'La zone pellucide entoure l’embryon durant les premières divisions et limite notamment une implantation tubaire trop précoce. Le blastocyste en sort avant l’adhésion à l’endomètre. L’éclosion dépend de l’expansion et de mécanismes enzymatiques ; elle rend l’implantation possible mais ne la garantit pas.'),
    s('Repères temporels et devenir', 'La segmentation et le stade morula précèdent généralement le blastocyste libre dans la cavité utérine, puis l’apposition et l’implantation débutent vers la fin de la première semaine. Ces événements se chevauchent et la datation clinique est rapportée à la dernière menstruation, environ deux semaines avant la fécondation dans un cycle de référence.')], 'Le blastocyste se forme après la morula ; le trophoblaste et la masse cellulaire interne ont des devenirs différents.', 'Quelles sont les deux grandes populations cellulaires du blastocyste ?', 'Le trophoblaste externe et la masse cellulaire interne, ou embryoblaste.', '28-1-fertilization', 'Une biopsie préimplantatoire distingue une couche externe de cellules et un amas interne. Quels compartiments sont identifiés ?', 'La couche externe correspond au trophoblaste ; l’amas interne est l’embryoblaste, à l’origine de l’embryon proprement dit.', ['Quel stade suit habituellement la morula ?', 'Quelle cavité apparaît dans le blastocyste ?', 'Quelle population cellulaire externe contribue aux annexes embryonnaires ?', 'À quoi sert la zone pellucide durant le transport tubaire ?', 'Quel compartiment du blastocyste forme l’embryon proprement dit ?'], ['Le blastocyste.', 'Le blastocèle.', 'Le trophoblaste.', 'Elle limite l’adhésion prématurée avant l’arrivée dans l’utérus.', 'La masse cellulaire interne, ou embryoblaste.'], [['La gastrula.', 'Le neurula.', 'Le fœtus.'], ['La cavité amniotique.', 'Le cœlome intra-embryonnaire.', 'Le canal neural.'], ['L’endoderme définitif.', 'Le mésoderme para-axial.', 'La notochorde.'], ['Elle nourrit le placenta après le terme.', 'Elle forme le tube neural.', 'Elle constitue la paroi utérine.'], ['Le syncytiotrophoblaste seul.', 'La zone pellucide.', 'Le blastocèle.']])),
  make('embryo-gastrulation-germ-layers', item('embryo-gastrulation-germ-layers', ['Situer la ligne primitive et le nœud primitif', 'Expliquer les mouvements de gastrulation', 'Associer les trois feuillets à leurs grands dérivés'], [
    s('Disque didermique et ligne primitive', 'Au début de la troisième semaine, le disque embryonnaire est didermique. La ligne primitive apparaît dans l’épiblaste caudal et établit les axes cranio-caudal, droite-gauche et dorsal-ventral. Son extrémité crâniale forme le nœud primitif.'),
    s('Migrations cellulaires', 'Des cellules épiblastiques convergent vers la ligne primitive, s’invaginent et migrent entre les couches. Les premières remplacent l’hypoblaste pour former l’endoderme définitif ; d’autres s’interposent pour donner le mésoderme intra-embryonnaire. L’épiblaste restant devient l’ectoderme.'),
    s('Feuillets embryonnaires', 'L’ectoderme donne notamment épiderme, système nerveux et certains organes sensoriels. Le mésoderme contribue aux muscles, os, tissus conjonctifs, cœur, vaisseaux, reins et gonades. L’endoderme forme principalement l’épithélium de nombreux appareils digestif et respiratoire ainsi que des glandes associées.'),
    s('Notochorde et induction', 'Les cellules du nœud migrent crânialement et participent à la formation du processus notochordal puis de la notochorde. Cette structure axiale organise l’axe longitudinal et participe à l’induction de la plaque neurale. Des restes notochordaux persistent dans le nucleus pulposus des disques.'),
    s('Fin de la gastrulation', 'La ligne primitive régresse habituellement à mesure que les migrations s’achèvent. Une persistance caudale peut être associée à une anomalie sacrococcygienne rare. La gastrulation transforme donc le disque didermique en disque tridermique et pose l’organisation corporelle, sans que les dérivés de chaque feuillet soient absolument exclusifs.')], 'L’endoderme définitif provient de cellules épiblastiques qui remplacent l’hypoblaste, et non de l’hypoblaste lui-même.', 'Quels trois feuillets résultent de la gastrulation ?', 'L’ectoderme, le mésoderme et l’endoderme définitif.', '28-2-embryonic-development', 'Des cellules épiblastiques migrent à travers la ligne primitive et remplacent l’hypoblaste. Quel feuillet forment-elles ?', 'Elles participent à l’endoderme définitif ; des cellules migrant ensuite s’interposent pour former le mésoderme.', ['Quel feuillet embryonnaire provient de l’épiblaste restant ?', 'Où apparaît la ligne primitive ?', 'Quelle structure axiale contribue à induire la plaque neurale ?', 'Quel feuillet forme principalement les épithéliums digestif et respiratoire ?', 'Quelle est l’origine de l’endoderme définitif ?'], ['L’ectoderme.', 'Dans l’épiblaste caudal du disque embryonnaire.', 'La notochorde.', 'L’endoderme.', 'Des cellules épiblastiques qui remplacent l’hypoblaste.'], [['L’endoderme.', 'Le mésoderme.', 'Le trophoblaste.'], ['Dans le trophoblaste.', 'Dans l’amnios.', 'Dans la plaque préchordale uniquement.'], ['Le canal neurentérique.', 'L’allantoïde.', 'Le sac vitellin.'], ['L’ectoderme.', 'Le mésoderme para-axial.', 'La crête neurale.'], ['De cellules trophoblastiques.', 'De cellules hypoblastiques restant en place.', 'Des cellules de la ligne primitive exclusivement après neurulation.']])),
  make('embryo-spermatogenesis-detail', item('embryo-spermatogenesis-detail', ['Ordonner les cellules de la lignée germinale mâle', 'Distinguer méiose et spermiogenèse', 'Relier Sertoli et Leydig au microenvironnement testiculaire'], [
    s('Compartiment des tubes séminifères', 'La spermatogenèse a lieu dans les tubes séminifères. Les cellules germinales occupent différents niveaux de l’épithélium, des spermatogonies basales aux spermatides plus proches de la lumière. Les cellules de Sertoli soutiennent la lignée, participent à la barrière hémato-testiculaire et répondent aux signaux hormonaux.'),
    s('Mitoses et spermatocytes', 'Les spermatogonies se renouvellent par mitose et certaines se différencient en spermatocytes I diploïdes qui entrent en méiose. La réplication de l’ADN précède la première division méiotique. Les recombinaisons et ségrégations produisent des cellules haploïdes génétiquement distinctes.'),
    s('Méiose et spermatides', 'La méiose I sépare les chromosomes homologues et produit des spermatocytes II ; la méiose II sépare les chromatides sœurs pour former des spermatides haploïdes. Les divisions sont inégales en cytoplasme mais aboutissent classiquement à quatre cellules haploïdes par spermatocyte I, avant maturation.'),
    s('Spermiogenèse', 'La spermiogenèse transforme les spermatides rondes en spermatozoïdes sans nouvelle division : le noyau se condense, l’acrosome se forme, un flagelle apparaît et l’excès de cytoplasme est éliminé. La tête porte noyau et acrosome, la pièce intermédiaire contient les mitochondries et le flagelle assure la motilité.'),
    s('Sertoli, Leydig et régulation', 'Les cellules de Leydig du tissu interstitiel produisent la testostérone sous l’influence de la LH. La FSH agit sur les cellules de Sertoli, qui nourrissent les cellules germinales et sécrètent notamment l’inhibine B. La température testiculaire, les hormones et l’intégrité de l’épithélium influencent la production spermatique.')], 'La spermiogenèse est une différenciation morphologique des spermatides, pas une division méiotique supplémentaire.', 'Quelle division produit les spermatides haploïdes ?', 'La méiose II, après la séparation des homologues lors de la méiose I.', '27-2-anatomy-and-physiology-of-the-male-reproductive-system', 'Une cellule ronde haploïde développe un acrosome et un flagelle sans changer de ploïdie. Quel processus se déroule ?', 'La spermiogenèse, différenciation des spermatides en spermatozoïdes.', ['Quelle hormone hypophysaire stimule les cellules de Leydig ?', 'Quel type cellulaire forme la barrière hémato-testiculaire ?', 'Que sépare principalement la première division méiotique ?', 'La spermiogenèse augmente-t-elle le nombre de cellules ?', 'Où se trouvent les cellules de Leydig ?'], ['La LH.', 'Les cellules de Sertoli.', 'Les chromosomes homologues.', 'Non, elle transforme les spermatides sans division.', 'Dans le tissu interstitiel entre les tubes séminifères.'], [['La FSH seule.', 'La prolactine.', 'L’ocytocine.'], ['Les cellules germinales.', 'Les cellules de Leydig.', 'Les cellules endothéliales uniquement.'], ['Les chromatides sœurs.', 'Les chromosomes sexuels uniquement.', 'Les centromères après la mitose.'], ['Oui, elle comprend une mitose.', 'Oui, elle forme deux cellules diploïdes.', 'Oui, elle correspond à la méiose III.'], ['Dans la lumière des tubes.', 'Dans l’épididyme.', 'Dans les vésicules séminales.']])),
  make('embryo-oogenesis-folliculogenesis', item('embryo-oogenesis-folliculogenesis', ['Suivre la méiose ovocytaire et ses arrêts', 'Distinguer croissance folliculaire et maturation ovocytaire', 'Décrire les grandes étapes de la folliculogenèse'], [
    s('Mise en place prénatale', 'Les ovogonies prolifèrent pendant la vie fœtale puis entrent en méiose et deviennent des ovocytes I. Ceux-ci s’arrêtent en prophase I, au stade diplotène, et sont entourés de cellules folliculaires aplaties dans des follicules primordiaux. Le stock folliculaire diminue ensuite par atrésie.'),
    s('Croissance folliculaire', 'À partir de la puberté, des follicules sont recrutés de façon cyclique. Le follicule primaire développe des cellules de la granulosa cubiques et une zone pellucide ; les follicules en croissance acquièrent plusieurs couches de granulosa et une thèque. Le follicule antral forme une cavité remplie de liquide.'),
    s('Deux compartiments endocrines', 'Les cellules de la thèque interne produisent des androgènes sous stimulation de LH ; les cellules de granulosa, stimulées par FSH, les aromatisent en œstrogènes. La thèque externe est surtout conjonctive. Cette coopération explique la stéroïdogenèse folliculaire et varie au cours du cycle.'),
    s('Reprise méiotique et ovulation', 'Le pic préovulatoire de LH déclenche la reprise de la méiose I. L’ovocyte I achève cette division avec cytodiérèse inégale, formant un ovocyte II et un premier globule polaire. L’ovocyte II commence la méiose II et s’arrête en métaphase II ; l’ovulation libère le complexe ovocyte-cumulus.'),
    s('Corps jaune et fécondation', 'Après l’ovulation, les cellules folliculaires se lutéinisent pour former le corps jaune, qui sécrète surtout progestérone et œstrogènes. En l’absence de grossesse, il régresse ; en début de grossesse, l’hCG le maintient transitoirement. La méiose II de l’ovocyte ne s’achève qu’en cas de fécondation.')], 'L’ovocyte II ovulé est bloqué en métaphase II ; la méiose ne s’achève qu’après fécondation.', 'À quel stade méiotique se trouve l’ovocyte libéré lors de l’ovulation ?', 'En métaphase II, après avoir terminé la première division méiotique.', '27-3-anatomy-and-physiology-of-the-female-reproductive-system', 'Un ovocyte expulsé au moment de l’ovulation est observé avant toute fécondation. À quel stade méiotique est-il arrêté ?', 'En métaphase II ; l’entrée du spermatozoïde déclenche l’achèvement de la méiose.', ['À quel stade l’ovocyte I reste-t-il arrêté avant la puberté ?', 'Quelle hormone déclenche le pic ovulatoire ?', 'Quelle cellule folliculaire aromatise les androgènes en œstrogènes ?', 'Quel événement permet l’achèvement de la méiose II ?', 'Quelle structure sécrète la progestérone après l’ovulation ?'], ['En prophase I.', 'La LH.', 'La granulosa.', 'La fécondation.', 'Le corps jaune.'], [['En métaphase II.', 'En anaphase I.', 'En prophase II.'], ['La FSH seule.', 'La progestérone.', 'La prolactine.'], ['La thèque externe.', 'Le corps albicans.', 'Les cellules de Leydig.'], ['La nidation.', 'La menstruation.', 'La croissance folliculaire.'], ['Le follicule primordial.', 'La zone pellucide.', 'L’endomètre.']])),
  make('embryo-fertilization-mechanisms', item('embryo-fertilization-mechanisms', ['Décrire la capacitation des spermatozoïdes', 'Ordonner les étapes de fusion gamétique', 'Expliquer les mécanismes limitant la polyspermie'], [
    s('Lieu et rencontre des gamètes', 'La fécondation se déroule le plus souvent dans l’ampoule de la trompe. Les spermatozoïdes déposés dans les voies génitales féminines acquièrent progressivement leur capacité fécondante. Le transport, la motilité et la rencontre du complexe ovocyte-cumulus dépendent de facteurs biologiques multiples.'),
    s('Capacitation', 'Dans les voies génitales féminines, la capacitation modifie la membrane du spermatozoïde et son profil de motilité. Elle rend possible la réaction acrosomique et la fécondation ; elle ne correspond pas à une production supplémentaire de spermatozoïdes. La durée et les mécanismes précis dépendent de l’espèce et du contexte.'),
    s('Cumulus et zone pellucide', 'Les spermatozoïdes traversent les cellules du cumulus puis interagissent avec la zone pellucide entourant l’ovocyte. Des molécules de surface et des enzymes acrosomiques facilitent le passage. L’acrosome est une vésicule spécialisée de la tête spermatique, distincte du noyau.'),
    s('Fusion et activation ovocytaire', 'La fusion des membranes gamétiques déclenche des oscillations calciques dans l’ovocyte. L’activation ovocytaire conduit notamment à la reprise et à l’achèvement de la méiose II, à l’émission du second globule polaire puis à la formation des pronoyaux. Le matériel génétique paternel et maternel se rapproche avant la première division.'),
    s('Blocage de la polyspermie', 'La réaction corticale libère le contenu des granules corticaux dans l’espace périvitellin et modifie la zone pellucide, réduisant la possibilité qu’un autre spermatozoïde pénètre. Ce mécanisme préserve la diploïdie et le développement normal. Les détails moléculaires varient selon les espèces ; il ne faut pas réduire le blocage à une simple fermeture mécanique instantanée.')], 'La capacitation précède la réaction acrosomique ; l’activation ovocytaire entraîne la réaction corticale et limite la polyspermie.', 'Quel processus cortical limite l’entrée de spermatozoïdes supplémentaires ?', 'La réaction corticale qui modifie la zone pellucide après l’activation ovocytaire.', '28-1-fertilization', 'Après la fusion du premier spermatozoïde, des granules ovocytaires libèrent leur contenu et la zone pellucide change. Quel mécanisme est décrit ?', 'La réaction corticale, mécanisme majeur de blocage de la polyspermie.', ['Où se déroule le plus souvent la fécondation ?', 'Quelle maturation fonctionnelle précède la réaction acrosomique ?', 'Quelle structure entoure l’ovocyte en dehors du cumulus ?', 'Quel ion déclenche notamment l’activation ovocytaire ?', 'Quel processus limite la polyspermie ?'], ['Dans l’ampoule tubaire.', 'La capacitation.', 'La zone pellucide.', 'Le calcium intracellulaire.', 'La réaction corticale.'], [['Dans la cavité utérine.', 'Dans le col utérin.', 'Dans l’ovaire.'], ['La spermiogenèse.', 'La gastrulation.', 'La nidation.'], ['La membrane basale.', 'La capsule rénale.', 'Le périchondre.'], ['Le sodium extracellulaire seul.', 'Le fer nucléaire.', 'Le potassium osseux.'], ['La réaction acrosomique seule.', 'La méiose I.', 'La segmentation.']])),
  make('embryo-implantation-decidualization', item('embryo-implantation-decidualization', ['Distinguer cytotrophoblaste et syncytiotrophoblaste', 'Décrire apposition, adhésion et invasion', 'Relier réaction déciduale et nutrition précoce'], [
    s('Adhésion au cours de la deuxième semaine', 'Après l’éclosion de la zone pellucide, le blastocyste s’appose à l’épithélium endométrial puis adhère et s’implante. La fenêtre d’implantation dépend de la réceptivité endométriale. L’orientation du blastocyste influence le site d’entrée, sans garantir une implantation normale.'),
    s('Différenciation trophoblastique', 'Le trophoblaste se différencie en cytotrophoblaste interne, constitué de cellules individualisées, et syncytiotrophoblaste externe multinucleé et invasif. Le syncytiotrophoblaste érode localement l’épithélium et le stroma, participe à l’établissement des lacunes et sécrète l’hCG détectable au début de grossesse.'),
    s('Disque didermique et cavités', 'L’embryoblaste s’organise en épiblaste et hypoblaste, constituant le disque didermique. Une cavité amniotique se forme au-dessus de l’épiblaste ; le sac vitellin se met en place du côté hypoblastique. Ces compartiments temporaires contribuent à l’organisation précoce de l’embryon.'),
    s('Réaction déciduale', 'Le stroma endométrial répond à l’implantation par une transformation déciduale, avec changements cellulaires, vasculaires et immunitaires locaux. Cette réaction soutient l’implantation et module les interactions materno-embryonnaires. Elle ne signifie pas que l’embryon est déjà vascularisé par un échange placentaire mature.'),
    s('Lacunes et limites', 'Les lacunes du syncytiotrophoblaste se remplissent progressivement de sang maternel lors de l’érosion de sinusoïdes endométriaux. Les échanges précoces évoluent au fil des semaines et la circulation placentaire fonctionnelle se met en place graduellement. Un saignement ou une douleur ne permettent pas à eux seuls de diagnostiquer une anomalie d’implantation.')], 'Le syncytiotrophoblaste envahit l’endomètre et sécrète l’hCG ; le cytotrophoblaste reste la couche cellulaire interne.', 'Quelles sont les deux couches trophoblastiques distinguées après l’implantation ?', 'Le cytotrophoblaste interne et le syncytiotrophoblaste externe.', '28-2-embryonic-development', 'Une hormone détectée précocement après l’implantation est sécrétée par le tissu trophoblastique invasif. Quelle couche est concernée ?', 'Le syncytiotrophoblaste sécrète l’hCG au début de la grossesse.', ['Quelles couches forment le trophoblaste différencié ?', 'Quelle hormone trophoblastique est détectée précocement ?', 'Quel feuillet forme le disque didermique avec l’hypoblaste ?', 'Quel compartiment se forme au-dessus de l’épiblaste ?', 'La réaction déciduale survient-elle dans le tissu maternel ou embryonnaire ?'], ['Cytotrophoblaste et syncytiotrophoblaste.', 'L’hCG.', 'L’épiblaste.', 'La cavité amniotique.', 'Dans le stroma endométrial maternel.'], [['Épiblaste et endoderme définitif.', 'Amnios et chorion.', 'Mésoderme et notochorde.'], ['La LH.', 'La TSH.', 'La FSH.'], ['Le trophoblaste.', 'Le syncytiotrophoblaste.', 'La zone pellucide.'], ['Le cœlome intra-embryonnaire.', 'Le canal neural.', 'Le blastocèle initial persistant.'], ['Dans les cellules du trophoblaste uniquement.', 'Dans le sac vitellin.', 'Dans le myomètre embryonnaire.']]))
]

const qb: Record<string, { prompts: string[]; answers: string[]; distractors: string[][] }> = {
  'embryo-early-cleavage-blastocyst': { prompts: ['Quel stade suit la morula ?', 'Quelle cavité apparaît dans le blastocyste ?', 'Quelle population externe contribue aux annexes embryonnaires ?', 'À quoi sert la zone pellucide durant le transport tubaire ?', 'Quel compartiment forme l’embryon proprement dit ?'], answers: ['Le blastocyste.', 'Le blastocèle.', 'Le trophoblaste.', 'Elle limite l’adhésion prématurée avant l’arrivée utérine.', 'La masse cellulaire interne, ou embryoblaste.'], distractors: [['La gastrula.', 'Le neurula.', 'Le fœtus.'], ['La cavité amniotique.', 'Le cœlome intra-embryonnaire.', 'Le canal neural.'], ['L’endoderme définitif.', 'Le mésoderme para-axial.', 'La notochorde.'], ['Elle forme le tube neural.', 'Elle constitue la paroi utérine.', 'Elle fabrique les gamètes.'], ['Le syncytiotrophoblaste seul.', 'La zone pellucide.', 'Le blastocèle.']] },
  'embryo-gastrulation-germ-layers': { prompts: ['Quel feuillet provient de l’épiblaste restant ?', 'Où apparaît la ligne primitive ?', 'Quelle structure axiale induit la plaque neurale ?', 'Quel feuillet forme surtout l’épithélium digestif ?', 'Quelle est l’origine de l’endoderme définitif ?'], answers: ['L’ectoderme.', 'Dans l’épiblaste caudal.', 'La notochorde.', 'L’endoderme.', 'Des cellules épiblastiques qui remplacent l’hypoblaste.'], distractors: [['L’endoderme.', 'Le mésoderme.', 'Le trophoblaste.'], ['Dans le trophoblaste.', 'Dans l’amnios.', 'Dans le sac vitellin.'], ['Le canal neurentérique.', 'L’allantoïde.', 'Le sac vitellin.'], ['L’ectoderme.', 'Le mésoderme para-axial.', 'La crête neurale.'], ['Des cellules trophoblastiques.', 'Des cellules hypoblastiques restées en place.', 'Des cellules de la notochorde.']] },
  'embryo-spermatogenesis-detail': { prompts: ['Quelle hormone stimule les cellules de Leydig ?', 'Quelles cellules forment la barrière hémato-testiculaire ?', 'Que sépare surtout la première division méiotique ?', 'La spermiogenèse augmente-t-elle le nombre de cellules ?', 'Où se trouvent les cellules de Leydig ?'], answers: ['La LH.', 'Les cellules de Sertoli.', 'Les chromosomes homologues.', 'Non, elle différencie les spermatides sans division.', 'Dans le tissu interstitiel entre les tubes séminifères.'], distractors: [['La FSH seule.', 'La prolactine.', 'L’ocytocine.'], ['Les spermatides.', 'Les cellules de Leydig.', 'Les cellules endothéliales seulement.'], ['Les chromatides sœurs.', 'Les centromères après mitose.', 'Les pronoyaux.'], ['Oui, elle comprend une mitose.', 'Oui, elle forme deux cellules diploïdes.', 'Oui, elle correspond à une méiose III.'], ['Dans la lumière des tubes.', 'Dans l’épididyme.', 'Dans les vésicules séminales.']] },
  'embryo-oogenesis-folliculogenesis': { prompts: ['À quel stade l’ovocyte I s’arrête-t-il avant la puberté ?', 'Quelle hormone déclenche le pic ovulatoire ?', 'Quelle cellule aromatise les androgènes en œstrogènes ?', 'Quel événement achève la méiose II ?', 'Quelle structure sécrète la progestérone après ovulation ?'], answers: ['En prophase I.', 'La LH.', 'Les cellules de la granulosa.', 'La fécondation.', 'Le corps jaune.'], distractors: [['En métaphase II.', 'En anaphase I.', 'En prophase II.'], ['La FSH seule.', 'La progestérone.', 'La prolactine.'], ['La thèque externe.', 'Le corps albicans.', 'Les cellules de Leydig.'], ['La nidation.', 'La menstruation.', 'La croissance folliculaire.'], ['Le follicule primordial.', 'La zone pellucide.', 'L’endomètre.']] },
  'embryo-fertilization-mechanisms': { prompts: ['Où se déroule le plus souvent la fécondation ?', 'Quelle maturation fonctionnelle précède la réaction acrosomique ?', 'Quelle structure entoure l’ovocyte sous le cumulus ?', 'Quel ion participe à l’activation ovocytaire ?', 'Quel processus limite la polyspermie ?'], answers: ['Dans l’ampoule tubaire.', 'La capacitation.', 'La zone pellucide.', 'Le calcium intracellulaire.', 'La réaction corticale.'], distractors: [['Dans la cavité utérine.', 'Dans le col utérin.', 'Dans l’ovaire.'], ['La spermiogenèse.', 'La gastrulation.', 'La nidation.'], ['La membrane basale.', 'La capsule rénale.', 'Le périchondre.'], ['Le sodium extracellulaire uniquement.', 'Le fer nucléaire.', 'Le potassium osseux.'], ['La méiose I.', 'La segmentation.', 'La réaction acrosomique seule.']] },
  'embryo-implantation-decidualization': { prompts: ['Quelles couches forment le trophoblaste différencié ?', 'Quelle hormone trophoblastique est détectée précocement ?', 'Quel feuillet forme le disque didermique avec l’hypoblaste ?', 'Quelle cavité se forme au-dessus de l’épiblaste ?', 'Où se produit la réaction déciduale ?'], answers: ['Cytotrophoblaste et syncytiotrophoblaste.', 'L’hCG.', 'L’épiblaste.', 'La cavité amniotique.', 'Dans le stroma endométrial maternel.'], distractors: [['Épiblaste et endoderme définitif.', 'Amnios et chorion.', 'Mésoderme et notochorde.'], ['La LH.', 'La TSH.', 'La FSH.'], ['Le trophoblaste.', 'Le syncytiotrophoblaste.', 'La zone pellucide.'], ['Le cœlome intra-embryonnaire.', 'Le canal neural.', 'Le blastocèle initial.'], ['Dans les cellules du trophoblaste uniquement.', 'Dans le sac vitellin.', 'Dans le myomètre embryonnaire.']] }
}
export const additionalEmbryologyQuestions: Question[] = additionalEmbryologyCourses.flatMap(course => qb[course.id].prompts.map((prompt, i) => {
  const options = [qb[course.id].answers[i], ...qb[course.id].distractors[i]]
  return { id: `${course.id}-q${i + 1}`, course: course.id, topic: 'Embryologie & Reproduction', prompt, options, correct: [0], why: options.map((_, j) => j === 0 ? `Cette réponse correspond au mécanisme embryologique décrit : ${qb[course.id].answers[i]}` : 'Cette proposition correspond à une autre étape ou structure.'), difficulty: i < 2 ? 'essentiel' as const : 'application' as const, format: 'single' as const }
}))
