import type { Course } from '../../curriculum'
import type { Question } from '../../questions'
import { canonicalCourses } from '../../taxonomy/canonicalCourses'

const metadata = new Map(canonicalCourses.filter(item => item.subject === 'Embryologie & Reproduction').map(item => [item.id, item]))
const base = 'https://openstax.org/books/anatomy-and-physiology-2e/pages/'
type Draft = { objectives: string[]; sections: Course['sections']; trap: string; recall: string; answer: string; source: string; caseStudy: NonNullable<Course['caseStudy']>; glossary: NonNullable<Course['glossary']> }
const s = (title: string, text: string, bullets?: string[]) => ({ title, text, ...(bullets ? { bullets } : {}) })
function course(id: string, d: Draft): Course {
  const c = metadata.get(id)
  if (!c) throw new Error(`Chapitre canonique d’embryologie introuvable : ${id}`)
  return { id, title: c.title, category: c.subject, tag: c.module, minutes: 14, structure: null, objectives: d.objectives,
    sections: d.sections, trap: d.trap, recall: d.recall, answer: d.answer, source: base + d.source,
    sources: [{ label: 'OpenStax · Anatomy & Physiology 2e', url: base + d.source }],
    prerequisites: ['Méiose et gamétogenèse', 'Organisation des feuillets embryonnaires'], glossary: d.glossary, caseStudy: d.caseStudy,
    review: { status: 'unreviewed', updatedAt: '2026-09-23', sourcesUpdatedAt: '2026-09-23' } }
}
export const embryologyCourses: Course[] = [
  course('embryo-placenta', {
    objectives: ['Décrire les composantes fœtale et maternelle du placenta', 'Expliquer les échanges sans mélange normal des circulations', 'Relier les fonctions placentaires au développement fœtal'],
    sections: [
      s('Origine et mise en place', 'Le placenta se développe à partir de tissus embryonnaires, notamment du chorion trophoblastique, et de la décidua basale maternelle. Les villosités choriales se ramifient et augmentent la surface d’échange. Le placenta est un organe d’interface en évolution, dont l’organisation se modifie au cours de la grossesse.'),
      s('Villosités et espace intervilleux', 'Les villosités contiennent des capillaires fœtaux et sont baignées par le sang maternel dans l’espace intervilleux. Le sang maternel arrive par les artères spiralées et repart par des veines utérines ; le sang fœtal circule dans des vaisseaux reliés aux artères et à la veine ombilicales. Les deux circulations sont proches mais normalement séparées par une barrière tissulaire.'),
      s('Échanges sélectifs', 'L’oxygène, le dioxyde de carbone, l’eau, certains nutriments et des déchets traversent par diffusion, transport facilité ou actif selon la molécule. Le transfert d’IgG maternelles fournit une immunité passive au fœtus. La barrière n’est pas une protection absolue : certains médicaments, toxiques et agents infectieux peuvent la franchir.'),
      s('Fonctions endocrines', 'Le trophoblaste sécrète notamment l’hCG au début de la grossesse, qui soutient le corps jaune. Le placenta produit ensuite progestérone et œstrogènes, et des hormones telles que l’hormone lactogène placentaire contribuent aux adaptations maternelles. La production dépend du stade gestationnel et de la coopération avec les tissus maternels.'),
      s('Circulation et conséquences cliniques', 'La circulation fœtale comporte deux artères ombilicales qui apportent au placenta un sang relativement pauvre en oxygène et une veine ombilicale qui ramène un sang plus oxygéné. Les échanges exigent une perfusion adéquate des deux côtés. Une insuffisance placentaire peut compromettre croissance et oxygénation ; elle ne se déduit pas d’un seul signe isolé.'),
    ], trap: 'Les sangs maternel et fœtal circulent dans des compartiments distincts : les échanges se font à travers une barrière, pas par mélange direct normal.', recall: 'Combien d’artères et de veines ombilicales existent habituellement, et dans quel sens transportent-elles le sang ?', answer: 'Deux artères ombilicales vont du fœtus vers le placenta ; une veine ombilicale ramène le sang du placenta vers le fœtus.', source: '28-6-embryonic-development', glossary: [['Chorion', 'Membrane extraembryonnaire externe contribuant à la composante fœtale du placenta.'], ['Décidua basale', 'Partie maternelle de l’endomètre transformé au site d’implantation.'], ['Espace intervilleux', 'Compartiment contenant le sang maternel au contact des villosités.']], caseStudy: { prompt: 'Pourquoi l’administration d’un médicament à la mère peut-elle exposer l’embryon ou le fœtus ?', answer: 'La barrière placentaire est sélective mais non absolue ; le passage dépend des propriétés du produit, de la dose, du terme et du transport placentaire.' } }),
  course('embryo-organogenesis', {
    objectives: ['Situer les périodes de développement prénatal', 'Relier les feuillets embryonnaires aux grandes lignées tissulaires', 'Comprendre les conséquences des fenêtres sensibles'],
    sections: [
      s('Périodes du développement', 'La période pré-embryonnaire couvre la fécondation, la segmentation et l’implantation ; la période embryonnaire correspond aux premières semaines de formation des principaux organes ; la période fœtale est dominée par croissance et maturation. Les limites calendaires dépendent du mode de datation, âge post-fécondation ou âge gestationnel obstétrical.'),
      s('Gastrulation et feuillets', 'La gastrulation établit les trois feuillets : ectoderme, mésoderme et endoderme. L’ectoderme contribue notamment à l’épiderme et au système nerveux ; le mésoderme aux muscles, os, tissu conjonctif, cœur et reins ; l’endoderme à l’épithélium de nombreuses voies digestives et respiratoires et à certaines glandes. Les organes associent des dérivés de plusieurs feuillets.'),
      s('Induction et organisation spatiale', 'Les tissus embryonnaires échangent des signaux inducteurs qui orientent différenciation et organisation. Gradients moléculaires, interactions cellule-cellule et propriétés mécaniques contribuent à l’identité des axes et des territoires. La destinée d’une cellule dépend de son origine, de sa position et des signaux reçus, pas seulement d’un feuillet pris isolément.'),
      s('Métamérisation et crêtes neurales', 'Le mésoderme para-axial se segmente en somites selon une progression contrôlée, puis chaque somite se régionalise en lignées contribuant à vertèbres et côtes, muscles squelettiques et derme selon les territoires. Les cellules des crêtes neurales migrent et contribuent à de nombreuses structures, dont des éléments du système nerveux périphérique et du squelette craniofacial.'),
      s('Fenêtres de sensibilité', 'La formation des organes est particulièrement sensible aux perturbations pendant des fenêtres temporelles précises, mais la vulnérabilité varie selon l’organe et l’agent. Avant certaines étapes, une exposition sévère peut provoquer perte embryonnaire ; plus tard, elle peut affecter croissance ou fonction. Ces principes ne permettent pas de prédire individuellement une issue sans évaluation clinique.'),
    ], trap: 'Un organe n’est généralement pas dérivé d’un seul feuillet : épithélium, stroma, vaisseaux et innervation peuvent avoir des origines différentes.', recall: 'Quels sont les trois feuillets embryonnaires et quel grand dérivé associer à chacun ?', answer: 'Ectoderme : système nerveux et épiderme ; mésoderme : muscles, os, cœur et tissu conjonctif ; endoderme : épithéliums digestif et respiratoire, avec nuances selon les organes.', source: '28-2-embryonic-development', glossary: [['Gastrulation', 'Processus établissant les feuillets embryonnaires et les axes précoces.'], ['Somite', 'Unité segmentaire issue du mésoderme para-axial.'], ['Induction', 'Signal d’un tissu modifiant la destinée ou le comportement d’un autre.']], caseStudy: { prompt: 'Pourquoi le calendrier d’une exposition tératogène est-il essentiel dans son évaluation ?', answer: 'Les organes passent par des fenêtres de formation et maturation différentes ; l’effet dépend du stade, de la dose et de l’agent, et ne peut être déduit du seul nom de l’exposition.' } }),
  course('embryo-gametogenesis', {
    objectives: ['Distinguer spermatogenèse et ovogenèse', 'Expliquer le devenir des cellules germinales primordiales', 'Relier méiose et formation de gamètes haploïdes'],
    sections: [
      s('Lignée germinale', 'Les cellules germinales primordiales sont spécifiées précocement puis migrent vers les crêtes génitales en développement. Elles colonisent les gonades où elles entrent dans des voies de différenciation distinctes. Leur migration, survie et prolifération sont essentielles à la formation des gamètes, mais le calendrier diffère entre ovaires et testicules.'),
      s('Spermatogenèse', 'Dans les tubes séminifères, les spermatogonies se renouvellent et certaines deviennent des spermatocytes qui effectuent la méiose. Chaque spermatocyte primaire conduit à quatre spermatides haploïdes, qui se différencient ensuite en spermatozoïdes lors de la spermiogenèse. Le soutien des cellules de Sertoli et les signaux hormonaux organisent la production continue après la puberté.'),
      s('Ovogenèse et réserve', 'Les ovogonies prolifèrent durant le développement fœtal puis les ovocytes primaires entrent en méiose et restent bloqués en prophase I. À partir de la puberté, certains reprennent leur maturation au cours des cycles ; la méiose I produit un ovocyte secondaire et un globule polaire. La méiose II ne s’achève habituellement qu’en cas de fécondation.'),
      s('Division asymétrique', 'L’ovogenèse conserve l’essentiel du cytoplasme dans une cellule fonctionnelle, tandis que les globules polaires reçoivent peu de cytoplasme. La spermatogenèse répartit plus équitablement le cytoplasme de la cellule, puis remodèle fortement les spermatides. Ces stratégies répondent à des fonctions différentes du gamète femelle et du gamète mâle.'),
      s('Contrôle endocrinien et fertilité', 'La FSH et la LH contribuent à réguler les gonades via l’axe hypothalamo-hypophysaire, avec des effets dépendant du sexe, de l’âge et du stade. La gamétogenèse exige aussi un environnement gonadique approprié, une méiose fidèle et une maturation fonctionnelle. Une anomalie de fertilité peut résulter de nombreux niveaux et nécessite une évaluation adaptée.'),
    ], trap: 'L’ovocyte secondaire libéré lors de l’ovulation n’a pas achevé la méiose II ; celle-ci est déclenchée par la fécondation.', recall: 'Combien de gamètes fonctionnels résultent habituellement d’un spermatocyte primaire et d’un ovocyte primaire ?', answer: 'Un spermatocyte primaire produit quatre spermatides haploïdes ; un ovocyte primaire produit un grand gamète fonctionnel et des globules polaires.', source: '27-2-anatomy-and-physiology-of-the-male-reproductive-system', glossary: [['Cellule germinale primordiale', 'Précurseur embryonnaire de la lignée germinale.'], ['Spermiogenèse', 'Différenciation des spermatides en spermatozoïdes.'], ['Globule polaire', 'Petite cellule haploïde recevant peu de cytoplasme lors de divisions ovocytaires.']], caseStudy: { prompt: 'Un ovocyte secondaire est fécondé. Quel événement méiotique se termine alors ?', answer: 'La méiose II, conduisant à l’ovule et au second globule polaire.' } }),
]
const prompts: Record<string, string[]> = {
  'embryo-placenta': ['Quelle est l’origine générale des deux composantes placentaires ?', 'Où circule le sang maternel au contact des villosités ?', 'Les circulations maternelle et fœtale se mélangent-elles normalement directement ?', 'Quel rôle joue l’hCG au début de grossesse ?', 'Combien d’artères ombilicales et de veines ombilicales sont habituelles ?'],
  'embryo-organogenesis': ['Quels trois feuillets sont établis pendant la gastrulation ?', 'Quel feuillet contribue au système nerveux central ?', 'Les organes dérivent-ils toujours d’un seul feuillet ?', 'Que sont les somites ?', 'Pourquoi une fenêtre sensible dépend-elle du terme ?'],
  'embryo-gametogenesis': ['Combien de spermatides proviennent normalement d’un spermatocyte primaire ?', 'À quel stade l’ovocyte primaire reste-t-il bloqué avant la puberté ?', 'Quand s’achève habituellement la méiose II de l’ovocyte ?', 'Quel est le rôle de la spermiogenèse ?', 'Que deviennent les globules polaires ?'],
}
const answers: Record<string, string[]> = {
  'embryo-placenta': ['La composante fœtale vient du chorion trophoblastique et la composante maternelle de la décidua basale.', 'Dans l’espace intervilleux.', 'Non, elles sont séparées par une barrière placentaire à travers laquelle se font les échanges.', 'Elle soutient le corps jaune en début de grossesse.', 'Deux artères vont du fœtus au placenta et une veine revient du placenta vers le fœtus.'],
  'embryo-organogenesis': ['Ectoderme, mésoderme et endoderme.', 'L’ectoderme.', 'Non, plusieurs feuillets contribuent souvent aux tissus d’un organe.', 'Des unités segmentaires issues du mésoderme para-axial.', 'Les organes ne se forment pas tous en même temps et leur susceptibilité change pendant leur développement.'],
  'embryo-gametogenesis': ['Quatre spermatides haploïdes.', 'En prophase I de méiose.', 'Habituellement lors de la fécondation.', 'La différenciation morphologique des spermatides en spermatozoïdes.', 'Ils reçoivent peu de cytoplasme et ne deviennent pas des gamètes fonctionnels.'],
}
const distractors = ['Elle se déroule entièrement après la naissance.', 'Elle ne requiert aucune division cellulaire.', 'Elle rend les deux circulations identiques.', 'Elle conduit toujours à quatre cellules équivalentes.']
export const embryologyQuestions: Question[] = embryologyCourses.flatMap((c, ci) => prompts[c.id].map((prompt, qi) => {
  const answer = answers[c.id][qi]
  const options = [answer, distractors[(qi + ci) % 4], distractors[(qi + ci + 1) % 4], distractors[(qi + ci + 2) % 4]]
  return { id: `${c.id}-q${qi + 1}`, course: c.id, topic: c.category, prompt, options, correct: [0],
    why: options.map((option, oi) => oi === 0 ? answer : `${option} Cette formulation contredit l’organisation décrite dans le cours.`), difficulty: qi < 2 ? 'essentiel' as const : 'application' as const, format: 'single' as const }
}))
