import type { Course } from '../../curriculum'
import type { Question } from '../../questions'
import { canonicalCourses } from '../../taxonomy/canonicalCourses'

const metadata = new Map(canonicalCourses.filter(item => item.subject === 'Biostatistiques').map(item => [item.id, item]))
const base = 'https://openstax.org/books/introductory-statistics/pages/'
type Draft = { objectives: string[]; sections: Course['sections']; trap: string; recall: string; answer: string; source: string; learning?: Course['learning']; caseStudy: NonNullable<Course['caseStudy']>; glossary: NonNullable<Course['glossary']> }
const s = (title: string, text: string, bullets?: string[]) => ({ title, text, ...(bullets ? { bullets } : {}) })
function course(id: string, d: Draft): Course {
  const c = metadata.get(id)
  if (!c) throw new Error(`Chapitre canonique de biostatistiques introuvable : ${id}`)
  return { id, title: c.title, category: c.subject, tag: c.module, minutes: 15, structure: null,
    objectives: d.objectives, sections: d.sections, trap: d.trap, recall: d.recall, answer: d.answer,
    source: base + d.source, sources: [{ label: 'OpenStax · Introductory Statistics', url: base + d.source }],
    prerequisites: ['Fractions, pourcentages et proportionnalité', 'Lecture de tableaux et graphiques'],
    ...(d.learning ? { learning: d.learning } : {}), glossary: d.glossary, caseStudy: d.caseStudy,
    review: { status: 'unreviewed', updatedAt: '2026-09-23', sourcesUpdatedAt: '2026-09-23' } }
}
export const statisticsCourses: Course[] = [
  course('stats-diagnostic-tests', {
    objectives: ['Calculer sensibilité et spécificité', 'Distinguer valeur prédictive positive et négative', 'Appliquer un raisonnement bayésien à un dépistage'],
    sections: [
      s('Table de contingence', 'Un test diagnostique compare le résultat à un état de référence dans une population définie. La table distingue vrais positifs, faux positifs, vrais négatifs et faux négatifs. Sensibilité et spécificité conditionnent les résultats à l’état de référence, tandis que les valeurs prédictives conditionnent le statut réel au résultat du test.'),
      s('Sensibilité et spécificité', 'La sensibilité est la proportion de personnes malades dont le test est positif : VP/(VP+FN). La spécificité est la proportion de personnes non malades dont le test est négatif : VN/(VN+FP). Un test très sensible réduit les faux négatifs ; un test très spécifique réduit les faux positifs, dans la population et au seuil étudiés.'),
      s('Valeurs prédictives', 'La valeur prédictive positive vaut VP/(VP+FP) et la valeur prédictive négative VN/(VN+FN). Elles répondent à la question après connaître le résultat. Elles dépendent fortement de la prévalence ou probabilité prétest : lorsque la maladie est rare, les faux positifs peuvent représenter une part importante des tests positifs malgré une bonne spécificité.'),
      s('Bayes en effectifs naturels', 'Pour rendre le raisonnement concret, choisir une cohorte hypothétique de 1 000 personnes. Appliquer la prévalence pour répartir malades et non malades, puis sensibilité et spécificité dans chaque groupe. La VPP est le nombre de vrais positifs divisé par tous les positifs. Cette méthode évite d’inverser les probabilités conditionnelles.'),
      s('Seuil et usage clinique', 'Déplacer le seuil d’un test continu modifie souvent le compromis sensibilité-spécificité. Le choix dépend du coût des faux négatifs et faux positifs, de l’objectif — dépister ou confirmer —, des traitements disponibles et du parcours de confirmation. Les performances publiées doivent correspondre à la population et au contexte d’utilisation.'),
    ], trap: 'Une sensibilité de 95 % signifie P(test positif | maladie), pas P(maladie | test positif).', recall: 'Prévalence 1 %, sensibilité 90 %, spécificité 95 % : quelle VPP approximative sur 1 000 personnes ?', answer: 'Sur 1 000, 10 sont malades : 9 vrais positifs. Parmi 990 non malades, 5 % soit 49,5 sont faux positifs. VPP ≈ 9/(9+49,5) ≈ 15,4 %.', source: '8-4-calc-the-test-statistic', learning: { formula: { label: 'Valeurs prédictives', expression: 'VPP = VP/(VP+FP) ; VPN = VN/(VN+FN)', explanation: 'Le dénominateur rassemble les personnes ayant le résultat considéré ; ces probabilités varient avec la prévalence.' }, comparison: { headers: ['Mesure', 'Conditionnement', 'Question'], rows: [['Sensibilité', 'Parmi les malades', 'Quelle part est détectée ?'], ['Spécificité', 'Parmi les non-malades', 'Quelle part est correctement négative ?'], ['VPP', 'Parmi les tests positifs', 'Quelle part est malade ?'], ['VPN', 'Parmi les tests négatifs', 'Quelle part est non malade ?']] }, example: { prompt: 'Sur 1 000 personnes, 10 malades ; sensibilité 90 %, spécificité 95 %.', steps: ['VP = 9 ; FN = 1.', 'VN = 940,5 ; FP = 49,5.', 'VPP = 9/(9+49,5).'], result: 'VPP ≈ 15,4 % ; l’arrondi des effectifs fractionnaires rappelle que les performances sont des proportions attendues.' }, errors: [{ title: 'Inverser les conditionnelles', detail: 'P(test+ | malade) et P(malade | test+) ne sont pas la même probabilité ; utiliser une table 2×2.' }] }, glossary: [['Vrai positif', 'Test positif chez une personne classée malade par la référence.'], ['Faux négatif', 'Test négatif chez une personne malade selon la référence.'], ['Probabilité prétest', 'Estimation de probabilité avant de connaître le résultat du test.']], caseStudy: { prompt: 'Un dépistage est utilisé dans une population où la maladie est très rare. Pourquoi un résultat positif peut-il nécessiter confirmation ?', answer: 'La faible prévalence réduit la VPP ; parmi les tests positifs, une proportion notable peut être constituée de faux positifs malgré une bonne spécificité.' }
  }),
  course('stats-study-design', {
    objectives: ['Distinguer cohortes, cas-témoins et essais randomisés', 'Identifier temporalité et mesure d’association adaptées', 'Repérer biais et facteurs de confusion'],
    sections: [
      s('Question, population et exposition', 'Le choix du plan d’étude part d’une question explicite : exposition, intervention, comparateur, population et résultat. Les critères d’inclusion définissent à qui les conclusions s’appliquent. La temporalité entre exposition et événement est centrale pour interpréter causalité et biais.'),
      s('Étude de cohorte', 'Une cohorte suit des personnes définies selon exposition, puis observe la survenue d’issues. Elle permet de mesurer incidence et risque, et de calculer un risque relatif dans des conditions appropriées. Elle peut être prospective ou rétrospective ; pertes de suivi, changements d’exposition et confusion peuvent affecter les résultats.'),
      s('Étude cas-témoins', 'Une étude cas-témoins sélectionne des personnes selon la présence ou non de l’issue, puis compare les expositions antérieures. Elle est utile pour des événements rares ou à longue latence. L’odds ratio est la mesure d’association usuelle ; biais de sélection et mémoire des expositions doivent être examinés.'),
      s('Essai randomisé contrôlé', 'Dans un essai randomisé, l’allocation aléatoire vise à équilibrer en moyenne facteurs connus et inconnus entre groupes. Le contrôle, l’aveugle lorsque possible et l’analyse selon l’assignation initiale limitent certains biais. La randomisation ne garantit pas une exécution parfaite, et les résultats peuvent manquer de puissance ou de généralisabilité.'),
      s('Association, causalité et biais', 'Confusion, sélection, information, causalité inverse et hasard peuvent expliquer une association observée. La temporalité, la plausibilité, la cohérence avec d’autres études et des analyses robustes contribuent à l’évaluation causale sans transformer un seul critère en preuve. Il faut aussi distinguer significativité statistique, taille d’effet et pertinence clinique.'),
    ], trap: 'Un odds ratio d’étude cas-témoins ne se lit pas automatiquement comme un risque relatif, surtout si l’issue est fréquente.', recall: 'Pourquoi une étude cas-témoins est-elle efficace pour étudier une maladie rare ?', answer: 'Elle sélectionne directement un nombre suffisant de cas puis des témoins, plutôt que de suivre une cohorte très grande jusqu’à observer peu d’événements.', source: '1-3-data-collection-experiment-and-sampling', glossary: [['Confusion', 'Distorsion d’une association par un facteur lié à l’exposition et à l’issue.'], ['Randomisation', 'Attribution aléatoire d’une intervention pour équilibrer les groupes en moyenne.'], ['Odds ratio', 'Rapport de cotes d’exposition ou d’issue entre groupes, selon le plan.']], caseStudy: { prompt: 'Une étude cas-témoins trouve une association entre médicament et maladie. Quel biais lié au recueil rétrospectif est à envisager ?', answer: 'Un biais de mémorisation : cas et témoins peuvent rapporter différemment une exposition antérieure.' } }),
  course('stats-confidence-intervals', {
    objectives: ['Interpréter un intervalle de confiance', 'Distinguer significativité statistique et importance clinique', 'Comprendre l’effet de taille d’échantillon et variabilité'],
    sections: [
      s('Estimation et incertitude', 'Une statistique calculée sur un échantillon estime un paramètre de population et varie d’un échantillon à l’autre. Un intervalle de confiance reflète cette incertitude selon une méthode et des hypothèses précises. Un intervalle étroit indique une précision plus élevée dans le modèle, pas l’absence de biais systématique.'),
      s('Interprétation fréquentiste', 'Un intervalle de confiance à 95 % signifie que si l’on répétait le plan d’échantillonnage et la méthode un grand nombre de fois, environ 95 % des intervalles construits contiendraient le paramètre fixe. Après calcul d’un intervalle particulier, on ne décrit pas en fréquentiste la probabilité du paramètre comme étant 95 % dans cet intervalle.'),
      s('Valeur p et hypothèse nulle', 'La valeur p est la probabilité, sous une hypothèse nulle et les autres hypothèses du modèle, d’observer un résultat au moins aussi extrême que celui obtenu. Elle n’est ni la probabilité que l’hypothèse nulle soit vraie ni la taille de l’effet. Elle dépend de l’effet, de la variabilité, de la taille d’échantillon et du plan.'),
      s('Significativité clinique', 'Une petite différence peut devenir statistiquement significative dans un grand échantillon sans importance clinique ; un effet potentiellement important peut rester imprécis dans un petit échantillon. Interpréter taille d’effet, intervalle, risques absolus, conséquences, coûts et préférences. Les critères de pertinence doivent être définis indépendamment du seuil de p.'),
      s('Multiplicité et rapport complet', 'Tester de nombreuses hypothèses augmente la chance de résultats fortuits. Préspécification, correction de multiplicité, transparence des analyses et réplication réduisent les interprétations sélectives. Présenter estimations et intervalles rend l’incertitude plus informative qu’une simple dichotomie significatif/non significatif.'),
    ], trap: 'p > 0,05 ne prouve pas l’absence d’effet ; l’étude peut être trop imprécise pour exclure des effets pertinents.', recall: 'Comment interpréter un IC fréquentiste à 95 % sans dire que le paramètre a 95 % de chances d’y être ?', answer: 'La procédure produirait des intervalles contenant le paramètre dans environ 95 % des répétitions, sous les hypothèses du modèle.', source: '8-2-a-single-population-mean-using-the-student-t-distribution', glossary: [['Précision', 'Degré d’incertitude aléatoire d’une estimation.'], ['Valeur p', 'Probabilité conditionnelle sous l’hypothèse nulle d’un résultat au moins aussi extrême.'], ['Taille d’effet', 'Quantification de l’ampleur d’une différence ou association.']], caseStudy: { prompt: 'Un essai rapporte p = 0,04 pour un effet très faible avec un intervalle étroit. Que faut-il examiner avant de conclure à un bénéfice important ?', answer: 'La taille d’effet absolue, l’intervalle de confiance, la pertinence clinique prédéfinie, les risques, le plan et la multiplicité des analyses.' } }),
]
const prompts: Record<string, string[]> = {
  'stats-diagnostic-tests': ['Quelle formule définit la sensibilité ?', 'Quelle mesure répond à P(maladie | test positif) ?', 'La VPP reste-t-elle constante lorsque la prévalence change ?', 'Sur 1 000 personnes dont 1 % sont malades, combien de malades si la sensibilité est 90 % ?', 'Que désigne un faux négatif ?'],
  'stats-study-design': ['Dans quel plan sélectionne-t-on les participants selon la présence de la maladie ?', 'Quel plan permet directement d’estimer une incidence dans une population suivie ?', 'Que cherche à équilibrer la randomisation ?', 'Quelle mesure est habituelle en étude cas-témoins ?', 'Citez un biais possible de rappel.'],
  'stats-confidence-intervals': ['Que signifie un IC fréquentiste à 95 % ?', 'La valeur p est-elle la probabilité que l’hypothèse nulle soit vraie ?', 'Que suggère un grand IC ?', 'Une valeur p faible prouve-t-elle une importance clinique ?', 'Que signifie p > 0,05 à elle seule ?'],
}
const answers: Record<string, string[]> = {
  'stats-diagnostic-tests': ['VP/(VP+FN), proportion de malades testés positifs.', 'La valeur prédictive positive.', 'Non, elle varie notamment avec la prévalence.', 'Environ 9 vrais positifs attendus.', 'Un test négatif chez une personne malade selon la référence.'],
  'stats-study-design': ['L’étude cas-témoins.', 'Une étude de cohorte avec suivi adéquat.', 'À répartir les facteurs pronostiques en moyenne entre groupes.', 'L’odds ratio.', 'Les cas peuvent se souvenir ou rapporter différemment une exposition que les témoins.'],
  'stats-confidence-intervals': ['La procédure d’échantillonnage produirait des intervalles contenant le paramètre dans environ 95 % des répétitions, sous les hypothèses.', 'Non, elle est calculée conditionnellement à l’hypothèse nulle et au modèle.', 'Une estimation moins précise ou un effectif informatif plus faible.', 'Non, il faut examiner l’ampleur et la pertinence de l’effet.', 'Que les données ne permettent pas de rejeter le modèle nul au seuil choisi ; cela ne prouve pas l’absence d’effet.'],
}
const distractors = ['Elle donne directement la probabilité que le traitement guérisse.', 'Elle est indépendante du plan et de la population.', 'Elle élimine tous les biais de sélection et de mesure.', 'Elle garantit une relation causale sans hypothèse supplémentaire.']
export const statisticsQuestions: Question[] = statisticsCourses.flatMap((c, ci) => prompts[c.id].map((prompt, qi) => {
  const answer = answers[c.id][qi]
  const options = [answer, distractors[(qi + ci) % 4], distractors[(qi + ci + 1) % 4], distractors[(qi + ci + 2) % 4]]
  return { id: `${c.id}-q${qi + 1}`, course: c.id, topic: c.category, prompt, options, correct: [0],
    why: options.map((option, oi) => oi === 0 ? answer : `${option} Cette interprétation ne correspond pas à la définition statistique demandée.`), difficulty: qi < 2 ? 'essentiel' as const : 'application' as const, format: 'single' as const }
}))
