import type { Course } from '../../curriculum'
import type { Question } from '../../questions'
import { canonicalCourses } from '../../taxonomy/canonicalCourses'

const meta = new Map(canonicalCourses.filter(item => item.subject === 'Anatomie').map(item => [item.id, item]))
const vessels = 'https://openstax.org/books/anatomy-and-physiology-2e/pages/20-5-circulatory-pathways'
const liver = 'https://openstax.org/books/anatomy-and-physiology-2e/pages/23-6-accessory-organs-in-digestion-the-liver-pancreas-and-gallbladder'
const intestine = 'https://openstax.org/books/anatomy-and-physiology-2e/pages/23-5-the-small-and-large-intestines'
type D = { objectives: string[]; sections: Course['sections']; trap: string; recall: string; answer: string; source: string; glossary: NonNullable<Course['glossary']>; caseStudy: NonNullable<Course['caseStudy']> }
const s = (title: string, text: string) => ({ title, text })
const make = (id: string, d: D): Course => {
  const c = meta.get(id); if (!c) throw new Error(`Identifiant anatomique absent : ${id}`)
  return { id, title: c.title, category: c.subject, tag: c.module, minutes: 15, structure: null, objectives: d.objectives,
    sections: d.sections, trap: d.trap, recall: d.recall, answer: d.answer, source: d.source, sources: [{ label: 'OpenStax · Anatomy & Physiology 2e', url: d.source }],
    prerequisites: ['Topographie abdominale et péritonéale', 'Anatomie digestive et vasculaire de base'], glossary: d.glossary, caseStudy: d.caseStudy,
    review: { status: 'unreviewed', updatedAt: '2026-09-23', sourcesUpdatedAt: '2026-09-23' } }
}
export const abdominalCourses: Course[] = [
  make('anat-thoracic-aorta-azygos', {
    objectives: ['Suivre l’aorte thoracique descendante et ses principales branches', 'Décrire le système azygos et ses communications', 'Situer le conduit thoracique dans le médiastin'],
    sections: [
      s('Aorte thoracique descendante', 'L’aorte descendante commence après l’arche aortique à gauche du corps de T4, descend dans le médiastin postérieur puis traverse le hiatus aortique du diaphragme vers T12 pour devenir l’aorte abdominale. Elle est à gauche des corps vertébraux, en arrière du hile pulmonaire gauche et à proximité de l’œsophage selon les niveaux.'),
      s('Branches pariétales et viscérales', 'Les branches pariétales comprennent les artères intercostales postérieures des espaces inférieurs, subcostales et phréniques supérieures. Les branches viscérales incluent bronchiques, œsophagiennes, médiastinales et péricardiques. Des variations sont fréquentes, notamment pour les artères bronchiques.'),
      s('Système azygos', 'La veine azygos remonte à droite des corps vertébraux, reçoit des veines intercostales postérieures puis forme une crosse au-dessus de la racine pulmonaire droite pour se jeter dans la veine cave supérieure. À gauche, hémi-azygos et hémi-azygos accessoire drainent des veines intercostales et rejoignent l’azygos à des niveaux variables.'),
      s('Conduit thoracique', 'Le conduit thoracique monte depuis la citerne du chyle lorsqu’elle est identifiable, traverse le hiatus aortique et chemine dans le médiastin postérieur entre l’aorte et l’azygos, en arrière de l’œsophage. Il croise vers la gauche au thorax supérieur et se termine à l’angle veineux jugulo-subclavier gauche. Il draine la majeure partie de la lymphe corporelle.'),
      s('Communications et repères', 'Les réseaux azygos offrent une voie collatérale entre systèmes cave supérieur et inférieur. Les veines intercostales postérieures droites rejoignent surtout l’azygos ; les gauches empruntent hémi-azygos ou accessoire selon leur niveau. Les rapports aorte-œsophage-conduit sont utiles en imagerie médiastinale mais changent avec la respiration et les variantes.'),
    ], trap: 'Le conduit thoracique se termine habituellement à l’angle veineux gauche ; l’azygos forme sa crosse au-dessus du hile pulmonaire droit.', recall: 'Quel territoire lymphatique rejoint le conduit thoracique ?', answer: 'La majeure partie du corps, à l’exception classique du quadrant supérieur droit qui se draine dans le conduit lymphatique droit.', source: vessels, glossary: [['Veine azygos', 'Voie veineuse longitudinale droite reliant des réseaux cave inférieur et supérieur.'], ['Hémi-azygos', 'Voie veineuse longitudinale gauche drainant des espaces intercostaux inférieurs.'], ['Angle veineux', 'Jonction entre veines jugulaire interne et subclavière.']], caseStudy: { prompt: 'Une obstruction de la veine cave supérieure peut recruter une voie collatérale thoracique. Quel système veineux peut contribuer à cette dérivation ?', answer: 'Le système azygos, qui communique avec des réseaux caves et peut détourner une partie du retour thoracique.' }
  }),
  make('anat-hepatic-segmentation-couinaud', {
    objectives: ['Décrire la segmentation fonctionnelle en huit segments', 'Relier pédicules portaux et veines hépatiques', 'Repérer les éléments du ligament hépatoduodénal'],
    sections: [
      s('Organisation fonctionnelle', 'La segmentation de Couinaud décrit huit territoires hépatiques fonctionnels, chacun associé à une branche portale, une branche artérielle hépatique et un canal biliaire de second ordre. Les plans intersegmentaires suivent surtout les veines hépatiques. Cette organisation diffère du simple partage morphologique en lobes droit et gauche visibles en surface.'),
      s('Plans et numérotation', 'Les segments II et III occupent le secteur latéral gauche, IV le secteur médial gauche, V et VIII le secteur antérieur droit, VI et VII le secteur postérieur droit. Le segment I correspond au lobe caudé, postérieur, souvent à drainage veineux direct vers la cave. La numérotation décrit des unités chirurgicales et radiologiques.'),
      s('Pédicule portal', 'La veine porte se divise en branches droite et gauche à l’entrée du foie ; avec l’artère hépatique et les voies biliaires, leurs branches cheminent au centre des segments dans les pédicules portaux. Les territoires sont donc vascularisés et drainés biliairement de façon relativement indépendante. Les variations artérielles sont fréquentes et importantes en chirurgie.'),
      s('Veines hépatiques', 'Les veines hépatiques droite, moyenne et gauche cheminent dans les fissures intersegmentaires et se jettent directement dans la veine cave inférieure. Elles séparent des territoires portaux adjacents. Le segment I peut avoir des veines courtes propres vers la cave et reçoit des branches portales des deux côtés.'),
      s('Pédicule hépatique', 'Dans le ligament hépatoduodénal, la veine porte est postérieure ; l’artère hépatique propre est antérieure à gauche et le conduit biliaire principal antérieur à droite dans le repère classique. Ces éléments constituent la triade portale. Les rapports et branches varient ; les gestes de clampage ou d’exploration relèvent de pratiques spécialisées.'),
    ], trap: 'Les branches portales sont centrales dans les segments ; les veines hépatiques cheminent plutôt entre segments.', recall: 'Quel segment correspond au lobe caudé et quel est son drainage veineux typique ?', answer: 'Le segment I ; il peut se drainer directement dans la veine cave inférieure par des veines hépatiques courtes.', source: liver, glossary: [['Segment hépatique', 'Unité fonctionnelle recevant un pédicule portal et possédant un drainage biliaire.'], ['Pédicule portal', 'Association d’une branche portale, artérielle hépatique et biliaire.'], ['Fissure intersegmentaire', 'Plan contenant généralement une veine hépatique séparant des territoires portaux.']], caseStudy: { prompt: 'Une résection limitée suit un territoire portal tout en préservant les veines hépatiques de drainage. Quelle logique anatomique est appliquée ?', answer: 'Les branches portales sont centrales dans chaque segment, tandis que les veines hépatiques marquent plutôt les plans entre segments.' }
  }),
  make('anat-biliary-tree-vesicle', {
    objectives: ['Suivre les voies biliaires intra- et extra-hépatiques', 'Décrire les rapports du canal cystique et du cholédoque', 'Relier anatomie de la vésicule aux voies pancréatiques'],
    sections: [
      s('Voies intrahépatiques', 'Les canalicules biliaires entre hépatocytes recueillent la bile et la conduisent vers des canaux de plus en plus grands dans les espaces portes. Les canaux hépatiques droit et gauche quittent le foie au hile et s’unissent pour former le canal hépatique commun. Le drainage segmentaire varie et peut comporter des conduits accessoires.'),
      s('Vésicule et canal cystique', 'La vésicule biliaire occupe une fosse sur la face viscérale du foie et comprend fundus, corps et col. Le canal cystique relie son col au canal hépatique commun ; des replis spiralés muqueux en modulent la lumière. L’union du cystique et de l’hépatique commun forme le cholédoque.'),
      s('Trajet du cholédoque', 'Le cholédoque descend dans le ligament hépatoduodénal, généralement à droite de l’artère hépatique propre et en avant de la veine porte, puis passe derrière la première portion du duodénum et dans ou derrière la tête pancréatique. Il s’unit souvent au conduit pancréatique principal avant l’ampoule hépatopancréatique et la papille majeure.'),
      s('Triangle hépatocystique', 'Le triangle hépatocystique est délimité par canal cystique, canal hépatique commun et face inférieure du foie. L’artère cystique chemine souvent dans cette région et irrigue la vésicule. Les variations vasculaires et biliaires sont fréquentes ; l’identification anatomique précise est essentielle en chirurgie, sans pouvoir être remplacée par une règle simplifiée.'),
      s('Fonction et repères', 'Entre les repas, la bile peut être stockée et concentrée dans la vésicule ; après un repas, la contraction vésiculaire et le relâchement du sphincter d’Oddi favorisent son arrivée dans le duodénum. La bile est produite par le foie, la vésicule ne la fabrique pas. L’imagerie permet d’évaluer calculs et dilatation des voies.'),
    ], trap: 'Le foie produit la bile ; la vésicule la stocke et la concentre entre les repas.', recall: 'Quel conduit naît de la réunion du canal cystique et du canal hépatique commun ?', answer: 'Le canal cholédoque (canal biliaire commun).', source: liver, glossary: [['Canal hépatique commun', 'Conduit formé par réunion des canaux hépatiques droit et gauche.'], ['Canal cystique', 'Conduit reliant le col vésiculaire au canal hépatique commun.'], ['Ampoule hépatopancréatique', 'Union fréquente du cholédoque et du conduit pancréatique avant la papille majeure.']], caseStudy: { prompt: 'Un calcul migre du canal cystique vers le cholédoque. Quelle structure peut être obstruée à proximité de la tête pancréatique ?', answer: 'Le cholédoque passe dans ou derrière la tête du pancréas et peut être comprimé ou obstrué dans cette région.' }
  }),
  make('anat-colon-rectum', {
    objectives: ['Suivre les segments du gros intestin', 'Décrire les caractéristiques macroscopiques du côlon', 'Expliquer les rapports péritonéaux et la vascularisation principale'],
    sections: [
      s('Cæcum et appendice', 'Le cæcum est la poche initiale du gros intestin sous l’abouchement iléal, généralement dans la fosse iliaque droite. L’appendice vermiforme naît de sa face postéromédiale près de la convergence des taeniae coli ; sa position est variable, souvent rétro-cæcale ou pelvienne. Son mésoappendice porte les vaisseaux appendiculaires.'),
      s('Côlon ascendant et transverse', 'Le côlon ascendant remonte du cæcum au foie et forme la flexure colique droite ; il est secondairement rétropéritonéal dans la plupart des cas. Le transverse traverse l’abdomen entre flexures droite et gauche et possède un mésocôlon transverse. Les rapports varient avec la distension, la respiration et la morphologie.'),
      s('Côlon descendant et sigmoïde', 'Le côlon descendant descend le long du flanc gauche, généralement secondairement rétropéritonéal, puis le sigmoïde possède un mésosigmoïde et rejoint le rectum au niveau de S3. Les taeniae coli, haustrations et appendices épiploïques caractérisent le côlon ; les taeniae s’élargissent et fusionnent au rectum.'),
      s('Rectum et canal anal', 'Le rectum suit la concavité sacrée dans le pelvis, présente des courbures et des ampoules transverses, puis se continue par le canal anal. Il est dépourvu de taeniae et d’appendices épiploïques. Le péritoine recouvre sa partie supérieure différemment chez les sexes et forme des récessus, tandis que le tiers inférieur est sous-péritonéal.'),
      s('Vascularisation et drainage', 'Le côlon proximal dépend surtout de l’artère mésentérique supérieure via iléo-colique, colique droite variable et colique moyenne ; le côlon distal dépend de l’artère mésentérique inférieure via colique gauche et sigmoïdiennes. Les réseaux marginals anastomosent ces territoires. Le drainage veineux suit les axes vers système porte ; les lymphatiques progressent le long des vaisseaux.'),
    ], trap: 'Le côlon possède des taeniae et des haustrations ; le rectum n’a pas ces bandelettes longitudinales distinctes.', recall: 'Quel repère aide à localiser la base de l’appendice ?', answer: 'La convergence des trois taeniae coli sur le cæcum.', source: intestine, glossary: [['Taenia coli', 'Bandelette longitudinale de muscle lisse caractéristique du côlon.'], ['Haustration', 'Sacculation du côlon produite par le tonus des taeniae.'], ['Mésosigmoïde', 'Méso suspendant le côlon sigmoïde et portant ses vaisseaux.']], caseStudy: { prompt: 'Pourquoi la convergence des taeniae coli est-elle un repère utile pour retrouver la base appendiculaire ?', answer: 'Les trois bandelettes convergent sur le cæcum à la base de l’appendice, quelle que soit la position distale variable de celui-ci.' }
  }),
  make('anat-celiac-trunk-mesenteric-arteries', {
    objectives: ['Nommer les branches principales du tronc cœliaque', 'Associer les axes mésentériques aux territoires intestinaux', 'Relier vascularisation embryologique et anastomoses'],
    sections: [
      s('Aorte abdominale', 'L’aorte traverse le hiatus aortique à T12, descend en avant des corps vertébraux et se divise en artères iliaques communes vers L4. Ses branches viscérales impaires sont tronc cœliaque, mésentérique supérieure et mésentérique inférieure ; les paires incluent notamment rénales et gonadiques.'),
      s('Tronc cœliaque', 'Le tronc cœliaque naît peu après le hiatus et se divise habituellement en artères gastrique gauche, hépatique commune et splénique. Il irrigue l’intestin antérieur : œsophage abdominal, estomac, duodénum proximal, foie, vésicule, pancréas et rate, avec chevauchements autour du duodénum.'),
      s('Artère mésentérique supérieure', 'L’artère mésentérique supérieure naît sous le tronc cœliaque, passe derrière le col du pancréas puis en avant de la troisième portion du duodénum. Ses branches comprennent pancréatico-duodénale inférieure, jéjunales, iléales, iléo-colique, colique droite variable et colique moyenne. Elle vascularise l’intestin moyen jusqu’aux deux tiers proximaux du transverse environ.'),
      s('Artère mésentérique inférieure', 'L’artère mésentérique inférieure naît plus bas de l’aorte et donne colique gauche, sigmoïdiennes et rectale supérieure. Elle dessert l’intestin postérieur, du tiers distal du transverse au rectum supérieur. Les artères rectales moyenne et inférieure proviennent d’autres axes et s’anastomosent avec la rectale supérieure.'),
      s('Arcades et territoires limites', 'Les branches forment des arcades mésentériques et une artère marginale colique reliant les territoires mésentériques supérieur et inférieur. Les zones de Griffith et Sudeck sont des régions frontières où la perfusion peut être vulnérable, avec variabilité des anastomoses. Le tronc cœliaque et l’AMS communiquent notamment via les arcades pancréatico-duodénales.'),
    ], trap: 'L’AMS irrigue l’intestin moyen et l’AMI l’intestin postérieur ; les territoires se chevauchent par des arcades.', recall: 'Quelles sont les trois branches classiques du tronc cœliaque ?', answer: 'Gastrique gauche, hépatique commune et splénique.', source: vessels, glossary: [['Intestin antérieur', 'Territoire embryologique associé principalement au tronc cœliaque.'], ['Artère marginale', 'Arcade longeant le côlon et reliant des branches mésentériques.'], ['Artère iléo-colique', 'Branche de l’AMS desservant iléon terminal, cæcum et région appendiculaire.']], caseStudy: { prompt: 'Une occlusion de l’AMS en amont de ses branches menace surtout quel territoire intestinal ?', answer: 'La majeure partie de l’intestin grêle et le côlon proximal, correspondant au territoire de l’intestin moyen.' }
  }),
  make('anat-portal-vein-system', {
    objectives: ['Décrire la formation et le trajet de la veine porte', 'Relier drainage digestif et passage hépatique', 'Localiser les principales anastomoses portosystémiques'],
    sections: [
      s('Confluence portale', 'La veine porte hépatique naît habituellement derrière le col du pancréas de la réunion de la veine mésentérique supérieure et de la veine splénique. La veine mésentérique inférieure se jette le plus souvent dans la splénique, mais les variantes sont fréquentes. Le système porte conduit le sang digestif riche en nutriments vers les sinusoïdes hépatiques.'),
      s('Trajet et pédicule', 'La veine porte monte derrière la première portion du duodénum puis entre dans le ligament hépatoduodénal. Elle est postérieure à l’artère hépatique propre et au cholédoque. Au hile, elle se divise en branches droite et gauche qui se ramifient dans les pédicules portaux avec artère et canal biliaires.'),
      s('Territoires drainés', 'La porte reçoit le sang veineux de la plupart du tube digestif abdominal, pancréas, rate et vésicule biliaire. Le rectum est drainé en partie par la veine rectale supérieure vers la porte et en partie par les veines moyenne et inférieure vers les axes iliaques systémiques. Le sang portal n’est pas oxygéné de la même manière que le sang artériel, mais reste essentiel au foie.'),
      s('Anastomoses portosystémiques', 'Les communications portosystémiques existent à la jonction gastro-œsophagienne, autour du rectum, au ligament falciforme et dans la région rétropéritonéale. En hypertension portale, ces voies peuvent se dilater : varices œsophagiennes, hémorroïdes ne sont pas équivalentes aux varices rectales, et veines péri-ombilicales peuvent devenir visibles.'),
      s('Fonction hépatique et repères', 'Le sang portal apporte nutriments et substances absorbées aux hépatocytes avant le retour par les veines hépatiques à la cave inférieure. Les sinusoïdes mélangent apports portal et artériel ; les veines centrales convergent vers les veines hépatiques. Le système porte est un réseau veine-capillaires-veine, non une simple veine de retour directe.'),
    ], trap: 'La veine porte se forme généralement derrière le col du pancréas ; la veine mésentérique inférieure a un abouchement variable.', recall: 'Quelles sont les deux veines formant le plus souvent la veine porte ?', answer: 'Veine mésentérique supérieure et veine splénique.', source: vessels, glossary: [['Système porte', 'Circuit où un réseau capillaire se situe entre deux réseaux veineux.'], ['Sinusoïde hépatique', 'Canal vasculaire spécialisé où le sang portal et artériel baigne les hépatocytes.'], ['Anastomose portosystémique', 'Communication entre drainage portal et drainage veineux systémique.']], caseStudy: { prompt: 'Une hypertension portale dilate des veines à la jonction œsophage-estomac. Quelle communication anatomique est impliquée ?', answer: 'Les anastomoses entre veine gastrique gauche du système portal et veines œsophagiennes drainées vers le système azygos.' }
  })
]
const prompts: Record<string, string[]> = {
  'anat-thoracic-aorta-azygos': ['À quel niveau l’aorte thoracique devient-elle abdominale ?', 'Où se termine le conduit thoracique le plus souvent ?', 'Quel système veineux forme une crosse vers la VCS à droite ?', 'Quel territoire la veine hémi-azygos draine-t-elle principalement ?', 'Quel conduit lymphatique draine le quadrant supérieur droit ?'],
  'anat-hepatic-segmentation-couinaud': ['Combien de segments comprend la classification de Couinaud ?', 'Quel segment correspond au lobe caudé ?', 'Où cheminent typiquement les branches portales ?', 'Quelles veines marquent les plans intersegmentaires ?', 'Quelle structure est postérieure dans la triade portale ?'],
  'anat-biliary-tree-vesicle': ['Quels conduits forment le canal hépatique commun ?', 'Quel conduit rejoint le canal hépatique commun pour former le cholédoque ?', 'Quel organe synthétise la bile avant son stockage vésiculaire ?', 'Où passe le cholédoque dans le ligament hépatoduodénal par rapport à la porte ?', 'Où s’abouche habituellement le cholédoque ?'],
  'anat-colon-rectum': ['Où convergent les taeniae coli ?', 'Quel segment du côlon possède habituellement un méso ?', 'Quelle artère irrigue surtout le côlon proximal ?', 'Le rectum possède-t-il des taeniae coli distinctes ?', 'Où se termine le sigmoïde et commence le rectum classiquement ?'],
  'anat-celiac-trunk-mesenteric-arteries': ['Quelles sont les trois branches classiques du tronc cœliaque ?', 'Quelle artère irrigue l’intestin moyen ?', 'Quelle artère irrigue l’intestin postérieur ?', 'Quel repère marque le passage aorte thoracique-abdominale ?', 'Quelle arcade relie les branches mésentériques le long du côlon ?'],
  'anat-portal-vein-system': ['Quelles veines forment généralement la veine porte ?', 'Où se forme habituellement la confluence portale ?', 'Quel territoire se draine dans la veine porte ?', 'Quel système fournit des voies collatérales aux varices œsophagiennes ?', 'Par quelles veines le sang quitte-t-il le foie vers la VCI ?']
}
const answers: Record<string, string[]> = {
  'anat-thoracic-aorta-azygos': ['Au hiatus aortique, vers T12.', 'À l’angle veineux gauche jugulo-subclavier.', 'La veine azygos.', 'Les espaces intercostaux inférieurs gauches via la veine hémi-azygos.', 'Le conduit lymphatique droit.'],
  'anat-hepatic-segmentation-couinaud': ['Huit.', 'Le segment I.', 'Au centre des segments avec branche artérielle et biliaire.', 'Les veines hépatiques.', 'La veine porte.'],
  'anat-biliary-tree-vesicle': ['Les canaux hépatiques droit et gauche.', 'Le canal cystique.', 'Le foie.', 'Elle est postérieure à l’artère hépatique et au cholédoque.', 'À la papille majeure du duodénum, souvent après union avec le conduit pancréatique.'],
  'anat-colon-rectum': ['Sur la base de l’appendice au cæcum.', 'Le côlon transverse.', 'L’artère mésentérique supérieure.', 'Non, elles fusionnent en couche longitudinale continue.', 'Au niveau de S3.'],
  'anat-celiac-trunk-mesenteric-arteries': ['Gastrique gauche, hépatique commune et splénique.', 'L’artère mésentérique supérieure.', 'L’artère mésentérique inférieure.', 'Le hiatus aortique autour de T12.', 'L’artère marginale colique.'],
  'anat-portal-vein-system': ['Veine mésentérique supérieure et veine splénique.', 'Derrière le col du pancréas.', 'La plupart du tube digestif abdominal, de la rate et du pancréas.', 'Le système azygos via les veines œsophagiennes.', 'Par les veines hépatiques.']
}
const wrong: Record<string, string[][]> = {
  'anat-thoracic-aorta-azygos': [['T8.', 'T10.', 'L4.'], ['À l’angle veineux droit.', 'Dans l’atrium droit.', 'Dans la veine cave inférieure.'], ['La veine cave inférieure.', 'La veine hémi-azygos.', 'La veine subclavière droite.'], ['Les espaces intercostaux supérieurs droits.', 'Le réseau portal.', 'Le membre inférieur droit.'], ['Le conduit thoracique.', 'La veine azygos.', 'Le canal cystique.']],
  'anat-hepatic-segmentation-couinaud': [['Quatre.', 'Six.', 'Dix.'], ['Le segment IV.', 'Le segment VIII.', 'Le segment II.'], ['Dans les fissures entre segments uniquement.', 'Dans les veines hépatiques.', 'Sous la capsule en périphérie uniquement.'], ['Les branches portales.', 'Les canaux biliaires seuls.', 'Les artères cystiques.'], ['L’artère hépatique propre.', 'Le cholédoque.', 'La veine hépatique droite.']],
  'anat-biliary-tree-vesicle': [['Les canaux cystique et cholédoque.', 'Les conduits pancréatiques.', 'Les canaux hépatiques gauche et cystique.'], ['Le canal hépatique droit.', 'Le canal pancréatique accessoire.', 'Le canal hépatique gauche.'], ['La vésicule biliaire.', 'Le pancréas.', 'Le duodénum.'], ['Elle est antérieure à la veine porte et à l’artère.', 'Elle est latérale à la vésicule et postérieure au foie.', 'Elle est dans le mésocôlon transverse.'], ['Dans l’iléon terminal.', 'Dans l’atrium gauche.', 'Dans la veine cave.']],
  'anat-colon-rectum': [['Au bord libre du mésocôlon transverse.', 'À l’angle colique gauche.', 'Sur le rectum distal.'], ['Le côlon ascendant.', 'Le côlon descendant.', 'Le cæcum.'], ['L’artère mésentérique inférieure.', 'Le tronc cœliaque.', 'L’artère iliaque interne.'], ['Oui, elles sont visibles jusqu’au canal anal.', 'Oui, une bandelette reste séparée sur le rectum.', 'Oui, elles accompagnent les haustrations rectales.'], ['À L1.', 'À T12.', 'À S1.']],
  'anat-celiac-trunk-mesenteric-arteries': [['Rénale, gonadique et lombaire.', 'Hépatique propre, cystique et rectale supérieure.', 'Gastrique droite, mésentérique supérieure et splénique.'], ['L’artère mésentérique inférieure.', 'Le tronc cœliaque.', 'L’artère iliaque commune.'], ['L’artère mésentérique supérieure.', 'Le tronc cœliaque.', 'L’artère pudendale interne.'], ['Le ligament inguinal à L4.', 'Le hiatus œsophagien à T10.', 'Le hiatus de l’adducteur.'], ['L’arcade plantaire.', 'Le cercle artériel du cerveau.', 'L’arcade palmaire profonde.']],
  'anat-portal-vein-system': [['Veine splénique et veine cave inférieure.', 'Veines hépatiques droite et gauche.', 'Veines iliaques communes.'], ['En avant du sternum.', 'Au hile hépatique.', 'Dans la fosse iliaque gauche.'], ['Le cœur et les poumons uniquement.', 'La paroi thoracique droite seule.', 'Les membres supérieurs.'], ['Les veines caves hépatiques seules.', 'Les veines pulmonaires.', 'Les veines saphènes.'], ['Par les veines portes segmentaires.', 'Par les veines caves directement dans les sinusoïdes.', 'Par le canal thoracique.']]
}
const rationale: Record<string, string[]> = {
  'anat-thoracic-aorta-azygos': ['Le hiatus aortique traverse le diaphragme vers T12.', 'Le conduit thoracique se termine classiquement dans l’angle veineux gauche.', 'L’azygos forme une crosse au-dessus de la racine pulmonaire droite.', 'La veine hémi-azygos recueille surtout les espaces inférieurs gauches.', 'Le quadrant supérieur droit rejoint classiquement le conduit lymphatique droit.'],
  'anat-hepatic-segmentation-couinaud': ['La segmentation fonctionnelle distingue huit unités numérotées.', 'Le caudé est le segment I, postérieur au hile.', 'Les pédicules portaux sont intrasegmentaires.', 'Les veines hépatiques se placent entre territoires portaux.', 'La porte est l’élément postérieur de la triade hépatoduodénale.'],
  'anat-biliary-tree-vesicle': ['La fusion des canaux hépatiques droit et gauche crée le conduit commun.', 'Le cystique rejoint l’hépatique commun avant le duodénum.', 'Les hépatocytes produisent la bile ; la vésicule la stocke.', 'Le cholédoque est postérieur dans le ligament hépatoduodénal.', 'Il s’abouche à la papille majeure, souvent avec le conduit pancréatique.'],
  'anat-colon-rectum': ['Les bandelettes convergent à la base appendiculaire.', 'Le transverse est mobile et suspendu par son méso.', 'L’AMS donne notamment colique moyenne et iléo-colique.', 'Au rectum les taeniae s’élargissent et fusionnent.', 'La jonction rectosigmoïdienne est classiquement repérée vers S3.'],
  'anat-celiac-trunk-mesenteric-arteries': ['La trifurcation classique est gastrique gauche, hépatique commune et splénique.', 'L’AMS vascularise l’intestin moyen.', 'L’AMI dessert l’intestin postérieur.', 'L’aorte traverse le diaphragme par le hiatus aortique.', 'L’arcade marginale longe le côlon et relie des branches coliques.'],
  'anat-portal-vein-system': ['La confluence mésentérico-splénique forme habituellement la porte.', 'La confluence se situe derrière le col du pancréas.', 'Le système porte collecte les viscères digestifs et organes annexes.', 'Les veines gastriques communiquent avec le réseau œsophagien systémique azygos.', 'Les veines hépatiques conduisent le sang à la VCI.']
}
export const abdominalQuestions: Question[] = abdominalCourses.flatMap(c => prompts[c.id].map((prompt, i) => {
  const options = [answers[c.id][i], ...wrong[c.id][i]]
  return { id: `${c.id}-q${i + 1}`, course: c.id, topic: 'Anatomie', prompt, options, correct: [0], why: options.map((_, j) => j === 0 ? rationale[c.id][i] : 'Cette structure ou ce territoire correspond à un autre axe anatomique.'), difficulty: i < 2 ? 'essentiel' as const : 'application' as const, format: 'single' as const }
}))
