import type { Course } from '../../curriculum'
import type { Question } from '../../questions'
import { canonicalCourses } from '../../taxonomy/canonicalCourses'

const meta = new Map(canonicalCourses.filter(item => item.subject === 'Anatomie').map(item => [item.id, item]))
const muscle = 'https://openstax.org/books/anatomy-and-physiology-2e/pages/11-6-appendicular-muscles-of-the-pelvic-girdle-and-lower-limbs'
const vessels = 'https://openstax.org/books/anatomy-and-physiology-2e/pages/20-5-circulatory-pathways'
const nerves = 'https://openstax.org/books/anatomy-and-physiology-2e/pages/13-4-the-peripheral-nervous-system'
const bones = 'https://openstax.org/books/anatomy-and-physiology-2e/pages/8-4-bones-of-the-lower-limb'
type Draft = { objectives: string[]; sections: Course['sections']; trap: string; recall: string; answer: string; source: string; glossary: NonNullable<Course['glossary']>; caseStudy: NonNullable<Course['caseStudy']> }
const s = (title: string, text: string, bullets?: string[]) => ({ title, text, ...(bullets ? { bullets } : {}) })
const make = (id: string, d: Draft): Course => {
  const c = meta.get(id)
  if (!c) throw new Error(`Identifiant anatomique canonique absent : ${id}`)
  return { id, title: c.title, category: c.subject, tag: c.module, minutes: 15, structure: null, objectives: d.objectives,
    sections: d.sections, trap: d.trap, recall: d.recall, answer: d.answer, source: d.source,
    sources: [{ label: 'OpenStax · Anatomy & Physiology 2e', url: d.source }],
    prerequisites: ['Repères anatomiques et anatomie osseuse des membres', 'Organisation des loges et des faisceaux neurovasculaires'],
    glossary: d.glossary, caseStudy: d.caseStudy, review: { status: 'unreviewed', updatedAt: '2026-09-23', sourcesUpdatedAt: '2026-09-23' } }
}
export const lowerLimbCourses: Course[] = [
  make('anat-coxofemoral-joint', {
    objectives: ['Décrire les surfaces articulaires de la hanche', 'Expliquer les rôles du labrum, de la capsule et des ligaments', 'Relier stabilité et mobilité coxofémorales'],
    sections: [
      s('Surfaces et congruence', 'L’articulation coxofémorale unit la tête fémorale sphérique à la surface semi-lunaire de l’acétabulum. L’incisure acétabulaire est complétée par le ligament transverse de l’acétabulum. Cette articulation synoviale sphéroïde transmet le poids du tronc au membre inférieur tout en permettant flexion-extension, abduction-adduction et rotations.'),
      s('Labrum acétabulaire', 'Le labrum est un anneau fibrocartilagineux fixé au rebord acétabulaire. Il approfondit la cavité, augmente la surface de contact et contribue au joint d’étanchéité qui maintient une fine couche de liquide synovial. Il se continue avec le ligament transverse au niveau de l’incisure ; son rôle ne remplace pas celui de la capsule.'),
      s('Capsule et zones de faiblesse', 'La capsule s’attache proximalement au rebord acétabulaire et distalement à la ligne intertrochantérique en avant ; en arrière, son insertion fémorale est plus proximale sur le col. Les fibres circulaires profondes forment une zone orbiculaire entourant le col. Les plis synoviaux et le ligament de la tête fémorale accompagnent vaisseaux et tissus mais contribuent modestement à la stabilité adulte.'),
      s('Renforts ligamentaires', 'Les ligaments iliofémoral, pubofémoral et ischiofémoral renforcent la capsule. Le ligament iliofémoral en Y de Bigelow est particulièrement robuste et limite l’hyperextension en station debout ; le pubofémoral freine notamment l’abduction excessive ; l’ischiofémoral renforce la région postérieure. Leur mise en tension dépend de la position et de la rotation.'),
      s('Stabilité, vascularisation et mouvements', 'La stabilité combine congruence, labrum, capsule, ligaments, pression intra-articulaire et muscles périarticulaires. Les branches rétinaculaires de l’artère circonflexe fémorale médiale contribuent fortement à l’irrigation de la tête chez l’adulte, avec variations. Les mouvements sont limités par tissus mous, géométrie et tension capsulaire ; aucune structure isolée n’explique toute la stabilité.'),
    ], trap: 'Le ligament de la tête fémorale n’est pas le principal stabilisateur de la hanche adulte ; la capsule, les ligaments et les muscles jouent un rôle majeur.', recall: 'Quel ligament capsulaire est particulièrement important pour limiter l’hyperextension en station debout ?', answer: 'Le ligament iliofémoral, très résistant, tendu en extension.', source: bones, glossary: [['Labrum acétabulaire', 'Anneau fibrocartilagineux approfondissant l’acétabulum.'], ['Zone orbiculaire', 'Fibres circulaires profondes de la capsule entourant le col fémoral.'], ['Ligament iliofémoral', 'Renfort antérieur en Y de la capsule limitant notamment l’extension excessive.']], caseStudy: { prompt: 'Une fracture intracapsulaire du col fémoral menace la vascularisation de la tête. Quel réseau artériel doit être particulièrement considéré ?', answer: 'Les branches rétinaculaires issues surtout de l’artère circonflexe fémorale médiale chez l’adulte.' }
  }),
  make('anat-gluteal-region-spaces', {
    objectives: ['Décrire les plans musculaires glutéaux et les rotateurs profonds', 'Localiser les foramens ischiatiques et leur contenu majeur', 'Expliquer les rapports du nerf sciatique et les repères topographiques'],
    sections: [
      s('Plans superficiels', 'Le grand fessier recouvre une partie des muscles moyen et petit fessiers. Il naît du bassin postérieur et du sacrum, puis s’insère en partie sur le tractus ilio-tibial et la tubérosité glutéale ; il étend et tourne latéralement la hanche. Moyen et petit fessiers s’insèrent sur le grand trochanter et assurent surtout l’abduction et la stabilisation pelvienne en appui unipodal.'),
      s('Rotateurs latéraux profonds', 'Le piriforme traverse la grande incisure ischiatique, divise fonctionnellement le foramen en passages supra- et infra-piriformes et se termine sur le grand trochanter. Obturateur interne, jumeaux supérieur et inférieur et carré fémoral forment un plan profond de rotateurs latéraux. Le nerf du carré fémoral et les nerfs obturateurs internes suivent des trajets distincts vers ces muscles.'),
      s('Foramens ischiatiques', 'Le ligament sacro-épineux transforme la grande incisure en foramen ischiatique majeur ; le ligament sacro-tubéral participe aux limites du grand et du petit foramens. Le nerf pudendal et les vaisseaux pudendaux internes quittent le pelvis par le grand foramen sous le piriforme, contournent l’épine ischiatique puis entrent dans le périnée par le petit foramen.'),
      s('Nerf sciatique et rapports', 'Le nerf sciatique quitte habituellement le pelvis sous le piriforme, passe profondément au grand fessier puis descend entre grand trochanter et tubérosité ischiatique, en arrière des rotateurs latéraux. Il contient les composantes tibiale et fibulaire commune qui se séparent à un niveau variable. La branche glutéale supérieure passe au-dessus du piriforme et innerve moyen, petit fessiers et tenseur du fascia lata.'),
      s('Vascularisation et fonction', 'Les artères glutéales supérieure et inférieure, branches de l’iliaque interne, vascularisent la région et s’anastomosent autour de la hanche. Le moyen et petit fessiers maintiennent le bassin horizontal lors de l’appui sur un seul membre ; leur faiblesse peut entraîner une chute controlatérale du bassin. Les repères de surface orientent, mais ne remplacent pas l’évaluation neurovasculaire.'),
    ], trap: 'Le nerf pudendal sort du pelvis par le grand foramen puis revient par le petit foramen pour gagner le périnée.', recall: 'Quel est le trajet habituel du nerf sciatique par rapport au piriforme ?', answer: 'Il quitte généralement le pelvis sous le piriforme par le foramen ischiatique majeur.', source: muscle, glossary: [['Foramen ischiatique majeur', 'Passage reliant pelvis et région glutéale, formé à partir de la grande incisure et de ligaments.'], ['Nerf pudendal', 'Nerf du périnée passant par les foramens majeur puis mineur.'], ['Signe de Trendelenburg', 'Abaissement du bassin controlatéral en appui unipodal par insuffisance des abducteurs.']], caseStudy: { prompt: 'En appui sur le membre droit, le bassin gauche s’abaisse. Quel groupe musculaire et quel nerf du côté droit faut-il examiner ?', answer: 'Les moyen et petit fessiers droits, principalement innervés par le nerf glutéal supérieur.' }
  }),
  make('anat-femoral-triangle-scarpa', {
    objectives: ['Délimiter le trigone fémoral', 'Ordonner ses principaux éléments de latéral à médial', 'Relier les compartiments de cuisse à leurs actions et innervations'],
    sections: [
      s('Limites du trigone', 'Le trigone fémoral est une dépression antérosupérieure de la cuisse. Il est limité en haut par le ligament inguinal, latéralement par le sartorius et médialement par le long adducteur ; son sommet se prolonge sous le sartorius. Son plancher comprend notamment iliopsoas latéralement et pectiné/adducteur long médialement ; le fascia lata forme le toit.'),
      s('Contenu et ordre', 'Sous le ligament inguinal, le nerf fémoral est latéral à l’artère fémorale, puis la veine fémorale est médiale à l’artère ; les lymphatiques et le canal fémoral se trouvent plus médialement. Le moyen mnémotechnique NAVL résume nerf, artère, veine, lymphatiques de latéral à médial, avec une séparation fasciale entre nerf et gaine vasculaire.'),
      s('Artère et veine fémorales', 'L’artère fémorale prolonge l’iliaque externe sous le ligament inguinal, donne des branches superficielles et la profonde de la cuisse, puis devient poplitée en traversant le hiatus de l’adducteur. La veine fémorale accompagne l’artère, reçoit notamment la grande saphène et la veine profonde, puis devient iliaque externe sous le ligament inguinal.'),
      s('Loge antérieure et quadriceps', 'Le quadriceps comprend droit fémoral, vaste latéral, vaste médial et vaste intermédiaire ; leurs tendons convergent sur la patella puis se prolongent par le ligament patellaire vers la tubérosité tibiale. Il étend le genou ; le droit fémoral fléchit aussi la hanche. Le nerf fémoral innerve principalement cette loge et donne le nerf saphène sensitif.'),
      s('Loges médiale et postérieure', 'Les adducteurs long, court, grand, le gracile et le pectiné rapprochent la cuisse et occupent principalement la loge médiale, innervée surtout par le nerf obturateur avec exceptions et contributions. Les ischio-jambiers étendent la hanche et fléchissent le genou ; leur innervation dépend surtout de la division tibiale du sciatique, sauf le chef court du biceps fémoral.'),
    ], trap: 'Le nerf fémoral est latéral à la gaine fémorale et ne chemine pas dans la gaine avec l’artère et la veine.', recall: 'Quel est l’ordre de latéral à médial des éléments majeurs sous le ligament inguinal ?', answer: 'Nerf fémoral, artère fémorale, veine fémorale, puis structures lymphatiques/canal fémoral.', source: muscle, glossary: [['Trigone fémoral', 'Région triangulaire antérieure de la cuisse sous le ligament inguinal.'], ['Hiatus de l’adducteur', 'Ouverture du grand adducteur par laquelle l’artère et la veine fémorales gagnent la fosse poplitée.'], ['Nerf saphène', 'Branche sensitive du nerf fémoral destinée notamment à la jambe médiale.']], caseStudy: { prompt: 'Une faiblesse d’extension du genou et une diminution du réflexe patellaire accompagnent une hypoesthésie médiale de jambe. Quel nerf proximal est à considérer ?', answer: 'Le nerf fémoral, dont les branches motrices innervent le quadriceps, la branche réflexe participe au réflexe patellaire et le nerf saphène innerve la peau médiale de jambe.' }
  }),
  make('anat-popliteal-fossa', {
    objectives: ['Décrire les limites musculaires de la fosse poplitée', 'Ordonner artère, veine et nerfs dans la fosse', 'Suivre les divisions vasculaires et nerveuses distales'],
    sections: [
      s('Limites et toit', 'La fosse poplitée est un espace losangique en arrière du genou. En haut, ses limites sont formées par biceps fémoral en latéral et semi-tendineux/semi-membraneux en médial ; en bas, par les chefs médial et latéral du gastrocnémien et le plantaire lorsque présent. Le toit comprend peau, fascia superficiel et fascia poplité.'),
      s('Plancher', 'Le plancher correspond à la surface poplitée du fémur, la capsule postérieure et le ligament poplité oblique, puis au muscle poplité plus distalement. Ce plancher profond sépare les structures vasculonerveuses des articulations et doit être pris en compte lors de l’examen ou de l’imagerie.'),
      s('Contenu et plans', 'De superficiel à profond dans la partie centrale, le nerf tibial est le plus superficiel, la veine poplitée intermédiaire et l’artère poplitée la plus profonde, au contact du plancher. Le nerf fibulaire commun suit le bord médial du biceps fémoral puis contourne le col de la fibula. Des nœuds lymphatiques poplités accompagnent les vaisseaux.'),
      s('Artère poplitée', 'L’artère poplitée est la continuation de la fémorale après le hiatus de l’adducteur. Elle donne des branches géniculées qui participent au réseau périarticulaire, puis se termine habituellement en artères tibiales antérieure et postérieure au bord inférieur du poplité. Des artères surales nourrissent aussi le gastrocnémien et les structures voisines.'),
      s('Veine et nerfs', 'La veine poplitée résulte de la convergence des veines profondes de jambe, reçoit la petite saphène et devient veine fémorale en traversant le hiatus de l’adducteur. Le nerf tibial continue vers la loge postérieure de jambe ; le nerf fibulaire commun se divise près du col fibulaire en branches superficielle et profonde. Cette région est vulnérable aux traumatismes et à la distension vasculaire.'),
    ], trap: 'Dans la fosse poplitée, le nerf tibial est superficiel à la veine, elle-même superficielle à l’artère poplitée.', recall: 'Quel nerf contourne le col de la fibula et quelle division motrice distale en résulte ?', answer: 'Le nerf fibulaire commun contourne le col de la fibula et se divise en nerfs fibulaires superficiel et profond.', source: vessels, glossary: [['Fosse poplitée', 'Espace losangique postérieur du genou contenant axes vasculaires et nerveux.'], ['Artère géniculée', 'Branche participant au réseau artériel autour du genou.'], ['Nerf fibulaire commun', 'Branche du sciatique contournant le col de la fibula.']], caseStudy: { prompt: 'Après luxation du genou, une ischémie distale est suspectée malgré un examen initial rassurant. Quelle artère de la fosse doit être évaluée ?', answer: 'L’artère poplitée, étroitement appliquée au plancher et exposée aux lésions lors des traumatismes du genou.' }
  }),
  make('anat-leg-compartments', {
    objectives: ['Comparer les trois loges de la jambe', 'Associer muscles et mouvements de cheville/pied', 'Relier chaque loge à son nerf et son axe vasculaire'],
    sections: [
      s('Cloisons et compartiments', 'La crête antérieure de la fibula, la membrane interosseuse, le fascia profond et les septums séparent loges antérieure, latérale et postérieure. La loge postérieure se divise en plans superficiel et profond. Les compartiments sont peu extensibles ; leurs rapports neurovasculaires permettent de localiser des déficits moteurs ou sensitifs.'),
      s('Loge antérieure', 'Tibial antérieur, long extenseur de l’hallux, long extenseur des orteils et fibulaire tertiaire dorsifléchissent la cheville ; certains étendent les orteils ou participent à l’éversion. Le nerf fibulaire profond et les vaisseaux tibiaux antérieurs cheminent dans cette loge. Le tibial antérieur participe aussi à l’inversion et au soutien de l’arche médiale.'),
      s('Loge latérale', 'Long et court fibulaires éversent le pied et contribuent à la flexion plantaire. Ils passent derrière la malléole latérale dans une gaine rétinaculaire puis sous le pied pour s’insérer respectivement à la base du premier métatarsien/cunéiforme médial et à la base du cinquième métatarsien. Le nerf fibulaire superficiel les innerve.'),
      s('Loge postérieure superficielle', 'Gastrocnémien, soléaire et plantaire forment le triceps sural fonctionnel et convergent vers le tendon calcanéen. Ils réalisent une puissante flexion plantaire ; le gastrocnémien fléchit aussi le genou car il franchit l’articulation. Le nerf tibial innerve cette loge ; le tendon s’insère sur la face postérieure du calcanéus.'),
      s('Loge postérieure profonde et faisceau tibial', 'Tibial postérieur, long fléchisseur des doigts et long fléchisseur de l’hallux participent à l’inversion, à la flexion plantaire et à la flexion des orteils. Le nerf tibial et les vaisseaux tibiaux postérieurs passent derrière la malléole médiale sous le rétinaculum des fléchisseurs. Les tendons se dirigent vers la plante ; l’ordre exact se retient « Tom, Dick, And Very Nervous Harry » de l’avant vers l’arrière.'),
    ], trap: 'Le nerf fibulaire profond innerve la loge antérieure ; le nerf fibulaire superficiel innerve la loge latérale.', recall: 'Quel paquet passe derrière la malléole médiale sous le rétinaculum des fléchisseurs ?', answer: 'Le nerf tibial et les vaisseaux tibiaux postérieurs, accompagnés des tendons des fléchisseurs profonds.', source: muscle, glossary: [['Triceps sural', 'Ensemble fonctionnel gastrocnémien-soléaire transmettant sa force au tendon calcanéen.'], ['Nerf fibulaire profond', 'Nerf de la loge antérieure de jambe et du premier espace interdigital.'], ['Rétinaculum des fléchisseurs', 'Toit du tunnel tarsien derrière la malléole médiale.']], caseStudy: { prompt: 'Une fracture du col fibulaire s’accompagne d’un steppage et d’une faiblesse d’éversion. Quel nerf et quelles branches sont menacés ?', answer: 'Le nerf fibulaire commun au col de la fibula ; ses branches profonde et superficielle peuvent affecter dorsiflexion et éversion.' }
  }),
  make('anat-talocrural-joint-ankle', {
    objectives: ['Décrire la mortaise talocrurale', 'Comparer les faisceaux ligamentaires latéral et médial', 'Relier position du pied et mécanisme d’entorse'],
    sections: [
      s('Mortaise de cheville', 'L’articulation talocrurale associe la trochlée du talus à la mortaise formée par les extrémités distales du tibia et de la fibula. La pince malléolaire stabilise surtout la trochlée en dorsiflexion, position où sa partie antérieure plus large s’engage dans la mortaise. La principale liberté est la flexion dorsale et plantaire.'),
      s('Syndesmose tibiofibulaire', 'La syndesmose distale comprend ligaments tibiofibulaires antéro-inférieur et postéro-inférieur, ligament transverse et membrane interosseuse distale. Elle maintient la mortaise et autorise une très faible adaptation lors de la dorsiflexion. Une lésion syndesmotique peut être plus étendue qu’une entorse latérale simple.'),
      s('Complexe ligamentaire latéral', 'Le ligament latéral comprend talo-fibulaire antérieur, calcanéo-fibulaire et talo-fibulaire postérieur. Le talo-fibulaire antérieur est souvent sollicité lors d’inversion avec flexion plantaire ; le calcanéo-fibulaire traverse les articulations talocrurale et subtalaire. Le talo-fibulaire postérieur est plus robuste et est moins souvent isolément lésé.'),
      s('Ligament médial', 'Le ligament deltoïde s’étend de la malléole médiale vers talus, calcanéus et naviculaire par plusieurs faisceaux. Sa résistance limite l’éversion excessive et contribue à stabiliser la cheville. Les entorses médiales isolées sont moins fréquentes ; un traumatisme en éversion peut aussi fracturer la malléole ou léser la syndesmose.'),
      s('Stabilité et examen anatomique', 'La stabilité dépend de la géométrie osseuse, des ligaments, des tendons et de la capsule. Les articulations subtalaire et transverse du tarse participent à l’inversion-éversion globale du pied, à distinguer du mouvement talocrural dominant. Douleur, œdème et limitation ne permettent pas à eux seuls de conclure à une lésion ligamentaire plutôt qu’osseuse.'),
    ], trap: 'L’inversion du pied implique fortement l’articulation subtalaire ; la talocrurale réalise surtout flexion dorsale et plantaire.', recall: 'Quel ligament latéral est le plus souvent touché dans une entorse en inversion avec pied en flexion plantaire ?', answer: 'Le ligament talo-fibulaire antérieur.', source: bones, glossary: [['Mortaise talocrurale', 'Encastrement du talus entre tibia et fibula distaux.'], ['Syndesmose', 'Union fibreuse maintenant les extrémités distales du tibia et de la fibula.'], ['Ligament deltoïde', 'Complexe ligamentaire médial résistant à l’éversion de la cheville.']], caseStudy: { prompt: 'Une douleur persiste au-dessus de la mortaise après un mouvement de rotation externe. Quel complexe fibreux doit être distingué d’une entorse talo-fibulaire antérieure ?', answer: 'La syndesmose tibiofibulaire distale, notamment ses ligaments antéro- et postéro-inférieurs.' }
  }),
  make('anat-lumbosacral-plexus', {
    objectives: ['Décrire les contributions du plexus lombaire et sacré', 'Suivre les nerfs fémoral, obturateur et sciatique', 'Localiser leurs fonctions motrices et sensitives principales'],
    sections: [
      s('Plexus lombaire', 'Le plexus lombaire se forme principalement dans le psoas à partir des rameaux antérieurs L1 à L4, avec contribution fréquente de T12. Des branches ilio-hypogastrique, ilio-inguinale, génito-fémorale, cutané latéral de la cuisse, fémorale et obturatrice émergent selon leurs rapports au psoas. Les variantes segmentaires sont fréquentes.'),
      s('Nerf fémoral', 'Le nerf fémoral provient des divisions postérieures des rameaux L2-L4 et émerge du bord latéral du psoas. Il passe sous le ligament inguinal, latéral à l’artère fémorale, puis se divise dans la cuisse antérieure. Il innerve quadriceps, sartorius et une partie de l’iliacus ; le nerf saphène poursuit une sensibilité médiale de jambe et du pied.'),
      s('Nerf obturateur', 'Le nerf obturateur provient des divisions antérieures L2-L4, émerge du bord médial du psoas et traverse le canal obturateur avec les vaisseaux obturateurs. Ses branches antérieure et postérieure innervent plusieurs adducteurs et donnent une contribution sensitive variable à la cuisse médiale. Les variations et recouvrements rendent les territoires cutanés moins nets que les muscles.'),
      s('Plexus sacré et nerf sciatique', 'Le plexus sacré se constitue contre la face antérieure du piriforme par le tronc lombo-sacré L4-L5 et les rameaux antérieurs S1-S4. Le sciatique est la principale branche et sort habituellement par le grand foramen sous le piriforme. Il contient composantes tibiale et fibulaire commune, qui se séparent à un niveau variable.'),
      s('Localiser une atteinte', 'Le nerf tibial dessert la loge postérieure de jambe et la plante ; le fibulaire commun se divise en nerfs profond et superficiel pour loges antérieure et latérale. Une atteinte fémorale affecte extension du genou et réflexe patellaire ; une atteinte obturatrice peut réduire l’adduction ; une radiculopathie ou atteinte sciatique produit des profils plus larges à distinguer par examen et imagerie.'),
    ], trap: 'Le nerf fémoral passe latéralement au paquet vasculaire sous le ligament inguinal ; le nerf obturateur gagne la cuisse par le canal obturateur.', recall: 'Quels rameaux forment habituellement le nerf fémoral et quels mouvements peut affecter sa lésion ?', answer: 'L2-L4, surtout divisions postérieures ; une lésion peut affaiblir l’extension du genou et diminuer le réflexe patellaire.', source: nerves, glossary: [['Tronc lombo-sacré', 'Contribution L4-L5 reliant le plexus lombaire au plexus sacré.'], ['Nerf saphène', 'Branche sensitive terminale du nerf fémoral.'], ['Canal obturateur', 'Passage des nerfs et vaisseaux obturateurs du pelvis à la cuisse médiale.']], caseStudy: { prompt: 'Une faiblesse d’adduction de hanche et une hypoesthésie médiale limitée de cuisse suivent une chirurgie pelvienne. Quel nerf est à considérer ?', answer: 'Le nerf obturateur, qui innerve plusieurs adducteurs et donne une sensibilité médiale de cuisse variable.' }
  }),
]
const prompts: Record<string, string[]> = {
  'anat-coxofemoral-joint': ['Quel anneau fibrocartilagineux approfondit l’acétabulum ?', 'Quel ligament limite fortement l’hyperextension de la hanche ?', 'Quelle artère contribue surtout à la vascularisation de la tête fémorale adulte ?', 'Quel mouvement prédomine dans une articulation coxofémorale sphéroïde ?', 'Le ligament de la tête fémorale est-il le stabilisateur principal chez l’adulte ?'],
  'anat-gluteal-region-spaces': ['Quel nerf passe habituellement sous le piriforme ?', 'Quel nerf quitte le pelvis puis revient par le petit foramen ischiatique ?', 'Quel muscle stabilise le bassin en appui unipodal ?', 'Quelles artères principales vascularisent la région glutéale ?', 'Quel nerf innerve les moyens et petits fessiers ?'],
  'anat-femoral-triangle-scarpa': ['Quelles structures forment les limites du trigone fémoral ?', 'Quel est l’ordre latéro-médial sous le ligament inguinal ?', 'Quel nerf innerve principalement le quadriceps ?', 'Où l’artère fémorale devient-elle poplitée ?', 'Quel muscle fléchit la hanche et étend le genou ?'],
  'anat-popliteal-fossa': ['Quelle structure est la plus profonde des trois éléments centraux ?', 'Quel nerf contourne le col de la fibula ?', 'De quelle artère l’artère poplitée est-elle la continuation ?', 'En quelles artères se termine-t-elle généralement ?', 'Quel muscle participe à la limite inféro-médiale de la fosse ?'],
  'anat-leg-compartments': ['Quel nerf innerve la loge antérieure de jambe ?', 'Quel nerf innerve la loge latérale ?', 'Quel tendon transmet la force du triceps sural au calcanéus ?', 'Quel paquet passe derrière la malléole médiale ?', 'Quel mouvement est principalement assuré par le tibial antérieur ?'],
  'anat-talocrural-joint-ankle': ['Quels os forment la mortaise talocrurale ?', 'Quel ligament est souvent atteint lors d’une inversion en flexion plantaire ?', 'Quel complexe relie tibia et fibula distaux ?', 'Quel complexe médial limite l’éversion excessive ?', 'Quelle articulation participe fortement à l’inversion-éversion ?'],
  'anat-lumbosacral-plexus': ['Quelles racines contribuent principalement au nerf fémoral ?', 'Par quel passage le nerf obturateur gagne-t-il la cuisse ?', 'Quel nerf sort habituellement sous le piriforme ?', 'Quelle branche sensitive du fémoral descend sur la jambe médiale ?', 'Une lésion du nerf fémoral affaiblit principalement quel mouvement du genou ?'],
}
const answers: Record<string, string[]> = {
  'anat-coxofemoral-joint': ['Le labrum acétabulaire.', 'Le ligament iliofémoral.', 'L’artère circonflexe fémorale médiale et ses branches rétinaculaires.', 'Flexion-extension, avec abduction-adduction et rotations également possibles.', 'Non, la capsule, les ligaments et les muscles assurent la stabilité majeure.'],
  'anat-gluteal-region-spaces': ['Le nerf sciatique.', 'Le nerf pudendal.', 'Le moyen et le petit fessiers.', 'Les artères glutéales supérieure et inférieure.', 'Le nerf glutéal supérieur.'],
  'anat-femoral-triangle-scarpa': ['Ligament inguinal, sartorius et long adducteur.', 'Nerf fémoral, artère fémorale, veine fémorale, lymphatiques.', 'Le nerf fémoral.', 'Au hiatus de l’adducteur.', 'Le droit fémoral.'],
  'anat-popliteal-fossa': ['L’artère poplitée, plaquée au plancher.', 'Le nerf fibulaire commun.', 'L’artère fémorale après son passage au hiatus de l’adducteur.', 'Artères tibiales antérieure et postérieure.', 'Le chef médial du gastrocnémien.'],
  'anat-leg-compartments': ['Le nerf fibulaire profond.', 'Le nerf fibulaire superficiel.', 'Le tendon calcanéen (Achille).', 'Le nerf tibial et les vaisseaux tibiaux postérieurs avec tendons fléchisseurs.', 'La dorsiflexion de cheville, avec une contribution à l’inversion.'],
  'anat-talocrural-joint-ankle': ['Le tibia, la fibula distale et le talus.', 'Le ligament talo-fibulaire antérieur.', 'La syndesmose tibiofibulaire distale.', 'Le ligament deltoïde.', 'L’articulation subtalaire.'],
  'anat-lumbosacral-plexus': ['L2, L3 et L4.', 'Le canal obturateur.', 'Le nerf sciatique.', 'Le nerf saphène.', 'L’extension du genou.'],
}
const optionsByCourse: Record<string, string[][]> = {
  'anat-coxofemoral-joint': [['Le ligament rond.', 'Le ligament iliofémoral.', 'Le ligament transverse du genou.'], ['Le ligament pubofémoral.', 'Le ligament sacro-tubéral.', 'Le ligament de la tête fémorale.'], ['L’artère glutéale supérieure.', 'L’artère obturatrice seule.', 'L’artère circonflexe fémorale latérale uniquement.'], ['Rotation axiale uniquement.', 'Glissement sans rotation.', 'Flexion-extension sans autre mouvement possible.'], ['Oui, il retient seul la tête dans l’acétabulum.', 'Oui, sa section entraîne toujours une luxation.', 'Oui, car il entoure la capsule entière.']],
  'anat-gluteal-region-spaces': [['Le nerf fémoral.', 'Le nerf pudendal.', 'Le nerf obturateur.'], ['Le nerf sciatique.', 'Le nerf glutéal supérieur.', 'Le nerf cutané latéral de la cuisse.'], ['Le grand fessier seul.', 'Le piriforme.', 'Le carré fémoral.'], ['Les artères circonflexes fémorales seulement.', 'Les artères pudendales internes.', 'Les artères iliaques externes directement.'], ['Le nerf glutéal inférieur.', 'Le nerf obturateur.', 'Le nerf sciatique.']],
  'anat-femoral-triangle-scarpa': [['Ligament inguinal, sartorius et gracile.', 'Ligament inguinal, droit fémoral et pectiné.', 'Sartorius, vaste médial et patella.'], ['Veine, artère, nerf, lymphatiques.', 'Artère, nerf, lymphatiques, veine.', 'Nerf, veine, artère, lymphatiques.'], ['Le nerf obturateur.', 'Le nerf tibial.', 'Le nerf fibulaire profond.'], ['À l’anneau inguinal profond.', 'Au canal obturateur.', 'À la malléole médiale.'], ['Le biceps fémoral.', 'Le vaste médial.', 'Le sartorius.']],
  'anat-popliteal-fossa': [['Le nerf tibial.', 'La veine poplitée.', 'Le nerf fibulaire commun.'], ['Le nerf tibial.', 'Le nerf saphène.', 'Le nerf obturateur.'], ['L’artère iliaque interne.', 'L’artère tibiale postérieure.', 'L’artère fémorale avant le ligament inguinal.'], ['Artères fibulaire et surale.', 'Artères fémorale profonde et circonflexe.', 'Artères dorsale du pied et plantaire médiale.'], ['Le soléaire.', 'Le biceps fémoral.', 'Le semi-tendineux.']],
  'anat-leg-compartments': [['Le nerf tibial.', 'Le nerf fibulaire superficiel.', 'Le nerf saphène.'], ['Le nerf fibulaire profond.', 'Le nerf tibial.', 'Le nerf sural.'], ['Le tendon patellaire.', 'Le tendon du tibial postérieur.', 'Le tendon du long fibulaire.'], ['Le nerf fibulaire commun et les vaisseaux fibulaires.', 'Le nerf fibulaire profond et l’artère dorsale du pied.', 'Le nerf saphène et la grande saphène.'], ['Flexion plantaire.', 'Éversion seule.', 'Flexion des orteils.']],
  'anat-talocrural-joint-ankle': [['Le calcanéus, le naviculaire et la fibula.', 'Le tibia et le calcanéus.', 'Le talus, le calcanéus et le naviculaire.'], ['Le talo-fibulaire postérieur.', 'Le ligament deltoïde.', 'Le tibiofibulaire postérieur inférieur.'], ['Le ligament collatéral latéral du genou.', 'La membrane obturatrice.', 'Le ligament patellaire.'], ['Le ligament talo-fibulaire antérieur.', 'Le ligament calcanéo-fibulaire.', 'Le ligament plantaire long.'], ['L’articulation talocrurale seule.', 'L’articulation métatarso-phalangienne.', 'L’articulation tibiofibulaire proximale.']],
  'anat-lumbosacral-plexus': [['L1-L2 uniquement.', 'L5-S2.', 'S1-S4.'], ['Le hiatus de l’adducteur.', 'Le canal inguinal.', 'Le foramen obturé sans canal.'], ['Le nerf fémoral.', 'Le nerf obturateur.', 'Le nerf glutéal inférieur.'], ['Le nerf cutané latéral de la cuisse.', 'Le nerf fibulaire superficiel.', 'Le nerf ilio-inguinal.'], ['La flexion plantaire.', 'L’adduction des orteils.', 'La flexion du genou uniquement.']]
}
const explanations: Record<string, string[]> = {
  'anat-coxofemoral-joint': ['Le labrum borde et approfondit la cavité acétabulaire.', 'Ce renfort antérieur résistant freine l’extension excessive.', 'Les branches rétinaculaires, souvent issues de la circonflexe médiale, vascularisent la tête.', 'La hanche est une articulation sphéroïde permettant plusieurs axes de mouvement.', 'La stabilité repose surtout sur congruence, capsule, ligaments et muscles.'],
  'anat-gluteal-region-spaces': ['Il quitte le pelvis habituellement sous le piriforme.', 'Le trajet classique quitte puis regagne la région périnéale via ces deux foramens.', 'Ces abducteurs stabilisent le bassin en appui sur le membre controlatéral.', 'Ce sont les deux branches glutéales majeures de l’iliaque interne.', 'La branche supérieure innerve moyen, petit fessiers et tenseur du fascia lata.'],
  'anat-femoral-triangle-scarpa': ['Ces limites se rencontrent sous le ligament inguinal dans la cuisse antérieure.', 'Le nerf est latéral, l’artère centrale, la veine médiale puis les lymphatiques.', 'Il innerve le quadriceps et participe au réflexe patellaire.', 'L’axe passe sous le grand adducteur pour devenir poplité.', 'Le droit fémoral traverse hanche et genou, fléchissant l’une et étendant l’autre.'],
  'anat-popliteal-fossa': ['L’artère est au contact du plancher profond de la fosse.', 'La branche fibulaire commune contourne le col fibulaire.', 'La poplitée prolonge la fémorale après le hiatus de l’adducteur.', 'La terminaison habituelle donne les artères tibiales antérieure et postérieure.', 'Le chef médial du gastrocnémien forme le bord inférieur médial.'],
  'anat-leg-compartments': ['Le nerf fibulaire profond traverse le compartiment antérieur avec les vaisseaux tibiaux antérieurs.', 'Le nerf fibulaire superficiel innerve les fibulaires latéraux.', 'Le triceps sural transmet sa force au calcanéus par ce tendon.', 'Ces structures passent dans le tunnel tarsien derrière la malléole médiale.', 'Le tibial antérieur relève le pied et participe à l’inversion.'],
  'anat-talocrural-joint-ankle': ['Le talus s’articule dans la mortaise tibiofibulaire.', 'Ce ligament antérieur est fréquemment sollicité dans ce mécanisme.', 'Les ligaments distaux et la membrane interosseuse stabilisent cette union fibreuse.', 'Le complexe médial robuste oppose l’éversion excessive.', 'Elle contribue fortement aux mouvements d’inversion et d’éversion du pied.'],
  'anat-lumbosacral-plexus': ['Les divisions postérieures L2-L4 forment principalement le nerf fémoral.', 'Nerf et vaisseaux obturateurs traversent ce conduit osseux vers la cuisse médiale.', 'Il passe habituellement sous le piriforme en quittant le pelvis.', 'Le saphène est sensitif et accompagne le territoire médial distal du membre.', 'Le quadriceps et donc l’extension du genou sont principalement dépendants du fémoral.']
}
export const lowerLimbQuestions: Question[] = lowerLimbCourses.flatMap(course => prompts[course.id].map((prompt, i) => {
  const options = [answers[course.id][i], ...optionsByCourse[course.id][i]]
  return { id: `${course.id}-q${i + 1}`, course: course.id, topic: 'Anatomie', prompt, options, correct: [0], why: options.map((_, j) => j === 0 ? explanations[course.id][i] : 'Cette option correspond à une autre structure ou à un rapport anatomique différent.'), difficulty: i < 2 ? 'essentiel' as const : 'application' as const, format: 'single' as const }
}))
