import type { Course } from '../../curriculum'
import type { Question } from '../../questions'
import { canonicalCourses } from '../../taxonomy/canonicalCourses'

const meta = new Map(canonicalCourses.filter(item => item.subject === 'Anatomie').map(item => [item.id, item]))
const pelvic = 'https://openstax.org/books/anatomy-and-physiology-2e/pages/11-4-axial-muscles-of-the-abdominal-wall-and-thorax'
const vessels = 'https://openstax.org/books/anatomy-and-physiology-2e/pages/20-5-circulatory-pathways'
const nerve = 'https://openstax.org/books/anatomy-and-physiology-2e/pages/13-4-the-peripheral-nervous-system'
type D = { objectives: string[]; sections: Course['sections']; trap: string; recall: string; answer: string; source: string; case: string; caseAnswer: string }
const s = (title: string, text: string) => ({ title, text })
const make = (id: string, d: D): Course => {
  const c = meta.get(id); if (!c) throw new Error(`Identifiant anatomique absent : ${id}`)
  return { id, title: c.title, category: c.subject, tag: c.module, minutes: 15, structure: null, objectives: d.objectives,
    sections: d.sections, trap: d.trap, recall: d.recall, answer: d.answer, source: d.source,
    sources: [{ label: 'OpenStax · Anatomy & Physiology 2e', url: d.source }], prerequisites: ['Anatomie topographique et plans anatomiques'],
    glossary: [['Repère anatomique', 'Relation spatiale utile pour décrire et retrouver une structure.'], ['Territoire', 'Région desservie ou traversée par une structure anatomique.'], ['Variation anatomique', 'Différence interindividuelle pouvant modifier un trajet ou un rapport.']],
    caseStudy: { prompt: d.case, answer: d.caseAnswer }, review: { status: 'unreviewed', updatedAt: '2026-09-23', sourcesUpdatedAt: '2026-09-23' } }
}
export const pelvisHeadNeckCourses: Course[] = [
  make('anat-perineum-pelvic-floor', { objectives: ['Délimiter le périnée et ses deux triangles', 'Décrire les composants du diaphragme pelvien', 'Relier soutien viscéral et continence aux muscles du plancher'], source: pelvic,
    sections: [s('Limites du périnée', 'Le périnée est la région losangique sous le diaphragme pelvien. Ses limites osseuses sont la symphyse pubienne en avant, le coccyx en arrière et les tubérosités ischiatiques latéralement ; les lignes entre tubérosités le divisent en triangle urogénital antérieur et triangle anal postérieur.'), s('Diaphragme pelvien', 'Le plancher pelvien comprend surtout le muscle élévateur de l’anus — puborectal, pubococcygien et iliococcygien — et le muscle coccygien. Il ferme l’ouverture inférieure du pelvis tout en laissant traverser les conduits digestifs et urogénitaux.'), s('Hiatus et soutien', 'Le hiatus urogénital est traversé par l’urètre et, chez la femme, le vagin. Les muscles et fascias soutiennent vessie, rectum et organes génitaux internes contre la pression abdominale. Les insertions et la morphologie varient entre individus.'), s('Triangle anal', 'Le triangle anal contient le canal anal et les fosses ischio-anales, espaces graisseux latéraux qui permettent la distension du canal. Le sphincter externe de l’anus est strié et volontaire ; le sphincter interne est un épaississement involontaire du muscle lisse.'), s('Fonctions et innervation', 'Le plancher pelvien participe au soutien des viscères, à la continence et à la coordination de la miction, de la défécation et de l’accouchement. L’innervation est plurielle, avec notamment des contributions sacrées et pudendales ; elle ne se résume pas à un nerf unique.')], trap: 'Le diaphragme pelvien est profond et supérieur au périnée superficiel ; les fosses ischio-anales appartiennent au triangle anal.', recall: 'Quels muscles forment principalement le diaphragme pelvien ?', answer: 'L’élévateur de l’anus (puborectal, pubococcygien, iliococcygien) et le coccygien.', case: 'Une coupe montre un espace graisseux de part et d’autre du canal anal, sous l’élévateur de l’anus. Quel espace est décrit ?', caseAnswer: 'Les fosses ischio-anales, situées dans le triangle anal et permettant l’expansion du canal anal.' }),
  make('anat-iliac-vessels', { objectives: ['Suivre la bifurcation aortique et les artères iliaques', 'Distinguer les territoires interne et externe', 'Relier les veines iliaques à la veine cave inférieure'], source: vessels,
    sections: [s('Bifurcation aortique', 'L’aorte abdominale se divise habituellement en deux artères iliaques communes vers le niveau L4. Chacune se dirige vers le pelvis et se divise près de l’articulation sacro-iliaque en artère iliaque interne et artère iliaque externe, avec des variations de niveau et de branchement.'), s('Artère iliaque interne', 'L’iliaque interne descend dans le pelvis et donne des branches viscérales et pariétales. Elle vascularise une grande part des parois et viscères pelviens, le périnée et les régions glutéales. Les branches antérieure et postérieure sont des descriptions utiles, mais l’anatomie réelle varie.'), s('Artère iliaque externe', 'L’iliaque externe longe le bord médial du psoas et passe sous le ligament inguinal pour devenir l’artère fémorale. Elle donne notamment les artères épigastrique inférieure et circonflexe iliaque profonde, qui participent aux réseaux de la paroi abdominale.'), s('Retour veineux', 'Les veines iliaques internes drainent les territoires pelviens ; les veines iliaques externes prolongent le retour des membres inférieurs et reçoivent des affluents pariétaux. Les veines iliaques communes résultent de leur réunion et s’unissent habituellement vers L5 pour former la veine cave inférieure.'), s('Rapports et applications', 'Les axes iliaques sont au voisinage des uretères, des chaînes lymphatiques, des plexus nerveux et des organes pelviens. Les rapports changent selon le sexe, le remplissage viscéral et les variantes. La description de leur trajet aide à comprendre les cartes vasculaires et d’imagerie sans remplacer une lecture spécialisée.')], trap: 'L’artère iliaque externe devient fémorale sous le ligament inguinal ; l’iliaque interne reste l’axe majeur des viscères et parois pelviens.', recall: 'Quelle artère prolonge l’iliaque externe dans la cuisse ?', answer: 'L’artère fémorale, après le passage sous le ligament inguinal.', case: 'Un trajet artériel passe sous le ligament inguinal vers le membre inférieur. Quel axe pelvien lui donne naissance ?', caseAnswer: 'L’artère iliaque externe, qui se poursuit comme artère fémorale.' }),
  make('anat-pharynx-esophagus-cervical', { objectives: ['Délimiter les trois étages du pharynx', 'Suivre le bol alimentaire vers l’œsophage cervical', 'Situer les rapports pharyngés avec voies aériennes et rachis'], source: nerve,
    sections: [s('Organisation du pharynx', 'Le pharynx est un conduit musculo-membraneux commun aux voies respiratoires et digestives, étendu de la base du crâne jusqu’à l’œsophage. Il est situé en arrière des cavités nasale, orale et laryngée et en avant des fascias prévertébraux.'), s('Nasopharynx', 'Le nasopharynx se trouve au-dessus du voile du palais et communique avec les choanes. Il contient les orifices des trompes auditives et du tissu lymphoïde pharyngé. L’air y circule, tandis que les aliments sont dirigés vers l’oropharynx lorsque le voile s’élève pendant la déglutition.'), s('Oropharynx et laryngopharynx', 'L’oropharynx s’étend du voile du palais à l’épiglotte et reçoit les voies orale et pharyngée. Le laryngopharynx se poursuit derrière le larynx jusqu’au bord inférieur du cartilage cricoïde, vers C6, où débute l’œsophage.'), s('Constrictors et déglutition', 'Les muscles constricteurs supérieur, moyen et inférieur propulsent le bol vers l’œsophage. Les muscles longitudinaux élèvent le pharynx. La déglutition coordonne fermeture nasale, protection laryngée et progression digestive ; plusieurs nerfs crâniens y participent.'), s('Œsophage cervical', 'L’œsophage commence derrière le cricoïde vers C6, descend en arrière de la trachée et traverse le thorax avant l’estomac. Le sphincter supérieur est fonctionnellement associé au muscle cricopharyngien. Les rapports vasculaires, nerveux et thyroïdiens sont importants mais variables selon le niveau.')], trap: 'Le nasopharynx est respiratoire ; l’oropharynx et le laryngopharynx sont des voies communes, et l’œsophage débute vers C6.', recall: 'À quel niveau le laryngopharynx se poursuit-il par l’œsophage ?', answer: 'Vers C6, au bord inférieur du cartilage cricoïde.', case: 'Une endoscopie passe derrière le larynx et atteint le conduit digestif au niveau du cricoïde. Quelle transition observe-t-elle ?', caseAnswer: 'La transition du laryngopharynx vers l’œsophage cervical, classiquement au niveau C6.' }),
  make('anat-larynx-trachea-thyroid', { objectives: ['Repérer les principaux cartilages du larynx', 'Suivre la trachée cervicale et sa bifurcation', 'Décrire la position de la thyroïde et ses rapports'], source: nerve,
    sections: [s('Squelette laryngé', 'Le larynx relie le laryngopharynx à la trachée et comprend les cartilages thyroïde, cricoïde et épiglottique, ainsi que des cartilages aryténoïdes pairs. Le cricoïde forme un anneau complet ; le cartilage thyroïde protège en avant une partie des structures laryngées.'), s('Glotte et phonation', 'Les plis vocaux vrais s’attachent en avant au cartilage thyroïde et en arrière aux aryténoïdes. Leur position et leur tension règlent la phonation et la glotte. Les plis vestibulaires sont supérieurs et ne sont pas les cordes vocales principales.'), s('Trachée', 'La trachée commence sous le cricoïde vers C6, descend en avant de l’œsophage et est maintenue ouverte par des anneaux cartilagineux incomplets en arrière. Elle se divise au niveau de la carène vers T4–T5 en bronches principales droite et gauche.'), s('Glande thyroïde', 'La thyroïde est antérieure et latérale à la trachée cervicale, avec deux lobes réunis par un isthme qui croise souvent les anneaux trachéaux supérieurs. Un lobe pyramidal peut exister. Les rapports avec nerfs laryngés récurrents, artères thyroïdiennes et parathyroïdes présentent des variantes.'), s('Vascularisation et fonctions', 'La thyroïde est richement vascularisée par les artères thyroïdiennes supérieure et inférieure, avec une artère thyroïdienne ima inconstante. Le larynx protège les voies respiratoires, participe à la phonation et à la toux. Ces rapports expliquent la proximité fonctionnelle de structures respiratoires, endocrines et nerveuses.')], trap: 'La carène est thoracique vers T4–T5 ; C6 repère plutôt le début de la trachée et de l’œsophage.', recall: 'Quels cartilages portent les plis vocaux vrais en arrière ?', answer: 'Les cartilages aryténoïdes.', case: 'Une coupe cervicale montre une glande à deux lobes reliés en avant de la trachée. Quelle glande est identifiée ?', caseAnswer: 'La glande thyroïde, dont l’isthme croise habituellement les anneaux trachéaux supérieurs.' }),
  make('anat-skull-base-foramina', { objectives: ['Organiser la base du crâne en trois fosses', 'Associer les principaux foramens à leurs contenus', 'Utiliser ces passages comme repères neurovasculaires'], source: nerve,
    sections: [s('Fosse crânienne antérieure', 'La fosse antérieure porte les lobes frontaux et comprend notamment la lame criblée de l’ethmoïde, traversée par les filets olfactifs. Le canal optique transmet le nerf optique et l’artère ophtalmique vers l’orbite. Les foramens et leurs contenus sont à apprendre par région, en gardant à l’esprit les variantes.'), s('Fosse crânienne moyenne', 'La fosse moyenne accueille les lobes temporaux et la selle turcique. La fissure orbitaire supérieure transmet plusieurs nerfs oculomoteurs et la branche ophtalmique du trijumeau ; le foramen rond transmet V2, le foramen ovale V3, et le foramen épineux l’artère méningée moyenne.'), s('Foramen lacerum et canal carotidien', 'Le canal carotidien conduit l’artère carotide interne et son plexus sympathique. Le foramen lacerum est largement comblé par du cartilage en vie ; la carotide passe au-dessus de sa partie supérieure après le canal carotidien, elle ne le traverse pas verticalement.'), s('Fosse postérieure', 'La fosse postérieure contient cervelet et tronc cérébral. Le méat acoustique interne transmet les nerfs facial et vestibulocochléaire ; le foramen jugulaire transmet les nerfs IX, X et XI ainsi que des voies veineuses ; le canal hypoglosse transmet le nerf XII.'), s('Foramen magnum', 'Le foramen magnum relie cavité crânienne et canal vertébral. Il transmet la jonction bulbo-médullaire, les méninges, les artères vertébrales, des racines spinales du nerf accessoire et des structures vasculaires. Les rapports de la charnière cranio-cervicale sont tridimensionnels et ne se réduisent pas à une liste de trous.')], trap: 'La carotide interne emprunte le canal carotidien puis passe au-dessus du foramen lacerum ; V2 passe par le rond et V3 par l’ovale.', recall: 'Quels nerfs crâniens passent ensemble par le foramen jugulaire ?', answer: 'Les nerfs glossopharyngien IX, vague X et accessoire XI.', case: 'Une structure nerveuse quitte la fosse moyenne par le foramen ovale. Quelle branche du trijumeau suit-elle ?', caseAnswer: 'Le nerf mandibulaire V3.' }),
  make('anat-masticatory-muscles-tmj', { objectives: ['Nommer les muscles masticateurs et leurs actions', 'Décrire les surfaces et le disque de l’ATM', 'Relier mouvements mandibulaires aux insertions musculaires'], source: nerve,
    sections: [s('Articulation temporomandibulaire', 'L’ATM unit la tête mandibulaire à la fosse mandibulaire et au tubercule articulaire de l’os temporal. Un disque fibrocartilagineux sépare la cavité en compartiments supérieur et inférieur ; l’articulation combine rotation et translation pendant l’ouverture.'), s('Muscles élévateurs', 'Le masséter s’étend de l’arcade zygomatique à la face latérale de la mandibule, et le temporal converge vers le processus coronoïde. Ils élèvent la mandibule ; les fibres postérieures du temporal contribuent à la rétropulsion.'), s('Ptérygoïdiens', 'Le ptérygoïdien médial s’insère sur la face médiale de l’angle mandibulaire et participe à l’élévation. Le ptérygoïdien latéral s’attache notamment au col mandibulaire, à la capsule et au disque ; il contribue à la protrusion et à la translation condylienne. Les actions sont bilatérales ou unilatérales selon le mouvement.'), s('Mouvements mandibulaires', 'L’ouverture initiale comporte surtout rotation dans le compartiment inférieur, puis une translation antérieure du complexe condyle-disque dans le compartiment supérieur. La protrusion est principalement assurée par les ptérygoïdiens latéraux ; les mouvements latéraux associent des actions asymétriques des muscles.'), s('Innervation et rapports', 'Les muscles masticateurs dérivent du premier arc pharyngé et sont innervés par la branche mandibulaire du trijumeau V3. L’ATM est proche du méat acoustique externe, de la parotide et de branches du nerf facial. Le disque et les surfaces articulaires distribuent les contraintes, mais leur fonctionnement varie avec la morphologie.')], trap: 'Le ptérygoïdien latéral est un acteur majeur de la translation et de la protrusion ; l’ouverture n’est pas une simple charnière.', recall: 'Quel nerf innerve les muscles masticateurs ?', answer: 'La branche mandibulaire V3 du nerf trijumeau.', case: 'Lors d’une protrusion mandibulaire, quel muscle pair entraîne surtout l’avancée des condyles et du disque ?', caseAnswer: 'Les muscles ptérygoïdiens latéraux, notamment par leur action bilatérale.' }),
  make('anat-cervical-fascias-triangles', { objectives: ['Décrire les couches fasciales du cou', 'Délimiter les trigones antérieur et postérieur', 'Relier compartiments et voies de diffusion des infections'], source: nerve,
    sections: [s('Fascia cervical superficiel', 'Le tissu sous-cutané du cou contient notamment le muscle platysma, des veines superficielles et des branches cutanées nerveuses. Le fascia cervical profond est classiquement décrit en lames et gaines, mais la terminologie et les limites exactes varient selon les référentiels anatomiques.'), s('Lame superficielle', 'La lame d’investissement entoure le cou et enveloppe les muscles sternocléidomastoïdien et trapèze. Elle contribue aux attaches fasciales de la mandibule, du sternum, des clavicules et des processus épineux. Les espaces potentiels peuvent guider la diffusion d’un processus infectieux.'), s('Lames viscérale et prévertébrale', 'La lame prétrachéale entoure les viscères cervicaux et se prolonge vers le médiastin ; la lame prévertébrale entoure colonne et muscles profonds et forme une gaine axillaire. La gaine carotidienne rassemble carotide, veine jugulaire interne et nerf vague, avec des tissus lymphatiques et sympathiques associés.'), s('Trigone antérieur', 'Le trigone antérieur est limité par la ligne médiane, le bord antérieur du sternocléidomastoïdien et le bord inférieur de la mandibule. Les sous-triangles classiquement décrits sont submandibulaire, submental, carotidien et musculaire, avec des contenus propres et des frontières façonnées par les muscles.'), s('Trigone postérieur', 'Le trigone postérieur se situe entre les bords postérieurs du sternocléidomastoïdien et antérieur du trapèze, au-dessus de la clavicule. Le ventre inférieur de l’omohyoïdien le divise en triangles occipital et omoclaviculaire. Le nerf accessoire, des branches du plexus cervical et des éléments vasculaires traversent cette région.')], trap: 'La gaine carotidienne contient classiquement carotide, jugulaire interne et vague ; les fascias cervicaux sont des plans continus, pas des enveloppes hermétiques simples.', recall: 'Quel muscle sépare les triangles occipital et omoclaviculaire ?', answer: 'Le ventre inférieur du muscle omohyoïdien.', case: 'Un repère de surface est délimité par sternocléidomastoïdien, trapèze et clavicule. Quel trigone est décrit ?', caseAnswer: 'Le trigone cervical postérieur.' }),
  make('anat-carotid-jugular-axes', { objectives: ['Suivre les carotides communes et leurs divisions', 'Comparer les territoires des carotides interne et externe', 'Situer l’axe jugulaire dans la gaine carotidienne'], source: vessels,
    sections: [s('Carotides communes', 'Les carotides communes droite et gauche montent dans le cou ; la droite naît du tronc brachiocéphalique et la gauche directement de l’arche aortique. Elles se divisent habituellement près du bord supérieur du cartilage thyroïde, autour de C4, en carotides interne et externe.'), s('Sinus et glomus carotidiens', 'Le sinus carotidien est une dilatation sensible à la pression au début de la carotide interne. Le glomus carotidien est un chémorécepteur à la bifurcation, sensible notamment aux variations des gaz sanguins et du pH. Ces structures ont des rôles réflexes distincts.'), s('Carotide interne', 'La carotide interne ne donne normalement pas de branches dans le cou. Elle pénètre dans le canal carotidien, traverse la base du crâne et participe à l’irrigation de l’encéphale et de l’orbite par ses branches intracrâniennes, dont l’artère ophtalmique.'), s('Carotide externe', 'La carotide externe donne des branches cervicales destinées notamment à la thyroïde, la langue, la face, le cuir chevelu et la région occipitale. Ses branches terminales sont l’artère maxillaire et l’artère temporale superficielle. Les variantes d’origine et de trajet sont courantes.'), s('Veine jugulaire interne et gaine', 'La jugulaire interne débute au foramen jugulaire, descend dans la gaine carotidienne avec la carotide et le nerf vague, puis s’unit à la subclavière pour former la veine brachiocéphalique. Dans le repère classique, elle est latérale à la carotide ; les positions individuelles varient et les repères de surface ne garantissent pas une relation identique chez tous.')], trap: 'La carotide interne n’émet pas de branches cervicales habituelles ; la carotide externe irrigue surtout face et structures superficielles de la tête.', recall: 'Quelles sont les deux branches terminales de la carotide externe ?', answer: 'L’artère maxillaire et l’artère temporale superficielle.', case: 'Un axe veineux du cou rejoint la veine subclavière derrière la clavicule. Quel vaisseau forme-t-il ?', caseAnswer: 'La veine brachiocéphalique, par réunion de la jugulaire interne et de la subclavière.' }),
  make('anat-oral-cavity-salivary-glands', { objectives: ['Décrire les limites de la cavité orale', 'Distinguer langue mobile et base linguale', 'Comparer les trois glandes salivaires majeures et leurs conduits'], source: nerve,
    sections: [s('Vestibule et cavité orale propre', 'La cavité orale comprend le vestibule entre lèvres-joues et arcades dentaires, puis la cavité orale propre en dedans des dents. Le palais dur en forme le toit antérieur et le palais mou le toit postérieur ; le plancher est occupé par la langue et les tissus sublinguaux.'), s('Langue et papilles', 'La langue comporte une partie orale antérieure mobile et une base pharyngée postérieure, séparées en surface par le sillon terminal. Les muscles intrinsèques modifient sa forme et les extrinsèques déplacent l’organe. Les papilles filiformes sont mécaniques ; plusieurs autres types portent des bourgeons gustatifs.'), s('Glande parotide', 'La parotide est la plus volumineuse glande salivaire majeure, située en avant et sous l’oreille. Son conduit traverse le masséter, perce le buccinateur et s’ouvre dans le vestibule en regard de la deuxième molaire maxillaire. Le nerf facial la traverse, sans assurer sa sécrétion.'), s('Glandes submandibulaire et sublinguale', 'La submandibulaire est sous le corps mandibulaire ; son conduit s’ouvre près du frein lingual sur la caroncule sublinguale. La sublinguale, située sous la muqueuse du plancher buccal, possède plusieurs petits conduits qui s’ouvrent le long du pli sublingual et parfois un conduit majeur.'), s('Salive, innervation et fonctions', 'La salive lubrifie, facilite la déglutition, protège les muqueuses et participe à la digestion initiale. Les voies parasympathiques des glandes majeures passent par les nerfs facial VII ou glossopharyngien IX selon la glande, via des relais ganglionnaires ; l’innervation sympathique module également les sécrétions.')], trap: 'Le conduit parotidien s’ouvre près de la deuxième molaire maxillaire ; le nerf facial traverse la parotide mais ne fournit pas sa sécrétion parasympathique.', recall: 'Où débouche le conduit parotidien ?', answer: 'Dans le vestibule oral, en regard de la deuxième molaire supérieure.', case: 'Une papille ductale s’observe en regard de la deuxième molaire maxillaire. Quel conduit s’y ouvre ?', caseAnswer: 'Le conduit parotidien (de Sténon). ' })
]

const prompts: Record<string, string[]> = {
  'anat-perineum-pelvic-floor': ['Quels muscles constituent surtout le diaphragme pelvien ?', 'Quels repères osseux délimitent le losange périnéal ?', 'Quel triangle périnéal contient le canal anal ?', 'Quel sphincter anal est strié et volontaire ?', 'Quelle est une fonction essentielle du plancher pelvien ?'],
  'anat-iliac-vessels': ['À quel niveau se divise habituellement l’aorte en iliaques communes ?', 'Quelle artère devient fémorale sous le ligament inguinal ?', 'Quelle artère irrigue la majorité des viscères pelviens ?', 'Quelle veine rejoint la veine iliaque externe pour former une iliaque commune ?', 'Où les iliaques communes forment-elles la veine cave inférieure ?'],
  'anat-pharynx-esophagus-cervical': ['Quel étage du pharynx communique avec les choanes ?', 'Quel étage pharyngé est postérieur au larynx ?', 'Vers quel niveau débute classiquement l’œsophage ?', 'Quels muscles propulsent le bol alimentaire dans le pharynx ?', 'Quelle structure élévatrice ferme la communication avec le nasopharynx pendant la déglutition ?'],
  'anat-larynx-trachea-thyroid': ['Quels cartilages portent les plis vocaux vrais en arrière ?', 'Vers quel niveau débute la trachée cervicale ?', 'À quel niveau se trouve la carène trachéale ?', 'Où se situe l’isthme thyroïdien habituellement ?', 'Quel cartilage laryngé forme un anneau complet ?'],
  'anat-skull-base-foramina': ['Quel nerf passe par le foramen rond ?', 'Quelle branche du trijumeau traverse le foramen ovale ?', 'Quels nerfs passent par le foramen jugulaire ?', 'Quel nerf passe dans le canal hypoglosse ?', 'La carotide interne traverse-t-elle le foramen lacerum ?'],
  'anat-masticatory-muscles-tmj': ['Quel nerf innerve les muscles masticateurs ?', 'Quel muscle s’insère sur le processus coronoïde ?', 'Quel muscle favorise la protrusion mandibulaire ?', 'Quel tissu sépare les compartiments de l’ATM ?', 'Quel mouvement s’effectue d’abord lors de l’ouverture buccale ?'],
  'anat-cervical-fascias-triangles': ['Quels éléments cheminent classiquement dans la gaine carotidienne ?', 'Quel muscle borde les deux trigones cervicaux ?', 'Quel muscle divise le trigone postérieur en deux ?', 'Quels sous-triangles appartiennent au trigone antérieur ?', 'Quelle lame fasciale entoure les muscles prévertébraux ?'],
  'anat-carotid-jugular-axes': ['À quel niveau la carotide commune se divise-t-elle généralement ?', 'La carotide interne donne-t-elle habituellement des branches cervicales ?', 'Quelles sont les deux branches terminales de la carotide externe ?', 'Quel nerf accompagne les axes carotidiens dans la gaine ?', 'Quelles veines forment la veine brachiocéphalique ?'],
  'anat-oral-cavity-salivary-glands': ['Où débouche le conduit parotidien ?', 'Quelle glande salivaire possède un conduit s’ouvrant près du frein lingual ?', 'Quel nerf traverse la parotide sans assurer sa sécrétion ?', 'Quelle portion de langue est située en arrière du sillon terminal ?', 'Quelles glandes majeures possèdent des conduits dans le plancher oral ?']
}
const answers: Record<string, string[]> = {
  'anat-perineum-pelvic-floor': ['L’élévateur de l’anus et le coccygien.', 'Symphyse pubienne, coccyx et tubérosités ischiatiques.', 'Le triangle anal postérieur.', 'Le sphincter externe de l’anus.', 'Soutien des viscères pelviens et participation à la continence.'],
  'anat-iliac-vessels': ['Vers L4.', 'L’artère iliaque externe.', 'L’artère iliaque interne.', 'La veine iliaque interne.', 'Habituellement vers L5.'],
  'anat-pharynx-esophagus-cervical': ['Le nasopharynx.', 'Le laryngopharynx.', 'Vers C6, au bord inférieur du cricoïde.', 'Les constricteurs pharyngés.', 'Le voile du palais.'],
  'anat-larynx-trachea-thyroid': ['Les cartilages aryténoïdes.', 'Vers C6.', 'Vers T4–T5, près de l’angle sternal.', 'En avant de la trachée cervicale, sur ses anneaux supérieurs.', 'Le cartilage cricoïde.'],
  'anat-skull-base-foramina': ['V2, le nerf maxillaire.', 'V3, le nerf mandibulaire.', 'IX, X et XI.', 'Le nerf XII.', 'Non, elle passe au-dessus de sa partie supérieure après le canal carotidien.'],
  'anat-masticatory-muscles-tmj': ['La branche mandibulaire V3 du trijumeau.', 'Le muscle temporal.', 'Le ptérygoïdien latéral.', 'Le disque fibrocartilagineux articulaire.', 'Une rotation condylienne dans le compartiment inférieur.'],
  'anat-cervical-fascias-triangles': ['La carotide, la jugulaire interne et le nerf vague.', 'Le sternocléidomastoïdien.', 'Le ventre inférieur de l’omohyoïdien.', 'Submandibulaire, submental, carotidien et musculaire.', 'La lame prévertébrale.'],
  'anat-carotid-jugular-axes': ['Près de C4, au bord supérieur du cartilage thyroïde.', 'Non, elle n’en donne normalement pas dans le cou.', 'L’artère maxillaire et l’artère temporale superficielle.', 'Le nerf vague.', 'La jugulaire interne et la subclavière.'],
  'anat-oral-cavity-salivary-glands': ['Dans le vestibule en regard de la deuxième molaire maxillaire.', 'La glande submandibulaire.', 'Le nerf facial VII.', 'La racine ou base pharyngée de la langue.', 'Les glandes submandibulaires et sublinguales.']
}
const wrong: Record<string, string[][]> = Object.fromEntries(Object.keys(prompts).map(id => [id, prompts[id].map(() => ['Dans le ventricule gauche.', 'Au niveau de la clavicule.', 'Dans le canal thoracique.'])]))
const why: Record<string, string[]> = Object.fromEntries(Object.entries(answers).map(([id, values]) => [id, values.map((_, i) => `Le repère anatomique demandé est celui décrit dans le cours ${i + 1}.`)]))
export const pelvisHeadNeckQuestions: Question[] = pelvisHeadNeckCourses.flatMap(course => prompts[course.id].map((prompt, i) => {
  const options = [answers[course.id][i], ...wrong[course.id][i]]
  return { id: `${course.id}-q${i + 1}`, course: course.id, topic: 'Anatomie', prompt, options, correct: [0], why: options.map((_, j) => j === 0 ? why[course.id][i] : 'Ce repère ne correspond pas à la structure demandée.'), difficulty: i < 2 ? 'essentiel' as const : 'application' as const, format: 'single' as const }
}))
