import type { Course } from '../../curriculum'
import type { Question } from '../../questions'
import { canonicalCourses } from '../../taxonomy/canonicalCourses'

const meta = new Map(canonicalCourses.filter(item => item.subject === 'Anatomie').map(item => [item.id, item]))
const heart = 'https://openstax.org/books/anatomy-and-physiology-2e/pages/19-1-heart-anatomy'
const vessels = 'https://openstax.org/books/anatomy-and-physiology-2e/pages/20-5-circulatory-pathways'
const lungs = 'https://openstax.org/books/anatomy-and-physiology-2e/pages/22-1-organs-and-structures-of-the-respiratory-system'
const conduction = 'https://openstax.org/books/anatomy-and-physiology-2e/pages/19-2-cardiac-muscle-and-electrical-activity'
type D = { objectives: string[]; sections: Course['sections']; trap: string; recall: string; answer: string; source: string; glossary: NonNullable<Course['glossary']>; caseStudy: NonNullable<Course['caseStudy']> }
const s = (title: string, text: string) => ({ title, text })
const make = (id: string, d: D): Course => {
  const c = meta.get(id); if (!c) throw new Error(`Identifiant anatomique absent : ${id}`)
  return { id, title: c.title, category: c.subject, tag: c.module, minutes: 15, structure: null, objectives: d.objectives,
    sections: d.sections, trap: d.trap, recall: d.recall, answer: d.answer, source: d.source,
    sources: [{ label: 'OpenStax · Anatomy & Physiology 2e', url: d.source }], prerequisites: ['Médiastin et cavités thoraciques', 'Repères d’anatomie cardiovasculaire et respiratoire'],
    glossary: d.glossary, caseStudy: d.caseStudy, review: { status: 'unreviewed', updatedAt: '2026-09-23', sourcesUpdatedAt: '2026-09-23' } }
}
export const thoraxVisceraCourses: Course[] = [
  make('anat-heart-chambers-valves', {
    objectives: ['Suivre le sang à travers les quatre cavités', 'Localiser les quatre valves et leurs supports', 'Relier surfaces cardiaques aux grandes structures entrantes et sortantes'],
    sections: [
      s('Position et enveloppes', 'Le cœur est situé dans le médiastin moyen, derrière le sternum, au-dessus du diaphragme et entre les poumons. Son apex se projette vers le bas, l’avant et la gauche ; sa base est postérieure et reçoit les gros vaisseaux. Le péricarde fibreux et séreux l’entoure, avec un espace potentiel contenant une petite quantité de liquide.'),
      s('Cavités droites', 'L’atrium droit reçoit veines caves supérieure et inférieure ainsi que le sinus coronaire. Il communique avec le ventricule droit par la valve tricuspide. Le ventricule droit présente trabécules charnues, muscles papillaires et cordages tendineux ; il éjecte vers le tronc pulmonaire à travers la valve pulmonaire.'),
      s('Cavités gauches', 'L’atrium gauche reçoit habituellement quatre veines pulmonaires et communique avec le ventricule gauche par la valve mitrale. Le ventricule gauche possède une paroi plus épaisse car il propulse le sang dans la circulation systémique. Il éjecte dans l’aorte à travers la valve aortique ; ses muscles papillaires et cordages stabilisent la valve mitrale.'),
      s('Squelette fibreux et valves', 'Les anneaux fibreux entourent les orifices et soutiennent les valves. Les valves atrioventriculaires s’ouvrent en diastole ventriculaire et se ferment lorsque la pression ventriculaire dépasse la pression atriale ; les cordages limitent leur prolapsus. Les valves sigmoïdes s’ouvrent à l’éjection et se ferment lors de l’inversion du gradient, sans cordages.'),
      s('Surfaces et repères', 'La face sternocostale est surtout ventriculaire droite ; la face diaphragmatique est principalement ventriculaire gauche et droite ; la base est majoritairement atriale gauche. Les sillons coronaires et interventriculaires marquent les séparations externes. Les repères de surface sont approximatifs et ne remplacent pas l’imagerie ou l’examen.'),
    ], trap: 'Les veines pulmonaires se déversent dans l’atrium gauche ; les veines caves et le sinus coronaire rejoignent l’atrium droit.', recall: 'Quel trajet suit une goutte de sang depuis la veine cave jusqu’à l’aorte ?', answer: 'Atrium droit → tricuspide → ventricule droit → valve pulmonaire → poumons → veines pulmonaires → atrium gauche → mitrale → ventricule gauche → valve aortique → aorte.', source: heart, glossary: [['Valve atrioventriculaire', 'Valve entre atrium et ventricule, soutenue par cordages et muscles papillaires.'], ['Valve sigmoïde', 'Valve aortique ou pulmonaire dépourvue de cordages tendineux.'], ['Trabécule charnue', 'Relief musculaire de la surface interne ventriculaire.']], caseStudy: { prompt: 'Une régurgitation mitrale permet un reflux du ventricule gauche vers quelle cavité ?', answer: 'Vers l’atrium gauche pendant la systole ventriculaire.' }
  }),
  make('anat-coronary-vessels', {
    objectives: ['Décrire les origines et trajets des artères coronaires', 'Associer branches à territoires myocardiques', 'Suivre le drainage veineux coronaire'],
    sections: [
      s('Origine aortique', 'Les artères coronaires droite et gauche naissent des sinus aortiques au-dessus des cuspides de la valve aortique. Le remplissage coronaire gauche prédomine surtout en diastole car la contraction ventriculaire comprime ses vaisseaux intramyocardiques. Les ostia et la dominance coronaire varient, ce qui influence l’irrigation des territoires.'),
      s('Coronaire gauche', 'Le tronc coronaire gauche passe entre le tronc pulmonaire et l’auricule gauche puis se divise le plus souvent en interventriculaire antérieure et circonflexe. L’interventriculaire antérieure descend dans le sillon interventriculaire antérieur avec la grande veine cardiaque, émet des diagonales et des septales. La circonflexe suit le sillon atrioventriculaire gauche et donne des marginales obtuses.'),
      s('Coronaire droite', 'La coronaire droite chemine dans le sillon atrioventriculaire droit et donne des branches marginales droites. Elle peut donner l’artère interventriculaire postérieure dans le sillon postérieur ; la dominance est définie par l’origine de cette artère, droite dans la majorité des cas. Les branches nodales sino-atriale et atrioventriculaire ont une origine variable.'),
      s('Territoires et dominance', 'L’interventriculaire antérieure irrigue une partie majeure des parois ventriculaires antérieures et du septum interventriculaire. La circonflexe dessert des territoires latéraux et postérieurs gauches ; la droite dessert souvent ventricule droit et régions inférieures. Les chevauchements et anastomoses limités rendent l’anatomie individuelle importante.'),
      s('Drainage veineux', 'Les veines cardiaques grande, moyenne et petite accompagnent souvent les sillons et drainent dans le sinus coronaire, qui se jette dans l’atrium droit. Des veines antérieures du ventricule droit s’abouchent directement dans l’atrium droit ; de petites veines cardiaques s’ouvrent directement dans les cavités. Le drainage n’est donc pas exclusivement sinusal.'),
    ], trap: 'La dominance coronaire est définie par l’origine de l’artère interventriculaire postérieure, et non par la taille du tronc coronaire.', recall: 'Dans quel sillon chemine l’artère interventriculaire antérieure ?', answer: 'Dans le sillon interventriculaire antérieur, avec la grande veine cardiaque.', source: vessels, glossary: [['Dominance coronaire', 'Définie par l’artère qui donne l’interventriculaire postérieure.'], ['Artère diagonale', 'Branche de l’interventriculaire antérieure irriguant la paroi antérolatérale.'], ['Sinus coronaire', 'Collecteur veineux principal se drainant dans l’atrium droit.']], caseStudy: { prompt: 'Une occlusion de l’interventriculaire antérieure menace particulièrement quel territoire ?', answer: 'Le septum interventriculaire antérieur et une large part des parois antérieures des ventricules, selon la distribution individuelle.' }
  }),
  make('anat-cardiac-conduction-nodes', {
    objectives: ['Localiser les nœuds sino-atrial et atrioventriculaire', 'Suivre le faisceau atrioventriculaire et ses branches', 'Relier conduction et contraction coordonnée'],
    sections: [
      s('Nœud sino-atrial', 'Le nœud sino-atrial se situe dans l’atrium droit, près de l’abouchement de la veine cave supérieure et du sillon terminal. Ses cellules pacemaker initient généralement le rythme sinusal. L’apport artériel vient d’une branche dont l’origine est souvent coronaire droite mais peut être circonflexe.'),
      s('Propagation atriale et nœud AV', 'L’activation se propage à travers le myocarde atrial vers le nœud atrioventriculaire, situé dans la partie inférieure du septum interatrial près de l’orifice du sinus coronaire et de la valve tricuspide. La conduction y ralentit, permettant un délai entre contraction atriale et ventriculaire. L’innervation autonome module fréquence et conduction.'),
      s('Faisceau de His', 'Le faisceau atrioventriculaire traverse le squelette fibreux, seule connexion électrique normale entre myocarde atrial et ventriculaire. Il descend dans le septum interventriculaire et se divise en branches droite et gauche. Les fascicules gauches conduisent vers des régions antérieures et postérieures, avec variations anatomiques.'),
      s('Réseau de Purkinje', 'Les fibres de Purkinje sous-endocardiques distribuent rapidement le signal au myocarde ventriculaire. L’activation progresse globalement de l’apex vers la base pour coordonner l’éjection vers les voies de sortie. Le système comprend aussi connexions intramyocardiques et ne se résume pas à un simple câble anatomique.'),
      s('Corrélations électriques et anatomiques', 'Le trajet du signal se reflète dans les intervalles et complexes observés à l’ECG, mais un tracé ne localise pas à lui seul toutes les lésions anatomiques. Ischémie, fibrose, médicaments, tonus autonome et déséquilibres électrolytiques peuvent modifier conduction. Le tissu nodal est irrigué par des branches coronaires variables.'),
    ], trap: 'Le faisceau atrioventriculaire est la voie électrique normale qui traverse le squelette fibreux ; les fibres atriales ne se continuent pas directement dans les ventricules.', recall: 'Pourquoi le nœud AV ralentit-il la conduction avant l’activation ventriculaire ?', answer: 'Ce délai permet aux ventricules de recevoir le sang après la contraction atriale et avant leur propre systole.', source: conduction, glossary: [['Nœud sino-atrial', 'Pacemaker physiologique généralement situé près de la veine cave supérieure dans l’atrium droit.'], ['Faisceau atrioventriculaire', 'Voie normale conductrice traversant le squelette fibreux vers les ventricules.'], ['Fibres de Purkinje', 'Réseau sous-endocardique distribuant rapidement l’activation ventriculaire.']], caseStudy: { prompt: 'Un bloc complet du faisceau AV sépare activation atriale et ventriculaire. Quel système peut prendre un rythme d’échappement plus lent ?', answer: 'Un pacemaker jonctionnel ou ventriculaire distal peut décharger plus lentement selon le niveau et l’état du système conducteur.' }
  }),
  make('anat-tracheobronchial-tree', {
    objectives: ['Suivre les voies aériennes depuis la trachée jusqu’aux bronches lobaires', 'Décrire la segmentation bronchopulmonaire', 'Relier bronches, vaisseaux et rapports médiastinaux'],
    sections: [
      s('Trachée thoracique', 'La trachée commence sous le larynx et descend dans le médiastin supérieur, en avant de l’œsophage. Des anneaux cartilagineux en C maintiennent sa lumière ouverte, avec une paroi postérieure membraneuse et le muscle trachéal. Elle se termine à la carène vers l’angle sternal, où elle se divise en bronches principales.'),
      s('Bronches principales', 'La bronche principale droite est généralement plus courte, plus large et plus verticale que la gauche ; un corps étranger inhalé y pénètre donc plus souvent. La gauche passe sous l’arche aortique et en avant de l’œsophage et de l’aorte descendante. Les rapports changent à proximité du hile pulmonaire.'),
      s('Bronches lobaires et segmentaires', 'La bronche principale droite donne trois bronches lobaires et la gauche deux, correspondant aux lobes. Les bronches segmentaires desservent des segments bronchopulmonaires, unités relativement indépendantes séparées par du tissu conjonctif. Chaque segment possède une bronche segmentaire et une branche artérielle pulmonaire ; les veines pulmonaires cheminent plutôt dans les plans intersegmentaires.'),
      s('Hile et racine pulmonaire', 'La racine pulmonaire réunit bronche, artère pulmonaire, veines pulmonaires, vaisseaux bronchiques, lymphatiques et nerfs au hile. L’artère pulmonaire est antérieure à la bronche à droite et supérieure à la bronche à gauche dans les rapports classiques. La disposition doit être apprise par côté et niveau, car la règle RALS résume les rapports artériels.'),
      s('Organisation distale', 'Les bronches perdent progressivement le cartilage et le calibre, deviennent bronchioles puis bronchioles terminales, respiratoires et conduits alvéolaires. La zone conductrice conditionne transport et conditionnement de l’air ; la zone respiratoire porte les alvéoles et les échanges. Les artères bronchiques nourrissent les tissus des voies aériennes, tandis que le réseau pulmonaire réalise les échanges gazeux.'),
    ], trap: 'La bronche droite est plus verticale et reçoit plus souvent les corps étrangers inhalés ; les lobes correspondent aux bronches lobaires.', recall: 'Combien de bronches lobaires possèdent habituellement les poumons droit et gauche ?', answer: 'Trois à droite et deux à gauche.', source: lungs, glossary: [['Carène', 'Crête interne au niveau de la bifurcation trachéale.'], ['Segment bronchopulmonaire', 'Territoire desservi par une bronche segmentaire et une branche artérielle pulmonaire.'], ['Racine pulmonaire', 'Ensemble des conduits et vaisseaux entrant ou sortant au hile.']], caseStudy: { prompt: 'Une résection anatomique suit les plans intersegmentaires. Quel élément veineux est souvent utilisé pour délimiter ces plans ?', answer: 'Les veines pulmonaires intersegmentaires, qui cheminent entre les segments bronchopulmonaires.' }
  })
]
const prompts: Record<string, string[]> = {
  'anat-heart-chambers-valves': ['Où se drainent les veines pulmonaires ?', 'Quelle valve sépare ventricule droit et tronc pulmonaire ?', 'Quelle cavité a la paroi la plus épaisse ?', 'Quels éléments empêchent le prolapsus des valves atrioventriculaires ?', 'Où se situe la base du cœur par rapport à l’apex ?'],
  'anat-coronary-vessels': ['D’où naissent les artères coronaires ?', 'Dans quel sillon descend l’interventriculaire antérieure ?', 'Comment définit-on la dominance coronaire ?', 'Quel collecteur reçoit la majorité du drainage veineux cardiaque ?', 'Quelle coronaire donne souvent les branches nodales ?'],
  'anat-cardiac-conduction-nodes': ['Où se situe le nœud sino-atrial ?', 'Quel est le rôle du délai nodal AV ?', 'Quelle voie traverse le squelette fibreux du cœur ?', 'Où se trouve le réseau de Purkinje ?', 'Le tonus autonome module-t-il la conduction cardiaque ?'],
  'anat-tracheobronchial-tree': ['À quel repère la trachée se divise-t-elle ?', 'Quelle bronche est généralement plus verticale ?', 'Combien de bronches lobaires possède le poumon gauche ?', 'Quel couple structurel définit un segment bronchopulmonaire ?', 'Où cheminent généralement les veines pulmonaires par rapport aux segments ?']
}
const answers: Record<string, string[]> = {
  'anat-heart-chambers-valves': ['Dans l’atrium gauche.', 'La valve pulmonaire.', 'Le ventricule gauche.', 'Les cordages tendineux attachés aux muscles papillaires.', 'La base est postérieure ; l’apex pointe vers le bas, l’avant et la gauche.'],
  'anat-coronary-vessels': ['Des sinus aortiques au-dessus des cuspides aortiques.', 'Le sillon interventriculaire antérieur.', 'Par l’artère qui donne l’interventriculaire postérieure.', 'Le sinus coronaire, qui s’abouche dans l’atrium droit.', 'La coronaire droite, mais l’origine est variable.'],
  'anat-cardiac-conduction-nodes': ['Dans l’atrium droit, près de l’abouchement de la veine cave supérieure.', 'Il laisse le temps à la contraction atriale de précéder la contraction ventriculaire.', 'Le faisceau atrioventriculaire (His).', 'Dans le tissu sous-endocardique ventriculaire.', 'Oui, il modifie fréquence et conduction.'],
  'anat-tracheobronchial-tree': ['À la carène, près de l’angle sternal.', 'La bronche principale droite.', 'Deux.', 'Une bronche segmentaire et une branche artérielle pulmonaire.', 'Dans les plans intersegmentaires.']
}
const wrong: Record<string, string[][]> = {
  'anat-heart-chambers-valves': [['Dans l’atrium droit.', 'Dans le ventricule gauche.', 'Dans le sinus coronaire.'], ['La valve tricuspide.', 'La valve mitrale.', 'La valve aortique.'], ['L’atrium gauche.', 'Le ventricule droit.', 'L’atrium droit.'], ['Les cordages seuls sans muscles papillaires.', 'Les cuspides aortiques.', 'Le septum interventriculaire.'], ['La base est antérieure et apicale.', 'Base et apex sont voisins dans le médiastin.', 'La base se situe sous le diaphragme.']],
  'anat-coronary-vessels': [['De l’artère pulmonaire.', 'De la veine cave supérieure.', 'De l’artère thoracique interne.'], ['Le sillon atrioventriculaire droit.', 'Le sillon interventriculaire postérieur uniquement.', 'La veine cave supérieure.'], ['Par l’origine de la coronaire droite.', 'Par la taille du ventricule gauche.', 'Par l’origine de l’artère circonflexe seulement.'], ['La veine cave supérieure.', 'La grande veine saphène.', 'La veine pulmonaire droite.'], ['La coronaire gauche toujours.', 'L’artère circonflexe dans tous les cas.', 'La thoracique interne.']],
  'anat-cardiac-conduction-nodes': [['Dans le ventricule gauche près de l’apex.', 'Dans l’atrium gauche près des veines pulmonaires.', 'Dans le septum interventriculaire inférieur.'], ['Il accélère la contraction ventriculaire avant l’atriale.', 'Il ferme les valves sigmoïdes.', 'Il empêche l’activation électrique atriale.'], ['Le nerf vague.', 'Le sinus coronaire.', 'La veine cave inférieure.'], ['Dans la paroi atriale autour du sinus coronaire.', 'Dans le péricarde fibreux.', 'Dans les valves sigmoïdes.'], ['Non, seule la masse ventriculaire compte.', 'Non, seulement la pression artérielle.', 'Non, la conduction est indépendante du système autonome.']],
  'anat-tracheobronchial-tree': [['À la base du cœur.', 'Au hiatus aortique.', 'Au niveau de la carène du larynx.'], ['La bronche principale gauche.', 'Les deux sont toujours identiques.', 'La bronche lobaire supérieure gauche.'], ['Trois.', 'Un.', 'Quatre.'], ['Une bronchiole et une veine pulmonaire.', 'Un lobe et une veine cave.', 'Une bronche principale et une artère bronchique uniquement.'], ['Dans le centre du segment avec les bronches.', 'Dans la bronche principale.', 'Dans le médiastin hors du hile.']]
}
const rationale: Record<string, string[]> = {
  'anat-heart-chambers-valves': ['Elles ramènent le sang oxygéné vers l’atrium gauche.', 'Elle régule la sortie du ventricule droit vers la circulation pulmonaire.', 'Il éjecte contre la pression systémique et possède une paroi plus épaisse.', 'Cordages et muscles papillaires stabilisent les cuspides AV pendant la systole.', 'L’apex est antérieur et gauche, tandis que la base est plutôt postérieure.'],
  'anat-coronary-vessels': ['Les ostia s’ouvrent dans les sinus aortiques.', 'Elle chemine entre les deux ventricules en avant.', 'La dominance dépend de l’origine de cette branche postérieure.', 'Le sinus coronaire ramène le sang vers l’atrium droit.', 'Une branche de la droite est fréquente, mais l’origine varie.'],
  'anat-cardiac-conduction-nodes': ['Le pacemaker physiologique est proche de la jonction cave supérieure-atrium droit.', 'Le ralentissement autorise le remplissage ventriculaire après la systole atriale.', 'Le faisceau His relie électriquement atriums et ventricules à travers l’anneau fibreux.', 'Purkinje diffuse rapidement le signal sous l’endocarde ventriculaire.', 'Les influences sympathiques et parasympathiques modulent la fonction nodale.'],
  'anat-tracheobronchial-tree': ['La bifurcation trachéale se projette près de l’angle sternal.', 'La bronche droite est plus courte, large et verticale.', 'Le poumon gauche a deux lobes et deux bronches lobaires.', 'Chaque segment suit sa bronche segmentaire et sa branche artérielle pulmonaire.', 'Les veines sont plutôt intersegmentaires et aident à repérer les plans.']
}
export const thoraxVisceraQuestions: Question[] = thoraxVisceraCourses.flatMap(c => prompts[c.id].map((prompt, i) => {
  const options = [answers[c.id][i], ...wrong[c.id][i]]
  return { id: `${c.id}-q${i + 1}`, course: c.id, topic: 'Anatomie', prompt, options, correct: [0], why: options.map((_, j) => j === 0 ? rationale[c.id][i] : 'Cette relation ne correspond pas au trajet cardiovasculaire ou respiratoire décrit.'), difficulty: i < 2 ? 'essentiel' as const : 'application' as const, format: 'single' as const }
}))
