import type { Course } from '../../curriculum'
import type { Question } from '../../questions'
import { canonicalCourses } from '../../taxonomy/canonicalCourses'

const meta = new Map(canonicalCourses.filter(item => item.subject === 'Anatomie').map(item => [item.id, item]))
const spine = 'https://openstax.org/books/anatomy-and-physiology-2e/pages/7-3-the-vertebral-column'
const ribs = 'https://openstax.org/books/anatomy-and-physiology-2e/pages/7-4-the-thoracic-cage'
const muscle = 'https://openstax.org/books/anatomy-and-physiology-2e/pages/11-4-axial-muscles-of-the-abdominal-wall-and-thorax'
type D = { objectives: string[]; sections: Course['sections']; trap: string; recall: string; answer: string; source: string; glossary: NonNullable<Course['glossary']>; caseStudy: NonNullable<Course['caseStudy']> }
const s = (title: string, text: string) => ({ title, text })
const make = (id: string, d: D): Course => {
  const c = meta.get(id); if (!c) throw new Error(`Identifiant anatomique absent : ${id}`)
  return { id, title: c.title, category: c.subject, tag: c.module, minutes: 15, structure: null, objectives: d.objectives,
    sections: d.sections, trap: d.trap, recall: d.recall, answer: d.answer, source: d.source, sources: [{ label: 'OpenStax · Anatomy & Physiology 2e', url: d.source }],
    prerequisites: ['Ostéologie axiale et plans anatomiques', 'Anatomie des parois thoracique et abdominale'], glossary: d.glossary, caseStudy: d.caseStudy,
    review: { status: 'unreviewed', updatedAt: '2026-09-23', sourcesUpdatedAt: '2026-09-23' } }
}
export const trunkWallCourses: Course[] = [
  make('anat-intervertebral-disc-joints', {
    objectives: ['Décrire les parties du disque intervertébral', 'Distinguer symphyse et articulations zygapophysaires', 'Relier orientation facettaire et mobilité régionale'],
    sections: [
      s('Corps vertébraux et disques', 'Les disques fibrocartilagineux unissent les corps vertébraux de C2 à S1 et participent à la longueur, la souplesse et l’amortissement de la colonne. Ils sont plus épais en région lombaire, où les charges sont importantes. C1-C2 et sacrum-coccyx constituent des exceptions à la série discale typique.'),
      s('Anneau fibreux', 'L’annulus fibrosus est formé de lamelles concentriques de fibrocartilage, avec fibres de collagène orientées obliquement et alternant leur direction d’une lamelle à l’autre. Il résiste à la traction et aux torsions et contient le noyau. Sa région postérieure est plus mince, ce qui contribue à une moindre résistance locale.'),
      s('Noyau pulpeux', 'Le nucleus pulposus est un centre gélatineux riche en eau et protéoglycanes, vestige de la notochorde. Il se déforme sous charge et répartit la compression vers l’anneau et les plateaux vertébraux. Avec l’âge, sa teneur en eau diminue et les propriétés mécaniques du disque évoluent.'),
      s('Articulations zygapophysaires', 'Les facettes articulaires supérieures et inférieures de vertèbres adjacentes forment des articulations synoviales planes postérieures, appelées zygapophysaires ou interapophysaires postérieures. Leur orientation varie : cervicales favorisent mobilité multidirectionnelle, thoraciques limitent certaines flexions par côtes et facettes, lombaires favorisent flexion-extension et limitent la rotation axiale.'),
      s('Foramens et rapports', 'Les pédicules et incisures vertébrales forment les foramens intervertébraux par lesquels passent nerfs spinaux et vaisseaux radiculaires. Le disque est antérieur aux structures neurales et ses rapports varient selon le niveau. Une protrusion discale n’implique pas automatiquement une compression symptomatique ; la concordance clinique et l’imagerie sont nécessaires.'),
    ], trap: 'Les disques unissent les corps par symphyses fibrocartilagineuses ; les processus articulaires forment séparément des articulations synoviales.', recall: 'Quelles sont les deux parties principales du disque et leur fonction mécanique ?', answer: 'L’anneau fibreux résiste aux tractions et contient le noyau pulpeux, qui répartit et amortit les forces compressives.', source: spine, glossary: [['Annulus fibrosus', 'Anneau périphérique lamellaire de fibrocartilage.'], ['Nucleus pulposus', 'Centre hydraté et gélatineux du disque intervertébral.'], ['Articulation zygapophysaire', 'Articulation synoviale entre processus articulaires de vertèbres adjacentes.']], caseStudy: { prompt: 'Pourquoi une rotation axiale importante est-elle davantage limitée en région lombaire qu’en cervicale ?', answer: 'L’orientation des facettes lombaires favorise flexion-extension et limite la rotation, alors que les facettes cervicales permettent une mobilité plus multidirectionnelle.' }
  }),
  make('anat-intercostal-space-vessels', {
    objectives: ['Décrire les plans d’un espace intercostal', 'Suivre le paquet vasculonerveux principal', 'Repérer les rapports utiles aux gestes pleuraux'],
    sections: [
      s('Limites de l’espace', 'Chaque espace intercostal est compris entre deux côtes adjacentes et leurs cartilages. Les muscles intercostaux externe, interne et intime occupent des plans successifs et contribuent au soutien de la paroi et aux mouvements respiratoires. Les couches ne sont pas complètes de manière identique en avant et en arrière.'),
      s('Plans musculaires', 'Les intercostaux externes s’étendent des tubercules costaux vers la jonction costo-chondrale et leurs fibres sont orientées en bas et en avant. Les internes poursuivent plus antérieurement avec une orientation opposée. Les intimes forment un plan profond incomplet ; les vaisseaux et nerfs intercostaux cheminent entre intercostal interne et intime.'),
      s('Paquet vasculonerveux', 'Le paquet principal suit le sillon costal sur le bord inférieur de la côte supérieure, entre les plans interne et intime. De haut en bas, l’ordre classique est veine, artère, nerf. Les artères intercostales postérieures proviennent surtout de l’aorte thoracique, sauf les deux premiers espaces qui reçoivent des branches de l’artère intercostale suprême ; les artères antérieures proviennent des thoraciques internes et musculophréniques.'),
      s('Anastomoses et rameaux', 'Les branches antérieures et postérieures s’anastomosent dans chaque espace. Le nerf intercostal est le rameau antérieur du nerf spinal thoracique, distribuant fibres motrices, sensitives et sympathiques. Des rameaux collatéraux longent le bord supérieur de la côte inférieure et complètent les réseaux, d’où l’impossibilité d’une zone absolument dépourvue de risque.'),
      s('Repères topographiques', 'Le bord supérieur de la côte inférieure est parfois utilisé pour réduire le risque de blesser le paquet principal lors d’une ponction pleurale, mais la technique dépend du site, de l’imagerie et des protocoles. Les artères collatérales, variations et structures pleurales imposent une formation clinique appropriée ; la description anatomique ne suffit pas à réaliser un geste.'),
    ], trap: 'Le paquet principal est dans le sillon costal, mais des branches collatérales longent aussi la côte sous-jacente.', recall: 'Quel est l’ordre classique du paquet vasculonerveux intercostal dans le sillon costal ?', answer: 'De supérieur à inférieur : veine, artère, nerf (VAN).', source: ribs, glossary: [['Sillon costal', 'Gouttière sur le bord inférieur interne d’une côte contenant le paquet principal.'], ['Nerf intercostal', 'Rameau antérieur thoracique distribuant paroi, peau et fibres sympathiques.'], ['Artère intercostale suprême', 'Source artérielle habituelle des deux premiers espaces intercostaux postérieurs.']], caseStudy: { prompt: 'Pourquoi un geste passant juste au-dessus d’une côte n’est-il pas pour autant dépourvu de risque vasculaire ?', answer: 'Le paquet principal longe la côte supérieure, mais des rameaux collatéraux et des variations vasculaires peuvent exister près du bord supérieur de la côte sous-jacente.' }
  }),
  make('anat-diaphragm-muscle', {
    objectives: ['Décrire les origines sternale, costale et lombaire du diaphragme', 'Localiser ses principaux orifices et niveaux vertébraux', 'Relier contraction diaphragmatique et ventilation'],
    sections: [
      s('Une cloison musculo-tendineuse', 'Le diaphragme sépare thorax et abdomen. Ses fibres musculaires périphériques convergent vers un centre tendineux central. Il présente une coupole droite généralement plus haute que la gauche du fait notamment du foie. Les plèvres et péritoine le recouvrent respectivement en haut et en bas, avec zones d’attache périphériques.'),
      s('Parties sternale et costale', 'La partie sternale naît de la face postérieure du processus xiphoïde ; la partie costale des faces internes des six dernières côtes et cartilages, imbriquée avec le transverse de l’abdomen. Les insertions créent des zones de faiblesse relative comme les trigones sternocostaux, variables selon les individus.'),
      s('Partie lombaire et piliers', 'Les piliers droit et gauche s’attachent aux corps vertébraux lombaires et forment des arcs tendineux avec les ligaments arqués médian, médial et latéral. Les piliers contribuent au hiatus œsophagien et aux attaches. Le nerf phrénique, issu de C3-C5, assure l’innervation motrice principale et une sensibilité centrale.'),
      s('Orifices et niveaux', 'Le foramen cave dans le centre tendineux est généralement au niveau T8 et transmet veine cave inférieure et rameaux phréniques droits. Le hiatus œsophagien, entouré surtout par le pilier droit, est vers T10 et transmet œsophage, troncs vagaux et vaisseaux associés. Le hiatus aortique postérieur sous le ligament arqué médian est vers T12 et transmet aorte, conduit thoracique et système azygos.'),
      s('Mécanique ventilatoire', 'À l’inspiration, les fibres se contractent et le centre tendineux descend, augmentant le volume thoracique et abaissant la pression intrathoracique. Le contenu abdominal est déplacé vers le bas et l’avant, contribuant à la respiration abdominale. Le diaphragme intervient aussi dans la pression abdominale, la toux, la défécation et le retour veineux.'),
    ], trap: 'Les niveaux conventionnels sont T8 pour la veine cave, T10 pour l’œsophage et T12 pour l’aorte.', recall: 'Quels sont les trois grands orifices et leurs niveaux mnémotechniques ?', answer: 'Veine cave T8, œsophage T10, aorte T12.', source: muscle, glossary: [['Centre tendineux', 'Aponévrose centrale où convergent les fibres du diaphragme.'], ['Pilier diaphragmatique', 'Attache musculotendineuse lombaire participant aux hiatus.'], ['Nerf phrénique', 'Nerf principalement moteur du diaphragme, issu de C3-C5.']], caseStudy: { prompt: 'Une lésion unilatérale du nerf phrénique peut modifier le mouvement de quelle coupole à l’inspiration ?', answer: 'La coupole homolatérale peut perdre une partie de sa contraction et présenter un mouvement paradoxal selon la lésion.' }
  }),
  make('anat-inguinal-canal-hernias', {
    objectives: ['Décrire les parois et orifices du canal inguinal', 'Comparer les trajets des hernies directes et indirectes', 'Distinguer les contenus chez l’homme et la femme'],
    sections: [
      s('Trajet oblique', 'Le canal inguinal est un passage oblique de la paroi abdominale inférieure, au-dessus de la moitié médiale du ligament inguinal. Il s’étend de l’anneau profond, ouverture du fascia transversalis, à l’anneau superficiel, ouverture de l’aponévrose de l’oblique externe. Chez l’adulte, il transmet le cordon spermatique chez l’homme et le ligament rond chez la femme.'),
      s('Parois', 'La paroi antérieure est surtout l’aponévrose de l’oblique externe, renforcée latéralement par l’oblique interne. Le toit est formé par les fibres arquées des oblique interne et transverse. Le plancher est le ligament inguinal, renforcé médialement par le ligament lacunaire. La paroi postérieure est le fascia transversalis, renforcé médialement par le tendon conjoint selon les descriptions.'),
      s('Contenu et cordon spermatique', 'Le cordon contient conduit déférent, artères testiculaire, déférentielle et crémastérique, plexus pampiniforme, fibres autonomes, lymphatiques et rameau génital du génito-fémoral. Le nerf ilio-inguinal traverse une partie du canal mais entre par la paroi et ne passe pas par l’anneau profond. Chez la femme, le ligament rond suit le canal vers les grandes lèvres.'),
      s('Hernie indirecte', 'Une hernie indirecte entre par l’anneau profond, latéralement aux vaisseaux épigastriques inférieurs, suit le canal et peut atteindre le scrotum. Elle est souvent associée à la persistance du processus vaginal, sans que ce mécanisme explique chaque cas. Son trajet est oblique et suit les structures du canal.'),
      s('Hernie directe et repères', 'Une hernie directe pousse à travers une faiblesse de la paroi postérieure dans le triangle de Hesselbach, médialement aux vaisseaux épigastriques inférieurs. Les limites classiques sont bord latéral du droit, vaisseaux épigastriques et ligament inguinal. L’anatomie oriente la classification, mais toute masse inguinale nécessite une évaluation clinique.'),
    ], trap: 'Par rapport aux vaisseaux épigastriques inférieurs, une hernie indirecte est latérale et une hernie directe est médiale.', recall: 'Quel élément permet de distinguer topographiquement une hernie directe d’une indirecte ?', answer: 'Les vaisseaux épigastriques inférieurs : indirecte latérale, directe médiale.', source: 'https://openstax.org/books/anatomy-and-physiology-2e/pages/11-6-appendicular-muscles-of-the-pelvic-girdle-and-lower-limbs', glossary: [['Anneau inguinal profond', 'Ouverture du fascia transversalis située latéralement aux vaisseaux épigastriques inférieurs.'], ['Triangle de Hesselbach', 'Zone médiale de faiblesse de la paroi postérieure du canal inguinal.'], ['Tendon conjoint', 'Renfort médial lié à la fusion d’aponévroses de muscles abdominaux.']], caseStudy: { prompt: 'Une protrusion suit le canal depuis latéralement aux vaisseaux épigastriques inférieurs. Quel type de hernie cela évoque-t-il ?', answer: 'Une hernie inguinale indirecte, qui entre par l’anneau profond latéralement aux vaisseaux.' }
  })
]
const prompts: Record<string, string[]> = {
  'anat-intervertebral-disc-joints': ['Quelle partie centrale hydratée résiste à la compression ?', 'Quel type d’articulation unit les corps vertébraux via les disques ?', 'Quelles articulations synoviales relient les processus articulaires ?', 'Dans quelle région les facettes limitent particulièrement la rotation axiale ?', 'Par quelle ouverture sortent les nerfs spinaux ?'],
  'anat-intercostal-space-vessels': ['Quel est l’ordre du paquet principal de haut en bas ?', 'Entre quels plans musculaires chemine le paquet ?', 'D’où proviennent surtout les artères intercostales postérieures inférieures ?', 'Quel nerf forme le nerf intercostal ?', 'Les rameaux collatéraux suppriment-ils le risque au bord supérieur d’une côte ?'],
  'anat-diaphragm-muscle': ['Quel niveau correspond classiquement au hiatus cave ?', 'Quel niveau correspond au hiatus œsophagien ?', 'Quel niveau correspond au hiatus aortique ?', 'Quel nerf assure l’innervation motrice principale ?', 'Que fait le centre tendineux à l’inspiration ?'],
  'anat-inguinal-canal-hernias': ['Quel est le contenu principal du canal chez l’homme ?', 'Où se situe une hernie indirecte par rapport aux vaisseaux épigastriques ?', 'Où se situe une hernie directe par rapport aux vaisseaux épigastriques ?', 'Quel plan forme la paroi postérieure du canal ?', 'Le nerf ilio-inguinal entre-t-il par l’anneau profond ?']
}
const answers: Record<string, string[]> = {
  'anat-intervertebral-disc-joints': ['Le nucleus pulposus.', 'Une symphyse fibrocartilagineuse.', 'Les articulations zygapophysaires.', 'La région lombaire.', 'Le foramen intervertébral.'],
  'anat-intercostal-space-vessels': ['Veine, artère, nerf (VAN).', 'Entre l’intercostal interne et l’intercostal intime.', 'De l’aorte thoracique, sauf les premiers espaces.', 'Le rameau antérieur du nerf spinal thoracique.', 'Non, des rameaux collatéraux peuvent longent la côte inférieure.'],
  'anat-diaphragm-muscle': ['T8.', 'T10.', 'T12.', 'Le nerf phrénique C3-C5.', 'Il s’abaisse et augmente le volume thoracique.'],
  'anat-inguinal-canal-hernias': ['Le cordon spermatique.', 'Latéralement.', 'Médialement.', 'Le fascia transversalis, renforcé médialement.', 'Non, il traverse une partie du canal en y entrant par la paroi.']
}
const wrong: Record<string, string[][]> = {
  'anat-intervertebral-disc-joints': [['L’annulus fibrosus.', 'Le ligament longitudinal antérieur.', 'Le processus épineux.'], ['Une articulation trochoïde.', 'Une syndesmose.', 'Une articulation sphéroïde.'], ['Les symphyses pubiennes.', 'Les articulations costo-vertébrales.', 'Les sutures crâniennes.'], ['La région cervicale.', 'La région thoracique.', 'L’articulation atlanto-occipitale.'], ['Le canal sacré.', 'Le foramen obturé.', 'Le hiatus de l’adducteur.']],
  'anat-intercostal-space-vessels': [['Artère, veine, nerf.', 'Nerf, artère, veine.', 'Veine, nerf, artère.'], ['Entre l’externe et l’interne.', 'En dehors du fascia superficiel.', 'Entre plèvre et poumon.'], ['De l’artère thoracique interne uniquement.', 'De l’artère axillaire.', 'De l’artère pulmonaire.'], ['Le rameau postérieur.', 'Le nerf phrénique.', 'Le nerf vague.'], ['Oui, il n’existe aucune branche ailleurs.', 'Oui, le paquet principal est sous la côte inférieure.', 'Oui, les artères se trouvent uniquement dans le sillon.']],
  'anat-diaphragm-muscle': [['T6.', 'T10.', 'T12.'], ['T8.', 'T12.', 'L2.'], ['T8.', 'T10.', 'L1.'], ['Le nerf vague.', 'Le nerf intercostal T12 seul.', 'Le nerf subcostal uniquement.'], ['Il se soulève et réduit le volume thoracique.', 'Il reste fixe pendant la respiration.', 'Il ferme les trois orifices.']],
  'anat-inguinal-canal-hernias': [['Le nerf fémoral.', 'L’artère iliaque externe.', 'Le nerf obturateur.'], ['Médialement.', 'En arrière.', 'Dans le triangle de Hesselbach.'], ['Latéralement.', 'Au-dessus du fascia lata.', 'Dans l’anneau profond.'], ['L’aponévrose de l’oblique externe seule.', 'Le ligament inguinal.', 'Le péritoine viscéral.'], ['Oui, il accompagne le cordon depuis l’anneau profond.', 'Oui, il passe dans le cordon tout le long.', 'Oui, il ne traverse pas les parois du canal.']]
}
const rationale: Record<string, string[]> = {
  'anat-intervertebral-disc-joints': ['Sa matrice hydratée répartit les contraintes de compression.', 'Les disques constituent des symphyses cartilagineuses entre corps vertébraux.', 'Ces facettes postérieures forment des articulations synoviales planes.', 'L’orientation facettaire lombaire favorise flexion-extension et limite la rotation.', 'Les nerfs spinaux quittent le canal vertébral par ces foramens.'],
  'anat-intercostal-space-vessels': ['Le moyen mnémotechnique VAN décrit l’ordre du sillon costal.', 'Le paquet principal est interposé entre les plans interne et intime.', 'L’aorte fournit la majorité des branches postérieures thoraciques.', 'Le rameau antérieur thoracique devient le nerf intercostal.', 'Des branches collatérales peuvent être présentes près de la côte inférieure.'],
  'anat-diaphragm-muscle': ['Le foramen cave est classiquement dans le centre tendineux au niveau T8.', 'Le hiatus œsophagien se situe vers T10.', 'L’aorte passe postérieurement au niveau T12.', 'Le nerf phrénique fournit l’innervation motrice majeure.', 'La contraction abaisse le dôme et accroît le volume intrathoracique.'],
  'anat-inguinal-canal-hernias': ['Le cordon traverse le canal chez l’homme ; le ligament rond chez la femme.', 'L’indirecte entre par l’anneau profond, latéral aux vaisseaux épigastriques.', 'La directe traverse la paroi postérieure médialement aux vaisseaux.', 'Le fascia transversalis forme le plan postérieur, renforcé médialement.', 'Le nerf entre à travers la paroi, pas par l’anneau profond.']
}
export const trunkWallQuestions: Question[] = trunkWallCourses.flatMap(c => prompts[c.id].map((prompt, i) => {
  const options = [answers[c.id][i], ...wrong[c.id][i]]
  return { id: `${c.id}-q${i + 1}`, course: c.id, topic: 'Anatomie', prompt, options, correct: [0], why: options.map((_, j) => j === 0 ? rationale[c.id][i] : 'Cette structure ou relation correspond à un autre niveau ou plan anatomique.'), difficulty: i < 2 ? 'essentiel' as const : 'application' as const, format: 'single' as const }
}))
