import type { Course } from '../../curriculum'
import type { Question } from '../../questions'
import { canonicalCourses } from '../../taxonomy/canonicalCourses'

const meta = new Map(canonicalCourses.filter(item => item.subject === 'Anatomie').map(item => [item.id, item]))
const vessel = 'https://openstax.org/books/anatomy-and-physiology-2e/pages/20-5-circulatory-pathways'
const nerve = 'https://openstax.org/books/anatomy-and-physiology-2e/pages/13-4-the-peripheral-nervous-system'
type D = { objectives: string[]; sections: Course['sections']; trap: string; recall: string; answer: string; source: string; glossary: NonNullable<Course['glossary']>; caseStudy: NonNullable<Course['caseStudy']> }
const s = (title: string, text: string) => ({ title, text })
const make = (id: string, d: D): Course => {
  const c = meta.get(id); if (!c) throw new Error(`Identifiant anatomique absent : ${id}`)
  return { id, title: c.title, category: c.subject, tag: c.module, minutes: 14, structure: null, objectives: d.objectives,
    sections: d.sections, trap: d.trap, recall: d.recall, answer: d.answer, source: d.source,
    sources: [{ label: 'OpenStax · Anatomy & Physiology 2e', url: d.source }], prerequisites: ['Topographie du membre supérieur', 'Anatomie des loges brachiales et antébrachiales'],
    glossary: d.glossary, caseStudy: d.caseStudy, review: { status: 'unreviewed', updatedAt: '2026-09-23', sourcesUpdatedAt: '2026-09-23' } }
}
export const upperNeurovascularCourses: Course[] = [
  make('anat-axillary-brachial-arteries', {
    objectives: ['Suivre les limites et segments de l’artère axillaire', 'Relier branches et régions vascularisées', 'Décrire la continuité axillaire-brachiale et ses rapports'],
    sections: [
      s('De la subclavière à l’axillaire', 'L’artère subclavière devient artère axillaire au bord latéral de la première côte. L’axillaire traverse l’aisselle et est divisée en trois portions par le muscle petit pectoral : médiale, postérieure puis latérale au muscle. Cette segmentation fournit un repère de description, tandis que les branches et variations peuvent différer.'),
      s('Branches axillaires', 'La première portion donne habituellement l’artère thoracique supérieure. La deuxième donne thoraco-acromiale et thoracique latérale. La troisième donne subscapulaire, circonflexes humérales antérieure et postérieure. La subscapulaire se divise notamment en thoraco-dorsale et circonflexe de la scapula ; des anastomoses scapulaires relient les circulations de la région.'),
      s('Rapports dans l’aisselle', 'Le plexus brachial entoure l’artère axillaire par ses faisceaux latéral, médial et postérieur au niveau de sa deuxième portion. La veine axillaire est généralement médiale et reçoit les veines satellites et la veine céphalique. Les rapports varient le long du trajet ; la paroi antérieure comprend pectoraux et fascia clavipectoral, la postérieure subscapulaire puis grand rond et grand dorsal.'),
      s('Artère brachiale', 'Au bord inférieur du grand rond, l’axillaire devient brachiale. L’artère descend dans le bras, souvent avec le nerf médian qui passe de latéral à médial, et donne profonde du bras ainsi que collatérales ulnaire supérieure et inférieure. Elle atteint la fosse cubitale puis se divise généralement en artères radiale et ulnaire près du col du radius.'),
      s('Anastomoses et repères', 'Les branches collatérales brachiales s’anastomosent autour du coude avec des branches récurrentes radiales et ulnaires, maintenant des voies de circulation selon la position. Le pouls brachial se palpe médialement au tendon du biceps dans la fosse cubitale. Une plaie axillaire ou humérale exige une évaluation vasculaire car les axes sont proches de nerfs du plexus.'),
    ], trap: 'L’artère axillaire est divisée en trois portions par le petit pectoral, pas par le grand pectoral.', recall: 'Quel repère anatomique marque le passage de l’artère axillaire à l’artère brachiale ?', answer: 'Le bord inférieur du muscle grand rond.', source: vessel, glossary: [['Artère thoraco-acromiale', 'Branche axillaire courte qui se divise vers régions pectorale, deltoïdienne et acromiale.'], ['Artère profonde du bras', 'Branche brachiale accompagnant le nerf radial dans la région postérieure.'], ['Anastomose scapulaire', 'Réseau reliant des branches axillaires et subclavières autour de la scapula.']], caseStudy: { prompt: 'Une compression artérielle au bord inférieur du grand rond concerne quel segment de l’axe artériel ?', answer: 'L’artère brachiale, qui commence à ce niveau comme continuation de l’artère axillaire.' }
  }),
  make('anat-radial-ulnar-arteries', {
    objectives: ['Suivre le trajet des artères radiale et ulnaire', 'Décrire les arcades palmaires et leur contribution', 'Associer repères de surface et vascularisation de la main'],
    sections: [
      s('Bifurcation brachiale', 'Dans la fosse cubitale, l’artère brachiale se divise le plus souvent en radiale et ulnaire. La radiale gagne le côté latéral de l’avant-bras ; l’ulnaire descend médialement et donne l’artère interosseuse commune, qui se divise en branches antérieure et postérieure. Les variantes de hauteur de bifurcation ou de trajet sont possibles.'),
      s('Trajet radial et tabatière', 'L’artère radiale longe le bord latéral de l’avant-bras, passe près du processus styloïde puis contourne la région dorsale du carpe à travers la tabatière anatomique. Elle gagne la paume en passant entre les chefs du premier interosseux dorsal et contribue principalement à l’arcade palmaire profonde. La tabatière est bordée par tendons du pouce.'),
      s('Trajet ulnaire et canal de Guyon', 'L’artère ulnaire passe en avant du rétinaculum des fléchisseurs dans le canal de Guyon avec le nerf ulnaire, puis pénètre dans la paume. Elle contribue surtout à l’arcade palmaire superficielle et donne des branches communes palmaires digitales. Son trajet n’est pas celui du nerf médian dans le canal carpien.'),
      s('Arcades et anastomoses', 'Les arcades palmaires superficielle et profonde sont formées par des contributions ulnaire et radiale dont l’importance varie. Des artères métacarpiennes et digitales irriguent la main et les doigts. Les anastomoses offrent une redondance, mais leur perméabilité fonctionnelle doit être évaluée individuellement lors d’une procédure ou après traumatisme.'),
      s('Pouls et application', 'Le pouls radial se palpe à la face antérieure du poignet, latéralement au tendon du fléchisseur radial du carpe. L’artère ulnaire est plus médiale et plus profonde. Les repères guident l’examen mais la pression, le froid, les variations anatomiques et l’état circulatoire peuvent rendre un pouls difficile à percevoir.'),
    ], trap: 'Le canal carpien transmet le nerf médian et les tendons fléchisseurs ; le nerf et l’artère ulnaires passent dans le canal de Guyon.', recall: 'Quelle artère forme la majeure partie de l’arcade palmaire superficielle et quelle artère contribue surtout à l’arcade profonde ?', answer: 'L’ulnaire contribue principalement à l’arcade superficielle ; la radiale contribue principalement à l’arcade profonde, avec des anastomoses variables.', source: vessel, glossary: [['Tabatière anatomique', 'Dépression dorsolatérale du poignet bordée par les tendons du pouce.'], ['Arcade palmaire superficielle', 'Réseau artériel palmaire à contribution ulnaire généralement dominante.'], ['Artère interosseuse commune', 'Branche de l’ulnaire donnant les artères interosseuses antérieure et postérieure.']], caseStudy: { prompt: 'Un pouls radial est recherché au poignet. Quel tendon sert de repère latéral immédiat ?', answer: 'Le tendon du fléchisseur radial du carpe se situe juste en dedans du site habituel de palpation radiale.' }
  }),
  make('anat-upper-limb-veins-lymph', {
    objectives: ['Distinguer réseaux veineux superficiel et profond', 'Suivre les veines céphalique et basilique vers l’axillaire', 'Décrire le drainage lymphatique vers les nœuds axillaires'],
    sections: [
      s('Réseaux dorsaux et veines superficielles', 'Le réseau veineux dorsal de la main se prolonge par les veines céphalique latérale et basilique médiale. La veine céphalique remonte sur le côté radial de l’avant-bras et du bras, traverse le sillon delto-pectoral puis rejoint la veine axillaire. La basilique remonte médialement, perfore le fascia brachial et rejoint les veines profondes pour former l’axillaire.'),
      s('Veine médiane cubitale', 'La veine médiane cubitale relie fréquemment céphalique et basilique dans la fosse cubitale, en avant de l’aponévrose bicipitale. Elle est souvent utilisée pour la ponction veineuse, mais ses configurations sont variables et l’artère brachiale et le nerf médian sont profonds. Le repérage visuel seul ne garantit pas l’absence de variation.'),
      s('Réseau veineux profond', 'Les veines radiales et ulnaires accompagnent leurs artères sous forme de veines satellites. Elles se réunissent en veines brachiales, qui reçoivent notamment les veines profondes du bras, puis participent à la formation de la veine axillaire au bord inférieur du grand rond. L’axillaire devient subclavière au bord latéral de la première côte.'),
      s('Drainage lymphatique', 'Les lymphatiques superficiels suivent souvent les veines superficielles et convergent vers les nœuds axillaires. Les nœuds pectoraux reçoivent une part de la paroi thoracique antérieure et du sein ; les huméraux reçoivent une grande partie du membre supérieur. Les chaînes centrale puis apicale relaient le drainage vers les troncs subclaviers.'),
      s('Groupes axillaires et clinique', 'Les nœuds axillaires comprennent groupes pectoral, subscapulaire, huméral, central et apical, disposés selon les parois et le sommet de l’aisselle. Des voies collatérales rejoignent parfois les nœuds supraclaviculaires ou parasternal. L’examen lymphatique décrit taille, mobilité et sensibilité, mais ne détermine pas à lui seul l’étiologie d’une adénopathie.'),
    ], trap: 'La veine céphalique rejoint directement la veine axillaire dans le sillon delto-pectoral ; la basilique rejoint le réseau profond plus distalement.', recall: 'Comment les veines basilique et céphalique rejoignent-elles le réseau axillaire ?', answer: 'La céphalique se jette dans l’axillaire près du sillon delto-pectoral ; la basilique traverse le fascia et s’unit aux veines brachiales pour former l’axillaire.', source: vessel, glossary: [['Veine céphalique', 'Veine superficielle latérale du membre supérieur se terminant dans l’axillaire.'], ['Veine basilique', 'Veine superficielle médiale rejoignant le réseau profond dans le bras.'], ['Nœud axillaire apical', 'Groupe supérieur recevant les efférents des autres groupes axillaires.']], caseStudy: { prompt: 'Une infection du bord latéral de la main peut drainer d’abord vers quelle voie veineuse/lymphatique superficielle ?', answer: 'Les lymphatiques superficiels peuvent suivre la veine céphalique vers des nœuds axillaires apicaux ou delto-pectoraux, avec des variations de drainage.' }
  }),
  make('anat-upper-limb-nerves-trunks', {
    objectives: ['Comparer les trajets des cinq nerfs terminaux du plexus', 'Associer territoires moteurs et sensitifs majeurs', 'Interpréter les signes topographiques d’une neuropathie périphérique'],
    sections: [
      s('Nerf musculocutané', 'Le nerf musculocutané traverse le coracobrachial, descend entre biceps et brachial, puis devient nerf cutané latéral de l’avant-bras. Il innerve principalement les fléchisseurs antérieurs du bras et contribue à la flexion du coude et à la supination via le biceps. Une atteinte affaiblit ces actions et diminue la sensibilité latérale de l’avant-bras.'),
      s('Nerf axillaire', 'Le nerf axillaire quitte l’aisselle par l’espace quadrilatère avec l’artère circonflexe humérale postérieure, contourne le col chirurgical et innerve deltoïde et petit rond. Il donne le nerf cutané latéral supérieur du bras. Son atteinte peut diminuer l’abduction après les premiers degrés et la sensibilité de la région deltoïdienne.'),
      s('Nerf radial', 'Le radial chemine avec la profonde du bras dans le sillon radial de l’humérus puis traverse le septum latéral. Au coude, il se divise en branche superficielle sensitive et branche profonde motrice, poursuivie comme nerf interosseux postérieur. Il innerve les extenseurs du bras et de l’avant-bras ; une lésion haute peut produire un déficit d’extension du poignet et des doigts.'),
      s('Nerf médian', 'Le médian accompagne l’artère brachiale, traverse la fosse cubitale sans innerver les muscles du bras, puis gagne l’avant-bras entre les chefs du rond pronateur. Il innerve la plupart des fléchisseurs-pronateurs, sauf exceptions ulnaires, puis traverse le canal carpien et innerve plusieurs muscles thénariens et lombricaux latéraux. La peau latérale palmaire et les doigts radiaux relèvent de son territoire.'),
      s('Nerf ulnaire et synthèse clinique', 'Le nerf ulnaire passe derrière l’épicondyle médial, descend dans l’avant-bras et rejoint la main par le canal de Guyon. Il innerve le fléchisseur ulnaire du carpe, une partie du fléchisseur profond et la majorité des muscles intrinsèques de la main. Une lésion peut gêner abduction-adduction des doigts et sensibilité médiale ; localisation et sévérité influencent le tableau.'),
    ], trap: 'Le nerf médian traverse le canal carpien ; le nerf ulnaire traverse le canal de Guyon et passe en arrière de l’épicondyle médial.', recall: 'Quel nerf contourne le col chirurgical et innerve principalement le deltoïde ?', answer: 'Le nerf axillaire.', source: nerve, glossary: [['Nerf interosseux postérieur', 'Continuation motrice de la branche profonde du nerf radial dans l’avant-bras.'], ['Nerf cutané latéral de l’avant-bras', 'Continuation sensitive du nerf musculocutané.'], ['Canal de Guyon', 'Passage ulnaire du poignet contenant nerf et artère ulnaires.']], caseStudy: { prompt: 'Après fracture humérale, une personne ne peut plus étendre le poignet et les doigts. Quel nerf et quel trajet osseux expliquent ce tableau ?', answer: 'Le nerf radial, qui chemine dans le sillon radial de l’humérus et innerve les extenseurs.' }
  })
]
const prompts: Record<string, string[]> = {
  'anat-axillary-brachial-arteries': ['Quel muscle divise l’artère axillaire en trois portions ?', 'Au bord de quel muscle l’artère axillaire devient-elle brachiale ?', 'Quelle branche axillaire passe avec le nerf radial dans la région postérieure du bras ?', 'Quel est le devenir distal habituel de l’artère brachiale ?', 'Quelle structure entoure l’artère axillaire par des faisceaux latéral, médial et postérieur ?'],
  'anat-radial-ulnar-arteries': ['Quelle artère contribue principalement à l’arcade palmaire superficielle ?', 'Quelle artère contourne le carpe par la tabatière anatomique ?', 'Quel paquet passe dans le canal de Guyon ?', 'Où palpe-t-on habituellement le pouls radial ?', 'Quelle artère donne l’artère interosseuse commune ?'],
  'anat-upper-limb-veins-lymph': ['Quelle veine superficielle chemine latéralement et rejoint l’axillaire dans le sillon delto-pectoral ?', 'Quelle veine traverse le fascia brachial pour rejoindre le réseau profond ?', 'Quelle veine superficielle relie souvent céphalique et basilique dans la fosse cubitale ?', 'Quel groupe axillaire reçoit une grande partie du drainage du membre supérieur ?', 'Quelle chaîne de nœuds reçoit les efférents axillaires avant le tronc subclavier ?'],
  'anat-upper-limb-nerves-trunks': ['Quel nerf traverse le coracobrachial et devient cutané latéral de l’avant-bras ?', 'Quel nerf passe derrière l’épicondyle médial ?', 'Quel nerf innerve la plupart des extenseurs de l’avant-bras ?', 'Quel nerf accompagne les tendons fléchisseurs dans le tunnel carpien ?', 'Quel nerf innerve deltoïde et petit rond ?']
}
const answers: Record<string, string[]> = {
  'anat-axillary-brachial-arteries': ['Le petit pectoral.', 'Le bord inférieur du grand rond.', 'L’artère profonde du bras.', 'Elle se divise généralement en radiale et ulnaire dans la fosse cubitale.', 'Les faisceaux du plexus brachial.'],
  'anat-radial-ulnar-arteries': ['L’artère ulnaire.', 'L’artère radiale.', 'Le nerf ulnaire et l’artère ulnaire.', 'À la face antérieure latérale du poignet, près du tendon du fléchisseur radial du carpe.', 'L’artère ulnaire.'],
  'anat-upper-limb-veins-lymph': ['La veine céphalique.', 'La veine basilique.', 'La veine médiane cubitale.', 'Les nœuds huméraux (latéraux).', 'La chaîne apicale.'],
  'anat-upper-limb-nerves-trunks': ['Le nerf musculocutané.', 'Le nerf ulnaire.', 'Le nerf radial.', 'Le nerf médian.', 'Le nerf axillaire.']
}
const wrong: Record<string, string[][]> = {
  'anat-axillary-brachial-arteries': [['Le grand rond.', 'Le deltoïde.', 'Le coracobrachial.'], ['Le bord inférieur du petit pectoral.', 'Le bord supérieur du grand rond.', 'Le bord latéral de la clavicule.'], ['L’artère thoracique latérale.', 'L’artère thoraco-acromiale.', 'L’artère circonflexe humérale antérieure.'], ['Elle se termine dans l’artère subclavière.', 'Elle devient directement artère axillaire.', 'Elle se termine en artères tibiales.'], ['Le nerf musculocutané seul.', 'Les racines C5-T1 seulement.', 'Les veines brachiales.']],
  'anat-radial-ulnar-arteries': [['L’artère radiale.', 'L’artère brachiale.', 'L’artère interosseuse postérieure.'], ['L’artère ulnaire.', 'L’artère brachiale.', 'L’artère interosseuse commune.'], ['Le nerf médian et l’artère radiale.', 'Le nerf radial et l’artère brachiale.', 'Les tendons extenseurs seuls.'], ['Médialement au tendon du fléchisseur ulnaire du carpe.', 'Dans la paume sous le rétinaculum.', 'En arrière de la malléole médiale.'], ['L’artère radiale.', 'L’artère brachiale profonde.', 'L’artère thoraco-acromiale.']],
  'anat-upper-limb-veins-lymph': [['La veine basilique.', 'La veine médiane cubitale.', 'La veine brachiale.'], ['La veine céphalique.', 'La veine médiane cubitale.', 'La veine radiale.'], ['La veine brachiale.', 'La veine axillaire.', 'La veine subclavière.'], ['Les nœuds pectoraux uniquement.', 'Les nœuds poplités.', 'Les nœuds para-aortiques.'], ['La chaîne humérale.', 'La chaîne inguinale.', 'La chaîne poplitée.']],
  'anat-upper-limb-nerves-trunks': [['Le nerf radial.', 'Le nerf médian.', 'Le nerf axillaire.'], ['Le nerf médian.', 'Le nerf radial.', 'Le nerf musculocutané.'], ['Le nerf médian.', 'Le nerf ulnaire.', 'Le nerf axillaire.'], ['Le nerf ulnaire.', 'Le nerf radial superficiel.', 'Le nerf musculocutané.'], ['Le nerf supra-scapulaire.', 'Le nerf radial.', 'Le nerf médian.']]
}
const why: Record<string, string[]> = {
  'anat-axillary-brachial-arteries': ['Les trois portions sont définies selon les rapports de l’axillaire avec le petit pectoral.', 'La transition se situe au bord inférieur du grand rond.', 'La profonde du bras accompagne le radial dans le sillon radial.', 'C’est la bifurcation habituelle de l’artère brachiale distale.', 'Les faisceaux sont disposés autour de l’artère dans la région axillaire.'],
  'anat-radial-ulnar-arteries': ['La contribution ulnaire domine généralement l’arcade superficielle.', 'La radiale contourne le carpe et la tabatière avant d’atteindre la paume.', 'Ces éléments traversent le canal ulnaire, distinct du canal carpien.', 'Le repère de surface est latéral au tendon du fléchisseur radial du carpe.', 'L’ulnaire donne l’interosseuse commune qui se divise en deux branches.'],
  'anat-upper-limb-veins-lymph': ['La céphalique suit le versant latéral et rejoint l’axillaire près du delto-pectoral.', 'La basilique perfore le fascia et rejoint les veines profondes.', 'Elle relie souvent les deux réseaux superficiels en avant du coude.', 'Les nœuds huméraux reçoivent une grande partie du membre supérieur.', 'Les efférents rejoignent les nœuds apicaux puis les troncs subclaviers.'],
  'anat-upper-limb-nerves-trunks': ['Le musculocutané traverse le coracobrachial puis devient cutané latéral de l’avant-bras.', 'L’ulnaire passe derrière l’épicondyle médial.', 'Le radial dessert les extenseurs dans les loges postérieures.', 'Le médian traverse le canal carpien avec les tendons fléchisseurs.', 'L’axillaire contourne le col chirurgical et innerve ces muscles.']
}
export const upperNeurovascularQuestions: Question[] = upperNeurovascularCourses.flatMap(c => prompts[c.id].map((prompt, i) => {
  const options = [answers[c.id][i], ...wrong[c.id][i]]
  return { id: `${c.id}-q${i + 1}`, course: c.id, topic: 'Anatomie', prompt, options, correct: [0], why: options.map((_, j) => j === 0 ? why[c.id][i] : 'Cette structure a un autre trajet ou rapport dans la topographie du membre supérieur.'), difficulty: i < 2 ? 'essentiel' as const : 'application' as const, format: 'single' as const }
}))
