import type { Course } from '../../curriculum'
import type { Question } from '../../questions'
import { canonicalCourses } from '../../taxonomy/canonicalCourses'

const metadata = new Map(canonicalCourses.filter(item => item.subject === 'Physiologie').map(item => [item.id, item]))
const base = 'https://openstax.org/books/anatomy-and-physiology-2e/pages/'
type Draft = { objectives: string[]; sections: Course['sections']; trap: string; recall: string; answer: string; source: string; learning?: Course['learning']; caseStudy: NonNullable<Course['caseStudy']>; glossary: NonNullable<Course['glossary']> }
const s = (title: string, text: string, bullets?: string[]) => ({ title, text, ...(bullets ? { bullets } : {}) })
function course(id: string, d: Draft): Course {
  const c = metadata.get(id)
  if (!c) throw new Error(`Chapitre canonique de physiologie introuvable : ${id}`)
  return { id, title: c.title, category: c.subject, tag: c.module, minutes: 15, structure: null,
    objectives: d.objectives, sections: d.sections, trap: d.trap, recall: d.recall, answer: d.answer,
    source: base + d.source, sources: [{ label: 'OpenStax · Anatomy & Physiology 2e', url: base + d.source }],
    prerequisites: ['Anatomie fonctionnelle des organes concernés', 'Homéostasie et gradients physiologiques'],
    ...(d.learning ? { learning: d.learning } : {}), glossary: d.glossary, caseStudy: d.caseStudy,
    review: { status: 'unreviewed', updatedAt: '2026-09-23', sourcesUpdatedAt: '2026-09-23' } }
}
export const physiologyCourses: Course[] = [
  course('homeostasis', {
    objectives: ['Décomposer une boucle de régulation', 'Distinguer rétrocontrôle négatif et positif', 'Analyser une réponse homéostatique simple'],
    sections: [
      s('Stabilité dynamique', 'L’homéostasie maintient des variables internes dans des plages compatibles avec la fonction cellulaire malgré les variations externes. Elle n’implique pas une valeur fixe : température, glycémie, osmolarité et pression artérielle fluctuent et sont régulées. Un état stable peut nécessiter des échanges permanents de matière et d’énergie.'),
      s('Capteur, intégrateur, effecteur', 'Un capteur détecte la variation d’une variable ou d’un signal associé. Un centre intégrateur compare l’information à une référence et organise une réponse ; un effecteur modifie la variable. Les composants peuvent être répartis dans plusieurs organes et communiquer par voies nerveuses, endocrines ou locales.'),
      s('Rétrocontrôle négatif', 'Le rétrocontrôle négatif produit une réponse qui s’oppose à la perturbation initiale et ramène la variable vers sa plage cible. La thermorégulation illustre plusieurs effecteurs : vasomotricité cutanée, sudation ou frisson. Une réponse peut corriger l’écart sans le supprimer instantanément ; délai, intensité et perturbations persistantes modulent le résultat.'),
      s('Rétrocontrôle positif', 'Le rétrocontrôle positif amplifie temporairement le processus qui l’a déclenché. La libération d’ocytocine pendant le travail peut renforcer les contractions et stimuler davantage le signal, jusqu’à un événement d’arrêt comme la naissance. Il ne constitue pas un mécanisme général de stabilisation et requiert souvent une limite physiologique.'),
      s('Anticipation et intégration', 'Certaines réponses anticipent une perturbation prévisible, comme les ajustements digestifs associés aux repas. Des systèmes de régulation interagissent : une même variable peut recevoir plusieurs entrées, et un effecteur influencer plusieurs paramètres. La régulation repose donc sur des réseaux, des gains, des délais et des compromis physiologiques.'),
    ], trap: '« Négatif » décrit le sens de la réponse par rapport à l’écart initial ; cela ne signifie ni dangereux ni mauvais.', recall: 'Dans une baisse de glycémie, comment identifier capteur, intégrateur et effecteur dans une boucle ?', answer: 'Le pancréas détecte la baisse et adapte les sécrétions hormonales ; les tissus effecteurs modifient production, stockage ou utilisation du glucose afin de corriger l’écart.', source: '1-5-homeostasis', learning: { formula: { label: 'Organisation d’une boucle', expression: 'perturbation → capteur → intégrateur → effecteur → réponse', explanation: 'Le rétrocontrôle relie la réponse à la variable, en renforçant ou en réduisant l’écart initial.' }, comparison: { headers: ['Type', 'Effet sur l’écart initial', 'Exemple'], rows: [['Négatif', 'Le réduit', 'Thermorégulation'], ['Positif', 'L’amplifie temporairement', 'Contractions du travail'], ['Anticipatoire', 'Agit avant la perturbation complète', 'Réponse digestive préparatoire']] }, example: { prompt: 'La température corporelle augmente.', steps: ['Des capteurs thermiques détectent l’écart.', 'L’intégration hypothalamique active des effecteurs de dissipation.', 'L’évaporation et les échanges cutanés favorisent la baisse.'], result: 'La réponse s’oppose à la hausse initiale : rétrocontrôle négatif.' }, errors: [{ title: 'Confondre variable et réponse', detail: 'Nommer ce qui est régulé, l’écart observé et l’action de l’effecteur pour décrire correctement la boucle.' }] }, glossary: [['Variable régulée', 'Paramètre physiologique maintenu dans une plage par des mécanismes de contrôle.'], ['Consigne', 'Référence ou plage vers laquelle tend un système de régulation.'], ['Effecteur', 'Organe, cellule ou tissu exécutant la réponse.']], caseStudy: { prompt: 'Le frisson apparaît lorsque la température interne diminue. Quel est le sens de la réponse ?', answer: 'Les contractions musculaires augmentent la production de chaleur et s’opposent à la baisse de température : c’est un rétrocontrôle négatif.' }
  }),
  course('phys-gas-exchange', {
    objectives: ['Distinguer ventilation, perfusion et diffusion', 'Expliquer le rapport ventilation/perfusion', 'Interpréter les transports d’O₂ et de CO₂'],
    sections: [
      s('Ventilation et surface alvéolaire', 'La ventilation renouvelle l’air des alvéoles par mouvements respiratoires. Les bronchioles terminales conduisent l’air vers les unités d’échange, dont les alvéoles offrent une grande surface et une barrière air-sang mince. L’anatomie et les propriétés du surfactant influencent stabilité et efficacité des échanges.'),
      s('Perfusion pulmonaire', 'La perfusion correspond au débit sanguin dans les capillaires pulmonaires. Le sang veineux mêlé rejoint le réseau alvéolaire, où il reçoit l’oxygène et libère du dioxyde de carbone. La gravité et la pression vasculaire produisent des différences régionales de débit, notamment entre sommets et bases en position debout.'),
      s('Diffusion selon les gradients', 'Les gaz diffusent selon leurs gradients de pression partielle. La vitesse augmente avec la surface et la solubilité, et diminue quand la barrière s’épaissit ou que la distance augmente. Une limitation de diffusion peut survenir lors d’épaississement interstitiel, perte de surface ou temps capillaire très court, surtout à l’effort.'),
      s('Rapport ventilation/perfusion', 'Le rapport V/Q compare ventilation alvéolaire et perfusion d’une région. Une unité ventilée mais peu perfusée se comporte comme un espace mort ; une unité perfusée mais peu ventilée crée un effet de shunt. Les réponses locales, dont vasoconstriction pulmonaire hypoxique, tendent à rediriger le sang vers des alvéoles mieux ventilées.'),
      s('Transport dans le sang', 'La majeure partie de l’oxygène est liée à l’hémoglobine ; une faible fraction est dissoute et détermine la pression partielle. Le CO₂ circule dissous, lié à des protéines ou sous forme de bicarbonate après conversion dans les érythrocytes. L’effet Bohr facilite la libération d’O₂ dans des tissus riches en CO₂ et H⁺.'),
    ], trap: 'Un shunt et un espace mort traduisent tous deux un déséquilibre V/Q, mais dans des sens opposés entre ventilation et perfusion.', recall: 'Comment le poumon répond-il localement à une alvéole hypoventilée ?', answer: 'L’hypoxie alvéolaire peut provoquer une vasoconstriction des artérioles pulmonaires locales, redistribuant la perfusion vers des régions mieux ventilées.', source: '22-4-gas-exchange', learning: { formula: { label: 'Rapport ventilation/perfusion', expression: 'V/Q = ventilation alvéolaire / perfusion', explanation: 'Le rapport global moyen est proche de 0,8 chez un adulte au repos, mais varie selon les régions pulmonaires.' }, comparison: { headers: ['Situation', 'Ventilation', 'Perfusion'], rows: [['Équilibrée', 'Présente', 'Présente'], ['Espace mort', 'Présente relativement', 'Faible ou absente'], ['Shunt', 'Faible ou absente', 'Présente'], ['Hypoventilation', 'Insuffisante', 'Peut persister']] }, example: { prompt: 'Une embolie bouche une branche artérielle pulmonaire.', steps: ['L’alvéole correspondante peut rester ventilée.', 'Sa perfusion diminue fortement.', 'Le rapport V/Q local augmente.'], result: 'La région se comporte comme un espace mort relatif.' }, errors: [{ title: 'Confondre saturation et pression partielle', detail: 'La saturation de l’hémoglobine dépend de sa liaison à l’O₂ ; la pression partielle reflète surtout le gaz dissous.' }] }, glossary: [['Pression partielle', 'Contribution d’un gaz à la pression totale d’un mélange.'], ['Shunt', 'Perfusion d’unités pulmonaires insuffisamment ventilées.'], ['Espace mort', 'Ventilation d’unités peu ou pas perfusées.']], caseStudy: { prompt: 'Une obstruction bronchique régionale réduit la ventilation tandis que la perfusion se maintient. Quel déséquilibre V/Q apparaît ?', answer: 'Un rapport V/Q bas, pouvant tendre vers un effet shunt, car le sang traverse une région insuffisamment ventilée.' }
  }),
  course('phys-digestion', {
    objectives: ['Décrire les phases de digestion et d’absorption', 'Relier sécrétions gastriques et pancréatiques à leurs fonctions', 'Expliquer les rôles de la bile et des hormones digestives'],
    sections: [
      s('Motricité digestive', 'Le tube digestif assure propulsion, stockage transitoire et mélange. Le péristaltisme déplace le contenu, tandis que des contractions segmentaires le mélangent au chyme. Le système nerveux entérique coordonne des circuits locaux, modulés par le système autonome, les hormones et les propriétés du contenu.'),
      s('Estomac : sécrétion et vidange', 'Les cellules pariétales sécrètent HCl et facteur intrinsèque ; les cellules principales libèrent pepsinogène, activé en pepsine dans un milieu acide. Le mucus et le bicarbonate protègent la muqueuse. L’acidité dénature des protéines et active des enzymes, tandis que la vidange gastrique dépend de la composition et du volume du repas et du rétrocontrôle duodénal.'),
      s('Bile et pancréas exocrine', 'Le foie produit la bile, stockée et concentrée dans la vésicule entre les repas. Les sels biliaires émulsifient les lipides et facilitent la formation de micelles, sans être eux-mêmes des enzymes. Le pancréas déverse bicarbonate et enzymes digestives dans le duodénum ; le bicarbonate neutralise l’acidité gastrique et crée un pH favorable aux enzymes intestinales.'),
      s('Absorption intestinale', 'L’intestin grêle possède plis, villosités et microvillosités qui accroissent sa surface. Les glucides et protéines sont absorbés surtout sous forme de monosaccharides et d’acides aminés ou petits peptides. Les lipides entrent dans les entérocytes, y sont réassemblés et exportés en chylomicrons par les vaisseaux lymphatiques, alors que les nutriments hydrosolubles rejoignent le sang portal.'),
      s('Coordination hormonale', 'La gastrine stimule certaines fonctions gastriques ; la sécrétine répond notamment à l’acidité duodénale et favorise la sécrétion de bicarbonate ; la cholécystokinine favorise libération d’enzymes pancréatiques et contraction vésiculaire. Ces signaux s’intègrent avec des réflexes nerveux et varient selon les phases céphalique, gastrique et intestinale.'),
    ], trap: 'La bile facilite la digestion lipidique par émulsification et micelles, mais ne contient pas d’enzyme qui hydrolyse directement les triglycérides.', recall: 'Quelle différence fonctionnelle entre sécrétine et cholécystokinine ?', answer: 'La sécrétine stimule surtout une sécrétion pancréatique riche en bicarbonate en réponse à l’acidité ; la cholécystokinine stimule notamment enzymes pancréatiques et contraction de la vésicule biliaire.', source: '23-6-chemical-digestion-and-absorption-a-closer-look', glossary: [['Chyme', 'Contenu semi-liquide issu du mélange gastrique des aliments et sécrétions.'], ['Micelle', 'Agrégat de sels biliaires facilitant le transport luminal des produits lipidiques.'], ['Chylomicron', 'Particule riche en lipides formée par l’entérocyte et exportée dans la lymphe.']], caseStudy: { prompt: 'Après un repas riche en graisses, quel rôle joue la cholécystokinine sur la vésicule et le pancréas ?', answer: 'Elle favorise la contraction de la vésicule biliaire et la sécrétion d’enzymes pancréatiques pour soutenir la digestion des lipides.' }
  }),
  course('phys-sensory-motor', {
    objectives: ['Décomposer une voie sensorielle et une voie motrice', 'Décrire l’arc réflexe médullaire', 'Relier voies descendantes et contrôle volontaire'],
    sections: [
      s('Récepteurs et transduction', 'Les récepteurs sensoriels convertissent une énergie physique ou chimique en signal électrique. Leur modalité dépend de leur sensibilité, et leur activité peut s’adapter lors d’une stimulation prolongée. Un potentiel récepteur gradué peut déclencher des potentiels d’action dans une fibre afférente lorsque le seuil est atteint.'),
      s('Voies sensitives ascendantes', 'Les informations somatiques sont transmises par neurones afférents dont les corps cellulaires se trouvent souvent dans les ganglions spinaux. Les voies des colonnes dorsales transportent notamment tact fin, vibration et proprioception consciente avec un croisement bulbaire ; le système antérolatéral véhicule douleur et température avec des relais et croisements médullaires précoces.'),
      s('Intégration médullaire et réflexe', 'Un arc réflexe associe récepteur, voie afférente, centre intégrateur, voie efférente et effecteur. Un réflexe monosynaptique comme le réflexe myotatique met en jeu une synapse entre afférence Ia et motoneurone alpha ; des interneurones participent à la coordination et à l’inhibition réciproque. Les réflexes restent modulés par les voies descendantes.'),
      s('Voie corticospinale', 'Les neurones moteurs corticaux contribuent au contrôle des mouvements volontaires, particulièrement fins. Les axones descendent depuis le cortex, traversent la capsule interne et le tronc cérébral ; une majorité décusse dans la partie caudale du bulbe pour former le faisceau corticospinal latéral. Les motoneurones inférieurs constituent la voie finale commune vers le muscle.'),
      s('Unités motrices et commande', 'Une unité motrice comprend un motoneurone alpha et les fibres musculaires qu’il innerve. Le recrutement progressif et la fréquence de décharge règlent force et précision. Les mouvements coordonnés impliquent aussi cervelet, noyaux gris centraux, afférences sensorielles et circuits du tronc cérébral ; une lésion peut produire des signes différents selon son niveau.'),
    ], trap: 'Une lésion d’un motoneurone supérieur et une lésion d’un motoneurone inférieur ont des signes distincts ; il faut localiser avant de conclure.', recall: 'Quels éléments constituent un arc réflexe spinal ?', answer: 'Récepteur, neurone afférent, centre d’intégration médullaire, neurone efférent et effecteur.', source: '13-1-the-function-of-the-nervous-system', glossary: [['Afférent', 'Qui conduit une information vers le système nerveux central.'], ['Efférent', 'Qui conduit une commande du système nerveux central vers un effecteur.'], ['Unité motrice', 'Motoneurone alpha et ensemble des fibres musculaires qu’il innerve.']], caseStudy: { prompt: 'Une percussion du tendon patellaire étire brièvement le quadriceps. Quel type de réflexe est provoqué ?', answer: 'Le réflexe myotatique : l’afférence proprioceptive active les motoneurones du muscle étiré via un circuit médullaire bref, avec inhibition réciproque des antagonistes.' }
  }),
]
const prompts: Record<string, string[]> = {
  homeostasis: ['Une boucle homéostatique comprend généralement quels trois éléments fonctionnels ?', 'Quel est l’effet d’un rétrocontrôle négatif sur l’écart initial ?', 'Le terme « négatif » signifie-t-il nocif ?', 'Quel événement peut arrêter la boucle positive du travail ?', 'Pourquoi une variable homéostatique peut-elle fluctuer ?'],
  'phys-gas-exchange': ['Que compare le rapport V/Q ?', 'Quel déséquilibre survient si une région est ventilée mais peu perfusée ?', 'Quel gaz est l’accepteur terminal en respiration cellulaire mais pas directement requis par la diffusion pulmonaire ?', 'Sous quelle forme circule la majorité de l’oxygène sanguin ?', 'Comment réagit localement une artériole pulmonaire à l’hypoxie alvéolaire ?'],
  'phys-digestion': ['Quel est le rôle principal des sels biliaires dans la digestion ?', 'Quelle hormone favorise la sécrétion pancréatique de bicarbonate ?', 'Quel organe produit la bile ?', 'Par quel système les chylomicrons quittent-ils l’intestin ?', 'Quel facteur intrinsèque sécrété par l’estomac est nécessaire à l’absorption de la vitamine B12 ?'],
  'phys-sensory-motor': ['Que transforme un récepteur sensoriel ?', 'Quels éléments composent un arc réflexe ?', 'Où croise la majorité des fibres corticospinales latérales ?', 'Quel est le rôle d’un motoneurone alpha ?', 'Quels types d’information véhiculent surtout les colonnes dorsales ?'],
}
const answers: Record<string, string[]> = {
  homeostasis: ['Capteur, centre intégrateur et effecteur.', 'Il tend à le réduire et ramener la variable vers sa plage cible.', 'Non, il décrit une réponse qui s’oppose à la perturbation.', 'La naissance interrompt le stimulus mécanique qui entretenait la boucle.', 'L’homéostasie maintient une plage dynamique malgré les perturbations, elle ne fige pas la valeur.'],
  'phys-gas-exchange': ['La ventilation alvéolaire et la perfusion capillaire d’une région.', 'Un effet d’espace mort relatif, avec rapport V/Q élevé.', 'L’oxygène est l’accepteur terminal de la chaîne mitochondriale ; les échanges pulmonaires sont gouvernés par les gradients de pressions partielles.', 'Lié à l’hémoglobine.', 'Elle se contracte, redirigeant le débit vers des régions mieux ventilées.'],
  'phys-digestion': ['Ils émulsifient les lipides et facilitent les micelles ; ils ne les hydrolysent pas directement.', 'La sécrétine.', 'Le foie, dont les hépatocytes synthétisent la bile.', 'La lymphe, via les vaisseaux chylifères.', 'Le facteur intrinsèque, qui permet son absorption dans l’iléon terminal.'],
  'phys-sensory-motor': ['Une énergie ou modalité de stimulation en signal électrique.', 'Récepteur, afférence, centre d’intégration, efférence et effecteur.', 'Dans la décussation pyramidale caudale du bulbe pour la majorité des fibres.', 'Il innerve les fibres musculaires squelettiques extrafusales et constitue la voie motrice finale commune.', 'Tact fin, vibration et proprioception consciente.'],
}
const distractors = ['Elle se déroule sans capteur ni voie de communication.', 'Elle rend les variables internes parfaitement constantes.', 'Elle dépend d’un seul organe dans toutes les situations.', 'Elle n’utilise jamais de signaux électriques ou chimiques.']
export const physiologyQuestions: Question[] = physiologyCourses.flatMap((c, ci) => prompts[c.id].map((prompt, qi) => {
  const answer = answers[c.id][qi]
  const options = [answer, distractors[(qi + ci) % 4], distractors[(qi + ci + 1) % 4], distractors[(qi + ci + 2) % 4]]
  return { id: `${c.id}-q${qi + 1}`, course: c.id, topic: c.category, prompt, options, correct: [0],
    why: options.map((option, oi) => oi === 0 ? answer : `${option} Cette proposition ne décrit pas le mécanisme physiologique demandé.`), difficulty: qi < 2 ? 'essentiel' as const : 'application' as const, format: 'single' as const }
}))
