import type { Course } from '../../curriculum'
import type { Question } from '../../questions'
import { canonicalCourses } from '../../taxonomy/canonicalCourses'

const metadata = new Map(canonicalCourses.filter(item => item.subject === 'Biophysique').map(item => [item.id, item]))
const base = 'https://openstax.org/books/college-physics-2e/pages/'
type Draft = { objectives: string[]; sections: Course['sections']; trap: string; recall: string; answer: string; source: string; learning?: Course['learning']; caseStudy: NonNullable<Course['caseStudy']>; glossary: NonNullable<Course['glossary']> }
const s = (title: string, text: string, bullets?: string[]) => ({ title, text, ...(bullets ? { bullets } : {}) })
function course(id: string, d: Draft): Course {
  const c = metadata.get(id)
  if (!c) throw new Error(`Chapitre canonique de biophysique introuvable : ${id}`)
  return { id, title: c.title, category: c.subject, tag: c.module, minutes: 14, structure: null,
    objectives: d.objectives, sections: d.sections, trap: d.trap, recall: d.recall, answer: d.answer,
    source: base + d.source, sources: [{ label: 'OpenStax · College Physics 2e', url: base + d.source }],
    prerequisites: ['Unités SI et analyse dimensionnelle', 'Notions de concentration et de potentiel électrique'],
    ...(d.learning ? { learning: d.learning } : {}), glossary: d.glossary, caseStudy: d.caseStudy,
    review: { status: 'unreviewed', updatedAt: '2026-09-23', sourcesUpdatedAt: '2026-09-23' } }
}
export const biophysicsCourses: Course[] = [
  course('physics-membranes', {
    objectives: ['Relier diffusion et gradient de concentration', 'Appliquer qualitativement la loi de Fick', 'Distinguer transport passif et actif'],
    sections: [
      s('Déplacement brownien et flux net', 'Les molécules en solution subissent un mouvement thermique désordonné. À l’équilibre, elles traversent une membrane dans les deux sens mais les flux moyens se compensent. En présence d’un gradient de concentration, le flux net se dirige vers la région la moins concentrée, sans que chaque particule « choisisse » cette direction.'),
      s('Loi de Fick', 'Pour une membrane homogène, le flux diffusif augmente avec le coefficient de diffusion, la surface d’échange et la différence de concentration, et diminue avec l’épaisseur. Le coefficient de perméabilité regroupe diffusion et partage dans la membrane. Les unités doivent être vérifiées : un flux surfacique et une quantité totale transférée ne sont pas la même grandeur.'),
      s('Facteurs qui modulent la diffusion', 'La taille moléculaire, la température, la viscosité, la charge, la liposolubilité et les propriétés de la membrane influencent les déplacements. Les petites molécules non polaires traversent souvent la bicouche plus facilement que les ions hydratés. Une protéine canal ou un transporteur peut accroître la perméabilité sans rendre le transport énergétiquement actif.'),
      s('Osmose et tonicité', 'L’osmose est le déplacement de l’eau à travers une membrane sélectivement perméable en réponse à une différence de potentiel chimique de l’eau. La pression osmotique dépend du nombre de particules en solution dans le modèle idéal. La tonicité prédit le changement de volume cellulaire selon les solutés qui ne traversent pas la membrane considérée.'),
      s('Transports couplés', 'Le transport actif primaire utilise directement une source d’énergie, par exemple l’ATP pour une pompe ionique. Le transport actif secondaire couple le déplacement favorable d’un ion à celui d’un soluté contre son gradient. Les cotransporteurs symportent des espèces dans le même sens ; les échangeurs les déplacent en sens opposé.'),
    ], trap: 'Un transport facilité par une protéine peut rester passif s’il suit le gradient électrochimique.', recall: 'Quels paramètres de la loi de Fick augmentent le flux diffusif à travers une membrane ?', answer: 'Une plus grande surface, un coefficient de diffusion supérieur et un gradient de concentration plus marqué augmentent le flux ; une membrane plus épaisse le réduit.', source: '12-3-osmosis-and-diffusion', learning: { formula: { label: 'Flux diffusif simplifié', expression: 'J ∝ D · A · ΔC / Δx', explanation: 'D : coefficient de diffusion ; A : surface ; ΔC : gradient ; Δx : épaisseur traversée. Les conventions de signe et unités dépendent du repère.' }, comparison: { headers: ['Transport', 'Énergie directe', 'Sens général'], rows: [['Diffusion simple', 'Non', 'Selon gradient électrochimique'], ['Diffusion facilitée', 'Non', 'Selon gradient, avec protéine'], ['Transport actif primaire', 'Oui, par exemple ATP', 'Peut aller contre un gradient'], ['Transport actif secondaire', 'Énergie d’un gradient ionique', 'Couplage de flux favorables et défavorables']] }, example: { prompt: 'La surface d’échange double, toutes choses égales par ailleurs.', steps: ['Le flux est proportionnel à A.', 'Multiplier A par 2 multiplie J par 2 dans le modèle.'], result: 'Le flux total double, sans que la perméabilité intrinsèque change.' }, errors: [{ title: 'Confondre flux et perméabilité', detail: 'Le flux observé dépend de la surface et du gradient ; la perméabilité caractérise davantage la membrane et le soluté dans des conditions définies.' }] }, glossary: [['Flux', 'Quantité de matière traversant une surface par unité de temps.'], ['Tonicité', 'Effet des solutés non perméants sur le volume cellulaire.'], ['Gradient électrochimique', 'Combinaison du gradient chimique et de la force électrique pour un ion.']], caseStudy: { prompt: 'Pourquoi un canal ionique peut-il accélérer un passage sans consommation directe d’ATP ?', answer: 'Il augmente la perméabilité et laisse l’ion diffuser selon son gradient électrochimique, sans fournir lui-même l’énergie du déplacement.' }
  }),
  course('physics-bioelectricity', {
    objectives: ['Relier courant, tension et résistance', 'Expliquer la capacité électrique membranaire', 'Interpréter qualitativement un potentiel d’action'],
    sections: [
      s('Charge et différence de potentiel', 'Une différence de potentiel électrique représente une énergie potentielle par unité de charge. Le courant correspond à un débit de charge ; les ions sont les porteurs de courant dans les tissus biologiques. Une membrane sépare deux solutions conductrices et peut maintenir une différence de potentiel grâce aux gradients ioniques et à sa perméabilité sélective.'),
      s('Loi d’Ohm et conductance', 'Dans un élément ohmique, la relation U = R·I associe tension, résistance et courant. La conductance G = 1/R exprime l’aisance du passage. Les canaux ouverts contribuent aux conductances ioniques ; leur ouverture dépend du voltage, de ligands ou de signaux mécaniques. Les tissus vivants sont non linéaires et leurs paramètres évoluent avec le temps.'),
      s('Membrane comme condensateur', 'Les charges séparées de part et d’autre de la bicouche font de la membrane un condensateur. La capacité C relie charge Q et tension U par Q = C·U. La résistance membranaire reflète les voies ioniques ; une constante de temps approximative τ = Rm·Cm décrit la vitesse de réponse à un courant, dans un modèle passif simple.'),
      s('Potentiel de repos', 'Le potentiel de membrane résulte des gradients ioniques, des perméabilités relatives et des transports actifs qui maintiennent ces gradients. Le potentiel d’équilibre de chaque ion dépend de ses concentrations de part et d’autre et de sa valence. Le potentiel observé n’est pas simplement égal à celui d’un seul ion, sauf situation particulière.'),
      s('Potentiel d’action et propagation', 'Une dépolarisation suffisante peut ouvrir des canaux sodiques voltage-dépendants, entraînant une phase ascendante, puis leur inactivation et l’ouverture retardée de conductances potassiques favorisent la repolarisation. La période réfractaire limite le retour immédiat et soutient une propagation orientée. La myéline accélère la conduction en réduisant les fuites entre nœuds.'),
    ], trap: 'Le potentiel d’équilibre d’un ion ne correspond pas automatiquement au potentiel réel de membrane lorsque plusieurs espèces contribuent.', recall: 'Que représente la constante de temps τ dans un modèle membranaire RC passif ?', answer: 'Elle caractérise l’échelle temporelle avec laquelle la tension membranaire approche sa nouvelle valeur après un changement de courant.', source: '20-1-electric-current-voltage-and-resistance', learning: { formula: { label: 'Circuit RC membranaire', expression: 'τ = Rm · Cm', explanation: 'Résistance membranaire en ohms et capacité en farads donnent une constante de temps en secondes.' }, comparison: { headers: ['Paramètre', 'Interprétation', 'Effet qualitatif'], rows: [['Rm', 'Résistance membranaire', 'Plus élevée : fuites passives moindres'], ['Cm', 'Capacité membranaire', 'Plus élevée : davantage de charge pour changer la tension'], ['τ', 'Constante de temps RC', 'Plus élevée : réponse passive plus lente'], ['Conductance ionique', 'Voies disponibles au courant', 'Varie selon l’état des canaux']] }, example: { prompt: 'Rm = 100 MΩ et Cm = 10 pF.', steps: ['Convertir : 100 MΩ = 10⁸ Ω ; 10 pF = 10⁻¹¹ F.', 'τ = 10⁸ × 10⁻¹¹ s.'], result: 'τ = 10⁻³ s, soit 1 ms dans ce modèle simplifié.' }, errors: [{ title: 'Oublier les unités', detail: 'Les préfixes pico et méga changent fortement l’ordre de grandeur ; convertir avant le produit.' }] }, glossary: [['Capacité', 'Quantité de charge stockée par unité de tension.'], ['Dépolarisation', 'Déplacement du potentiel vers une valeur moins négative ou plus positive.'], ['Période réfractaire', 'Période où une nouvelle excitation est impossible ou requiert un stimulus accru.']], caseStudy: { prompt: 'Une démyélinisation augmente les fuites de courant le long d’un axone. Quel effet peut-elle avoir sur la conduction ?', answer: 'La propagation devient moins efficace et plus lente, pouvant échouer si la dépolarisation n’atteint pas le segment suivant.' }
  }),
]
const prompts: Record<string, string[]> = {
  'physics-membranes': ['Dans quel sens se fait le flux net diffusif sans autre force ?', 'Comment l’épaisseur membranaire agit-elle sur le flux selon Fick ?', 'Une diffusion facilitée consomme-t-elle nécessairement de l’ATP ?', 'Que prédit la tonicité ?', 'Que couple un transport actif secondaire ?'],
  'physics-bioelectricity': ['Que relie la loi d’Ohm dans un élément ohmique ?', 'Pourquoi la membrane se comporte-t-elle comme un condensateur ?', 'Quelle équation définit la constante de temps d’un modèle RC ?', 'Le potentiel réel de membrane est-il toujours égal à un potentiel d’équilibre ionique ?', 'Quel événement contribue à la phase ascendante d’un potentiel d’action neuronal classique ?'],
}
const answers: Record<string, string[]> = {
  'physics-membranes': ['Vers la région de moindre concentration, selon le gradient.', 'Une épaisseur accrue diminue le flux diffusif.', 'Non, elle peut suivre un gradient via une protéine sans hydrolyse directe d’ATP.', 'Le changement de volume d’une cellule selon les solutés non perméants.', 'Un flux ionique favorable avec le transport d’un autre soluté contre son gradient.'],
  'physics-bioelectricity': ['La tension, le courant et la résistance : U = R·I.', 'Elle sépare des charges opposées sur les deux faces de la bicouche.', 'τ est le produit de Rm par Cm.', 'Non, le potentiel réel résulte de plusieurs gradients et perméabilités.', 'L’ouverture de canaux sodiques voltage-dépendants augmente l’entrée de charge positive.'],
}
const distractors = ['Elle inverse systématiquement tous les gradients ioniques.', 'Elle ne dépend d’aucune propriété du milieu.', 'Elle mesure uniquement la quantité de matière sans dimension.', 'Elle supprime toute différence de potentiel à travers les tissus.']
export const biophysicsQuestions: Question[] = biophysicsCourses.flatMap((c, ci) => prompts[c.id].map((prompt, qi) => {
  const answer = answers[c.id][qi]
  const options = [answer, distractors[(qi + ci) % 4], distractors[(qi + ci + 1) % 4], distractors[(qi + ci + 2) % 4]]
  return { id: `${c.id}-q${qi + 1}`, course: c.id, topic: c.category, prompt, options, correct: [0],
    why: options.map((option, oi) => oi === 0 ? answer : `${option} Cette proposition ne suit pas le modèle biophysique étudié.`), difficulty: qi < 2 ? 'essentiel' as const : 'application' as const, format: 'single' as const }
}))
