import type { Course } from '../../curriculum'
import type { Question } from '../../questions'
import { canonicalCourses } from '../../taxonomy/canonicalCourses'

const meta = new Map(canonicalCourses.filter(c => c.subject === 'Biophysique').map(c => [c.id, c]))
const s = (title: string, text: string) => ({ title, text })
type L = { id: string; objectives: string[]; sections: Course['sections']; trap: string; recall: string; answer: string; source: string; label: string; case: string; caseAnswer: string }
const units: L[] = [
 { id: 'physics-ultrasound-attenuation-impedance', objectives: ['Relier impédance acoustique et réflexion à une interface', 'Décrire atténuation et compromis fréquence-pénétration', 'Expliquer la formation de l’échogramme'], source: 'https://www.radiologyinfo.org/en/info/genus', label: 'RadiologyInfo · RSNA / ACR',
 sections: [s('Onde sonore et impédance', 'Les ultrasons sont des ondes mécaniques de fréquence supérieure à la bande audible, qui se propagent dans un milieu matériel. L’impédance acoustique Z = ρc combine masse volumique ρ et vitesse du son c dans le milieu. Une différence d’impédance entre deux tissus crée une réflexion partielle à l’interface.'), s('Réflexion et transmission', 'À incidence normale sur une interface plane idéale, le coefficient d’intensité réfléchie dépend du contraste d’impédance : R = ((Z₂−Z₁)/(Z₂+Z₁))². À cette interface idéale sans absorption, la fraction transmise vaut 1 − R. Une interface air-peau réfléchit fortement ; le gel élimine l’air entre sonde et peau pour améliorer la transmission.'), s('Atténuation', 'L’intensité ultrasonore diminue avec la profondeur par absorption, diffusion et réflexion. L’atténuation augmente généralement avec la fréquence et varie selon les tissus. Les gains de compensation en profondeur amplifient les échos tardifs à l’affichage, mais ne restaurent pas l’information perdue et amplifient aussi le bruit.'), s('Résolution et fréquence', 'Une fréquence élevée raccourcit la longueur d’onde et améliore souvent la résolution axiale, mais l’atténuation réduit la pénétration. Une fréquence plus basse convient mieux aux structures profondes, avec résolution moindre. La résolution latérale dépend aussi de la largeur du faisceau et de la focalisation.'), s('Formation de l’image', 'La sonde envoie des impulsions et mesure l’amplitude et le délai des échos. La profondeur est estimée à partir du temps aller-retour et d’une vitesse moyenne supposée, généralement proche de celle des tissus mous. L’image B-mode représente la brillance des échos ; un artefact peut provenir de réverbération, ombre acoustique ou renforcement postérieur.')], trap: 'Le gel facilite la transmission en supprimant une couche d’air ; le gain augmente la brillance affichée sans récupérer le signal perdu.', recall: 'Comment définit-on l’impédance acoustique ?', answer: 'Z = ρc, produit de la masse volumique par la célérité du son.', case: 'Une structure profonde reste mal visible quand la fréquence de la sonde augmente. Quel compromis physique l’explique ?', caseAnswer: 'L’atténuation augmente généralement avec la fréquence : la résolution s’améliore mais la pénétration diminue.' },
 { id: 'physics-doppler-effect-flowmetry', objectives: ['Calculer le décalage Doppler d’un écho ultrasonore', 'Relier angle, vitesse et fréquence mesurée', 'Comparer Doppler continu et pulsé'], source: 'https://www.radiologyinfo.org/en/info/genus', label: 'RadiologyInfo · RSNA / ACR',
 sections: [s('Effet Doppler', 'Lorsqu’une onde est réfléchie par des diffuseurs en mouvement, la fréquence reçue diffère de la fréquence émise. En Doppler ultrasonore, les globules rouges mobiles diffusent le faisceau. Pour une réflexion aller-retour, le décalage est approximativement Δf = 2f₀v cosθ/c, où θ est l’angle entre faisceau et vitesse.'), s('Angle et estimation de vitesse', 'La composante de vitesse mesurée est celle projetée sur le faisceau. À 0° d’angle, cosθ vaut 1 et le décalage est maximal ; à 90°, il est nul. L’angle doit être estimé et rester suffisamment faible pour limiter l’erreur. Un mouvement vers la sonde augmente généralement la fréquence reçue ; un mouvement qui s’en éloigne la diminue.'), s('Doppler continu', 'Le Doppler continu utilise des cristaux distincts d’émission et de réception et détecte toutes les vitesses le long du faisceau. Il peut mesurer des vitesses élevées sans aliasing de Nyquist, mais n’assigne pas précisément la profondeur d’origine du signal. Il est utile lorsque la localisation exacte n’est pas le besoin principal.'), s('Doppler pulsé et aliasing', 'Le Doppler pulsé émet des impulsions et sélectionne une fenêtre de profondeur. La fréquence de répétition des impulsions limite la fréquence maximale mesurable sans repliement spectral : la limite de Nyquist est environ PRF/2. L’aliasing survient si le décalage dépasse cette limite ; augmenter l’échelle ou utiliser un autre mode peut aider selon la situation.'), s('Modes et interprétation', 'Le Doppler spectral affiche le décalage au cours du temps, le Doppler couleur superpose une estimation du sens et de la vitesse moyenne sur l’image B-mode, et le Doppler énergie renseigne surtout sur la présence de flux. La couleur ne donne pas directement le sens anatomique universel : elle dépend de la convention affichée et de l’orientation de la sonde.')], trap: 'À 90°, cosθ = 0 et le Doppler idéal ne mesure pas la composante de vitesse ; le Doppler continu ne localise pas la profondeur.', recall: 'Quelle équation relie le décalage Doppler à la vitesse sanguine ?', answer: 'Δf = 2f₀v cosθ/c pour une réflexion aller-retour.', case: 'Un signal Doppler pulsé dépasse la moitié de la fréquence de répétition et se replie sur le spectre. Quel phénomène est observé ?', caseAnswer: 'L’aliasing, lié à la limite d’échantillonnage de Nyquist.' },
 { id: 'physics-geometric-optics-eye', objectives: ['Appliquer réfraction et vergence aux dioptres simples', 'Décrire la formation d’image rétinienne', 'Distinguer myopie, hypermétropie et presbytie'], source: 'https://openstax.org/books/college-physics-2e/pages/26-2-the-eye', label: 'OpenStax · College Physics 2e',
 sections: [s('Réfraction et dioptre', 'La réfraction est le changement de direction d’une onde qui passe entre milieux où sa vitesse diffère. La loi de Snell-Descartes s’écrit n₁ sinθ₁ = n₂ sinθ₂, les angles étant mesurés à la normale. La cornée et le cristallin réfractent la lumière ; l’indice, la courbure et les distances déterminent la puissance optique.'), s('Image rétinienne', 'La cornée fournit la majeure partie de la puissance réfractive de l’œil, tandis que le cristallin ajuste finement la mise au point par accommodation. Le système optique forme sur la rétine une image réelle, inversée et réduite. La rétine convertit la lumière en signaux nerveux, traités ensuite par les voies visuelles.'), s('Vergence et lentilles', 'La vergence C d’une lentille mince est l’inverse de sa distance focale f exprimée en mètres : C = 1/f, en dioptries. Une lentille convergente a une vergence positive et une divergente une vergence négative selon la convention habituelle. Dans l’œil réel, la puissance dépend de plusieurs surfaces et milieux.'), s('Défauts de réfraction', 'Dans la myopie, l’image d’un objet lointain se forme en avant de la rétine lorsque l’accommodation est relâchée ; une lentille divergente déplace le foyer vers l’arrière. Dans l’hypermétropie, le foyer tend à se situer derrière la rétine et une lentille convergente aide à le ramener. Les causes anatomiques diffèrent selon longueur axiale et puissance optique.'), s('Accommodation et presbytie', 'L’accommodation modifie la courbure du cristallin afin de focaliser les objets proches. Avec l’âge, la diminution de souplesse du cristallin réduit cette capacité : la presbytie gêne la vision de près. Elle n’est pas simplement une forme d’hypermétropie, même si une correction convergente de près peut être utilisée.')], trap: 'Myopie : correction divergente ; hypermétropie : correction convergente. La presbytie résulte surtout de la baisse d’accommodation avec l’âge.', recall: 'Quelle relation donne la vergence d’une lentille mince ?', answer: 'C = 1/f, avec f en mètres et C en dioptries.', case: 'Un œil myope forme au repos l’image d’un objet lointain devant la rétine. Quel type de lentille corrige classiquement ce défaut ?', caseAnswer: 'Une lentille divergente, qui repousse le foyer vers la rétine.' },
 { id: 'physics-sound-waves-auditory', objectives: ['Définir fréquence, période, amplitude et niveau sonore', 'Utiliser l’échelle logarithmique du décibel', 'Relier transmission sonore et impédance de l’oreille'], source: 'https://openstax.org/books/college-physics-2e/pages/17-3-sound-intensity-and-sound-level', label: 'OpenStax · College Physics 2e',
 sections: [s('Onde sonore', 'Dans un fluide, le son est une perturbation mécanique longitudinale faite de compressions et raréfactions. La fréquence f, en hertz, détermine la hauteur perçue ; la période T vérifie T = 1/f. La célérité dépend du milieu et de ses propriétés élastiques et thermiques. Le son ne se propage pas dans le vide.'), s('Intensité acoustique', 'L’intensité I est une puissance transportée par unité de surface, en W/m². Pour une onde sphérique idéale, elle décroît comme 1/r² en champ libre. L’amplitude de pression et l’intensité sont liées, mais leur relation dépend du milieu. Dans une pièce, réflexions, absorption et directivité modifient ce modèle.'), s('Décibels', 'Le niveau d’intensité sonore est L = 10 log₁₀(I/I₀), avec une référence I₀ conventionnelle. Un facteur 10 en intensité correspond à +10 dB ; doubler l’intensité augmente le niveau d’environ 3 dB. L’échelle est logarithmique, et les mesures pondérées en fréquence ne sont pas identiques à l’intensité physique brute.'), s('Oreille et impédance', 'Le pavillon et le conduit auditif guident l’onde vers le tympan. Les osselets transmettent les vibrations de l’air vers le liquide cochléaire et contribuent à l’adaptation d’impédance. La cochlée sépare les fréquences selon leur position et les cellules ciliées convertissent les mouvements en signaux nerveux. Une exposition sonore forte ou prolongée peut endommager l’audition.'), s('Audiométrie et précautions', 'L’audiométrie tonale détermine les seuils de détection à différentes fréquences en conduction aérienne et osseuse. L’écart entre voies peut orienter vers une composante conductive, tandis qu’une atteinte neurosensorielle affecte l’oreille interne ou les voies auditives. Les résultats se lisent avec les symptômes, l’étalonnage et le contexte ; une valeur isolée ne suffit pas à diagnostiquer.')], trap: 'Le décibel est logarithmique : +10 dB correspond à dix fois l’intensité physique, pas à dix fois l’amplitude subjective.', recall: 'De combien de décibels augmente le niveau si l’intensité est multipliée par dix ?', answer: 'ΔL = 10 log₁₀(I₂/I₁) = 10 log₁₀(10) = 10 dB. Le facteur 20 ne s’utilise que pour un rapport d’amplitudes de pression dans le même milieu.', case: 'Deux sons ont des intensités dans un rapport de 100. Quel écart de niveau en décibels les sépare ?', caseAnswer: '20 dB, car 10 log₁₀(100) = 20.' }
]
export const waveCourses: Course[] = units.map(d => {
 const c = meta.get(d.id); if (!c) throw new Error(`Cours canonique inconnu : ${d.id}`)
 return { id: d.id, title: c.title, category: c.subject, tag: c.module, minutes: 17, structure: null, objectives: d.objectives, sections: d.sections, trap: d.trap, recall: d.recall, answer: d.answer, source: d.source, sources: [{ label: d.label, url: d.source }], prerequisites: ['Ondes, milieu matériel et grandeurs physiques'], glossary: [['Fréquence', 'Nombre de cycles d’une onde par seconde.'], ['Impédance', 'Opposition d’un milieu à la propagation et au transfert d’une onde.'], ['Atténuation', 'Diminution de l’intensité d’une onde au cours de sa propagation.']], caseStudy: { prompt: d.case, answer: d.caseAnswer }, review: { status: 'unreviewed', updatedAt: '2026-09-23', sourcesUpdatedAt: '2026-09-23' } }
})
type Item = [prompt: string, options: string[], why: string[]]
const items: Record<string, Item[]> = {
 'physics-ultrasound-attenuation-impedance': [
  ['La masse volumique d’un tissu vaut 1 000 kg/m³ et la célérité 1 500 m/s. Quelle est son impédance acoustique ?', ['1,5 × 10⁶ kg·m⁻²·s⁻¹.', '1,5 kg·m⁻²·s⁻¹.', '0,67 kg·m⁻²·s⁻¹.', '2,25 × 10⁹ kg·m⁻²·s⁻¹.'], ['Z = ρc : 1 000 × 1 500 = 1,5 × 10⁶. Les unités sont celles d’une pression divisée par une vitesse.', 'Le rapport c/ρ donne numériquement 1,5, mais ce rapport ne définit pas l’impédance.', 'Le rapport ρ/c donne environ 0,67 ; Z est un produit, non un quotient.', 'Le produit ρc² vaut 2,25 × 10⁹ et a les dimensions d’une pression, non d’une impédance.']],
  ['Pourquoi une couche d’air entre sonde et peau dégrade-t-elle fortement l’échographie ?', ['Le contraste d’impédance provoque une forte réflexion à l’interface.', 'La célérité devient nulle dans l’air.', 'La fréquence de la sonde est abaissée par le passage dans l’air.', 'Le gain de réception est imposé par l’épaisseur de l’air.'], ['Le grand écart d’impédance renvoie l’essentiel de l’énergie ; le gel assure un couplage acoustique.', 'Le son se propage dans l’air ; sa célérité y est inférieure à celle des tissus mous, mais non nulle.', 'La fréquence est fixée par l’émetteur ; c’est la longueur d’onde qui change avec le milieu.', 'Le gain est un réglage électronique ; il ne supprime pas la réflexion due à l’air.']],
  ['À profondeur et tissu identiques, quel effet attend-on d’une augmentation de fréquence ultrasonore ?', ['Une longueur d’onde plus courte, mais une atténuation généralement accrue.', 'Une longueur d’onde plus longue et une meilleure résolution axiale.', 'Une atténuation moindre et une meilleure pénétration.', 'Une célérité proportionnelle à la fréquence dans les tissus mous.'], ['Avec λ = c/f, la longueur d’onde diminue ; l’atténuation croît généralement avec f, ce qui limite la profondeur utile.', 'La longueur d’onde diminue quand f augmente à célérité constante ; une impulsion spatialement plus courte favorise la résolution axiale.', 'Dans les tissus mous, monter en fréquence augmente généralement les pertes plutôt que la pénétration.', 'La célérité dépend surtout du milieu ; on la suppose approximativement constante dans cette comparaison.']],
  ['Un écho revient après 100 µs. Avec c = 1 540 m/s, à quelle profondeur se situe le réflecteur ?', ['7,7 cm.', '15,4 cm.', '3,85 cm.', '77 cm.'], ['d = ct/2 = 1 540 × 100 × 10⁻⁶/2 = 0,077 m ; le trajet comprend aller et retour.', '15,4 cm est la longueur totale du trajet aller-retour, pas la profondeur.', 'Diviser par quatre compte deux fois la correction aller-retour ; il faut diviser par deux.', '77 cm résulte d’une erreur de conversion des mètres en centimètres.']],
  ['Quel est l’effet d’une augmentation du gain de réception sur un écho très faible ?', ['Le signal reçu et le bruit sont amplifiés.', 'L’énergie acoustique émise dans le patient augmente.', 'La longueur d’onde émise diminue.', 'Une information absente du signal reçu est rétablie.'], ['Le gain amplifie les tensions reçues, y compris le bruit ; il ne crée pas l’information perdue.', 'La puissance d’émission et le gain de réception sont deux réglages distincts.', 'La longueur d’onde dépend de la fréquence et de la célérité, non du gain de réception.', 'Une amplification ne permet pas de reconstruire un écho qui n’a pas été détecté.']],
 ],
 'physics-doppler-effect-flowmetry': [
  ['Dans Δf = 2f₀v cosθ/c, quelle origine a le facteur 2 ?', ['Le décalage intervient lors de la réception puis de la réémission par le diffuseur mobile.', 'Deux globules rouges doivent réfléchir le faisceau.', 'La célérité du son est doublée dans le sang.', 'La fréquence de répétition des impulsions vaut deux fois f₀.'], ['Le diffuseur mobile reçoit une onde décalée puis renvoie une onde à nouveau décalée ; au premier ordre, les deux effets s’additionnent.', 'Un diffuseur mobile suffit à produire un écho Doppler ; le facteur 2 ne compte pas les cellules.', 'La célérité utilisée dans le calcul est celle du milieu ; elle ne double pas du fait du mouvement sanguin.', 'La PRF règle l’échantillonnage temporel, tandis que f₀ est la fréquence porteuse ultrasonore.']],
  ['La vitesse est identique à 0° puis à 60°. Comment varie la valeur absolue du décalage Doppler ?', ['Elle est divisée par deux.', 'Elle est multipliée par deux.', 'Elle devient nulle.', 'Elle reste inchangée.'], ['cos60° = 0,5 : la projection de la vitesse sur le faisceau est divisée par deux.', 'Le décalage est proportionnel à cosθ et diminue entre 0° et 60°.', 'Il s’annule idéalement à 90°, où cosθ = 0, et non à 60°.', 'L’angle modifie la composante de vitesse mesurée même lorsque la vitesse réelle ne change pas.']],
  ['Quel dispositif permet de sélectionner la profondeur du volume étudié en Doppler pulsé ?', ['Une fenêtre temporelle de réception après chaque émission.', 'Une émission continue sans mesure du temps de retour.', 'L’augmentation du gain de réception seule.', 'La suppression du mode B sans changement de l’échantillonnage.'], ['Le délai après émission correspond à une profondeur ; une fenêtre temporelle isole un volume échantillon.', 'Le Doppler continu reçoit les signaux de la ligne du faisceau sans discrimination par temps de vol.', 'Le gain agit sur l’amplitude affichée, pas sur la sélection de profondeur.', 'Le mode B aide au repérage ; le choix de profondeur repose sur la fenêtre temporelle du Doppler pulsé.']],
  ['Pour une PRF de 6 kHz en Doppler pulsé, quel décalage dépasse la limite de Nyquist ?', ['4 kHz.', '2,5 kHz.', '2 kHz.', '1 kHz.'], ['La limite vaut PRF/2 = 3 kHz ; un décalage de 4 kHz subit un repliement spectral.', '2,5 kHz est inférieur à la limite de 3 kHz.', '2 kHz reste dans la bande mesurable sans repliement dans ce modèle.', '1 kHz est inférieur à la limite de Nyquist ; il n’entraîne pas d’aliasing ici.']],
  ['Quel compromis caractérise le Doppler continu par rapport au Doppler pulsé ?', ['Il mesure des vitesses élevées sans aliasing de PRF, mais sans sélection précise de profondeur.', 'Il sélectionne mieux la profondeur mais réduit la vitesse maximale mesurable.', 'Il supprime la dépendance à l’angle du faisceau.', 'Il permet d’estimer une vitesse à 90° sans autre information.'], ['L’émission-réception continue évite la limite de la PRF, mais les signaux proviennent de l’ensemble du faisceau.', 'La localisation par temps de vol appartient au Doppler pulsé ; ce compromis est inversé.', 'Le facteur cosθ intervient aussi en Doppler continu.', 'À 90°, la projection de vitesse est nulle ; le mode continu ne résout pas cette limitation géométrique.']],
 ],
 'physics-geometric-optics-eye': [
  ['Un rayon arrive de l’air dans un milieu d’indice plus élevé, avec une incidence oblique. Comment est-il réfracté ?', ['Il se rapproche de la normale.', 'Il s’éloigne de la normale.', 'Son angle avec la normale est inchangé.', 'Il subit nécessairement une réflexion totale.'], ['n₁ sinθ₁ = n₂ sinθ₂ ; si n₂ > n₁, alors θ₂ < θ₁ pour une incidence non nulle.', 'L’éloignement de la normale se produit au passage vers un indice plus faible, hors réflexion totale.', 'À incidence oblique, un changement d’indice modifie l’angle de réfraction.', 'La réflexion totale exige un passage vers un indice plus faible et une incidence supérieure à l’angle critique.']],
  ['Dans un œil emmétrope regardant au loin sans accommodation, où convergent les rayons issus d’un point de l’objet ?', ['Sur la rétine.', 'En avant de la rétine.', 'En arrière de la rétine.', 'Sur le cristallin.'], ['L’emmétropie correspond à une focalisation rétinienne de l’objet lointain au repos accommodatif.', 'Un foyer situé en avant de la rétine au repos caractérise un œil myope.', 'Un foyer qui se situerait derrière la rétine au repos caractérise l’hypermétropie.', 'Le cristallin réfracte la lumière ; il n’est pas le plan de réception de l’image nette.']],
  ['Une lentille mince a une distance focale de −0,50 m. Quelle est sa vergence ?', ['−2 dioptries.', '+2 dioptries.', '−0,5 dioptrie.', '+0,5 dioptrie.'], ['C = 1/f = 1/(−0,50) = −2 dioptries ; la lentille est divergente.', 'La valeur absolue est correcte mais le signe doit rester négatif.', '−0,5 m est la distance focale ; la vergence est son inverse.', 'Il faut à la fois inverser la distance focale et conserver son signe négatif.']],
  ['Chez un sujet myope, pourquoi une lentille divergente améliore-t-elle la vision de loin ?', ['Elle diminue la convergence de l’ensemble et ramène le foyer sur la rétine.', 'Elle augmente la puissance convergente et avance le foyer.', 'Elle raccourcit la longueur axiale du globe.', 'Elle déclenche une accommodation maximale permanente.'], ['L’œil myope focalise en avant de la rétine ; la divergence ajoutée recule le foyer.', 'Accroître la convergence avancerait encore le foyer et aggraverait le défaut optique.', 'La correction externe modifie le trajet des rayons sans changer la longueur du globe.', 'L’accommodation augmente la convergence ; elle ne corrige pas la myopie de loin.']],
  ['Quel mécanisme explique principalement la presbytie ?', ['La diminution liée à l’âge de la capacité de déformation du cristallin.', 'L’allongement progressif obligatoire du globe.', 'L’augmentation isolée de la puissance cornéenne.', 'La perte sélective des photorécepteurs périphériques.'], ['Le cristallin devient moins déformable ; la réserve d’accommodation pour la vision de près diminue.', 'Un globe plus long peut favoriser la myopie axile, mais ne définit pas la presbytie.', 'La presbytie concerne surtout la diminution de l’accommodation, non une hausse de puissance de la cornée.', 'Une atteinte rétinienne peut altérer la vision, mais elle n’explique pas le défaut accommodatif de la presbytie.']],
 ],
 'physics-sound-waves-auditory': [
  ['Un son périodique a une période de 0,5 ms. Quelle est sa fréquence ?', ['2 000 Hz.', '500 Hz.', '2 Hz.', '0,002 Hz.'], ['f = 1/T = 1/(0,5 × 10⁻³) = 2 000 Hz.', '500 Hz correspondrait à une période de 2 ms, pas de 0,5 ms.', 'Cette valeur oublie la conversion des millisecondes en secondes.', 'Le préfixe milli concerne la période avant inversion ; il ne faut pas multiplier le résultat par 10⁻³.']],
  ['Dans un même milieu, multiplier l’intensité sonore par dix augmente le niveau de combien ?', ['10 dB.', '3 dB.', '20 dB.', '100 dB.'], ['ΔL = 10 log₁₀(10) = 10 dB pour un rapport d’intensités.', 'Environ 3 dB correspond à un doublement de l’intensité.', '20 log₁₀ s’applique à un rapport d’amplitudes de pression ; le rapport d’intensités utilise le facteur 10.', 'L’échelle est logarithmique : on ne multiplie pas directement les décibels par le rapport d’intensités.']],
  ['En champ libre, à puissance constante, on double la distance à une source ponctuelle isotrope. Comment varie l’intensité ?', ['Elle est divisée par quatre.', 'Elle est divisée par deux.', 'Elle est multipliée par quatre.', 'Elle reste constante.'], ['I = P/(4πr²) : doubler r multiplie la surface de répartition par quatre.', 'La décroissance en 1/r concerne l’amplitude de pression dans ce modèle ; l’intensité suit 1/r².', 'S’éloigner répartit l’énergie sur une surface plus grande et diminue l’intensité.', 'La puissance totale reste constante, mais la puissance par unité de surface diminue.']],
  ['Quelle étape réalise la transduction mécanoélectrique auditive ?', ['La déflexion des stéréocils des cellules ciliées cochléaires.', 'Le déplacement de la chaîne des osselets.', 'La vibration de la membrane tympanique.', 'La propagation de l’onde dans le conduit auditif.'], ['La déflexion ouvre des canaux mécanosensibles et modifie le potentiel de la cellule ciliée ; les cellules internes transmettent l’essentiel du message afférent.', 'Les osselets assurent une transmission mécanique vers l’oreille interne, sans réaliser cette transduction.', 'Le tympan transforme la variation de pression en vibration mécanique ; la conversion électrique a lieu dans la cochlée.', 'Le conduit guide une onde de pression ; il ne transforme pas cette onde en signal nerveux.']],
  ['Quel rôle joue l’oreille moyenne dans la transmission de l’air au liquide cochléaire ?', ['Elle améliore le transfert d’énergie malgré la différence d’impédance.', 'Elle change la fréquence fondamentale de chaque son.', 'Elle remplace le mouvement liquidien par une transmission aérienne dans la cochlée.', 'Elle mesure le seuil auditif indépendamment de la cochlée.'], ['Le rapport de surfaces tympan/fenêtre ovale et le levier des osselets augmentent la pression transmise et limitent la perte liée au changement de milieu.', 'La chaîne ossiculaire transmet les fréquences du stimulus ; elle n’a pas pour rôle de les convertir.', 'Le mouvement de l’étrier met en mouvement les liquides de l’oreille interne ; la cochlée n’est pas remplie d’air.', 'Le seuil auditif dépend de l’ensemble de la voie ; sa mesure relève de l’audiométrie, pas d’une fonction de l’oreille moyenne.']],
 ],
}
export const waveQuestions: Question[] = units.flatMap(d => items[d.id].map(([prompt, options, why], i) => ({
 id: `${d.id}-q${i + 1}`, course: d.id, topic: 'Biophysique', prompt, options, correct: [0], why,
 difficulty: i === 0 || i === 3 ? 'application' as const : 'essentiel' as const, format: 'single' as const,
})))
