import type { Course } from '../../curriculum'
import type { Question } from '../../questions'
import { canonicalCourses } from '../../taxonomy/canonicalCourses'

const openStaxChem = 'https://openstax.org/books/chemistry-2e/pages/'
type Draft = Pick<Course, 'objectives' | 'sections' | 'trap' | 'recall' | 'answer' | 'source'> & Partial<Pick<Course, 'learning' | 'glossary' | 'caseStudy'>>
const meta = new Map(canonicalCourses.filter(item => item.subject === 'Chimie').map(item => [item.id, item]))
const build = (id: string, draft: Draft): Course => {
  const canonical = meta.get(id)
  if (!canonical) throw new Error(`Chapitre canonique de chimie introuvable : ${id}`)
  return {
    id, title: canonical.title, category: canonical.subject, tag: canonical.module, minutes: 12,
    structure: null, objectives: draft.objectives, sections: draft.sections, trap: draft.trap,
    recall: draft.recall, answer: draft.answer, source: draft.source,
    sources: [{ label: draft.source.includes('organic-chemistry') ? 'OpenStax · Organic Chemistry' : 'OpenStax · Chemistry 2e', url: draft.source }],
    prerequisites: ['Quantité de matière et unités SI', 'Écriture d’une réaction chimique équilibrée'],
    review: { status: 'unreviewed', updatedAt: '2026-09-23', sourcesUpdatedAt: '2026-09-23' },
    ...(draft.learning ? { learning: draft.learning } : {}),
    ...(draft.glossary ? { glossary: draft.glossary } : {}),
    ...(draft.caseStudy ? { caseStudy: draft.caseStudy } : {})
  }
}
const s = (title: string, text: string, bullets?: string[]) => ({ title, text, ...(bullets ? { bullets } : {}) })

export const chemistryGeneralCourses: Course[] = [
  build('chem-thermodynamics', {
    objectives: ['Distinguer spontanéité thermodynamique et vitesse réactionnelle', 'Calculer ΔG à partir de ΔH, ΔS et T avec des unités cohérentes', 'Interpréter le lien entre énergie libre et position d’équilibre'],
    sections: [
      s('Système et transformation', 'La thermodynamique compare des états initial et final ; elle ne décrit pas la trajectoire moléculaire ni sa vitesse. L’enthalpie H suit les échanges thermiques à pression constante. L’entropie S mesure la dispersion de matière et d’énergie, reliée au nombre de microétats accessibles. Les variations dépendent des états et pas du chemin suivi.'),
      s('Spontanéité et deuxième principe', 'Une transformation spontanée se produit dans le sens considéré sans apport continu de travail extérieur ; elle peut tout de même être lente ou nécessiter une énergie d’amorçage. Le critère général est ΔS univers > 0. Pour un système à température et pression constantes, le critère équivalent est ΔG < 0.'),
      s('Énergie libre de Gibbs', 'À température constante, ΔG = ΔH − TΔS. Un ΔG négatif indique un sens direct favorable dans les conditions considérées, un ΔG positif un sens inverse favorable, et ΔG nul l’équilibre. Il faut exprimer ΔH et TΔS dans les mêmes unités. Les grandeurs standard donnent ΔG°, pas nécessairement ΔG réel.'),
      s('Température et signes', 'Si ΔH < 0 et ΔS > 0, le sens est favorable à toute température dans le modèle. Si ΔH > 0 et ΔS < 0, il ne l’est à aucune. Lorsque ΔH et ΔS ont le même signe, le terme TΔS peut inverser la conclusion avec la température. Les unités des entropies tabulées sont souvent J·mol⁻¹·K⁻¹.'),
      s('Équilibre et composition', 'La relation ΔG = ΔG° + RT ln Q relie l’état instantané à la composition. À l’équilibre, ΔG = 0 et Q = K, d’où ΔG° = −RT ln K. Une réaction peut avoir ΔG° positif mais avancer dans les conditions réelles si Q est suffisamment petit ; standard ne signifie pas universel.'),
      s('Calcul guidé', 'Pour ΔH = −20 kJ·mol⁻¹, ΔS = −50 J·mol⁻¹·K⁻¹ et T = 300 K, convertir ΔS en −0,050 kJ·mol⁻¹·K⁻¹. Alors TΔS = −15 kJ·mol⁻¹ et ΔG = −20 − (−15) = −5 kJ·mol⁻¹ : le sens direct est favorable dans ces conditions.'),
    ],
    trap: 'Un ΔG négatif n’indique pas que la réaction est rapide. La vitesse relève de la cinétique et dépend notamment de l’énergie d’activation.',
    recall: 'Une réaction a ΔH = +10 kJ·mol⁻¹ et ΔS = +40 J·mol⁻¹·K⁻¹. Au-dessus de quelle température ΔG devient-il négatif ?',
    answer: 'T > ΔH/ΔS = 10 000 J·mol⁻¹ / 40 J·mol⁻¹·K⁻¹ = 250 K. Au-dessus, le terme TΔS dépasse ΔH.',
    source: 'https://openstax.org/books/chemistry-2e/pages/16-4-free-energy',
    learning: { formula: { label: 'Énergie libre de Gibbs', expression: 'ΔG = ΔH − TΔS', explanation: 'T en kelvins ; mettre ΔH et TΔS dans la même unité, par exemple kJ·mol⁻¹.' }, comparison: { headers: ['ΔG', 'Interprétation thermodynamique', 'Ce que cela ne dit pas'], rows: [['< 0', 'Sens direct favorable', 'La vitesse réelle'], ['= 0', 'Équilibre', 'Des concentrations égales'], ['> 0', 'Sens inverse favorable', 'Une impossibilité absolue']] }, example: { prompt: 'ΔH = −20 kJ·mol⁻¹, ΔS = −50 J·mol⁻¹·K⁻¹, T = 300 K', steps: ['Convertir ΔS en −0,050 kJ·mol⁻¹·K⁻¹', 'TΔS = −15 kJ·mol⁻¹', 'ΔG = −20 − (−15)'], result: 'ΔG = −5 kJ·mol⁻¹ ; le sens direct est favorable.' }, errors: [{ title: 'Mélanger joules et kilojoules', detail: 'Convertir ΔS ou ΔH avant de calculer TΔS.' }, { title: 'Assimiler spontané à rapide', detail: 'Une réaction thermodynamiquement favorable peut rester lente si sa barrière cinétique est élevée.' }] }
  }),
  build('chem-atomic-structure-periodicity', {
    objectives: ['Relier numéro atomique, isotopes et charge d’un ion', 'Écrire une configuration électronique d’atome léger', 'Expliquer les tendances périodiques à partir de la charge nucléaire effective'],
    sections: [
      s('Noyau et identité de l’élément', 'Le numéro atomique Z est le nombre de protons ; il définit l’élément. Le nombre de masse A additionne protons et neutrons. Des isotopes ont le même Z et des nombres de neutrons différents. Dans un atome neutre, le nombre d’électrons égale Z ; un ion résulte d’un gain ou d’une perte d’électrons, sans modifier le noyau.'),
      s('Électrons et orbitales', 'Les électrons occupent des orbitales décrites par des nombres quantiques. Une orbitale contient au plus deux électrons de spins opposés. Dans une sous-couche, les orbitales de même énergie se remplissent d’abord chacune avec un électron avant appariement (règle de Hund). Le principe de Pauli interdit à deux électrons d’un même atome d’avoir les quatre mêmes nombres quantiques.'),
      s('Écrire une configuration', 'On remplit les sous-couches selon leur énergie croissante : 1s, 2s, 2p, 3s, 3p, puis 4s avant 3d dans l’ordre usuel. Une sous-couche s accueille 2 électrons, p en accueille 6. Pour un cation de métal de transition, les électrons 4s sont retirés avant les 3d, malgré l’ordre de remplissage initial.'),
      s('Lire la périodicité', 'Une période correspond au remplissage d’une couche de valence ; les éléments d’un groupe ont souvent des configurations de valence comparables. Le rayon atomique tend à diminuer de gauche à droite, car la charge nucléaire effective augmente, et à augmenter du haut vers le bas avec l’ajout de couches. L’énergie d’ionisation suit généralement la tendance inverse du rayon.'),
      s('Des tendances aux propriétés', 'L’électronégativité exprime la capacité relative d’un atome engagé dans une liaison à attirer les électrons partagés. Elle augmente globalement vers le haut et la droite du tableau. Ces tendances sont des repères, pas des lois sans exception : comparer d’abord les couches occupées, la charge effective et la stabilité des sous-couches.'),
    ],
    trap: 'Les électrons d’un cation ne se retirent pas toujours dans l’ordre inverse du remplissage. Pour les métaux de transition, on enlève d’abord les électrons ns, puis (n−1)d.',
    recall: 'Un ion X²⁺ possède 10 électrons. Quel est Z de l’atome neutre X et combien de neutrons peut-on en déduire ?',
    answer: 'X²⁺ a perdu deux électrons, donc l’atome neutre en avait 12 et Z = 12. Le nombre de neutrons est indéterminable sans connaître l’isotope ou A.',
    source: openStaxChem + '2-introduction',
    glossary: [['Isotope', 'Atomes d’un même élément qui diffèrent par leur nombre de neutrons.'], ['Orbitale', 'État spatial d’un électron associé à une énergie et à des nombres quantiques.'], ['Électronégativité', 'Tendance relative d’un atome lié à attirer le doublet de liaison.']],
    caseStudy: { prompt: 'Le magnésium forme couramment Mg²⁺. Expliquez la charge et pourquoi elle ne signifie pas que son noyau a perdu deux protons.', answer: 'Le magnésium neutre a 12 protons et 12 électrons. Mg²⁺ a perdu deux électrons de valence : il garde 12 protons, donc reste le magnésium, avec 10 électrons.' }
  }),
  build('chem-chemical-bonds-geometry', {
    objectives: ['Distinguer liaison ionique, covalente et métallique', 'Construire une représentation de Lewis en respectant les électrons de valence', 'Prévoir géométrie et polarité moléculaires avec VSEPR'],
    sections: [
      s('Pourquoi les atomes se lient', 'Une liaison résulte d’interactions électrostatiques entre noyaux et électrons. Le modèle de Lewis suit les électrons de valence et aide à vérifier les octets, les charges formelles et les liaisons. L’octet est utile pour les éléments légers, mais connaît des exceptions : duet de H, électrons célibataires, octet incomplet ou hypervalence dans les modèles introductifs.'),
      s('Trois modèles de liaison', 'Dans une liaison ionique, le transfert électronique conduit à des ions stabilisés dans un réseau, sans molécule isolée nécessairement. Une liaison covalente partage un ou plusieurs doublets. Dans un métal, des électrons délocalisés contribuent à la cohésion et à la conductivité. Les liaisons réelles peuvent avoir un caractère intermédiaire.'),
      s('Lewis et charges formelles', 'Compter les électrons de valence, choisir un squelette, placer les liaisons simples, compléter les doublets non liants et distribuer les électrons restants. Si l’octet manque, créer des liaisons multiples. La charge formelle se calcule : électrons de valence − électrons non liants − moitié des électrons liants. Les formes de résonance déplacent des électrons, pas les atomes.'),
      s('VSEPR : des domaines électroniques à la forme', 'Les domaines électroniques autour d’un atome central s’écartent au maximum. Une liaison simple, double ou triple compte comme un domaine ; un doublet libre en est aussi un et repousse davantage. Quatre domaines donnent une organisation électronique tétraédrique, mais si l’un est un doublet libre, la forme moléculaire est pyramidale trigonale.'),
      s('Polarité et moment dipolaire', 'La polarité d’une liaison dépend de la différence d’électronégativité ; le dipôle moléculaire est la somme vectorielle des dipôles de liaison. Une molécule à liaisons polaires peut être globalement apolaire si sa géométrie compense les vecteurs, comme CO₂ linéaire. Une géométrie asymétrique peut produire un moment résultant.'),
    ],
    trap: 'Ne déduisez pas la polarité moléculaire de la seule polarité des liaisons : il faut tenir compte de la géométrie et de la somme des moments dipolaires.',
    recall: 'Pourquoi CO₂ est-il apolaire alors que chacune de ses liaisons C=O est polaire ?',
    answer: 'La molécule est linéaire et symétrique. Les deux moments dipolaires, égaux et opposés, se compensent.',
    source: openStaxChem + '7-6-molecular-structure-and-polarity',
    glossary: [['Domaine électronique', 'Région de densité électronique autour de l’atome central ; liaison multiple comprise comme un domaine en VSEPR.'], ['Charge formelle', 'Comptabilité conventionnelle des électrons attribués à un atome dans une structure de Lewis.'], ['Résonance', 'Représentation d’une délocalisation électronique par plusieurs structures limites.']],
    caseStudy: { prompt: 'NH₃ et BF₃ ont chacun trois liaisons autour de l’atome central. Pourquoi NH₃ est-il polaire alors que BF₃ ne l’est pas ?', answer: 'NH₃ possède un doublet libre : la forme est pyramidale et les dipôles ne se compensent pas. BF₃ est trigonale plane et symétrique ; ses trois dipôles de liaison se compensent.' }
  }),
  build('chem-solutions-concentrations', {
    objectives: ['Calculer une concentration molaire à partir d’une quantité et d’un volume', 'Effectuer une dilution avec conservation de la quantité de soluté', 'Distinguer molarité, fraction molaire, molalité et osmolarité'],
    sections: [
      s('Composition et concentration', 'Une solution homogène associe un solvant et un ou plusieurs solutés. La concentration molaire C rapporte la quantité de soluté n au volume final V de solution : C = n/V, en mol·L⁻¹ si n est en mol et V en litres. Bien identifier le volume final et convertir les millilitres en litres avant le calcul.'),
      s('Préparer une solution', 'À partir d’un solide, calculer n puis la masse m = nM, peser et compléter au volume final dans une fiole jaugée. Le volume du solvant ajouté n’est pas égal au volume final. À partir d’une solution mère, une dilution conserve la quantité de matière transférée, dans les limites du protocole.'),
      s('Relation de dilution', 'Pour une prise d’essai de solution mère de concentration C₁ et volume V₁ diluée à un volume final V₂ de concentration C₂, C₁V₁ = C₂V₂. Les volumes doivent employer la même unité. Une dilution au facteur F donne C₂ = C₁/F ; elle ne change pas la quantité de soluté prélevée, elle augmente le volume.'),
      s('Autres façons d’exprimer la composition', 'La fraction molaire xᵢ vaut nᵢ divisé par la somme des quantités de matière ; les fractions d’un mélange somment à 1. La molalité rapporte les moles de soluté à la masse de solvant en kilogrammes. L’osmolarité compte les particules osmotiquement actives par litre ; la dissociation d’un électrolyte doit être considérée.'),
      s('Exemple résolu', 'On prélève 10,0 mL d’une solution à 0,50 mol·L⁻¹ et on complète à 100,0 mL. La quantité transférée est 0,50 × 0,0100 = 0,0050 mol ; la concentration finale vaut 0,0050/0,1000 = 0,050 mol·L⁻¹. Le facteur de dilution est 10.'),
    ],
    trap: 'Dans C₁V₁ = C₂V₂, V₂ est le volume final de la solution diluée, pas le volume de solvant ajouté.',
    recall: 'Quel volume d’une solution à 0,20 mol·L⁻¹ faut-il prélever pour préparer 50 mL à 0,040 mol·L⁻¹ ?',
    answer: 'V₁ = C₂V₂/C₁ = 0,040 × 50 / 0,20 = 10 mL, en utilisant la même unité de volume des deux côtés.',
    source: openStaxChem + '11-1-the-dissolution-process',
    learning: { formula: { label: 'Dilution', expression: 'C₁ × V₁ = C₂ × V₂', explanation: 'La quantité de soluté transférée reste constante ; exprimez les volumes dans la même unité.' }, comparison: { headers: ['Grandeur', 'Définition', 'Unité usuelle'], rows: [['Molarité', 'n(soluté) / V(solution)', 'mol·L⁻¹'], ['Molalité', 'n(soluté) / masse du solvant', 'mol·kg⁻¹'], ['Fraction molaire', 'nᵢ / somme des n', 'sans unité']] }, example: { prompt: 'Diluer 10 mL de 0,50 M à 100 mL', steps: ['C₁V₁ = C₂V₂', 'C₂ = 0,50 × 10 / 100', 'Garder les volumes dans la même unité'], result: 'C₂ = 0,050 mol·L⁻¹' }, errors: [{ title: 'Oublier les litres', detail: 'Convertir 50 mL en 0,050 L si la concentration est en mol·L⁻¹.' }, { title: 'Confondre solvant et solution', detail: 'Le volume de la fiole jaugée correspond au volume final de solution.' }] }
  }),
  build('chem-acid-base-equilibria', {
    objectives: ['Identifier donneur et accepteur de proton selon Brønsted', 'Relier pH, pOH et concentrations ioniques à 25 °C', 'Utiliser Ka et pKa pour comparer des couples acide-base'],
    sections: [
      s('Acide, base et couples conjugués', 'Un acide de Brønsted cède un proton H⁺ ; une base le capte. Après cession, l’acide devient sa base conjuguée ; après capture, la base devient son acide conjugué. Dans une réaction, le proton est transféré d’un couple à l’autre. L’eau est amphotère : elle peut donner ou capter H⁺.'),
      s('Équilibre de l’eau et pH', 'L’autoprotolyse de l’eau s’écrit 2 H₂O ⇌ H₃O⁺ + OH⁻. À 25 °C, Kw = [H₃O⁺][OH⁻] = 10⁻¹⁴ et pH + pOH = 14. Le pH est −log₁₀[H₃O⁺] dans le modèle dilué usuel ; une variation d’une unité correspond à un facteur dix de concentration.'),
      s('Acides et bases forts ou faibles', 'Un acide fort est presque totalement transféré à l’eau dans les conditions considérées ; un acide faible établit un équilibre appréciable entre formes protonée et déprotonée. La constante Ka mesure la dissociation du couple ; pKa = −log₁₀ Ka. Plus pKa est petit, plus l’acide est fort, toutes choses comparables.'),
      s('Déplacer un équilibre', 'Pour HA + H₂O ⇌ H₃O⁺ + A⁻, Ka = [H₃O⁺][A⁻]/[HA] à l’équilibre. Ajouter un produit ou un réactif déplace la composition jusqu’à rétablir la relation d’équilibre. La constante dépend de la température, pas des quantités initiales ; ces dernières déterminent la position finale.'),
      s('Résoudre sans perdre le sens', 'Avant de calculer, identifier le couple, écrire l’équation, vérifier les unités et estimer si la dissociation est faible ou quasi totale. Pour une solution diluée d’acide faible monoprotique de concentration initiale C, l’approximation [H₃O⁺] ≈ √(KaC) n’est acceptable que si la fraction dissociée reste petite devant C ; vérifier ensuite cette hypothèse.'),
    ],
    trap: '« Acide fort » décrit une dissociation quasi totale dans l’eau, pas une solution forcément concentrée ni dangereuse ; la force et la concentration sont deux notions différentes.',
    recall: 'Quel couple est le plus acide : pKa = 3 ou pKa = 8 ? Dans quel sens va la réaction acide-base favorisée ?',
    answer: 'Le couple de pKa 3 est le plus acide. Un transfert de proton favorise généralement la formation de l’acide et de la base les plus faibles, donc le côté du couple d’acide au pKa le plus élevé.',
    source: openStaxChem + '14-introduction',
    learning: { formula: { label: 'pH et acidité', expression: 'pH = −log₁₀[H₃O⁺] ; pKa = −log₁₀Ka', explanation: 'Une baisse d’une unité de pH correspond à une concentration en H₃O⁺ multipliée par dix.' }, comparison: { headers: ['Espèce', 'Comportement dans l’eau', 'Couple conjugué'], rows: [['Acide fort', 'Dissociation presque complète', 'Base conjuguée très faible'], ['Acide faible', 'Équilibre partiel', 'Base conjuguée plus réactive'], ['Base', 'Accepte un proton', 'Devient son acide conjugué']] }, example: { prompt: 'Comparer deux acides de pKa 4 et 6', steps: ['ΔpKa = 2', 'Ka₁ / Ka₂ = 10²', 'Un pKa plus faible indique un acide plus dissocié'], result: 'Le premier acide est environ 100 fois plus fort selon Ka.' }, errors: [{ title: 'Inverser pKa et force', detail: 'Plus le pKa est petit, plus l’acide correspondant est fort.' }] }
  }),
  build('chem-buffers-titration', {
    objectives: ['Expliquer comment un couple faible amortit une variation de pH', 'Utiliser Henderson–Hasselbalch dans son domaine de validité', 'Repérer demi-équivalence et équivalence sur un titrage'],
    sections: [
      s('Une réserve acide et basique', 'Un tampon contient des quantités appréciables d’un acide faible HA et de sa base conjuguée A⁻, ou d’une base faible et de son acide conjugué. Ajout de H⁺ : A⁻ le capte ; ajout de OH⁻ : HA le neutralise. La variation est amortie tant qu’aucun constituant n’est épuisé.'),
      s('Relation de Henderson–Hasselbalch', 'Pour HA/A⁻, pH = pKa + log₁₀([A⁻]/[HA]). La relation vient de l’expression de Ka et est surtout utile lorsque les deux formes sont présentes en quantités non négligeables. Au rapport 1, le pH égale le pKa. Le tampon est le plus efficace autour de son pKa.'),
      s('Capacité tampon et choix du couple', 'L’efficacité dépend de la concentration totale du couple et de la proximité du pH visé avec le pKa. Un couple trop dilué est vite dépassé ; un couple très concentré a une capacité supérieure, mais n’abolit pas la variation. La relation ne signifie pas que tout pH est maintenu, ni que le tampon produit des protons à volonté.'),
      s('Construire une courbe de titrage', 'Un titrage suit le pH pendant l’ajout progressif d’un réactif de concentration connue. L’équivalence correspond aux proportions stœchiométriques, pas nécessairement à pH 7. Pour acide faible titré par base forte, le pH à l’équivalence est généralement supérieur à 7 par hydrolyse de la base conjuguée.'),
      s('Demi-équivalence et indicateur', 'Avant l’équivalence d’un acide faible, la neutralisation forme son conjugué : la zone est tampon. À la demi-équivalence, les quantités de HA et A⁻ sont égales, donc pH = pKa. L’indicateur se choisit selon le saut de pH autour de l’équivalence, en faisant coïncider son intervalle de virage avec cette zone.'),
    ],
    trap: 'Le point d’équivalence n’est pas systématiquement à pH 7. La valeur dépend notamment de la force de l’acide et de la base ainsi que de l’hydrolyse des espèces formées.',
    recall: 'On titre un acide faible par une base forte. Que vaut le rapport [A⁻]/[HA] à la demi-équivalence et qu’en déduire pour le pH ?',
    answer: 'Le rapport vaut 1 puisque la moitié de HA a été convertie en A⁻. Henderson–Hasselbalch donne donc pH = pKa.',
    source: openStaxChem + '14-6-buffers',
    learning: { formula: { label: 'Tampon acide faible / base conjuguée', expression: 'pH = pKa + log₁₀([A⁻]/[HA])', explanation: 'À la demi-équivalence, les deux formes sont en quantités égales et pH = pKa.' }, comparison: { headers: ['Étape', 'Espèces dominantes', 'Repère'], rows: [['Avant équivalence', 'HA et A⁻', 'Zone tampon'], ['Demi-équivalence', '[HA] = [A⁻]', 'pH = pKa'], ['Équivalence', 'A⁻ pour acide faible titré', 'pH généralement > 7']] }, example: { prompt: 'Un tampon a pKa 6,1 et [A⁻]/[HA] = 10', steps: ['log₁₀(10) = 1', 'pH = 6,1 + 1'], result: 'pH = 7,1.' }, errors: [{ title: 'Employer la formule après épuisement d’un constituant', detail: 'Henderson–Hasselbalch décrit le couple tampon ; près ou après l’équivalence, refaire la stœchiométrie puis l’équilibre.' }] }
  }),
  build('chem-redox-potentials', {
    objectives: ['Identifier oxydant, réducteur et transfert d’électrons', 'Équilibrer une demi-équation rédox en milieu acide', 'Déterminer le sens spontané à partir des potentiels standards'],
    sections: [
      s('Oxydation et réduction', 'Une oxydation est une perte d’électrons ; une réduction est un gain d’électrons. Les deux ont lieu ensemble. L’oxydant accepte des électrons et se réduit ; le réducteur donne des électrons et s’oxyde. Le nombre d’oxydation sert à suivre le bilan lorsque le transfert n’est pas représenté par des ions libres.'),
      s('Écrire des demi-équations', 'Séparer les deux couples, équilibrer d’abord les atomes autres que O et H, puis O avec H₂O, H avec H⁺ en milieu acide et la charge avec e⁻. Multiplier ensuite les demi-équations pour égaliser les électrons, additionner et simplifier. En milieu basique, neutraliser H⁺ par OH⁻ et simplifier l’eau.'),
      s('Potentiel standard de réduction', 'Les tables donnent généralement des potentiels standard écrits dans le sens de la réduction, dans des conditions standard. Un potentiel plus élevé indique une tendance plus forte à la réduction par rapport à l’électrode de référence. Il ne s’agit pas d’une énergie absolue de l’espèce isolée.'),
      s('Calculer la force électromotrice', 'Pour une pile dans le sens écrit, E°pile = E°cathode − E°anode, avec les deux valeurs prises comme potentiels de réduction. Si E°pile est positif, le sens global choisi est thermodynamiquement favorable dans les conditions standard. Ne multipliez jamais un potentiel par le coefficient stœchiométrique.'),
      s('Lien avec l’équilibre', 'À température donnée, le potentiel de cellule hors standard dépend des activités et du quotient réactionnel Q via l’équation de Nernst. Au cours du fonctionnement d’une pile, les concentrations changent et la tension évolue. À l’équilibre, la force motrice nette devient nulle ; ce cadre relie potentiel, énergie libre et constante d’équilibre.'),
    ],
    trap: 'Pour inverser une demi-équation, le signe de E change. Pour multiplier l’équation afin d’équilibrer les électrons, E ne se multiplie pas.',
    recall: 'Les potentiels standards sont E°(Cu²⁺/Cu) = +0,34 V et E°(Zn²⁺/Zn) = −0,76 V. Quel métal s’oxyde dans une pile spontanée ?',
    answer: 'Le zinc s’oxyde à l’anode. E°pile = 0,34 − (−0,76) = +1,10 V, positif dans le sens Zn + Cu²⁺ → Zn²⁺ + Cu.',
    source: openStaxChem + '17-2-galvanic-cells',
    learning: { formula: { label: 'Pile en conditions standard', expression: 'E°pile = E°cathode − E°anode', explanation: 'Utiliser les potentiels tabulés comme potentiels de réduction, sans les multiplier par les coefficients.' }, comparison: { headers: ['Terme', 'Électrons', 'Dans une pile galvanique'], rows: [['Anode', 'Perte par oxydation', 'Borne négative'], ['Cathode', 'Gain par réduction', 'Borne positive'], ['Oxydant', 'Accepte e⁻', 'Se réduit à la cathode']] }, example: { prompt: 'Couples Cu²⁺/Cu (+0,34 V), Zn²⁺/Zn (−0,76 V)', steps: ['Cu²⁺/Cu a le potentiel de réduction le plus élevé', 'Cu²⁺ se réduit à la cathode', 'E° = 0,34 − (−0,76)'], result: 'E° = +1,10 V ; Zn s’oxyde.' }, errors: [{ title: 'Multiplier E° par le coefficient', detail: 'Le potentiel est intensif ; les électrons s’équilibrent en multipliant les demi-réactions, pas les volts.' }] }
  }),
  build('chem-chemical-equilibria-law', {
    objectives: ['Écrire Qr et K à partir d’une réaction équilibrée', 'Comparer Qr à K pour prévoir le sens d’évolution', 'Décrire l’effet d’une perturbation sans confondre équilibre et immobilité'],
    sections: [
      s('Un équilibre dynamique', 'Dans un système réversible fermé, l’équilibre est atteint lorsque vitesses directe et inverse sont égales. Les concentrations macroscopiques restent alors constantes, mais les transformations moléculaires continuent. L’équilibre n’implique pas des quantités égales de réactifs et de produits.'),
      s('Quotient réactionnel', 'Pour aA + bB ⇌ cC + dD, Qr = a(C)^c a(D)^d / (a(A)^a a(B)^b), où a désigne l’activité ; en solution diluée on l’approche par concentration rapportée à l’état standard. Les solides purs et liquides purs n’apparaissent pas dans l’expression.'),
      s('Constante d’équilibre et direction', 'À température donnée, K est la valeur de Qr à l’équilibre. Si Qr < K, l’évolution nette forme des produits ; si Qr > K, elle forme des réactifs ; si Qr = K, le système est à l’équilibre. Cette comparaison donne une direction, pas la vitesse ni le rendement instantané.'),
      s('Modifier la composition', 'Ajouter un réactif change Qr immédiatement sans changer K si la température est constante ; le système évolue ensuite dans le sens qui ramène Qr vers K. Retirer un produit produit un raisonnement similaire. Un catalyseur accélère l’atteinte de l’équilibre sans déplacer sa composition finale.'),
      s('Température et constante', 'La température peut changer K, contrairement à une variation de quantité ou de pression qui modifie surtout Qr et la composition. Pour une réaction endothermique, chauffer favorise le sens direct ; pour une réaction exothermique, chauffer favorise le sens inverse. Le principe de Le Chatelier résume la réponse à la perturbation.'),
    ],
    trap: 'Le catalyseur ne déplace pas l’équilibre et ne change pas K : il accélère les deux sens et réduit le temps nécessaire pour atteindre l’équilibre.',
    recall: 'Pour une réaction avec K = 4 et Qr = 0,5, dans quel sens évolue le système ?',
    answer: 'Qr < K : l’évolution nette se fait vers les produits jusqu’à ce que Qr atteigne K.',
    source: openStaxChem + '13-2-equilibrium-constants',
    learning: { formula: { label: 'Comparer état instantané et équilibre', expression: 'Qr < K : sens direct · Qr > K : sens inverse · Qr = K : équilibre', explanation: 'K ne change qu’avec la température ; Qr reflète la composition du moment.' }, comparison: { headers: ['Comparaison', 'Évolution nette', 'Interprétation'], rows: [['Qr < K', 'Vers les produits', 'Le quotient doit augmenter'], ['Qr > K', 'Vers les réactifs', 'Le quotient doit diminuer'], ['Qr = K', 'Aucune évolution nette', 'Équilibre dynamique']] }, example: { prompt: 'Si K = 4 et Qr = 0,5', steps: ['Comparer 0,5 à 4', 'Qr est inférieur à K', 'Le système avance vers les produits'], result: 'L’évolution nette est dans le sens direct.' }, errors: [{ title: 'Mettre les solides purs dans Qr', detail: 'Leur activité est constante et intégrée à K ; ils sont omis de l’expression.' }] }
  }),
  build('chem-reaction-kinetics', {
    objectives: ['Calculer une vitesse moyenne avec les coefficients stœchiométriques', 'Déterminer les ordres à partir d’expériences, et non de l’équation globale', 'Relier température, énergie d’activation et catalyse à la vitesse'],
    sections: [
      s('Vitesse et stœchiométrie', 'Pour aA + bB → cC, la vitesse de réaction s’écrit −(1/a)d[A]/dt = −(1/b)d[B]/dt = (1/c)d[C]/dt. Les signes rendent la vitesse positive, et les coefficients permettent de comparer la disparition de réactifs à l’apparition de produits.'),
      s('Loi de vitesse expérimentale', 'Une loi courante est v = k[A]^m[B]^n. Les ordres m et n se déduisent de mesures où l’on fait varier les concentrations initiales ; ils ne sont généralement pas les coefficients de l’équation globale. L’ordre global est m+n. Les unités de k dépendent de l’ordre total.'),
      s('Facteurs cinétiques', 'Une hausse de concentration augmente souvent la fréquence des rencontres réactives. Une hausse de température augmente la fraction de molécules ayant une énergie suffisante pour franchir la barrière d’activation. La surface de contact importe pour les systèmes hétérogènes. Ces facteurs modifient la vitesse, sans suffire à prédire l’équilibre.'),
      s('Arrhenius et énergie d’activation', 'La relation k = A·exp(−Ea/RT) décrit la dépendance thermique de la constante de vitesse dans un domaine donné. Ea est une barrière cinétique ; elle n’est pas l’énergie libre de réaction. Une réaction très favorable thermodynamiquement peut être lente si la barrière est haute.'),
      s('Catalyse et mécanisme', 'Un catalyseur offre une voie réactionnelle alternative de plus faible énergie d’activation et est régénéré au cours du mécanisme. Il accélère l’approche de l’équilibre dans les deux sens, sans changer ΔG° ni K. Les étapes élémentaires décrivent un mécanisme proposé ; la loi cinétique globale doit rester compatible avec les mesures.'),
    ],
    trap: 'Une loi de vitesse ne se déduit pas en général des coefficients stœchiométriques de l’équation globale ; les ordres sont expérimentaux.',
    recall: 'Doubler [A] multiplie la vitesse par quatre, à toutes choses égales. Quel ordre apparent pour A ?',
    answer: 'v ∝ [A]^m et 2^m = 4, donc m = 2. Il s’agit d’un ordre expérimental par rapport à A.',
    source: openStaxChem + '12-3-rate-laws',
    learning: { formula: { label: 'Loi de vitesse empirique', expression: 'v = k[A]ᵐ[B]ⁿ', explanation: 'Les exposants sont déterminés expérimentalement ; l’ordre global vaut m+n.' }, comparison: { headers: ['Modification', 'Effet cinétique fréquent', 'Change K à T constante ?'], rows: [['Concentration', 'Change v selon la loi de vitesse', 'Non'], ['Catalyseur', 'Augmente les vitesses directe et inverse', 'Non'], ['Température', 'Change k et souvent v', 'Oui, peut changer K']] }, example: { prompt: 'Doubler [A] quadruple v', steps: ['Écrire 4 = 2ᵐ', 'Comparer les puissances', 'm = 2'], result: 'La réaction est d’ordre 2 par rapport à A.' }, errors: [{ title: 'Confondre cinétique et thermodynamique', detail: 'La vitesse dit combien de temps prend une transformation ; K compare les états à l’équilibre.' }] }
  }),
  build('chem-intermolecular-forces', {
    objectives: ['Classer les principales interactions entre particules', 'Relier polarité moléculaire et interaction dipôle-dipôle', 'Utiliser les interactions pour raisonner sur solubilité et propriétés physiques'],
    sections: [
      s('Liaisons intramoléculaires et interactions', 'Les liaisons covalentes ou ioniques maintiennent les entités chimiques ; les forces intermoléculaires agissent entre molécules ou particules. Les rompre ou les former affecte notamment volatilité, viscosité, températures de changement d’état et dissolution.'),
      s('Dispersion de London', 'Les fluctuations instantanées du nuage électronique créent des dipôles momentanés qui en induisent chez les voisins. Ces interactions existent entre toutes les particules et deviennent plus importantes lorsque le nuage est plus polarisable. Une molécule apolaire peut donc se liquéfier ou se dissoudre via ces attractions.'),
      s('Dipôles permanents et liaison hydrogène', 'Des molécules polaires s’attirent par interactions dipôle-dipôle. La liaison hydrogène est une interaction particulièrement directionnelle lorsque H lié à N, O ou F interagit avec un doublet libre d’un N, O ou F voisin. Elle influence fortement les propriétés de l’eau et des biomolécules.'),
      s('Interactions ioniques et solvatation', 'Un ion interagit avec le dipôle d’une molécule polaire par attraction ion-dipôle ; l’hydratation des ions contribue à la dissolution des sels dans l’eau. La dissolution dépend du bilan entre interactions soluté-soluté, solvant-solvant et soluté-solvant, ainsi que du gain entropique ; « le semblable dissout le semblable » reste un repère qualitatif.'),
      s('Applications aux propriétés', 'À masse comparable, les molécules capables de liaisons hydrogène ont souvent des températures d’ébullition supérieures aux analogues qui n’en forment pas. La taille, la forme et la surface de contact influencent aussi les forces de dispersion. Comparer une propriété exige donc de considérer ensemble structure, polarité et interactions accessibles.'),
    ],
    trap: 'La liaison hydrogène n’est pas une liaison covalente O–H ou N–H : c’est une interaction entre molécules ou entre régions d’une macromolécule.',
    recall: 'Pourquoi le NaCl se dissout-il bien dans l’eau mais peu dans l’hexane ?',
    answer: 'L’eau polaire stabilise les ions Na⁺ et Cl⁻ par interactions ion-dipôle. L’hexane apolaire ne compense pas suffisamment l’énergie nécessaire pour séparer le réseau ionique.',
    source: openStaxChem + '11-1-the-dissolution-process',
    glossary: [['Polarisabilité', 'Facilité avec laquelle un nuage électronique est déformé.'], ['Solvatation', 'Organisation des molécules de solvant autour d’une espèce dissoute.'], ['Liaison hydrogène', 'Interaction directionnelle impliquant un H lié à N, O ou F et un doublet accepteur.']]
  }),
  build('chem-precipitation-solubility', {
    objectives: ['Écrire le produit de solubilité d’un solide ionique', 'Comparer quotient ionique et Ks pour prévoir une précipitation', 'Prendre en compte stœchiométrie et effet d’ion commun'],
    sections: [
      s('Saturation et équilibre', 'Un solide peu soluble peut être en équilibre avec ses ions en solution : MₐXᵦ(s) ⇌ a Mⁿ⁺ + b Xᵐ⁻. Une solution insaturée peut encore dissoudre du solide ; une solution saturée est à l’équilibre ; une solution sursaturée est métastable et peut précipiter après nucléation.'),
      s('Produit de solubilité Ks', 'Pour l’équilibre ci-dessus, Ks = [Mⁿ⁺]ᵃ[Xᵐ⁻]ᵇ dans l’approximation des solutions diluées. Le solide pur n’apparaît pas dans l’expression. Les exposants viennent des coefficients stœchiométriques. Ks se rapporte à une température et au solide précis.'),
      s('Prévoir une précipitation', 'Après mélange, calculer les concentrations immédiatement après dilution, puis le produit ionique Qs avec les mêmes exposants que Ks. Qs < Ks : pas de précipitation attendue et dissolution possible ; Qs = Ks : saturation ; Qs > Ks : précipitation jusqu’au retour à l’équilibre.'),
      s('Calculer une solubilité molaire', 'Pour un sel de type MX qui libère M²⁺ et X²⁻ en proportions 1:1, si la solubilité vaut s, les deux concentrations sont s et Ks = s², donc s = √Ks. Cette simplification change si le sel a une stœchiométrie différente ou si un ion est déjà présent.'),
      s('Ion commun et limites', 'Ajouter un ion déjà impliqué dans l’équilibre déplace la dissolution vers le solide et diminue généralement la solubilité du sel. Les complexations, réactions acido-basiques et coefficients d’activité peuvent modifier l’analyse simple ; commencer par le modèle demandé, puis vérifier si les conditions données imposent de le raffiner.'),
    ],
    trap: 'Ks petit n’est pas directement la solubilité molaire : la relation dépend des coefficients de dissociation et des autres ions déjà présents.',
    recall: 'Pour MX(s) ⇌ M²⁺ + X²⁻, Ks = 4,0 × 10⁻¹⁰. Quelle est la solubilité molaire en eau pure dans le modèle idéal ?',
    answer: 'Ks = s², donc s = √(4,0 × 10⁻¹⁰) = 2,0 × 10⁻⁵ mol·L⁻¹.',
    source: openStaxChem + '15-1-precipitation-and-dissolution',
    learning: { formula: { label: 'Critère de précipitation', expression: 'Qs > Ks : précipitation · Qs = Ks : saturation · Qs < Ks : sous-saturation', explanation: 'Calculer Qs après mélange et dilution, avant que l’équilibre se réajuste.' }, comparison: { headers: ['État', 'Relation', 'Conséquence'], rows: [['Sous-saturé', 'Qs < Ks', 'Le solide peut se dissoudre'], ['Saturé', 'Qs = Ks', 'Équilibre avec le solide'], ['Sursaturé', 'Qs > Ks', 'Précipitation attendue']] }, example: { prompt: 'MX libère M²⁺ et X²⁻ en proportions 1:1 ; Ks = 4 × 10⁻¹⁰', steps: ['Poser [M²⁺] = [X²⁻] = s', 'Ks = s²', 's = √Ks'], result: 's = 2 × 10⁻⁵ mol·L⁻¹.' }, errors: [{ title: 'Oublier la dilution au mélange', detail: 'Les concentrations immédiatement après mélange déterminent Qs ; ne comparez pas les solutions mères directement.' }] }
  })
]

const q = (course: string, n: number, _topic: string, prompt: string, options: string[], correct: number[], why: string[]): Question => ({ id: `${course}-q${n}`, course, topic: 'Chimie', prompt, options, correct, why, difficulty: n < 3 ? 'essentiel' : 'application' })
export const chemistryGeneralQuestions: Question[] = [
  q('chem-atomic-structure-periodicity',1,'Isotopes','Deux noyaux ont Z = 6 ; l’un a 6 neutrons, l’autre 8. Quelle relation ont-ils ?', ['Ce sont des isotopes du carbone','Ce sont deux éléments différents','Ils ont des nombres de masse identiques','Ils ont nécessairement des charges différentes'],[0],['Même Z : même élément ; les neutrons distinguent les isotopes.','L’identité dépend du nombre de protons.','A vaut 12 puis 14.','La charge dépend des électrons.']),
  q('chem-atomic-structure-periodicity',2,'Ions','Un cation X²⁺ contient 10 électrons. Combien d’électrons possède l’atome neutre ?', ['8','10','12','14'],[2],['Un cation a perdu des électrons ; l’atome neutre en avait deux de plus.','C’est le nombre d’électrons de l’ion.','10 + 2 = 12.','Aucune donnée ne conduit à 14.']),
  q('chem-atomic-structure-periodicity',3,'Périodicité','En général, pourquoi le rayon atomique diminue-t-il de gauche à droite dans une période ?', ['La charge nucléaire effective augmente','Une couche électronique entière est ajoutée à chaque case','Les noyaux perdent des protons','Les électrons de valence disparaissent'],[0],['À couche principale comparable, l’attraction nucléaire effective augmente.','Les électrons sont ajoutés à une couche déjà occupée.','Z augmente le long de la période.','La couche de valence se remplit progressivement.']),
  q('chem-atomic-structure-periodicity',4,'Configuration électronique','Quelle sous-couche peut contenir au maximum six électrons ?', ['s','p','d','f'],[1],['Une sous-couche s contient une orbitale et deux électrons.','p contient trois orbitales, soit six électrons.','d peut en accueillir dix.','f peut en accueillir quatorze.']),
  q('chem-atomic-structure-periodicity',5,'Potentiel d’ionisation','Quelle précaution s’applique à un cation d’un métal de transition ?', ['Retirer d’abord les électrons ns avant les électrons (n−1)d','Retirer d’abord les protons','Inverser le remplissage sans tenir compte des sous-couches','Le nombre de neutrons diminue lors de l’ionisation'],[0],['C’est l’ordre usuel de retrait pour les cations de métaux de transition.','Une ionisation électronique ne touche pas le noyau.','Les sous-couches ns sont retirées avant (n−1)d.','Le noyau ne change pas.']),
  q('chem-chemical-bonds-geometry',1,'Lewis','Combien d’électrons de valence possède l’oxygène neutre, élément du groupe 16 ?', ['4','5','6','8'],[2],['Quatre correspond au groupe 14.','Cinq correspond au groupe 15.','Le groupe principal 16 porte six électrons de valence.','Huit est le nombre d’électrons total, pas de valence.']),
  q('chem-chemical-bonds-geometry',2,'Géométrie','Quelle est la géométrie moléculaire de CO₂ autour du carbone ?', ['Linéaire','Coudée','Pyramidale trigonale','Tétraédrique'],[0],['Deux domaines liants opposés donnent une géométrie linéaire.','Le carbone central n’a pas de doublet libre.','Il n’y a pas trois domaines liants.','Il n’y a pas quatre domaines électroniques.']),
  q('chem-chemical-bonds-geometry',3,'Polarité','Une molécule possède trois liaisons polaires identiques disposées de façon trigonale plane et symétrique. Quelle conclusion est la plus probable ?', ['Les dipôles peuvent se compenser','La molécule est nécessairement polaire','Les liaisons deviennent ioniques','La géométrie n’influence pas le dipôle global'],[0],['La symétrie permet une somme vectorielle nulle.','La polarité dépend aussi de la géométrie.','Rien ne permet de conclure à un transfert ionique.','La géométrie détermine la somme des dipôles.']),
  q('chem-chemical-bonds-geometry',4,'VSEPR','En VSEPR, une liaison double autour de l’atome central compte généralement comme :',['Un domaine électronique','Deux domaines séparés','Aucun domaine','Un doublet non liant'],[0],['Les liaisons multiples comptent comme un domaine de densité électronique.','Les deux paires ne sont pas traitées comme deux directions indépendantes.','Elle occupe un domaine.','Elle est liante, pas non liante.']),
  q('chem-chemical-bonds-geometry',5,'Résonance','Que décrivent des formes mésomères correctement dessinées ?', ['La délocalisation des électrons avec positions atomiques inchangées','Un équilibre rapide entre molécules qui changent de squelette','Une migration de noyaux','Des isotopes distincts'],[0],['Les atomes restent à la même place ; seule la distribution électronique varie.','La résonance est un modèle de délocalisation, pas une interconversion réelle.','Les noyaux ne migrent pas dans les formes mésomères.','Les isotopes diffèrent par leurs neutrons.']),
  q('chem-solutions-concentrations',1,'Molarité','0,20 mol de soluté sont dissoutes pour obtenir 0,50 L de solution. Quelle est C ?', ['0,10 mol·L⁻¹','0,40 mol·L⁻¹','2,5 mol·L⁻¹','4,0 mol·L⁻¹'],[1],['Le produit nV n’est pas la définition.','C = n/V = 0,20/0,50 = 0,40.','Il faut diviser n par V.','Le rapport est inférieur à 1 ici.']),
  q('chem-solutions-concentrations',2,'Dilution','Quel est le principe utilisé dans C₁V₁ = C₂V₂ ?', ['Conservation de la quantité de soluté prélevée','Conservation du volume de solvant','Conservation de la masse du récipient','Formation de nouvelles moles pendant dilution'],[0],['La quantité de soluté transférée ne change pas lors de la dilution.','Le volume augmente.','Le récipient n’intervient pas.','La dilution ne crée ni ne détruit le soluté.']),
  q('chem-solutions-concentrations',3,'Calcul','Quel volume de solution mère 0,20 M faut-il pour préparer 50 mL à 0,040 M ?', ['1 mL','10 mL','25 mL','250 mL'],[1],['C₁V₁ = C₂V₂ donne V₁ = 10 mL.','0,040 × 50 / 0,20 = 10 mL.','Ce volume conduirait à 0,10 M.','Le volume prélevé dépasserait le volume final.']),
  q('chem-solutions-concentrations',4,'Concentrations','Quelle grandeur rapporte les moles de soluté à la masse de solvant ?', ['Molarité','Molalité','Fraction molaire','Osmolarité'],[1],['La molarité utilise le volume de solution.','La molalité est en mol par kilogramme de solvant.','La fraction molaire est sans unité.','L’osmolarité compte les particules par volume.']),
  q('chem-solutions-concentrations',5,'Préparation','Pour préparer 100 mL d’une solution, à quoi correspond le trait de jauge ?', ['Au volume final de la solution','Au volume de solvant à ajouter avant dissolution','Au volume molaire du soluté','Au volume du solide pesé'],[0],['La fiole est complétée jusqu’au volume final.','Le volume du solvant ajouté n’est pas nécessairement le volume final.','Ce terme ne s’applique pas ici.','La fiole mesure un volume de solution.']),
  q('chem-acid-base-equilibria',1,'Brønsted','Dans NH₃ + H₂O ⇌ NH₄⁺ + OH⁻, qui capte le proton ?', ['NH₃','H₂O','NH₄⁺','OH⁻'],[0],['NH₃ gagne H⁺ et devient NH₄⁺.','L’eau cède ici H⁺.','C’est le produit protoné.','C’est la base conjuguée formée.']),
  q('chem-acid-base-equilibria',2,'pH','À 25 °C, une solution a pH = 5. Quelle est sa concentration en H₃O⁺ dans le modèle idéal ?', ['10⁻⁵ mol·L⁻¹','10⁵ mol·L⁻¹','5 mol·L⁻¹','10⁻⁹ mol·L⁻¹'],[0],['[H₃O⁺] = 10⁻pH.','Le logarithme impose une concentration très faible.','Le pH n’est pas directement une concentration.','10⁻⁹ correspondrait à un pH de 9.']),
  q('chem-acid-base-equilibria',3,'pKa','Quel acide est le plus fort : pKa 2 ou pKa 6 ?', ['pKa 2','pKa 6','Ils ont la même force','Impossible à comparer'],[0],['Un pKa plus faible correspond à un Ka plus grand et à un acide plus fort.','pKa plus élevé signifie acide plus faible.','Leurs Ka diffèrent de quatre ordres de grandeur.','Les pKa suffisent à les comparer.']),
  q('chem-acid-base-equilibria',4,'Couples','Après qu’une base B a capté un proton, quelle espèce est produite ?', ['Son acide conjugué BH⁺','Sa base conjuguée B⁻','Un isotope de B','Un oxydant'],[0],['La capture de H⁺ donne l’acide conjugué.','B⁻ correspondrait à une perte d’électron, pas à une protonation.','Aucun noyau n’est changé.','Ce vocabulaire concerne le rédox.']),
  q('chem-acid-base-equilibria',5,'Équilibre','À 25 °C, si [H₃O⁺] = 10⁻⁴ M, quelle est [OH⁻] ?', ['10⁻¹⁰ M','10⁻⁴ M','10⁻¹⁸ M','10¹⁰ M'],[0],['Kw = 10⁻¹⁴ ; [OH⁻] = 10⁻¹⁴/10⁻⁴ = 10⁻¹⁰.','Les concentrations seraient égales seulement à neutralité.','Il faut multiplier à 10⁻¹⁴.','Une concentration supérieure à 1 M n’est pas obtenue.']),
  q('chem-buffers-titration',1,'Tampon','Quel mélange forme le plus directement un tampon ?', ['Acide faible et base conjuguée','Acide fort seul','Base forte seule','Sel insoluble sans ions communs'],[0],['Le couple conjugué neutralise de petites additions acides ou basiques.','Un acide fort seul n’offre pas une réserve conjuguée adaptée.','Une base forte seule n’est pas un tampon.','Un solide isolé n’est pas le couple tampon.']),
  q('chem-buffers-titration',2,'Henderson–Hasselbalch','À la demi-équivalence d’un titrage d’acide faible par base forte, quelle relation est vraie ?', ['pH = pKa','pH = 7 systématiquement','[HA] = 0','Il n’y a pas encore de base conjuguée'],[0],['Les formes HA et A⁻ sont équimolaires.','Le pH d’équivalence peut être différent de 7 et ce point est la demi-équivalence.','HA est encore présent.','A⁻ s’est formé par neutralisation.']),
  q('chem-buffers-titration',3,'Capacité tampon','Que se passe-t-il lorsqu’une quantité importante d’acide dépasse la capacité tampon ?', ['Le constituant A⁻ peut être épuisé','Le tampon conserve toujours exactement le même pH','Le pKa augmente automatiquement','La température détermine seule le pH'],[0],['La base conjuguée est consommée ; le tampon ne peut plus amortir efficacement.','Un tampon n’est pas illimité.','Le pKa ne change pas automatiquement par ajout d’acide.','La composition et les équilibres comptent.']),
  q('chem-buffers-titration',4,'Titrage','Pourquoi l’équivalence acide faible/base forte est-elle souvent à pH supérieur à 7 ?', ['La base conjuguée formée réagit avec l’eau','Toute équivalence est neutre','L’indicateur rend le milieu basique','La base forte disparaît en formant un acide fort'],[0],['A⁻ hydrolyse l’eau et forme OH⁻.','La neutralité dépend des forces acide-base.','L’indicateur signale le pH, il ne le fixe pas.','L’acide conjugué de la base forte est très faible.']),
  q('chem-buffers-titration',5,'Indicateurs','Comment choisir un indicateur de titrage ?', ['Son intervalle de virage recouvre le saut de pH près de l’équivalence','Sa couleur initiale doit être bleue','Son pKa doit toujours valoir 7','Il doit réagir irréversiblement avec tout le titrant'],[0],['Le virage doit se produire dans la zone verticale de la courbe.','La couleur seule n’est pas un critère général.','L’équivalence n’est pas toujours à pH 7.','L’indicateur signale le milieu sans consommer significativement le titrant.']),
  q('chem-redox-potentials',1,'Oxydoréduction','Une réduction correspond à :',['Un gain d’électrons','Une perte d’électrons','Une perte de protons uniquement','Une hausse obligatoire du nombre de masse'],[0],['L’espèce gagne des électrons.','C’est une oxydation.','Un transfert de proton relève d’une réaction acide-base.','Le noyau ne change pas.']),
  q('chem-redox-potentials',2,'Oxydant','Quel rôle joue un oxydant ?', ['Il accepte des électrons et se réduit','Il donne des électrons et s’oxyde','Il ne change jamais','Il donne nécessairement un proton'],[0],['L’oxydant capte les électrons du réducteur.','C’est le rôle du réducteur.','Il se transforme en forme réduite.','Cela n’est pas la définition rédox.']),
  q('chem-redox-potentials',3,'Pile','Avec E°(Cu²⁺/Cu)=+0,34 V et E°(Zn²⁺/Zn)=−0,76 V, quelle est E° de la pile Zn/Cu dans le sens spontané ?', ['+1,10 V','−1,10 V','+0,42 V','−0,42 V'],[0],['0,34 − (−0,76) = +1,10 V.','Le sens écrit est spontané.','La différence est 1,10 V.','La somme en valeur absolue vaut 1,10 V.']),
  q('chem-redox-potentials',4,'Équilibrage','Pour équilibrer une équation rédox en milieu acide, avec quoi équilibre-t-on l’oxygène ?', ['H₂O','H⁺','e⁻','OH⁻ d’abord'],[0],['L’eau apporte un atome d’oxygène.','H⁺ sert ensuite à équilibrer l’hydrogène.','Les électrons équilibrent la charge.','OH⁻ est la stratégie usuelle du milieu basique.']),
  q('chem-redox-potentials',5,'Potentiels','Si une demi-équation est multipliée par 3 pour équilibrer les électrons, comment évolue son potentiel ?', ['Il ne change pas','Il est multiplié par 3','Il est divisé par 3','Il change toujours de signe'],[0],['Le potentiel est une grandeur intensive.','Le coefficient stœchiométrique ne multiplie pas le voltage.','Il n’est pas divisé non plus.','Le signe change uniquement si on inverse la réaction.']),
  q('chem-chemical-equilibria-law',1,'Équilibre','À l’équilibre chimique, que deviennent les vitesses directe et inverse ?', ['Elles sont égales','Elles sont toutes deux nulles','La réaction directe s’arrête','Toutes les concentrations sont égales'],[0],['L’égalité des vitesses maintient les concentrations constantes.','Les transformations microscopiques continuent.','L’équilibre est dynamique.','Les quantités ne sont pas nécessairement égales.']),
  q('chem-chemical-equilibria-law',2,'Quotient réactionnel','Pour A(s) + B(aq) ⇌ C(aq), que contient Qr ?', ['Les activités de B et C, pas celle du solide pur A','L’activité du solide A au carré','La masse totale du récipient','Uniquement les concentrations initiales'],[0],['L’activité d’un solide pur est constante et omise.','Les solides purs sont omis.','Le récipient n’intervient pas.','Qr décrit la composition instantanée.']),
  q('chem-chemical-equilibria-law',3,'Sens d’évolution','À température constante, Qr < K. Quelle direction est attendue ?', ['Vers les produits','Vers les réactifs','Aucune direction possible','K diminue jusqu’à Qr'],[0],['Le quotient doit augmenter pour rejoindre K.','Cela correspondrait à Qr > K.','La comparaison détermine le sens net.','K ne change pas si T est constante.']),
  q('chem-chemical-equilibria-law',4,'Catalyse','Quel est l’effet d’un catalyseur sur un système réversible ?', ['Il accélère l’approche de l’équilibre sans changer K','Il augmente toujours le rendement d’équilibre','Il ne catalyse que le sens direct','Il modifie les coefficients stœchiométriques'],[0],['Il accélère les réactions dans les deux sens.','K reste inchangé à température donnée.','La voie catalysée est accessible aux deux sens.','L’équation globale ne change pas.']),
  q('chem-chemical-equilibria-law',5,'Température','Quel paramètre peut modifier K pour une réaction donnée ?', ['La température','L’ajout d’un catalyseur','La quantité initiale d’un solide pur','Le volume du récipient seul'],[0],['La constante dépend de la température.','Le catalyseur ne déplace pas l’équilibre.','Un solide pur n’entre pas dans K.','Une modification de volume peut changer Qr et la composition, mais pas K à température constante.']),
  q('chem-reaction-kinetics',1,'Ordres','Doubler [A] quadruple la vitesse, les autres facteurs constants. Quel est l’ordre en A ?', ['2','1','0','4'],[0],['Le carré de 2 donne bien un facteur quatre.','Un ordre 1 doublerait la vitesse.','Un ordre 0 ne la changerait pas.','La vitesse serait multipliée par 16 pour un ordre quatre.']),
  q('chem-reaction-kinetics',2,'Mécanisme','Peut-on déduire en général les ordres de réaction de l’équation globale ?', ['Non, ils sont déterminés expérimentalement','Oui, ils égalent toujours les coefficients','Oui, ils valent toujours 1','Non, aucun ordre n’existe'],[0],['La loi cinétique globale est mesurée.','Seules certaines étapes élémentaires permettent cette déduction.','Les ordres peuvent être nuls, fractionnaires ou autres.','Les ordres cinétiques existent pour les lois étudiées.']),
  q('chem-reaction-kinetics',3,'Catalyse','Pourquoi un catalyseur augmente-t-il la vitesse ?', ['Il fournit un mécanisme alternatif de plus faible énergie d’activation','Il augmente toujours la température','Il rend ΔG° négatif','Il est consommé définitivement dans la première étape'],[0],['La voie alternative réduit la barrière cinétique.','Ce n’est pas son mécanisme nécessaire.','La thermodynamique de la réaction globale ne change pas.','Un catalyseur est régénéré au cours du mécanisme.']),
  q('chem-reaction-kinetics',4,'Vitesse','Pour 2A → B, quelle expression relie la vitesse de réaction à A ?', ['v = −(1/2)d[A]/dt','v = −2d[A]/dt','v = d[A]/dt','v = 2[A]'],[0],['Le coefficient stœchiométrique divise le taux de disparition.','Le facteur est inversé.','La disparition doit être prise négativement.','La vitesse n’est pas une concentration isolée.']),
  q('chem-reaction-kinetics',5,'Arrhenius','L’énergie d’activation Ea caractérise principalement :',['Une barrière cinétique à franchir','La quantité totale de produits à l’équilibre','Le pH final','Le nombre stœchiométrique'],[0],['Ea décrit la barrière associée à la vitesse.','Le rendement d’équilibre relève de la thermodynamique.','Le pH n’est pas déterminé par Ea seule.','Ea n’est pas un coefficient.']),
  q('chem-intermolecular-forces',1,'London','Quelle interaction existe aussi entre deux molécules apolaires ?', ['Dispersion de London','Liaison hydrogène obligatoire','Ion-dipôle','Liaison ionique'],[0],['Les fluctuations électroniques induisent des dipôles temporaires.','Elle requiert des motifs donneur/accepteur particuliers.','Elle implique un ion et un dipôle.','Il ne s’agit pas d’un réseau ionique.']),
  q('chem-intermolecular-forces',2,'Liaison hydrogène','Quel motif peut donner une liaison hydrogène forte dans le modèle introductif ?', ['H lié à O interagissant avec un doublet de N voisin','Deux carbones saturés voisins','Deux ions de même charge','Deux noyaux d’hydrogène seuls'],[0],['H–O est un donneur, le doublet de N un accepteur.','Aucun donneur/accepteur adapté n’est présent.','Ils se repoussent électrostatiquement.','La liaison implique un donneur lié à un atome électronégatif.']),
  q('chem-intermolecular-forces',3,'Solubilité','Pourquoi l’eau hydrate-t-elle efficacement de nombreux ions ?', ['Les interactions ion-dipôle stabilisent les ions','L’eau est apolaire','L’eau transforme toujours les ions en atomes','Les forces de London sont absentes'],[0],['Le dipôle de l’eau s’oriente autour des charges.','L’eau est polaire.','Les ions restent chargés dans la solution.','Les forces de dispersion existent aussi dans l’eau.']),
  q('chem-intermolecular-forces',4,'Propriétés','Toutes choses comparables, pourquoi des liaisons hydrogène peuvent-elles élever le point d’ébullition ?', ['Il faut fournir de l’énergie pour séparer les molécules attirées','Elles diminuent toujours la masse molaire','Elles changent les molécules en ions','Elles éliminent toutes les autres forces'],[0],['Des attractions plus fortes demandent davantage d’énergie à surmonter.','Le point d’ébullition ne requiert pas une baisse de masse.','Aucune ionisation obligatoire.','Les interactions coexistent.']),
  q('chem-intermolecular-forces',5,'Forces','Quelle phrase distingue correctement liaison et interaction intermoléculaire ?', ['La liaison covalente unit des atomes dans une entité ; les interactions agissent entre entités','Une liaison hydrogène est toujours plus forte qu’une liaison covalente','Les forces de London n’existent que dans les gaz','Une interaction ion-dipôle exige deux ions'],[0],['La distinction dépend des partenaires et de l’échelle moléculaire.','Une liaison covalente est généralement bien plus forte.','Elles existent aussi dans les liquides et solides moléculaires.','Elle implique un ion et une molécule polaire.']),
  q('chem-precipitation-solubility',1,'Ks','Pour AgCl(s) ⇌ Ag⁺ + Cl⁻, quelle expression convient ?', ['Ks = [Ag⁺][Cl⁻]','Ks = [AgCl]','Ks = [Ag⁺]/[Cl⁻]','Ks = [Ag⁺] + [Cl⁻]'],[0],['Les concentrations ioniques sont multipliées ; le solide pur est omis.','Le solide pur n’apparaît pas dans Ks.','La stœchiométrie impose un produit.','L’expression de masse d’action est un produit.']),
  q('chem-precipitation-solubility',2,'Précipitation','Après mélange, Qs > Ks. Que prévoit le modèle ?', ['Une précipitation jusqu’au retour vers la saturation','Une dissolution complète du solide','Aucun changement possible','Une hausse obligatoire de température'],[0],['La solution est sursaturée.','Elle ne peut pas dissoudre davantage au-delà de l’équilibre.','Elle évolue pour réduire Qs.','La température n’est pas nécessairement modifiée.']),
  q('chem-precipitation-solubility',3,'Calcul','Pour un sel MX de dissolution 1:1 en eau pure, si Ks = 9 × 10⁻¹⁰, quelle est s ?', ['3 × 10⁻⁵ mol·L⁻¹','9 × 10⁻¹⁰ mol·L⁻¹','9 × 10⁻⁵ mol·L⁻¹','3 × 10⁻¹⁰ mol·L⁻¹'],[0],['s = √Ks = 3 × 10⁻⁵.','Ks est un produit, pas la solubilité.','La racine donne 3, pas 9, en mantisse.','Il faut prendre la racine carrée.']),
  q('chem-precipitation-solubility',4,'Ion commun','Quel effet a souvent l’ajout d’un ion commun sur la solubilité d’un sel peu soluble ?', ['Elle diminue','Elle augmente toujours','Ks change immédiatement','Le solide devient un liquide pur'],[0],['L’équilibre est déplacé vers le solide.','L’effet courant est inverse.','Ks reste fixé à température donnée.','L’état du solide ne change pas par cette seule addition.']),
  q('chem-precipitation-solubility',5,'Mélanges','Avant de comparer Qs et Ks après mélange, que faut-il faire ?', ['Calculer les concentrations après dilution','Utiliser directement les concentrations des solutions mères','Omettre les coefficients stœchiométriques','Inclure le solide pur dans Qs'],[0],['Qs se calcule pour la composition initiale effective du mélange.','Les solutions mères ont été diluées.','Les puissances viennent des coefficients.','Le solide pur est omis.'])
]
