import type { Course } from '../../curriculum'
import type { Question } from '../../questions'
import { canonicalCourses } from '../../taxonomy/canonicalCourses'

const oc = 'https://openstax.org/books/organic-chemistry/pages/'
const chemIds = new Map(canonicalCourses.filter(item => item.subject === 'Chimie').map(item => [item.id, item]))
type Draft = Pick<Course, 'objectives' | 'sections' | 'trap' | 'recall' | 'answer' | 'source'> & Partial<Pick<Course, 'glossary' | 'caseStudy'>>
const lesson = (id: string, d: Draft): Course => {
  const item = chemIds.get(id)
  if (!item) throw new Error(`Chapitre canonique de chimie introuvable : ${id}`)
  return { id, title: item.title, category: item.subject, tag: item.module, minutes: 12, structure: null,
    objectives: d.objectives, sections: d.sections, trap: d.trap, recall: d.recall, answer: d.answer,
    source: d.source, sources: [{ label: 'OpenStax · Organic Chemistry', url: d.source }],
    prerequisites: ['Lire une formule topologique', 'Reconnaître liaison covalente et doublet électronique'],
    review: { status: 'unreviewed', updatedAt: '2026-09-23', sourcesUpdatedAt: '2026-09-23' },
    ...(d.glossary ? { glossary: d.glossary } : {}), ...(d.caseStudy ? { caseStudy: d.caseStudy } : {}) }
}
const s = (title: string, text: string, bullets?: string[]) => ({ title, text, ...(bullets ? { bullets } : {}) })

export const chemistryOrganicCourses: Course[] = [
  lesson('chem-organic-functions-isomery', {
    objectives: ['Repérer les principales fonctions à partir d’une formule développée', 'Appliquer une stratégie de nomenclature à chaîne principale', 'Distinguer isomérie de constitution et stéréoisomérie'],
    sections: [
      s('Lire la structure carbonée', 'Les atomes de carbone peuvent former des chaînes ou des cycles et établir quatre liaisons covalentes. Dans une formule topologique, chaque sommet et extrémité non étiquetée représente un carbone ; les hydrogènes liés au carbone sont implicites. Les hétéroatomes et leurs hydrogènes sont écrits.'),
      s('Reconnaître les fonctions', 'Une fonction est un motif qui organise une partie de la réactivité : alcool R–OH, amine R–NH₂, aldéhyde R–CHO, cétone R–CO–R′, acide carboxylique R–COOH, ester R–COO–R′, amide R–CONH₂. Un même composé peut porter plusieurs fonctions ; ne confondez pas ester et éther, ni aldéhyde et cétone.'),
      s('Nommer sans sauter d’étapes', 'Choisir une chaîne mère contenant la fonction prioritaire et, si possible, le maximum d’insaturations pertinentes ; numéroter pour donner les plus petits indices selon les règles applicables ; identifier substituants et locants ; terminer par le suffixe correspondant à la fonction principale. Pour une molécule polyfonctionnelle, les fonctions secondaires deviennent souvent des préfixes.'),
      s('Isomérie de constitution', 'Deux composés de même formule brute sont isomères de constitution si leurs atomes sont connectés différemment. L’isomérie peut toucher le squelette, la position d’une fonction ou la fonction elle-même. Des formules brutes identiques ne suffisent donc pas à conclure à une structure ou à des propriétés identiques.'),
      s('Du dessin au raisonnement', 'Avant de nommer ou comparer, dessiner explicitement les liaisons autour du groupe fonctionnel, repérer les carbones porteurs, puis vérifier la valence. Une modification de connectivité change la constitution ; un simple changement d’orientation spatiale avec mêmes connexions relève de la stéréoisomérie, examinée séparément.'),
    ],
    trap: 'Deux dessins qui semblent différents peuvent représenter la même molécule tournée dans l’espace. Comparez d’abord la connectivité avant de conclure à un isomère.',
    recall: 'Quelle différence structurale distingue un aldéhyde d’une cétone ?',
    answer: 'Dans un aldéhyde, le carbone du carbonyle est lié à au moins un hydrogène ; dans une cétone, il est lié à deux groupes carbonés.',
    source: oc + '3-4-naming-alkanes',
    glossary: [['Fonction', 'Groupe d’atomes qui contribue aux propriétés et à la réactivité d’une molécule.'], ['Isomères de constitution', 'Molécules de même formule brute mais de connectivité différente.'], ['Locant', 'Indice qui indique la position d’un groupe ou d’une insaturation dans le nom.']],
    caseStudy: { prompt: 'Deux molécules ont la formule C₂H₆O. L’une contient –OH, l’autre un atome O entre deux carbones. S’agit-il d’une même fonction ?', answer: 'Non. La première est un alcool (éthanol), la seconde un éther (diméthyléther) ; elles ont même formule brute mais connectivité et fonction différentes.' }
  }),
  lesson('chem-organic-stereochemistry-conformations', {
    objectives: ['Lire une projection de Cram et de Newman', 'Comparer conformations décalée et éclipsée autour d’une liaison simple', 'Relier encombrement stérique et stabilité relative'],
    sections: [
      s('Conformation et configuration', 'La rotation autour d’une liaison simple σ change l’orientation des groupes sans rompre la liaison : elle produit des conformères. Changer une configuration demande en général de rompre et reformer des liaisons ou d’inverser un centre stéréogène. Cette différence distingue un mouvement accessible d’une transformation chimique.'),
      s('Projections utiles', 'La projection de Cram code l’orientation dans l’espace : trait simple dans le plan, coin plein vers l’observateur, coin hachuré vers l’arrière. La projection de Newman regarde dans l’axe d’une liaison C–C ; le carbone avant est un point, le carbone arrière un cercle. Elle rend visible l’angle dièdre.'),
      s('Décalée ou éclipsée', 'Une conformation décalée place les liaisons du carbone arrière entre celles du carbone avant ; les répulsions électroniques et la tension de torsion sont réduites. Une conformation éclipsée aligne les liaisons et est généralement plus énergétique. L’énergie varie au cours de la rotation et plusieurs minima ou maxima peuvent exister.'),
      s('Éthane et butane', 'Pour l’éthane, la conformation décalée est plus stable que l’éclipsée. Pour le butane, la conformation anti, où les deux groupes méthyle sont à 180°, est généralement le minimum ; les conformations gauches à 60° sont moins favorables à cause de l’encombrement. L’éclipsée méthyle–méthyle est particulièrement défavorable.'),
      s('Cycles et représentation', 'Dans le cyclohexane chaise, les substituants occupent des positions axiales ou équatoriales. Un basculement de chaise échange ces positions sans changer la connectivité ni convertir un substituant « haut » en « bas ». Les substituants volumineux préfèrent généralement l’équatorial, où les interactions 1,3-diaxiales sont réduites.'),
    ],
    trap: 'Le basculement de chaise échange axial et équatorial, mais conserve l’orientation haut/bas du substituant et la configuration du carbone.',
    recall: 'Dans le butane, pourquoi la conformation anti est-elle plus stable que la gauche ?',
    answer: 'Les groupes méthyle sont plus éloignés à 180° en anti qu’à 60° en gauche ; les interactions stériques entre eux sont moindres.',
    source: oc + '3-7-conformations-of-other-alkanes',
    glossary: [['Conformère', 'Arrangement spatial interconvertible par rotation autour d’une liaison simple.'], ['Angle dièdre', 'Angle entre deux liaisons observées le long d’une liaison centrale.'], ['Interaction 1,3-diaxiale', 'Encombrement entre un substituant axial et des groupes axiaux de carbones éloignés de deux positions.']]
  }),
  lesson('chem-organic-chirality-enantiomers-diastereomers', {
    objectives: ['Repérer un centre stéréogène tétraédrique', 'Attribuer R/S avec les règles CIP', 'Distinguer énantiomères, diastéréoisomères et mélange racémique'],
    sections: [
      s('Chiralité et superposition', 'Une molécule est chirale si son image dans un miroir n’est pas superposable à elle. Un carbone tétraédrique lié à quatre groupes différents est une cause courante de chiralité, mais la propriété s’apprécie pour la molécule entière. La présence d’un tel centre ne suffit donc pas dans tous les cas à conclure.'),
      s('Priorités CIP', 'Attribuer les priorités en comparant les numéros atomiques des atomes directement liés au centre ; le numéro le plus élevé l’emporte. En cas d’égalité, comparer les atomes du rang suivant, classés par numéro atomique décroissant, jusqu’au premier point de différence. Les liaisons multiples sont traitées comme des duplications conventionnelles.'),
      s('Notation R/S', 'Orienter le substituant de plus faible priorité vers l’arrière. Suivre ensuite 1 → 2 → 3 : sens horaire, R ; antihoraire, S. Si la priorité 4 pointe vers l’observateur, inverser le résultat apparent. R/S décrit la configuration absolue ; cela ne prédit pas le signe de rotation optique.'),
      s('Relations entre stéréoisomères', 'Deux images miroir non superposables sont des énantiomères : elles ont mêmes propriétés dans un environnement achiral, mais peuvent interagir différemment avec des systèmes biologiques chiraux. Des stéréoisomères qui ne sont pas images miroir sont des diastéréoisomères ; leurs propriétés physiques et chimiques peuvent différer.'),
      s('Plusieurs centres et formes méso', 'Avec n centres indépendants, 2ⁿ configurations sont un maximum, pas une garantie : une symétrie interne peut réduire le nombre, comme dans une forme méso achirale. Un mélange équimolaire de deux énantiomères est racémique et ne présente pas de rotation optique nette dans les conditions idéales.'),
    ],
    trap: 'R ne veut pas dire dextrogyre et S ne veut pas dire lévogyre. La notation décrit la configuration ; le signe optique doit être mesuré.',
    recall: 'Deux molécules possèdent chacune deux centres stéréogènes. Si elles ont des configurations opposées aux deux centres, quelle relation peuvent-elles avoir ?',
    answer: 'Si les configurations sont inversées à tous les centres et que les molécules sont non superposables, ce sont des énantiomères. Il faut vérifier la symétrie et la possibilité de forme méso.',
    source: oc + '5-2-the-reason-for-handedness-in-molecules-chirality',
    glossary: [['Énantiomères', 'Stéréoisomères images miroir non superposables.'], ['Diastéréoisomères', 'Stéréoisomères qui ne sont pas images miroir.'], ['Centre stéréogène', 'Atome où un échange de deux substituants produit un stéréoisomère.']],
    caseStudy: { prompt: 'Un échantillon contient 50 % de chaque énantiomère d’une molécule. Que peut-on dire de son activité optique nette ?', answer: 'Dans un milieu achiral et en conditions idéales, les rotations opposées se compensent : le mélange racémique n’a pas de rotation optique nette.' }
  }),
  lesson('chem-electronic-effects-inductive-mesomeric', {
    objectives: ['Reconnaître les effets inductif et mésomère', 'Suivre le déplacement des doublets avec des flèches courbes', 'Relier la délocalisation à la stabilité et à la réactivité'],
    sections: [
      s('Polarisation inductive', 'L’effet inductif transmet une polarisation à travers les liaisons σ, liée notamment aux différences d’électronégativité. Un substituant attracteur retire de la densité électronique ; un donneur en pousse relativement vers le squelette. L’effet s’atténue avec la distance et n’implique pas à lui seul une charge entière.'),
      s('Délocalisation mésomère', 'Un système conjugué permet de délocaliser des électrons π ou des doublets non liants sur plusieurs atomes voisins. Les structures limites représentent la distribution ; l’hybride réel est délocalisé. Un donneur par résonance fournit un doublet au système ; un attracteur reçoit la densité par résonance.'),
      s('Tracer les flèches correctement', 'Une flèche courbe part d’une source d’électrons : liaison ou doublet. Elle pointe vers l’atome receveur ou vers la nouvelle liaison. À chaque étape, vérifier les charges et la valence. Une flèche ne représente ni le déplacement d’un atome ni le mouvement isolé d’un proton.'),
      s('Effets sur acidité et basicité', 'Un substituant qui stabilise la base conjuguée peut augmenter l’acidité ; la délocalisation d’une charge négative sur plusieurs atomes est souvent stabilisante. À l’inverse, la disponibilité d’un doublet conditionne la basicité et la nucléophilie. Solvant, encombrement et structure interviennent aussi : aucun effet électronique n’explique seul toutes les réactivités.'),
      s('Conjugaison et absorption', 'La conjugaison relie des orbitales p adjacentes et peut réduire l’écart énergétique entre niveaux électroniques ; elle influence la stabilité et parfois la couleur des molécules. Une double liaison isolée ne transmet pas les mêmes effets qu’un système conjugué. Distinguer donc conjugaison continue et alternance interrompue.'),
    ],
    trap: 'Une flèche mésomère déplace des électrons, pas les atomes. Les formes limites ne sont pas des espèces qui s’interconvertissent en oscillant.',
    recall: 'Pourquoi un carboxylate est-il plus stable qu’une charge négative localisée sur un seul oxygène ?',
    answer: 'Les formes mésomères répartissent la densité négative entre les deux oxygènes équivalents ; la charge est délocalisée, ce qui stabilise la base conjuguée.',
    source: 'https://openstax.org/books/organic-chemistry/pages/2-5-rules-for-resonance-forms',
    glossary: [['Effet inductif', 'Polarisation transmise à travers les liaisons σ.'], ['Effet mésomère', 'Redistribution électronique par conjugaison des orbitales p.'], ['Conjugaison', 'Recouvrement continu d’orbitales p permettant la délocalisation électronique.']]
  }),
  lesson('chem-reaction-mechanisms-sn1-sn2', {
    objectives: ['Comparer les étapes élémentaires des mécanismes SN1 et SN2', 'Relier substrat, nucléophile, solvant et stéréochimie au mécanisme', 'Prédire qualitativement la cinétique et le produit de substitution'],
    sections: [
      s('Substitution nucléophile', 'Un nucléophile donne un doublet pour former une liaison au carbone électrophile ; un groupe partant quitte ce carbone avec le doublet de liaison. Le mécanisme dépend de la structure du substrat et des conditions. Les désignations SN1 et SN2 décrivent la cinétique de l’étape déterminante et l’organisation du mécanisme.'),
      s('SN2 : une étape concertée', 'Le nucléophile attaque à l’opposé du groupe partant pendant que celui-ci s’éloigne. Une seule étape, sans carbocation libre ; la vitesse dépend du substrat et du nucléophile : v = k[substrat][Nu]. À un centre stéréogène, l’attaque arrière entraîne une inversion de configuration géométrique, dite inversion de Walden.'),
      s('SN1 : ionisation puis capture', 'Le groupe partant part d’abord et forme un carbocation ; cette ionisation est l’étape lente. Le nucléophile attaque ensuite. La vitesse de l’étape déterminante dépend principalement du substrat : v = k[substrat]. Un carbocation plan peut être attaqué des deux côtés ; la racémisation peut être partielle selon la paire d’ions et l’environnement.'),
      s('Substrat, nucléophile, solvant', 'Les carbocations tertiaires sont mieux stabilisés que les primaires par hyperconjugaison et effets inductifs, ce qui favorise SN1 ; un carbocation primaire est généralement défavorable. L’encombrement gêne l’attaque arrière et pénalise SN2. Un nucléophile fort et un solvant polaire aprotique soutiennent souvent SN2 ; un solvant protique stabilise les ions et peut soutenir SN1.'),
      s('Choisir sans règle absolue', 'Pour un substrat secondaire, plusieurs voies peuvent entrer en compétition. Examiner d’abord l’encombrement, la force et la basicité du nucléophile, le pouvoir du groupe partant et le solvant, puis chercher substitution ou élimination. Un schéma pédagogique décrit des tendances ; les conditions et la structure exacte restent décisives.'),
    ],
    trap: 'SN1 ne signifie pas « une molécule au total » : le mécanisme comporte plusieurs étapes ; « 1 » désigne l’ordre cinétique de l’étape déterminante.',
    recall: 'Quel mécanisme de substitution attend-on le plus volontiers pour un halogénure primaire avec un bon nucléophile en solvant aprotique ?',
    answer: 'SN2 est favorisé : le carbone primaire est accessible à l’attaque arrière et un nucléophile bon accélère l’étape concertée.',
    source: oc + '11-12-a-summary-of-reactivity-sn1-sn2-e1-e1cb-and-e2',
    glossary: [['Nucléophile', 'Donneur de doublet qui forme une nouvelle liaison.'], ['Groupe partant', 'Substituant qui quitte le substrat avec le doublet de la liaison rompue.'], ['Inversion de Walden', 'Inversion géométrique au centre réactif lors d’une attaque SN2 arrière.']],
    caseStudy: { prompt: 'Un tert-butyl halogéné réagit dans un solvant polaire protique avec un nucléophile faible. Quelle voie de substitution est plausible et pourquoi ?', answer: 'SN1 est plausible : le substrat tertiaire peut former un carbocation relativement stabilisé, et le solvant protique stabilise les espèces ioniques. Les autres voies restent dépendantes des conditions exactes.' }
  }),
  lesson('chem-reaction-mechanisms-e1-e2', {
    objectives: ['Distinguer E1 et E2 par leur séquence d’étapes et leur loi cinétique', 'Relier force de base et structure du substrat à la voie d’élimination', 'Repérer géométrie anti-périplanaire et produit alcène attendu'],
    sections: [
      s('Éliminer pour former une double liaison', 'Une élimination enlève un proton β et un groupe partant porté par le carbone voisin ; les électrons de la liaison C–H contribuent à la nouvelle liaison π. Elle concurrence souvent la substitution. Le squelette et l’orientation spatiale des groupes déterminent les produits accessibles.'),
      s('E2 : départ concerté', 'Une base arrache le proton β pendant que le groupe partant quitte le carbone α et que la liaison C=C se forme, en une étape. La vitesse dépend des concentrations du substrat et de la base : v = k[substrat][base]. Une géométrie anti-périplanaire des liaisons C–H et C–X favorise le recouvrement orbital.'),
      s('E1 : carbocation intermédiaire', 'Le groupe partant s’éloigne d’abord pour former un carbocation, puis une base enlève un proton β. La vitesse de l’étape lente dépend du substrat. La rotation autour des liaisons adjacentes peut précéder l’élimination ; les réarrangements de carbocation sont possibles si une voie plus stable existe.'),
      s('Substrat et conditions', 'Les substrats tertiaires favorisent plus volontiers E1 en milieu ionisant, mais une base forte peut conduire à E2. E2 exige une base ; une base encombrée peut favoriser l’arrachement du proton le plus accessible. Les substrats primaires suivent rarement E1, car un carbocation primaire est très défavorable.'),
      s('Régiosélectivité et stéréochimie', 'Quand plusieurs hydrogènes β sont disponibles, plusieurs alcènes peuvent se former. La règle de Zaïtsev décrit souvent la prédominance de l’alcène le plus substitué, mais l’encombrement et les contraintes géométriques peuvent inverser cette tendance. En E2, seule une géométrie alignée appropriée réagit efficacement.'),
    ],
    trap: '« E1 donne toujours le produit de Zaïtsev » est trop catégorique : la géométrie, l’encombrement de la base et le squelette peuvent contrôler le produit majoritaire.',
    recall: 'Quelle différence de loi cinétique distingue E1 de E2 ?',
    answer: 'E1 dépend de la concentration du substrat dans l’étape déterminante, v = k[substrat] ; E2 dépend du substrat et de la base, v = k[substrat][base].',
    source: oc + '11-12-a-summary-of-reactivity-sn1-sn2-e1-e1cb-and-e2',
    glossary: [['Carbone α', 'Carbone qui porte le groupe partant dans le substrat.'], ['Hydrogène β', 'Hydrogène porté par un carbone voisin du carbone α.'], ['Anti-périplanaire', 'Disposition coplanaire où deux liaisons sont opposées à 180°.']]
  }),
  lesson('chem-alkenes-electrophilic-addition', {
    objectives: ['Expliquer pourquoi le doublet π d’un alcène réagit avec un électrophile', 'Tracer les étapes élémentaires d’une addition électrophile simple', 'Prévoir régiosélectivité et limites des règles usuelles'],
    sections: [
      s('La double liaison comme source électronique', 'Une double liaison C=C associe une liaison σ et une liaison π. Le nuage π est exposé et plus facilement polarisable que le squelette σ ; il peut donner de la densité à un électrophile. L’addition transforme la liaison π et forme deux nouvelles liaisons σ, saturant les carbones concernés.'),
      s('Mécanisme avec HX', 'Pour l’addition de HBr à un alcène, le doublet π capte H⁺ et forme un carbocation ; Br⁻ attaque ensuite. La première étape détermine souvent l’orientation du produit. Un intermédiaire carbocationique peut se réarranger si un déplacement conduit à une espèce plus stable.'),
      s('Règle de Markovnikov', 'Dans l’addition ionique usuelle de HX à un alcène asymétrique, H se fixe souvent sur le carbone qui portait déjà le plus d’hydrogènes, ce qui place la charge positive intermédiaire sur le carbone le plus substitué et généralement mieux stabilisé. C’est une tendance mécanistique, pas une règle sans exception.'),
      s('Orientation stéréochimique', 'Un carbocation est approximativement plan ; un nucléophile peut attaquer ses deux faces. Si un nouveau centre stéréogène est créé, on peut obtenir plusieurs stéréoisomères. D’autres mécanismes d’addition, comme certaines additions concertées, imposent une stéréochimie différente ; toujours identifier les conditions avant de conclure.'),
      s('Raisonner sur un produit', 'Repérer les deux carbones de la double liaison, indiquer l’électrophile et le nucléophile, dessiner l’intermédiaire le plus plausible et vérifier la stabilité de la charge. Puis vérifier valences, régiosélectivité et stéréochimie. Une formule brute inchangée ne suffit pas à établir le mécanisme.'),
    ],
    trap: 'La règle de Markovnikov ne dit pas que le carbone le plus substitué « attire » directement H : l’orientation découle de la stabilité relative de l’intermédiaire dans ce mécanisme.',
    recall: 'Lors de l’addition de HBr au propène par voie ionique, quel carbocation est favorisé ?',
    answer: 'La protonation qui place la charge positive sur le carbone secondaire conduit au carbocation le plus stable ; Br⁻ attaque ensuite ce centre.',
    source: oc + '7-7-electrophilic-addition-reactions-of-alkenes',
    glossary: [['Électrophile', 'Accepteur de paire d’électrons.'], ['Carbocation', 'Intermédiaire carboné portant une charge positive.'], ['Régiosélectivité', 'Préférence d’une réaction pour une orientation de formation des produits.']]
  }),
  lesson('chem-carbonyl-nucleophilic-addition', {
    objectives: ['Expliquer la polarisation de la liaison C=O', 'Tracer l’addition d’un nucléophile sur aldéhyde ou cétone', 'Comparer qualitativement leur réactivité envers une addition nucléophile'],
    sections: [
      s('Un carbone électrophile', 'L’oxygène attire davantage le doublet de la liaison C=O : O porte une densité électronique plus élevée et le carbone est électrophile. Un nucléophile apporte un doublet au carbone carbonylé. La liaison π se déplace vers l’oxygène, formant un intermédiaire tétraédrique de type alcoolate.'),
      s('Étapes de l’addition', 'Dans le modèle basique, Nu⁻ attaque le carbone ; les électrons π migrent sur O et donnent un alcoolate. Une protonation ultérieure produit souvent un alcool. En catalyse acide, protoner d’abord l’oxygène peut accroître l’électrophilie du carbone, puis le nucléophile attaque ; le bilan dépend du réactif.'),
      s('Aldéhydes et cétones', 'Un aldéhyde porte un H et un groupe carboné ; une cétone porte deux groupes carbonés. Les aldéhydes sont généralement plus réactifs en addition nucléophile : ils sont moins encombrés et leurs groupes alkyles stabilisent moins la charge partielle positive du carbone que dans les cétones.'),
      s('Du réactif au produit', 'Les hydrures réducteurs ajoutent un H⁻ équivalent puis protonation : un aldéhyde conduit à un alcool primaire, une cétone à un alcool secondaire. Les réactifs organométalliques peuvent former une liaison C–C puis un alcool après hydrolyse. Le cyanure donne un cyanohydrine. Vérifier toujours le nombre de groupes carbonés.'),
      s('Addition ou substitution acyle', 'Les aldéhydes et cétones n’ont pas de bon groupe partant lié au carbone carbonylé ; l’addition conduit à un intermédiaire qui est généralement protoné. Les dérivés d’acide carboxylique peuvent éliminer un groupe partant après addition : le bilan devient une substitution acyle. Cette différence explique des familles de réactivité distinctes.'),
    ],
    trap: 'L’addition sur un aldéhyde ou une cétone ne remplace pas automatiquement l’oxygène carbonylé : l’oxygène devient souvent alcool après protonation.',
    recall: 'Un réactif carboné s’ajoute à une cétone puis le mélange est hydrolysé. Quel type de produit obtient-on ?',
    answer: 'Une liaison C–C est formée au carbone carbonylé ; après protonation de l’alcoolate, on obtient généralement un alcool tertiaire si la cétone a deux groupes carbonés distincts et que le réactif apporte le troisième.',
    source: oc + '19-4-nucleophilic-addition-reactions-of-aldehydes-and-ketones',
    glossary: [['Carbonyle', 'Motif C=O polarisé, avec carbone électrophile et oxygène nucléophile/base.'], ['Alcoolate', 'Anion portant O⁻, souvent intermédiaire après addition nucléophile.'], ['Cyanohydrine', 'Produit d’addition de HCN/CN⁻ sur un carbonyle, portant OH et CN sur le même carbone.']]
  }),
  lesson('chem-carboxylic-derivatives-esters', {
    objectives: ['Reconnaître acide carboxylique, ester, amide et anhydride', 'Expliquer l’addition-élimination nucléophile au carbonyle acyle', 'Écrire le bilan d’une estérification ou d’une hydrolyse simple'],
    sections: [
      s('La famille acyle', 'Les acides carboxyliques portent –COOH ; les esters –COOR′ ; les amides –CONR₂ ; les halogénures d’acyle –COX ; les anhydrides associent deux acyles par un oxygène. Le carbone du carbonyle est électrophile, mais la présence d’un substituant pouvant partir ouvre une voie absente des aldéhydes et cétones.'),
      s('Addition puis élimination', 'Le nucléophile attaque le carbone du carbonyle et les électrons π vont vers O, donnant un intermédiaire tétraédrique. Celui-ci rétablit C=O en éliminant un groupe partant. Le bilan est une substitution nucléophile d’acyle. La facilité dépend de l’électrophilie du carbonyle et de la capacité du groupe partant.'),
      s('Transestérification et hydrolyse', 'Un ester réagit avec un alcool pour échanger le groupe –OR′, généralement sous catalyse acide ou basique. L’hydrolyse acide forme acide carboxylique et alcool dans une réaction réversible. L’hydrolyse basique, dite saponification, conduit au carboxylate ; cette déprotonation rend le processus globalement favorable dans les conditions usuelles.'),
      s('Acides, esters et amides en biologie', 'Les liaisons ester relient notamment certains lipides ; les liaisons amide constituent la liaison peptidique des protéines. Leur hydrolyse rompt une liaison C–O ou C–N au niveau acyle et nécessite catalyse et eau. Reconnaître le motif permet d’anticiper les produits, sans confondre une liaison amide avec une amine.'),
      s('Nomenclature fonctionnelle', 'L’acide carboxylique est souvent la fonction prioritaire dans un composé polyfonctionnel et donne le suffixe acide …oïque. Les esters se nomment en distinguant partie issue de l’alcool et partie carboxylate. Les amides emploient le suffixe –amide ; les substituants portés par l’azote sont indiqués comme tels. Vérifier les locants et la chaîne principale.'),
    ],
    trap: 'Une estérification acide est souvent un équilibre, tandis que la saponification forme un carboxylate qui n’est pas simplement l’acide carboxylique neutre.',
    recall: 'Pourquoi un dérivé d’acide carboxylique subit-il souvent une substitution acyle alors qu’un aldéhyde donne surtout une addition ?',
    answer: 'Après addition, le dérivé peut rétablir C=O en expulsant un groupe partant. Dans l’aldéhyde, H ou un groupe carboné ne part pas comme un groupe partant usuel : l’intermédiaire est plutôt protoné.',
    source: oc + '21-2-nucleophilic-acyl-substitution-reactions',
    glossary: [['Groupe acyle', 'Fragment R–C(=O)–.'], ['Saponification', 'Hydrolyse basique d’un ester conduisant notamment à un carboxylate et un alcool.'], ['Liaison peptidique', 'Liaison amide entre le carboxyle d’un acide aminé et l’amine du suivant.']]
  })
]

const q = (course: string, n: number, topicOrPrompt: string, promptOrOptions: string | string[], optionsOrCorrect: string[] | number[], correctOrWhy: number[] | string[], finalWhy?: string[]): Question => {
  const hasTopic = typeof promptOrOptions === 'string'
  const prompt = hasTopic ? promptOrOptions : topicOrPrompt
  const options = hasTopic ? optionsOrCorrect as string[] : promptOrOptions
  const correct = hasTopic ? correctOrWhy as number[] : optionsOrCorrect as number[]
  const why = hasTopic ? finalWhy! : correctOrWhy as string[]
  return { id: `${course}-q${n}`, course, topic: 'Chimie', prompt, options, correct, why, difficulty: n < 3 ? 'essentiel' : 'application' }
}
export const chemistryOrganicQuestions: Question[] = [
  q('chem-organic-functions-isomery',1,'Quel groupe fonctionnel caractérise un ester ?', ['R–COO–R′','R–O–R′','R–CO–R′','R–CHO'],[0],['Un ester comporte le motif acyle–O–alkyle.','C’est un éther sans carbonyle.','C’est une cétone.','C’est un aldéhyde.']),
  q('chem-organic-functions-isomery',2,'Quelle différence distingue aldéhyde et cétone ?', ['L’aldéhyde porte un H sur le carbone carbonylé','La cétone porte toujours OH','L’aldéhyde ne contient pas C=O','La cétone est toujours cyclique'],[0],['C’est la différence de connectivité au carbone du carbonyle.','OH n’est pas le critère définitoire.','Les deux ont un carbonyle.','La cyclicité n’est pas obligatoire.']),
  q('chem-organic-functions-isomery',3,'Deux composés ont même formule brute mais des connexions atomiques différentes. Ce sont :',['Des isomères de constitution','Des isotopes','Des conformères nécessairement','Des énantiomères nécessairement'],[0],['Même formule, connectivité différente : isomérie de constitution.','Les isotopes diffèrent par le nombre de neutrons.','Les conformères gardent la connectivité et changent par rotation.','Les énantiomères sont des stéréoisomères miroir.']),
  q('chem-organic-functions-isomery',4,'Dans une formule topologique, que représente généralement un sommet non marqué ?', ['Un atome de carbone','Un atome d’oxygène','Un proton libre','Un ion métallique'],[0],['Les sommets et extrémités non étiquetés sont des carbones.','Les hétéroatomes sont écrits.','Les hydrogènes sont implicites sur les carbones.','Aucun métal n’est implicite.']),
  q('chem-organic-functions-isomery',5,'Quelle fonction porte le motif R–CONH₂ ?', ['Amide','Amine','Ester','Éther'],[0],['Le carbonyle adjacent à l’azote définit l’amide.','Une amine n’a pas ce carbonyle acyle adjacent.','Un ester comporte O entre acyle et carbone.','Un éther est R–O–R′.']),
  q('chem-organic-stereochemistry-conformations',1,'Quelle projection regarde le long d’une liaison C–C ?', ['Newman','Fischer uniquement','Lewis','Haworth uniquement'],[0],['Newman place le carbone avant en point et l’arrière en cercle.','Fischer est une représentation conventionnelle différente.','Lewis montre surtout les connexions et doublets.','Haworth représente certains cycles.']),
  q('chem-organic-stereochemistry-conformations',2,'Pour l’éthane, quelle conformation est généralement la plus stable ?', ['Décalée','Éclipsée','Les deux ont une énergie infinie','Aucune rotation possible'],[0],['La conformation décalée réduit la tension de torsion.','Elle est généralement plus énergétique.','Les conformères accessibles ont une énergie finie.','La rotation autour de C–C est possible.']),
  q('chem-organic-stereochemistry-conformations',3,'Dans le butane, que décrit une conformation anti ?', ['Groupes méthyle séparés par un angle dièdre de 180°','Groupes méthyle superposés','Une double liaison C=C','Deux carbones chiraux'],[0],['Anti place les groupes volumineux à 180°.','Ils seraient éclipsés à 0°.','La rotation concerne ici une liaison simple.','La conformation seule ne définit pas de centres chiraux.']),
  q('chem-organic-stereochemistry-conformations',4,'Lors d’un basculement de chaise du cyclohexane, quel changement a lieu ?', ['Axial devient équatorial et inversement','Haut devient toujours bas','La connectivité change','Un carbone est éliminé'],[0],['Le basculement échange les positions axiale et équatoriale.','L’orientation haut/bas est conservée.','Aucune liaison n’est rompue.','Le squelette reste identique.']),
  q('chem-organic-stereochemistry-conformations',5,'Quelle conformation est souvent favorisée pour un substituant volumineux sur cyclohexane ?', ['Équatoriale','Axiale','Eclipsée','Hors du cycle'],[0],['Elle réduit les interactions 1,3-diaxiales.','Elle augmente l’encombrement axial.','Le terme éclipsé décrit une rotation de liaison ouverte.','Le substituant reste lié au cycle.']),
  q('chem-organic-chirality-enantiomers-diastereomers',1,'Un carbone tétraédrique lié à quatre substituants différents est généralement :',['Un centre stéréogène','Un groupe partant','Un ion commun','Un carbone carbonylé plan'],[0],['L’échange de deux substituants produit souvent un stéréoisomère.','Ce n’est pas un groupe qui quitte.','Il ne s’agit pas d’un ion.','Un carbone carbonylé est sp², pas tétraédrique.']),
  q('chem-organic-chirality-enantiomers-diastereomers',2,'Comment attribue-t-on les priorités CIP ?', ['Par numéro atomique, puis comparaison successive en cas d’égalité','Par masse totale de la molécule','Toujours par ordre alphabétique des noms','Par sens horaire initial'],[0],['On compare les atomes liés puis les rangs suivants.','La masse moléculaire globale n’est pas la règle.','L’alphabet intervient dans la nomenclature, pas les priorités CIP.','Le sens est déterminé après classement et orientation.']),
  q('chem-organic-chirality-enantiomers-diastereomers',3,'Quelle relation unit deux énantiomères ?', ['Images miroir non superposables','Images identiques superposables','Même formule et connectivité mais nécessairement même configuration','Isomères de constitution'],[0],['C’est leur définition.','Ils ne sont pas superposables.','Leur configuration est opposée à tous les centres correspondants.','Leur connectivité reste la même.']),
  q('chem-organic-chirality-enantiomers-diastereomers',4,'Que signifie la désignation R ?', ['Une configuration absolue définie par les priorités CIP','Une rotation optique forcément positive','Une molécule forcément naturelle','Une liaison réactive'],[0],['R/S décrit la disposition spatiale selon CIP.','Le signe optique n’est pas déduit de R/S.','L’origine naturelle n’est pas impliquée.','R ne marque pas une fonction.']),
  q('chem-organic-chirality-enantiomers-diastereomers',5,'Un mélange équimolaire d’énantiomères est dit :',['Racémique','Mésomère','Diastereomérique pur','Ionique'],[0],['Un mélange 1:1 d’énantiomères est racémique.','Mésomère se rapporte à une délocalisation électronique.','Le mélange contient deux énantiomères.','Aucune charge n’est impliquée.']),
  q('chem-electronic-effects-inductive-mesomeric',1,'D’où part une flèche courbe de mécanisme ?', ['D’une source d’électrons comme un doublet ou une liaison','D’un atome sans électron','Du produit final uniquement','D’un proton toujours'],[0],['Elle montre le déplacement d’une paire d’électrons.','Il faut une source électronique.','La flèche est tracée au cours du mécanisme.','Les protons ne sont pas la seule source.']),
  q('chem-electronic-effects-inductive-mesomeric',2,'Quel effet se transmet surtout par polarisation des liaisons σ ?', ['Effet inductif','Effet mésomère','Effet stérique','Effet isotopique'],[0],['Il se transmet le long des liaisons σ et s’atténue avec la distance.','Le mésomère passe par délocalisation π/conjugaison.','L’encombrement est spatial.','Les isotopes concernent le noyau.']),
  q('chem-electronic-effects-inductive-mesomeric',3,'Que bougent les formes mésomères ?', ['Les électrons, sans déplacer les noyaux','Les atomes du squelette','Les protons toujours','Les molécules entières dans l’espace'],[0],['La résonance décrit la distribution électronique.','La connectivité des noyaux reste identique.','Un proton n’est pas déplacé dans la résonance.','Il ne s’agit pas d’une rotation moléculaire.']),
  q('chem-electronic-effects-inductive-mesomeric',4,'Pourquoi la délocalisation d’une charge peut-elle stabiliser un anion ?', ['Elle répartit la densité électronique sur plusieurs atomes','Elle augmente toujours la charge totale','Elle rompt tous les liens covalents','Elle ajoute un proton'],[0],['Une charge moins localisée est souvent énergétiquement favorable.','La charge totale se conserve.','La délocalisation ne rompt pas toutes les liaisons.','Aucun proton n’est ajouté.']),
  q('chem-electronic-effects-inductive-mesomeric',5,'Quelle propriété décrit l’effet inductif ?', ['Il s’atténue généralement avec la distance','Il exige toujours une double liaison conjuguée','Il déplace les noyaux','Il transforme toute liaison en liaison ionique'],[0],['La polarisation σ décroît le long de la chaîne.','La conjugaison caractérise plutôt la mésomérie.','Les atomes ne changent pas de place.','La polarisation n’implique pas une ionisation complète.']),
  q('chem-reaction-mechanisms-sn1-sn2',1,'SN2','Quel est le nombre d’étapes de base du mécanisme SN2 ?', ['Une étape concertée','Deux étapes avec carbocation','Trois ionisations successives','Aucune formation de liaison'],[0],['Attaque et départ ont lieu dans une même étape.','Cela ressemble au schéma SN1.','Ce n’est pas le mécanisme usuel.','Le nucléophile forme une liaison.']),
  q('chem-reaction-mechanisms-sn1-sn2',2,'Cinétique','Quelle loi correspond au mécanisme SN2 ?', ['v = k[substrat][nucléophile]','v = k[substrat] uniquement','v = k[nucléophile] uniquement','v = k'],[0],['Les deux partenaires interviennent dans l’étape concertée.','C’est la forme usuelle SN1.','Le substrat réactif intervient aussi.','Les concentrations interviennent.']),
  q('chem-reaction-mechanisms-sn1-sn2',3,'Stéréochimie','Quel effet stéréochimique est associé à une SN2 sur un centre chiral ?', ['Inversion de configuration géométrique par attaque arrière','Racémisation complète obligatoire','Rétention obligatoire','Aucun changement de liaison'],[0],['Le nucléophile attaque du côté opposé au groupe partant.','L’attaque arrière n’est pas un carbocation plan.','Le mécanisme n’impose pas la rétention.','La liaison au centre est remplacée.']),
  q('chem-reaction-mechanisms-sn1-sn2',4,'SN1','Quel intermédiaire caractérise généralement SN1 ?', ['Carbocation','Carbanion','Radical oxygène obligatoire','État solide'],[0],['Le départ du groupe partant forme le carbocation.','Un carbanion n’est pas le schéma SN1.','Cela n’est pas une exigence.','La réaction se déroule en solution typiquement.']),
  q('chem-reaction-mechanisms-sn1-sn2',5,'Substrat','Pourquoi un substrat tertiaire convient-il mieux souvent à SN1 qu’un primaire ?', ['Il stabilise davantage le carbocation intermédiaire','Il est moins substitué','Il empêche toute ionisation','Il supprime le groupe partant'],[0],['Les groupes alkyles contribuent à stabiliser la charge positive.','Un primaire est moins substitué.','Un tertiaire favorise l’ionisation relative.','Le groupe partant reste requis.']),
  q('chem-reaction-mechanisms-e1-e2',1,'E2','Que se passe-t-il dans une étape E2 ?', ['Arrachement du Hβ et départ du groupe partant de façon concertée','Formation préalable d’un carbocation libre','Addition d’eau sur un alcène','Transfert d’électron au noyau'],[0],['La base arrache H pendant que X part et C=C se forme.','Cela définit plutôt E1.','C’est une réaction distincte.','L’élimination ne modifie pas le noyau.']),
  q('chem-reaction-mechanisms-e1-e2',2,'Cinétique','Quelle est la loi cinétique usuelle de E1 ?', ['v = k[substrat]','v = k[substrat][base]','v = k[base]²','v = 0'],[0],['La première ionisation lente dépend du substrat.','C’est l’expression usuelle de E2.','La base intervient après l’étape lente.','La réaction a une vitesse non nulle.']),
  q('chem-reaction-mechanisms-e1-e2',3,'Géométrie','Quelle disposition facilite souvent une élimination E2 ?', ['Hβ et groupe partant anti-périplanaires','Hβ et groupe partant sur des carbones non voisins','Deux doubles liaisons alignées','Groupe partant libre sans substrat'],[0],['L’alignement anti favorise le recouvrement orbital.','L’élimination exige des carbones voisins.','Ce n’est pas le critère.','Le groupe partant doit être lié au substrat.']),
  q('chem-reaction-mechanisms-e1-e2',4,'Produit','Quel type de produit se forme lors d’une élimination β classique ?', ['Alcène','Alcool saturé exclusivement','Amide','Sel métallique toujours'],[0],['La nouvelle liaison π forme une double liaison C=C.','L’eau n’est pas nécessairement ajoutée.','Aucun azote imposé.','Aucun métal imposé.']),
  q('chem-reaction-mechanisms-e1-e2',5,'Sélectivité','La règle de Zaïtsev est-elle universelle ?', ['Non, géométrie et encombrement peuvent changer le produit majoritaire','Oui, quelle que soit la base','Elle ne concerne que les acides','Elle prédit le pH'],[0],['C’est une tendance soumise à la structure et aux conditions.','Une base encombrée et la géométrie peuvent la modifier.','Elle concerne souvent la distribution des alcènes.','Elle n’est pas acido-basique quantitative.']),
  q('chem-alkenes-electrophilic-addition',1,'Électrons π','Pourquoi un alcène peut-il réagir comme nucléophile ?', ['Sa liaison π riche en électrons peut donner un doublet à un électrophile','Il porte nécessairement une charge négative entière','Il est toujours un acide fort','Il n’a pas d’électrons de valence'],[0],['Le nuage π est disponible et polarisable.','Un alcène neutre n’est pas forcément chargé.','Ce n’est pas la définition.','Il contient des électrons de valence.']),
  q('chem-alkenes-electrophilic-addition',2,'Mécanisme','Dans l’addition ionique de HBr au propène, quelle espèce se forme après protonation initiale ?', ['Un carbocation','Un carbanion','Un ester','Un radical obligatoire'],[0],['La protonation de la double liaison génère un carbocation.','Le mécanisme est électrophile.','Aucun carbonyle n’intervient.','Pas de radical dans le mécanisme usuel.']),
  q('chem-alkenes-electrophilic-addition',3,'Markovnikov','La règle de Markovnikov pour HX sur un alcène asymétrique reflète généralement :',['La formation préférentielle du carbocation le plus stable','La masse de l’halogène uniquement','Le pH du produit final','La conservation de la géométrie initiale seulement'],[0],['La première étape favorise un intermédiaire mieux stabilisé.','La masse atomique ne décide pas la régiosélectivité.','Le pH n’explique pas le mécanisme.','La double liaison est consommée.']),
  q('chem-alkenes-electrophilic-addition',4,'Réactivité','Quelles liaisons sont formées globalement dans une addition sur C=C ?', ['Deux liaisons σ nouvelles, la liaison π est consommée','Deux liaisons π nouvelles','Aucune liaison nouvelle','Une liaison au noyau'],[0],['Les deux atomes ajoutés se lient aux deux carbones de l’ancienne double liaison.','Le bilan sature la double liaison.','L’addition forme des liaisons.','Le noyau n’est pas concerné.']),
  q('chem-alkenes-electrophilic-addition',5,'Stéréochimie','Pourquoi une addition via carbocation peut-elle donner plusieurs stéréoisomères ?', ['Le carbocation plan peut être attaqué par ses deux faces','Le carbocation est tétraédrique rigide','Les noyaux se réarrangent toujours','La réaction ne crée jamais de centre stéréogène'],[0],['Les deux faces peuvent être accessibles.','Le carbocation est approximativement plan.','Un réarrangement n’est pas obligatoire.','Un nouveau centre peut être formé.']),
  q('chem-carbonyl-nucleophilic-addition',1,'Polarité','Quel atome du carbonyle est généralement le site électrophile ?', ['Carbone','Oxygène','Hydrogène d’un groupe absent','Aucun atome'],[0],['La liaison C=O est polarisée vers O.','L’oxygène est plus riche en électrons.','Le carbonyle peut ne pas porter cet hydrogène.','Le carbone reçoit le nucléophile.']),
  q('chem-carbonyl-nucleophilic-addition',2,'Mécanisme','Après l’attaque nucléophile sur un carbonyle, quel intermédiaire courant apparaît ?', ['Alcoolate tétraédrique','Carbocation plan stable obligatoire','Alcène','Ion chlorure obligatoire'],[0],['La liaison π se déplace sur O et le carbone devient tétraédrique.','Ce n’est pas le mécanisme courant.','Aucune double liaison C=C n’est formée.','Le chlore n’est pas requis.']),
  q('chem-carbonyl-nucleophilic-addition',3,'Comparaison','Pourquoi les aldéhydes sont-ils souvent plus réactifs que les cétones ?', ['Moindre encombrement et moindre donation alkyle au carbonyle','Présence obligatoire de deux groupes alkyles','Carbone moins électrophile','Absence de groupe carbonyle'],[0],['Les deux facteurs tendent à favoriser l’addition aux aldéhydes.','Un aldéhyde porte un H.','Le carbone est plus accessible et électrophile.','Les deux familles comportent C=O.']),
  q('chem-carbonyl-nucleophilic-addition',4,'Produits','La réduction d’une cétone par un hydrure suivie d’une protonation donne généralement :',['Un alcool secondaire','Un acide carboxylique','Un ester','Un alcène exclusivement'],[0],['Le carbone carbonylé porte deux groupes carbonés ; après ajout de H, alcool secondaire.','Aucune oxydation en acide n’a lieu.','Aucun groupe alkoxy ajouté.','La réduction forme C–H et C–OH.']),
  q('chem-carbonyl-nucleophilic-addition',5,'Addition vs substitution','Pourquoi une addition nucléophile sur un aldéhyde ne se termine-t-elle pas typiquement par expulsion d’un groupe carboné ?', ['Un groupe carboné ou H n’est pas un groupe partant usuel dans ces conditions','Le carbone carbonylé est inerte','L’oxygène n’existe plus','Le nucléophile est toujours un proton'],[0],['Il n’y a pas de groupe partant approprié ; l’alcoolate est protoné.','Le carbonyle réagit.','L’oxygène devient souvent alcoolate puis OH.','Un nucléophile peut être un anion ou une molécule neutre.']),
  q('chem-carboxylic-derivatives-esters',1,'Fonctions','Quel motif caractérise un amide ?', ['R–C(=O)–N','R–C(=O)–O–R′','R–O–R′','R–CHO'],[0],['Un carbonyle lié à un azote.','C’est un ester.','C’est un éther.','C’est un aldéhyde.']),
  q('chem-carboxylic-derivatives-esters',2,'Mécanisme','Quelle séquence décrit la substitution nucléophile d’acyle ?', ['Addition au carbonyle puis élimination d’un groupe partant','Substitution directe du noyau atomique','Protonation sans changement de liaison','Radicalisation obligatoire'],[0],['L’intermédiaire tétraédrique se reforme en C=O avec départ d’un substituant.','Le noyau atomique reste inchangé.','Une liaison est transformée.','Le mécanisme ionique usuel n’exige pas de radical.']),
  q('chem-carboxylic-derivatives-esters',3,'Saponification','Quel produit ionique est formé lors de l’hydrolyse basique d’un ester ?', ['Carboxylate','Carbocation','Peroxyde','Aldéhyde nécessairement'],[0],['Le milieu basique déprotone l’acide formé en carboxylate.','Pas de carbocation dans le bilan.','Aucun peroxyde.','L’hydrolyse donne carboxylate et alcool.']),
  q('chem-carboxylic-derivatives-esters',4,'Biologie','Quelle liaison unit deux résidus d’acides aminés dans une chaîne peptidique ?', ['Liaison amide','Liaison ester','Liaison éther','Liaison ionique obligatoire'],[0],['La liaison peptidique est une liaison amide.','Un ester relie un oxygène à un acyle et un alkyle.','Ce n’est pas un éther.','La liaison covalente peptidique est une amide.']),
  q('chem-carboxylic-derivatives-esters',5,'Équilibre','Pourquoi une estérification acide peut-elle nécessiter un déplacement d’équilibre ?', ['La réaction est réversible et produit de l’eau','Elle est toujours instantanée et totale','Elle ne forme jamais d’eau','L’équilibre n’existe pas en chimie organique'],[0],['La réaction acide + alcool ⇌ ester + eau est réversible.','Le rendement dépend des conditions.','L’eau est un produit.','Les équilibres sont communs en chimie organique.'])
]
