import type { Course } from '../../curriculum'
import type { Question } from '../../questions'
import { canonicalCourses } from '../../taxonomy/canonicalCourses'

const metadata = new Map(canonicalCourses.filter(item => item.subject === 'Santé publique').map(item => [item.id, item]))
const base = 'https://openstax.org/books/introductory-statistics/pages/'
type Draft = { objectives: string[]; sections: Course['sections']; trap: string; recall: string; answer: string; source: string; learning?: Course['learning']; caseStudy: NonNullable<Course['caseStudy']>; glossary: NonNullable<Course['glossary']> }
const s = (title: string, text: string, bullets?: string[]) => ({ title, text, ...(bullets ? { bullets } : {}) })
function course(id: string, d: Draft): Course {
  const c = metadata.get(id)
  if (!c) throw new Error(`Chapitre canonique de santé publique introuvable : ${id}`)
  return { id, title: c.title, category: c.subject, tag: c.module, minutes: 14, structure: null,
    objectives: d.objectives, sections: d.sections, trap: d.trap, recall: d.recall, answer: d.answer,
    source: base + d.source, sources: [{ label: 'OpenStax · Introductory Statistics', url: base + d.source }],
    prerequisites: ['Proportions et taux', 'Plans d’étude et tests diagnostiques'],
    ...(d.learning ? { learning: d.learning } : {}), glossary: d.glossary, caseStudy: d.caseStudy,
    review: { status: 'unreviewed', updatedAt: '2026-09-23', sourcesUpdatedAt: '2026-09-23' } }
}
export const publicHealthCourses: Course[] = [
  course('public-epidemiology', {
    objectives: ['Distinguer incidence et prévalence', 'Calculer un taux sur une période définie', 'Interpréter les mesures selon population et temps'],
    sections: [
      s('Population et événement de santé', 'L’épidémiologie étudie la distribution des états de santé dans les populations et leurs déterminants, afin d’informer prévention et contrôle. Toute mesure exige de définir cas, population à risque, période, territoire et méthode de collecte. Un changement de définition de cas ou de dépistage peut modifier les nombres observés sans changement biologique équivalent.'),
      s('Prévalence', 'La prévalence ponctuelle est la proportion de personnes ayant une maladie à une date donnée : cas existants/population étudiée. La prévalence de période inclut les personnes atteintes durant un intervalle défini. Elle dépend de l’incidence, de la durée de maladie, de la survie et de la détection ; elle n’est pas un risque instantané de développer la maladie.'),
      s('Incidence cumulée', 'L’incidence cumulée rapporte les nouveaux cas apparus pendant une période au nombre de personnes initialement à risque. Elle estime un risque dans une population suivie sur une durée spécifiée. Les pertes de suivi, entrées tardives et événements concurrents compliquent l’interprétation, surtout quand les durées d’observation diffèrent.'),
      s('Taux d’incidence', 'Le taux d’incidence divise les nouveaux cas par le temps-personne à risque accumulé. Il a la dimension inverse d’un temps et s’interprète comme une vitesse de survenue, pas directement comme une probabilité. Deux taux ne sont comparables que si définition des cas, période, population et méthode de calcul sont adéquatement alignées.'),
      s('Mortalité et létalité', 'Le taux de mortalité rapporte les décès à une population et une durée ; il peut être brut ou standardisé selon âge. La létalité est la proportion de cas diagnostiqués qui décèdent d’une maladie sur une durée ou dans une cohorte définie. Elle dépend de la gravité, du diagnostic et de la prise en charge et se distingue du risque de décès dans la population générale.'),
    ], trap: 'La prévalence est une proportion de cas existants ; le taux d’incidence mesure la vitesse d’apparition de nouveaux cas par temps-personne.', recall: 'Une cohorte observe 20 nouveaux cas pendant 2 000 personnes-années. Quel est le taux d’incidence ?', answer: '20/2 000 = 0,01 cas par personne-année, soit 10 cas pour 1 000 personnes-années.', source: '1-3-data-collection-experiment-and-sampling', learning: { formula: { label: 'Incidence', expression: 'Incidence cumulée = nouveaux cas / personnes à risque au départ ; taux = nouveaux cas / temps-personne', explanation: 'La première mesure un risque sur une période ; le second rapporte les événements au temps observé.' }, comparison: { headers: ['Mesure', 'Numérateur', 'Dénominateur'], rows: [['Prévalence', 'Cas existants', 'Population à une date ou période'], ['Incidence cumulée', 'Nouveaux cas', 'Personnes initialement à risque'], ['Taux d’incidence', 'Nouveaux cas', 'Temps-personne à risque'], ['Létalité', 'Décès parmi les cas', 'Cas atteints définis']] }, example: { prompt: '20 cas apparaissent sur 2 000 personnes-années.', steps: ['Calculer 20 ÷ 2 000 = 0,01.', 'Exprimer éventuellement pour 1 000 personnes-années.'], result: '10 cas pour 1 000 personnes-années.' }, errors: [{ title: 'Interpréter un taux comme un pourcentage', detail: 'Un taux a une unité de temps au dénominateur ; il ne devient une probabilité qu’avec un modèle et un horizon spécifiés.' }] }, glossary: [['Personne-temps', 'Somme des durées pendant lesquelles les participants contribuent au temps à risque.'], ['Prévalence', 'Proportion de personnes présentant une maladie dans une population définie.'], ['Standardisation', 'Méthode ajustant une comparaison à une distribution de facteurs, souvent l’âge.']], caseStudy: { prompt: 'Un traitement améliore la survie sans modifier le nombre de nouveaux cas. Quel effet possible sur la prévalence ?', answer: 'La prévalence peut augmenter parce que les personnes vivent plus longtemps avec la maladie, même si l’incidence reste stable.' }
  }),
  course('public-screening', {
    objectives: ['Définir le dépistage et le distinguer du diagnostic', 'Évaluer bénéfices et risques d’un programme', 'Expliquer biais de temps d’avance et surdiagnostic'],
    sections: [
      s('Dépister une population asymptomatique', 'Le dépistage applique un test à des personnes sans symptômes pour identifier celles qui pourraient bénéficier d’une évaluation plus poussée. Un test positif ne pose pas le diagnostic ; une étape confirmatoire et une prise en charge doivent être définies. Le dépistage organisé concerne une population et un programme, pas seulement un test isolé.'),
      s('Critères d’un programme', 'Un programme se justifie davantage si le problème est important, son histoire naturelle comprise, une phase détectable existe, le test est acceptable et suffisamment performant, et un traitement plus précoce améliore les résultats. Il faut disposer d’un parcours diagnostique, de ressources, d’assurance qualité et d’une évaluation régulière des bénéfices et dommages.'),
      s('Bénéfices attendus et faux positifs', 'Le dépistage peut réduire la morbidité ou mortalité spécifique si une intervention précoce est efficace. Les faux positifs entraînent anxiété, examens et complications ; les faux négatifs peuvent retarder un diagnostic. Les valeurs prédictives dépendent de la prévalence dans le groupe dépisté et du seuil choisi.'),
      s('Biais de temps d’avance et de durée', 'Le biais de temps d’avance fait paraître la survie depuis le diagnostic plus longue simplement parce que le diagnostic est posé plus tôt, sans retarder le décès. Le biais de durée favorise la détection de maladies à évolution lente, présentes plus longtemps dans la fenêtre de dépistage. Comparer mortalité ou événements de population aide à éviter une conclusion naïve fondée sur la survie après diagnostic.'),
      s('Surdiagnostic et décision partagée', 'Le surdiagnostic identifie une anomalie qui n’aurait pas causé de symptômes ou de décès pendant la vie de la personne. Il peut entraîner traitements inutiles et effets indésirables. La décision de dépister dépend du rapport bénéfice-risque, de l’âge, des préférences, des comorbidités et des recommandations actualisées ; une information équilibrée est essentielle.'),
    ], trap: 'Une augmentation de survie mesurée depuis le diagnostic ne prouve pas à elle seule que le dépistage réduit la mortalité.', recall: 'Quelle différence entre faux positif et surdiagnostic ?', answer: 'Un faux positif correspond à un test positif sans maladie selon la référence ; un surdiagnostic détecte une vraie anomalie qui n’aurait pas causé de dommage clinique.', source: '8-4-calc-the-test-statistic', glossary: [['Surdiagnostic', 'Détection d’une maladie réelle qui n’aurait jamais causé de symptôme ou dommage.'], ['Temps d’avance', 'Temps gagné artificiellement entre diagnostic précoce et diagnostic qui aurait été clinique.'], ['Valeur prédictive', 'Probabilité d’un état réel conditionnelle au résultat d’un test.']], caseStudy: { prompt: 'Après mise en place d’un dépistage, la survie à cinq ans après diagnostic augmente, mais la mortalité dans la population ne change pas. Quelle explication est possible ?', answer: 'Un biais de temps d’avance ou un surdiagnostic peut augmenter la survie mesurée sans réduire la mortalité de population.' } }),
]
const prompts: Record<string, string[]> = {
  'public-epidemiology': ['Que rapporte une prévalence ponctuelle ?', 'Quel est le dénominateur d’un taux d’incidence ?', 'Un taux d’incidence est-il directement une probabilité ?', 'Que peut faire une survie accrue à la prévalence ?', 'Que signifie une létalité ?'],
  'public-screening': ['Un test de dépistage positif suffit-il pour diagnostiquer ?', 'Qu’est-ce qu’un surdiagnostic ?', 'Quel biais augmente artificiellement la survie mesurée depuis le diagnostic après détection précoce ?', 'Les valeurs prédictives dépendent-elles de la prévalence ?', 'Quel résultat de population est plus informatif qu’une survie post-diagnostic seule ?'],
}
const answers: Record<string, string[]> = {
  'public-epidemiology': ['La proportion de personnes ayant la maladie dans une population à une date donnée.', 'Le temps-personne à risque accumulé.', 'Non, il mesure une vitesse par temps et non un risque sans horizon ni modèle.', 'L’augmenter, car les personnes vivent plus longtemps avec la maladie.', 'La proportion de personnes atteintes qui décèdent de cette maladie dans une cohorte ou période définie.'],
  'public-screening': ['Non, il identifie des personnes nécessitant une évaluation diagnostique.', 'La détection d’une anomalie réelle qui n’aurait jamais causé de dommage clinique.', 'Le biais de temps d’avance.', 'Oui, elles varient notamment avec la prévalence et le seuil du test.', 'La mortalité ou les événements cliniques dans la population ciblée.'],
}
const distractors = ['Elle prouve directement la causalité individuelle.', 'Elle ne nécessite ni définition de population ni période.', 'Elle est toujours identique au taux de mortalité.', 'Elle supprime les faux positifs et le surdiagnostic.']
export const publicHealthQuestions: Question[] = publicHealthCourses.flatMap((c, ci) => prompts[c.id].map((prompt, qi) => {
  const answer = answers[c.id][qi]
  const options = [answer, distractors[(qi + ci) % 4], distractors[(qi + ci + 1) % 4], distractors[(qi + ci + 2) % 4]]
  return { id: `${c.id}-q${qi + 1}`, course: c.id, topic: c.category, prompt, options, correct: [0],
    why: options.map((option, oi) => oi === 0 ? answer : `${option} Cette proposition ne correspond pas à la mesure ou au biais étudié.`), difficulty: qi < 2 ? 'essentiel' as const : 'application' as const, format: 'single' as const }
}))
