import type { Course } from '../../curriculum'
import type { Question } from '../../questions'
import { canonicalCourses } from '../../taxonomy/canonicalCourses'

const metadata = new Map(canonicalCourses.filter(item => item.subject === 'Pharmacologie').map(item => [item.id, item]))
const base = 'https://openstax.org/books/anatomy-and-physiology-2e/pages/'
type Draft = { objectives: string[]; sections: Course['sections']; trap: string; recall: string; answer: string; source: string; learning?: Course['learning']; caseStudy: NonNullable<Course['caseStudy']>; glossary: NonNullable<Course['glossary']> }
const s = (title: string, text: string, bullets?: string[]) => ({ title, text, ...(bullets ? { bullets } : {}) })
function course(id: string, d: Draft): Course {
  const c = metadata.get(id)
  if (!c) throw new Error(`Chapitre canonique de pharmacologie introuvable : ${id}`)
  return { id, title: c.title, category: c.subject, tag: c.module, minutes: 14, structure: null,
    objectives: d.objectives, sections: d.sections, trap: d.trap, recall: d.recall, answer: d.answer,
    source: base + d.source, sources: [{ label: 'OpenStax · Anatomy & Physiology 2e', url: base + d.source }],
    prerequisites: ['Physiologie des systèmes concernés', 'Notions de dose et concentration'],
    ...(d.learning ? { learning: d.learning } : {}), glossary: d.glossary, caseStudy: d.caseStudy,
    review: { status: 'unreviewed', updatedAt: '2026-09-23', sourcesUpdatedAt: '2026-09-23' } }
}
export const pharmacologyCourses: Course[] = [
  course('pharma-receptors', {
    objectives: ['Distinguer affinité et efficacité', 'Interpréter EC50 et Emax', 'Comparer agonistes et antagonistes'],
    sections: [
      s('Cible pharmacologique et liaison', 'Un médicament peut agir sur récepteur, enzyme, canal, transporteur ou autre cible. La liaison réversible dépend de concentration libre, affinité et compétition avec des ligands endogènes. L’occupation d’une cible n’entraîne pas nécessairement un effet proportionnel, car amplification, réserve de récepteurs et couplage intracellulaire interviennent.'),
      s('Affinité et efficacité', 'L’affinité décrit la tendance d’un ligand à se lier à sa cible, souvent caractérisée expérimentalement par Kd ou Ki selon le protocole. L’efficacité décrit sa capacité à activer une réponse après liaison. Un agoniste possède une efficacité positive ; un antagoniste neutre peut se lier sans activer le récepteur et bloquer l’agoniste.'),
      s('Courbe concentration-réponse', 'Une courbe concentration-réponse graduelle relie concentration à effet dans un système. Emax représente l’effet maximal observé et EC50 la concentration donnant la moitié de cet effet dans le modèle. Ces paramètres dépendent du tissu, du protocole et de l’amplification ; EC50 n’est pas toujours égale à Kd.'),
      s('Agonisme partiel et antagonisme', 'Un agoniste partiel produit un effet inférieur à celui d’un agoniste plein même à occupation élevée dans le même système. En présence d’un agoniste plein, il peut en réduire l’effet en occupant des récepteurs. Un antagoniste compétitif déplace souvent la courbe vers des concentrations plus élevées sans changer Emax si l’antagonisme est surmontable ; un antagonisme insurmontable peut réduire Emax.'),
      s('Récepteurs et adaptation', 'Une exposition répétée peut entraîner désensibilisation, internalisation ou régulation du nombre de récepteurs. À l’inverse, une réduction de stimulation peut modifier sensibilité ou expression. Tolérance et dépendance ne se déduisent pas d’un mécanisme récepteur unique ; elles dépendent du médicament, de la durée, du système et de facteurs individuels.'),
    ], trap: 'EC50 mesure une concentration associée à l’effet dans un système donné ; elle ne mesure pas directement l’affinité de liaison.', recall: 'Quelle différence entre affinité et efficacité pharmacologique ?', answer: 'L’affinité décrit la liaison à la cible ; l’efficacité décrit la réponse que le ligand déclenche après liaison.', source: '3-1-the-cell-membrane', learning: { formula: { label: 'Courbe concentration-réponse', expression: 'Effet = Emax · [A]/(EC50 + [A])', explanation: 'Expression simplifiée de type Hill avec coefficient 1 ; l’ajustement réel dépend du système et du modèle.' }, comparison: { headers: ['Ligand', 'Liaison', 'Efficacité intrinsèque'], rows: [['Agoniste plein', 'Oui', 'Élevée dans le système'], ['Agoniste partiel', 'Oui', 'Positive mais moindre'], ['Antagoniste neutre', 'Oui', 'Nulle, bloque un agoniste'], ['Agoniste inverse', 'Oui', 'Réduit une activité constitutive si présente']] }, example: { prompt: 'À [A] = EC50 dans un modèle simple.', steps: ['Remplacer [A] par EC50.', 'Effet = Emax·EC50/(EC50+EC50).'], result: 'L’effet vaut Emax/2.' }, errors: [{ title: 'Assimiler Kd et EC50', detail: 'Kd décrit la liaison à l’équilibre ; EC50 décrit une concentration produisant un effet, influencé par la transduction et les réserves de récepteurs.' }] }, glossary: [['Affinité', 'Propension d’un ligand à se lier à une cible.'], ['Efficacité', 'Capacité à produire une réponse après liaison.'], ['Antagoniste compétitif', 'Ligand qui concurrence un agoniste à une cible et peut être déplacé selon le modèle.']], caseStudy: { prompt: 'Deux ligands occupent le même récepteur ; l’un produit un effet maximal inférieur à l’autre même à forte concentration. Quelle notion décrit cette différence ?', answer: 'Une efficacité intrinsèque plus faible, compatible avec un agoniste partiel.' }
  }),
  course('pharma-safety', {
    objectives: ['Distinguer effet indésirable et interaction pharmacocinétique', 'Relier marge thérapeutique à la surveillance', 'Identifier facteurs qui modifient l’exposition au médicament'],
    sections: [
      s('Effet recherché et effet indésirable', 'Un médicament peut produire des effets non souhaités à dose thérapeutique ou lors d’un surdosage. L’évaluation tient compte de gravité, fréquence, causalité, dose, délai et facteurs du patient. Un effet temporellement associé n’est pas automatiquement causé par le médicament ; d’autres explications et la qualité des données comptent.'),
      s('Pharmacocinétique des interactions', 'Une interaction pharmacocinétique modifie absorption, distribution, métabolisme ou élimination. Un inhibiteur enzymatique peut augmenter l’exposition d’un substrat ; un inducteur peut la diminuer après un délai lié au renouvellement des enzymes. Les interactions avec transporteurs, aliments, pH gastrique ou fonction rénale peuvent également modifier concentrations.'),
      s('Interactions pharmacodynamiques', 'Une interaction pharmacodynamique survient lorsque deux agents influencent le même système physiologique ou des voies convergentes, sans nécessaire changement de concentration. Les effets peuvent s’additionner, se potentialiser ou s’opposer. Une association de médicaments sédatifs peut accroître une dépression du système nerveux central ; l’importance dépend des doses et du contexte.'),
      s('Marge thérapeutique', 'La fenêtre thérapeutique sépare les expositions généralement associées à l’effet recherché et celles associées à une toxicité inacceptable. Pour des médicaments à marge étroite, variations modestes d’exposition ou d’observance peuvent nécessiter surveillance biologique, clinique ou adaptation individualisée. Aucun seuil universel ne remplace les recommandations propres au médicament.'),
      s('Vulnérabilité et prévention', 'Âge, grossesse, poids, génétique, fonction hépatique et rénale, comorbidités et polymédication modifient réponse et risque. Réconcilier médicaments prescrits et produits en vente libre, préciser les symptômes d’alerte, adapter les doses et documenter les allergies réduisent certains risques. Un effet grave suspecté justifie un avis médical rapide.'),
    ], trap: 'Une interaction peut modifier l’effet sans modifier la concentration, et une variation de concentration n’entraîne pas toujours une toxicité clinique.', recall: 'Que peut faire un inhibiteur enzymatique à l’exposition d’un médicament substrat ?', answer: 'En diminuant son métabolisme, il peut augmenter la concentration et l’exposition du substrat, avec un effet dépendant de la voie et du contexte.', source: '3-6-transport-of-substances-across-the-cell-membrane', glossary: [['Pharmacocinétique', 'Devenir du médicament dans l’organisme : absorption, distribution, métabolisme, élimination.'], ['Pharmacodynamie', 'Effets du médicament et mécanismes reliant exposition à réponse.'], ['Marge thérapeutique', 'Écart entre expositions efficaces et expositions associées à toxicité.']], caseStudy: { prompt: 'Un patient sous anticoagulant commence un inhibiteur d’une enzyme qui métabolise le traitement. Quel risque pharmacocinétique faut-il envisager ?', answer: 'Une exposition accrue au médicament et donc un risque hémorragique potentiel ; vérifier l’interaction précise, la dose, les paramètres de surveillance et demander un avis professionnel.' } }),
  course('pharma-therapeutic-drug-monitoring', {
    objectives: ['Définir dose, concentration et réponse', 'Interpréter une relation dose-effet', 'Expliquer les limites de l’index thérapeutique'],
    sections: [
      s('Dose et exposition', 'La dose administrée ne correspond pas directement à la concentration au site d’action. Absorption, biodisponibilité, distribution, clairance, intervalle d’administration et observance déterminent l’exposition. Une même dose produit des concentrations différentes selon patient, voie, fonction d’organes et interactions.'),
      s('Réponse graduelle et quantale', 'Une relation graduelle mesure l’intensité d’un effet chez un sujet ou système ; une relation quantale décrit la proportion d’une population atteignant un critère défini. ED50 peut désigner dose efficace médiane dans une population, tandis qu’EC50 concerne une concentration d’effet dans un système. Toujours préciser l’unité et le contexte.'),
      s('Dose efficace et toxique', 'TD50 ou LD50 sont des repères expérimentaux de dose produisant toxicité ou létalité dans 50 % d’une population animale ou modèle, et ne sont pas des seuils individuels sûrs. L’écart entre courbes d’efficacité et toxicité informe sur la sécurité populationnelle, mais la gravité des effets, leur variabilité et l’incertitude restent essentielles.'),
      s('Index et fenêtre thérapeutique', 'L’index thérapeutique est souvent présenté comme TD50/ED50, mais cet indicateur simplifie des distributions d’effets. Une fenêtre thérapeutique décrit plus directement une plage d’exposition visée. La surveillance thérapeutique peut être utile lorsque relation exposition-réponse est prévisible et marge étroite ; l’échantillon doit être interprété au bon moment.'),
      s('Choix et adaptation de dose', 'La dose initiale, l’intervalle, la dose de charge et la titration dépendent de demi-vie, cible, urgence et tolérance. Une réponse clinique insuffisante peut refléter mauvaise adhésion, diagnostic différent, interaction ou exposition basse, pas seulement une dose trop faible. L’adaptation se fait selon recommandations, efficacité observée et risques.'),
    ], trap: 'ED50 d’une population n’est pas la dose efficace garantie pour un individu donné.', recall: 'Pourquoi une dose identique ne garantit-elle pas une concentration identique chez deux patients ?', answer: 'Absorption, distribution, métabolisme, élimination, interactions, génétique, âge et fonction d’organes peuvent différer.', source: '3-5-passive-transport', glossary: [['ED50', 'Dose efficace médiane selon un critère et une population définis.'], ['TD50', 'Dose produisant une toxicité définie chez 50 % d’une population expérimentale.'], ['Titration', 'Ajustement progressif de dose selon réponse et tolérance.']], caseStudy: { prompt: 'Deux patients prennent la même dose, mais l’un a une insuffisance rénale. Quel changement pharmacocinétique est à évaluer ?', answer: 'Une diminution de clairance rénale peut augmenter l’exposition à un médicament ou métabolite éliminé par le rein ; l’ajustement dépend de la molécule et du suivi.' } }),
]
const prompts: Record<string, string[]> = {
  'pharma-receptors': ['Que décrit l’affinité d’un ligand ?', 'Que représente l’EC50 dans une courbe graduelle simple ?', 'Un antagoniste neutre active-t-il nécessairement son récepteur ?', 'Quelle distinction entre agoniste partiel et agoniste plein ?', 'EC50 est-elle toujours égale à Kd ?'],
  'pharma-safety': ['Que peut produire l’inhibition d’une enzyme métabolisant un médicament substrat ?', 'Une interaction pharmacodynamique change-t-elle nécessairement la concentration ?', 'Qu’est-ce qu’une marge thérapeutique étroite implique souvent ?', 'Citez un exemple de facteur patient modifiant l’exposition.', 'Un effet indésirable temporellement associé est-il forcément causé par le médicament ?'],
  'pharma-therapeutic-drug-monitoring': ['La dose administrée est-elle égale à l’exposition au site d’action ?', 'Que décrit l’ED50 ?', 'L’index thérapeutique est-il un seuil individuel de sécurité ?', 'Quel est l’intérêt d’une titration ?', 'Quel facteur peut nécessiter adaptation d’un médicament éliminé par le rein ?'],
}
const answers: Record<string, string[]> = {
  'pharma-receptors': ['La tendance d’un ligand à se lier à sa cible.', 'La concentration donnant la moitié de l’effet maximal dans le modèle considéré.', 'Non, il peut se lier sans activer et bloquer l’agoniste.', 'L’agoniste partiel produit un effet maximal inférieur dans le même système.', 'Non, EC50 dépend aussi de la transduction et du système ; Kd caractérise la liaison.'],
  'pharma-safety': ['Elle peut réduire sa clairance métabolique et augmenter son exposition.', 'Non, elle peut modifier l’effet par convergence physiologique sans modifier la concentration.', 'Une surveillance clinique ou biologique plus attentive et une adaptation prudente.', 'Âge, fonction rénale ou hépatique, génétique, grossesse ou interaction.', 'Non, la causalité doit être évaluée parmi d’autres explications.'],
  'pharma-therapeutic-drug-monitoring': ['Non, la pharmacocinétique et les caractéristiques du patient déterminent l’exposition.', 'La dose efficace médiane pour un critère défini dans une population.', 'Non, c’est un repère populationnel simplifié, pas une garantie individuelle.', 'Ajuster progressivement la dose selon bénéfice et tolérance.', 'Une insuffisance rénale peut réduire la clairance et accroître l’exposition.'],
}
const distractors = ['Elle est identique chez tous les patients et toutes les voies.', 'Elle décrit uniquement l’élimination sans effet biologique.', 'Elle supprime les incertitudes et les interactions possibles.', 'Elle indique toujours un effet clinique favorable.']
export const pharmacologyQuestions: Question[] = pharmacologyCourses.flatMap((c, ci) => prompts[c.id].map((prompt, qi) => {
  const answer = answers[c.id][qi]
  const options = [answer, distractors[(qi + ci) % 4], distractors[(qi + ci + 1) % 4], distractors[(qi + ci + 2) % 4]]
  return { id: `${c.id}-q${qi + 1}`, course: c.id, topic: c.category, prompt, options, correct: [0],
    why: options.map((option, oi) => oi === 0 ? answer : `${option} Cette interprétation ne correspond pas au principe pharmacologique évalué.`), difficulty: qi < 2 ? 'essentiel' as const : 'application' as const, format: 'single' as const }
}))
