import type { Course } from '../../curriculum'
import type { Question } from '../../questions'
import { canonicalCourses } from '../../taxonomy/canonicalCourses'

const metadata = new Map(canonicalCourses.filter(item => item.subject === 'Santé, Société, Humanité').map(item => [item.id, item]))
const base = 'https://www.who.int/'
type Draft = { objectives: string[]; sections: Course['sections']; trap: string; recall: string; answer: string; source: string; caseStudy: NonNullable<Course['caseStudy']>; glossary: NonNullable<Course['glossary']> }
const s = (title: string, text: string, bullets?: string[]) => ({ title, text, ...(bullets ? { bullets } : {}) })
function course(id: string, d: Draft): Course {
  const c = metadata.get(id)
  if (!c) throw new Error(`Chapitre canonique de sciences humaines introuvable : ${id}`)
  return { id, title: c.title, category: c.subject, tag: c.module, minutes: 13, structure: null,
    objectives: d.objectives, sections: d.sections, trap: d.trap, recall: d.recall, answer: d.answer,
    source: d.source, sources: [{ label: 'Organisation mondiale de la Santé · Constitution et éthique', url: d.source }],
    prerequisites: ['Notions de santé, maladie et déterminants sociaux', 'Principes de communication et de droit'],
    glossary: d.glossary, caseStudy: d.caseStudy, review: { status: 'unreviewed', updatedAt: '2026-09-23', sourcesUpdatedAt: '2026-09-23' } }
}
export const shsCourses: Course[] = [
  course('ssh-epistemology-medical-concept-normal-pathological', {
    objectives: ['Distinguer modèles biomédical et biopsychosocial', 'Définir santé et maladie comme phénomènes multidimensionnels', 'Relier expérience du patient et données biomédicales'],
    sections: [
      s('Définir la santé avec prudence', 'La définition classique de l’OMS décrit la santé comme un état de complet bien-être physique, mental et social, et non seulement une absence de maladie. Elle fournit une approche large mais soulève des questions sur le caractère idéal ou mesurable du « complet bien-être ». Les usages cliniques et de santé publique doivent préciser le contexte.'),
      s('Modèle biomédical', 'Le modèle biomédical explique les maladies par des mécanismes biologiques, lésions ou dysfonctionnements. Il a permis des diagnostics et traitements efficaces, mais peut sous-estimer vécu, environnement, comportements et organisation des soins lorsqu’il est utilisé seul. Il reste indispensable pour les mécanismes physiopathologiques.'),
      s('Modèle biopsychosocial', 'Le modèle biopsychosocial considère les interactions entre processus biologiques, facteurs psychologiques et conditions sociales. Il n’oppose pas biologie et contexte : les dimensions se modulent mutuellement. Il aide à formuler une situation de soins complète sans réduire la maladie à une seule cause ou nier la réalité d’une lésion.'),
      s('Expérience de maladie', 'Distinguer disease, altération biomédicale ; illness, expérience vécue ; et sickness, reconnaissance sociale d’un rôle de malade, aide à comprendre des décalages entre signes, symptômes et retentissement. Ces termes ne se traduisent pas toujours par une séparation parfaite, mais rappellent les différents niveaux d’analyse.'),
      s('Récit, alliance et décision', 'Écouter le récit, les priorités et les contraintes de la personne complète l’examen et les mesures. Une décision partagée explique options, bénéfices, risques et incertitudes en tenant compte des valeurs du patient. Le langage, la littératie, les rapports de pouvoir et les conditions matérielles influencent la possibilité réelle de participer.'),
    ], trap: 'Le modèle biopsychosocial complète l’analyse biologique ; il ne remplace pas l’examen médical ni les preuves mécanistiques.', recall: 'Comment les notions de disease et illness diffèrent-elles ?', answer: 'Disease désigne l’altération biomédicale définie ; illness décrit l’expérience subjective et le vécu de la maladie par la personne.', source: 'https://www.who.int/about/governance/constitution', glossary: [['Modèle biomédical', 'Approche centrée sur mécanismes biologiques et lésions.'], ['Modèle biopsychosocial', 'Approche considérant les interactions biologiques, psychologiques et sociales.'], ['Décision partagée', 'Processus où professionnel et patient examinent options et préférences ensemble.']], caseStudy: { prompt: 'Deux patients ont la même anomalie biologique mais des retentissements et contraintes très différents. Quel cadre aide à préparer un plan adapté ?', answer: 'Le modèle biopsychosocial et l’écoute du vécu permettent d’intégrer sévérité biologique, symptômes, priorités et contexte social, sans négliger les soins fondés sur les preuves.' } }),
  course('ssh-bioethics-principles-beauchamp-childress', {
    objectives: ['Expliquer autonomie, bienfaisance, non-malfaisance et justice', 'Distinguer consentement libre et information suffisante', 'Appliquer un raisonnement éthique structuré à un cas'],
    sections: [
      s('Autonomie et respect de la personne', 'L’autonomie concerne la capacité à comprendre, délibérer et décider selon ses valeurs, dans un contexte donné. La respecter suppose une information accessible, la possibilité de poser des questions et l’absence de contrainte. Elle n’équivaut pas à laisser seul le patient ni à considérer toute décision comme indépendante de relations et de vulnérabilités.'),
      s('Bienfaisance et non-malfaisance', 'La bienfaisance demande de viser un bénéfice pertinent pour la personne ; la non-malfaisance impose d’éviter ou réduire les dommages prévisibles. Toute intervention comporte des bénéfices et risques dont l’importance dépend des objectifs, de l’incertitude, des alternatives et des conséquences d’une absence d’intervention.'),
      s('Justice et équité', 'La justice concerne distribution équitable des ressources, accès et traitement des personnes. Égalité de traitement ne signifie pas toujours équité : des besoins différents peuvent justifier des adaptations pour assurer une possibilité réelle d’accès. Les critères d’allocation doivent être transparents, pertinents et non discriminatoires.'),
      s('Information et consentement', 'Un consentement valable requiert information pertinente, compréhension, capacité décisionnelle et caractère libre. L’information doit porter sur nature, objectif, bénéfices attendus, risques importants, alternatives et conséquences possibles du refus, dans un langage compréhensible. Le consentement peut être retiré et doit respecter les règles juridiques applicables.'),
      s('Raisonner sur un dilemme', 'Décrire les faits et incertitudes, identifier personnes concernées et valeurs en jeu, examiner options et conséquences, consulter si nécessaire, puis justifier et réévaluer la décision. Les principes ne donnent pas toujours une réponse automatique ; les obligations déontologiques et juridiques locales doivent également être connues.'),
    ], trap: 'L’autonomie n’annule pas les obligations de protection, d’information et de cadre légal ; elle demande une décision comprise et libre.', recall: 'Quels éléments permettent de caractériser un consentement valide ?', answer: 'Une information adaptée, une compréhension suffisante, une capacité à décider et l’absence de contrainte ; le consentement peut être retiré.', source: 'https://www.who.int/about/governance/constitution', glossary: [['Autonomie', 'Possibilité de participer à une décision informée selon ses valeurs.'], ['Bienfaisance', 'Obligation de rechercher le bénéfice pertinent pour la personne.'], ['Justice distributive', 'Répartition équitable des ressources, bénéfices et charges.']], caseStudy: { prompt: 'Un patient refuse un traitement recommandé après explication compréhensible des options. Quelle démarche respecte son autonomie tout en poursuivant les soins ?', answer: 'Vérifier compréhension et capacité, explorer les raisons sans coercition, expliquer conséquences et alternatives, documenter la décision et maintenir une relation de soins respectueuse.' } }),
  course('ssh-doctor-patient-relationship-models', {
    objectives: ['Structurer un entretien centré sur la personne', 'Utiliser questions ouvertes et reformulation', 'Adapter la communication aux besoins et contraintes'],
    sections: [
      s('Installer un cadre relationnel', 'Se présenter, vérifier l’identité et le souhait d’être accompagné, expliquer le déroulement et protéger la confidentialité aident à créer un cadre respectueux. La posture, le ton et l’organisation du lieu influencent l’échange. Des interprètes professionnels sont préférables à des proches pour transmettre une information complexe lorsque la langue constitue une barrière.'),
      s('Commencer par le récit', 'Une question ouverte comme « Qu’est-ce qui vous amène aujourd’hui ? » permet au patient d’exposer sa préoccupation avec ses mots. Laisser un temps de parole initial et repérer attentes et inquiétudes aide à fixer un ordre du jour partagé. Des questions fermées précisent ensuite chronologie, caractéristiques et symptômes associés.'),
      s('Écoute et clarification', 'La reformulation vérifie que le professionnel a compris ; la synthèse regroupe les éléments et invite le patient à corriger. Les questions doivent rester neutres, éviter d’imposer une réponse et explorer contexte, retentissement et priorités. Les silences peuvent laisser le temps de réfléchir et ne sont pas nécessairement un signe d’échec.'),
      s('Expliquer et vérifier la compréhension', 'Présenter une information en petites séquences, limiter le jargon, utiliser des comparaisons prudentes et demander au patient de reformuler avec ses mots permet d’évaluer la compréhension. Le teach-back ne teste pas le patient : il vérifie la clarté de l’explication et signale ce qu’il faut reprendre.'),
      s('Clore et planifier', 'Résumer problèmes et décisions, vérifier les questions restantes, convenir des prochaines étapes et préciser les signes nécessitant un recours rapide. Le plan doit être réalisable au regard des contraintes financières, familiales, cognitives ou matérielles. Documenter clairement et assurer la continuité renforcent sécurité et confiance.'),
    ], trap: 'Le teach-back vérifie la qualité de l’explication et la compréhension ; il ne doit pas devenir un examen humiliant du patient.', recall: 'À quoi sert une question ouverte en début d’entretien ?', answer: 'Elle permet au patient de formuler sa préoccupation, ses attentes et son récit avant que l’entretien ne précise les éléments ciblés.', source: 'https://www.who.int/about/governance/constitution', glossary: [['Question ouverte', 'Question invitant une réponse développée plutôt qu’un oui/non.'], ['Reformulation', 'Restitution de ce qui a été compris afin de vérifier et clarifier.'], ['Teach-back', 'Méthode où la personne reformule un plan pour vérifier la clarté de l’information.']], caseStudy: { prompt: 'Un patient n’arrive pas à expliquer la prise de son traitement après votre explication. Comment utiliser le teach-back sans le mettre en défaut ?', answer: 'Dire que l’on veut vérifier si l’explication était claire, puis demander au patient de décrire comment il prendra le traitement ; corriger et simplifier si nécessaire.' } }),
]
const prompts: Record<string, string[]> = {
  'ssh-epistemology-medical-concept-normal-pathological': ['Que met en relation le modèle biopsychosocial ?', 'Que désigne l’expérience vécue de la maladie ?', 'Le modèle biopsychosocial remplace-t-il l’analyse biologique ?', 'Que permet une décision partagée ?', 'La définition OMS classique se limite-t-elle à l’absence de maladie ?'],
  'ssh-bioethics-principles-beauchamp-childress': ['Quels quatre principes éthiques sont classiquement mobilisés ?', 'L’autonomie signifie-t-elle que le patient doit décider sans soutien ?', 'Quel est un élément nécessaire au consentement libre ?', 'L’équité signifie-t-elle toujours un traitement strictement identique ?', 'Que faire devant un dilemme sans solution automatique ?'],
  'ssh-doctor-patient-relationship-models': ['Quelle forme de question ouvre le récit du patient ?', 'Quel est l’objectif du teach-back ?', 'Qui devrait aider en cas de barrière linguistique pour une information complexe ?', 'Pourquoi reformuler le récit ?', 'Le plan de soins doit-il tenir compte des contraintes concrètes ?'],
}
const answers: Record<string, string[]> = {
  'ssh-epistemology-medical-concept-normal-pathological': ['Les dimensions biologiques, psychologiques et sociales dans leur interaction.', 'L’illness, le vécu subjectif de la maladie.', 'Non, il la complète en intégrant le contexte et l’expérience.', 'Examiner options et préférences du patient avec le professionnel.', 'Non, elle inclut le bien-être physique, mental et social.'],
  'ssh-bioethics-principles-beauchamp-childress': ['Autonomie, bienfaisance, non-malfaisance et justice.', 'Non, elle suppose un soutien informatif et une décision sans contrainte.', 'Une information pertinente et compréhensible, avec possibilité de refuser.', 'Non, l’équité peut demander des adaptations liées aux besoins.', 'Décrire faits et incertitudes, valeurs, options et conséquences, puis justifier la démarche.'],
  'ssh-doctor-patient-relationship-models': ['Une question ouverte.', 'Vérifier si l’explication était claire en demandant une reformulation.', 'Un interprète professionnel.', 'Pour vérifier la compréhension et permettre au patient de corriger.', 'Oui, sinon les décisions convenues risquent de ne pas être applicables.'],
}
const distractors = ['Elle supprime l’obligation d’écouter le patient.', 'Elle rend le contexte social inutile à l’analyse.', 'Elle garantit que toutes les options ont le même bénéfice.', 'Elle remplace les règles juridiques et déontologiques.']
export const shsQuestions: Question[] = shsCourses.flatMap((c, ci) => prompts[c.id].map((prompt, qi) => {
  const answer = answers[c.id][qi]
  const options = [answer, distractors[(qi + ci) % 4], distractors[(qi + ci + 1) % 4], distractors[(qi + ci + 2) % 4]]
  return { id: `${c.id}-q${qi + 1}`, course: c.id, topic: c.category, prompt, options, correct: [0],
    why: options.map((option, oi) => oi === 0 ? answer : `${option} Cette réponse n’est pas conforme au cadre étudié.`), difficulty: qi < 2 ? 'essentiel' as const : 'application' as const, format: 'single' as const }
}))
