import type { Course } from '../../curriculum'
import type { Question } from '../../questions'
import { canonicalCourses } from '../../taxonomy/canonicalCourses'

const base = 'https://openstax.org/books/biology-2e/pages/'
type Draft = { objectives: string[]; sections: Course['sections']; trap: string; recall: string; answer: string; source: string; glossary?: Course['glossary']; caseStudy?: Course['caseStudy'] }
const metadata = new Map(canonicalCourses.filter(item => item.subject === 'Biologie cellulaire').map(item => [item.id, item]))
const lesson = (id: string, d: Draft): Course => {
  const canonical = metadata.get(id)
  if (!canonical) throw new Error(`Chapitre canonique de biologie cellulaire introuvable : ${id}`)
  return { id, title: canonical.title, category: canonical.subject, tag: canonical.module, minutes: 12, structure: null,
    objectives: d.objectives, sections: d.sections, trap: d.trap, recall: d.recall, answer: d.answer,
    source: base + d.source, sources: [{ label: 'OpenStax · Biology 2e', url: base + d.source }],
    prerequisites: ['Organisation de la cellule eucaryote', 'Structure des protéines et des membranes'],
    review: { status: 'unreviewed', updatedAt: '2026-09-23', sourcesUpdatedAt: '2026-09-23' },
    ...(d.glossary ? { glossary: d.glossary } : {}), ...(d.caseStudy ? { caseStudy: d.caseStudy } : {}) }
}
const s = (title: string, text: string, bullets?: string[]) => ({ title, text, ...(bullets ? { bullets } : {}) })

export const architectureDivisionCourses: Course[] = [
  lesson('cell-cycle-phases-control', {
    objectives: ['Situer G1, S, G2, M et G0 dans le cycle', 'Expliquer le rôle cyclines-CDK et des points de contrôle', 'Relier réplication de l’ADN et ségrégation fidèle des chromosomes'],
    sections: [
      s('Interphase et phase M', 'Le cycle cellulaire alterne une interphase — G1, S et G2 — et une phase M. En G1, la cellule croît et intègre des signaux ; en S, l’ADN est répliqué ; en G2, la cellule prépare la division. La phase M comprend mitose et cytocinèse. Certaines cellules entrent en G0, état quiescent variable.'),
      s('Cyclines et CDK', 'Les kinases dépendantes des cyclines (CDK) phosphorylent des protéines cibles lorsqu’elles sont associées à une cycline adaptée. Les concentrations de cyclines varient par synthèse et dégradation ; l’activité des CDK dépend aussi de phosphorylation et d’inhibiteurs. Cette combinaison rend certains événements ordonnés et limite leur déclenchement prématuré.'),
      s('Points de contrôle', 'Le point G1/S évalue notamment conditions de croissance et intégrité de l’ADN avant réplication. Le point G2/M vérifie que la réplication est achevée et qu’aucun dommage majeur ne persiste. Le point d’assemblage du fuseau retient l’anaphase tant que les chromosomes ne sont pas attachés correctement aux microtubules des deux pôles.'),
      s('Réponse aux dommages', 'Des lésions de l’ADN activent des voies de signalisation qui ralentissent ou arrêtent la progression pour permettre réparation. Selon la nature et l’intensité des dommages, une cellule peut entrer en sénescence ou déclencher l’apoptose. Les protéines p53 et RB participent à des contrôles importants, sans agir comme un simple interrupteur isolé.'),
      s('Durée et renouvellement', 'Les phases n’ont pas toutes la même durée et varient selon le type cellulaire et les conditions. Une cellule différenciée peut rester longtemps en G0 ; une cellule épithéliale en renouvellement peut cycler fréquemment. La durée totale n’est donc pas un chronomètre universel et une cellule ne passe pas nécessairement par G0.'),
    ],
    trap: 'La réplication se déroule en phase S, pas pendant la mitose ; la mitose répartit les copies déjà répliquées.',
    recall: 'À quel point de contrôle la cellule s’assure-t-elle que les chromosomes sont attachés au fuseau avant séparation ?',
    answer: 'Au point de contrôle du fuseau, avant l’anaphase. Il retarde la séparation des chromatides tant que les kinétochores ne sont pas correctement attachés.',
    source: '10-2-the-cell-cycle',
    glossary: [['CDK', 'Kinase dont l’activité dépend de l’association à une cycline.'], ['G0', 'État hors cycle prolifératif, pouvant être transitoire ou durable selon les cellules.'], ['Point de contrôle du fuseau', 'Contrôle qui retarde l’anaphase tant que l’attachement chromosomique est incorrect.']]
  }),
  lesson('cell-mitosis-cytokinesis', {
    objectives: ['Décrire les étapes de la mitose et le comportement des chromosomes', 'Expliquer l’attachement des microtubules aux kinétochores', 'Distinguer karyocinèse et cytocinèse'],
    sections: [
      s('Condensation et fuseau', 'Au début de la mitose, les chromosomes répliqués se condensent et les centrosomes organisent les pôles du fuseau. La prométaphase suit la rupture de l’enveloppe nucléaire ; les microtubules explorent l’espace et capturent les kinétochores, complexes assemblés au centromère de chaque chromatide.'),
      s('Métaphase et attachements', 'Les chromosomes s’alignent sur le plan équatorial après attachement bipolaire : les kinétochores des chromatides sœurs sont reliés à des pôles opposés. L’alignement visible est une conséquence de forces et de contrôles, non une étape où les chromosomes cessent d’interagir avec le fuseau.'),
      s('Anaphase', 'La satisfaction du point de contrôle permet l’activation de la séparase et la rupture de la cohésion entre chromatides sœurs. Les chromatides deviennent des chromosomes indépendants et migrent vers les pôles. Les microtubules kinétochoriens raccourcissent ; les pôles peuvent aussi s’éloigner par glissement de microtubules polaires.'),
      s('Télophase et enveloppes', 'Les chromosomes arrivent aux pôles, se décondensent progressivement et de nouvelles enveloppes nucléaires se reforment autour des deux lots. Les noyaux filles rétablissent l’organisation de l’interphase. Les étapes se chevauchent dans le temps ; les schémas en phases servent à décrire des événements dominants.'),
      s('Cytocinèse', 'Dans une cellule animale, un anneau contractile d’actine et de myosine forme un sillon de division qui pince le cytoplasme. Dans une cellule végétale, la paroi rigide empêche ce mécanisme : des vésicules fusionnent au centre pour construire une plaque cellulaire. La cytocinèse partage le cytoplasme après ou pendant la mitose.'),
    ],
    trap: 'La métaphase n’est pas le moment où l’ADN est répliqué : elle suit la phase S et organise la séparation des chromatides.',
    recall: 'Quelle structure relie les chromosomes au fuseau et où est-elle assemblée ?',
    answer: 'Le kinétochore s’assemble au niveau du centromère de chaque chromatide et capture les microtubules du fuseau.',
    source: '10-2-the-cell-cycle',
    glossary: [['Centromère', 'Région chromosomique où s’organise la cohésion et l’assemblage du kinétochore.'], ['Kinétochore', 'Complexe protéique qui relie une chromatide aux microtubules du fuseau.'], ['Cytocinèse', 'Séparation du cytoplasme en deux cellules filles.']],
    caseStudy: { prompt: 'Une cellule entre en anaphase alors qu’un chromosome n’est attaché qu’à un seul pôle. Quel contrôle a probablement échoué ?', answer: 'Le point de contrôle du fuseau, qui détecte les attachements incorrects et empêche normalement la séparation prématurée des chromatides.' }
  }),
  lesson('cell-cytoskeleton-motors', {
    objectives: ['Comparer actine, microtubules et filaments intermédiaires', 'Associer myosines, kinésines et dynéines à leurs pistes', 'Expliquer comment le cytosquelette soutient transport et forme cellulaire'],
    sections: [
      s('Trois systèmes de filaments', 'Les microfilaments d’actine, les microtubules de tubuline et les filaments intermédiaires ont des diamètres, propriétés mécaniques et distributions distincts. L’actine est fréquente sous la membrane et dans les structures contractiles ; les microtubules rayonnent souvent depuis le centrosome ; les filaments intermédiaires résistent aux contraintes de traction.'),
      s('Polarité dynamique', 'Actine et microtubules sont polarisés avec des extrémités plus et moins, et leurs sous-unités s’assemblent ou se retirent selon des conditions locales. Les microtubules alternent phases de croissance et de catastrophe ; l’actine assemble rapidement des réseaux ou faisceaux. Cette dynamique remodèle la cellule et permet l’adaptation aux signaux.'),
      s('Moteurs moléculaires', 'Les myosines se déplacent principalement sur l’actine. Les kinésines avancent le plus souvent vers l’extrémité plus des microtubules ; les dynéines se déplacent généralement vers l’extrémité moins et participent au transport rétrograde. Les moteurs hydrolysent l’ATP pour convertir une énergie chimique en mouvement et transport de cargaisons.'),
      s('Transport intracellulaire', 'Des vésicules, complexes protéiques et organites s’attachent à des moteurs via des adaptateurs. La direction dépend de la piste, du moteur, de l’ancrage et des signaux ; un organite peut être transporté dans les deux sens. Les microtubules facilitent les trajets à longue distance, tandis que l’actine intervient davantage dans les régions corticales.'),
      s('Forme, division et mouvement', 'L’actine contribue aux microvillosités, au front de migration et au sillon de cytocinèse. Les microtubules forment le fuseau mitotique et l’armature des cils et flagelles. Les filaments intermédiaires relient des structures d’ancrage et renforcent les tissus. Un même mouvement cellulaire résulte souvent de plusieurs composants coordonnés.'),
    ],
    trap: 'Les dynéines ne se déplacent pas sur l’actine : elles utilisent les microtubules, comme la plupart des kinésines.',
    recall: 'Quel moteur transporte souvent une vésicule vers l’extrémité moins d’un microtubule ?',
    answer: 'La dynéine cytoplasmique se déplace généralement vers l’extrémité moins ; sa direction effective dépend toutefois de la polarité de la piste et du complexe moteur.',
    source: '4-3-eukaryotic-cells',
    glossary: [['Microtubule', 'Polymère polarisé de tubuline servant de piste et de composant du fuseau.'], ['Kinésine', 'Moteur ATPasique se déplaçant le plus souvent vers l’extrémité plus des microtubules.'], ['Filament intermédiaire', 'Filament cytosquelettique apportant résistance mécanique et cohésion.']]
  }),
  lesson('cell-junctions-adhesion', {
    objectives: ['Distinguer jonctions serrées, adhérentes, desmosomes et jonctions gap', 'Relier les jonctions aux filaments auxquels elles s’ancrent', 'Expliquer leur rôle dans barrière, cohésion et communication tissulaire'],
    sections: [
      s('Une organisation tissulaire', 'Les cellules épithéliales sont reliées par des complexes de jonction qui maintiennent cohésion et polarité apico-basale. Les jonctions ne sont pas interchangeables : certaines scellent l’espace entre cellules, d’autres transmettent une force ou laissent passer des petites molécules.'),
      s('Jonctions serrées', 'Les jonctions serrées, ou zonulae occludentes, limitent le passage paracellulaire et aident à séparer domaines apical et basolatéral. Claudines et occludines contribuent à leur architecture ; le niveau d’étanchéité varie selon le tissu. Elles forment une barrière sélective, pas une paroi absolument imperméable.'),
      s('Adhérence et desmosomes', 'Les jonctions adhérentes utilisent des cadhérines reliées à l’actine via des protéines de plaque ; elles distribuent des forces et participent au remodelage de forme. Les desmosomes associent aussi des cadhérines spécialisées à une plaque plus robuste, ancrée aux filaments intermédiaires et adaptée aux tissus soumis à des tensions.'),
      s('Communication par jonctions gap', 'Les jonctions communicantes forment des canaux entre cytoplasmes voisins. Chaque connexon est constitué de connexines et s’apparie à un connexon de la cellule voisine. Ions et petites molécules peuvent ainsi passer, ce qui synchronise des réponses ; les protéines et macromolécules ne traversent pas librement ces pores.'),
      s('Choisir la jonction dans un raisonnement', 'Une barrière de perméabilité oriente vers les jonctions serrées ; une connexion mécanique liée aux filaments intermédiaires vers les desmosomes ; une adhérence associée à l’actine vers les jonctions adhérentes ; une communication ionique ou métabolique vers les jonctions gap. Plusieurs types coexistent dans un même tissu et se coordonnent.'),
    ],
    trap: 'Les jonctions serrées ne relient pas directement les cytoplasmes ; les jonctions gap, elles, créent un passage entre cellules.',
    recall: 'Quelle jonction relie des filaments intermédiaires entre cellules et résiste aux contraintes mécaniques ?',
    answer: 'Le desmosome, grâce à ses cadhérines et à sa plaque d’ancrage connectée aux filaments intermédiaires.',
    source: '4-6-connections-between-cells-and-cellular-activities',
    glossary: [['Cadhérine', 'Protéine d’adhérence dépendante du calcium contribuant à des jonctions cellule-cellule.'], ['Connexon', 'Hémicanal assemblé à partir de connexines dans une jonction gap.'], ['Polarité apico-basale', 'Organisation différenciée des domaines supérieur et latéraux/basaux d’une cellule épithéliale.']]
  }),
  lesson('cell-signaling-pathways', {
    objectives: ['Distinguer récepteurs membranaires et intracellulaires', 'Décrire les étapes réception, transduction et réponse', 'Expliquer l’amplification et l’extinction d’un signal cellulaire'],
    sections: [
      s('Modes de communication', 'Un ligand agit sur la cellule qui le sécrète en signalisation autocrine, sur une cellule voisine en paracrine ou à distance par voie endocrine. Les signaux peuvent aussi passer par contact direct ou jonctions communicantes. La portée dépend de stabilité, dilution, dégradation et accès au récepteur.'),
      s('Récepteurs et nature du ligand', 'Les ligands hydrophiles se lient le plus souvent à des récepteurs membranaires, car ils traversent mal la bicouche. Les molécules lipophiles peuvent atteindre des récepteurs intracellulaires qui régulent souvent l’expression génique. Un récepteur ne répond qu’aux molécules compatibles avec son site de liaison et son état conformationnel.'),
      s('RCPG et seconds messagers', 'Un récepteur couplé aux protéines G active une protéine hétérotrimérique par échange GDP-GTP sur sa sous-unité α ou par dissociation de ses composants. Ceux-ci régulent des effecteurs, comme adénylate cyclase ou phospholipase C, produisant des seconds messagers tels qu’AMPc, IP₃, DAG ou Ca²⁺.'),
      s('Récepteurs à activité enzymatique', 'Certains récepteurs tyrosine kinases s’oligomérisent ou se réorganisent après liaison du ligand, puis s’autophosphorylent. Les phosphotyrosines recrutent des protéines adaptatrices et déclenchent des cascades comme Ras–MAPK ou PI3K–AKT. Ces voies règlent croissance, survie, métabolisme et différenciation selon le contexte cellulaire.'),
      s('Amplifier puis arrêter', 'Une seule liaison ligand-récepteur peut activer plusieurs effecteurs et amplifier le signal. La réponse dépend aussi de rétrocontrôles, d’internalisation du récepteur, d’hydrolyse du GTP, de dégradation des seconds messagers et de déphosphorylation. L’arrêt est essentiel : une stimulation persistante ne signifie pas nécessairement une réponse proportionnelle ou bénéfique.'),
    ],
    trap: 'Une cascade MAPK ou PI3K/AKT n’est pas exclusivement activée par un seul type de récepteur : l’identité de la voie dépend du récepteur et des adaptateurs exprimés.',
    recall: 'Quel rôle joue l’échange GDP-GTP sur la sous-unité α d’une protéine G ?',
    answer: 'Il active la sous-unité α après stimulation du RCPG ; celle-ci peut alors réguler un effecteur avant d’hydrolyser le GTP et de revenir à l’état inactif.',
    source: '9-2-propagation-of-the-signal',
    glossary: [['Second messager', 'Petite molécule intracellulaire relayant ou amplifiant un signal de récepteur.'], ['Autophosphorylation', 'Phosphorylation d’un récepteur par sa propre activité kinase après activation.'], ['Adaptateur', 'Protéine qui connecte des composants d’une voie de signalisation.']]
  }),
  lesson('cell-nuclear-envelope-pores', {
    objectives: ['Décrire les deux membranes de l’enveloppe nucléaire et la lamina', 'Distinguer diffusion passive et transport actif par les pores nucléaires', 'Expliquer import et export dirigés par signaux et Ran-GTP'],
    sections: [
      s('Enveloppe à deux membranes', 'L’enveloppe nucléaire comprend une membrane interne et une membrane externe, séparées par l’espace périnucléaire. La membrane externe se prolonge dans le RE. La lamina nucléaire, réseau de lamines sous la membrane interne, soutient la forme du noyau et contribue à l’organisation de la chromatine.'),
      s('Architecture du pore', 'Le complexe du pore nucléaire est un assemblage massif de nucléoporines formant un canal sélectif. Les petites molécules diffusent plus facilement ; les macromolécules traversent de manière dirigée grâce à des récepteurs de transport. Des nucléoporines riches en répétitions FG contribuent à la barrière sélective.'),
      s('Importer une protéine', 'Une protéine nucléaire porte souvent un signal de localisation nucléaire reconnu par une importine. Le complexe franchit le pore ; dans le noyau, Ran-GTP se lie à l’importine et favorise la libération de la cargaison. L’importine retourne au cytosol où l’hydrolyse du GTP contribue au cycle de transport.'),
      s('Exporter une cargaison', 'Une exportine reconnaît un signal d’export sur sa cargaison, souvent en présence de Ran-GTP dans le noyau. Le complexe traverse le pore vers le cytosol ; l’hydrolyse du GTP y dissocie les partenaires. Le gradient Ran-GTP élevé dans le noyau et Ran-GDP dominant dans le cytosol donne une direction au cycle.'),
      s('Transport et régulation', 'Les ARNm maturés s’associent à des protéines et sont exportés par des récepteurs adaptés ; les sous-unités ribosomales suivent également un transport dirigé. L’accès nucléaire peut être réglé par exposition ou masquage des signaux, modification des pores et rétention de la cargaison. La barrière protège le génome tout en permettant un échange sélectif.'),
    ],
    trap: 'Le pore nucléaire n’est pas un trou ouvert sans contrôle : diffusion et transport récepteur-dépendant ont des règles différentes.',
    recall: 'Dans quel compartiment Ran-GTP est-il le plus abondant, et comment cela favorise-t-il l’import nucléaire ?',
    answer: 'Ran-GTP est élevé dans le noyau. Sa liaison à l’importine y libère la cargaison importée ; le cycle est entretenu par l’hydrolyse cytosolique du GTP et le retour des facteurs.',
    source: '4-3-eukaryotic-cells',
    glossary: [['Nucléoporine', 'Protéine constituant le complexe du pore nucléaire.'], ['Importine', 'Récepteur qui reconnaît un signal d’importation nucléaire.'], ['Lamina nucléaire', 'Réseau de lamines sous la membrane interne de l’enveloppe.']]
  }),
  lesson('cell-extracellular-matrix-integrins', {
    objectives: ['Identifier les principaux composants de la matrice extracellulaire', 'Expliquer le lien intégrines-cytosquelette dans l’adhérence focale', 'Relier matrice et signalisation à l’organisation tissulaire'],
    sections: [
      s('Une matrice produite par les cellules', 'La matrice extracellulaire (MEC) est un réseau de macromolécules sécrétées et organisées à l’extérieur des cellules. Sa composition varie selon les tissus et les contraintes. Elle fournit un support, filtre des molécules et présente des signaux qui influencent adhérence, migration, prolifération et différenciation.'),
      s('Collagènes et élastine', 'Les collagènes forment des structures résistantes à la traction et sont abondants dans de nombreux tissus conjonctifs. L’élastine permet l’étirement suivi d’un retour élastique dans des tissus comme les grandes artères et les poumons. Leur assemblage et leur organisation conditionnent les propriétés mécaniques locales.'),
      s('Protéoglycanes et fibronectine', 'Les protéoglycanes associent une protéine centrale à des glycosaminoglycanes chargés qui attirent eau et ions et forment un gel hydraté. La fibronectine est une glycoprotéine d’adhérence qui lie plusieurs composants matriciels et des intégrines. La lame basale contient notamment laminines et collagène IV, avec une organisation spécialisée.'),
      s('Intégrines et adhérences focales', 'Les intégrines sont des récepteurs transmembranaires hétérodimériques qui lient des composants de la MEC à l’extérieur et des protéines adaptatrices puis l’actine à l’intérieur. Dans une adhérence focale, taline, vinculine et autres protéines connectent les intégrines au cytosquelette. La force transmise peut modifier la conformation et déclencher des signaux.'),
      s('Mécanique et signalisation', 'La cellule détecte rigidité, tension et composition de la matrice : la mécano-transduction transforme une contrainte physique en réponse biochimique. Des voies associées aux intégrines influencent survie, migration et expression génique. Remodelage enzymatique, contraction et dépôt matriciel modifient en retour l’environnement ; la MEC est donc dynamique.'),
    ],
    trap: 'Les intégrines traversent la membrane et relient les deux côtés via des protéines d’ancrage ; elles ne constituent pas elles-mêmes un filament d’actine.',
    recall: 'Quel rôle joue la taline dans une adhérence focale ?',
    answer: 'La taline se lie à la queue cytosolique d’intégrines et à l’actine via des partenaires ; elle contribue à l’ancrage mécanique et à l’activation de la signalisation.',
    source: '4-6-connections-between-cells-and-cellular-activities',
    glossary: [['Glycosaminoglycane', 'Polysaccharide chargé contribuant à l’hydratation et aux propriétés de la matrice.'], ['Lame basale', 'Matrice spécialisée sous certains épithéliums et autour de cellules.'], ['Mécano-transduction', 'Conversion d’une force ou rigidité en signal biochimique.']]
  }),
  lesson('cell-apoptosis-mechanisms', {
    objectives: ['Distinguer apoptose et mort cellulaire non programmée', 'Comparer voies mitochondriale et récepteur-dépendante', 'Expliquer le rôle des caspases et le devenir des corps apoptotiques'],
    sections: [
      s('Une mort cellulaire organisée', 'L’apoptose est une forme régulée de mort cellulaire caractérisée par condensation, fragmentation contrôlée et formation de corps apoptotiques. La membrane plasmique reste globalement intacte aux premières étapes, ce qui limite la libération de contenu et la réaction inflammatoire. Elle intervient dans développement, renouvellement et élimination de cellules endommagées.'),
      s('Caspases initiatrices et effectrices', 'Les caspases sont des protéases synthétisées comme précurseurs inactifs. Des plateformes d’activation rapprochent des caspases initiatrices qui s’activent puis clivent des caspases effectrices. Celles-ci dégradent des protéines structurales et régulatrices, ce qui produit les changements morphologiques caractéristiques.'),
      s('Voie mitochondriale intrinsèque', 'Des dommages, privation de facteurs trophiques ou autres stress activent les protéines pro-apoptotiques de la famille Bcl-2. Bax et Bak perméabilisent la membrane externe mitochondriale, libérant notamment le cytochrome c. Celui-ci participe à l’apoptosome avec Apaf-1, qui active la caspase initiatrice 9.'),
      s('Voie extrinsèque des récepteurs de mort', 'Des ligands comme FasL ou certaines formes de TNF se lient à des récepteurs de mort et favorisent le recrutement de protéines adaptatrices dans un complexe de signalisation. La caspase 8 ou 10 peut être activée, puis déclencher les caspases effectrices. Une connexion avec la voie mitochondriale amplifie la réponse dans certaines cellules.'),
      s('Élimination sans débordement', 'Les cellules apoptotiques exposent des signaux de reconnaissance, dont la phosphatidylsérine, et sont rapidement phagocytées par des cellules voisines ou spécialisées. Une apoptose excessive ou insuffisante peut contribuer à des maladies, mais l’issue dépend du tissu et du contexte ; apoptose n’est pas synonyme de toute mort cellulaire.'),
    ],
    trap: 'Le cytochrome c libéré dans le cytosol participe à l’activation de l’apoptosome ; il ne déclenche pas directement seul toutes les caspases.',
    recall: 'Quel événement mitochondrial distingue la voie intrinsèque en amont de la caspase 9 ?',
    answer: 'La perméabilisation de la membrane externe mitochondriale par Bax/Bak libère le cytochrome c, qui contribue à l’assemblage de l’apoptosome activant la caspase 9.',
    source: '9-3-response-to-the-signal',
    glossary: [['Apoptosome', 'Complexe assemblé autour d’Apaf-1 et du cytochrome c qui active la caspase 9.'], ['Caspase', 'Protéase à cystéine qui clive des protéines après un résidu aspartate.'], ['Corps apoptotique', 'Fragment membranaire contenant des éléments de la cellule en apoptose.']],
    caseStudy: { prompt: 'Une cellule présente condensation nucléaire, corps apoptotiques et exposition de phosphatidylsérine, sans rupture membranaire précoce. Quel mécanisme est cohérent ?', answer: 'Ces signes sont cohérents avec une apoptose suivie d’une reconnaissance et d’une phagocytose, plutôt qu’une lyse immédiate avec libération massive de contenu.' }
  })
]

const q = (course: string, n: number, topicOrPrompt: string, promptOrOptions: string | string[], optionsOrCorrect: string[] | number[], correctOrWhy: number[] | string[], finalWhy?: string[]): Question => {
  const hasTopic = typeof promptOrOptions === 'string'
  const prompt = hasTopic ? promptOrOptions : topicOrPrompt
  const options = hasTopic ? optionsOrCorrect as string[] : promptOrOptions
  const correct = hasTopic ? correctOrWhy as number[] : optionsOrCorrect as number[]
  const why = hasTopic ? finalWhy! : correctOrWhy as string[]
  return { id: `${course}-q${n}`, course, topic: 'Biologie cellulaire', prompt, options, correct, why, difficulty: n < 3 ? 'essentiel' : 'application' }
}
export const architectureDivisionQuestions: Question[] = [
  q('cell-cycle-phases-control',1,'À quelle phase l’ADN est-il répliqué ?', ['S','G1','G2','Anaphase'],[0],['La phase S correspond à la synthèse de l’ADN.','G1 précède la réplication.','G2 suit la phase S.','L’anaphase sépare les chromatides.']),
  q('cell-cycle-phases-control',2,'Quel complexe phosphoryle des protéines cibles pour faire progresser le cycle ?', ['Cycline-CDK','Clathrine-SNARE','Actine-tubuline','Collagène-intégrine'],[0],['Les CDK associées aux cyclines coordonnent plusieurs transitions.','Ces protéines participent au trafic membranaire.','Ce sont des éléments du cytosquelette.','Ces protéines participent à la MEC et l’adhérence.']),
  q('cell-cycle-phases-control',3,'Quel point de contrôle retarde l’anaphase si les kinétochores sont mal attachés ?', ['Point de contrôle du fuseau','G1/S','Contrôle de traduction','Contrôle lysosomal'],[0],['Il vérifie les attachements avant séparation.','G1/S intervient avant la réplication.','Il ne s’agit pas d’un contrôle de traduction.','Les lysosomes ne vérifient pas le fuseau.']),
  q('cell-cycle-phases-control',4,'Une cellule différenciée peut sortir temporairement ou durablement du cycle vers :',['G0','S','M','Prométaphase'],[0],['G0 correspond à un état quiescent hors du cycle actif.','S est la réplication.','M est la division.','La prométaphase est une étape de mitose.']),
  q('cell-cycle-phases-control',5,'Que fait p53 après certains dommages à l’ADN ?', ['Contribue à arrêter le cycle et coordonner la réponse','Réplique directement le chromosome','Forme le fuseau mitotique','Dégrade les membranes cellulaires'],[0],['p53 participe à des réponses de contrôle et réparation ou élimination.','La réplication dépend de complexes enzymatiques.','Le fuseau repose notamment sur les microtubules.','Ce n’est pas son rôle.']),
  q('cell-mitosis-cytokinesis',1,'Quel complexe capture les microtubules sur le chromosome ?', ['Kinétochore','Ribosome','Centrosome du RE','Connexon'],[0],['Le kinétochore s’assemble au centromère.','Le ribosome traduit l’ARNm.','Ce terme ne désigne pas une structure.','Le connexon permet la communication entre cellules.']),
  q('cell-mitosis-cytokinesis',2,'Quel événement définit l’anaphase ?', ['Séparation des chromatides sœurs','Réplication de l’ADN','Formation des ribosomes','Condensation initiale du Golgi'],[0],['La cohésion est rompue et les chromatides migrent aux pôles.','La réplication a lieu en phase S.','La biogenèse ribosomale se déroule surtout dans le nucléole.','Le Golgi ne se condense pas ainsi.']),
  q('cell-mitosis-cytokinesis',3,'Que contient une paire de chromosomes répliqués en métaphase ?', ['Deux chromatides sœurs reliées au centromère','Deux chromosomes homologues sans lien','Un seul brin d’ADN','Quatre noyaux'],[0],['Chaque chromosome répliqué possède deux chromatides sœurs.','Les homologues ne sont pas les chromatides sœurs.','Chaque chromatide contient une molécule d’ADN double brin.','La cellule n’a pas encore quatre noyaux.']),
  q('cell-mitosis-cytokinesis',4,'Quel composant forme principalement le fuseau mitotique ?', ['Microtubules','Filaments de collagène','Phospholipides libres','ARN ribosomique'],[0],['Les microtubules organisent le fuseau.','Le collagène est extracellulaire.','Les lipides forment les membranes.','L’ARNr constitue les ribosomes.']),
  q('cell-mitosis-cytokinesis',5,'Comment une cellule végétale réalise-t-elle généralement la cytocinèse ?', ['Par formation d’une plaque cellulaire à partir de vésicules','Par sillon actomyosine qui pince toute la paroi','Par fusion nucléaire','Par rupture de la membrane interne mitochondriale'],[0],['Les vésicules forment la plaque séparatrice.','La paroi rigide empêche le sillon animal classique.','La cytocinèse sépare le cytoplasme.','La membrane mitochondriale n’est pas le mécanisme.']),
  q('cell-cytoskeleton-motors',1,'Pistes','Sur quels filaments les myosines se déplacent-elles ?', ['Actine','Microtubules','ADN','Collagène extracellulaire'],[0],['Les myosines sont des moteurs de l’actine.','Les kinésines et dynéines utilisent surtout les microtubules.','L’ADN n’est pas une piste motrice.','Le collagène est hors de la cellule.']),
  q('cell-cytoskeleton-motors',2,'Moteurs','Quel moteur se déplace généralement vers l’extrémité moins des microtubules ?', ['Dynéine','Kinésine classique','Myosine II','Kératine'],[0],['La dynéine assure souvent un transport rétrograde.','La plupart des kinésines vont vers le plus.','La myosine agit sur l’actine.','La kératine est un filament intermédiaire, non un moteur.']),
  q('cell-cytoskeleton-motors',3,'Structure','Quel élément cytosquelettique est particulièrement résistant à la traction ?', ['Filaments intermédiaires','ARN messager','Phospholipides','Ribosomes'],[0],['Ils renforcent mécaniquement la cellule et les tissus.','L’ARNm porte une séquence codante.','Les lipides forment des membranes.','Les ribosomes traduisent des protéines.']),
  q('cell-cytoskeleton-motors',4,'Dynamique','Quelle structure est faite de tubuline ?', ['Microtubule','Filament d’actine','Desmosome','Lamina basale'],[0],['Les microtubules polymérisent à partir de tubuline.','L’actine forme les microfilaments.','Le desmosome est une jonction.','La lamina basale est extracellulaire.']),
  q('cell-cytoskeleton-motors',5,'Application','Pourquoi un moteur moléculaire consomme-t-il de l’ATP ?', ['Pour convertir l’énergie chimique en changement de conformation et déplacement','Pour fournir les sous-unités d’actine','Pour transcrire l’ADN','Pour remplacer les membranes'],[0],['L’hydrolyse alimente les cycles mécaniques du moteur.','L’actine est synthétisée par polymérisation de monomères.','La transcription utilise des polymérases et NTP.','L’ATP ne remplace pas les membranes.']),
  q('cell-junctions-adhesion',1,'Barrière','Quelle jonction limite le passage paracellulaire entre cellules épithéliales ?', ['Jonction serrée','Jonction gap','Desmosome','Synapse chimique'],[0],['Claudines et autres protéines forment un sceau sélectif.','Les jonctions gap laissent passer de petites molécules.','Les desmosomes résistent aux tractions.','La synapse libère des neurotransmetteurs.']),
  q('cell-junctions-adhesion',2,'Résistance mécanique','Quelle jonction est ancrée aux filaments intermédiaires ?', ['Desmosome','Jonction serrée','Jonction gap','Pore nucléaire'],[0],['Les desmosomes distribuent les contraintes via ces filaments.','La jonction serrée agit comme barrière.','La jonction gap connecte des cytoplasmes.','Le pore nucléaire contrôle le trafic nucléaire.']),
  q('cell-junctions-adhesion',3,'Communication','Que laissent passer les jonctions gap ?', ['Ions et petites molécules entre cytoplasmes','Protéines entières sans sélection','Chromosomes','Vésicules sécrétoires'],[0],['Les connexons forment des canaux de petite taille.','Les macromolécules ne traversent pas librement.','Les chromosomes ne passent pas par les pores gap.','Les vésicules sont des organites séparés.']),
  q('cell-junctions-adhesion',4,'Jonction adhérente','À quels filaments s’associe principalement une jonction adhérente ?', ['Actine','ADN','Filaments de myosine isolés exclusivement','Microvillosités luminales'],[0],['Les cadhérines connectent la jonction au réseau d’actine.','L’ADN est nucléaire.','La myosine peut agir avec l’actine mais ne définit pas l’ancrage.','Les microvillosités sont des projections, pas un filament.']),
  q('cell-junctions-adhesion',5,'Structure','Quelle protéine participe aux jonctions gap ?', ['Connexine','Claudine uniquement','Kinétochore','SRP'],[0],['Les connexines s’assemblent en connexons.','Les claudines participent aux jonctions serrées.','Le kinétochore organise l’attachement du fuseau.','La SRP cible des protéines au RE.']),
  q('cell-signaling-pathways',1,'Récepteurs','Où se trouvent souvent les récepteurs de ligands lipophiles ?', ['Dans le cytosol ou le noyau','Dans la lumière lysosomale uniquement','Sur les chromosomes sans protéine','Dans la paroi cellulosique humaine'],[0],['Les ligands lipophiles traversent la membrane et peuvent se lier à des récepteurs intracellulaires.','Ce n’est pas leur localisation usuelle.','Les récepteurs sont des protéines.','Les cellules humaines n’ont pas de paroi cellulosique.']),
  q('cell-signaling-pathways',2,'RCPG','Que lie la sous-unité α active d’une protéine G ?', ['GTP','ADP exclusivement','ADN','Mannose-6-phosphate'],[0],['L’échange GDP-GTP active souvent la sous-unité α.','Ce n’est pas l’état actif classique.','L’ADN n’est pas son ligand.','Ce marqueur adresse des hydrolases.']),
  q('cell-signaling-pathways',3,'Seconds messagers','Lequel est un second messager courant ?', ['AMPc','Collagène IV','Tubuline','Kératine'],[0],['L’AMPc relaie plusieurs signaux intracellulaires.','C’est une protéine de matrice.','La tubuline est une protéine cytosquelettique.','La kératine est un filament intermédiaire.']),
  q('cell-signaling-pathways',4,'RTK','Quel événement suit souvent l’activation d’un récepteur tyrosine kinase ?', ['Phosphorylation de tyrosines et recrutement d’adaptateurs','Réplication directe de l’ADN','Dégradation du récepteur par défaut','Ouverture d’une jonction gap'],[0],['Les phosphotyrosines recrutent des protéines de signalisation.','La réplication est un processus distinct.','Le récepteur peut être internalisé mais pas automatiquement dégradé.','Les jonctions gap sont des canaux intercellulaires.']),
  q('cell-signaling-pathways',5,'Extinction','Quel mécanisme contribue à terminer un signal RCPG ?', ['Hydrolyse du GTP par la protéine G','Synthèse d’un chromosome','Assemblage de la paroi végétale','Activation permanente du récepteur'],[0],['La sous-unité α hydrolyse GTP et revient vers l’état inactif.','La réplication du chromosome ne met pas fin au signal.','Les humains n’ont pas de paroi végétale.','Un signal doit pouvoir être arrêté.']),
  q('cell-nuclear-envelope-pores',1,'Pores','Que fait le complexe du pore nucléaire ?', ['Permet un transport sélectif entre noyau et cytosol','Fusionne toutes les membranes cellulaires','Synthétise les lipides du RE','Dégrade les protéines dans un pH acide'],[0],['Les petites molécules diffusent et les macromolécules utilisent des récepteurs.','Les pores ne fusionnent pas les membranes.','Le RE synthétise des lipides.','Les lysosomes assurent la digestion acide.']),
  q('cell-nuclear-envelope-pores',2,'Import','Que reconnaît une importine pour importer certaines protéines ?', ['Signal de localisation nucléaire','Mannose-6-phosphate','Séquence d’ancrage des mitochondries toujours','Phosphatidylsérine externe'],[0],['Le signal nucléaire est reconnu par un récepteur de transport.','Le mannose-6-phosphate cible des hydrolases lysosomales.','D’autres signaux ciblent les mitochondries.','La phosphatidylsérine est un signal membranaire.']),
  q('cell-nuclear-envelope-pores',3,'Ran','Quel est l’effet de Ran-GTP dans le noyau sur un complexe importine-cargaison ?', ['Il favorise la libération de la cargaison','Il hydrolyse l’ADN','Il ferme tous les pores','Il crée l’enveloppe nucléaire'],[0],['Ran-GTP se lie à l’importine et provoque la dissociation du complexe.','Il n’est pas une nucléase.','Le transport continue.','L’enveloppe est réassemblée par d’autres composants.']),
  q('cell-nuclear-envelope-pores',4,'Structure','Où se situe la lamina nucléaire ?', ['Sous la membrane interne de l’enveloppe nucléaire','Dans le lysosome','À l’extérieur de la cellule','Dans la lumière du Golgi'],[0],['Les lamines tapissent la face nucléoplasmique interne.','Le lysosome est un compartiment acide.','La matrice extracellulaire est externe.','Le Golgi est un organite distinct.']),
  q('cell-nuclear-envelope-pores',5,'Export','Quelle distribution de Ran aide à donner une direction au transport nucléaire ?', ['Ran-GTP élevé dans le noyau et Ran-GDP dominant dans le cytosol','Ran-GTP identique partout sans hydrolyse','Ran uniquement dans les lysosomes','ATP élevé dans le nucléole uniquement'],[0],['Le gradient de nucléotides Ran organise les cycles import/export.','Le gradient est essentiel à la directionnalité.','Ran n’est pas limité aux lysosomes.','L’ATP du nucléole n’explique pas l’import.']),
  q('cell-extracellular-matrix-integrins',1,'Matrice','Quel composant donne une forte résistance à la traction à de nombreux tissus ?', ['Collagène','Clathrine','ARN polymérase','Connexine'],[0],['Les fibres de collagène contribuent à la résistance mécanique.','La clathrine forme un manteau vésiculaire.','La polymérase transcrit l’ARN.','La connexine forme des canaux gap.']),
  q('cell-extracellular-matrix-integrins',2,'Intégrines','Quel lien établissent les intégrines ?', ['Matrice extracellulaire vers protéines adaptatrices et cytosquelette','Noyau vers ADN mitochondrial directement','Lysosome vers lumière du Golgi','Ribosome vers ARN polymérase'],[0],['Leur queue cytosolique se lie à des adaptateurs connectés au cytosquelette.','Elles ne relient pas ces compartiments.','Ce n’est pas leur fonction.','La traduction et transcription sont distinctes.']),
  q('cell-extracellular-matrix-integrins',3,'Protéoglycanes','Quel effet les glycosaminoglycanes chargés ont-ils souvent dans la matrice ?', ['Ils attirent l’eau et contribuent à un gel hydraté','Ils forment le fuseau mitotique','Ils transportent les ARNm au noyau','Ils hydrolysent l’ATP'],[0],['Leurs charges retiennent eau et ions.','Le fuseau est constitué de microtubules.','L’export d’ARNm passe par des pores.','Ils ne sont pas des moteurs ou enzymes ATPases.']),
  q('cell-extracellular-matrix-integrins',4,'Adhérence focale','Quel filament est associé aux adhérences focales ?', ['Actine','ADN chromosomique','Filament d’ARNr','Membrane nucléaire externe exclusivement'],[0],['Les intégrines s’associent aux filaments d’actine par adaptateurs.','L’ADN ne s’ancre pas ainsi.','L’ARNr est un composant des ribosomes.','La jonction est à la membrane plasmique.']),
  q('cell-extracellular-matrix-integrins',5,'Mécano-transduction','Que désigne la mécano-transduction ?', ['Conversion de contraintes physiques en signaux biochimiques','Conversion de glucose en ADN','Transport de vésicules sans moteur','Dégradation des protéines dans le noyau'],[0],['Tension et rigidité influencent des voies de signalisation.','Ce n’est pas une voie de synthèse d’ADN.','Des moteurs peuvent participer au transport.','La dégradation n’est pas sa définition.']),
  q('cell-apoptosis-mechanisms',1,'Caspases','Quel type de protéase caractérise la cascade apoptotique ?', ['Caspases','Amylases digestives uniquement','Pompes à protons','Tubulines'],[0],['Les caspases initiatrices et effectrices orchestrent de nombreux clivages.','Les amylases digèrent les glucides.','Les pompes maintiennent un gradient.','Les tubulines composent les microtubules.']),
  q('cell-apoptosis-mechanisms',2,'Voie intrinsèque','Quel événement déclenche en aval l’assemblage de l’apoptosome ?', ['Libération de cytochrome c dans le cytosol','Sortie de ribosomes du nucléole','Fusion d’un lysosome avec la membrane','Production de collagène'],[0],['Le cytochrome c rejoint Apaf-1 et favorise l’activation de la caspase 9.','La biogenèse ribosomale est distincte.','Cela correspond à une exocytose, pas à la voie intrinsèque.','Le collagène est une protéine matricielle.']),
  q('cell-apoptosis-mechanisms',3,'Voie extrinsèque','Quel type de récepteur peut initier une voie extrinsèque ?', ['Récepteur de mort comme Fas','Récepteur nucléaire aux stéroïdes uniquement','Récepteur du mannose-6-phosphate','Récepteur de l’oxygène mitochondrial'],[0],['Fas peut recruter des adaptateurs pro-apoptotiques.','Les récepteurs stéroïdiens ont une autre fonction.','Ce récepteur trie des hydrolases.','Ce n’est pas une classe usuelle.']),
  q('cell-apoptosis-mechanisms',4,'Phagocytose','Quel signal facilite la reconnaissance de cellules apoptotiques ?', ['Exposition de phosphatidylsérine','Perte de tous les phospholipides','Hausse d’ARNr cytosolique','Sortie d’hémoglobine obligatoire'],[0],['Ce phospholipide externe est un signal de reconnaissance.','La membrane reste initialement globalement intacte.','L’ARNr n’est pas le signal principal.','Une cellule n’est pas nécessairement érythrocytaire.']),
  q('cell-apoptosis-mechanisms',5,'Conséquence','Pourquoi l’apoptose déclenche-t-elle souvent moins d’inflammation qu’une lyse immédiate ?', ['La membrane reste contenante et les corps sont rapidement phagocytés','Elle libère toujours le contenu cellulaire en masse','Elle n’implique jamais de membranes','Elle produit des bactéries'],[0],['La reconnaissance et l’élimination limitent le débordement du contenu.','C’est plutôt le risque d’une lyse.','Les corps apoptotiques sont membranaires.','L’apoptose est un processus cellulaire eucaryote.'])
]
