import type { Course } from '../../curriculum'
import type { Question } from '../../questions'
import { canonicalCourses } from '../../taxonomy/canonicalCourses'

const base = 'https://openstax.org/books/biology-2e/pages/'
type Draft = { objectives: string[]; sections: Course['sections']; trap: string; recall: string; answer: string; source: string; glossary?: Course['glossary']; caseStudy?: Course['caseStudy'] }
const metadata = new Map(canonicalCourses.filter(item => item.subject === 'Biologie cellulaire').map(item => [item.id, item]))
const lesson = (id: string, d: Draft): Course => {
  const canonical = metadata.get(id)
  if (!canonical) throw new Error(`Chapitre canonique de biologie cellulaire introuvable : ${id}`)
  return { id, title: canonical.title, category: canonical.subject, tag: canonical.module, minutes: 12, structure: null,
    objectives: d.objectives, sections: d.sections, trap: d.trap, recall: d.recall, answer: d.answer,
    source: base + d.source, sources: [{ label: 'OpenStax · Biology 2e', url: base + d.source }],
    prerequisites: ['Organisation de la cellule eucaryote', 'Membrane plasmique et gradients'],
    review: { status: 'unreviewed', updatedAt: '2026-09-23', sourcesUpdatedAt: '2026-09-23' },
    ...(d.glossary ? { glossary: d.glossary } : {}), ...(d.caseStudy ? { caseStudy: d.caseStudy } : {}) }
}
const s = (title: string, text: string, bullets?: string[]) => ({ title, text, ...(bullets ? { bullets } : {}) })

export const membraneCourses: Course[] = [
  lesson('cell-membrane-trafficking', {
    objectives: ['Décrire la bicouche et ses principaux composants', 'Relier composition lipidique et fluidité membranaire', 'Expliquer la polarité et l’asymétrie de la membrane'],
    sections: [
      s('Une bicouche auto-assemblée', 'Les phospholipides amphiphiles exposent leurs têtes hydrophiles au milieu aqueux et enfouissent leurs chaînes hydrophobes. La membrane est une barrière dynamique, pas une enveloppe rigide. Sa perméabilité dépend de la taille, de la charge et de la solubilité lipidique des molécules ; les ions traversent rarement le cœur lipidique sans protéine.'),
      s('Protéines et glucides', 'Les protéines intégrales pénètrent la bicouche ou la traversent ; les protéines périphériques s’associent à une face par interactions non covalentes. Canaux, transporteurs, enzymes et récepteurs assurent des fonctions distinctes. Les chaînes glucidiques liées aux lipides ou protéines sont exposées principalement à la face extracellulaire et participent à la reconnaissance et à l’adhérence.'),
      s('Fluidité et cholestérol', 'Les lipides diffusent latéralement, tandis que le passage spontané d’un feuillet à l’autre est rare et souvent facilité par des enzymes. Des chaînes insaturées créent des coudes qui gênent l’empilement. Le cholestérol amortit les variations de fluidité : il limite le mouvement à température élevée et empêche un empaquetage trop serré à basse température.'),
      s('Asymétrie des feuillets', 'Les deux faces n’ont pas la même composition. Des flippases, floppases et scramblases déplacent certains phospholipides et entretiennent ou dissipent cette asymétrie. L’exposition externe de phosphatidylsérine peut servir de signal de reconnaissance cellulaire, notamment lors de l’apoptose. Elle n’est donc pas une propriété équivalente à une simple variation de fluidité.'),
      s('Microdomaines et signalisation', 'Les radeaux membranaires désignent des microdomaines transitoires enrichis en cholestérol et sphingolipides, auxquels certaines protéines s’associent. Ils peuvent organiser localement des partenaires de signalisation ou de trafic. Le modèle de mosaïque fluide n’implique pas que chaque constituant diffuse sans contrainte : cytosquelette, interactions protéiques et composition locale limitent les mouvements.'),
    ],
    trap: 'Le cholestérol ne « fluidifie » pas toujours la membrane : son effet dépend de la température et de la composition lipidique.',
    recall: 'Pourquoi une chaîne d’acide gras insaturée tend-elle à empêcher l’empilement compact des phospholipides ?',
    answer: 'La double liaison cis introduit un coude dans la chaîne, augmente l’espace entre lipides voisins et réduit les interactions de dispersion qui stabilisent l’empilement.',
    source: '5-1-components-and-structure',
    glossary: [['Amphiphile', 'Molécule portant une partie hydrophile et une partie hydrophobe.'], ['Flip-flop', 'Passage transversal d’un lipide d’un feuillet à l’autre.'], ['Radeau lipidique', 'Microdomaine membranaire dynamique enrichi en certains lipides et protéines.']],
    caseStudy: { prompt: 'Une cellule expose soudainement de la phosphatidylsérine sur son feuillet externe. Quelle propriété a changé et quelle conséquence peut en découler ?', answer: 'L’asymétrie membranaire est modifiée. Cette exposition peut être reconnue par des cellules phagocytaires comme un signal associé à l’élimination d’une cellule apoptotique.' }
  }),
  lesson('cell-endoplasmic-reticulum', {
    objectives: ['Distinguer fonctions du réticulum rugueux et lisse', 'Expliquer le ciblage d’une protéine sécrétée vers le RER', 'Relier repliement protéique et contrôle de qualité du RE'],
    sections: [
      s('Un réseau de membranes', 'Le réticulum endoplasmique (RE) forme des citernes et tubules continus avec l’enveloppe nucléaire externe. Sa lumière constitue un compartiment distinct du cytosol. La répartition des ribosomes donne l’aspect rugueux ou lisse, mais ces régions sont reliées et échangent leurs constituants.'),
      s('Ciblage vers le RE rugueux', 'Une séquence signal naissante est reconnue par la particule SRP, qui ralentit momentanément la traduction et amène le ribosome au récepteur SRP du RE. La chaîne entre ensuite par un translocon pendant sa synthèse. Les protéines sans signal approprié restent généralement dans le cytosol ou suivent une autre voie de ciblage.'),
      s('Maturation et contrôle', 'Dans la lumière du RE, les protéines peuvent se replier avec des chaperonnes, former des ponts disulfure et recevoir une N-glycosylation initiale. Des systèmes retiennent les protéines mal repliées, favorisent leur réparation ou les dirigent vers la dégradation associée au RE. Une surcharge peut déclencher une réponse adaptative au stress du réticulum.'),
      s('RE lisse et lipides', 'Les régions lisses participent à la synthèse de lipides membranaires et de stéroïdes, au métabolisme de certains composés et au stockage du calcium selon le type cellulaire. Dans les cellules musculaires, le réticulum sarcoplasmique est spécialisé dans la libération puis la recapture du Ca²⁺ qui règle la contraction.'),
      s('Export et rétention', 'Les protéines correctement assemblées sont concentrées dans des sites de sortie et emballées dans des vésicules vers le Golgi. Des signaux de rétention ou de récupération ramènent certaines protéines résidentes du RE. Le compartiment n’est donc pas un simple convoyeur : il sélectionne, modifie et contrôle le chargement avant export.'),
    ],
    trap: 'Le RER synthétise les protéines destinées à la sécrétion, aux membranes et à certains organites ; il ne synthétise pas toutes les protéines de la cellule.',
    recall: 'Comment une protéine en cours de traduction est-elle reconnue et amenée vers le RE rugueux ?',
    answer: 'Sa séquence signal est reconnue par la SRP, qui dirige le complexe ribosome-chaîne naissante vers le récepteur SRP puis le translocon du RE.',
    source: '4-4-the-endomembrane-system-and-proteins',
    glossary: [['SRP', 'Particule qui reconnaît certaines séquences signal et cible le ribosome au RE.'], ['Translocon', 'Canal membranaire permettant le passage d’une chaîne naissante vers la lumière du RE.'], ['N-glycosylation', 'Ajout précoce d’un oligosaccharide sur l’azote d’une asparagine.']]
  }),
  lesson('cell-golgi-apparatus', {
    objectives: ['Décrire polarité cis-médiale-trans du Golgi', 'Distinguer maturation et tri des protéines', 'Relier les signaux d’adressage à la destination des vésicules'],
    sections: [
      s('Un empilement polarisé', 'L’appareil de Golgi est constitué de citernes membranaires empilées. La face cis reçoit une grande partie des cargaisons issues du RE ; les régions médiales assurent des transformations successives ; la face trans et le réseau trans-Golgi trient et expédient les produits vers plusieurs destinations.'),
      s('Maturation des glycoconjugués', 'Les chaînes oligosaccharidiques ajoutées dans le RE sont élaguées puis modifiées par des glycosidases et glycosyltransférases spécifiques des citernes. Le Golgi ajoute aussi des sucres à des protéines sur des résidus sérine ou thréonine par O-glycosylation. La maturation dépend de l’ordre d’exposition aux enzymes.'),
      s('Modifications au-delà des sucres', 'Le Golgi participe à la sulfation de certaines molécules, à la maturation protéolytique et à l’assemblage de composants membranaires ou sécrétoires. Toutes les protéines ne subissent pas toutes ces transformations. Le résultat dépend de la séquence protéique, des enzymes exprimées et du trajet suivi dans l’empilement.'),
      s('Tri au réseau trans-Golgi', 'Des signaux moléculaires dirigent les cargaisons vers la membrane plasmique, des granules de sécrétion ou des endosomes et lysosomes. Le mannose-6-phosphate cible certaines hydrolases lysosomales vers les endosomes. Une erreur de marquage peut faire sécréter une enzyme au lieu de l’adresser au compartiment où elle fonctionne.'),
      s('Transport par vésicules', 'Les vésicules bourgeonnent avec des manteaux qui sélectionnent cargaisons et membrane, puis perdent ce manteau et s’arriment à la bonne membrane. Les protéines Rab, facteurs d’attachement et SNARE contribuent à la spécificité de fusion. Le transport entre citernes et vers l’extérieur combine maturation de citernes et mouvements vésiculaires.'),
    ],
    trap: 'Le Golgi ne « fabrique » pas à lui seul une protéine : il modifie, mature et trie des cargaisons produites en amont.',
    recall: 'Quel signal permet à de nombreuses hydrolases d’être triées vers les lysosomes ?',
    answer: 'Le mannose-6-phosphate apposé sur leurs chaînes N-glycosylées est reconnu par un récepteur du réseau trans-Golgi et permet leur adressage vers les endosomes.',
    source: '4-4-the-endomembrane-system-and-proteins',
    glossary: [['Citerne', 'Sac membranaire aplati constituant une unité de l’empilement golgien.'], ['Mannose-6-phosphate', 'Marque de tri de nombreuses enzymes lysosomales.'], ['SNARE', 'Famille de protéines participant à l’arrimage et à la fusion membranaire.']]
  }),
  lesson('cell-endocytosis-exocytosis', {
    objectives: ['Distinguer phagocytose, pinocytose et endocytose médiée par récepteur', 'Décrire les étapes de l’endocytose clathrine-dépendante', 'Expliquer fusion vésiculaire et exocytose régulée'],
    sections: [
      s('Faire entrer du matériel', 'L’endocytose internalise une portion de membrane avec des molécules ou particules extracellulaires. La phagocytose concerne de grosses particules ; la pinocytose internalise du liquide et des solutés ; l’endocytose médiée par récepteur concentre sélectivement un ligand. Ces catégories diffèrent par cargaison et organisation, pas seulement par la taille de la vésicule.'),
      s('Clathrine et sélection', 'Des récepteurs liés à leurs ligands recrutent des adaptines et la clathrine sur la face cytosolique. Le manteau courbe la membrane et forme un puits. La dynamine, une GTPase, facilite le détachement de la vésicule ; le manteau est ensuite démonté et recyclé avant le tri de la cargaison.'),
      s('Trajet endosomal', 'La vésicule rejoint un endosome précoce dont le pH acide favorise parfois la dissociation ligand-récepteur. Les récepteurs peuvent retourner à la membrane tandis que la cargaison poursuit vers endosome tardif et lysosome, ou être recyclés autrement. L’endocytose règle aussi l’abondance de récepteurs et la durée d’un signal.'),
      s('Exocytose constitutive et régulée', 'L’exocytose fusionne une vésicule intracellulaire avec la membrane plasmique, libère son contenu et ajoute des lipides et protéines à la membrane. La voie constitutive fonctionne dans de nombreuses cellules. La voie régulée stocke des produits et attend un signal, souvent une hausse locale de Ca²⁺, avant fusion.'),
      s('Reconnaître la membrane cible', 'Les v-SNARE de la vésicule s’apparient avec des t-SNARE de la membrane cible ; d’autres facteurs assurent l’arrimage et le contrôle. La fusion est directionnelle et précise. La membrane ajoutée par exocytose est compensée en partie par l’endocytose, maintenant l’aire et la composition de surface.'),
    ],
    trap: 'La clathrine participe au bourgeonnement mais ne réalise pas la fusion avec l’endosome ; le manteau est généralement retiré avant cette étape.',
    recall: 'Pourquoi une endocytose médiée par récepteur peut-elle capter sélectivement une molécule pourtant peu concentrée dans le milieu ?',
    answer: 'Les récepteurs reconnaissent et concentrent spécifiquement le ligand dans les puits recouverts, ce qui enrichit la cargaison avant le bourgeonnement.',
    source: '4-4-the-endomembrane-system-and-proteins',
    glossary: [['Adaptine', 'Protéine adaptatrice qui relie récepteurs de cargaison et manteau de clathrine.'], ['Endosome', 'Compartiment de tri des molécules internalisées ou adressées aux lysosomes.'], ['Exocytose régulée', 'Fusion déclenchée par un signal après stockage de la cargaison.']]
  }),
  lesson('cell-lysosomes-autophagy', {
    objectives: ['Relier acidification lysosomale et activité des hydrolases', 'Expliquer le ciblage d’une cargaison vers le lysosome', 'Comparer autophagie et dégradation endocytaire'],
    sections: [
      s('Un compartiment de dégradation', 'Le lysosome est limité par une membrane qui sépare ses enzymes hydrolytiques du cytosol. Son pH acide est entretenu par une pompe à protons V-ATPase ; des contre-ions limitent l’accumulation de charge. Les hydrolases acides dégradent protéines, lipides, acides nucléiques et glucides en unités réutilisables.'),
      s('Protéger le cytosol', 'La plupart des hydrolases lysosomales fonctionnent mieux à pH acide ; leur fuite dans le cytosol neutre réduit leur activité mais peut contribuer à des dommages si la membrane est fortement altérée. La membrane lysosomale porte des protéines fortement glycosylées et des transporteurs qui exportent les produits de digestion.'),
      s('Acheminer la cargaison', 'Les molécules internalisées arrivent via les endosomes ; des enzymes solubles du système sécrétoire sont adressées grâce au mannose-6-phosphate. Les récepteurs de ce signal circulent entre Golgi et endosomes. Les composants membranaires destinés à la dégradation sont triés vers des vésicules intraluminales des corps multivésiculaires.'),
      s('Autophagie', 'Dans l’autophagie macroautophagique, une membrane en croissance entoure une portion de cytoplasme ou un organite pour former un autophagosome à double membrane. Celui-ci fusionne avec un lysosome ; le contenu et la membrane interne sont dégradés. Le processus recycle des nutriments et élimine des composants endommagés, surtout en réponse à des signaux métaboliques ou de stress.'),
      s('Une voie régulée', 'Les voies d’autophagie et d’endocytose ne sont pas des poubelles indépendantes : elles convergent vers des compartiments lysosomaux et répondent à des besoins de renouvellement et d’adaptation. Une hausse du flux autophagique peut refléter plus de formation d’autophagosomes ou une dégradation finale ralentie ; il faut distinguer ces deux étapes.'),
    ],
    trap: 'Observer davantage d’autophagosomes ne prouve pas que l’autophagie fonctionne mieux : ils peuvent s’accumuler parce que la fusion ou la dégradation terminale est bloquée.',
    recall: 'Pourquoi l’acidification du lysosome est-elle utile, et quelle protéine la réalise ?',
    answer: 'Le pH acide optimise les hydrolases lysosomales ; la V-ATPase transporte des protons dans la lumière en utilisant l’énergie de l’ATP.',
    source: '4-4-the-endomembrane-system-and-proteins',
    glossary: [['Hydrolase acide', 'Enzyme de dégradation dont l’activité optimale se situe à pH bas.'], ['Autophagosome', 'Vésicule à double membrane englobant du matériel cytoplasmique avant fusion lysosomale.'], ['V-ATPase', 'Pompe membranaire consommant de l’ATP pour acidifier un compartiment.']]
  }),
  lesson('cell-mitochondria-peroxisomes', {
    objectives: ['Comparer compartiments et fonctions de mitochondrie et peroxysome', 'Relier chaîne respiratoire et gradient protonique à la synthèse d’ATP', 'Expliquer le rôle des peroxysomes dans l’oxydation et la gestion du peroxyde'],
    sections: [
      s('Architecture mitochondriale', 'La mitochondrie possède une membrane externe, un espace intermembranaire, une membrane interne plissée en crêtes et une matrice. La membrane interne porte la chaîne respiratoire et l’ATP-synthase. La matrice accueille notamment le cycle de Krebs et la β-oxydation de nombreux acides gras ; les compartiments séparent des réactions incompatibles.'),
      s('Transport d’électrons et ATP', 'Les électrons issus de NADH et FADH₂ passent par des complexes respiratoires jusqu’à l’oxygène, accepteur terminal réduit en eau. Les complexes I, III et IV contribuent au pompage des protons vers l’espace intermembranaire. Le retour des protons via l’ATP-synthase entraîne la phosphorylation de l’ADP : c’est la chimiosmose.'),
      s('Contrôle du flux énergétique', 'La phosphorylation oxydative dépend de l’apport en substrats et en oxygène, mais aussi de la demande en ATP et de la disponibilité de l’ADP. Un gradient protonique peut alimenter d’autres transports ou être dissipé. Les fuites d’électrons peuvent produire des espèces réactives de l’oxygène ; antioxydants enzymatiques et non enzymatiques en limitent les effets.'),
      s('Réactions peroxysomales', 'Les peroxysomes réalisent des oxydations, notamment le raccourcissement initial de certains acides gras très longs et la dégradation de molécules. Certaines oxydases transfèrent directement des électrons à O₂ et produisent H₂O₂. La catalase transforme le peroxyde en eau et oxygène ; le compartiment limite ainsi l’exposition du cytosol.'),
      s('Des rôles complémentaires', 'Les peroxysomes n’ont pas de génome propre et importent la majorité de leurs protéines depuis le cytosol. Les mitochondries ont leur propre ADN et des ribosomes, mais dépendent aussi du noyau. Les deux organites coopèrent dans certains métabolismes lipidiques et dans la gestion redox ; ils ne se remplacent pas pour fabriquer l’ATP.'),
    ],
    trap: 'Les peroxysomes oxydent des substrats mais ne produisent pas directement l’ATP par phosphorylation oxydative comme le fait la mitochondrie.',
    recall: 'Quel gradient fait fonctionner l’ATP-synthase mitochondriale et de quel côté les protons sont-ils pompés ?',
    answer: 'La chaîne respiratoire pompe les protons de la matrice vers l’espace intermembranaire. Leur retour vers la matrice à travers l’ATP-synthase fournit l’énergie de synthèse de l’ATP.',
    source: '4-3-eukaryotic-cells',
    glossary: [['Chimiosmose', 'Couplage entre gradient électrochimique de protons et synthèse d’ATP.'], ['Crête mitochondriale', 'Repli de la membrane interne qui augmente la surface disponible pour la respiration.'], ['Catalase', 'Enzyme qui dégrade le peroxyde d’hydrogène en eau et oxygène.']],
    caseStudy: { prompt: 'Une cellule manque d’oxygène. Quelle conséquence immédiate attend-on sur le transfert final d’électrons et la phosphorylation oxydative ?', answer: 'L’oxygène étant l’accepteur terminal, le flux de la chaîne ralentit ou s’arrête ; le pompage de protons diminue, le gradient s’effondre et la production mitochondriale d’ATP baisse.' }
  }),
  lesson('cell-nucleus-ribosomes', {
    objectives: ['Distinguer enveloppe nucléaire, chromatine et nucléole', 'Décrire transcription des ARN ribosomiques et assemblage des sous-unités', 'Comparer ribosomes libres et liés au RE selon la destination protéique'],
    sections: [
      s('Noyau et chromatine', 'Le noyau abrite l’essentiel de l’ADN eucaryote. L’enveloppe nucléaire à deux membranes sépare le nucléoplasme du cytosol et se prolonge dans le RE. La chromatine associe ADN, histones et protéines ; son état de compaction varie selon l’activité et le cycle cellulaire. L’hétérochromatine est plus condensée, l’euchromatine généralement plus accessible.'),
      s('Nucléole', 'Le nucléole est une région nucléaire sans membrane où sont transcrits, maturés et assemblés une partie des ARN ribosomiques avec des protéines ribosomales. Les gènes d’ARNr sont souvent organisés en répétitions. Plusieurs nucléoles peuvent fusionner et leur taille reflète en partie l’activité de production ribosomale de la cellule.'),
      s('Fabriquer les ARN ribosomiques', 'Dans les cellules humaines, l’ARN polymérase I transcrit un précurseur contenant la majorité des séquences d’ARNr, ensuite clivé et modifié. L’ARNr 5S est transcrit séparément par l’ARN polymérase III. Les protéines ribosomales sont synthétisées dans le cytosol puis importées dans le noyau et le nucléole.'),
      s('Assembler et exporter', 'Les ARNr s’associent aux protéines pour former les sous-unités ribosomales petite et grande. Les pré-sous-unités passent par des étapes de maturation et contrôle dans le noyau avant export par les pores nucléaires. Leur assemblage final en ribosome fonctionnel se produit dans le cytosol lorsque l’ARNm et les facteurs d’initiation sont présents.'),
      s('Ribosomes selon la destination', 'Les ribosomes sont chimiquement équivalents, qu’ils soient libres ou associés au RE. Une séquence signal émergente recrute la SRP et dirige certains ribosomes vers la membrane du RE ; la protéine naissante entre alors dans la lumière ou s’insère dans la membrane. Les ribosomes libres fabriquent notamment des protéines cytosoliques et nucléaires.'),
    ],
    trap: 'Un nucléole n’est pas un organite entouré d’une membrane ; c’est un domaine nucléaire organisé autour de la biogenèse ribosomale.',
    recall: 'Les ribosomes libres et ceux liés au RE sont-ils deux types de ribosomes différents ?',
    answer: 'Non. Ils ont une composition comparable ; le ciblage dépend de la séquence de la protéine naissante, qui recrute la SRP et dirige le complexe vers le RE.',
    source: '4-3-eukaryotic-cells',
    glossary: [['Euchromatine', 'Chromatine relativement décondensée, souvent plus accessible à la transcription.'], ['Pré-sous-unité', 'Complexe immature d’ARNr et protéines avant son export et sa maturation finale.'], ['ARN polymérase I', 'Enzyme nucléolaire qui transcrit le précurseur de la majorité des ARNr.']]
  })
]

const q = (course: string, n: number, topicOrPrompt: string, promptOrOptions: string | string[], optionsOrCorrect: string[] | number[], correctOrWhy: number[] | string[], finalWhy?: string[]): Question => {
  const hasTopic = typeof promptOrOptions === 'string'
  const prompt = hasTopic ? promptOrOptions : topicOrPrompt
  const options = hasTopic ? optionsOrCorrect as string[] : promptOrOptions
  const correct = hasTopic ? correctOrWhy as number[] : optionsOrCorrect as number[]
  const why = hasTopic ? finalWhy! : correctOrWhy as string[]
  return { id: `${course}-q${n}`, course, topic: 'Biologie cellulaire', prompt, options, correct, why, difficulty: n < 3 ? 'essentiel' : 'application' }
}
export const membraneQuestions: Question[] = [
  q('cell-membrane-trafficking',1,'Quel composant rend la bicouche possible en milieu aqueux ?', ['Phospholipides amphiphiles','ADN double brin','Triglycérides uniquement','Cellulose'],[0],['Leurs têtes hydrophiles et queues hydrophobes s’orientent dans deux milieux compatibles.','L’ADN n’est pas le constituant structural principal de la membrane.','Les triglycérides n’ont pas cette organisation amphiphile de membrane.','La cellulose est un polysaccharide de paroi végétale.']),
  q('cell-membrane-trafficking',2,'Quel effet une double liaison cis a-t-elle sur une chaîne lipidique ?', ['Elle crée un coude et gêne l’empilement','Elle transforme la chaîne en glucide','Elle augmente automatiquement le nombre de protéines','Elle rend le feuillet symétrique'],[0],['Le coude réduit le compactage entre chaînes.','Une chaîne d’acide gras reste lipidique.','La composition protéique n’est pas déterminée par cette liaison.','L’asymétrie dépend de la distribution des lipides.']),
  q('cell-membrane-trafficking',3,'Où sont surtout exposés les glucides des glycoprotéines membranaires ?', ['Face extracellulaire','Face cytosolique exclusivement','Dans le cœur hydrophobe','Dans le noyau'],[0],['Ils contribuent à reconnaissance et adhérence en surface externe.','Leur orientation habituelle est extracellulaire.','Les chaînes glucidiques ne sont pas enfouies dans la bicouche.','Ils sont liés à la membrane, pas localisés au noyau.']),
  q('cell-membrane-trafficking',4,'Quel est l’effet typique du cholestérol à température élevée ?', ['Il limite la mobilité excessive des lipides','Il détruit la bicouche','Il augmente toujours la fluidité','Il remplace les protéines de transport'],[0],['Il amortit les variations et restreint les mouvements à haute température.','Il s’insère dans la bicouche.','Son effet dépend de la température.','Il ne remplace pas les protéines.']),
  q('cell-membrane-trafficking',5,'Que peut signaler une exposition externe de phosphatidylsérine ?', ['Un état associé à l’apoptose et à la reconnaissance de la cellule','Une augmentation de l’ADN nucléaire','La synthèse de cellulose','Un échange de protons dans la mitochondrie'],[0],['Cette asymétrie modifiée peut être reconnue par des phagocytes.','Le noyau n’est pas impliqué directement.','Les cellules humaines ne fabriquent pas de paroi cellulosique.','Cela ne décrit pas le gradient mitochondrial.']),
  q('cell-endoplasmic-reticulum',1,'Ciblage','Quelle molécule reconnaît une séquence signal visant le RE ?', ['SRP','Clathrine','Catalase','Actine'],[0],['La SRP cible le ribosome vers le RE.','La clathrine forme des manteaux de vésicules.','La catalase dégrade H₂O₂.','L’actine est un filament du cytosquelette.']),
  q('cell-endoplasmic-reticulum',2,'RE rugueux','Pourquoi certaines régions du RE paraissent-elles rugueuses ?', ['Des ribosomes sont associés à leur face cytosolique','Elles portent des lysosomes internes','Leur lumière contient des lipides solides','Elles sont dépourvues de membrane'],[0],['Les ribosomes fixés donnent l’aspect granuleux.','Les lysosomes sont des compartiments distincts.','Les lipides ne causent pas l’aspect rugueux.','Le RE est un réseau membranaire.']),
  q('cell-endoplasmic-reticulum',3,'Repliement','Quel destin peut attendre une protéine mal repliée dans le RE ?', ['Rétention, tentative de correction ou dégradation','Export automatique vers le noyau','Transformation en ADN','Diffusion libre dans la lumière extracellulaire'],[0],['Le RE assure un contrôle de qualité.','Le noyau n’est pas sa destination automatique.','Les protéines ne se convertissent pas en ADN.','Une protéine sécrétée nécessite export et trafic.']),
  q('cell-endoplasmic-reticulum',4,'RE lisse','Quelle fonction est classiquement associée au RE lisse ?', ['Synthèse de lipides','Traduction de tous les ARNm','Réplication chromosomique','Assemblage des sous-unités ribosomales'],[0],['Le RE lisse participe notamment à la synthèse lipidique.','Les ribosomes réalisent la traduction.','La réplication de l’ADN a lieu dans le noyau.','Les pré-sous-unités se forment dans le nucléole.']),
  q('cell-endoplasmic-reticulum',5,'Trafic','Où vont généralement les cargaisons protéiques correctement assemblées dans le RE ?', ['Vers le Golgi dans des vésicules','Directement dans l’ADN','Vers le lysosome sans tri','Dans le nucléole'],[0],['La voie sécrétoire passe classiquement par l’appareil de Golgi.','Les protéines ne s’intègrent pas à l’ADN par ce trajet.','Le ciblage lysosomal peut nécessiter maturation et tri golgiens.','Le nucléole est nucléaire.']),
  q('cell-golgi-apparatus',1,'Polarité','Quelle face du Golgi reçoit principalement les vésicules provenant du RE ?', ['Cis','Trans','Latérale uniquement','Nucléolaire'],[0],['La face cis est tournée vers le RE.','La face trans est principalement associée au tri et à l’expédition.','Les citernes ne se définissent pas ainsi.','Le nucléole appartient au noyau.']),
  q('cell-golgi-apparatus',2,'Maturation','Qu’est-ce que l’O-glycosylation ?', ['Ajout de sucres sur l’oxygène de certains résidus comme sérine ou thréonine','Ajout d’un phosphate sur l’ADN','Synthèse d’un acide gras','Élimination de toutes les chaînes glucidiques'],[0],['Le Golgi ajoute fréquemment des sucres sur le groupement hydroxyle.','Ce n’est pas une modification de l’ADN.','Les lipides ne sont pas des sucres.','Le Golgi modifie les glycannes, pas seulement les retire.']),
  q('cell-golgi-apparatus',3,'Tri','Quel signal adresse de nombreuses hydrolases vers le lysosome ?', ['Mannose-6-phosphate','Séquence d’actine','Cholestérol','Ribosome 5S'],[0],['Le marqueur est reconnu dans le réseau trans-Golgi.','L’actine n’est pas le signal lysosomal.','Le cholestérol est un lipide membranaire.','L’ARNr 5S fait partie des ribosomes.']),
  q('cell-golgi-apparatus',4,'Transport','Quel rôle ont les protéines SNARE ?', ['Aider l’arrimage et la fusion de membranes compatibles','Transcrire l’ARNm','Pomper des protons dans l’ADN','Former les microtubules'],[0],['Les SNARE participent à la reconnaissance et fusion vésiculaire.','La transcription dépend de polymérases.','Elles ne pompent pas de protons.','La tubuline constitue les microtubules.']),
  q('cell-golgi-apparatus',5,'Voie sécrétoire','Quel est le rôle principal du Golgi dans le trafic ?', ['Maturation et tri de nombreuses cargaisons','Traduction de tous les polypeptides','Production de l’ATP','Réplication de l’ADN'],[0],['Il modifie et distribue des protéines et lipides.','La traduction a lieu sur les ribosomes.','La phosphorylation oxydative est mitochondriale.','La réplication est nucléaire.']),
  q('cell-endocytosis-exocytosis',1,'Endocytose','Quelle voie internalise préférentiellement une cargaison reconnue par récepteur ?', ['Endocytose médiée par récepteur','Diffusion simple','Exocytose constitutive','Osmose'],[0],['Les récepteurs concentrent sélectivement les ligands.','La diffusion ne forme pas de vésicule sélective.','L’exocytose expulse ou sécrète du contenu.','L’osmose concerne l’eau.']),
  q('cell-endocytosis-exocytosis',2,'Clathrine','Quelle protéine facilite le détachement de certaines vésicules clathrine-dépendantes ?', ['Dynamine','Histone H3','Myosine cardiaque uniquement','ARN polymérase I'],[0],['La dynamine est une GTPase impliquée dans la scission.','Les histones organisent l’ADN.','Les myosines ne constituent pas le mécanisme de scission classique.','La polymérase I transcrit des ARNr.']),
  q('cell-endocytosis-exocytosis',3,'Tri endosomal','Que peut-il arriver à un récepteur après dissociation du ligand dans l’endosome précoce ?', ['Il peut être recyclé vers la membrane','Il devient nécessairement un lysosome','Il est converti en ATP','Il migre obligatoirement au noyau'],[0],['Le recyclage des récepteurs est fréquent.','Un récepteur n’est pas un organite.','Il n’y a pas conversion en ATP.','Le trajet dépend des signaux de tri.']),
  q('cell-endocytosis-exocytosis',4,'Exocytose régulée','Quel signal déclenche souvent la fusion de vésicules sécrétoires régulées ?', ['Une hausse locale de Ca²⁺','Une baisse de l’ADN','Une absence de membrane','Une hausse obligatoire de NaCl extracellulaire'],[0],['Le calcium intracellulaire déclenche de nombreuses sécrétions régulées.','L’ADN n’est pas le déclencheur général.','La fusion nécessite des membranes.','Ce n’est pas un signal obligatoire commun.']),
  q('cell-endocytosis-exocytosis',5,'Compensation membranaire','Pourquoi endocytose et exocytose sont-elles souvent coordonnées ?', ['Pour renouveler le contenu tout en régulant surface et composition membranaires','Pour empêcher tout trafic vésiculaire','Pour répliquer l’ADN','Pour produire du collagène extracellulaire'],[0],['L’ajout de membrane par fusion est équilibré en partie par internalisation.','Les deux processus sont actifs dans les cellules.','La réplication est nucléaire.','Le collagène est synthétisé puis sécrété.']),
  q('cell-lysosomes-autophagy',1,'Acidité','Quelle protéine maintient le pH lysosomal acide ?', ['V-ATPase','ATP-synthase mitochondriale','Clathrine','Tubuline'],[0],['La V-ATPase pompe des protons dans le lysosome.','L’ATP-synthase exploite le gradient mitochondrial.','La clathrine forme certains manteaux.','La tubuline forme des microtubules.']),
  q('cell-lysosomes-autophagy',2,'Hydrolases','Pourquoi les hydrolases lysosomales sont-elles adaptées au compartiment ?', ['Elles ont une activité optimale à pH acide','Elles catalysent la réplication de l’ADN','Elles remplacent les protéines membranaires','Elles produisent de l’oxygène à partir d’ATP'],[0],['Le milieu acide favorise leur activité enzymatique.','Les enzymes de réplication sont nucléaires.','Les hydrolases dégradent des molécules.','La V-ATPase consomme l’ATP pour pomper H⁺.']),
  q('cell-lysosomes-autophagy',3,'Autophagie','Quelle structure entoure le matériel cytoplasmique avant fusion lysosomale ?', ['Autophagosome à double membrane','Nucléole','Ribosome libre','Crête mitochondriale'],[0],['L’autophagosome apporte son contenu au lysosome.','Le nucléole organise la biogenèse ribosomale.','Un ribosome traduit les ARNm.','La crête est une membrane mitochondriale.']),
  q('cell-lysosomes-autophagy',4,'Flux','Une accumulation d’autophagosomes prouve-t-elle une dégradation autophagique accrue ?', ['Non, la dégradation finale peut être ralentie','Oui, toujours','Oui, si le pH cytosolique baisse','Non, car les autophagosomes sont des ribosomes'],[0],['Une formation accrue et un blocage terminal peuvent tous deux les accumuler.','Le nombre seul n’établit pas le flux.','Le pH cytosolique ne répond pas à cette question.','Ce sont des vésicules à double membrane.']),
  q('cell-lysosomes-autophagy',5,'Trafic lysosomal','Quel marqueur dirige des hydrolases solubles via le Golgi ?', ['Mannose-6-phosphate','Phosphatidylsérine externe','ADN mitochondrial','Cholestérol libre'],[0],['Ce signal est reconnu par un récepteur de tri.','Ce signal concerne notamment la reconnaissance apoptotique.','Il n’adresse pas les hydrolases du Golgi.','Le cholestérol ne constitue pas le marqueur de tri.']),
  q('cell-mitochondria-peroxisomes',1,'Compartiments','Où se trouvent la chaîne respiratoire mitochondriale et l’ATP-synthase ?', ['Membrane interne','Membrane externe','Nucléole','Membrane lysosomale'],[0],['Les complexes sont dans la membrane interne et les crêtes.','La membrane externe ne porte pas la chaîne complète.','Le nucléole assemble des ribosomes.','Le lysosome n’assure pas la phosphorylation oxydative.']),
  q('cell-mitochondria-peroxisomes',2,'Gradient','Dans quel sens les complexes respiratoires pompent-ils les protons ?', ['De la matrice vers l’espace intermembranaire','Du cytosol vers le noyau','Du lysosome vers le Golgi','De l’espace intermembranaire vers la matrice uniquement'],[0],['Cela crée le gradient utilisé au retour par l’ATP-synthase.','Ce n’est pas un transport nucléaire.','Les compartiments ne sont pas connectés de cette manière.','Le flux de retour via ATP-synthase ramène les protons à la matrice.']),
  q('cell-mitochondria-peroxisomes',3,'Accepteur final','Quel est l’accepteur terminal des électrons de la chaîne respiratoire aérobie ?', ['O₂, réduit en H₂O','CO₂, réduit en glucose','NAD⁺, réduit en oxygène','H₂O, réduite en protons'],[0],['L’oxygène capte les électrons et des protons pour former de l’eau.','Le CO₂ n’est pas l’accepteur terminal.','Le NAD⁺ est réduit plus tôt dans le métabolisme.','L’eau est le produit final de cette réduction.']),
  q('cell-mitochondria-peroxisomes',4,'Peroxysome','Quelle enzyme neutralise notamment le H₂O₂ dans les peroxysomes ?', ['Catalase','ATP-synthase','SRP','Kinésine'],[0],['La catalase décompose le peroxyde d’hydrogène.','L’ATP-synthase produit l’ATP.','La SRP cible des protéines.','La kinésine déplace des cargaisons le long des microtubules.']),
  q('cell-mitochondria-peroxisomes',5,'Métabolisme','Quelle différence fonctionnelle résume le mieux les deux organites ?', ['Mitochondrie : phosphorylation oxydative ; peroxysome : oxydations avec gestion du peroxyde','Peroxysome : production principale d’ATP ; mitochondrie : digestion acide','Les deux sont des ribosomes','Aucune différence de compartimentation'],[0],['La chaîne respiratoire et l’ATP-synthase sont mitochondriales ; les oxydases peroxysomales peuvent former H₂O₂.','Ces fonctions sont inversées.','Ce sont des organites membraneux.','Leurs enzymes et compartiments diffèrent.']),
  q('cell-nucleus-ribosomes',1,'Nucléole','Quelle activité est fortement associée au nucléole ?', ['Transcription et assemblage de composants ribosomaux','Glycolyse','Dégradation lysosomale','Oxydation des acides gras très longs'],[0],['Le nucléole participe à la biogenèse ribosomale.','La glycolyse a lieu dans le cytosol.','La digestion a lieu dans les lysosomes.','Certaines oxydations ont lieu dans les peroxysomes.']),
  q('cell-nucleus-ribosomes',2,'ARN polymérase','Quelle polymérase transcrit le précurseur de la majorité des ARNr ?', ['ARN polymérase I','ARN polymérase II uniquement','ADN polymérase','Transcriptase inverse'],[0],['La polymérase I transcrit les ARNr majeurs dans le nucléole.','La polymérase II transcrit surtout les ARNm.','Elle réplique l’ADN.','Elle copie un ARN en ADN dans certains systèmes.']),
  q('cell-nucleus-ribosomes',3,'Chromatine','Quelle description correspond à l’hétérochromatine ?', ['Chromatine plus condensée, souvent moins accessible','ARN libre dans le cytosol','Réseau de microtubules','Membrane du Golgi'],[0],['La compaction est généralement associée à une accessibilité réduite.','Ce n’est pas un ARN.','Les microtubules sont cytosquelettiques.','Le Golgi est un organite distinct.']),
  q('cell-nucleus-ribosomes',4,'Ribosomes','Les ribosomes liés au RE diffèrent-ils chimiquement des ribosomes libres ?', ['Non ; le ciblage dépend de la séquence de la protéine naissante','Oui, ils ont tous un ARN différent','Oui, les libres ne traduisent jamais','Non, car aucun ribosome ne peut se fixer au RE'],[0],['Ils sont équivalents et peuvent être dirigés par SRP.','La composition de base est comparable.','Les ribosomes libres traduisent des protéines.','La fixation au RE est possible.']),
  q('cell-nucleus-ribosomes',5,'Export','Que deviennent les pré-sous-unités ribosomales après maturation nucléaire ?', ['Elles sont exportées vers le cytosol','Elles restent toujours dans le nucléole','Elles se transforment en ADN','Elles sont sécrétées dans le sang'],[0],['Les sous-unités rejoignent le cytosol avant assemblage fonctionnel.','Le nucléole n’est pas leur destination finale.','Les protéines et ARN ne se convertissent pas en ADN ainsi.','Elles ne sont pas des protéines sécrétées.'])
]
