import { X, Scissors, Tag, RotateCcw, Copy } from 'lucide-react'
import type { CutSettings, LabelMode, Opacities, GroupId } from './types'
import {defaultOpacity,defaultCut} from './viewState'
export default function ExplorerTools(p:{cut:CutSettings;setCut:(c:CutSettings)=>void;opacity:Opacities;setOpacity:(o:Opacities)=>void;labels:LabelMode;setLabels:(m:LabelMode)=>void;groups:{id:GroupId;name:string}[];close:()=>void;share:()=>void;status:string}) {
 return <aside className="detail-panel tools-panel" aria-label="Outils d’exploration"><div className="detail-heading"><span className="eyebrow">PERSONNALISER LA VUE</span><button className="icon-button" aria-label="Fermer les outils" onClick={p.close}><X size={18}/></button></div><div className="detail-content">
 <h2>Voir autrement.</h2><section className="tool-section"><h3><Scissors size={16}/> Coupe anatomique</h3><label className="setting-check"><input type="checkbox" checked={p.cut.enabled} onChange={e=>p.setCut({...p.cut,enabled:e.target.checked})}/>Activer la coupe</label>{p.cut.enabled&&<><label>Plan de coupe<select aria-label="Plan de coupe" value={p.cut.axis} onChange={e=>p.setCut({...p.cut,axis:e.target.value as CutSettings['axis']})}><option value="z">Coronal · avant / arrière</option><option value="x">Sagittal · gauche / droite</option><option value="y">Axial · haut / bas</option></select></label><label>Position <output>{Math.round(p.cut.position*100)} %</output><input aria-label="Position de coupe" type="range" min="-100" max="100" value={Math.round(p.cut.position*100)} onChange={e=>p.setCut({...p.cut,position:Number(e.target.value)/100})}/></label><button className="subtle-action" onClick={()=>p.setCut({...p.cut,flipped:!p.cut.flipped})}>Inverser le côté conservé</button><label className="setting-check"><input type="checkbox" checked={p.cut.guide} onChange={e=>p.setCut({...p.cut,guide:e.target.checked})}/>Afficher le plan de repère</label><p className="tool-note">La coupe ouvre les surfaces du modèle. Elle ne recrée pas les tissus internes ni une image médicale.</p></>}</section>
 <section className="tool-section"><h3><Tag size={16}/> Repères sur le corps</h3><select aria-label="Étiquettes anatomiques" value={p.labels} onChange={e=>p.setLabels(e.target.value as LabelMode)}><option value="off">Masquer les étiquettes</option><option value="names">Afficher les noms</option><option value="revision">Révision · numéros uniquement</option></select><p className="tool-note">Quelques repères suivent la vue ; ceux qui se chevauchent sont masqués.</p></section>
 <section className="tool-section"><h3>Opacité des couches</h3>{p.groups.map(g=><label key={g.id} className="opacity-control">{g.name}<output>{Math.round(p.opacity[g.id]*100)} %</output><input type="range" aria-label={`Opacité ${g.name}`} min="0" max="100" value={Math.round(p.opacity[g.id]*100)} onChange={e=>p.setOpacity({...p.opacity,[g.id]:Number(e.target.value)/100})}/></label>)}</section>
 <button className="subtle-action" onClick={()=>{p.setOpacity(defaultOpacity);p.setCut(defaultCut);p.setLabels('off')}}><RotateCcw size={14}/>Rétablir les réglages visuels</button><button className="primary-action" onClick={p.share}><Copy size={14}/>Partager cette vue exacte</button><p role="status">{p.status}</p>{p.status && p.status!=="Lien copié !" && <input aria-label="Lien de la vue" readOnly value={window.location.href} onFocus={e=>e.target.select()}/>}
 </div></aside>
}
