import type {Course} from './curriculum'
import {courseSupport} from './courseSupport'
const base='https://openstax.org/books/anatomy-and-physiology-2e/pages/'
export const breastCourses:Course[]=[{
 id:'anat-breast',title:'Sein : glande mammaire, conduits et lactation',category:'Anatomie',tag:'Thorax',minutes:10,structure:'HRA-region-breast',
 objectives:['Distinguer enveloppe, tissu adipeux et tissu glandulaire','Reconstituer le trajet de la sécrétion','Distinguer production et éjection du lait'],
 sections:[
 {title:'Lire la région en trois dimensions',text:'Commencez par faire tourner le modèle. Identifiez le mamelon, l’aréole et les volumes glandulaires. Masquez ensuite une structure sélectionnée pour observer celles situées derrière elle. La couleur sert au repérage : elle ne définit ni un tissu normal ni une maladie. Les deux côtés sont représentés par les maillages féminins HRA ; les proportions de cette référence ne décrivent pas toutes les personnes.'},
 {title:'Distinguer les tissus',text:'Le sein associe notamment tissu glandulaire, tissu adipeux et tissu conjonctif. Son volume externe ne mesure donc pas directement la quantité de tissu sécréteur. Dans l’atlas, comparez les lobes mammaires et les volumes adipeux ; ne déduisez pas une capacité fonctionnelle de leur taille. La silhouette et l’organisation interne constituent deux niveaux de lecture différents.'},
 {title:'Des unités sécrétrices aux conduits',text:'Pendant la lactation, les alvéoles mammaires produisent la sécrétion qui rejoint les conduits. Des cellules myoépithéliales contribuent à sa progression par contraction. Pour réviser, dessinez un trajet orienté depuis une unité sécrétrice jusqu’au mamelon. Le modèle régional montre des structures macroscopiques : il ne permet pas d’observer chaque cellule ou chaque alvéole histologique.'},
 {title:'Mamelon et aréole',text:'Le mamelon et l’aréole sont deux repères distincts. Les conduits débouchent au niveau du mamelon ; l’aréole correspond à la région pigmentée qui l’entoure. Retrouvez-les séparément dans la recherche, puis vérifiez leur relation dans le volume. Une vue externe seule ne suffit pas à reconstruire la disposition des tissus profonds.'},
 {title:'Production et éjection : deux mécanismes',text:'La prolactine participe à la production du lait. L’ocytocine intervient dans son éjection en favorisant la contraction myoépithéliale. Ces mécanismes sont coordonnés mais ne sont pas synonymes. Pour expliquer le processus, distinguez toujours la fabrication de la sécrétion de son déplacement vers l’extérieur.'},
 {title:'Construire une explication complète',text:'Présentez successivement les repères externes, les tissus internes, le trajet des conduits et les deux mécanismes hormonaux. À chaque étape, indiquez ce qui est visible dans l’atlas et ce qui relève du cours de physiologie ou d’histologie. Cette méthode évite de transformer une belle image en explication suffisante : le modèle situe les structures, tandis que le texte explicite leur fonctionnement.'}
 ],
 glossary:[['Tissu adipeux','Tissu graisseux contribuant au volume du sein.'],['Conduit lactifère','Voie de transport de la sécrétion mammaire.'],['Prolactine','Hormone participant à la production du lait.'],['Ocytocine','Hormone participant à l’éjection par contraction myoépithéliale.']],
 trap:'Une sécrétion produite n’est pas nécessairement déjà éjectée : production et éjection sont deux étapes différentes.',
 recall:'Quelle distinction faire entre les rôles de la prolactine et de l’ocytocine ?',answer:'La prolactine participe à la production ; l’ocytocine favorise l’éjection.',
 caseStudy:{prompt:'Un étudiant montre le volume adipeux et affirme que tout ce volume fabrique du lait. Quelle confusion fait-il ?',answer:'Il confond volume du sein et tissu sécréteur. Le tissu adipeux contribue au volume ; la sécrétion dépend des structures glandulaires spécialisées. Un maillage macroscopique ne permet pas de compter les cellules sécrétrices.'},
 source:base+'28-6-lactation',sources:[{label:'OpenStax · Glande mammaire et lactation',url:base+'28-6-lactation'},{label:'OpenStax · Appareil reproducteur ovarien',url:base+'27-2-anatomy-and-physiology-of-the-ovarian-reproductive-system'}]
}]
export const breastSupport=courseSupport(breastCourses)
breastSupport.diagrams['anat-breast']={title:'Produire, transporter, éjecter',caption:'Schéma fonctionnel : ces étapes ne représentent pas des compartiments à l’échelle.',kind:'flow',nodes:[{label:'Production',detail:'La sécrétion est produite par les cellules spécialisées ; la prolactine participe à sa régulation.'},{label:'Alvéoles',detail:'La sécrétion rejoint la lumière des unités sécrétrices.'},{label:'Conduits',detail:'Le réseau conduit la sécrétion vers les débouchés du mamelon.'},{label:'Éjection',detail:'L’ocytocine favorise la contraction myoépithéliale qui participe au déplacement du lait.'}]}
