import type {Course} from './curriculum'
const base='https://openstax.org/books/anatomy-and-physiology-2e/pages/'
type Chapter=Omit<Course,'tag'|'minutes'|'source'|'sources'> & {references:string[]}
const content:Chapter[]=[
 {id:'organelles',title:'La cellule : organites et trafic des protéines',category:'Biologie cellulaire',structure:null,objectives:['Relier chaque compartiment à sa fonction','Reconstituer le trajet d’une protéine sécrétée'],sections:[
 {title:'Une organisation en compartiments',text:'Le cytosol est le milieu liquide intracellulaire. Les organites délimitent des environnements spécialisés : leurs membranes permettent de séparer des réactions et de contrôler les échanges. Le noyau conserve l’ADN ; ses pores assurent les échanges avec le cytoplasme.'},
 {title:'Produire une protéine exportée',text:'Les ribosomes traduisent un ARN messager. Pour une protéine engagée dans la voie de sécrétion, la synthèse se poursuit au réticulum endoplasmique rugueux. Des vésicules transportent ensuite le produit vers l’appareil de Golgi, où il est modifié et trié.'},
 {title:'Énergie et renouvellement',text:'Les mitochondries participent à la production d’ATP. Les lysosomes dégradent du matériel grâce à leurs enzymes. Une cellule spécialisée ne possède pas tous les compartiments dans les mêmes proportions : son organisation accompagne son activité.'},
 {title:'Lire une chaîne fonctionnelle',text:'Pour expliquer une sécrétion, suivez le produit : information nucléaire, ARN messager, traduction, maturation, transport puis exocytose. Ne confondez pas le déplacement de la protéine avec celui de son information génétique.'}],flow:['ARN messager','Ribosome / réticulum','Golgi','Vésicule','Exocytose'],glossary:[['Cytosol','Phase liquide du cytoplasme.'],['Exocytose','Fusion d’une vésicule avec la membrane plasmique.']],caseStudy:{prompt:'Une protéine est produite mais reste retenue avant le Golgi. Peut-on conclure que sa traduction n’a pas eu lieu ?',answer:'Non. Sa présence indique une synthèse ; le blocage peut concerner le transport ou la maturation. Il faut distinguer les étapes avant de localiser le défaut.'},trap:'Tous les ribosomes ne sont pas fixés au réticulum.',recall:'Retracez le parcours d’une protéine sécrétée.',answer:'Traduction au réticulum rugueux, transport vésiculaire, Golgi, vésicule de sécrétion puis exocytose.',references:['3-2-the-cytoplasm-and-cellular-organelles','3-4-protein-synthesis']},
 {id:'gene-expression',title:'De l’ADN à la protéine',category:'Génétique',structure:null,objectives:['Distinguer réplication, transcription et traduction','Expliquer la maturation d’un ARN'],sections:[
 {title:'Conserver ou exprimer une information',text:'La réplication produit de l’ADN à partir d’ADN avant une division. La transcription produit un ARN à partir d’un brin matrice d’ADN. La traduction utilise un ARN messager pour assembler une chaîne d’acides aminés.'},
 {title:'Maturer le message',text:'Chez les cellules humaines, le pré-ARN messager subit notamment un épissage : les introns sont retirés et les exons raccordés. Des épissages différents peuvent produire plusieurs ARN à partir d’un même gène.'},
 {title:'Lire les codons',text:'Le ribosome lit l’ARN messager par triplets. Les ARN de transfert apportent les acides aminés ; leur anticodon s’apparie au codon. Les codons stop terminent la traduction sans coder un acide aminé.'},
 {title:'Raisonner sur une modification',text:'Modifier une séquence ne signifie pas automatiquement modifier une protéine. Il faut préciser la région touchée et la conséquence sur l’ARN ou le codon. Le code génétique est redondant : plusieurs codons peuvent désigner le même acide aminé.'}],flow:['ADN','Transcription','ARN mature','Traduction','Polypeptide'],glossary:[['Codon','Triplet de nucléotides de l’ARN messager.'],['Épissage','Retrait des introns et jonction des exons.']],caseStudy:{prompt:'Deux codons différents désignent le même acide aminé. Une substitution entre eux change-t-elle forcément la séquence protéique ?',answer:'Non : dans ce cas, la séquence en acides aminés reste identique. Cela illustre la redondance du code.'},trap:'La transcription ne fabrique pas directement une protéine.',recall:'Quel intermédiaire relie un gène codant à un ribosome ?',answer:'L’ARN messager mature.',references:['3-4-protein-synthesis','3-3-the-nucleus-and-dna-replication']},
 {id:'cell-cycle',title:'Cycle cellulaire et mitose',category:'Génétique',structure:null,objectives:['Ordonner les étapes du cycle','Distinguer chromosome et chromatide'],sections:[
 {title:'Préparer la division',text:'L’interphase comprend G1, S et G2. La cellule croît et prépare sa division ; la réplication de l’ADN a lieu en phase S. L’interphase est donc une période active.'},
 {title:'Dupliquer sans compter deux fois',text:'Après réplication, un chromosome comporte deux chromatides sœurs reliées au niveau du centromère. La quantité d’ADN augmente ; le nombre de chromosomes, comptés par leurs centromères, ne double pas à cette étape.'},
 {title:'Distribuer les copies',text:'Au cours de la mitose, les chromosomes se condensent, s’alignent puis leurs chromatides sœurs se séparent. La division nucléaire est suivie ou accompagnée de la cytocinèse, qui répartit le cytoplasme.'},
 {title:'Contrôler la progression',text:'Les points de contrôle contribuent à éviter la poursuite d’un cycle quand l’ADN est endommagé ou que la distribution des chromosomes est incorrecte. Certaines cellules quittent le cycle et entrent en G0.'}],flow:['G1','S : réplication','G2','Mitose','Cytocinèse'],glossary:[['Chromatides sœurs','Copies d’un chromosome après réplication.'],['Cytocinèse','Division du cytoplasme.']],caseStudy:{prompt:'Une cellule possède 46 chromosomes avant la phase S. En G2, combien compte-t-on de chromosomes et de chromatides ?',answer:'46 chromosomes à deux chromatides, soit 92 chromatides. On compte les chromosomes par leurs centromères avant la séparation.'},trap:'Doubler l’ADN n’est pas doubler le nombre de chromosomes en G2.',recall:'Quand les chromatides sœurs se séparent-elles ?',answer:'Lors de l’anaphase de la mitose.',references:['3-5-cell-growth-and-division','3-3-the-nucleus-and-dna-replication']},
 {id:'neuronal-signal',title:'Potentiel d’action et synapse',category:'Neurophysiologie',structure:'FMA50801',objectives:['Expliquer un signal électrique neuronal','Relier calcium et transmission synaptique'],sections:[
 {title:'Un potentiel de membrane',text:'Les concentrations ioniques et la perméabilité membranaire créent une différence de potentiel. Au repos, l’intérieur du neurone est généralement négatif par rapport à l’extérieur. Un potentiel gradué peut rapprocher la membrane du seuil.'},
 {title:'Déclencher le potentiel d’action',text:'Dans le modèle classique de l’axone, l’entrée de sodium par des canaux voltage-dépendants provoque la dépolarisation. L’inactivation de ces canaux et la sortie de potassium contribuent à la repolarisation.'},
 {title:'Coder et propager',text:'Une fois le seuil atteint, le potentiel d’action suit la loi du tout ou rien. L’intensité d’un stimulus peut être codée par la fréquence des décharges. La myéline permet une conduction saltatoire entre les nœuds.'},
 {title:'Traverser une synapse chimique',text:'L’arrivée du signal ouvre des canaux calciques présynaptiques. L’entrée de calcium déclenche la libération du neurotransmetteur. Celui-ci agit sur des récepteurs postsynaptiques et peut favoriser ou freiner un nouveau signal.'}],flow:['Potentiel d’action','Entrée de Ca²⁺','Libération du médiateur','Récepteur postsynaptique'],glossary:[['Dépolarisation','Potentiel devenant moins négatif.'],['Synapse','Zone de communication entre cellules.']],caseStudy:{prompt:'Si l’entrée de calcium présynaptique est empêchée, quelle étape est directement compromise ?',answer:'La libération vésiculaire du neurotransmetteur. Le signal électrique peut arriver sans transmission chimique efficace.'},trap:'Un stimulus plus fort ne produit pas simplement un potentiel d’action plus grand.',recall:'Quel ion déclenche la libération présynaptique ?',answer:'Le calcium, entrant dans la terminaison présynaptique.',references:['12-4-the-action-potential','12-5-communication-between-neurons']},
 {id:'muscle-contraction',title:'Du signal nerveux à la contraction musculaire',category:'Physiologie',structure:null,objectives:['Décrire le sarcomère','Expliquer les rôles du calcium et de l’ATP'],sections:[
 {title:'Une organisation emboîtée',text:'Un muscle squelettique contient des fibres, qui sont des cellules. Leurs myofibrilles associent des sarcomères répétés. Les filaments fins d’actine et épais de myosine s’y chevauchent.'},
 {title:'Libérer l’accès à l’actine',text:'Le signal électrique se propage sur la membrane et dans les tubules T. Le réticulum sarcoplasmique libère du calcium. Sa fixation à la troponine déplace la tropomyosine et rend accessibles les sites de liaison.'},
 {title:'Faire glisser les filaments',text:'Les têtes de myosine réalisent des cycles d’attachement et de mouvement. Les filaments glissent sans raccourcir eux-mêmes. La fixation d’ATP permet le détachement ; son hydrolyse prépare un nouveau cycle.'},
 {title:'Relâcher activement',text:'La relaxation exige la diminution du calcium cytosolique. Son retour vers le réticulum utilise des pompes consommant de l’ATP. L’énergie n’est donc pas nécessaire uniquement pendant le raccourcissement.'}],flow:['Excitation','Libération de Ca²⁺','Ponts actine–myosine','Recapture de Ca²⁺'],glossary:[['Sarcomère','Unité contractile entre deux stries Z.'],['Réticulum sarcoplasmique','Réserve intracellulaire de calcium.']],caseStudy:{prompt:'Un étudiant affirme que la relaxation ne coûte aucune énergie. Quelle étape contredit cette idée ?',answer:'La recapture du calcium par des pompes utilisant l’ATP. Le détachement actine–myosine nécessite aussi la fixation d’ATP.'},trap:'Les filaments ne deviennent pas plus courts pendant la contraction.',recall:'Sur quelle protéine le calcium se fixe-t-il dans le muscle squelettique ?',answer:'La troponine.',references:['10-2-skeletal-muscle','10-3-muscle-fiber-contraction-and-relaxation']},
 {id:'blood',title:'Le sang : plasma et éléments figurés',category:'Hématologie',structure:null,objectives:['Distinguer plasma et cellules sanguines','Relier production et fonction'],sections:[
 {title:'Un tissu circulant',text:'Le sang associe une phase liquide, le plasma, et des éléments figurés. Le plasma contient de l’eau, des protéines et des solutés. Il transporte des substances et participe aux équilibres internes.'},
 {title:'Transporter, défendre, obturer',text:'Les érythrocytes transportent les gaz grâce à l’hémoglobine. Les leucocytes participent aux défenses. Les plaquettes sont des fragments cellulaires impliqués dans l’hémostase, et non des globules rouges miniatures.'},
 {title:'Renouveler les éléments',text:'L’hématopoïèse produit les éléments figurés à partir de cellules souches. Chez l’adulte, la moelle osseuse rouge joue ce rôle. Des signaux régulent les différentes lignées selon les besoins.'},
 {title:'Lire une proportion',text:'L’hématocrite exprime la fraction volumique occupée par les globules rouges. Une variation peut refléter un changement des globules rouges ou du volume plasmatique. Une proportion ne suffit pas à identifier sa cause.'}],glossary:[['Hématocrite','Fraction du volume sanguin occupée par les érythrocytes.'],['Hématopoïèse','Production des éléments figurés du sang.']],caseStudy:{prompt:'Si le volume plasmatique diminue sans changement immédiat des globules rouges, comment évolue l’hématocrite ?',answer:'Il augmente : les globules rouges représentent une fraction plus grande du volume total.'},trap:'Les plaquettes sont des fragments cellulaires.',recall:'Où se déroule principalement l’hématopoïèse adulte ?',answer:'Dans la moelle osseuse rouge.',references:['18-1-an-overview-of-blood','18-2-production-of-the-formed-elements']},
 {id:'hemodynamics',title:'Débit, pression et résistance vasculaire',category:'Biophysique',structure:'FMA7088',objectives:['Utiliser débit = différence de pression / résistance','Distinguer débit et vitesse'],sections:[
 {title:'Un gradient fait circuler',text:'Le débit est un volume par unité de temps. Il dépend de la différence de pression entre deux points et de la résistance du trajet : Q = ΔP / R. Une pression isolée ne décrit donc pas tout le mouvement.'},
 {title:'Agir sur la résistance',text:'Le calibre vasculaire influence fortement la résistance. Une vasoconstriction augmente la résistance ; à différence de pression constante, elle réduit le débit. Les artérioles constituent un lieu majeur de régulation.'},
 {title:'Distribuer les échanges',text:'Les artères conduisent le sang depuis le cœur, les veines le ramènent. Les capillaires offrent une paroi fine favorable aux échanges. Le sens du flux définit artère et veine, indépendamment de l’oxygénation.'},
 {title:'Ne pas confondre les grandeurs',text:'La vitesse correspond à une distance par unité de temps. À débit donné, une plus grande section totale donne une vitesse moyenne plus faible. Dans les réseaux, il faut considérer l’ensemble des vaisseaux parallèles.'}],glossary:[['Débit','Volume transporté par unité de temps.'],['Résistance','Opposition à l’écoulement.']],caseStudy:{prompt:'À ΔP constant, une résistance passe de R à 2R. Que devient Q ?',answer:'Q est divisé par deux, puisque Q = ΔP / R. Cette conclusion suppose que la différence de pression reste constante.'},trap:'Une veine n’est pas définie par un sang pauvre en oxygène.',recall:'Quelle condition faut-il préciser pour prédire l’effet d’une résistance doublée ?',answer:'La différence de pression doit être maintenue constante.',references:['20-2-blood-flow-blood-pressure-and-resistance','20-1-structure-and-function-of-blood-vessels']},
 {id:'ventilation',title:'Ventilation et échanges respiratoires',category:'Physiologie',structure:'FMA7309',objectives:['Expliquer l’inspiration calme','Calculer la ventilation alvéolaire'],sections:[
 {title:'Déplacer l’air',text:'Lors de l’inspiration calme, le diaphragme se contracte et le volume thoracique augmente. La pression alvéolaire devient inférieure à la pression atmosphérique : l’air entre. L’expiration calme repose principalement sur le recul élastique.'},
 {title:'Distinguer volume utile et espace mort',text:'Une partie du volume courant reste dans les voies conductrices. La ventilation minute vaut volume courant × fréquence. La ventilation alvéolaire s’estime par (volume courant − espace mort) × fréquence.'},
 {title:'Échanger par diffusion',text:'Les gaz traversent la barrière alvéolocapillaire selon leurs gradients de pression partielle. Une grande surface et une faible épaisseur favorisent les échanges. Ventiler les alvéoles ne suffit pas si elles sont mal perfusées.'},
 {title:'Comparer deux respirations',text:'Des respirations très rapides et superficielles peuvent renouveler surtout l’espace mort. Deux ventilations minutes identiques ne garantissent donc pas deux ventilations alvéolaires identiques.'}],glossary:[['Espace mort','Volume ventilé ne participant pas aux échanges dans le modèle considéré.'],['Perfusion','Circulation sanguine d’un territoire.']],caseStudy:{prompt:'Exercice : volume courant 500 mL, espace mort 150 mL, fréquence 12/min. Calculez la ventilation alvéolaire.',answer:'(500 − 150) × 12 = 4 200 mL/min, soit 4,2 L/min. La ventilation minute totale est 6 L/min. Valeurs choisies pour l’exercice.'},trap:'Ventilation minute et ventilation alvéolaire ne sont pas identiques.',recall:'Quel gradient commande la diffusion d’un gaz ?',answer:'Son gradient de pression partielle.',references:['22-3-the-process-of-breathing','22-4-gas-exchange']},
 {id:'fluid-balance',title:'Compartiments hydriques et équilibre de l’eau',category:'Physiologie',structure:'FMA7204',objectives:['Situer plasma et liquide interstitiel','Relier osmose et régulation rénale'],sections:[
 {title:'Délimiter les compartiments',text:'Le liquide intracellulaire est à l’intérieur des cellules. Le compartiment extracellulaire comprend notamment plasma et liquide interstitiel. Le plasma est intravasculaire ; le liquide interstitiel entoure les cellules des tissus.'},
 {title:'Déplacer l’eau',text:'L’eau franchit les membranes selon les gradients osmotiques. La tonicité dépend des solutés qui ne traversent pas librement la membrane considérée. Elle permet de prévoir le changement de volume cellulaire.'},
 {title:'Ajuster les pertes',text:'La soif contribue aux apports. Les reins ajustent les pertes urinaires ; l’hormone antidiurétique augmente la réabsorption d’eau dans les segments rénaux sensibles. Le volume et la concentration des urines sont donc variables.'},
 {title:'Raisonner en bilan',text:'Pour un intervalle donné, comparez entrées et sorties d’eau. Une perte nette ne renseigne pas seule sur tous les électrolytes : préciser eau et solutés évite de confondre bilan hydrique et bilan sodé.'}],glossary:[['Interstitiel','Situé entre les cellules des tissus.'],['ADH','Hormone antidiurétique favorisant la conservation rénale d’eau.']],caseStudy:{prompt:'Une cellule est placée dans un milieu hypertonique contenant un soluté non pénétrant. Que devient son volume ?',answer:'L’eau sort de la cellule et son volume diminue. Il faut connaître la perméabilité au soluté pour raisonner sur la tonicité.'},trap:'Le plasma est extracellulaire, même s’il est à l’intérieur des vaisseaux.',recall:'Quel effet rénal de l’ADH conserve l’eau ?',answer:'Une augmentation de la réabsorption d’eau dans les segments sensibles.',references:['26-1-body-fluids-and-fluid-compartments','26-2-water-balance']},
 {id:'endocrine',title:'Hormones, récepteurs et rétrocontrôle',category:'Endocrinologie',structure:'FMA7198',objectives:['Identifier une cellule cible','Comparer récepteurs membranaires et intracellulaires'],sections:[
 {title:'Un message à distance',text:'Une hormone endocrine rejoint la circulation et agit sur des cellules possédant un récepteur adapté. Sa présence dans le sang ne signifie pas que toutes les cellules répondent. La concentration et la sensibilité des cibles participent à l’effet.'},
 {title:'Reconnaître le récepteur',text:'Les hormones peptidiques se lient généralement à des récepteurs membranaires. Les hormones stéroïdes peuvent traverser la membrane et agir via des récepteurs intracellulaires. La nature du message oriente le mécanisme de réponse.'},
 {title:'Transmettre et amplifier',text:'L’activation d’un récepteur membranaire peut déclencher une cascade de seconds messagers. Un petit signal initial peut ainsi produire une réponse importante. La réponse dépend du réseau intracellulaire de la cellule cible.'},
 {title:'Fermer la boucle',text:'Dans un rétrocontrôle négatif, la réponse ou l’hormone produite freine les étapes qui l’ont déclenchée. Pour lire un axe hormonal, dessinez les stimulations puis les freins ; distinguez concentration d’une hormone et effet biologique.'}],flow:['Glande','Hormone circulante','Récepteur','Réponse cellulaire'],glossary:[['Cellule cible','Cellule capable de reconnaître le signal hormonal.'],['Second messager','Relais intracellulaire après activation d’un récepteur.']],caseStudy:{prompt:'Une hormone circule normalement mais son récepteur est absent d’une cellule. Cette cellule doit-elle répondre ?',answer:'Non. La reconnaissance par un récepteur est nécessaire ; une concentration sanguine normale ne garantit pas une réponse de toutes les cibles.'},trap:'Endocrine signifie libération dans le milieu intérieur ; exocrine implique un conduit ou une surface.',recall:'Pourquoi une hormone ne stimule-t-elle pas toutes les cellules ?',answer:'La réponse dépend notamment de la présence et du fonctionnement de ses récepteurs.',references:['17-1-an-overview-of-the-endocrine-system','17-2-hormones']},
 {id:'immunity',title:'Immunité innée, adaptative et mémoire',category:'Immunologie',structure:null,objectives:['Comparer les deux réponses immunitaires','Distinguer lymphocytes B et T'],sections:[
 {title:'Empêcher puis contenir',text:'La peau et les muqueuses constituent des barrières. Quand elles sont franchies, l’immunité innée mobilise notamment inflammation et phagocytose. Elle reconnaît des motifs partagés et intervient rapidement.'},
 {title:'Reconnaître spécifiquement',text:'L’immunité adaptative repose sur des lymphocytes dont les récepteurs reconnaissent des antigènes. Les lymphocytes activés prolifèrent : cette expansion clonale prend du temps lors d’une première rencontre.'},
 {title:'Répartir les fonctions',text:'Les lymphocytes B peuvent donner des plasmocytes sécrétant des anticorps. Des lymphocytes T coordonnent la réponse ; d’autres détruisent des cellules cibles. Toutes les défenses ne passent donc pas par des anticorps.'},
 {title:'Conserver une mémoire',text:'Des cellules mémoire persistent après une réponse. Une nouvelle exposition peut provoquer une réponse plus rapide et plus efficace. Les réponses innée et adaptative coopèrent, notamment par présentation de l’antigène et signaux cellulaires.'}],glossary:[['Antigène','Élément reconnu par les récepteurs de l’immunité adaptative.'],['Plasmocyte','Cellule issue d’un lymphocyte B, sécrétrice d’anticorps.']],caseStudy:{prompt:'Pourquoi une deuxième rencontre avec un même antigène peut-elle déclencher une réponse différente ?',answer:'Les cellules mémoire issues de la première réponse peuvent être mobilisées plus rapidement. Il ne s’agit pas d’une nouvelle barrière physique.'},trap:'Les lymphocytes T ne sont pas les cellules qui sécrètent les anticorps.',recall:'Quelle cellule dérivée du lymphocyte B produit les anticorps ?',answer:'Le plasmocyte.',references:['21-2-barrier-defenses-and-the-innate-immune-response','21-3-the-adaptive-immune-response-t-lymphocytes-and-their-functional-types','21-4-the-adaptive-immune-response-b-lymphocytes-and-antibodies']},
 {id:'metabolism',title:'Enzymes, ATP et métabolisme',category:'Biochimie',structure:'FMA7197',objectives:['Distinguer anabolisme et catabolisme','Expliquer la catalyse et le couplage énergétique'],sections:[
 {title:'Transformer la matière',text:'Le métabolisme réunit les réactions de l’organisme. Le catabolisme dégrade des molécules et peut libérer de l’énergie. L’anabolisme construit des molécules et requiert un apport énergétique.'},
 {title:'Accélérer sans être consommé',text:'Une enzyme facilite une réaction en abaissant son énergie d’activation. Son site actif reconnaît des substrats. Elle ne fournit pas une énergie illimitée et n’est pas consommée à chaque cycle de catalyse.'},
 {title:'Coupler les réactions',text:'L’ATP sert d’intermédiaire énergétique. Son hydrolyse peut être couplée à un transport, une synthèse ou un travail mécanique. Les cellules le régénèrent continuellement grâce à leurs voies métaboliques.'},
 {title:'Préciser les conditions',text:'Température, pH et disponibilité du substrat influencent une activité enzymatique. Une modification de forme peut altérer le site actif. Pour comparer deux activités, gardez les autres conditions identiques.'}],flow:['Nutriments','Catabolisme','ATP','Travail / synthèses'],glossary:[['Catalyse','Accélération d’une réaction par un catalyseur.'],['Substrat','Molécule transformée par une enzyme.']],caseStudy:{prompt:'Doubler la quantité de substrat garantit-il toujours un doublement de la vitesse enzymatique ?',answer:'Non. Lorsque les sites actifs sont saturés, ajouter du substrat ne suffit plus à augmenter proportionnellement la vitesse.'},trap:'Une enzyme abaisse une barrière énergétique ; elle ne crée pas d’énergie.',recall:'Quelle différence oppose anabolisme et catabolisme ?',answer:'Construction de molécules pour le premier, dégradation pour le second ; leurs échanges énergétiques peuvent être couplés.',references:['2-3-chemical-reactions','2-5-organic-compounds-essential-to-human-functioning','24-1-overview-of-metabolic-reactions']},
]
export const chapters:Course[]=content.map(({references,...chapter})=>({...chapter,tag:'Chapitre essentiel',minutes:12,source:base+references[0],sources:references.map(ref=>({label:`OpenStax · ${ref.split('-').slice(0,2).join('.')}`,url:base+ref}))}))
