import type {Question} from './questions'
// Chaque proposition possède sa propre correction. Les identifiants sont persistants.
type Item=[string,string[],number[],string[]]
const banks:{course:string;topic:string;items:Item[]}[]=[
 {course:'organelles',topic:'Biologie cellulaire',items:[
 ['Quel compartiment trie les protéines de la voie sécrétoire ?',['Le Golgi','Le centromère','Le cytosol exclusivement','Le nucléole'],[0],['Le Golgi trie et modifie les produits reçus.','Le centromère concerne les chromosomes.','La voie sécrétoire passe par des organites.','Le nucléole participe à la production des ribosomes.']],
 ['Quels rôles des organites sont correctement associés ?',['Mitochondrie : production d’ATP','Lysosome : dégradation','Ribosome : traduction','Golgi : réplication de l’ADN'],[0,1,2],['Elle participe à la respiration cellulaire.','Ses enzymes dégradent du matériel.','Il assemble le polypeptide.','La réplication nucléaire ne se déroule pas au Golgi.']],
 ['Une protéine sécrétée a quitté le réticulum. Quelle étape est cohérente ?',['Passage par le Golgi','Transformation en ADN','Transport dans une vésicule','Passage obligatoire dans un chromosome'],[0,2],['Elle y poursuit sa maturation.','La protéine ne devient pas un acide nucléique.','Le trafic vésiculaire relie les compartiments.','Les chromosomes ne transportent pas ces produits.']],
 ['Une cellule bloque la fusion des vésicules à la membrane. Quelle fonction est directement touchée ?',['La sécrétion par exocytose','La lecture des codons par définition','La séparation des chromatides par définition','Le comptage des chromosomes'],[0],['La libération du contenu exige cette fusion.','Ce blocage ne prouve pas un défaut de traduction.','C’est une autre fonction cellulaire.','Le comptage ne dépend pas de l’exocytose.']],
 ]},
 {course:'gene-expression',topic:'Génétique',items:[
 ['La transcription produit :',['Un ARN','Une protéine directement','Un ARN à partir d’ADN','Deux cellules filles'],[0,2],['L’ARN est le produit transcrit.','La protéine résulte de la traduction.','Un brin d’ADN sert de matrice.','La division est un autre processus.']],
 ['Lors de la traduction :',['Le ribosome lit l’ARN messager','L’ARN de transfert apporte un acide aminé','Un codon est un triplet','Le ribosome réplique le génome'],[0,1,2],['Il parcourt les codons.','Son anticodon assure la reconnaissance.','Il comporte trois nucléotides.','La réplication relève des enzymes de l’ADN.']],
 ['Un épissage alternatif peut :',['Produire plusieurs ARN issus d’un même gène','Changer l’association des exons','Remplacer obligatoirement tout l’ADN','Se confondre avec la mitose'],[0,1],['Les combinaisons d’exons peuvent varier.','C’est le principe de cet épissage.','L’ADN du gène n’est pas réécrit par cette opération.','Il s’agit de maturation de l’ARN.']],
 ['Une substitution donne un codon du même acide aminé. Que conclure sur le polypeptide ?',['Cet acide aminé est inchangé','Il est forcément plus court','Le code possède une redondance','La traduction devient une réplication'],[0,2],['C’est la situation décrite.','Aucun codon stop n’est introduit dans cet énoncé.','Plusieurs codons peuvent désigner le même acide aminé.','Les deux processus restent distincts.']],
 ]},
 {course:'cell-cycle',topic:'Génétique',items:[
 ['À quel moment l’ADN est-il répliqué dans le cycle ?',['En phase S','Uniquement en anaphase','Pendant l’interphase','Pendant la cytocinèse exclusivement'],[0,2],['S correspond à la synthèse d’ADN.','L’anaphase sépare les chromatides.','S fait partie de l’interphase.','La cytocinèse répartit le cytoplasme.']],
 ['Une cellule humaine somatique normale en G2 possède :',['46 chromosomes','92 chromatides','92 chromosomes','Une seule chromatide par chromosome'],[0,1],['Les centromères ne sont pas encore séparés.','Chaque chromosome possède deux chromatides.','C’est confondre chromosomes et chromatides.','La réplication a déjà eu lieu.']],
 ['L’anaphase de mitose correspond notamment :',['À la séparation des chromatides sœurs','À leur maintien au centre sans mouvement','À la synthèse de tout l’ADN','À leur migration vers les pôles'],[0,3],['Les copies sont séparées.','L’alignement caractérise la métaphase.','La synthèse précède la mitose.','Le fuseau participe à leur distribution.']],
 ['Pourquoi distinguer mitose et cytocinèse ?',['L’une répartit les chromosomes, l’autre le cytoplasme','Ce sont deux noms de la réplication','La mitose implique le noyau','La cytocinèse fabrique les codons'],[0,2],['Ce sont deux étapes fonctionnellement distinctes.','La réplication précède la division.','Elle assure la division nucléaire.','Les codons sont des séquences d’ARN.']],
 ]},
 {course:'neuronal-signal',topic:'Neurophysiologie',items:[
 ['Dans un axone classique, la dépolarisation rapide implique :',['Une entrée de Na⁺','Des canaux voltage-dépendants','Une sortie de tout l’ADN','Une disparition de la membrane'],[0,1],['Le courant sodique rend le potentiel moins négatif.','Leur ouverture dépend du potentiel.','L’ADN ne réalise pas ce courant.','La membrane reste indispensable au signal.']],
 ['Le codage neuronal peut utiliser :',['La fréquence des potentiels d’action','Une amplitude doublée à chaque stimulus doublé','Des décharges tout ou rien','La conduction saltatoire des axones myélinisés'],[0,2,3],['Le nombre de décharges par temps peut varier.','Le tout ou rien exclut cette règle.','Le seuil déclenche un signal régénératif.','La myéline permet la propagation entre nœuds.']],
 ['Quel événement déclenche directement l’exocytose présynaptique ?',['L’entrée de Ca²⁺','La réplication du neurone','La sortie du noyau','La disparition des récepteurs'],[0],['Le calcium active la libération vésiculaire.','La transmission n’exige pas une division.','Le noyau ne sort pas.','Les récepteurs sont nécessaires à la réponse cible.']],
 ['Une synapse chimique peut :',['Avoir un effet inhibiteur','Utiliser un neurotransmetteur','Déclencher systématiquement un potentiel d’action','Agir sur des récepteurs postsynaptiques'],[0,1,3],['Certaines réponses freinent l’excitation.','C’est le messager chimique.','Le seuil peut ne pas être atteint.','Ils reconnaissent le médiateur.']],
 ]},
 {course:'muscle-contraction',topic:'Physiologie',items:[
 ['Dans le muscle squelettique, le calcium se lie à :',['La troponine','L’ADN pour ouvrir l’actine','La membrane nucléaire exclusivement','Un codon'],[0],['Cela permet le déplacement de la tropomyosine.','L’accès à l’actine relève des protéines régulatrices.','Le mécanisme concerne le sarcomère.','Un codon est une séquence d’ARN.']],
 ['Pendant le raccourcissement du sarcomère :',['Les filaments glissent','L’actine raccourcit nécessairement','Le chevauchement change','Les filaments épais disparaissent'],[0,2],['Le mouvement relatif raccourcit le sarcomère.','Le filament garde sa longueur.','C’est la base du modèle de glissement.','La myosine reste présente.']],
 ['L’ATP intervient dans :',['Le détachement de la myosine','La recapture du calcium','La préparation d’un nouveau cycle','La conversion de l’actine en ADN'],[0,1,2],['Sa fixation détache la tête.','Les pompes calciques consomment de l’énergie.','Son hydrolyse prépare la tête.','Ce n’est pas une transformation musculaire.']],
 ['Un défaut de recapture du calcium peut directement perturber :',['La relaxation','Le retour à un faible calcium cytosolique','Le nombre de chromosomes en G1','La formation d’un ARN par le sarcomère'],[0,1],['La relaxation dépend de la baisse du calcium.','La recapture réalise ce retour.','Il ne s’agit pas d’une division.','Le sarcomère ne transcrit pas l’ADN.']],
 ]},
 {course:'blood',topic:'Hématologie',items:[
 ['Le plasma est :',['La phase liquide du sang','Composé uniquement de globules rouges','Riche en eau','Dépourvu de protéines'],[0,2],['Il porte les éléments figurés et les solutés.','Les érythrocytes sont distincts du plasma.','L’eau constitue son milieu principal.','Il contient notamment de l’albumine.']],
 ['Quels éléments sont correctement associés ?',['Érythrocytes : hémoglobine','Leucocytes : défense','Plaquettes : fragments cellulaires','Plaquettes : globules rouges'],[0,1,2],['L’hémoglobine assure le transport de gaz.','Les leucocytes participent à l’immunité.','Elles proviennent de cellules précurseurs.','Ce sont des éléments différents.']],
 ['L’hématopoïèse adulte se déroule principalement :',['Dans la moelle osseuse rouge','Dans la lumière de l’estomac','À partir de cellules souches','Uniquement dans le plasma'],[0,2],['C’est le principal site adulte.','Le tube digestif n’assure pas ce rôle.','Elles donnent les lignées sanguines.','Le plasma n’est pas un tissu producteur de cellules.']],
 ['Le plasma diminue, le volume globulaire reste constant. L’hématocrite :',['Augmente','Diminue nécessairement','Prouve une production accrue de globules rouges','Est une proportion volumique'],[0,3],['Le dénominateur diminue.','La fraction globulaire augmente ici.','Le changement vient du plasma dans l’énoncé.','Il compare volume globulaire et volume total.']],
 ]},
 {course:'hemodynamics',topic:'Biophysique',items:[
 ['La relation Q = ΔP / R signifie :',['Q augmente avec ΔP à R constant','Q augmente avec R à ΔP constant','La différence de pression compte','Q est une distance'],[0,2],['Le débit suit le gradient à résistance fixée.','Il diminue lorsque R augmente.','Une pression isolée ne suffit pas.','Q est un volume par unité de temps.']],
 ['La vasoconstriction artériolaire, à ΔP fixé :',['Augmente la résistance','Diminue le débit','Double nécessairement le débit','Ne change jamais la résistance'],[0,1],['Le rétrécissement oppose davantage l’écoulement.','Q = ΔP / R.','Le sens prévu est inverse.','Le calibre influence fortement R.']],
 ['Quelle définition d’une artère est correcte ?',['Elle conduit le sang depuis le cœur','Elle contient toujours du sang oxygéné','Elle ramène toujours le sang au cœur','Elle est toujours un capillaire'],[0],['Le sens du flux définit ce terme.','Les artères pulmonaires constituent un contre-exemple.','C’est la définition d’une veine.','Les capillaires sont un autre type de vaisseau.']],
 ['À ΔP constant, R double. Que devient le débit ?',['Il est divisé par deux','Il double','Il reste nécessairement identique','Il devient nul'],[0],['Le dénominateur double dans Q = ΔP / R.','Il faudrait inverser la relation pour cela.','R intervient dans le calcul.','Une résistance doublée n’est pas infinie.']],
 ]},
 {course:'ventilation',topic:'Physiologie',items:[
 ['Pendant l’inspiration calme :',['Le diaphragme se contracte','Le volume thoracique augmente','L’air entre selon un gradient de pression','Le diaphragme fabrique l’oxygène'],[0,1,2],['Il participe à l’augmentation de volume.','Cela réduit la pression alvéolaire.','La pression atmosphérique devient supérieure.','L’oxygène provient de l’air inspiré.']],
 ['La ventilation alvéolaire se calcule par :',['(Volume courant − espace mort) × fréquence','Volume courant × fréquence seulement','Un volume par unité de temps','Une pression divisée par une surface'],[0,2],['On retire le volume non échangeur.','C’est la ventilation minute totale.','L’unité peut être L/min.','Cette expression n’est pas une ventilation.']],
 ['Les échanges alvéolocapillaires sont favorisés par :',['Une grande surface','Une faible épaisseur','Les gradients de pression partielle','L’absence totale de perfusion'],[0,1,2],['Elle offre davantage de surface de diffusion.','Le trajet à traverser est plus court.','Ils orientent les flux gazeux.','Sans sang, les échanges utiles sont compromis.']],
 ['Avec 500 mL courants, 150 mL d’espace mort et 12 cycles/min, la ventilation alvéolaire vaut :',['4,2 L/min','6 L/min','350 L/min','1,8 L/min'],[0],['350 × 12 = 4 200 mL/min.','C’est la ventilation minute totale.','350 est un volume en mL par cycle utile.','C’est 150 × 12, correspondant à l’espace mort ventilé.']],
 ]},
 {course:'fluid-balance',topic:'Physiologie',items:[
 ['Quels liquides sont extracellulaires ?',['Le plasma','Le liquide interstitiel','Le cytosol','Le contenu du noyau'],[0,1],['Il est hors des cellules, dans les vaisseaux.','Il entoure les cellules.','Il se trouve dans les cellules.','Le noyau est intracellulaire.']],
 ['Une solution hypertonique à soluté non pénétrant provoque :',['Une sortie d’eau cellulaire','Une diminution du volume cellulaire','Un gonflement obligatoire','Une division immédiate'],[0,1],['Le gradient osmotique attire l’eau vers le milieu.','La cellule perd de l’eau.','Ce serait l’effet opposé.','L’osmose n’est pas la mitose.']],
 ['L’ADH favorise :',['La réabsorption rénale d’eau','La conservation d’eau','Une perte obligatoire de toute l’eau filtrée','La transformation d’eau en sodium'],[0,1],['Elle agit sur les segments rénaux sensibles.','L’excrétion d’eau peut ainsi diminuer.','Son effet est antidiurétique.','Les éléments ne sont pas ainsi transformés.']],
 ['Pour interpréter un bilan hydrique, il faut :',['Comparer les entrées et les sorties','Préciser l’intervalle de temps','Confondre eau et sodium','Déduire tous les électrolytes du seul volume'],[0,1],['Le bilan mesure leur différence.','Un bilan se rapporte à une durée.','Ce sont des bilans distincts.','Le volume seul ne donne pas ces concentrations.']],
 ]},
 {course:'endocrine',topic:'Endocrinologie',items:[
 ['Une cellule cible hormonale possède :',['Un récepteur adapté','Forcément tous les récepteurs','Un moyen de reconnaître le signal','Obligatoirement un conduit exocrine'],[0,2],['La reconnaissance conditionne la réponse.','Les récepteurs varient selon les cellules.','C’est une propriété de la cible.','L’endocrinie ne nécessite pas ce conduit.']],
 ['Les hormones peptidiques utilisent généralement :',['Un récepteur membranaire','Une signalisation intracellulaire secondaire','Une traduction du récepteur par le sang','Un passage obligatoire dans l’ADN'],[0,1],['Le récepteur reconnaît le peptide à la surface.','Des cascades transmettent le message.','Le sang transporte l’hormone.','Ce passage n’est pas leur mécanisme général.']],
 ['Un rétrocontrôle négatif :',['Freine une stimulation initiale','Amplifie toujours le changement','Participe à une régulation','Signifie une réponse toxique'],[0,2],['Il limite l’écart ou la stimulation.','C’est le sens du rétrocontrôle positif.','Il contribue à stabiliser une variable.','Négatif décrit le sens, pas la toxicité.']],
 ['Une hormone normale mais un récepteur absent permettent de conclure :',['La cellule peut ne pas répondre','Toute cellule répond obligatoirement','La concentration seule ne garantit pas l’effet','L’hormone devient une enzyme digestive'],[0,2],['La reconnaissance du signal manque.','Il faut un récepteur fonctionnel.','La sensibilité de la cible compte.','Il n’y a pas une telle conversion.']],
 ]},
 {course:'immunity',topic:'Immunologie',items:[
 ['L’immunité innée inclut :',['Des barrières','La phagocytose','Une réponse rapide','Uniquement les anticorps spécifiques'],[0,1,2],['Peau et muqueuses participent à la défense.','Des cellules ingèrent du matériel.','Elle précède souvent l’expansion adaptative.','Les anticorps relèvent de la réponse B adaptative.']],
 ['Les plasmocytes :',['Dérivent des lymphocytes B','Sécrètent des anticorps','Sont des érythrocytes','Sont tous des lymphocytes T cytotoxiques'],[0,1],['Ils résultent de leur différenciation.','C’est leur fonction spécialisée.','Les globules rouges transportent des gaz.','B et T sont des lignées distinctes.']],
 ['La réponse adaptative comprend :',['Une expansion clonale','Une reconnaissance antigénique','Une mémoire possible','Uniquement une barrière cutanée'],[0,1,2],['Les clones activés prolifèrent.','Les récepteurs reconnaissent des antigènes.','Des cellules persistent après la réponse.','La peau est une barrière de première ligne.']],
 ['Lors d’une nouvelle rencontre avec un antigène, la mémoire peut :',['Accélérer la réponse','Mobiliser des cellules mémoire','Transformer les globules rouges en anticorps','Supprimer tout rôle de l’immunité innée'],[0,1],['La réponse secondaire peut être plus rapide.','Elles ont persisté après la première réponse.','Les anticorps sont produits par les plasmocytes.','Les deux réponses continuent de coopérer.']],
 ]},
 {course:'metabolism',topic:'Biochimie',items:[
 ['Une enzyme :',['Abaisse l’énergie d’activation','Est consommée à chaque réaction','Reconnaît un substrat','Crée une énergie illimitée'],[0,2],['Elle facilite le franchissement de la barrière.','Elle peut participer à plusieurs cycles.','Son site actif interagit avec lui.','La catalyse ne crée pas d’énergie.']],
 ['L’anabolisme correspond :',['À la construction de molécules','À un besoin énergétique fréquent','Uniquement à leur dégradation','À un synonyme de diffusion'],[0,1],['Il assemble des composants.','Les synthèses utilisent de l’énergie.','La dégradation relève du catabolisme.','La diffusion est un transport.']],
 ['L’ATP peut contribuer :',['Au transport actif','À un travail mécanique','À des synthèses couplées','À une réserve infinie sans renouvellement'],[0,1,2],['Des pompes utilisent son hydrolyse.','Les protéines motrices l’utilisent.','Le couplage fournit l’énergie nécessaire.','L’ATP doit être régénéré.']],
 ['Une enzyme saturée reçoit davantage de substrat. La vitesse :',['Ne double pas nécessairement','Double toujours','Dépend de la capacité catalytique disponible','Devient forcément nulle'],[0,2],['Les sites actifs sont déjà occupés.','La proportionnalité ne s’applique plus à saturation.','La quantité d’enzyme devient limitante.','La saturation ne signifie pas absence de réaction.']],
 ]},
]
export const chapterQuestions:Question[]=banks.flatMap(b=>b.items.map(([prompt,options,correct,why],i)=>({id:`${b.course}-${i+1}`,course:b.course,topic:b.topic,prompt,options,correct,why,difficulty:i<2?'essentiel' as const:'application' as const})))
