import type {Course,CourseLearning} from './curriculum'
import type {Diagram} from './diagrams'
import type {Question} from './questions'

type Check=[statement:string,correct:boolean,explanation:string]
type DeepSection={title:string;text:string;check:Check}
type Module={minutes:number;objectives:string[];sections:DeepSection[];learning:CourseLearning;diagram:{title:string;caption:string;kind:Diagram['kind']}}

const modules:Record<string,Module>={
 'phys-cardiac-cycle':{minutes:32,objectives:['Relier activité électrique, pressions, valves et volumes','Calculer débit cardiaque, volume d’éjection et fraction d’éjection','Raisonner sur précharge, postcharge, contractilité et fréquence'],diagram:{title:'Une révolution cardiaque, quatre temps couplés',caption:'Suivez simultanément pression, état des valves et variation du volume ventriculaire. Une valve s’ouvre passivement lorsque le gradient de pression devient favorable.',kind:'cycle'},sections:[
  {title:'Systole et diastole ne décrivent pas une valve',text:'La systole ventriculaire commence par une contraction isovolumétrique : toutes les valves sont fermées et la pression augmente sans changement de volume. Lorsque la pression ventriculaire dépasse la pression artérielle, la valve sigmoïde s’ouvre et l’éjection commence. La relaxation isovolumétrique survient après sa fermeture.',check:['Pendant la contraction isovolumétrique, le volume ventriculaire reste constant alors que la pression augmente.',true,'Toutes les valves sont fermées pendant cette phase ; aucun sang ne quitte encore le ventricule.']},
  {title:'Remplissage, compliance et pression atriale',text:'Quand la pression ventriculaire devient inférieure à la pression atriale, la valve atrioventriculaire s’ouvre. Le remplissage est d’abord rapide, ralentit, puis la systole atriale complète le volume télédiastolique. La contribution atriale varie avec la fréquence, la relaxation et la compliance du ventricule.',check:['La systole atriale est l’unique mécanisme du remplissage ventriculaire normal.',false,'Une grande partie du remplissage est passive ; la contraction atriale le complète.']},
  {title:'Lire une boucle pression-volume',text:'La largeur de la boucle correspond au volume d’éjection systolique. Le bord droit repère le volume télédiastolique et le bord gauche le volume télésystolique. Les segments verticaux représentent les phases isovolumétriques ; l’aire interne traduit un travail mécanique externe, pas la consommation totale d’oxygène.',check:['La largeur d’une boucle pression-volume représente le volume d’éjection systolique.',true,'VES = volume télédiastolique moins volume télésystolique.']},
  {title:'Précharge, postcharge et contractilité',text:'La précharge décrit l’étirement initial des fibres et est approchée par le volume ou la pression télédiastolique. La postcharge représente la contrainte contre laquelle le ventricule éjecte. La contractilité modifie la force à conditions de charge comparables ; elle ne se confond ni avec la fréquence ni avec la précharge.',check:['Augmenter la postcharge, toutes choses égales, facilite l’éjection et diminue le volume télésystolique.',false,'Une postcharge accrue s’oppose à l’éjection et tend à augmenter le volume télésystolique.']},
  {title:'Débit cardiaque et réserves',text:'Le débit cardiaque est le produit de la fréquence par le volume d’éjection. Une hausse de fréquence peut augmenter le débit, mais une tachycardie marquée raccourcit la diastole et peut réduire le remplissage. Le système autonome agit sur fréquence, conduction, contractilité et tonus vasculaire avec des effets coordonnés.',check:['Doubler la fréquence double toujours le débit cardiaque, quel que soit le remplissage.',false,'Le volume d’éjection peut diminuer lorsque la diastole devient trop courte.']},
  {title:'Coupler ECG, bruits et mécanique',text:'L’ECG enregistre des phénomènes électriques de surface ; il ne mesure pas directement contraction ou pression. Le premier bruit suit la fermeture des valves atrioventriculaires, le second celle des valves sigmoïdes. Il faut toujours respecter la séquence électrique puis mécanique sans les considérer comme simultanées.',check:['L’onde électrique précède l’événement mécanique qu’elle déclenche.',true,'La dépolarisation initie le couplage excitation-contraction avant le développement maximal de force.']}
 ],learning:{formula:{label:'Débit et fraction d’éjection',expression:'DC = FC × VES   ·   FE = VES / VTD × 100',explanation:'Utilisez des unités cohérentes : battements/min × mL/battement donne mL/min. La fraction d’éjection est une proportion et ne donne pas seule le débit.'},comparison:{headers:['Grandeur','Définition opérationnelle','Effet isolé attendu'],rows:[['Précharge','État d’étirement en fin de diastole','Une hausse modérée augmente le VES'],['Postcharge','Contrainte opposée à l’éjection','Une hausse tend à réduire le VES'],['Contractilité','Capacité intrinsèque à développer une force','Une hausse réduit le VTS']]},example:{prompt:'FC 75/min, VTD 120 mL et VTS 50 mL : calculer VES, DC et FE.',steps:['VES = 120 − 50 = 70 mL','DC = 75 × 70 = 5 250 mL/min','FE = 70 / 120 × 100 ≈ 58 %'],result:'Le débit vaut 5,25 L/min et la fraction d’éjection environ 58 %, dans ce cas pédagogique.'},errors:[{title:'Valves actives',detail:'Les valves ne pompent pas : elles répondent aux gradients de pression.'},{title:'ECG = contraction',detail:'L’ECG décrit l’électricité ; pression et mouvement nécessitent d’autres mesures.'},{title:'Fraction = débit',detail:'Une fraction d’éjection préservée ne fixe pas à elle seule le débit cardiaque.'}]}},

 ventilation:{minutes:30,objectives:['Distinguer ventilation minute et alvéolaire','Appliquer les lois de pression et de compliance','Relier ventilation, diffusion et perfusion'],diagram:{title:'De la pression atmosphérique aux échanges alvéolaires',caption:'Le schéma sépare mécanique ventilatoire, renouvellement alvéolaire, diffusion et transport sanguin.',kind:'flow'},sections:[
  {title:'Créer un gradient de pression',text:'À l’inspiration calme, la contraction diaphragmatique augmente le volume thoracique. La pression pleurale devient plus négative, la pression alvéolaire passe légèrement sous la pression atmosphérique et l’air entre. Le débit cesse lorsque les pressions s’égalisent, même si le poumon contient toujours de l’air.',check:['Un flux inspiratoire exige une pression alvéolaire inférieure à la pression atmosphérique.',true,'L’air se déplace selon un gradient de pression.']},
  {title:'Compliance et recul élastique',text:'La compliance est la variation de volume obtenue pour une variation de pression. Le recul élastique favorise l’expiration calme. Le surfactant réduit la tension superficielle et limite la tendance des petites unités alvéolaires à se vider ; résistance et compliance décrivent des obstacles différents.',check:['Compliance élevée et résistance élevée décrivent exactement la même propriété mécanique.',false,'La compliance concerne la distensibilité ; la résistance concerne l’opposition au débit.']},
  {title:'Volumes et capacités',text:'Le volume courant est mobilisé à chaque cycle calme. Les volumes de réserve s’ajoutent selon la manœuvre ; le volume résiduel reste après une expiration maximale. Une spirométrie simple ne mesure pas directement tout volume contenant le volume résiduel, ce qui impose de connaître la méthode.',check:['Une spirométrie simple mesure directement le volume résiduel.',false,'Le volume résiduel ne peut pas être expiré dans le spiromètre.']},
  {title:'Ventilation alvéolaire utile',text:'La ventilation minute vaut volume courant fois fréquence. La ventilation alvéolaire retranche l’espace mort avant de multiplier par la fréquence. Deux sujets ayant la même ventilation minute peuvent donc renouveler différemment leurs alvéoles si leurs volumes courants et fréquences diffèrent.',check:['À ventilation minute identique, une respiration plus ample et moins fréquente peut augmenter la ventilation alvéolaire.',true,'Une part moins grande de chaque minute sert alors à ventiler l’espace mort.']},
  {title:'Diffusion et pressions partielles',text:'Un gaz diffuse selon son gradient de pression partielle, la surface disponible, l’épaisseur de la barrière et ses propriétés. La quantité totale de gaz transportée ne se confond pas avec sa pression partielle. L’hémoglobine augmente fortement le contenu sanguin en oxygène sans abolir le gradient diffusif.',check:['Pression partielle et contenu total en oxygène sont deux grandeurs distinctes.',true,'Le contenu dépend notamment de l’hémoglobine liée, contrairement à la seule pression partielle.']},
  {title:'Rapport ventilation-perfusion',text:'Une unité bien ventilée mais non perfusée échange peu avec le sang ; une unité perfusée mais peu ventilée oxygène mal ce débit. Le rapport V/Q varie dans un poumon normal. Les mécanismes de compensation sont incomplets : une moyenne globale peut masquer une forte hétérogénéité régionale.',check:['Une ventilation normale garantit des échanges normaux même si la perfusion est absente.',false,'Ventilation et perfusion doivent toutes deux atteindre l’unité échangeuse.']}
 ],learning:{formula:{label:'Ventilation alvéolaire',expression:'V̇A = (VT − VD) × f',explanation:'VT est le volume courant, VD l’espace mort et f la fréquence. Convertissez les millilitres en litres seulement après le calcul.'},comparison:{headers:['Grandeur','Calcul','Ce qu’elle décrit'],rows:[['Ventilation minute','VT × f','Volume total mobilisé'],['Ventilation alvéolaire','(VT − VD) × f','Renouvellement utile'],['Compliance','ΔV / ΔP','Distensibilité du système']]},example:{prompt:'VT 500 mL, espace mort 150 mL, fréquence 12/min.',steps:['Volume utile = 500 − 150 = 350 mL','350 × 12 = 4 200 mL/min','Ventilation minute = 500 × 12 = 6 000 mL/min'],result:'La ventilation alvéolaire est 4,2 L/min, distincte de la ventilation minute de 6 L/min.'},errors:[{title:'Additionner l’espace mort',detail:'Il faut le retrancher du volume courant avant de multiplier.'},{title:'Confondre air et sang',detail:'Ventilation et perfusion sont deux flux différents.'},{title:'Lire une pression comme un contenu',detail:'Une pression partielle ne donne pas seule la quantité totale transportée.'}]}},

 'phys-renal':{minutes:34,objectives:['Établir un bilan filtré-réabsorbé-sécrété','Comprendre clairance et fraction filtrée','Relier segments du néphron et régulations hormonales'],diagram:{title:'Le trajet d’une substance dans un néphron',caption:'Chaque étape modifie la quantité tubulaire. L’excrétion finale résulte du bilan, pas de la filtration seule.',kind:'flow'},sections:[
  {title:'Filtration glomérulaire sélective',text:'La barrière glomérulaire laisse passer eau et petites molécules selon taille, charge et forces de filtration, tout en retenant normalement cellules et grande part des protéines. Le débit de filtration glomérulaire dépend de la pression nette et du coefficient de filtration ; il ne correspond pas au débit urinaire.',check:['Le débit de filtration glomérulaire est normalement bien supérieur au débit urinaire.',true,'La majeure partie de l’eau filtrée est réabsorbée.']},
  {title:'Réabsorption et sécrétion',text:'Réabsorber fait passer une substance du tubule vers le sang ; sécréter réalise le trajet opposé. Les transports peuvent être saturables et couplés à des gradients. La quantité excrétée peut être inférieure, égale ou supérieure à la quantité filtrée selon le bilan tubulaire.',check:['Une substance sécrétée peut être excrétée en quantité supérieure à sa charge filtrée.',true,'La sécrétion ajoute de la substance dans la lumière tubulaire.']},
  {title:'Clairance comme volume virtuel',text:'La clairance rapporte le débit d’excrétion urinaire à la concentration plasmatique. Elle représente un volume de plasma épuré par unité de temps, pas un volume anatomique réellement prélevé. Comparée au DFG, elle renseigne sur la réabsorption ou la sécrétion nette sous certaines hypothèses.',check:['La clairance est un volume urinaire réellement produit chaque minute.',false,'C’est un volume plasmatique virtuel calculé à partir d’un débit d’excrétion.']},
  {title:'Concentration médullaire',text:'L’anse de Henle, les gradients médullaires, les vasa recta et l’urée participent à la capacité de concentrer l’urine. La branche ascendante épaisse réabsorbe des solutés tout en étant peu perméable à l’eau. Ce dispositif prépare un gradient qu’un tube collecteur modulé par l’ADH peut utiliser.',check:['L’ADH crée seule le gradient médullaire indépendamment de l’anse de Henle.',false,'Elle augmente surtout la perméabilité du collecteur à l’eau ; le gradient dépend d’autres structures.']},
  {title:'Sodium, volume efficace et hormones',text:'Le système rénine-angiotensine-aldostérone répond notamment à des signaux de perfusion et de sodium tubulaire. L’aldostérone favorise la réabsorption de sodium et la sécrétion de potassium dans des segments distaux. ADH et aldostérone ont donc des cibles et effets distincts malgré leur coopération sur les bilans.',check:['ADH et aldostérone sont deux noms du même mécanisme de réabsorption d’eau.',false,'L’ADH module surtout la perméabilité à l’eau ; l’aldostérone régule des transports ioniques.']},
  {title:'Équilibre acide-base rénal',text:'Le rein réabsorbe le bicarbonate filtré et permet une excrétion nette d’acides, notamment sous forme titrable et ammonium. Cette réponse est plus lente que la ventilation mais soutient durablement le bilan. Un pH urinaire acide ne suffit pas à quantifier l’excrétion totale d’acide.',check:['Le rein contribue à l’équilibre acide-base en réabsorbant le bicarbonate et en excrétant des acides.',true,'Ces processus participent au maintien durable du bicarbonate plasmatique.']}
 ],learning:{formula:{label:'Excrétion et clairance',expression:'Excrété = Filtré − Réabsorbé + Sécrété   ·   Cx = Ux × V̇ / Px',explanation:'Les quantités doivent porter sur la même durée. Pour la clairance, Ux et Px utilisent la même unité de concentration.'},comparison:{headers:['Processus','Sens','Conséquence tubulaire'],rows:[['Filtration','Plasma vers capsule','Ajoute au tubule'],['Réabsorption','Tubule vers sang','Retire du tubule'],['Sécrétion','Sang vers tubule','Ajoute au tubule']]},example:{prompt:'Ux 60 mg/mL, débit urinaire 1 mL/min, Px 2 mg/mL.',steps:['Débit excrété = 60 × 1 = 60 mg/min','Clairance = 60 / 2','Vérifier les unités : mL/min'],result:'La clairance calculée est de 30 mL/min dans cet exemple.'},errors:[{title:'Filtré = éliminé',detail:'La réabsorption et la sécrétion modifient la quantité finale.'},{title:'Clairance = débit urinaire',detail:'La clairance est un volume plasmatique virtuel.'},{title:'ADH = aldostérone',detail:'Leurs récepteurs, cibles et mécanismes diffèrent.'}]}},

 'phys-digestion':{minutes:30,objectives:['Distinguer digestion, absorption et transport','Relier sécrétions et segments digestifs','Expliquer la régulation d’un repas'],diagram:{title:'Du repas au milieu intérieur',caption:'Le contenu reste extérieur au milieu intérieur tant qu’il n’a pas franchi l’épithélium.',kind:'flow'},sections:[
  {title:'Motricité et progression',text:'Déglutition, péristaltisme, segmentation et vidange gastrique remplissent des fonctions distinctes. La segmentation mélange sans imposer une progression rapide. Sphincters et réflexes coordonnent les compartiments ; le système nerveux entérique peut organiser des réponses locales modulées par les systèmes extrinsèques.',check:['La segmentation intestinale sert uniquement à propulser rapidement le contenu vers le côlon.',false,'Elle favorise surtout mélange et contact avec la muqueuse.']},
  {title:'Sécrétions gastriques',text:'Les cellules pariétales sécrètent acide et facteur intrinsèque ; les cellules principales produisent du pepsinogène. Le mucus et le bicarbonate protègent la surface. L’acidité favorise l’activation de la pepsine mais la digestion protéique ne s’achève pas dans l’estomac.',check:['Le facteur intrinsèque participe ensuite à l’absorption de la vitamine B12.',true,'Il est produit dans l’estomac mais son rôle d’absorption s’exerce plus distalement.']},
  {title:'Pancréas, foie et bile',text:'Le pancréas exocrine fournit enzymes et bicarbonate au duodénum. Le foie produit la bile, que la vésicule peut stocker et concentrer. Les sels biliaires émulsifient les lipides et participent aux micelles ; ils ne sont pas des enzymes hydrolysant directement les triglycérides.',check:['Les sels biliaires sont des enzymes qui hydrolysent directement les lipides.',false,'Ils facilitent dispersion et transport ; les lipases assurent l’hydrolyse.']},
  {title:'Absorber glucides et protéines',text:'Les glucides sont absorbés sous forme de monosaccharides après digestion luminale et membranaire. Les protéines fournissent acides aminés et petits peptides. Des cotransports utilisent indirectement le gradient de sodium, entretenu par la Na+/K+-ATPase basolatérale.',check:['Un cotransport apical dépendant du sodium peut être actif secondaire sans hydrolyser directement l’ATP.',true,'Son énergie provient d’un gradient entretenu ailleurs par une pompe.']},
  {title:'Absorber les lipides',text:'Produits lipidiques et sels biliaires forment des micelles qui approchent la membrane apicale. Dans l’entérocyte, les lipides sont réassemblés puis exportés dans des chylomicrons vers la lymphe. Micelle et chylomicron ne se situent pas du même côté de l’épithélium.',check:['Les chylomicrons quittent initialement l’intestin principalement par les capillaires lymphatiques.',true,'Ils gagnent les vaisseaux chylifères avant de rejoindre la circulation sanguine.']},
  {title:'Phases et signaux de régulation',text:'Les phases céphalique, gastrique et intestinale décrivent des ensembles de signaux qui se chevauchent. Gastrine, sécrétine et cholécystokinine répondent à des contenus différents et coordonnent sécrétion, motricité et vidange. Une hormone digestive n’agit pas sur un seul organe isolé.',check:['La sécrétine est notamment stimulée par l’acidité duodénale et favorise une réponse bicarbonatée.',true,'Elle contribue à neutraliser le contenu acide arrivant de l’estomac.']}
 ],learning:{formula:{label:'Charge absorbée',expression:'Absorption nette = entrée apicale − retour vers la lumière',explanation:'Le franchissement apical ne suffit pas : le soluté doit aussi quitter l’entérocyte vers le milieu intérieur.'},comparison:{headers:['Nutriment','Forme absorbée','Première voie majeure'],rows:[['Glucides','Monosaccharides','Capillaires portes'],['Protéines','Acides aminés et petits peptides','Capillaires portes'],['Lipides longs','Chylomicrons après réassemblage','Lymphe intestinale']]},example:{prompt:'Suivre un triglycéride alimentaire jusqu’à la circulation.',steps:['Émulsification et action des lipases','Micelle puis entrée des produits dans l’entérocyte','Réassemblage et formation d’un chylomicron','Passage lymphatique puis sanguin'],result:'Il faut distinguer digestion luminale, franchissement épithélial et transport après absorption.'},errors:[{title:'Digestion = absorption',detail:'La digestion transforme ; l’absorption franchit l’épithélium.'},{title:'Bile = lipase',detail:'La bile facilite la dispersion mais ne remplace pas l’enzyme.'},{title:'Tout rejoint directement le sang',detail:'Les lipides longs empruntent d’abord la voie lymphatique.'}]}},

 'neuronal-signal':{minutes:32,objectives:['Calculer et interpréter un potentiel d’équilibre','Décomposer potentiel d’action et périodes réfractaires','Comparer transmission synaptique et intégration'],diagram:{title:'Du gradient ionique à la réponse postsynaptique',caption:'La membrane transforme des gradients en signal électrique, puis la synapse convertit ce signal en message chimique et de nouveau électrique.',kind:'flow'},sections:[
  {title:'Potentiel de repos',text:'Le potentiel de repos résulte de gradients ioniques, de perméabilités sélectives et de l’activité des transporteurs. Il se situe souvent près du potentiel d’équilibre du potassium sans lui être égal. La pompe Na+/K+ entretient les gradients sur la durée mais ne produit pas seule chaque variation rapide.',check:['Le potentiel de repos dépend des perméabilités relatives de plusieurs ions.',true,'Les gradients et la perméabilité sélective déterminent ensemble la tension membranaire.']},
  {title:'Potentiel d’équilibre',text:'L’équation de Nernst donne la tension qui équilibre exactement gradient chimique et force électrique pour un ion. Le signe dépend de la valence et du rapport des concentrations. Ouvrir un canal tend à déplacer le potentiel membranaire vers le potentiel d’équilibre de l’ion concerné.',check:['Ouvrir des canaux potassiques tend toujours à fixer instantanément la membrane exactement à EK.',false,'Le déplacement dépend aussi des autres conductances et n’est pas forcément complet.']},
  {title:'Seuil et potentiel d’action',text:'Une dépolarisation suffisante recrute des canaux sodiques voltage-dépendants, créant une rétroaction positive. Leur inactivation et l’ouverture retardée de canaux potassiques permettent la repolarisation. L’amplitude du potentiel d’action n’augmente pas proportionnellement avec un stimulus supraliminaire.',check:['Un stimulus supraliminaire plus fort code principalement par une fréquence accrue plutôt que par une amplitude beaucoup plus grande.',true,'Le potentiel d’action obéit au principe du tout ou rien.']},
  {title:'Réfractarité et propagation',text:'Pendant la période réfractaire absolue, de nombreux canaux sodiques restent inactivés. La période relative exige un stimulus plus fort. La propagation régénère le signal le long de l’axone ; myéline et nœuds de Ranvier permettent une conduction saltatoire rapide sans que le signal saute physiquement dans l’espace extracellulaire.',check:['La période réfractaire contribue au sens privilégié de propagation et limite la fréquence maximale.',true,'Les canaux récemment activés ne sont pas immédiatement disponibles.']},
  {title:'Synapse chimique',text:'L’arrivée du potentiel d’action ouvre des canaux calciques présynaptiques. Le calcium déclenche la fusion vésiculaire ; le médiateur se fixe à des récepteurs postsynaptiques. L’arrêt du signal dépend de recapture, dégradation ou diffusion selon le neurotransmetteur.',check:['Le calcium présynaptique constitue un lien essentiel entre signal électrique et exocytose.',true,'Son entrée déclenche la machinerie de fusion des vésicules.']},
  {title:'Sommation et décision',text:'Les potentiels postsynaptiques sont gradués. Ils se somment dans le temps et l’espace, avec des effets dépendant du potentiel de membrane et des conductances. Excitateur et inhibiteur décrivent l’influence sur le déclenchement, pas une propriété morale ou toujours identique du neurotransmetteur.',check:['Un même neurotransmetteur peut produire des effets différents selon le récepteur et le gradient ionique.',true,'La réponse dépend du récepteur et du contexte électrique de la cellule cible.']}
 ],learning:{formula:{label:'Potentiel d’équilibre de Nernst',expression:'Eion = (RT / zF) × ln([ion]extérieur / [ion]intérieur)',explanation:'z porte le signe de la charge. Cette relation concerne un ion à l’équilibre, pas directement une membrane perméable à plusieurs espèces.'},comparison:{headers:['Signal','Amplitude','Propagation'],rows:[['Potentiel gradué','Variable','Décroît avec la distance'],['Potentiel d’action','Tout ou rien','Régénéré le long de l’axone'],['Transmission synaptique','Dépend du récepteur','Avec délai synaptique']]},example:{prompt:'Une membrane devient surtout perméable au K+.',steps:['Repérer le gradient de K+','Identifier son potentiel d’équilibre','Prévoir un déplacement de Vm vers EK','Conserver l’effet des autres conductances'],result:'Vm se rapproche de EK sans être obligatoirement égal à EK.'},errors:[{title:'Pompe = potentiel d’action',detail:'La pompe entretient les gradients ; les canaux produisent les variations rapides.'},{title:'Stimulus fort = pic plus haut',detail:'Au-delà du seuil, le codage repose surtout sur la fréquence.'},{title:'Neurotransmetteur toujours excitateur',detail:'Le récepteur et les gradients déterminent l’effet.'}]}},

 'muscle-contraction':{minutes:30,objectives:['Relier excitation, calcium et ponts actine-myosine','Distinguer force, longueur et vitesse','Comparer unité motrice et sommation'],diagram:{title:'Couplage excitation-contraction du muscle squelettique',caption:'Chaque étape peut être perturbée séparément : membrane, calcium, protéines régulatrices, ponts ou recapture.',kind:'cycle'},sections:[
  {title:'Jonction neuromusculaire',text:'Le motoneurone libère de l’acétylcholine, qui active des récepteurs nicotiniques et produit un potentiel de plaque. Si le seuil est atteint, un potentiel d’action musculaire se propage. L’acétylcholinestérase limite le signal ; potentiel de plaque et potentiel d’action sont distincts.',check:['Le potentiel de plaque est gradué alors que le potentiel d’action musculaire est tout ou rien.',true,'Le premier déclenche le second s’il atteint le seuil.']},
  {title:'Triades et libération du calcium',text:'Les tubules T conduisent la dépolarisation au cœur de la fibre. Les capteurs voltage-dépendants communiquent avec les canaux du réticulum sarcoplasmique, qui libère le calcium. La contraction peut ainsi être synchronisée dans une grande fibre sans diffusion lente depuis la seule surface.',check:['Les tubules T permettent à la dépolarisation d’atteindre rapidement l’intérieur de la fibre.',true,'Ils rapprochent le signal membranaire des citernes du réticulum.']},
  {title:'Troponine et tropomyosine',text:'Au repos, la tropomyosine limite l’accès de la myosine à l’actine. Le calcium se fixe à la troponine C et déplace le complexe régulateur. Le calcium n’apporte pas directement l’énergie mécanique : il rend possible le cycle des ponts.',check:['Le calcium fournit directement l’énergie de chaque coup de force de la myosine.',false,'L’énergie provient du cycle de l’ATP ; le calcium régule l’accès à l’actine.']},
  {title:'Cycle des ponts et ATP',text:'La fixation d’ATP détache la myosine de l’actine ; son hydrolyse arme la tête. La liaison puis la libération de phosphate favorisent le coup de force. Sans ATP, le détachement devient impossible. L’ATP sert aussi à la recapture du calcium pendant la relaxation.',check:['L’ATP est nécessaire au détachement actine-myosine ainsi qu’à la relaxation.',true,'Il intervient dans le cycle des ponts et alimente les pompes calciques.']},
  {title:'Longueur, charge et vitesse',text:'La force active dépend du chevauchement des filaments : trop peu ou trop de chevauchement réduit le nombre de ponts efficaces. En concentrique, une charge plus élevée réduit généralement la vitesse de raccourcissement. Une contraction isométrique développe une force sans changement global de longueur.',check:['Isométrique signifie absence de force puisque la longueur externe ne change pas.',false,'Une tension peut être développée sans raccourcissement global.']},
  {title:'Recrutement et tétanos',text:'Une unité motrice comprend un motoneurone et ses fibres. Augmenter le recrutement et la fréquence de stimulation accroît la force. La sommation temporelle peut conduire à un tétanos physiologique ; ce terme décrit une contraction soutenue et ne désigne pas ici la maladie infectieuse.',check:['Le recrutement augmente la force en activant davantage d’unités motrices.',true,'Plus de fibres contribuent alors à la tension totale.']}
 ],learning:{formula:{label:'Force et travail mécanique',expression:'Travail = Force × déplacement   ·   Puissance = Travail / temps',explanation:'Une contraction isométrique peut produire une forte tension mais un travail externe nul si le déplacement est nul.'},comparison:{headers:['Contraction','Longueur','Charge'],rows:[['Isométrique','Stable','Force sans déplacement'],['Concentrique','Diminue','Le muscle raccourcit'],['Excentrique','Augmente','Le muscle freine en s’allongeant']]},example:{prompt:'Un sujet tient immobile une charge puis la soulève.',steps:['Maintien : tension sans déplacement','Travail externe nul pendant le maintien idéal','Levée : contraction concentrique','Travail positif pendant le déplacement'],result:'Force et travail ne sont pas synonymes ; le déplacement doit être considéré.'},errors:[{title:'Calcium = énergie',detail:'Le calcium régule ; l’ATP fournit l’énergie chimique.'},{title:'Isométrique = repos',detail:'Une tension peut être élevée sans raccourcissement.'},{title:'Sarcomère = filaments raccourcis',detail:'Les filaments glissent et gardent approximativement leur longueur.'}]}},

 'fluid-balance':{minutes:28,objectives:['Calculer osmolarité et bilans','Prévoir les déplacements d’eau','Distinguer volume, osmolarité et tonicité'],diagram:{title:'Compartiments, barrières et mouvements d’eau',caption:'Suivez séparément quantité de soluté, volume d’eau et capacité du soluté à franchir la membrane.',kind:'branch'},sections:[
  {title:'Compartiments corporels',text:'L’eau totale se répartit entre compartiments intracellulaire et extracellulaire ; ce dernier comprend plasma et interstitiel. Les proportions sont des ordres de grandeur variables selon âge, sexe et composition corporelle. Intravasculaire ne signifie pas intracellulaire : le plasma reste hors des cellules.',check:['Le plasma appartient au compartiment extracellulaire.',true,'Il est dans les vaisseaux mais à l’extérieur des cellules.']},
  {title:'Osmolarité et osmoles',text:'L’osmolarité compte les particules osmotiquement actives par litre de solution. Une mole de glucose fournit approximativement une osmole ; un sel dissocié peut fournir plusieurs particules selon le modèle. Il faut distinguer concentration molaire, osmolarité mesurée et approximation idéale.',check:['À comportement idéal, une mole de NaCl totalement dissociée fournit environ deux osmoles.',true,'Elle donne des ions sodium et chlorure.']},
  {title:'Tonicité et volume cellulaire',text:'La tonicité prédit le volume cellulaire à l’équilibre et dépend surtout des osmoles efficaces qui ne traversent pas librement la membrane. Une solution peut être iso-osmolaire sans être isotonique si son soluté pénètre les cellules. Il faut préciser membrane, soluté et durée.',check:['Toute solution iso-osmolaire est nécessairement isotonique.',false,'Un soluté diffusible peut entrer dans la cellule et modifier son volume.']},
  {title:'Bilans d’eau et de sodium',text:'Un bilan compare entrées et sorties sur une durée définie. Le sodium extracellulaire influence le volume extracellulaire, tandis que la concentration plasmatique de sodium reflète surtout un rapport entre solutés échangeables et eau. Une concentration ne mesure donc pas directement le stock total.',check:['Une concentration plasmatique de sodium normale garantit un stock sodé total normal.',false,'La concentration est un rapport et peut rester normale malgré une variation parallèle d’eau et de sodium.']},
  {title:'Réponses à l’hyperosmolarité',text:'Une hausse d’osmolarité extracellulaire attire l’eau hors des cellules et stimule notamment soif et libération d’ADH. L’ADH augmente la perméabilité à l’eau du tube collecteur. La correction dépend toutefois de l’accès à l’eau et de la fonction rénale.',check:['Une hyperosmolarité extracellulaire tend initialement à faire sortir l’eau des cellules.',true,'L’eau se déplace vers le compartiment le plus concentré en osmoles efficaces.']},
  {title:'Œdème et forces capillaires',text:'L’œdème correspond à une accumulation interstitielle. Pressions hydrostatique et oncotique, perméabilité capillaire et drainage lymphatique participent au bilan. Une rétention d’eau globale et un œdème local ne sont pas des synonymes : la distribution entre compartiments compte.',check:['Un défaut de drainage lymphatique peut contribuer à un œdème interstitiel.',true,'Le retour des protéines et du liquide interstitiel devient insuffisant.']}
 ],learning:{formula:{label:'Osmolarité idéale et bilan',expression:'Osmolarité ≈ Σ concentration × nombre de particules   ·   Bilan = entrées − sorties',explanation:'Ces relations exigent une période et des unités explicites. La tonicité demande en plus de connaître la perméabilité membranaire.'},comparison:{headers:['Terme','Question posée','Piège'],rows:[['Osmolarité','Combien de particules ?','Ne prédit pas toujours le volume cellulaire'],['Tonicité','Quel volume cellulaire final ?','Dépend des solutés non diffusibles'],['Bilan','Stock augmente-t-il ?','Exige une durée définie']]},example:{prompt:'Ajouter 100 mmol/L de glucose non diffusible à un compartiment.',steps:['Une mole donne environ une osmole','Le compartiment gagne environ 100 mOsm/L','L’eau est attirée vers ce compartiment','Le résultat dépend ensuite des barrières et volumes'],result:'Le raisonnement sépare nombre de particules et mouvement d’eau.'},errors:[{title:'Plasma intracellulaire',detail:'Le repère est la membrane cellulaire, pas la paroi vasculaire.'},{title:'Iso-osmolaire = isotonique',detail:'La perméabilité du soluté peut changer le volume final.'},{title:'Concentration = stock',detail:'Une concentration est un rapport entre quantité et volume.'}]}},

 'biochem-bioenergetics':{minutes:30,objectives:['Calculer le sens thermodynamique avec ΔG','Distinguer équilibre, état stationnaire et vitesse','Justifier un couplage énergétique réel'],diagram:{title:'Coupler une réaction défavorable à l’hydrolyse de l’ATP',caption:'Le couplage exige un intermédiaire commun et une somme de ΔG négative dans les conditions cellulaires.',kind:'flow'},sections:[
  {title:'ΔG standard et ΔG réel',text:'ΔG°’ décrit des conditions biochimiques standardisées ; ΔG tient compte du quotient réactionnel réel. Une réaction dont ΔG°’ est positif peut avancer dans une cellule si les concentrations rendent ΔG négatif. Le signe prédit le sens favorable, pas la rapidité.',check:['Une réaction à ΔG négatif est forcément rapide sans enzyme.',false,'La thermodynamique ne fixe pas la barrière d’activation ni la vitesse.']},
  {title:'Équilibre et état stationnaire',text:'À l’équilibre, ΔG est nul et les flux microscopiques opposés se compensent. Un état stationnaire maintient des concentrations approximativement stables grâce à des entrées et sorties continues ; il peut rester loin de l’équilibre. Une cellule vivante consomme de l’énergie pour entretenir de tels états.',check:['Une concentration stable dans le temps prouve que la réaction est à l’équilibre.',false,'Des flux opposés ou des apports peuvent maintenir un état stationnaire hors équilibre.']},
  {title:'Barrière d’activation',text:'Une enzyme stabilise un état de transition et accélère les voies aller et retour. Elle ne change ni ΔG global ni constante d’équilibre. La vitesse dépend aussi des concentrations, de la température, des inhibiteurs et de la quantité d’enzyme.',check:['Une enzyme modifie la constante d’équilibre en faveur des produits.',false,'Elle accélère l’approche de l’équilibre sans déplacer celui-ci.']},
  {title:'Hydrolyse de l’ATP',text:'L’hydrolyse de l’ATP est favorable dans de nombreuses conditions cellulaires, mais l’énergie utile vient du couplage à un mécanisme. Phosphoryler un intermédiaire, changer une conformation ou établir un gradient relie chimiquement les processus. Une simple proximité avec l’ATP ne suffit pas.',check:['Deux réactions ne sont effectivement couplées que si un mécanisme commun relie leurs transformations.',true,'L’addition formelle des équations ne prouve pas un couplage cellulaire.']},
  {title:'Transport et gradients',text:'Une pompe peut convertir l’énergie chimique en gradient électrochimique. Le retour favorable d’un ion peut ensuite entraîner un transport actif secondaire. L’énergie est ainsi transférée en plusieurs étapes ; le cotransporteur secondaire n’hydrolyse pas nécessairement l’ATP lui-même.',check:['Un transport actif secondaire peut utiliser un gradient créé par une ATPase distincte.',true,'Le gradient constitue l’intermédiaire énergétique.']},
  {title:'Réguler les voies',text:'Les étapes très éloignées de l’équilibre sont souvent des points de contrôle efficaces. Allostérie, phosphorylation, disponibilité du substrat et expression enzymatique agissent à des échelles de temps différentes. L’étape la plus lente observée n’est pas automatiquement la seule étape régulée.',check:['Une voie métabolique peut être régulée à plusieurs étapes et à plusieurs échelles de temps.',true,'Contrôle rapide de l’activité et contrôle plus lent de l’expression peuvent coexister.']}
 ],learning:{formula:{label:'Énergie libre réelle',expression:'ΔG = ΔG°’ + RT ln Q   ·   ΔGcouplé = Σ ΔG',explanation:'Q décrit les concentrations ou activités présentes. Un couplage global devient favorable si la somme des variations est négative.'},comparison:{headers:['Concept','Détermine','Ne détermine pas'],rows:[['ΔG','Sens thermodynamique favorable','Vitesse'],['Énergie d’activation','Obstacle cinétique','Position de l’équilibre'],['Enzyme','Vitesse d’approche','ΔG global']]},example:{prompt:'Réaction A : +12 kJ/mol ; hydrolyse couplée : −30 kJ/mol.',steps:['Additionner les variations réellement couplées','+12 + (−30) = −18 kJ/mol','Vérifier que le mécanisme partage un intermédiaire'],result:'La transformation couplée est thermodynamiquement favorable avec ΔG = −18 kJ/mol.'},errors:[{title:'Spontané = rapide',detail:'Un ΔG négatif n’abolit pas la barrière d’activation.'},{title:'Enzyme déplace l’équilibre',detail:'Elle accélère les deux sens sans changer Keq.'},{title:'ATP comme énergie abstraite',detail:'Il faut identifier le transfert ou l’intermédiaire qui réalise le couplage.'}]}}
}

Object.assign(modules,{
 'biochem-carbohydrate':{minutes:32,objectives:['Relier glycolyse, glycogène et néoglucogenèse','Calculer un bilan simple en ATP et coenzymes','Expliquer les régulations réciproques'],diagram:{title:'Carrefour du glucose-6-phosphate',caption:'Une même molécule alimente production d’énergie, stockage, voie des pentoses ou libération hépatique selon le tissu et l’état nutritionnel.',kind:'branch'},sections:[
  {title:'Entrée et piégeage du glucose',text:'Les transporteurs facilitent l’entrée selon le tissu. Hexokinase ou glucokinase phosphoryle ensuite le glucose en glucose-6-phosphate, qui ne traverse plus librement la membrane. Affinité, capacité et régulation diffèrent : ces enzymes ne sont pas interchangeables.',check:['La phosphorylation contribue à retenir le glucose dans la cellule.',true,'Le glucose-6-phosphate ne ressort pas par les transporteurs du glucose.']},
  {title:'Glycolyse et bilan',text:'La glycolyse consomme deux ATP puis en produit quatre par glucose, soit un gain net de deux ATP, ainsi que deux NADH et deux pyruvates. En condition anaérobie, la formation de lactate régénère le NAD+ nécessaire à la poursuite du flux.',check:['Le gain net direct de la glycolyse est de deux ATP par glucose.',true,'Quatre sont formés mais deux ont été investis.']},
  {title:'Pyruvate comme carrefour',text:'Le pyruvate peut devenir lactate, alanine, oxaloacétate ou acétyl-CoA selon contexte et compartiment. La pyruvate déshydrogénase produit acétyl-CoA de manière irréversible et relie glycolyse et cycle de Krebs ; elle ne réalise pas la néoglucogenèse inverse.',check:['La conversion pyruvate-acétyl-CoA est directement réversible pour refaire du glucose.',false,'La néoglucogenèse utilise d’autres précurseurs et contournements.']},
  {title:'Glycogène : synthèse et mobilisation',text:'Glycogène synthase et glycogène phosphorylase répondent à des régulations réciproques. Le foie contribue à la glycémie grâce à la glucose-6-phosphatase ; le muscle utilise son glycogène pour lui-même et ne libère pas directement de glucose libre dans le sang.',check:['Le glycogène musculaire sert principalement les besoins énergétiques du muscle.',true,'Le muscle ne possède pas la même capacité hépatique de libération de glucose.']},
  {title:'Néoglucogenèse et jeûne',text:'Foie et, plus tard, rein produisent du glucose à partir de lactate, glycérol et certains acides aminés. Des enzymes contournent les étapes irréversibles de la glycolyse. Ce processus consomme de l’énergie et ne transforme pas globalement les acides gras pairs en glucose.',check:['La néoglucogenèse est une simple glycolyse parcourue à l’envers enzyme par enzyme.',false,'Les étapes irréversibles exigent des contournements spécifiques.']}
 ],learning:{formula:{label:'Bilan glycolytique direct',expression:'1 glucose → 2 pyruvates + 2 ATP nets + 2 NADH',explanation:'Le rendement oxydatif des NADH dépend ensuite des navettes et de la chaîne respiratoire.'},comparison:{headers:['Voie','État dominant','Finalité'],rows:[['Glycolyse','Besoin énergétique','Former ATP et pyruvate'],['Glycogénogenèse','Abondance','Stocker le glucose'],['Néoglucogenèse','Jeûne','Maintenir le glucose sanguin']]},example:{prompt:'Quatre ATP sont formés et deux consommés pendant la glycolyse.',steps:['Compter la phase d’investissement : −2','Compter la phase de rendement : +4','Calculer 4 − 2'],result:'Le gain net direct est de 2 ATP par glucose.'},errors:[{title:'Production brute = bilan net',detail:'Il faut retrancher les ATP investis.'},{title:'Muscle fournisseur direct de glycémie',detail:'Son glycogène soutient d’abord sa propre activité.'},{title:'Néoglucogenèse exactement inverse',detail:'Trois étapes glycolytiques doivent être contournées.'}]}},
 'biochem-oxidative-phosphorylation':{minutes:32,objectives:['Relier chaîne respiratoire et gradient protonique','Calculer un rendement approximatif','Distinguer inhibiteur, découplant et fuite'],diagram:{title:'Des électrons à l’ATP mitochondrial',caption:'Le transfert d’électrons pompe des protons ; leur retour par l’ATP synthase couple respiration et phosphorylation.',kind:'flow'},sections:[
  {title:'Donneurs et complexes',text:'NADH donne ses électrons au complexe I, FADH2 via le complexe II. Coenzyme Q et cytochrome c sont des transporteurs mobiles. Les électrons terminent sur l’oxygène au complexe IV, formant de l’eau.',check:['L’oxygène est l’accepteur final des électrons de la chaîne respiratoire.',true,'Sa réduction au complexe IV permet le flux électronique.']},
  {title:'Pompage des protons',text:'Les complexes I, III et IV utilisent l’énergie du transfert électronique pour expulser des protons vers l’espace intermembranaire. Le complexe II ne pompe pas de protons. Le gradient comporte une composante chimique et une composante électrique.',check:['Le complexe II pompe autant de protons que le complexe I.',false,'Le complexe II transfère des électrons sans pompage direct.']},
  {title:'ATP synthase et couplage',text:'Le retour des protons selon leur gradient entraîne la rotation fonctionnelle de l’ATP synthase et la formation d’ATP. La membrane interne doit rester suffisamment imperméable. Respiration et synthèse d’ATP sont couplées sans être la même réaction.',check:['Le gradient protonique constitue l’intermédiaire entre oxydation et synthèse d’ATP.',true,'Il stocke une énergie électrochimique utilisable par l’ATP synthase.']},
  {title:'Inhibition et découplage',text:'Un inhibiteur de la chaîne bloque le transfert d’électrons et réduit consommation d’oxygène et ATP. Un découplant dissipe le gradient : la chaîne peut accélérer alors que la production d’ATP chute et que l’énergie devient chaleur.',check:['Un découplant peut augmenter la consommation d’oxygène tout en diminuant la production d’ATP.',true,'Le gradient fuit et la chaîne tente de le rétablir.']},
  {title:'Espèces réactives et contrôle',text:'Une fraction des électrons peut réduire partiellement l’oxygène et produire des espèces réactives. Des défenses enzymatiques et non enzymatiques limitent leurs effets. Elles participent aussi à des signaux ; les considérer toujours comme déchets ou toujours comme bénéfiques est simpliste.',check:['Toute espèce réactive de l’oxygène a uniquement un rôle pathologique.',false,'Leur quantité et leur localisation déterminent effets de signal ou dommages.']}
 ],learning:{formula:{label:'Rendement P/O approximatif',expression:'NADH ≈ 2,5 ATP   ·   FADH₂ ≈ 1,5 ATP',explanation:'Ce sont des valeurs de travail dépendant des navettes, fuites et coûts de transport.'},comparison:{headers:['Agent','Gradient','Consommation O₂'],rows:[['Inhibiteur de chaîne','Diminue','Diminue'],['Découplant','Dissipé','Peut augmenter'],['Inhibiteur ATP synthase','S’accumule','Diminue secondairement']]},example:{prompt:'Deux NADH et un FADH2 alimentent la chaîne.',steps:['2 × 2,5 = 5 ATP approximatifs','1 × 1,5 = 1,5 ATP','Additionner : 6,5 ATP'],result:'Le rendement théorique approximatif est 6,5 ATP, avant coûts et fuites.'},errors:[{title:'Complexe II pompeur',detail:'Il ne contribue pas directement au pompage protonique.'},{title:'Oxygène transformé en ATP',detail:'Il reçoit les électrons ; l’ATP vient du couplage protonique.'},{title:'Découplant = inhibiteur',detail:'Le flux d’électrons peut persister ou augmenter lors du découplage.'}]}},
 'embryo-gametogenesis':{minutes:30,objectives:['Comparer méioses masculine et féminine','Suivre capacitation et fécondation','Déduire ploïdie et quantité d’ADN'],diagram:{title:'De la cellule germinale au zygote',caption:'La méiose réduit la ploïdie ; la fécondation réunit deux génomes haploïdes et déclenche le développement.',kind:'flow'},sections:[
  {title:'Compter chromosomes et ADN',text:'Après réplication, le nombre de chromosomes compté par centromères reste stable mais la quantité d’ADN double. La méiose I sépare les homologues ; la méiose II sépare les chromatides. Il n’existe pas de nouvelle phase S entre les deux divisions.',check:['Une cellule après phase S possède deux fois plus de chromatides sans avoir doublé son nombre de chromosomes.',true,'Chaque chromosome répliqué comporte deux chromatides reliées.']},
  {title:'Brassage génétique',text:'La répartition indépendante des paires homologues et les recombinaisons créent de nouvelles associations d’allèles. Un crossing-over se produit entre chromatides non sœurs d’homologues appariés. Il ne crée pas nécessairement une mutation.',check:['Un crossing-over physiologique est obligatoirement une mutation pathologique.',false,'C’est un mécanisme normal de recombinaison méiotique.']},
  {title:'Spermatogenèse',text:'Une méiose produit quatre spermatides haploïdes, ensuite remodelées par spermiogenèse. Sertoli soutient les cellules germinales et Leydig produit des androgènes dans l’interstitium. La spermiogenèse change la forme sans modifier la ploïdie.',check:['La spermiogenèse est une différenciation sans nouvelle division méiotique.',true,'Elle transforme les spermatides en spermatozoïdes.']},
  {title:'Ovogenèse et arrêts',text:'L’ovocyte primaire reste arrêté en prophase I jusqu’à la reprise cyclique. L’ovocyte secondaire est arrêté en métaphase II et n’achève cette division qu’en relation avec la fécondation. Les divisions cytoplasmiques asymétriques conservent les réserves dans une grande cellule.',check:['L’ovocyte ovulé a normalement déjà achevé la méiose II.',false,'Il est généralement bloqué en métaphase II.']},
  {title:'Fécondation contrôlée',text:'Capacitation, réaction acrosomique, fusion membranaire, réaction corticale et activation ovocytaire s’enchaînent. Les mécanismes de blocage limitent la polyspermie. La fécondation ne se résume pas à une pénétration mécanique du premier spermatozoïde arrivé.',check:['La réaction corticale contribue à limiter la polyspermie.',true,'Elle modifie les enveloppes après la fusion.']}
 ],learning:{formula:{label:'Ploïdie et contenu en ADN',expression:'Avant S : 2n, 2C   ·   Après S : 2n, 4C   ·   Après méiose II : n, 1C',explanation:'n compte les jeux chromosomiques ; C représente une quantité relative d’ADN.'},comparison:{headers:['Étape','Séparation','Produit'],rows:[['Méiose I','Homologues','Deux cellules n, 2C'],['Méiose II','Chromatides','Cellules n, 1C'],['Fécondation','Fusion des génomes','Zygote 2n']]},example:{prompt:'Une cellule humaine en G2 contient 92 chromatides.',steps:['Compter les centromères : 46','Chaque chromosome a deux chromatides','La ploïdie reste diploïde'],result:'Elle possède 46 chromosomes, 92 chromatides et un contenu 4C.'},errors:[{title:'Chromatide = chromosome toujours',detail:'Le comptage dépend du centromère et de l’étape.'},{title:'Phase S entre les méioses',detail:'La réplication n’a lieu qu’avant la méiose I.'},{title:'Spermiogenèse troisième division',detail:'C’est un remodelage cellulaire.'}]}},
 'embryo-weeks-one-three':{minutes:34,objectives:['Reconstituer la chronologie des semaines 1 à 3','Relier gastrulation, axes et feuillets','Distinguer embryon et annexes'],diagram:{title:'Trois semaines pour établir le plan du corps',caption:'Segmentation, implantation puis gastrulation changent successivement nombre de cellules, relations tissulaires et axes.',kind:'flow'},sections:[
  {title:'Segmentation sans croissance',text:'Les divisions augmentent le nombre de blastomères sans accroître proportionnellement le volume global. Compaction, morula puis blastocyste se succèdent pendant le transport. L’éclosion de la zone pellucide permet l’interaction avec l’endomètre.',check:['La segmentation augmente rapidement le volume total de l’embryon.',false,'Elle subdivise surtout le volume initial en cellules plus petites.']},
  {title:'Blastocyste et lignages',text:'Le trophoblaste contribue aux interfaces extraembryonnaires ; la masse cellulaire interne donne notamment l’embryon. Leur distinction apparaît avant la gastrulation. Employer « embryon » pour toutes les cellules du conceptus masque les contributions annexielles.',check:['Trophoblaste et masse cellulaire interne ont des devenirs identiques.',false,'Ils contribuent à des compartiments différents.']},
  {title:'Disque bilaminaire',text:'Épiblaste et hypoblaste organisent le disque de la deuxième semaine avec cavité amniotique et vésicule vitelline. L’embryon n’est pas encore trilaminaire. Les rapports spatiaux importent pour comprendre les migrations ultérieures.',check:['Le disque bilaminaire précède le disque trilaminaire.',true,'La gastrulation transforme ensuite l’organisation.']},
  {title:'Gastrulation',text:'Des cellules de l’épiblaste ingressent par la ligne primitive pour former endoderme définitif et mésoderme, tandis que l’épiblaste restant devient ectoderme. Les trois feuillets viennent donc de l’épiblaste. La ligne primitive participe aussi à l’établissement des axes.',check:['Les trois feuillets embryonnaires définitifs dérivent de l’épiblaste.',true,'Les mouvements de gastrulation redistribuent ses cellules.']},
  {title:'Notochorde, tube et crêtes neurales',text:'La notochorde joue un rôle inducteur axial. La plaque neurale se replie en tube neural ; les crêtes neurales se détachent et migrent vers de nombreux territoires. Tube et crêtes ont des devenirs différents et doivent être suivis séparément.',check:['Tube neural et crêtes neurales désignent exactement la même population finale.',false,'Les crêtes migrent tandis que le tube forme le système nerveux central.']}
 ],learning:{formula:{label:'Chronologie de référence',expression:'J0 fécondation → J3 morula → J5 blastocyste → S2 disque bilaminaire → S3 gastrulation',explanation:'Ces repères sont pédagogiques et admettent une variabilité biologique.'},comparison:{headers:['Population','Origine','Contribution majeure'],rows:[['Trophoblaste','Blastocyste externe','Interfaces placentaires'],['Épiblaste','Masse interne','Trois feuillets'],['Hypoblaste','Disque bilaminaire','Structures extraembryonnaires']]},example:{prompt:'Une coupe montre épiblaste, hypoblaste et cavité amniotique sans ligne primitive.',steps:['Identifier un disque bilaminaire','Rechercher les annexes','Ne pas attribuer encore trois feuillets','Situer autour de la deuxième semaine'],result:'L’organisation précède la gastrulation et le disque trilaminaire.'},errors:[{title:'Segmentation = croissance',detail:'Le volume global varie peu au début.'},{title:'Hypoblaste source des trois feuillets',detail:'Ils dérivent de l’épiblaste.'},{title:'Crête neurale = tube neural',detail:'Ces populations se séparent et ont des devenirs distincts.'}]}},
 'embryo-placenta':{minutes:28,objectives:['Décrire circulation maternelle et fœtale','Expliquer les échanges placentaires','Suivre les dérivations fœtales'],diagram:{title:'Deux circulations séparées autour des villosités',caption:'Le sang maternel baigne l’espace intervilleux ; le sang fœtal reste dans les capillaires villositaires.',kind:'cycle'},sections:[
  {title:'Villosités et barrière',text:'Les villosités choriales portent les capillaires fœtaux et baignent dans le sang maternel de l’espace intervilleux. Les deux sangs ne circulent pas normalement dans un conduit commun. La barrière évolue au cours de la grossesse.',check:['Les circulations maternelle et fœtale restent normalement distinctes.',true,'Les échanges traversent les tissus villositaires.']},
  {title:'Échanges multiples',text:'Oxygène, dioxyde de carbone, nutriments, déchets, anticorps et certaines substances franchissent l’interface par des mécanismes différents. Le placenta n’est ni un filtre absolu ni une simple membrane passive.',check:['Le placenta bloque toutes les molécules étrangères au fœtus.',false,'Sa perméabilité est sélective mais non absolue.']},
  {title:'Cordon ombilical',text:'Deux artères ombilicales conduisent le sang du fœtus vers le placenta ; une veine ombilicale revient vers le fœtus. Les noms artère et veine reposent sur le sens par rapport au cœur, non sur la teneur en oxygène.',check:['La veine ombilicale transporte un sang relativement oxygéné vers le fœtus.',true,'Elle revient du placenta vers le cœur fœtal.']},
  {title:'Dérivations fœtales',text:'Conduit veineux, foramen ovale et conduit artériel orientent les flux en contournant partiellement foie et poumons. Les poumons reçoivent du sang mais n’assurent pas les échanges gazeux. Les shunts ne suppriment pas toute perfusion.',check:['La circulation fœtale évite totalement toute perfusion pulmonaire.',false,'Elle la réduit et la détourne en partie, sans l’abolir.']},
  {title:'Transition néonatale',text:'L’aération pulmonaire diminue la résistance vasculaire pulmonaire ; l’arrêt du flux placentaire modifie les résistances systémiques. Les changements de pression favorisent la fermeture fonctionnelle des dérivations, suivie d’un remodelage anatomique variable.',check:['La fermeture fonctionnelle du foramen ovale dépend notamment d’un changement de pressions atriales.',true,'La pression gauche devient supérieure à la droite après la transition.']}
 ],learning:{formula:{label:'Sens des vaisseaux',expression:'Artère : s’éloigne du cœur   ·   Veine : revient au cœur',explanation:'Cette définition reste vraie dans le cordon, même si l’oxygénation est opposée au schéma adulte systémique.'},comparison:{headers:['Dérivation','Connexion','Rôle'],rows:[['Conduit veineux','Veine ombilicale vers voie cave','Contourne en partie le foie'],['Foramen ovale','Atrium droit vers gauche','Contourne en partie les poumons'],['Conduit artériel','Artère pulmonaire vers aorte','Dérive le flux pulmonaire']]},example:{prompt:'Après la première respiration, la résistance pulmonaire chute.',steps:['Le débit pulmonaire augmente','Le retour veineux pulmonaire augmente','La pression atriale gauche dépasse la droite','Le clapet du foramen ovale se ferme fonctionnellement'],result:'La modification des pressions participe à la transition circulatoire.'},errors:[{title:'Sangs mélangés librement',detail:'Ils restent séparés par l’interface placentaire.'},{title:'Artère = sang désoxygéné',detail:'Le nom dépend du sens du flux.'},{title:'Poumon fœtal non perfusé',detail:'Le débit est réduit, pas nul.'}]}},
 'embryo-organogenesis':{minutes:32,objectives:['Relier plicature et organisation corporelle','Suivre intestin, cœur et membres','Raisonner sur les périodes sensibles'],diagram:{title:'Plicature et organogenèse : du disque au volume',caption:'Les replis transforment la géométrie tandis que migrations, rotations et cloisonnements construisent les organes.',kind:'flow'},sections:[
  {title:'Plicature tridimensionnelle',text:'Les replis céphalique, caudal et latéraux incorporent une partie de la vésicule vitelline et ferment la paroi ventrale. Cœur, diaphragme et intestin changent de position relative. Il faut passer d’une carte plane à un raisonnement volumique.',check:['La plicature incorpore une partie de la vésicule vitelline dans l’intestin primitif.',true,'Les replis délimitent le corps et le tube digestif.']},
  {title:'Intestin primitif',text:'Intestins antérieur, moyen et postérieur correspondent à des territoires continus, associés à des axes vasculaires. L’épithélium est surtout endodermique tandis que muscle, conjonctif, vaisseaux et innervation ont d’autres contributions.',check:['Un organe digestif complet dérive toujours d’un seul feuillet.',false,'Ses différents tissus ont plusieurs origines.']},
  {title:'Courbure et cloisonnement cardiaques',text:'Le tube cardiaque se courbe puis des septa, coussins et alignements séparent progressivement cavités et voies de sortie. Les crêtes neurales contribuent à certaines régions. Le cœur à quatre cavités n’apparaît pas par ajout instantané d’une cloison unique.',check:['Le cloisonnement cardiaque repose sur plusieurs structures et alignements successifs.',true,'Septa, coussins et voies de sortie se coordonnent.']},
  {title:'Bourgeons des membres',text:'Les axes proximal-distal, antéro-postérieur et dorso-ventral sont contrôlés par des centres de signalisation. Croissance, segmentation et mort cellulaire sculptent les rayons digitaux. Une perturbation dépend du moment et du territoire exposé.',check:['Les doigts se séparent notamment grâce à une mort cellulaire programmée interdigital.',true,'L’apoptose participe au modelage des espaces.']},
  {title:'Périodes sensibles',text:'Le risque dépend du moment, de la dose, de la durée, du mécanisme et du génotype. L’organogenèse est une période de vulnérabilité structurale importante, mais la période fœtale reste sensible pour croissance et maturation. Une association temporelle ne prouve pas seule une causalité.',check:['Après l’organogenèse, tout développement devient insensible aux perturbations.',false,'Croissance et maturation peuvent encore être affectées.']}
 ],learning:{formula:{label:'Raisonnement temporel',expression:'Effet potentiel = processus en cours × exposition × susceptibilité',explanation:'Cette relation qualitative empêche de conclure à partir du seul nom d’un agent.'},comparison:{headers:['Période','Processus dominant','Risque pédagogique'],rows:[['Préimplantatoire','Segmentation','Effets précoces variables'],['Embryonnaire','Organogenèse','Anomalies structurales'],['Fœtale','Croissance et maturation','Atteintes fonctionnelles ou croissance']]},example:{prompt:'Une structure paraît changer brutalement de position entre deux schémas.',steps:['Identifier le plan de coupe','Rechercher plicature ou rotation','Suivre les attaches et axes vasculaires','Comparer les stades, pas seulement les formes'],result:'Le déplacement apparent peut provenir d’une transformation tridimensionnelle normale.'},errors:[{title:'Adulte miniature',detail:'L’embryon se transforme par mouvements et interactions tissulaires.'},{title:'Un organe, un feuillet',detail:'Chaque organe combine souvent plusieurs origines.'},{title:'Risque identique à tout âge',detail:'La fenêtre du processus modifie la conséquence.'}]}},
 'immuno-innate':{minutes:30,objectives:['Relier barrières, détection et inflammation','Décomposer recrutement leucocytaire','Expliquer complément et phagocytose'],diagram:{title:'De la détection tissulaire au contrôle de l’agression',caption:'Reconnaissance, médiateurs, recrutement et élimination forment une réponse coordonnée avec mécanismes de résolution.',kind:'flow'},sections:[
  {title:'Barrières et microbiote',text:'Peau, mucus, cils, pH, peptides antimicrobiens et microbiote limitent l’implantation. Une barrière est active et renouvelée. Sa rupture augmente l’exposition mais ne détermine pas seule l’issue, qui dépend aussi de la réponse locale.',check:['Les barrières innées associent mécanismes physiques, chimiques et biologiques.',true,'Elles ne se réduisent pas à une paroi inerte.']},
  {title:'Reconnaissance de motifs',text:'Des récepteurs reconnaissent des motifs microbiens ou de dommage et activent des programmes cellulaires. Cette reconnaissance est large sans être dépourvue de spécificité moléculaire. Les signaux produits dépendent du récepteur, de la cellule et du contexte.',check:['L’immunité innée ne reconnaît aucune structure moléculaire particulière.',false,'Ses récepteurs reconnaissent des familles de motifs.']},
  {title:'Inflammation et endothélium',text:'Médiateurs modifient débit, perméabilité et molécules d’adhérence. Roulement, activation, adhérence ferme puis diapédèse permettent aux leucocytes de quitter le sang. Rougeur, chaleur, gonflement et douleur ont des mécanismes liés mais distincts.',check:['La diapédèse désigne le passage d’un leucocyte à travers la paroi vasculaire.',true,'Elle suit les étapes de roulement et d’adhérence.']},
  {title:'Phagocytose',text:'Reconnaissance, ingestion, phagosome, fusion lysosomale et destruction se succèdent. L’opsonisation facilite la reconnaissance. Neutrophiles et macrophages partagent des fonctions mais diffèrent par durée de vie, localisation et rôles de signalisation.',check:['L’opsonisation peut faciliter la phagocytose.',true,'Les opsonines sont reconnues par des récepteurs phagocytaires.']},
  {title:'Complément et résolution',text:'Les voies du complément convergent vers opsonisation, inflammation et complexe d’attaque membranaire. Des régulateurs protègent les cellules de l’hôte. La résolution est un processus actif qui limite le recrutement, élimine les débris et favorise la réparation.',check:['La résolution de l’inflammation correspond seulement à l’épuisement passif des médiateurs.',false,'Elle implique des signaux actifs et des fonctions de réparation.']}
 ],learning:{formula:{label:'Séquence de recrutement',expression:'Roulement → activation → adhérence → diapédèse → chimiotaxie',explanation:'Chaque étape mobilise des interactions différentes ; leur ordre aide à localiser un défaut.'},comparison:{headers:['Acteur','Atout','Limite'],rows:[['Neutrophile','Arrivée rapide et destruction','Vie courte'],['Macrophage','Phagocytose et coordination','Réponse dépend du tissu'],['Complément','Amplification soluble','Doit être régulé']]},example:{prompt:'Une bactérie est couverte de C3b.',steps:['C3b agit comme opsonine','Un récepteur phagocytaire le reconnaît','L’adhérence et l’ingestion sont facilitées','La destruction reste une étape distincte'],result:'L’opsonisation augmente l’efficacité de reconnaissance sans tuer toujours directement.'},errors:[{title:'Innée = non spécifique',detail:'Elle reconnaît des motifs définis avec un répertoire germinal.'},{title:'Inflammation toujours nocive',detail:'Elle protège mais doit être proportionnée et résolue.'},{title:'Phagocytose = digestion immédiate',detail:'Ingestion et destruction sont des étapes successives.'}]}},
 'immuno-adaptive':{minutes:34,objectives:['Comparer activation des lymphocytes B et T','Relier présentation antigénique et effecteurs','Expliquer mémoire et tolérance'],diagram:{title:'Sélection clonale et réponse adaptative',caption:'Un antigène sélectionne des clones rares ; signaux d’activation, expansion et différenciation produisent effecteurs et mémoire.',kind:'branch'},sections:[
  {title:'Récepteurs et diversité',text:'Chaque clone porte un récepteur issu de réarrangements somatiques. Le répertoire existe avant la rencontre antigénique ; l’antigène sélectionne les clones compatibles. Cette diversité impose des mécanismes de tolérance pour limiter l’auto-réactivité.',check:['L’antigène fabrique sur mesure un nouveau récepteur dans chaque lymphocyte.',false,'Il sélectionne des clones dont les récepteurs existent déjà.']},
  {title:'Présentation aux lymphocytes T',text:'Le TCR reconnaît un peptide présenté par une molécule du CMH, et non l’antigène libre seul. Le CMH I présente à des T CD8, le CMH II à des T CD4 dans le schéma de base. Co-stimulation et cytokines complètent le signal antigénique.',check:['Le TCR reconnaît classiquement un peptide associé au CMH.',true,'La reconnaissance T est restreinte par le CMH.']},
  {title:'Activation des lymphocytes B',text:'Le BCR reconnaît l’antigène natif. Après activation, les cellules prolifèrent et deviennent plasmocytes ou cellules mémoire. L’aide T favorise commutation de classe, maturation d’affinité et mémoire pour de nombreuses réponses protéiques.',check:['Un plasmocyte est une cellule spécialisée dans la sécrétion d’anticorps.',true,'L’anticorps est une molécule, pas une cellule.']},
  {title:'Effecteurs T',text:'Les T CD4 coordonnent d’autres cellules par contact et cytokines ; les T CD8 peuvent tuer des cellules présentant une cible appropriée. Cytotoxicité et anticorps sont des mécanismes différents. L’activation doit être contrôlée pour éviter dommages collatéraux.',check:['Les lymphocytes T CD8 exercent notamment une cytotoxicité cellulaire ciblée.',true,'Ils reconnaissent des peptides sur le CMH I des cellules cibles.']},
  {title:'Mémoire, tolérance et vaccination',text:'Après contraction de la réponse, des cellules mémoire persistent et répondent plus vite ou plus efficacement lors d’une nouvelle exposition. La vaccination cherche cette mémoire sans imposer la maladie correspondante. Tolérances centrale et périphérique limitent les réponses contre le soi.',check:['La mémoire immunitaire signifie que tous les effecteurs restent constamment très nombreux.',false,'Une population mémoire persiste après la contraction des effecteurs.']}
 ],learning:{formula:{label:'Dynamique clonale',expression:'Reconnaissance + co-stimulation + cytokines → expansion → effecteurs + mémoire',explanation:'La reconnaissance isolée ne garantit pas une activation complète et peut conduire à d’autres destins.'},comparison:{headers:['Cellule','Reconnaissance','Fonction majeure'],rows:[['Lymphocyte B','Antigène natif via BCR','Anticorps après différenciation'],['T CD4','Peptide-CMH II','Coordination'],['T CD8','Peptide-CMH I','Cytotoxicité']]},example:{prompt:'Une cellule présente un peptide sur CMH I à un T CD8 activé.',steps:['Le TCR reconnaît le complexe','Les signaux d’adhérence stabilisent le contact','Les granules cytotoxiques peuvent être dirigés','La cellule cible engage sa mort'],result:'La cytotoxicité est ciblée et distincte de la neutralisation par anticorps.'},errors:[{title:'Anticorps = cellule',detail:'C’est une immunoglobuline sécrétée notamment par les plasmocytes.'},{title:'TCR reconnaît antigène libre',detail:'Il reconnaît un peptide présenté par le CMH.'},{title:'Mémoire = réponse permanente maximale',detail:'Les effecteurs diminuent puis des cellules mémoire persistent.'}]}}
})

export function enrichCoreCourses(courses:Course[]):Course[]{return courses.map(course=>{const module=modules[course.id];if(!module)return course;return {...course,minutes:module.minutes,objectives:module.objectives,sections:[...course.sections,...module.sections.map(({title,text})=>({title,text}))],learning:module.learning}})}

export const coreLearningDiagrams:Record<string,Diagram>=Object.fromEntries(Object.entries(modules).map(([id,module])=>[id,{...module.diagram,nodes:module.sections.map(section=>({label:section.title,detail:section.text}))}]))

export const coreLearningQuestions:Question[]=Object.entries(modules).flatMap(([course,module])=>{
 const checks:Check[]=[...module.sections.map(section=>section.check),...module.learning.comparison.rows.slice(0,2).map(row=>[`${row[0]} est correctement associé à : ${row[1]}.`,true,`${row[0]} : ${row[1]}. ${row[2]}`] as Check),[`${module.learning.example.prompt} La conclusion proposée est : ${module.learning.example.result}`,true,module.learning.example.steps.join(' ')],...module.learning.errors.slice(0,3).map(error=>[error.title+' : cette formulation est correcte.',false,error.detail] as Check)]
 return checks.map(([statement,correct,explanation],index)=>({id:`core-${course}-${String(index+1).padStart(2,'0')}`,course,topic:'',prompt:statement,options:['Vrai','Faux'],correct:[correct?0:1],why:[explanation,explanation],difficulty:index<6?'essentiel':'application',format:'boolean'}))
})
