import {useEffect,useState} from 'react'
import {ArrowLeft,ArrowRight,BookOpen,Check,CheckCircle2,Search,Box,Bookmark,GraduationCap} from 'lucide-react'
import {courses,categories} from './curriculum'
import diseases from '../data/diseases.json'
import {lessons} from '../learning'
export default function CoursesWorkspace(p:{initial:string|null;completed:string[];complete:(id:string)=>void;explore:(id:string)=>void;practice:(id:string)=>void;navigate:(id:string|null)=>void}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('Tous les cours'),[reveal,setReveal]=useState(false),[pathology,setPathology]=useState<string|null>(null)
 const course=courses.find(c=>c.id===p.initial)
 useEffect(()=>{setReveal(false);setPathology(null);document.querySelector('.study-workspace')?.scrollTo(0,0)},[p.initial])
 const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/œ/g,'oe').toLowerCase()
 const filtered=courses.filter(c=>(category==='Tous les cours'||c.category===category)&&normalize(`${c.title} ${c.tag}`).includes(normalize(query)))
 const disease=diseases.find(d=>d.id===pathology)
 return <section className="study-workspace courses-workspace" aria-label="Cours de première année">
 {course?<><div className="study-breadcrumb"><button onClick={()=>p.navigate(null)}><ArrowLeft size={16}/>Tous les cours</button><span>/</span><span>{course.tag}</span></div><div className="reading-layout"><article className="course-article"><div className="study-eyebrow">{course.category} · FICHE DE RÉVISION</div><h1>{course.title}</h1><div className="course-meta"><span><BookOpen size={14}/>{course.minutes} min estimées</span><span><GraduationCap size={15}/>Première année</span>{p.completed.includes(course.id)&&<span><CheckCircle2 size={15}/>Terminé</span>}</div><div className="objectives"><h2>À la fin de ce cours</h2>{course.objectives.map(o=><p key={o}><Check size={16}/>{o}</p>)}</div>
 {course.sections.map((s,i)=><section id={`section-${i}`} className="course-section" key={s.title}><span className="section-number">{String(i+1).padStart(2,'0')}</span><div><h2>{s.title}</h2><p>{s.text}</p>{s.bullets&&<ul>{s.bullets.map(t=><li key={t}>{t}</li>)}</ul>}</div></section>)}
 {course.id==='FMA7088'&&<div className="circulation-strip" aria-label="Trajet simplifié de la circulation"><span>Corps</span><ArrowRight/><span>Cœur droit</span><ArrowRight/><span>Poumons</span><ArrowRight/><span>Cœur gauche</span><ArrowRight/><span>Corps</span></div>}
 <aside className="exam-trap"><Bookmark size={21}/><div><h2>Le point à ne pas confondre</h2><p>{course.trap}</p></div></aside>
 <section className="active-recall"><div className="study-eyebrow">RAPPEL ACTIF</div><h2>Fermez le cours. Retrouvez l’idée.</h2><p>{course.recall}</p><button className="study-secondary" aria-expanded={reveal} onClick={()=>setReveal(v=>!v)}>{reveal?'Masquer la réponse':'Vérifier ma réponse'}</button>{reveal&&<p className="recall-answer">{course.answer}</p>}</section>
 {lessons.find(l=>l.id===course.id)?.diseases.length ? <section className="course-pathologies"><h2>Ouverture clinique</h2><p>À aborder après les bases. Ces repères ne constituent pas un avis médical.</p><div className="pathology-pills">{lessons.find(l=>l.id===course.id)!.diseases.map(id=><button key={id} onClick={()=>setPathology(pathology===id?null:id)} aria-expanded={pathology===id}>{diseases.find(d=>d.id===id)?.name}</button>)}</div>{disease&&<div className="disease-reading"><h3>{disease.name}</h3>{Object.entries(disease.sections).map(([k,v])=><section key={k}><h4>{k}</h4><p>{v}</p></section>)}<a href={disease.source} target="_blank" rel="noreferrer">Consulter la source médicale ↗</a></div>}</section>:null}
 <footer className="course-source"><a href={course.source} target="_blank" rel="noreferrer">Source pédagogique du cours ↗</a><p>Synthèse pédagogique en français. Complétez-la avec les supports et les attendus de votre faculté.</p></footer>
 <div className="course-completion"><button className="study-secondary" onClick={()=>p.complete(course.id)} disabled={p.completed.includes(course.id)}><CheckCircle2 size={17}/>{p.completed.includes(course.id)?'Cours terminé':'Marquer ce cours terminé'}</button><button className="study-primary" onClick={()=>p.practice(course.id)}>M’entraîner sur ce cours<ArrowRight size={17}/></button></div>
 </article><aside className="reading-sidebar"><span className="study-eyebrow">DANS CE COURS</span>{course.sections.map((s,i)=><a key={s.title} href={`#section-${i}`} onClick={e=>{e.preventDefault();document.getElementById(`section-${i}`)?.scrollIntoView({behavior:'smooth',block:'start'})}}><span>{String(i+1).padStart(2,'0')}</span>{s.title}</a>)}{course.structure&&<button className="anatomy-link" onClick={()=>p.explore(course.structure!)}><Box size={27}/><strong>Donnez du relief au cours.</strong><span>Retrouver la structure dans l’atlas 3D</span><ArrowRight size={19}/></button>}<div className="study-note">Comprendre → visualiser → se tester.<br/>Une notion, trois façons de l’apprendre.</div></aside></div></>:<><header className="study-page-heading"><div><span className="study-eyebrow">LE CAMPUS CORPUS · PREMIÈRE ANNÉE</span><h1>Comprendre avant<br/><em>d’apprendre par cœur.</em></h1><p>Des bases claires, des repères visuels et du rappel actif.<br/>Votre espace pour faire le lien entre anatomie et physiologie.</p></div><div className="course-progress"><BookOpen size={25}/><strong>{p.completed.length}<small> / {courses.length}</small></strong><span>cours terminés</span><progress max={courses.length} value={p.completed.length}/></div></header>
 <div className="course-toolbar"><div className="category-tabs" aria-label="Matières">{categories.map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div><label className="course-search"><Search size={17}/><input aria-label="Rechercher un cours" placeholder="Trouver un sujet…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 <div className="course-grid">{filtered.map((c,i)=><button className={`course-tile ${c.structure?'organ-course':'foundation-course'}`} key={c.id} onClick={()=>p.navigate(c.id)}><div className="course-tile-art" aria-hidden="true">{c.structure&&c.id!=="orientation"?<img src={`${import.meta.env.BASE_URL}course-previews/${c.structure}.png`} alt="" loading="lazy"/>:null}<span className={c.structure&&c.id!=="orientation"?"sr-only":""}>{c.structure?<Box size={56} strokeWidth={.8}/>:<BookOpen size={56} strokeWidth={.8}/>}</span><b>{String(courses.indexOf(c)+1).padStart(2,'0')}</b><div className="art-orbit"/></div><div className="course-tile-body"><span className="study-eyebrow">{c.tag}</span><h2>{c.title}</h2><p>{c.objectives[0]}</p><div className="course-tile-footer"><span>{c.minutes} min · {c.sections.length} notions</span>{p.completed.includes(c.id)?<CheckCircle2 size={20}/>:<ArrowRight size={19}/>}</div></div><span className="sr-only">Ouvrir le cours {i+1}</span></button>)}</div>{!filtered.length&&<p className="study-empty">Aucun cours ne correspond à cette recherche.</p>}<p className="curriculum-note">Socle d’anatomie et de physiologie pour commencer les études de santé. Ce parcours ne couvre pas l’ensemble d’un programme PASS ou L.AS. Aperçus : BodyParts3D, DBCLS, <a href={`${import.meta.env.BASE_URL}course-previews/LICENSE.txt`} target="_blank" rel="noreferrer">CC BY-SA 2.1 Japon</a>.</p></>}
 </section>
}
