import {useEffect,useRef,useState} from 'react'
import {ArrowLeft,ArrowRight,BookOpen,Check,CheckCircle2,Search,Box,Bookmark,GraduationCap,PenLine} from 'lucide-react'
import {courses,categories,type Course} from './curriculum'
import {questions} from './questions'
import CourseDiagram from './CourseDiagram'
import diseases from '../data/diseases.json'
import {lessons} from '../learning'

function readSaved():string[]{try{const v=JSON.parse(localStorage.getItem('corpus-saved-courses')||'[]');return Array.isArray(v)?v.filter(id=>courses.some(c=>c.id===id)):[]}catch{return []}}
function Notebook({course}:{course:Course}){
 const key='corpus-note-'+course.id
 const [note,setNote]=useState(()=>{try{return localStorage.getItem(key)||''}catch{return ''}}),[notice,setNotice]=useState('Enregistrées sur cet appareil uniquement.')
 return <section className="course-notebook"><h2><PenLine size={19}/>Mon carnet de cours</h2><p>Reformulez une notion, notez votre erreur ou une question à poser en cours.</p><textarea aria-label="Mes notes de cours" maxLength={8000} value={note} placeholder="Ce que je veux retenir…" onChange={e=>{setNote(e.target.value);try{localStorage.setItem(key,e.target.value);setNotice('Notes enregistrées sur cet appareil.')}catch{setNotice('Enregistrement indisponible : copiez vos notes avant de quitter.')}}}/><small role="status">{notice}</small></section>
}
export default function CoursesWorkspace(p:{initial:string|null;completed:string[];complete:(id:string)=>void;explore:(id:string)=>void;practice:(id:string)=>void;navigate:(id:string|null)=>void}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('Tous les cours'),[filter,setFilter]=useState('all'),[saved,setSaved]=useState(readSaved),[reveal,setReveal]=useState(false),[pathology,setPathology]=useState<string|null>(null),[progress,setProgress]=useState(0)
 const workspace=useRef<HTMLElement>(null),course=courses.find(c=>c.id===p.initial)
 useEffect(()=>{setReveal(false);setPathology(null);setProgress(0);workspace.current?.scrollTo(0,0)},[p.initial])
 const normalize=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/œ/g,'oe').toLowerCase()
 const filtered=courses.filter(c=>(category==='Tous les cours'||c.category===category)&&(filter==='all'||(filter==='saved'?saved.includes(c.id):!p.completed.includes(c.id)))&&normalize(c.title+' '+c.tag+' '+c.category+' '+c.objectives.join(' ')).includes(normalize(query)))
 const disease=diseases.find(d=>d.id===pathology),nextCourse=course?courses[courses.indexOf(course)+1]:null
 const toggleSave=(id:string)=>{const next=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];setSaved(next);try{localStorage.setItem('corpus-saved-courses',JSON.stringify(next))}catch{/* optional */}}
 const questionCount=(id:string)=>questions.filter(q=>q.course===id).length
 return <section ref={workspace} onScroll={e=>{const el=e.currentTarget;setProgress(Math.round(el.scrollTop/Math.max(1,el.scrollHeight-el.clientHeight)*100))}} className="study-workspace courses-workspace" aria-label="Cours de première année">
 {course?<>
  <div className="reading-progress"><span style={{width:progress+'%'}}/></div>
  <div className="study-breadcrumb"><button onClick={()=>p.navigate(null)}><ArrowLeft size={16}/>Tous les cours</button><span>/</span><span>{course.category}</span><button className="bookmark-course" aria-pressed={saved.includes(course.id)} onClick={()=>toggleSave(course.id)}><Bookmark size={15}/>{saved.includes(course.id)?'Enregistré':'Garder pour plus tard'}</button></div>
  <div className="reading-layout"><article className="course-article">
   <div className="study-eyebrow">{course.category} · {course.caseStudy?'COURS & APPLICATIONS':'REPÈRES ANATOMIQUES'}</div><h1>{course.title}</h1>
   <div className="course-meta"><span><BookOpen size={14}/>{course.minutes} min avec exercices</span><span><GraduationCap size={15}/>Première année</span><span>{questionCount(course.id)} questions associées</span>{p.completed.includes(course.id)&&<span><CheckCircle2 size={15}/>Terminé</span>}</div>
   <div className="objectives"><h2>À la fin de ce cours</h2>{course.objectives.map(o=><p key={o}><Check size={16}/>{o}</p>)}</div>
   <CourseDiagram key={'diagram-'+course.id} courseId={course.id}/>
   {course.sections.map((s,i)=><section id={'section-'+i} className="course-section" key={s.title}><span className="section-number">{String(i+1).padStart(2,'0')}</span><div><h2>{s.title}</h2>{s.text.split('\n\n').map((paragraph,j)=><p key={j}>{paragraph}</p>)}{s.bullets&&<ul>{s.bullets.map(t=><li key={t}>{t}</li>)}</ul>}</div></section>)}
   {(course.flow||course.id==='FMA7088')&&<figure className="course-flow"><figcaption>Le mécanisme en un regard</figcaption><ol>{(course.flow||['Corps','Cœur droit','Poumons','Cœur gauche','Corps']).map((step,i)=><li key={i}><span>{i+1}</span>{step}</li>)}</ol></figure>}
   {course.glossary&&<section className="course-glossary"><h2>Les mots à maîtriser</h2><dl>{course.glossary.map(([term,definition])=><div key={term}><dt>{term}</dt><dd>{definition}</dd></div>)}</dl></section>}
   <aside className="exam-trap"><Bookmark size={21}/><div><h2>Le point à ne pas confondre</h2><p>{course.trap}</p></div></aside>
   {course.caseStudy&&<section className="course-case"><span className="study-eyebrow">PASSER DE LA NOTION AU RAISONNEMENT</span><h2>À vous de l’expliquer.</h2><p>{course.caseStudy.prompt}</p><details key={course.id}><summary>Comparer avec le raisonnement corrigé</summary><p>{course.caseStudy.answer}</p></details></section>}
   <section className="active-recall"><div className="study-eyebrow">RAPPEL ACTIF</div><h2>Fermez le cours. Retrouvez l’idée.</h2><p>{course.recall}</p><button className="study-secondary" aria-expanded={reveal} onClick={()=>setReveal(v=>!v)}>{reveal?'Masquer la réponse':'Vérifier ma réponse'}</button>{reveal&&<p className="recall-answer">{course.answer}</p>}</section>
   {lessons.find(l=>l.id===course.id)?.diseases.length?<section className="course-pathologies"><h2>Ouverture clinique</h2><p>À aborder après les bases. Ces repères ne constituent pas un avis médical.</p><div className="pathology-pills">{lessons.find(l=>l.id===course.id)!.diseases.map(id=><button key={id} onClick={()=>setPathology(pathology===id?null:id)} aria-expanded={pathology===id}>{diseases.find(d=>d.id===id)?.name}</button>)}</div>{disease&&<div className="disease-reading"><h3>{disease.name}</h3>{Object.entries(disease.sections).map(([k,v])=><section key={k}><h4>{k}</h4><p>{v}</p></section>)}<a href={disease.source} target="_blank" rel="noreferrer">Consulter la source médicale ↗</a></div>}</section>:null}
   <Notebook key={course.id} course={course}/>
   <footer className="course-source"><h2>Pour vérifier et approfondir</h2>{(course.sources||[{label:'Source pédagogique du cours',url:course.source}]).map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.label} ↗</a>)}<p>Synthèse pédagogique en français. Complétez-la avec les supports et les attendus de votre faculté.</p></footer>
   <div className="course-completion"><button className="study-secondary" onClick={()=>p.complete(course.id)} disabled={p.completed.includes(course.id)}><CheckCircle2 size={17}/>{p.completed.includes(course.id)?'Cours terminé':'Marquer ce cours terminé'}</button><button className="study-primary" onClick={()=>p.practice(course.id)}>M’entraîner sur ce cours<ArrowRight size={17}/></button></div>
   {nextCourse&&<button className="next-chapter" onClick={()=>p.navigate(nextCourse.id)}><span>POURSUIVRE LA LECTURE<strong>{nextCourse.title}</strong></span><ArrowRight size={21}/></button>}
  </article><aside className="reading-sidebar"><span className="study-eyebrow">DANS CE COURS · {progress}% LU</span>{course.sections.map((s,i)=><a key={s.title} href={'#section-'+i} onClick={e=>{e.preventDefault();document.getElementById('section-'+i)?.scrollIntoView({behavior:'smooth',block:'start'})}}><span>{String(i+1).padStart(2,'0')}</span>{s.title}</a>)}{course.structure&&<button className="anatomy-link" onClick={()=>p.explore(course.structure!)}><Box size={27}/><strong>Donnez du relief au cours.</strong><span>Retrouver la structure dans l’atlas 3D</span><ArrowRight size={19}/></button>}<button className="study-secondary sidebar-practice" onClick={()=>p.practice(course.id)}>Tester ce chapitre · {questionCount(course.id)} questions<ArrowRight size={15}/></button><div className="study-note">Lire → reformuler → résoudre.<br/>Le défilement mesure la lecture, pas l’acquisition.</div></aside></div>
 </>:<>
  <header className="study-page-heading"><div><span className="study-eyebrow">LE CAMPUS CORPUS · PREMIÈRE ANNÉE</span><h1>Votre bibliothèque.<br/><em>Votre prochaine découverte.</em></h1><p>De la cellule aux grands systèmes : comprendre les mécanismes,<br/>les expliquer avec vos mots, puis vous tester.</p><div className="library-stats"><span>{courses.length} cours</span><span>{categories.length-1} matières</span><span>{questions.length} questions corrigées</span></div></div><div className="course-progress"><BookOpen size={25}/><strong>{p.completed.length}<small> / {courses.length}</small></strong><span>cours terminés</span><progress max={courses.length} value={p.completed.length}/></div></header>
  <div className="course-toolbar"><div className="category-tabs" aria-label="Matières">{categories.map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div><label className="course-search"><Search size={17}/><input aria-label="Rechercher un cours" placeholder="Un chapitre, une notion…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
  <div className="library-filter"><span>{filtered.length} cours à explorer</span><select aria-label="Afficher les cours" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Tous les cours</option><option value="saved">Enregistrés pour plus tard</option><option value="remaining">À terminer</option></select></div>
  <div className="course-grid">{filtered.map((c,i)=><button className={'course-tile '+(c.structure?'organ-course':'foundation-course')} key={c.id} onClick={()=>p.navigate(c.id)}><div className="course-tile-art" aria-hidden="true">{c.structure&&c.id!=='orientation'?<img src={import.meta.env.BASE_URL+'course-previews/'+c.structure+'.png'} alt="" loading="lazy"/>:null}<span className={c.structure&&c.id!=='orientation'?'sr-only':''}>{c.structure?<Box size={56} strokeWidth={.8}/>:<BookOpen size={56} strokeWidth={.8}/>}</span><b>{String(courses.indexOf(c)+1).padStart(2,'0')}</b><div className="art-orbit"/></div><div className="course-tile-body"><span className="study-eyebrow">{c.category}</span><h2>{c.title}</h2><p>{c.objectives[0]}</p><div className="course-tile-footer"><span>{c.minutes} min · {questionCount(c.id)} questions</span>{p.completed.includes(c.id)?<CheckCircle2 size={20}/>:saved.includes(c.id)?<Bookmark size={19}/>:<ArrowRight size={19}/>}</div></div><span className="sr-only">Ouvrir le cours {i+1}</span></button>)}</div>
  {!filtered.length&&<p className="study-empty">Aucun cours ne correspond à cette recherche.</p>}<p className="curriculum-note">Ce parcours ne couvre pas l’ensemble d’un programme PASS ou L.AS. Aperçus : BodyParts3D, DBCLS, <a href={import.meta.env.BASE_URL+'course-previews/LICENSE.txt'} target="_blank" rel="noreferrer">CC BY-SA 2.1 Japon</a>.</p>
 </>}
 </section>
}
