import type {Course} from './curriculum'
// Applications rédigées à partir des notions documentées par chaque fiche.
export const applications:Record<string,Pick<Course,'caseStudy'|'glossary'|'flow'>>={
 orientation:{glossary:[['Proximal','Plus proche de l’origine ou de l’attache d’un membre.'],['Latéral','Plus éloigné du plan médian.']],caseStudy:{prompt:'Vous faites tourner le modèle jusqu’à le voir de dos. Le rein droit devient-il le rein gauche ? Expliquez le repère utilisé.',answer:'Non. Les côtés appartiennent au sujet et non à l’observateur. Une rotation de caméra change l’image, pas la nomenclature anatomique.'}},
 homeostasis:{flow:['Variation','Capteur','Intégration','Effecteur','Réponse'],glossary:[['Variable régulée','Grandeur maintenue dans une plage fonctionnelle.'],['Effecteur','Structure réalisant la réponse.']],caseStudy:{prompt:'Une hausse de température déclenche une réponse qui favorise une perte de chaleur. Quel est le signe du rétrocontrôle et pourquoi ?',answer:'Il est négatif : la réponse tend à s’opposer à la variation initiale. On raisonne sur le sens de la variation, pas sur le caractère agréable ou désagréable de la réponse.'}},
 membrane:{glossary:[['Gradient','Différence d’une grandeur entre deux régions.'],['Transport passif','Déplacement suivant le gradient électrochimique sans apport d’énergie métabolique au transport.']],caseStudy:{prompt:'Une molécule traverse par un transporteur en suivant son gradient. Un étudiant conclut : « Il y a une protéine, donc c’est actif. » Corrigez son raisonnement.',answer:'La présence d’un transporteur ne prouve pas un transport actif. Il faut examiner le sens du déplacement et sa source d’énergie. La diffusion facilitée est passive malgré sa protéine de transport.'}},
 tissues:{glossary:[['Tissu','Organisation de cellules et de leur environnement extracellulaire.'],['Organe','Ensemble organisé de plusieurs tissus.']],caseStudy:{prompt:'Dans un organe, vous identifiez un revêtement, des vaisseaux, des nerfs et des cellules contractiles. Faut-il choisir une seule famille de tissus pour cet organe ?',answer:'Non. L’organe associe plusieurs tissus complémentaires. Le revêtement oriente vers l’épithélial, les éléments de soutien vers le conjonctif, la communication vers le nerveux et la contraction vers le musculaire.'}},
 FMA7088:{glossary:[['Atrium','Cavité cardiaque recevant le retour veineux.'],['Ventricule','Cavité éjectant le sang vers une circulation.']],caseStudy:{prompt:'Suivez une goutte de sang qui quitte le ventricule droit jusqu’à son retour dans le cœur. Dans quelle cavité revient-elle ?',answer:'Elle passe par le tronc pulmonaire, la circulation pulmonaire puis les veines pulmonaires et rejoint l’atrium gauche. Ce trajet aide à distinguer sens de circulation et oxygénation.'}},
 FMA7309:{flow:['Voies aériennes','Alvéoles','Barrière alvéolocapillaire','Sang'],glossary:[['Ventilation','Renouvellement de l’air.'],['Perfusion','Circulation de sang dans un territoire.']],caseStudy:{prompt:'Une alvéole reçoit de l’air mais pratiquement pas de sang. Une ventilation conservée garantit-elle des échanges efficaces ?',answer:'Non. La ventilation apporte le gaz, mais la perfusion est nécessaire pour transporter les gaz dans le sang. Il faut examiner les deux flux ensemble.'}},
 FMA7197:{glossary:[['Bile','Sécrétion hépatique participant à la digestion des lipides.'],['Hépatique','Qui concerne le foie.']],caseStudy:{prompt:'Un étudiant confond le lieu de production et le lieu de stockage de la bile. Comment rectifier cette confusion ?',answer:'Le foie produit la bile. La vésicule biliaire la stocke et la concentre. Produire, stocker et acheminer sont trois fonctions à distinguer.'}},
 FMA7148:{flow:['Œsophage','Estomac','Duodénum'],glossary:[['Chyme','Contenu issu du mélange gastrique.'],['Pylore','Région de sortie de l’estomac vers le duodénum.']],caseStudy:{prompt:'Pourquoi le brassage gastrique ne suffit-il pas à résumer toute la digestion ?',answer:'Il prépare et mélange le contenu, mais la digestion se poursuit dans l’intestin grêle, qui assure aussi une part majeure de l’absorption. Brassage et absorption sont des fonctions différentes.'}},
 FMA7198:{glossary:[['Endocrine','Libération d’un message hormonal dans le milieu intérieur.'],['Exocrine','Sécrétion vers une surface ou par un conduit.']],caseStudy:{prompt:'Deux produits du pancréas sont décrits : une enzyme envoyée au duodénum et une hormone libérée dans le sang. Relèvent-ils de la même fonction ?',answer:'L’enzyme relève de la fonction exocrine ; l’hormone relève de la fonction endocrine. Le même organe peut donc utiliser deux voies de sécrétion distinctes.'}},
 FMA7200:{flow:['Duodénum','Jéjunum','Iléon'],glossary:[['Absorption','Passage de substances à travers la paroi digestive vers le milieu intérieur.'],['Villosité','Relief de la muqueuse augmentant la surface disponible.']],caseStudy:{prompt:'Un aliment a été dégradé en petites molécules dans la lumière intestinale. Cela prouve-t-il qu’elles ont déjà été absorbées ?',answer:'Non. La digestion transforme les molécules ; l’absorption implique ensuite leur passage à travers la paroi. Un contenu digéré peut encore se trouver dans la lumière.'}},
 FMA7204:{flow:['Rein','Uretère','Vessie','Urètre'],glossary:[['Uretère','Conduit entre rein et vessie.'],['Urètre','Conduit d’évacuation depuis la vessie.']],caseStudy:{prompt:'La vessie se remplit. Quel organe a formé l’urine, quel conduit l’a transportée et quelle structure la stocke ?',answer:'Le rein forme l’urine, l’uretère la transporte et la vessie la stocke. L’urètre interviendra pour son évacuation vers l’extérieur.'}},
 FMA50801:{glossary:[['Intégration','Traitement et mise en relation d’informations.'],['Commande motrice','Signaux participant à l’activation et au contrôle des mouvements.']],caseStudy:{prompt:'Reconnaître un objet puis le saisir implique-t-il uniquement une commande motrice ?',answer:'Non. Il faut également traiter les informations sensorielles et les intégrer pour guider le mouvement. Plusieurs fonctions et réseaux coopèrent dans une action apparemment simple.'}},
 FMA24474:{glossary:[['Proximal','Du côté de l’attache du membre.'],['Distal','Plus éloigné de l’attache du membre.']],caseStudy:{prompt:'Sur le fémur isolé, vous repérez la tête et les condyles. Quelle extrémité participe à la hanche et laquelle au genou ?',answer:'La tête est proximale et s’articule avec l’acétabulum à la hanche. Les condyles sont distaux et participent au genou. La position des extrémités aide à orienter l’os.'}},
}
