import {ArrowRight,BookOpen,Bookmark,CheckCircle2,Search,ChevronRight,Layers3} from 'lucide-react'
import {courses,type Course} from './curriculum'
import {questions} from './questions'
import {subjects,groupCourses,courseSearchText,normalizeSearch} from './subjects'

export default function CourseLibrary(p:{subjectId:string;group:string;query:string;filter:string;saved:string[];completed:string[];browse:(subject:string,group?:string)=>void;search:(query:string)=>void;setFilter:(filter:string)=>void;open:(id:string)=>void}){
 const subject=subjects.find(s=>s.id===p.subjectId),own=subject?courses.filter(c=>c.category===subject.title):courses
 const groups=subject?groupCourses(own)[0]?.groups??[]:[]
 const needle=normalizeSearch(p.query)
 const filtered=own.filter(c=>(!p.group||c.tag===p.group)&&(p.filter==='all'||(p.filter==='saved'?p.saved.includes(c.id):!p.completed.includes(c.id)))&&(!needle||courseSearchText(c).includes(needle)))
 const directory=!subject&&!needle&&p.filter==='all'
 const countQuestions=(items:Course[])=>questions.filter(q=>items.some(c=>c.id===q.course)).length
 const searchHit=(c:Course)=>needle?c.sections.find(s=>normalizeSearch([s.title,s.text,...s.bullets??[]].join(' ')).includes(needle))?.title:null
 return <div className="catalog-layout">
  <aside className="subject-rail"><span className="study-eyebrow">LES MATIÈRES</span><nav aria-label="Choisir une matière"><button aria-current={!subject?'page':undefined} onClick={()=>p.browse('')}><Layers3 size={16}/><span>Vue des matières</span></button>{subjects.filter(s=>courses.some(c=>c.category===s.title)).map((s,i)=><button key={s.id} aria-current={subject?.id===s.id?'page':undefined} onClick={()=>p.browse(s.id)}><span className="subject-order">{String(i+1).padStart(2,'0')}</span><span>{s.title}</span><small>{courses.filter(c=>c.category===s.title).length}</small></button>)}</nav><p>Un classement par discipline.<br/>Des chapitres à suivre dans l’ordre, à votre rythme.</p></aside>
  <div className="catalog-main">
   <header className="catalog-heading"><div className="study-eyebrow">MYCORPUS · BIBLIOTHÈQUE DE PREMIÈRE ANNÉE</div><h1>{subject?subject.title:<>Chaque matière,<br/><em>à sa place.</em></>}</h1><p>{subject?subject.description:'Choisissez votre matière, puis une région ou un thème. Les cours et leurs exercices restent réunis dans un parcours clair.'}</p><div className="library-stats"><span>{own.length} chapitres</span><span>{countQuestions(own)} questions corrigées</span><span>{own.filter(c=>p.completed.includes(c.id)).length} terminés</span></div></header>
   <div className="catalog-tools"><label className="course-search"><Search size={18}/><input aria-label="Rechercher un cours" placeholder={subject?'Rechercher dans cette matière…':'Rechercher un cours, un os, une notion…'} value={p.query} onChange={e=>p.search(e.target.value)}/></label><select aria-label="Afficher les cours" value={p.filter} onChange={e=>p.setFilter(e.target.value)}><option value="all">Tous les cours</option><option value="saved">Enregistrés pour plus tard</option><option value="remaining">À terminer</option></select></div>
   {subject&&<nav className="module-tabs" aria-label="Régions et thèmes"><button aria-pressed={!p.group} onClick={()=>p.browse(subject.id)}>Tout en {subject.title.toLocaleLowerCase('fr')}</button>{groups.map(g=><button key={g.title} aria-pressed={p.group===g.title} onClick={()=>p.browse(subject.id,g.title)}>{g.title}<span>{g.courses.length}</span></button>)}</nav>}
   {directory?<div className="subject-directory" aria-label="Bibliothèque par matière">{subjects.map((s,i)=>{const items=courses.filter(c=>c.category===s.title);if(!items.length)return null;return <button className={'subject-card '+(s.id==='anatomie'?'anatomy-subject':'')} key={s.id} onClick={()=>p.browse(s.id)}><div className="subject-card-top"><span>{String(i+1).padStart(2,'0')}</span><BookOpen size={20} strokeWidth={1.3}/></div><h2>{s.title}</h2><p>{s.scope}</p><div className="subject-card-bottom"><span>{items.length} chapitres · {countQuestions(items)} questions</span><ArrowRight size={19}/></div></button>})}</div>:<>
    <div className="catalog-results" role="status">{filtered.length} chapitre{filtered.length>1?'s':''}{needle?' correspondant à « '+p.query+' »':''}{p.group?' · '+p.group:''}{(needle||p.filter!=='all')&&<button onClick={()=>{p.search('');p.setFilter('all')}}>Effacer les filtres</button>}</div>
    {groupCourses(filtered).map(({subject:s,groups:sections})=><section className="subject-results" key={s.id} aria-label={'Cours de '+s.title}>{!subject&&<h2 className="result-subject-title">{s.title}</h2>}{sections.map((g,i)=><section className="module-section" key={g.title} aria-label={g.title}><header><span>{String(i+1).padStart(2,'0')}</span><div><h2>{g.title}</h2><p>{g.courses.length} chapitres · {countQuestions(g.courses)} questions</p></div></header><div className="chapter-list">{g.courses.map((c,j)=><button className="course-tile chapter-row" key={c.id} onClick={()=>p.open(c.id)}><span className="chapter-number">{String(j+1).padStart(2,'0')}</span><span className="chapter-row-content"><span className="chapter-title">{c.title}</span><span className="chapter-objective">{searchHit(c)?'Dans ce cours : '+searchHit(c):c.objectives[0]}</span><span className="chapter-meta">{c.sections.length} sections · {c.minutes} min · {countQuestions([c])} questions</span></span><span className="chapter-state">{p.completed.includes(c.id)?<CheckCircle2 size={20} aria-label="Cours terminé"/>:p.saved.includes(c.id)?<Bookmark size={18} aria-label="Cours enregistré"/>:<ChevronRight size={20}/>}</span></button>)}</div></section>)}</section>)}
    {!filtered.length&&<div className="study-empty"><BookOpen size={30}/><p>Aucun chapitre ne correspond à ces filtres.</p>{subject&&needle&&<button className="study-secondary" onClick={()=>p.browse('')}>Chercher dans toutes les matières</button>}</div>}
   </>}
   <details className="curriculum-scope"><summary>Quels enseignements cette bibliothèque couvre-t-elle ?</summary><p>Les chapitres disponibles sont classés par discipline, sans numérotation d’UE propre à une faculté. Le programme et le niveau attendu varient entre PASS, L.AS et universités. Comparez ce sommaire avec vos supports universitaires : il ne constitue pas une certification de couverture intégrale.</p><p>L’anatomie est étudiée par région : plusieurs os ou muscles voisins peuvent être enseignés dans un même chapitre. Les schémas de cours expliquent les relations ; seuls les liens « Atlas 3D » ouvrent un modèle anatomique disponible.</p><a href="https://u-paris.fr/sante/pass-parcours-dacces-specifique-sante/" target="_blank" rel="noreferrer">Exemple de programme : Université Paris Cité ↗</a><a href="https://lyon-est.univ-lyon1.fr/formation/medecine/pass/pass" target="_blank" rel="noreferrer">Exemple de programme : Université Lyon 1 ↗</a></details>
  </div>
 </div>
}
