import {lessons} from '../learning'
export type Course = {id:string;title:string;category:string;tag:string;minutes:number;structure:string|null;objectives:string[];sections:{title:string;text:string;bullets?:string[]}[];trap:string;recall:string;answer:string;source:string}
const base='https://openstax.org/books/anatomy-and-physiology-2e/pages/'
export const foundations:Course[]=[
 {id:'orientation',title:'Se repérer dans le corps',category:'Anatomie',tag:'Fondamentaux',minutes:5,structure:'FMA24474',objectives:['Distinguer les trois plans','Employer les termes de position'],sections:[{title:'Un repère commun',text:'La droite et la gauche sont celles du sujet. La position anatomique de référence est debout, paumes vers l’avant.'},{title:'Trois plans de lecture',text:'Sagittal : droite / gauche. Frontal : avant / arrière. Transversal : haut / bas.'},{title:'Décrire une relation',text:'Médial : proche du plan médian. Latéral : plus éloigné. Proximal : proche de l’attache du membre. Distal : plus éloigné.'}],trap:'Le côté du sujet ne change pas lorsque vous tournez le modèle.',recall:'Le coude est-il proximal ou distal au poignet ?',answer:'Proximal : il est plus proche de l’attache du membre.',source:base+'1-6-anatomical-terminology'},
 {id:'homeostasis',title:'Comprendre l’homéostasie',category:'Physiologie',tag:'Fondamentaux',minutes:5,structure:null,objectives:['Identifier une boucle de régulation','Distinguer les rétrocontrôles'],sections:[{title:'Un équilibre dynamique',text:'L’homéostasie maintient des variables dans une plage compatible avec le fonctionnement de l’organisme.'},{title:'Une boucle fonctionnelle',text:'Un capteur détecte une variation ; un centre intégrateur organise la réponse ; un effecteur agit.'},{title:'Le signe du rétrocontrôle',text:'Un rétrocontrôle négatif limite l’écart initial. Un rétrocontrôle positif l’amplifie jusqu’à un événement d’arrêt.'}],trap:'« Négatif » décrit le sens de la réponse, pas sa nocivité.',recall:'La température interne reste-t-elle strictement constante ?',answer:'Non : elle varie dans une plage régulée.',source:base+'1-5-homeostasis'},
 {id:'membrane',title:'Les échanges membranaires',category:'Biologie cellulaire',tag:'Fondamentaux',minutes:6,structure:null,objectives:['Comparer transports passif et actif','Définir l’osmose'],sections:[{title:'Une barrière sélective',text:'La membrane associe une bicouche lipidique et des protéines. Toutes les substances ne la traversent pas de la même façon.'},{title:'Suivre un gradient',text:'La diffusion simple et la diffusion facilitée sont passives. La seconde utilise une protéine membranaire.'},{title:'Transporter contre le gradient',text:'Un transport actif utilise une source d’énergie. L’osmose correspond au mouvement d’eau à travers une membrane sélectivement perméable.'}],trap:'La présence d’une protéine ne suffit pas à définir un transport actif.',recall:'La diffusion facilitée consomme-t-elle directement de l’ATP ?',answer:'Non : elle suit le gradient sans hydrolyse directe d’ATP.',source:base+'3-1-the-cell-membrane'},
 {id:'tissues',title:'Les quatre familles de tissus',category:'Histologie',tag:'Fondamentaux',minutes:5,structure:null,objectives:['Nommer les familles tissulaires','Associer organisation et fonction'],sections:[{title:'Organiser le vivant',text:'Un tissu rassemble des cellules et leur environnement extracellulaire participant à une fonction.'},{title:'Quatre grandes familles',text:'Épithélial : revêtement et sécrétion. Conjonctif : soutien et liaison. Musculaire : contraction. Nerveux : communication.'},{title:'Du tissu à l’organe',text:'Un organe associe plusieurs tissus organisés ensemble.'}],trap:'Un organe ne correspond pas à une seule famille tissulaire.',recall:'Le cœur est-il constitué uniquement de tissu musculaire ?',answer:'Non : il associe notamment tissus musculaire, conjonctif et nerveux.',source:base+'4-1-types-of-tissues'},
]
export const courses:Course[]=[...foundations,...lessons.map(l=>({id:l.id,title:l.title,category:'Anatomie & physiologie',tag:l.system,minutes:7,structure:l.id,objectives:[`Localiser ${l.title.toLowerCase()}`,`Relier les structures à leur fonction`,`Restituer le mécanisme principal`],sections:[{title:'Localisation',text:l.location},{title:'Fonction',text:l.levels.student},{title:'Organisation anatomique',text:'Repérez les éléments suivants dans votre cours et dans l’atlas.',bullets:l.anatomy},{title:'Mécanisme',text:l.mechanism},{title:'Pour approfondir',text:l.levels.advanced}],trap:l.remember,recall:'Sans relire : expliquez la fonction de cet organe et citez deux de ses éléments anatomiques.',answer:l.levels.student+' '+l.anatomy.slice(0,2).join(' ; ')+'.',source:l.source}))]
export const categories=['Tous les cours',...new Set(courses.map(c=>c.category))]
