import type {Course} from './curriculum'
type Lesson={sections:[string,string][];references?:string[]}
export const deepCourses:Record<string,Lesson>={
 orientation:{references:['1-6-anatomical-terminology'],sections:[
 ['Construire une description anatomique complète','Une description doit identifier une structure, préciser le repère et nommer la relation observée. « Le coude est au-dessus » est ambigu si le bras est levé ; « le coude est proximal au poignet » décrit une relation stable sur le membre. Un même élément peut être proximal à une structure et distal à une autre : ce sont des relations, pas des étiquettes absolues.\n\nPour vous entraîner, prenez trois repères successifs : épaule, coude, poignet. Écrivez deux phrases sur le coude en changeant uniquement le point de comparaison. Faites ensuite tourner le modèle : les deux phrases doivent rester vraies. Cette méthode permet de vérifier que vous utilisez les repères du sujet.'],
 ['Passer du volume à la coupe','Un plan est une surface géométrique imaginaire ; une coupe est une représentation obtenue à son niveau. Un plan sagittal n’est médian que s’il passe par le milieu du corps. Plusieurs coupes parallèles peuvent appartenir à une même famille tout en montrant des structures différentes.\n\nPour lire une coupe, commencez donc par identifier sa famille, puis sa hauteur et son orientation. N’attribuez pas automatiquement la droite de l’image à la droite du sujet : les conventions de présentation doivent être connues. Dans l’atlas, le déplacement d’un plan de coupe permet de voir que l’apparition d’un organe dépend aussi du niveau choisi.'],
 ['Organiser la révision par relations','Apprendre une liste de noms sans relations donne peu de moyens de reconstruire une image oubliée. Associez chaque structure à deux voisines et à une région. Le sternum, par exemple, est antérieur au cœur ; la peau est superficielle aux muscles. Une relation de profondeur ne remplace pas une relation droite-gauche.\n\nVotre exercice de fin de chapitre consiste à décrire cinq structures avec des couples de termes différents : médial/latéral, proximal/distal, antérieur/postérieur, supérieur/inférieur et superficiel/profond. Vérifiez chaque phrase dans au moins deux vues. Notez les confusions plutôt que de simplement recopier la définition.'] ]},
 homeostasis:{references:['1-5-homeostasis'],sections:[
 ['Décomposer un mécanisme de régulation','Pour analyser une boucle, partez d’une variable mesurable, par exemple la température. Identifiez ensuite la perturbation, le dispositif qui la détecte, l’intégration de l’information et la réponse effectrice. Le capteur et l’effecteur ne sont pas interchangeables : détecter une variation ne suffit pas à la corriger.\n\nUne bonne explication suit une chaîne causale. Remplacez « le corps régule » par des étapes : variation détectée, signal transmis, réponse déclenchée, effet sur la variable. Si une étape manque, vous risquez de confondre le mécanisme avec son résultat. Dessiner des flèches aide à repérer cette omission.'],
 ['Distinguer stabilité et immobilité','Une variable régulée n’est pas figée. Les apports, les pertes et les besoins changent continuellement ; les réponses présentent aussi des délais. On peut donc observer des fluctuations sans conclure à l’absence de régulation. Il faut examiner leur amplitude, leur durée et le contexte.\n\nDans un exercice, une seule mesure ne permet pas de reconstituer toute une boucle. Comparez la situation avant et après la perturbation, puis demandez-vous si la réponse s’oppose à l’écart ou le renforce. Ne confondez pas le sens du rétrocontrôle avec la hausse ou la baisse d’un effecteur particulier.'],
 ['Expliquer le rétrocontrôle positif avec son arrêt','Un rétrocontrôle positif renforce le processus qui l’a déclenché. Une explication complète doit donc préciser ce qui limite ou termine la séquence. Sans cette information, le schéma paraît conduire à une amplification sans fin.\n\nPour comparer deux boucles, écrivez la même grille : variable de départ, réponse, conséquence de la réponse, mécanisme d’arrêt. Une boucle négative limite l’écart initial ; une boucle positive amplifie le processus jusqu’à une limite ou un événement. En révision, justifiez toujours votre classement par une phrase causale plutôt que par la mémorisation du mot « positif » ou « négatif ».'] ]},
 membrane:{references:['3-1-the-cell-membrane'],sections:[
 ['Concentration, charge et sens de déplacement','Pour une molécule non chargée, une différence de concentration contribue au sens de diffusion. Pour un ion, il faut également considérer la différence de potentiel électrique. L’ensemble constitue le gradient électrochimique. Un raisonnement fondé uniquement sur la concentration peut donc devenir insuffisant pour un ion.\n\nAvant de qualifier un transport, posez trois questions : quelle substance traverse, par quelle voie et dans quel sens par rapport à son gradient ? La présence d’un canal ou d’un transporteur décrit le chemin, pas à elle seule le caractère actif. Cette grille évite de classer toute protéine membranaire comme une pompe.'],
 ['Diffusion facilitée et transport actif','Une diffusion facilitée utilise une protéine et suit le gradient. Un transport actif peut utiliser directement une source d’énergie ou être couplé au déplacement d’une autre substance. Dans ce second cas, le gradient qui fournit l’énergie a lui-même dû être établi et entretenu.\n\nDans un schéma de cotransport, suivez séparément les deux solutés. Un soluté peut suivre son gradient pendant que l’autre est transporté contre le sien. Dire que l’ensemble « suit le gradient » sans préciser la substance masque le couplage. Pour réviser, annotez chaque flèche avec le nom du soluté et son sens.'],
 ['Osmose : raisonner sur la membrane réelle','Une différence de concentration ne suffit pas à prédire durablement le volume d’une cellule sans connaître la perméabilité de sa membrane aux solutés. Les solutés qui restent de part et d’autre contribuent à maintenir un déplacement d’eau. Un soluté qui traverse facilement peut réduire le déséquilibre.\n\nCommencez par dessiner les deux compartiments, puis indiquez ce qui peut traverser. Prévoir une sortie d’eau signifie prévoir une diminution du volume cellulaire, pas une disparition des solutés intracellulaires. En fin de raisonnement, vérifiez que vous n’avez pas confondu le mouvement de l’eau avec le transport du soluté.'] ]},
 tissues:{references:['4-2-epithelial-tissue','4-3-connective-tissue-supports-and-protects'],sections:[
 ['Reconnaître un épithélium par son organisation','Les cellules épithéliales sont étroitement associées et présentent une polarité : leur face apicale diffère de leur face basale. Elles reposent sur une membrane basale. Cette organisation permet de construire une barrière orientée, capable de protéger, transporter ou sécréter.\n\nPour décrire un épithélium, examinez le nombre de couches et la forme des cellules superficielles. Un revêtement simple favorise certains échanges, tandis qu’une organisation pluristratifiée contribue à la protection. Ne déduisez pas la fonction d’une seule caractéristique : la localisation et les spécialisations cellulaires complètent la description.'],
 ['Comprendre le rôle de la matrice extracellulaire','Dans les tissus conjonctifs, la matrice extracellulaire est déterminante. Elle associe une substance fondamentale et des fibres dont l’organisation influence les propriétés mécaniques. La proportion de cellules, de fibres et de liquide varie selon le tissu.\n\nComparer un tendon à un tissu adipeux montre pourquoi « conjonctif » ne signifie pas une structure uniforme. Les cellules et leur environnement sont adaptés à des fonctions différentes. En histologie, commencez par distinguer ce qui appartient aux cellules et ce qui est extracellulaire, puis décrivez l’organisation des fibres avant d’attribuer un nom.'],
 ['Relier les niveaux d’organisation','Une cellule musculaire possède une capacité contractile ; un tissu musculaire organise plusieurs cellules ; un organe réunit ce tissu à des éléments de soutien, de vascularisation et d’innervation. Passer d’un niveau à l’autre nécessite donc d’ajouter des relations, pas seulement d’augmenter la taille du dessin.\n\nPour analyser un organe, construisez un tableau fonctionnel : quel tissu assure le revêtement, lequel fournit la force, lequel transmet l’information et lequel soutient l’ensemble ? Toutes les cases n’ont pas la même importance selon l’organe. Cette démarche aide à comprendre pourquoi une fonction dominante n’exclut pas les autres familles tissulaires.'] ]},
 organelles:{sections:[
 ['Distinguer information, fabrication et destination','Le noyau contient l’information génétique, mais une protéine n’y est pas simplement stockée en attendant son export. L’expression d’un gène produit notamment un ARN messager, ensuite utilisé par les ribosomes. Il faut suivre deux objets différents : le message et le produit.\n\nPour une protéine sécrétée, le trajet fonctionnel relie la traduction associée au réticulum, le transport vésiculaire et le Golgi. Une protéine destinée au cytosol peut suivre une autre organisation. Évitez donc de transformer un exemple de sécrétion en règle absolue pour toutes les protéines cellulaires. Identifiez toujours la destination du produit étudié.'],
 ['Associer spécialisation et équipement cellulaire','Une cellule qui sécrète beaucoup de protéines et une cellule qui réalise un travail mécanique intense n’ont pas exactement les mêmes besoins. L’abondance relative des organites reflète ces activités. Une forte activité de sécrétion mobilise la voie réticulum-Golgi ; une consommation énergétique importante demande une régénération soutenue d’ATP.\n\nCette relation ne permet pas d’identifier infailliblement une cellule avec un seul organite. En exercice, combinez plusieurs indices : forme, localisation, compartiments et produit fabriqué. Une mitochondrie indique une participation au métabolisme énergétique ; elle ne suffit pas à définir à elle seule la fonction complète de la cellule.'],
 ['Localiser un défaut dans une chaîne','Supposez qu’une protéine soit détectée dans le réticulum mais absente à la surface. Vous savez que sa synthèse a commencé ; vous ne savez pas encore quelle étape ultérieure est altérée. Transport, maturation et fusion membranaire restent des possibilités à distinguer.\n\nUn raisonnement expérimental consiste à chercher le dernier compartiment où le produit est présent. Il faut aussi contrôler sa quantité totale : une absence peut provenir d’une faible production plutôt que d’un blocage. Pour chaque hypothèse, formulez une observation attendue. Cette méthode transforme la liste des organites en un véritable outil de compréhension du fonctionnement cellulaire.'] ]},
 'gene-expression':{sections:[
 ['Lire l’information dans le bon sens','La séquence d’un ARN messager doit être lue selon son orientation et son cadre de lecture. Regrouper les nucléotides par triplets à partir d’un autre point peut changer les codons obtenus. Une séquence isolée, sans préciser sa nature et son orientation, ne suffit donc pas à produire une interprétation fiable.\n\nDans un exercice, indiquez d’abord si vous disposez d’ADN ou d’ARN, puis si le brin fourni est matrice ou codant. Ne remplacez pas mécaniquement toutes les lettres sans établir cette distinction. La complémentarité intervient dans la transcription ; la lecture des codons intervient ensuite dans la traduction.'],
 ['Comprendre la maturation plutôt que mémoriser un trajet','Le pré-ARN messager et l’ARN mature ne sont pas strictement identiques. L’épissage modifie l’organisation du transcrit en raccordant des exons. Des combinaisons différentes peuvent élargir la diversité des produits sans multiplier le nombre de gènes dans les mêmes proportions.\n\nUn schéma utile comporte trois lignes alignées : région d’ADN, pré-ARN, ARN mature. Barrez les introns sur la ligne intermédiaire puis raccordez les segments conservés. Cela permet de distinguer une modification de l’ARN d’une suppression de l’ADN. Le gène n’est pas découpé à chaque épissage de son produit.'],
 ['Interpréter une variation sans conclure trop vite','Une variation de séquence peut conserver l’acide aminé, en changer un, introduire un signal d’arrêt ou modifier la lecture en aval selon sa nature et sa position. Ces conséquences ne sont pas équivalentes. Une conclusion sur la fonction demande encore de savoir quelle région du produit est concernée.\n\nPour répondre à un QCM, séparez trois niveaux : modification de la séquence, conséquence sur le produit et conséquence fonctionnelle. Une différence au premier niveau ne prouve pas automatiquement une perte totale de fonction au dernier. Indiquez ce qui est déductible de l’énoncé et ce qui nécessiterait des informations supplémentaires.'] ]},
 'cell-cycle':{sections:[
 ['Suivre deux compteurs différents','Le nombre de chromosomes et la quantité d’ADN décrivent deux grandeurs. Après la phase S, les chromosomes ont été copiés en chromatides sœurs mais leurs centromères ne se sont pas encore séparés. Vous pouvez donc augmenter la quantité d’ADN sans doubler immédiatement le nombre de chromosomes.\n\nConstruisez une ligne chronologique avec G1, S, G2 et mitose. Pour chaque étape, dessinez un chromosome et indiquez le nombre de chromatides. Les dessins révèlent mieux la confusion qu’une série de chiffres apprise seule. Précisez aussi si votre comptage concerne une cellule entière ou un futur noyau fille.'],
 ['Relier le fuseau à la distribution','La mitose doit répartir les copies entre les futurs noyaux. La condensation rend les chromosomes individualisables ; leur interaction avec le fuseau permet leur alignement puis leur séparation. Une simple duplication de l’ADN ne garantit donc pas une distribution correcte.\n\nLa succession prophase, métaphase, anaphase et télophase décrit des changements d’organisation. Pour retenir ces étapes, associez un verbe à chacune : préparer, aligner, séparer, reconstituer. Les limites entre certaines étapes peuvent être progressives ; l’essentiel est de comprendre quel problème de distribution est résolu à chaque moment.'],
 ['Comprendre pourquoi un cycle peut s’arrêter','Un point de contrôle relie l’état de la cellule à la poursuite du cycle. Si une étape préparatoire est incomplète, poursuivre la division risque de transmettre une anomalie. Les mécanismes de contrôle réduisent ce risque mais ne constituent pas une garantie absolue.\n\nIl faut distinguer une cellule temporairement arrêtée, une cellule sortie du cycle et une cellule morte. G0 n’est pas un synonyme de destruction. Dans une question expérimentale, une diminution du nombre de divisions peut avoir plusieurs causes : ralentissement, arrêt ou perte de cellules. Le seul nombre final ne permet pas de choisir sans observation complémentaire.'] ]},
 'neuronal-signal':{sections:[
 ['Du signal gradué au déclenchement','Les variations locales du potentiel ne sont pas toutes des potentiels d’action. Les signaux gradués peuvent s’additionner et influencer l’atteinte du seuil. Le potentiel d’action est ensuite régénéré le long de la membrane excitable.\n\nPour expliquer un neurone, séparez réception, intégration, déclenchement et transmission. Un signal synaptique faible peut modifier le potentiel sans déclencher de décharge. Plusieurs signaux rapprochés dans le temps ou issus de plusieurs contacts peuvent avoir un effet différent. Ainsi, une absence de potentiel d’action ne prouve pas une absence totale de réception d’information.'],
 ['Relier les canaux aux phases du signal','La dépolarisation et la repolarisation résultent de changements de perméabilité. Dans le modèle axonal classique, les canaux sodiques et potassiques ont des comportements temporels différents. L’ouverture, l’inactivation et la fermeture ne doivent pas être confondues.\n\nTracez le potentiel sur un axe vertical et le temps sur un axe horizontal. Sur la phase montante, annotez le courant entrant principal ; sur la phase descendante, le courant sortant. Le schéma ne représente pas le trajet spatial d’un ion le long de tout l’axone : il représente l’évolution du potentiel en un point au cours du temps.'],
 ['Passer d’une communication électrique à une réponse chimique','La synapse chimique transforme l’arrivée d’un signal présynaptique en libération de médiateur. Le calcium intervient dans cette libération ; les récepteurs de la cellule cible transforment ensuite la présence du médiateur en réponse. La chaîne comporte donc plusieurs endroits où un signal peut être modulé.\n\nUn même médiateur ne permet pas à lui seul de prévoir toute la réponse : le type de récepteur et l’état de la cellule comptent. Pour localiser un blocage, demandez si le potentiel arrive, si le médiateur est libéré et si la cible répond. Ces trois observations explorent des étapes différentes.'] ]},
 'muscle-contraction':{sections:[
 ['Lire le sarcomère en mouvement','Le sarcomère est délimité par deux stries Z. Son raccourcissement rapproche ces limites tandis que les filaments fins et épais changent de chevauchement. La longueur des filaments ne diminue pas dans le modèle de glissement.\n\nPour vérifier votre compréhension, dessinez deux sarcomères avec des filaments de même longueur mais deux chevauchements différents. Un dessin où les filaments raccourcissent décrit un autre mécanisme et doit être corrigé. Cette distinction est essentielle pour relier l’organisation microscopique au mouvement macroscopique d’un muscle.'],
 ['Relier excitation, calcium et force','Le potentiel d’action musculaire se propage dans les tubules T et déclenche la mobilisation du calcium stocké dans le réticulum sarcoplasmique. La troponine transmet le signal calcique à l’organisation des protéines régulatrices des filaments fins. L’actine devient accessible aux têtes de myosine.\n\nCette succession explique pourquoi une excitation électrique et une production de force ne sont pas exactement le même événement. Un défaut peut toucher le signal, le calcium ou les protéines contractiles. Pour expliquer une absence de contraction, il faut donc préciser quelle étape est testée plutôt que conclure automatiquement à un défaut nerveux.'],
 ['Analyser le rôle de l’énergie pendant tout le cycle','La fixation de l’ATP sur la myosine permet son détachement de l’actine. L’hydrolyse prépare la tête pour un nouveau cycle. Le calcium doit ensuite être repris par des pompes pour permettre le retour vers l’état de repos.\n\nAinsi, la relaxation n’est pas une simple disparition gratuite de la contraction. Elle exige elle aussi des mécanismes dépendant de l’énergie. Dans un exercice, distinguez ATP disponible, calcium disponible et accès aux sites de liaison. Une variation de l’un ne se résume pas automatiquement à une variation identique des deux autres.'] ]},
 blood:{sections:[
 ['Séparer la phase liquide et les éléments figurés','Le plasma constitue un milieu de transport contenant des protéines et des solutés. Les érythrocytes, leucocytes et plaquettes n’y jouent pas le même rôle. Les premiers sont spécialisés dans le transport gazeux, les seconds dans les défenses et les dernières dans les premières étapes de l’hémostase.\n\nLe vocabulaire est important : les plaquettes sont des fragments cellulaires, tandis que les globules rouges humains matures ont perdu leur noyau. Une absence de noyau n’implique pas que tous ces éléments soient identiques. Associez à chaque catégorie sa structure et sa fonction dominante.'],
 ['Comprendre une mesure relative','L’hématocrite est une fraction volumique. Son numérateur concerne les érythrocytes et son dénominateur le volume sanguin total. Une modification de l’un ou de l’autre peut donc changer le résultat.\n\nImaginez 40 unités de volume globulaire et 60 unités de plasma : la fraction est 40 sur 100. Si le plasma diminue à 40 unités sans modification des globules rouges, elle devient 40 sur 80. L’augmentation de la fraction n’exige pas de production nouvelle de globules rouges. Ces nombres sont un exemple de calcul, pas une interprétation d’un résultat biologique individuel.'],
 ['Relier production et durée de vie','Les éléments sanguins sont renouvelés. L’hématopoïèse dépend de cellules souches et de leur différenciation en lignées ; la moelle osseuse rouge est le principal site de production chez l’adulte. Les besoins et les signaux régulateurs influencent cette production.\n\nUn nombre circulant résulte à la fois de la production, de la durée de vie et des mouvements entre compartiments. Il ne mesure pas directement une seule de ces composantes. Dans une question de mécanisme, recherchez les indices qui permettent de distinguer un défaut de production d’une disparition accrue avant de conclure.'] ]},
 hemodynamics:{sections:[
 ['Choisir les unités avant de calculer','La relation Q = ΔP / R relie un débit, un gradient de pression et une résistance. Le débit s’exprime en volume par temps. La résistance doit utiliser des unités cohérentes avec celles du débit et de la pression choisis.\n\nSi ΔP vaut 80 unités et R vaut 20 unités compatibles, Q vaut 4 unités de débit. Si la pression passe à 120 alors que R reste identique, Q devient 6. Écrire « à résistance constante » fait partie du raisonnement. Sans cette condition, le changement du gradient ne suffit pas à prédire seul le nouveau débit.'],
 ['Comprendre une circulation en réseau','Les vaisseaux ne constituent pas un tube unique de calibre constant. Les branches distribuent le sang vers des territoires ; la résistance de ces chemins participe à la répartition du débit. Les artérioles peuvent modifier leur calibre et donc influencer cette distribution.\n\nUn débit total et un débit dans un organe sont deux niveaux de description. Une modification locale n’implique pas que tous les organes reçoivent la même variation de débit. Lorsque l’énoncé parle d’un réseau, identifiez le segment étudié et les conditions maintenues constantes avant d’appliquer une relation simple.'],
 ['Distinguer vitesse, débit et section','Le débit correspond à la quantité de volume qui franchit une section en une unité de temps ; la vitesse indique la distance parcourue. À débit identique, une section plus grande implique une vitesse moyenne plus faible. Pour des vaisseaux parallèles, c’est leur section totale qui compte.\n\nImaginez un même volume d’eau réparti dans plusieurs conduits au lieu d’un seul : le volume total transporté peut rester identique tandis que la vitesse locale change. Cette analogie aide à comprendre les grandeurs, mais elle ne remplace pas les propriétés biologiques des vaisseaux, notamment leur capacité à modifier leur calibre.'] ]},
 ventilation:{sections:[
 ['Suivre les pressions pendant un cycle','L’air se déplace selon une différence de pression. L’augmentation du volume thoracique pendant l’inspiration modifie la pression alvéolaire et permet une entrée d’air. Quand les pressions s’égalisent, le flux cesse momentanément, même si les poumons contiennent encore de l’air.\n\nLe volume et le débit ne sont donc pas synonymes. Un volume pulmonaire élevé ne prouve pas un débit entrant élevé à cet instant. Pour lire un graphique respiratoire, identifiez ce que représente chaque axe : volume, pression ou débit. Reliez ensuite les courbes par les différences de pression plutôt que par leur seule forme.'],
 ['Comparer des ventilations identiques en apparence','Avec un volume courant de 500 mL et 12 cycles/min, la ventilation minute est de 6 L/min. Si l’espace mort vaut 150 mL, la ventilation alvéolaire est de 4,2 L/min. Avec 250 mL et 24 cycles/min, la ventilation minute reste 6 L/min, mais la ventilation alvéolaire n’est plus que 2,4 L/min dans le même modèle.\n\nLa fréquence a augmenté, pourtant le volume utile par minute a diminué. C’est pourquoi une ventilation rapide et superficielle ne garantit pas une meilleure ventilation des alvéoles. Les valeurs sont choisies pour comparer les mécanismes, sans évaluer une personne.'],
 ['Relier air, barrière et circulation','L’efficacité des échanges dépend de l’arrivée de l’air, de la barrière de diffusion et du passage du sang. La surface, l’épaisseur et les gradients de pression partielle interviennent dans la diffusion. Ventilation et perfusion doivent être distinguées tout en étant étudiées ensemble.\n\nPour analyser une situation, commencez par demander quel élément change. Une alvéole ventilée mais peu perfusée ne correspond pas à une alvéole bien perfusée mais peu ventilée. Les deux situations limitent l’échange utile par des mécanismes différents. Un schéma à deux flèches, une pour l’air et une pour le sang, aide à conserver cette distinction.'] ]},
 'fluid-balance':{sections:[
 ['Cartographier les liquides de l’organisme','La membrane cellulaire sépare l’intracellulaire de l’extracellulaire. La paroi vasculaire sépare à son tour le plasma d’une partie du milieu interstitiel. Ces frontières ne possèdent pas exactement les mêmes propriétés de perméabilité.\n\nDire qu’un liquide est « à l’intérieur » ne suffit donc pas : il faut préciser à l’intérieur de quoi. Le plasma est dans les vaisseaux mais hors des cellules. Pour un exercice de déplacement d’eau, représentez les compartiments et nommez la barrière traversée. Cela empêche de confondre un échange plasma-interstitium avec un échange entre cellule et milieu extracellulaire.'],
 ['Relier tonicité et volume cellulaire','La tonicité décrit l’effet d’une solution sur le volume d’une cellule dans les conditions considérées. Un soluté non pénétrant contribue à un gradient osmotique durable ; un soluté pénétrant peut se répartir et modifier l’évolution du système.\n\nDans un milieu hypertonique à soluté non pénétrant, une sortie d’eau réduit le volume cellulaire. Cette description ne signifie pas que tous les ions de la cellule sortent avec l’eau. Le déplacement de solvant et le transport de solutés sont des phénomènes à distinguer. Vérifiez toujours que les hypothèses de perméabilité sont précisées dans votre réponse.'],
 ['Construire un bilan avec une durée','Un bilan hydrique compare les apports et les pertes pendant un intervalle. Si les entrées sont inférieures aux sorties, le bilan est négatif. Ce signe décrit une variation de stock sur la période ; il ne précise pas à lui seul toutes les concentrations du milieu intérieur.\n\nL’ADH contribue à conserver l’eau en augmentant la réabsorption rénale dans les segments sensibles. Pour comprendre son rôle, suivez le devenir de l’eau filtrée : celle qui est réabsorbée revient vers le milieu intérieur ; celle qui reste dans le liquide tubulaire peut être excrétée. Filtration et perte définitive ne sont donc pas équivalentes.'] ]},
 endocrine:{sections:[
 ['Du message circulant à la cellule cible','Une hormone peut atteindre de nombreux territoires par le sang, mais seules certaines cellules possèdent les moyens de reconnaître et de traiter son signal. Le récepteur constitue une étape de sélection. La quantité de récepteurs et les mécanismes intracellulaires participent à la sensibilité de la cible.\n\nUne concentration hormonale et un effet biologique ne sont donc pas deux mesures interchangeables. Si une cellule ne répond pas, plusieurs étapes sont possibles : disponibilité du message, récepteur ou transmission interne. Pour raisonner, dessinez la chaîne complète avant de localiser un défaut.'],
 ['Comparer deux mécanismes de réponse','Les hormones peptidiques agissent généralement via des récepteurs membranaires et des relais intracellulaires. Les hormones stéroïdes peuvent agir via des récepteurs intracellulaires et modifier l’expression de gènes. Ces catégories aident à comprendre les grandes voies, sans résumer toutes les particularités de chaque hormone.\n\nL’amplification signifie qu’un événement de reconnaissance peut mobiliser plusieurs étapes en aval. Elle ne signifie pas que la réponse est infinie. Des mécanismes d’arrêt et de régulation limitent le signal. Pour réviser, comparez localisation du récepteur, nature du relais et type de réponse plutôt que d’apprendre uniquement une liste d’hormones.'],
 ['Lire un axe hormonal dans les deux sens','Dans un axe, un signal en amont stimule une production en aval. Un rétrocontrôle négatif peut faire revenir l’information vers les étapes précédentes et freiner leur activité. La flèche de stimulation et la flèche de frein ne décrivent pas la même direction fonctionnelle.\n\nPour résoudre un exercice, commencez par une variation imposée et suivez chaque conséquence successivement. N’appliquez pas une règle « tout monte » à toute la chaîne : un élément en aval peut augmenter alors qu’un signal stimulant en amont diminue par rétrocontrôle. Précisez les hypothèses avant d’interpréter une combinaison de concentrations.'] ]},
 immunity:{sections:[
 ['Comprendre la coopération des défenses','Les barrières réduisent l’entrée d’agents extérieurs. Quand elles sont franchies, des mécanismes innés contribuent à reconnaître, recruter et éliminer. La réponse adaptative apporte une reconnaissance spécifique et une expansion des clones appropriés. Ces fonctions se complètent plutôt qu’elles ne se remplacent.\n\nUne présentation utile distingue le temps, la reconnaissance et les effecteurs. Une réponse rapide n’est pas automatiquement une réponse fondée sur une mémoire spécifique. Inversement, l’activation des lymphocytes ne supprime pas le rôle des mécanismes innés. Évitez de représenter les deux systèmes comme deux organes séparés sans échanges.'],
 ['Différenciation et fonction des lymphocytes','Un lymphocyte B activé peut se différencier en plasmocyte sécréteur d’anticorps. Les lymphocytes T comprennent notamment des cellules coordinatrices et des cellules cytotoxiques. Les produits et les modes d’action sont donc différents.\n\nLes anticorps sont des molécules, pas des cellules. Les plasmocytes sont les cellules qui les produisent. Cette distinction simple évite de nombreuses erreurs de QCM. Construisez une carte reliant origine cellulaire, différenciation, produit éventuel et fonction. Ne faites pas passer tous les lymphocytes par la case « sécrétion d’anticorps ».'],
 ['Interpréter la mémoire immunitaire','Après une première réponse, certaines cellules persistent. Lors d’une nouvelle rencontre, elles peuvent contribuer à une réponse plus rapide et plus efficace. Le temps nécessaire pour développer la réponse initiale ne décrit donc pas nécessairement la réponse secondaire.\n\nDans une expérience, comparez des expositions au même antigène et précisez le délai. Une réponse plus rapide peut être cohérente avec une mémoire, mais elle doit être interprétée dans le protocole proposé. Pour restituer le mécanisme, utilisez les mots reconnaissance, sélection, expansion, différenciation et persistance : chacun décrit une étape distincte.'] ]},
 metabolism:{sections:[
 ['Séparer possibilité et vitesse de réaction','Une enzyme accélère une réaction en diminuant la barrière d’activation. Elle ne crée pas de matière ni une réserve infinie d’énergie. Une réaction lente peut devenir plus rapide sans que sa nature chimique soit remplacée par une autre.\n\nDans une explication, distinguez le substrat, le produit et le catalyseur. Le substrat est transformé ; le catalyseur peut participer à plusieurs cycles. Évitez de dessiner l’enzyme comme un réactif définitivement incorporé dans chaque produit. Cette distinction sert ensuite à comprendre pourquoi une quantité limitée d’enzyme peut transformer une quantité plus importante de substrat au cours du temps.'],
 ['Comprendre la saturation et les conditions expérimentales','À faible disponibilité de substrat, ajouter du substrat peut augmenter l’activité observée. Lorsque les sites actifs sont fortement occupés, la capacité catalytique devient limitante. La relation entre quantité de substrat et vitesse n’est donc pas toujours proportionnelle.\n\nPour comparer deux expériences, contrôlez la quantité d’enzyme, la température, le pH et la durée de mesure. Une différence de produit accumulé peut provenir d’une durée différente plutôt que d’une activité intrinsèque différente. Écrivez les conditions maintenues constantes avant de conclure qu’une enzyme fonctionne mieux dans une situation.'],
 ['Relier les transformations à l’utilisation de l’ATP','Le catabolisme contribue à libérer et transférer de l’énergie ; l’anabolisme l’utilise pour construire. L’ATP est un intermédiaire permettant le couplage de certaines transformations avec un travail mécanique, un transport ou une synthèse.\n\nUne cellule ne vit pas sur un stock d’ATP qui ne serait jamais renouvelé. Les consommations et les régénérations se poursuivent. Pour expliquer un mécanisme, indiquez où l’ATP est utilisé et quel processus contribue à sa régénération. Ne confondez pas le rôle énergétique d’une molécule avec celui d’un signal hormonal, même si les deux influencent le métabolisme.'] ]},
 FMA7088:{references:['19-1-heart-anatomy','19-2-cardiac-muscle-and-electrical-activity'],sections:[
 ['Reconstruire les deux circulations','Le cœur droit reçoit le retour systémique et éjecte vers la circulation pulmonaire. Le cœur gauche reçoit le retour pulmonaire et éjecte vers la circulation systémique. Les deux côtés sont en série dans le trajet global du sang.\n\nPour mémoriser les cavités, suivez un parcours continu : veines caves, atrium droit, ventricule droit, circulation pulmonaire, atrium gauche, ventricule gauche et aorte. Ajoutez ensuite les valves entre les étapes. Cette méthode permet de retrouver un trajet oublié sans inverser une veine et une artère simplement parce que le sang est riche ou pauvre en oxygène.'],
 ['Relier valves, pressions et contraction','Les valves orientent le flux en s’ouvrant et se fermant selon les différences de pression. Elles ne constituent pas des pompes supplémentaires. Le myocarde fournit le travail mécanique, tandis que l’organisation des cavités et des valves permet de diriger le sang.\n\nImaginez une pression ventriculaire qui devient supérieure à celle de l’atrium correspondant : le gradient favorise la fermeture de la valve atrioventriculaire. Pour chaque valve, posez la même question : quelle pression est la plus élevée de part et d’autre ? Cette démarche est plus robuste que mémoriser des positions ouvertes ou fermées sans contexte temporel.'],
 ['Distinguer excitation électrique et débit sanguin','L’activité électrique organise l’activation du muscle cardiaque. Le système de conduction contribue à une succession coordonnée des contractions. Le signal électrique, la contraction et l’éjection sont liés mais représentent des événements différents.\n\nPour comprendre une figure de cours, identifiez si elle montre une activité électrique, une pression, un volume ou un débit. Une augmentation d’un tracé ne signifie pas automatiquement une augmentation de tous les autres. Dans l’atlas, utilisez le modèle pour les relations spatiales ; les animations illustratives ne permettent pas de mesurer un débit ou de déduire la fonction réelle d’un cœur.'] ]},
 FMA7309:{references:['22-1-organs-and-structures-of-the-respiratory-system','22-4-gas-exchange'],sections:[
 ['Suivre l’air des conduits aux échanges','Les voies respiratoires conduisent l’air vers des régions de plus en plus distales. Les bronches se ramifient en bronchioles ; les régions alvéolaires assurent les échanges avec les capillaires. Une structure qui conduit l’air n’est pas nécessairement un site majeur de diffusion gazeuse.\n\nLors d’une exploration, commencez par les voies principales puis observez les rapports des poumons dans le thorax. Le poumon droit comporte trois lobes et le gauche deux. Cette asymétrie ne signifie pas que l’un serait facultatif : chaque poumon participe à l’ensemble des échanges et possède sa propre organisation.'],
 ['Comprendre la barrière alvéolocapillaire','L’oxygène et le dioxyde de carbone traversent une barrière fine selon leurs gradients de pression partielle. Les alvéoles et les capillaires rapprochent les deux milieux, l’air et le sang, sans les mélanger directement.\n\nPour représenter un échange, dessinez deux compartiments séparés par une paroi. Ajoutez une flèche pour chaque gaz en précisant son gradient. Le sang ne coule pas normalement dans la lumière alvéolaire. Le modèle 3D montre les volumes et les rapports anatomiques ; il ne représente pas chaque alvéole ni la microstructure complète de cette barrière.'],
 ['Relier anatomie et fonction sans les confondre','La forme des poumons aide à comprendre leur place dans le thorax et leurs relations avec le cœur et le diaphragme. Leur fonctionnement exige aussi une ventilation, une perfusion et une barrière d’échange adaptées. Une anatomie visible ne suffit pas à mesurer ces fonctions.\n\nPour une révision efficace, écrivez une question spatiale et une question fonctionnelle : « Où est le lobe inférieur ? » puis « Pourquoi faut-il du sang au contact des alvéoles ? ». Répondez à la première dans l’atlas et à la seconde avec un schéma de flux. Cette alternance évite de réduire la physiologie à une liste de formes.'] ]},
 FMA7197:{references:['23-6-accessory-organs-in-digestion-the-liver-pancreas-and-gallbladder','24-1-overview-of-metabolic-reactions'],sections:[
 ['Situer le foie dans les échanges digestifs','Le foie reçoit des substances absorbées par le tube digestif et participe à leur traitement. Il réalise des transformations, des synthèses et des stockages selon les besoins. Il ne constitue donc pas seulement un lieu de passage.\n\nLa circulation porte relie notamment le territoire digestif au foie avant le retour vers la circulation générale. Pour réviser, distinguez l’arrivée d’un nutriment, son éventuelle transformation et sa redistribution. Une molécule présente après un repas peut avoir plusieurs devenirs ; le mot « digestion » ne résume pas toutes les opérations métaboliques hépatiques.'],
 ['Séparer production de bile et stockage','Le foie produit la bile, qui est acheminée par les voies biliaires. La vésicule biliaire assure un rôle de stockage et de concentration. La bile participe à la digestion des lipides, notamment en facilitant leur dispersion ; elle n’est pas une enzyme qui découpe elle-même toutes les molécules alimentaires.\n\nUn schéma à trois fonctions est utile : produire, stocker, conduire. Attribuez chaque fonction à une structure puis ajoutez l’intestin comme destination. Cette représentation prévient la confusion entre foie, vésicule et conduits biliaires.'],
 ['Comprendre la polyvalence d’un organe métabolique','Un organe peut contribuer à plusieurs fonctions sans que chacune soit assurée de manière isolée. Les voies hépatiques participent à la gestion des nutriments et de nombreuses substances. Leur activité dépend du contexte métabolique.\n\nPour apprendre ce chapitre, classez les fonctions en verbes : transformer, synthétiser, stocker et excréter certaines substances dans la bile. Associez un exemple documenté à chaque verbe, puis vérifiez que vous ne confondez pas un produit fabriqué avec un produit simplement transporté. Cette organisation donne une structure à une liste de fonctions souvent difficile à retenir telle quelle.'] ]},
 FMA7148:{references:['23-4-the-stomach','23-7-chemical-digestion-and-absorption-a-closer-look'],sections:[
 ['Organiser le trajet et les régions','Le contenu arrive de l’œsophage dans l’estomac puis rejoint le duodénum par la région pylorique. L’estomac reçoit, stocke temporairement et brasse le contenu. Ces fonctions mécaniques s’associent à des sécrétions digestives.\n\nRepérez l’entrée et la sortie avant d’apprendre les différentes régions. Un estomac isolé dans l’atlas perd une partie de ses rapports : remettez-le ensuite en contexte avec le foie et l’intestin. Cette double observation aide à distinguer sa forme propre de son orientation réelle dans l’abdomen.'],
 ['Relier acidité, enzymes et protection','Les sécrétions gastriques contribuent à la digestion, notamment des protéines. Le milieu acide participe à l’activation et au fonctionnement de certaines enzymes. La paroi doit parallèlement être protégée du contenu luminal par ses mécanismes de défense.\n\nIl faut donc séparer la fonction digestive du contenu et la protection de la muqueuse. « L’estomac contient de l’acide » ne suffit pas à expliquer son fonctionnement. Demandez quelles cellules sécrètent, où le produit agit et comment la surface est protégée. Le modèle de surface ne montre pas ces spécialisations cellulaires.'],
 ['Distinguer brassage, digestion et absorption','Le brassage fragmente et mélange ; la digestion chimique transforme les molécules ; l’absorption fait franchir une paroi. Ces opérations peuvent être associées dans un organe tout en gardant des mécanismes différents. L’intestin grêle demeure un site majeur de digestion et d’absorption.\n\nSuivez un aliment dans une chronologie simple. Sa présence dans le contenu gastrique ne signifie pas qu’il a déjà rejoint le sang. Lorsque vous répondez à un exercice, précisez le compartiment où se trouve la substance : lumière digestive, paroi ou milieu intérieur. Cette précision résout de nombreuses ambiguïtés.'] ]},
 FMA7198:{references:['17-9-the-endocrine-pancreas','23-6-accessory-organs-in-digestion-the-liver-pancreas-and-gallbladder'],sections:[
 ['Distinguer deux organisations fonctionnelles','Le pancréas associe des cellules exocrines et endocrines. Les sécrétions exocrines rejoignent le tube digestif par des conduits ; les hormones endocrines gagnent le milieu intérieur et la circulation. Il ne suffit donc pas de nommer l’organe pour savoir où agit un produit.\n\nDessinez le pancréas avec deux flèches de sortie : une vers le duodénum et une vers le sang. Placez les enzymes digestives sur la première, l’insuline et le glucagon sur la seconde. Ce schéma rend visible une distinction que le modèle anatomique externe ne peut pas montrer à l’échelle cellulaire.'],
 ['Relier les sécrétions digestives à leur destination','La fonction exocrine contribue à la digestion intestinale par des enzymes et une sécrétion bicarbonatée. Les conduits assurent le transport jusqu’au duodénum. Produire et acheminer sont deux étapes distinctes.\n\nDans une situation où un produit est fabriqué mais atteint mal sa destination, on ne peut pas conclure uniquement à une absence de synthèse. Il faut suivre la voie de sortie. Cette logique est commune à de nombreuses glandes exocrines : cellule sécrétrice, conduit, lumière où le produit agit. Elle aide à relier histologie et anatomie.'],
 ['Comprendre la régulation glycémique','Les cellules bêta des îlots produisent l’insuline et les cellules alpha le glucagon. Ces hormones participent à l’ajustement de la disponibilité du glucose. Leurs effets doivent être compris en relation avec les tissus cibles et le contexte nutritionnel.\n\nUne hausse de glycémie après un apport alimentaire peut stimuler la sécrétion d’insuline. La réponse contribue à l’utilisation et au stockage des nutriments. Pour restituer le mécanisme, distinguez le stimulus, la cellule sécrétrice, l’hormone et la réponse des cibles. L’hormone n’est pas elle-même une enzyme digestive déversée dans l’intestin.'] ]},
 FMA7200:{references:['23-5-the-small-and-large-intestines','23-7-chemical-digestion-and-absorption-a-closer-look'],sections:[
 ['Comprendre la succession des segments','L’intestin grêle comporte duodénum, jéjunum et iléon. Le duodénum reçoit le contenu gastrique ainsi que des sécrétions digestives accessoires. Le jéjunum et l’iléon poursuivent le traitement et l’absorption. Le gros intestin est une autre portion du tube digestif.\n\nLes anses peuvent rendre l’ordre difficile à lire dans un modèle 3D. Commencez par les connexions puis suivez la continuité, sans supposer que la structure la plus haute sur l’image est toujours la plus proximale. Le repliement spatial ne change pas l’ordre du trajet luminal.'],
 ['Associer la surface à l’absorption','L’organisation de la muqueuse augmente la surface disponible pour les échanges. Plis, villosités et microvillosités correspondent à des niveaux différents d’organisation. Une villosité n’est pas une cellule isolée ; une microvillosité est une spécialisation de surface cellulaire.\n\nCette hiérarchie relie l’anatomie à l’histologie. Un modèle d’organe ne résout pas ces détails microscopiques. Pour réviser, dessinez un zoom successif du segment intestinal vers la muqueuse puis vers une cellule. Étiquetez chaque niveau pour éviter de confondre un relief tissulaire et une structure subcellulaire.'],
 ['Suivre un nutriment jusqu’au milieu intérieur','La digestion chimique rend disponibles des molécules absorbables. Leur franchissement de l’épithélium utilise des mécanismes de transport adaptés. Le trajet ultérieur dépend de la nature des produits : tous les nutriments n’empruntent pas exactement la même voie.\n\nDans un exercice, identifiez la molécule et son compartiment initial avant de décrire son transport. Un produit présent dans la lumière n’est pas encore absorbé ; sa présence dans une cellule épithéliale ne décrit pas à elle seule son trajet final. Séparer ces étapes aide à comprendre pourquoi digestion, transport membranaire et circulation doivent être articulés.'] ]},
 FMA7204:{references:['25-3-gross-anatomy-of-the-kidney','25-5-physiology-of-urine-formation'],sections:[
 ['Du rein au néphron','Le rein présente une organisation corticale et médullaire. Ses unités fonctionnelles, les néphrons, associent une région de filtration et un système tubulaire. Les voies excrétrices collectent ensuite l’urine et l’acheminent vers l’uretère.\n\nL’échelle d’observation compte : la forme globale du rein aide à comprendre ses rapports, mais elle ne suffit pas à voir chaque néphron. Dessinez donc un deuxième schéma fonctionnel relié à l’organe. Ne placez pas la vessie parmi les régions où se réalise la filtration : elle intervient plus tard comme réservoir.'],
 ['Différencier filtration, réabsorption et sécrétion','La filtration fait passer une partie du plasma à travers la barrière glomérulaire vers le compartiment tubulaire. La réabsorption ramène des substances du tubule vers le sang. La sécrétion ajoute certaines substances du sang au liquide tubulaire.\n\nLa quantité excrétée dépend de ces opérations successives. Pour une substance donnée, on peut raisonner par bilan : quantité filtrée moins quantité réabsorbée plus quantité sécrétée. Être filtré ne signifie donc pas être intégralement perdu. Indiquez toujours la direction des flèches pour distinguer réabsorption et sécrétion.'],
 ['Résoudre un bilan tubulaire simple','Supposez que 100 unités d’une substance soient filtrées, que 80 soient réabsorbées et que 5 soient sécrétées. Le bilan donne 25 unités excrétées sur la période étudiée. Ce calcul illustre une conservation de quantité ; il n’est pas une valeur biologique de référence.\n\nVérifiez que toutes les quantités concernent la même substance et la même durée. Ne combinez pas une concentration avec une quantité sans tenir compte du volume. Cette vigilance sur les unités est aussi importante que la connaissance des noms des étapes. Elle permet de passer d’un schéma appris à une résolution argumentée.'] ]},
 FMA50801:{references:['13-2-the-central-nervous-system','16-2-the-mental-status-exam'],sections:[
 ['Se repérer dans l’encéphale','L’encéphale comprend notamment les hémisphères cérébraux, le diencéphale, le tronc cérébral et le cervelet. Le cortex correspond à une couche superficielle de substance grise ; d’autres régions grises se trouvent en profondeur. Les connexions en substance blanche relient différents territoires.\n\nLes hémisphères présentent des gyri séparés par des sillons. Les grands repères servent à situer les lobes frontal, pariétal, temporal et occipital. Dans la vue Cerveau, commencez par orienter l’ensemble avant de zoomer : un détail agrandi sans repère peut être plus difficile à identifier qu’une vue générale.'],
 ['Relier régions et fonctions avec prudence','Certaines régions sont particulièrement associées à des traitements moteurs, sensitifs, visuels ou auditifs. Cependant, une fonction complexe mobilise des réseaux distribués. La mémoire, le langage ou la réalisation d’un geste ne se résument pas à une seule petite zone fonctionnant isolément.\n\nPour comprendre une action comme lire puis saisir un objet, séparez réception sensorielle, interprétation, planification et commande. Reconstituez ensuite leurs relations. Cette démarche évite la mémorisation trompeuse d’un cerveau composé de cases indépendantes. Les associations fonctionnelles sont des repères pédagogiques, pas un moyen de poser un diagnostic avec l’atlas.'],
 ['Explorer le cerveau en trois dimensions','La vue dédiée isole l’ensemble anatomique disponible et rapproche la caméra. Utilisez les boutons de zoom pour observer les reliefs, puis le recadrage pour retrouver une vue lisible. Faire tourner l’ensemble aide à distinguer surface latérale, face médiale et régions inférieures.\n\nLe modèle est composé de maillages anatomiques : les limites entre portions peuvent rester visibles. Il ne représente pas chaque neurone ni toutes les connexions. Passez du modèle au cours pour relier ce qui est visible à ce qui relève d’une autre échelle. Un zoom augmente la taille d’affichage ; il ne crée pas une résolution anatomique absente du fichier.'] ]},
 FMA24474:{references:['8-4-bones-of-the-lower-limb','6-3-bone-structure'],sections:[
 ['Orienter le fémur avant de nommer ses reliefs','La tête du fémur est située du côté proximal et s’articule avec l’acétabulum. Le col relie cette tête au reste de l’os. Les trochanters constituent des reliefs proximaux ; les condyles se trouvent à l’extrémité distale, du côté du genou.\n\nPour orienter un os isolé, commencez par identifier les extrémités puis les surfaces articulaires. Évitez d’attribuer un côté à partir de la seule position dans la fenêtre. La caméra peut tourner librement : la droite anatomique appartient au sujet, pas à la droite de l’écran.'],
 ['Distinguer os compact et os spongieux','L’os est un tissu vivant organisé. L’os compact forme des régions denses ; l’os spongieux est organisé en travées. Leur répartition accompagne les propriétés mécaniques et les espaces internes de l’os. La moelle occupe certains de ces espaces.\n\nUn os long n’est donc pas un simple bâton plein. Pour associer structure et fonction, dessinez une vue globale puis une coupe schématique avec cortex et travées. Le maillage extérieur du fémur ne montre pas nécessairement cette organisation microscopique. Ne confondez pas une surface 3D avec une coupe histologique complète.'],
 ['Comprendre les rapports articulaires','Le fémur participe à deux grandes articulations : la hanche proximalement et le genou distalement. Une surface articulaire se comprend en relation avec la surface de l’os voisin et les structures qui stabilisent l’ensemble.\n\nAlternez donc isolation et contexte. En isolation, repérez tête et condyles ; en contexte, vérifiez leur relation avec le bassin et la région du genou. Une bonne réponse d’anatomie associe le nom, la localisation et le rapport. Cette méthode permet de reconnaître l’os dans une orientation inhabituelle sans dépendre d’une image unique apprise par cœur.'] ]},
}
export function expandCourse(course:Course):Course{
 const extra=deepCourses[course.id]
 if(!extra)return course
 const sources=[...(course.sources??[{label:'Source du cours',url:course.source}]),...(extra.references??[]).map(ref=>({label:'OpenStax · '+ref.split('-').slice(0,2).join('.'),url:'https://openstax.org/books/anatomy-and-physiology-2e/pages/'+ref}))]
 const sections=[...course.sections,...extra.sections.map(([title,text])=>({title,text}))]
 const words=sections.map(s=>s.text).join(' ').split(/\s+/).length
 return {...course,sections,minutes:Math.ceil(words/150)+8,sources:sources.filter((s,i)=>sources.findIndex(other=>other.url===s.url)===i)}
}
