import {breastSupport} from './breastCourse'
import {skeletalDiagrams} from './skeletalCourses'
import {systemDiagrams} from './systemCourses'
import {regionalSupport} from './regionalCourses'
import {reproductiveSupport} from './reproductiveCourses'
import {regionalSystemSupport} from './regionalSystems'
import {scienceSupport} from './scienceCourses'
export type Diagram={title:string;caption:string;kind:'flow'|'cycle'|'compare'|'branch';nodes:{label:string;detail:string}[];links?:{from:number;to:number;label?:string}[]}
type Node=[label:string,detail:string]
const diagram=(title:string,caption:string,kind:Diagram['kind'],nodes:Node[],links?:Diagram['links']):Diagram=>({title,caption,kind,nodes:nodes.map(([label,detail])=>({label,detail})),links})
export const diagrams:Record<string,Diagram>={
 ...skeletalDiagrams,...systemDiagrams,...regionalSupport.diagrams,...reproductiveSupport.diagrams,...scienceSupport.diagrams,...regionalSystemSupport.diagrams,...breastSupport.diagrams,
 orientation:diagram('Trois plans, trois séparations','Comparaison de plans anatomiques : ils décrivent une orientation, pas une position unique dans le corps.','compare',[
 ['Sagittal','Sépare droite et gauche. Un plan sagittal est médian seulement lorsqu’il passe par le milieu.'],['Frontal','Sépare une partie antérieure d’une partie postérieure. Il est aussi appelé coronal.'],['Transversal','Sépare une partie supérieure d’une partie inférieure. Déplacer sa hauteur change les structures traversées.']]),
 homeostasis:diagram('La boucle du rétrocontrôle négatif','La réponse finale tend à réduire la variation initiale. Les flèches représentent une relation fonctionnelle.','cycle',[
 ['Variation','Une grandeur régulée s’écarte de sa plage habituelle.'],['Capteur','Il détecte une variation ; il ne réalise pas nécessairement la correction.'],['Intégration','L’information est traitée pour organiser une réponse adaptée.'],['Effecteur','Une structure réalise la réponse : par exemple, une modification des pertes de chaleur.'],['Écart réduit','La réponse limite la perturbation. La variable continue de fluctuer dans le temps.']]),
 membrane:diagram('Trois façons de traverser une membrane','Comparez le gradient, la voie empruntée et l’énergie. Une protéine ne signifie pas automatiquement un transport actif.','compare',[
 ['Diffusion simple','La substance traverse selon son gradient sans transporteur spécifique. La perméabilité de la bicouche compte.'],['Diffusion facilitée','Un canal ou un transporteur permet un déplacement passif suivant le gradient électrochimique.'],['Transport actif','Le déplacement contre un gradient est couplé à une source d’énergie, directement ou indirectement.'],['Osmose','L’eau traverse selon les gradients osmotiques. La perméabilité aux solutés est nécessaire pour prévoir le volume cellulaire.']]),
 tissues:diagram('Un organe associe plusieurs tissus','Cette carte classe des fonctions dominantes ; elle ne décrit pas un organe composé de blocs indépendants.','branch',[
 ['Organe','Un ensemble organisé de tissus complémentaires : les fonctions coopèrent.'],['Épithélial','Revêtement, échanges et sécrétion. Les cellules sont polarisées et reposent sur une membrane basale.'],['Conjonctif','Soutien et liaison. La composition et l’organisation de la matrice extracellulaire sont déterminantes.'],['Musculaire','Production de force par contraction. L’organisation varie selon les types musculaires.'],['Nerveux','Réception, traitement et transmission d’informations. Il participe à la coordination.']]),
 organelles:diagram('Le parcours d’une protéine sécrétée','Schéma simplifié de la voie sécrétoire. Toutes les protéines cellulaires ne suivent pas ce trajet.','flow',[
 ['ARN messager','Il porte l’information utilisée pour fabriquer le polypeptide. Ce message est distinct du produit.'],['Réticulum rugueux','La traduction associée au réticulum engage le produit dans la voie sécrétoire.'],['Golgi','Il participe aux modifications, au tri et à l’orientation vers la destination.'],['Vésicule','Elle transporte le produit et le sépare du cytosol grâce à sa membrane.'],['Exocytose','La vésicule fusionne avec la membrane plasmique et libère son contenu à l’extérieur.']]),
 'gene-expression':diagram('Conserver l’information, produire un message','La transcription et la traduction sont deux opérations distinctes. La maturation intervient sur l’ARN.','flow',[
 ['ADN','Le gène fournit une information. La réplication copie l’ADN, tandis que la transcription produit un ARN.'],['Pré-ARN','Le transcrit initial contient des régions qui seront traitées pendant la maturation.'],['ARN mature','L’épissage retire les introns et raccorde les exons. L’ARN messager mature peut être traduit.'],['Ribosome','Il lit les codons ; les ARN de transfert apportent les acides aminés correspondants.'],['Polypeptide','Une chaîne d’acides aminés est produite. Sa maturation et son organisation contribuent à sa fonction.']]),
 'cell-cycle':diagram('Un cycle : préparer, copier, distribuer','Le retour en G1 représente un nouveau cycle possible. Certaines cellules quittent le cycle vers G0.','cycle',[
 ['G1','Croissance et activité cellulaire avant la réplication.'],['S','L’ADN est répliqué : les chromatides sœurs sont produites.'],['G2','La quantité d’ADN a augmenté, mais les chromatides sœurs ne sont pas encore séparées.'],['Mitose','Les chromosomes sont organisés, alignés puis les copies réparties vers les futurs noyaux.'],['Cytocinèse','Le cytoplasme est réparti. La division cellulaire ne se confond pas avec la réplication.']]),
 'neuronal-signal':diagram('Le relais d’une synapse chimique','Chaque flèche est une étape nécessaire au relais chimique ; la réponse cible n’est pas forcément excitatrice.','flow',[
 ['Signal électrique','Le potentiel d’action atteint la terminaison présynaptique.'],['Entrée de Ca²⁺','Les canaux calciques s’ouvrent ; le calcium entre dans la terminaison.'],['Libération','L’exocytose libère le neurotransmetteur dans la fente synaptique.'],['Récepteur','Le médiateur est reconnu par des récepteurs de la cellule postsynaptique.'],['Réponse cible','Le potentiel peut être modifié sans atteindre le seuil d’un nouveau potentiel d’action.']]),
 'muscle-contraction':diagram('Du signal à la force, puis au relâchement','Le calcium ouvre l’accès à l’actine ; l’ATP intervient dans les cycles de ponts et dans la recapture du calcium.','flow',[
 ['Excitation','Le signal se propage sur la membrane musculaire et dans les tubules T.'],['Calcium libéré','Le réticulum sarcoplasmique libère du calcium dans le cytosol.'],['Troponine','La fixation du calcium permet le déplacement de la tropomyosine.'],['Glissement','Les ponts actine–myosine modifient le chevauchement sans raccourcir les filaments.'],['Recapture','Des pompes utilisant l’ATP abaissent le calcium cytosolique et favorisent la relaxation.']]),
 blood:diagram('Le sang : un milieu et des éléments spécialisés','La taille des blocs n’indique pas une proportion. L’hématocrite concerne uniquement la fraction volumique des érythrocytes.','branch',[
 ['Sang','Le volume sanguin associe plasma et éléments figurés.'],['Plasma','Phase liquide contenant notamment eau, protéines et solutés.'],['Érythrocytes','Ils contiennent l’hémoglobine et participent au transport gazeux.'],['Leucocytes','Ils participent aux défenses immunitaires.'],['Plaquettes','Fragments cellulaires contribuant à l’hémostase.']]),
 hemodynamics:diagram('Q = ΔP / R : préciser ce qui reste constant','Trois situations dans le modèle simplifié. Les flèches ↑ et ↓ indiquent une variation, pas une valeur absolue.','compare',[
 ['ΔP ↑, R constant','Le débit Q augmente proportionnellement au gradient de pression dans ce modèle.'],['R ↑, ΔP constant','Le débit Q diminue. Si R double, Q est divisé par deux.'],['ΔP ×2 et R ×2','Le rapport reste identique : le débit Q ne change pas.'],['Section ↑, Q constant','La vitesse moyenne diminue. Débit et vitesse sont deux grandeurs différentes.']]),
 ventilation:diagram('Du volume inspiré au volume utile','Exemple pédagogique : 500 mL par cycle, espace mort 150 mL et fréquence 12/min.','flow',[
 ['Volume courant','500 mL entrent ou sortent pendant un cycle dans cet exemple.'],['Espace mort','150 mL par cycle ne participent pas aux échanges dans ce modèle simplifié.'],['Volume utile','500 − 150 = 350 mL par cycle atteignent le compartiment échangeur du modèle.'],['Fréquence','12 cycles chaque minute : il faut multiplier le volume utile par cette fréquence.'],['4,2 L/min','350 × 12 = 4 200 mL/min. La ventilation minute totale est 6 L/min, à distinguer de ce résultat.']]),
 'fluid-balance':diagram('Où se trouve l’eau ?','Les limites sont fonctionnelles. Le plasma est dans les vaisseaux mais reste hors des cellules.','branch',[
 ['Eau corporelle','Elle se répartit entre plusieurs compartiments séparés par des barrières.'],['Intracellulaire','À l’intérieur des cellules, séparé de l’extracellulaire par la membrane plasmique.'],['Extracellulaire','À l’extérieur des cellules : comprend notamment plasma et liquide interstitiel.'],['Plasma','Partie liquide intravasculaire du compartiment extracellulaire.'],['Interstitiel','Liquide extracellulaire situé entre les cellules des tissus.']], [{from:0,to:1},{from:0,to:2},{from:2,to:3},{from:2,to:4}]),
 endocrine:diagram('Une hormone ne suffit pas : il faut une cible','La chaîne aide à distinguer production, transport du message et réponse cellulaire.','flow',[
 ['Glande','Des cellules sécrètent une hormone dans le milieu intérieur.'],['Circulation','L’hormone peut être transportée vers plusieurs territoires.'],['Récepteur','La cible doit disposer d’un récepteur adapté et fonctionnel.'],['Relais cellulaire','Le signal est transmis par des mécanismes dépendant du type de récepteur.'],['Effet','La réponse biologique dépend du message mais aussi de la sensibilité et de l’état de la cellule.']]),
 immunity:diagram('Des défenses complémentaires','L’immunité innée et l’adaptative coopèrent ; cette carte présente des fonctions plutôt qu’un calendrier strict.','branch',[
 ['Défenses','Barrières, réponses innées et réponses adaptatives contribuent ensemble à la protection.'],['Barrières','Peau et muqueuses limitent l’entrée.'],['Réponse innée','Reconnaissance de motifs, inflammation et phagocytose participent à une réponse rapide.'],['Lymphocytes B','Ils peuvent se différencier en plasmocytes sécrétant des anticorps.'],['Lymphocytes T','Des populations coordonnent les réponses ; d’autres détruisent des cellules cibles.'],['Mémoire','Certaines cellules persistent après la réponse et participent aux réponses ultérieures.']]),
 metabolism:diagram('Transférer l’énergie vers le travail cellulaire','L’ATP est renouvelé : le schéma ne représente pas un stock infini.','flow',[
 ['Nutriments','Ils fournissent notamment de la matière et des sources d’énergie chimique.'],['Catabolisme','Des voies de dégradation permettent de transférer une partie de cette énergie.'],['ATP','Intermédiaire énergétique dont l’hydrolyse peut être couplée à un travail.'],['Travail cellulaire','Transport actif, mouvement et synthèses utilisent des couplages énergétiques.']]),
 FMA7088:diagram('Le trajet à travers les deux côtés du cœur','Les flèches suivent le sang. Le passage pulmonaire relie cœur droit et cœur gauche.','cycle',[
 ['Corps / veines caves','Le retour veineux systémique rejoint l’atrium droit.'],['Cœur droit','L’atrium droit puis le ventricule droit dirigent le sang vers les poumons.'],['Poumons','Le sang parcourt les capillaires pulmonaires où ont lieu les échanges gazeux.'],['Cœur gauche','Les veines pulmonaires rejoignent l’atrium gauche, puis le ventricule gauche éjecte le sang.'],['Aorte / corps','Le sang est distribué à la circulation systémique avant son retour veineux.']]),
 FMA7309:diagram('Trois conditions pour échanger les gaz','Ces fonctions sont complémentaires. Un modèle anatomique ne mesure pas leur efficacité.','compare',[
 ['Ventilation','Renouvelle l’air dans les régions alvéolaires. Les voies conductrices acheminent l’air.'],['Diffusion','Les gaz franchissent une barrière selon leurs gradients de pression partielle.'],['Perfusion','Le sang passe dans les capillaires et transporte les gaz échangés.']]),
 FMA7197:diagram('Bile : produire, stocker, acheminer','Schéma fonctionnel simplifié : le stockage dans la vésicule n’est pas un passage obligé pour toute la bile.','branch',[
 ['Foie','Produit la bile et assure de nombreuses fonctions métaboliques.'],['Voies biliaires','Conduisent la bile ; elles ne doivent pas être confondues avec le lieu de production.'],['Vésicule','Stocke et concentre la bile ; elle communique avec les voies biliaires.'],['Duodénum','La bile contribue à la digestion des lipides dans l’intestin.']], [{from:0,to:1},{from:1,to:2},{from:2,to:1},{from:1,to:3}]),
 FMA7148:diagram('Du bol alimentaire au contenu intestinal','Les étapes mécaniques et chimiques se complètent. L’absorption ne se confond pas avec le brassage.','flow',[
 ['Œsophage','Acheminement vers l’estomac.'],['Estomac','Stockage temporaire et mélange du contenu.'],['Sécrétions','Le milieu gastrique participe notamment à la digestion des protéines.'],['Pylore','Région de sortie du contenu vers le duodénum.'],['Intestin grêle','La digestion se poursuit, avec une part majeure de l’absorption.']]),
 FMA7198:diagram('Un pancréas, deux voies de sécrétion','Suivez la destination du produit pour distinguer endocrine et exocrine.','branch',[
 ['Pancréas','L’organe associe des fonctions digestives et hormonales.'],['Exocrine','Sécrétions digestives et bicarbonates.'],['Endocrine','Hormones, notamment insuline et glucagon.'],['Duodénum','Destination des sécrétions exocrines via des conduits.'],['Sang / cibles','Les hormones gagnent le milieu intérieur pour agir sur des cellules cibles.']], [{from:0,to:1},{from:0,to:2},{from:1,to:3},{from:2,to:4}]),
 FMA7200:diagram('Digérer n’est pas encore absorber','Une transformation chimique et un franchissement de paroi sont deux opérations différentes.','flow',[
 ['Lumière intestinale','Le contenu digestif est encore dans le tube digestif.'],['Digestion','Les molécules sont transformées en produits absorbables.'],['Épithélium','Les produits franchissent la barrière selon des mécanismes de transport adaptés.'],['Milieu intérieur','Les voies empruntées dépendent de la nature des nutriments absorbés.']]),
 FMA7204:diagram('Bilan rénal d’une substance','Quantité excrétée = filtrée − réabsorbée + sécrétée, sur une même période.','flow',[
 ['Filtration : +100','100 unités passent vers le compartiment tubulaire dans cet exemple.'],['Réabsorption : −80','80 unités retournent du tubule vers le sang.'],['Sécrétion : +5','5 unités sont ajoutées du sang vers le liquide tubulaire.'],['Excrétion : 25','100 − 80 + 5 = 25 unités quittent l’organisme. Ce sont des valeurs pédagogiques.']]),
 FMA50801:diagram('Reconnaître puis saisir : un travail en réseau','Schéma de fonctions coopérantes, pas une carte de localisation exclusive des fonctions.','flow',[
 ['Informations sensorielles','Des informations sur l’objet et le corps sont reçues.'],['Intégration','Les informations sont interprétées et mises en relation avec le contexte.'],['Planification','Une action adaptée est préparée.'],['Commande motrice','Des signaux contribuent à réaliser le mouvement.'],['Retour sensoriel','Les conséquences du mouvement apportent de nouvelles informations permettant des ajustements.']]),
 FMA24474:diagram('Orienter le fémur du proximal au distal','Le schéma associe reliefs et articulations ; les tailles ne sont pas à l’échelle.','flow',[
 ['Hanche','La tête fémorale s’articule avec l’acétabulum du bassin.'],['Tête et col','Région proximale. Le col relie la tête au reste de l’os.'],['Diaphyse','Partie allongée de l’os entre les extrémités.'],['Condyles','Reliefs articulaires de l’extrémité distale.'],['Genou','Le fémur participe à cette articulation par son extrémité distale.']]),
}
