import type {Course} from './curriculum'
import {courseSupport} from './courseSupport'

type Draft={id:string;title:string;category:string;tag:string;objectives:string[];sections:[string,string][];glossary:[string,string][];trap:string;recall:string;answer:string;caseStudy:{prompt:string;answer:string};sources:[string,string][]}
const open=(book:string,page:string)=>`https://openstax.org/books/${book}/pages/${page}`
const drafts:Draft[]=[
{id:'histo-methods',title:'Du prélèvement à la lame : lire une coupe histologique',category:'Histologie',tag:'Méthodes et lecture',objectives:['Reconstruire les étapes de préparation d’une coupe','Distinguer plan de coupe, artefact et structure','Décrire une lame avant de l’interpréter'],sections:[
['Prélever et préserver','Un prélèvement retire une petite partie d’un tissu qui doit être préservée aussi vite que possible. La fixation limite l’autolyse et stabilise les constituants, mais elle modifie aussi certaines propriétés. Une lame n’est donc jamais le tissu vivant intact. L’origine anatomique, l’orientation et le délai avant fixation influencent ce qui sera observable.'],
['Inclure, couper, colorer','Après déshydratation, le tissu peut être inclus dans un milieu qui permet de réaliser des coupes fines. Le microtome produit des sections dont l’épaisseur et l’orientation déterminent l’image. Les colorations créent un contraste : elles ne restituent pas les couleurs naturelles. Hématoxyline et éosine différencient notamment noyaux, cytoplasmes et matrice selon leurs affinités.'],
['Passer du faible au fort grossissement','Commencez par la forme générale, la lumière éventuelle, les limites et l’organisation en couches. Repérez ensuite les tissus dominants, puis les détails cellulaires. Aller directement au fort grossissement fait perdre l’architecture. Le grossissement agrandit l’image ; la résolution détermine la capacité à séparer deux points proches. Ces deux grandeurs ne sont pas synonymes.'],
['Comprendre le plan de coupe','Un tube coupé transversalement paraît circulaire ; le même tube coupé longitudinalement devient allongé. Une structure unique peut apparaître plusieurs fois si son trajet sinueux croise le plan. Il faut reconstruire un volume à partir d’une tranche. La forme observée dépend donc autant de l’objet que de la direction de la coupe.'],
['Reconnaître les artefacts','Plis, déchirures, rétractions, précipités et zones écrasées peuvent simuler une limite ou un espace. Un artefact varie souvent brutalement sans respecter l’organisation du tissu. Comparez plusieurs régions de la lame et recherchez une continuité. Décrire d’abord ce qui est visible protège contre l’interprétation trop rapide.']
],glossary:[['Fixation','Étape destinée à préserver l’organisation du prélèvement.'],['Inclusion','Enrobage du tissu dans un milieu permettant sa coupe.'],['Résolution','Capacité à distinguer deux points proches.'],['Artefact','Aspect créé ou accentué par la préparation plutôt que par l’organisation vivante.']],trap:'Une coloration histologique ne montre pas les couleurs naturelles du tissu vivant.',recall:'Pourquoi faut-il commencer une lame au faible grossissement ?',answer:'Pour reconnaître l’architecture, l’orientation et les grandes limites avant d’étudier les détails cellulaires.',caseStudy:{prompt:'Un conduit apparaît rond sur une zone et très allongé sur une autre. Faut-il conclure à deux organes ?',answer:'Pas nécessairement. Un même conduit sinueux peut être rencontré selon des plans différents. Il faut rechercher la continuité, les couches de paroi et répéter l’observation.'},sources:[['OpenStax · Types de tissus',open('anatomy-and-physiology-2e','4-1-types-of-tissues')],['OpenStax · Anatomie microscopique',open('anatomy-and-physiology-2e','1-2-structural-organization-of-the-human-body')]]},
{id:'histo-epithelial-specializations',title:'Épithéliums, polarité, jonctions et glandes',category:'Histologie',tag:'Tissus fondamentaux',objectives:['Classer un épithélium de revêtement','Relier polarité et fonction','Distinguer glandes exocrines et endocrines'],sections:[
['Une feuille cellulaire polarisée','Un épithélium associe des cellules serrées, une face apicale, un domaine latéral et une face basale reposant sur une lame basale. La polarité permet de répartir transporteurs, récepteurs et jonctions. Le tissu est généralement avasculaire et reçoit ses nutriments par diffusion depuis le conjonctif sous-jacent.'],
['Classer sans mélanger les critères','Simple ou stratifié décrit le nombre de couches. Pavimenteux, cubique ou prismatique décrit la forme des cellules superficielles. Un épithélium pseudostratifié paraît pluristratifié mais toutes ses cellules touchent la lame basale. Un urothélium change d’aspect avec la distension et ne se résume pas à un épithélium stratifié ordinaire.'],
['Spécialisations apicales','Les microvillosités augmentent la surface membranaire et favorisent les échanges. Les cils mobiles déplacent un fluide grâce à leur cytosquelette. Les stéréocils sont de longues expansions apparentées aux microvillosités. Ces structures ont des architectures et des fonctions différentes, même si elles forment toutes une bordure au pôle apical.'],
['Jonctions et barrière','Les jonctions serrées limitent le passage paracellulaire et entretiennent la polarité. Les jonctions d’ancrage transmettent des forces entre cellules ou vers la matrice. Les jonctions communicantes permettent le passage de petites molécules et d’ions. Une barrière épithéliale reste dynamique : ses propriétés dépendent du type de jonctions et des transports transcellulaires.'],
['Former une glande','Une glande exocrine conserve un conduit vers une surface ou une lumière. Une glande endocrine libère ses signaux vers le milieu intérieur sans conduit excréteur. La sécrétion mérocrine se fait par exocytose ; d’autres modes impliquent une partie apicale ou la cellule entière. Il faut séparer nature du produit, architecture et mode de libération.']
],glossary:[['Polarité','Répartition organisée des structures entre domaines apical, latéral et basal.'],['Lame basale','Matrice extracellulaire spécialisée sous l’épithélium.'],['Microvillosité','Expansion apicale augmentant la surface d’échange.'],['Glande exocrine','Glande libérant son produit vers une surface ou une lumière par un conduit.']],trap:'Pseudostratifié ne signifie pas réellement composé de plusieurs couches complètes.',recall:'Quels sont les deux critères principaux de classement d’un épithélium de revêtement ?',answer:'Le nombre de couches et la forme des cellules les plus superficielles.',caseStudy:{prompt:'Une image montre des noyaux à différentes hauteurs et des cils, mais toutes les cellules touchent la lame basale. Comment classer ?',answer:'Il s’agit d’un épithélium pseudostratifié cilié : l’impression de stratification vient de la hauteur variable des cellules et des noyaux.'},sources:[['OpenStax · Tissu épithélial',open('anatomy-and-physiology-2e','4-2-epithelial-tissue')]]},
{id:'histo-muscle',title:'Tissus musculaires : trois organisations, trois contrôles',category:'Histologie',tag:'Tissus spécialisés',objectives:['Comparer les trois tissus musculaires','Reconnaître striation et noyaux','Relier structure, contrôle et contraction'],sections:[
['Le muscle squelettique','Ses fibres sont longues, multinucléées et striées. Les noyaux se placent généralement en périphérie. Les myofibrilles alignent les sarcomères, ce qui explique la striation. Chaque fibre reçoit une commande motrice somatique ; les unités motrices organisent le recrutement. Le tissu conjonctif transmet les forces et accompagne vaisseaux et nerfs.'],
['Le muscle cardiaque','Les cardiomyocytes sont striés, ramifiés et le plus souvent dotés d’un noyau central. Les disques intercalaires réunissent des jonctions d’ancrage et communicantes, permettant cohésion mécanique et propagation de l’activité. L’automatisme de cellules spécialisées ne signifie pas que toutes les cellules se contractent sans coordination.'],
['Le muscle lisse','Les cellules fusiformes ne montrent pas de striation sarcomérique au microscope optique courant. Actine et myosine existent mais leur organisation diffère. Le contrôle est autonome, hormonal et local selon l’organe. Les contractions peuvent être lentes et soutenues, par exemple dans la paroi de nombreux viscères et vaisseaux.'],
['Comparer la régénération','Le muscle squelettique dispose de cellules satellites mais répare imparfaitement les pertes étendues. Le muscle cardiaque adulte régénère peu et une lésion importante peut être remplacée par une cicatrice. Le muscle lisse conserve souvent une capacité de prolifération supérieure. Ces tendances dépendent du contexte et ne garantissent pas une restauration fonctionnelle complète.'],
['Lire une coupe','En longitudinal, recherchez striation, ramification et position des noyaux. En transversal, la forme des profils et la localisation nucléaire aident, mais un plan oblique peut tromper. Associez toujours plusieurs critères. Une coupe de myocarde comporte aussi capillaires, matrice et cellules non musculaires.']
],glossary:[['Sarcomère','Unité contractile répétée du muscle strié.'],['Disque intercalaire','Complexe jonctionnel reliant des cardiomyocytes.'],['Cellule satellite','Cellule associée à la réparation des fibres musculaires squelettiques.'],['Muscle lisse','Tissu musculaire non strié à cellules fusiformes.']],trap:'Absence de striation visible ne signifie pas absence d’actine et de myosine.',recall:'Quel critère distingue immédiatement cardiomyocyte et fibre squelettique ?',answer:'Le cardiomyocyte est ramifié avec noyau central et disques intercalaires ; la fibre squelettique est longue, multinucléée et à noyaux périphériques.',caseStudy:{prompt:'Une lame montre des cellules striées ramifiées, à noyau central, reliées par des lignes transversales sombres. Quel tissu ?',answer:'Le muscle cardiaque ; les lignes correspondent aux disques intercalaires dans une préparation adaptée.'},sources:[['OpenStax · Tissu musculaire',open('anatomy-and-physiology-2e','4-4-muscle-tissue')],['OpenStax · Muscle squelettique',open('anatomy-and-physiology-2e','10-2-skeletal-muscle')]]},
{id:'histo-nervous',title:'Tissu nerveux : neurones, glie et organisation',category:'Histologie',tag:'Tissus spécialisés',objectives:['Identifier les compartiments d’un neurone','Comparer les principales cellules gliales','Relier myéline et conduction'],sections:[
['Le neurone comme cellule polarisée','Le soma contient le noyau et l’essentiel de la machinerie de synthèse. Les dendrites reçoivent de nombreux signaux ; l’axone conduit l’activité vers des cibles. Cette division est un modèle utile, mais la forme varie fortement. Une coupe peut montrer un soma sans permettre de suivre tout son prolongement.'],
['Glie du système central','Les astrocytes participent au milieu extracellulaire, aux échanges et aux interactions avec les synapses et vaisseaux. Les oligodendrocytes myélinisent des segments de plusieurs axones. La microglie appartient aux cellules immunitaires résidentes. Les épendymocytes bordent les cavités contenant le liquide cérébrospinal. Glie ne signifie pas simple colle passive.'],
['Glie périphérique','Une cellule de Schwann myélinise un segment d’un axone périphérique, tandis que les cellules satellites entourent les corps neuronaux dans les ganglions. La myéline périphérique et centrale assure une fonction isolante apparentée mais provient de cellules différentes. Cette distinction devient essentielle pour localiser certaines atteintes.'],
['Substances grise et blanche','La substance grise concentre notamment corps neuronaux, synapses et neuropile ; la substance blanche contient beaucoup d’axones, souvent myélinisés. Leur disposition varie entre moelle et encéphale. La couleur macroscopique ne permet pas de réduire chaque région à un seul type cellulaire.'],
['Nerf et ganglion','Un nerf périphérique rassemble des axones en fascicules entourés d’endonèvre, périnèvre et épinèvre. Un ganglion contient des corps neuronaux hors du système central. Un noyau nerveux désigne au contraire un regroupement de corps neuronaux dans le système central. Nerf, tractus, ganglion et noyau doivent être localisés avant d’être comparés.']
],glossary:[['Neuropile','Réseau de prolongements neuronaux et gliaux entre les corps cellulaires.'],['Oligodendrocyte','Cellule gliale qui forme la myéline dans le système nerveux central.'],['Cellule de Schwann','Cellule gliale associée aux axones périphériques.'],['Périnèvre','Enveloppe conjonctive entourant un fascicule nerveux.']],trap:'Un noyau nerveux n’est pas le noyau d’une cellule : c’est un groupe de neurones dans le système central.',recall:'Quelle cellule forme la myéline centrale et laquelle forme la myéline périphérique ?',answer:'L’oligodendrocyte dans le système central et la cellule de Schwann dans le système périphérique.',caseStudy:{prompt:'Une coupe montre des corps neuronaux entourés de cellules satellites, hors de la moelle. S’agit-il d’un nerf ?',answer:'La présence de corps neuronaux entourés de satellites évoque un ganglion périphérique. Un nerf montre surtout des faisceaux d’axones.'},sources:[['OpenStax · Tissu nerveux',open('anatomy-and-physiology-2e','4-5-nervous-tissue')],['OpenStax · Système nerveux',open('anatomy-and-physiology-2e','12-2-nervous-tissue')]]},
{id:'embryo-gametogenesis',title:'Gamétogenèse et fécondation : préparer un nouvel organisme',category:'Embryologie',tag:'Des gamètes au zygote',objectives:['Comparer ovogenèse et spermatogenèse','Expliquer la réduction méiotique','Ordonner les étapes de la fécondation'],sections:[
['La méiose change la ploïdie','Une cellule diploïde réalise une réplication de l’ADN puis deux divisions. La première sépare les chromosomes homologues et réduit le nombre de jeux chromosomiques ; la seconde sépare des chromatides. Le brassage provient notamment de la répartition des homologues et des recombinaisons. Réplication et division ne doivent pas être comptées comme le même événement.'],
['Spermatogenèse','Elle débute à partir des spermatogonies dans les tubes séminifères et produit, après méiose puis spermiogenèse, des cellules hautement spécialisées. Les cellules de Sertoli soutiennent ce processus ; les cellules de Leydig appartiennent au compartiment interstitiel. La spermiogenèse transforme la forme sans modifier à nouveau la ploïdie.'],
['Ovogenèse','Les ovocytes primaires sont engagés avant la naissance et restent bloqués en prophase I. À chaque cycle, un groupe folliculaire évolue mais un nombre plus restreint atteint l’ovulation. La méiose I produit une répartition cytoplasmique asymétrique. La méiose II n’est achevée qu’en relation avec la fécondation. Folliculogenèse et méiose sont coordonnées mais distinctes.'],
['Rencontre des gamètes','Les spermatozoïdes subissent une capacitation fonctionnelle dans les voies génitales. Les interactions avec les enveloppes ovocytaires permettent fusion et activation ovocytaire. Des mécanismes limitent ensuite la polyspermie. Dire que le premier spermatozoïde arrivé entre mécaniquement dans l’ovocyte masque les reconnaissances et transformations membranaires.'],
['Former puis segmenter le zygote','Après rapprochement du matériel parental, le zygote entre dans des divisions de segmentation. Le nombre de cellules augmente sans croissance proportionnelle du volume total initial. Morula puis blastocyste décrivent des organisations successives. Le blastocyste associe trophoblaste, masse cellulaire interne et cavité avant l’implantation.']
],glossary:[['Ploïdie','Nombre de jeux de chromosomes homologues dans une cellule.'],['Spermiogenèse','Différenciation d’une spermatide en spermatozoïde.'],['Capacitation','Modifications fonctionnelles rendant le spermatozoïde apte à féconder.'],['Blastocyste','Stade préimplantatoire avec trophoblaste, masse cellulaire interne et cavité.']],trap:'La spermiogenèse n’est pas une troisième division méiotique.',recall:'Pourquoi la méiose I est-elle dite réductionnelle ?',answer:'Parce qu’elle sépare les chromosomes homologues et fait passer de deux jeux chromosomiques à un jeu par cellule.',caseStudy:{prompt:'Un schéma place une réplication avant chacune des deux divisions méiotiques. Quelle correction ?',answer:'L’ADN est répliqué avant la méiose I, mais il n’existe pas de nouvelle phase S entre méiose I et méiose II.'},sources:[['OpenStax · Méiose',open('biology-2e','11-1-the-process-of-meiosis')],['OpenStax · Fécondation',open('anatomy-and-physiology-2e','28-1-fertilization')]]},
{id:'embryo-weeks-one-three',title:'Semaines 1 à 3 : implantation, gastrulation et axes',category:'Embryologie',tag:'Embryon précoce',objectives:['Reconstituer la chronologie des trois premières semaines','Distinguer embryon, trophoblaste et annexes','Relier gastrulation, feuillets et axes'],sections:[
['Semaine 1 : du zygote au blastocyste','Segmentation, compaction, morula puis blastocyste se succèdent pendant le transport vers la cavité utérine. La masse cellulaire interne contribue à l’embryon proprement dit ; le trophoblaste participe aux interfaces et annexes. L’éclosion de l’enveloppe pellucide précède l’implantation. Les jours sont des repères pédagogiques et présentent une variabilité biologique.'],
['Semaine 2 : implantation','Le trophoblaste se différencie et envahit l’endomètre de manière régulée. Le disque embryonnaire devient bilaminaire avec épiblaste et hypoblaste. Cavité amniotique, vésicule vitelline et cavité choriale doivent être distinguées. Le conceptus associe embryon et tissus extraembryonnaires ; une image de cette semaine ne doit pas être interprétée comme une coupe d’un adulte miniature.'],
['Semaine 3 : gastrulation','La ligne primitive organise des mouvements cellulaires à partir de l’épiblaste. L’endoderme définitif, le mésoderme intraembryonnaire puis l’ectoderme sont établis. La gastrulation transforme les relations entre cellules et pose des axes. Chaque futur organe associera souvent plusieurs origines tissulaires ; apprendre un feuillet unique pour un organe entier est insuffisant.'],
['Notochorde et neurulation initiale','La notochorde participe à l’organisation axiale et aux signaux adressés aux tissus voisins. L’ectoderme neural forme une plaque puis des replis. Le tube neural et les crêtes neurales ont des devenirs différents. La fermeture se déroule progressivement ; les neuropores ne sont pas des ouvertures définitives du système nerveux adulte.'],
['Mésoderme et segmentation','Le mésoderme para-axial se segmente en somites, le mésoderme intermédiaire contribue notamment aux appareils urogénitaux et le mésoderme latéral se divise autour du cœlome intraembryonnaire. Cette carte topographique aide à relier position précoce et dérivés, sans réduire tous les tissus conjonctifs à une origine unique sans nuance.']
],glossary:[['Épiblaste','Couche du disque bilaminaire à l’origine des trois feuillets embryonnaires.'],['Ligne primitive','Structure organisatrice de la gastrulation.'],['Notochorde','Structure mésodermique axiale jouant un rôle organisateur.'],['Somite','Bloc segmentaire de mésoderme para-axial.']],trap:'Le trophoblaste et l’embryon proprement dit ne désignent pas la même population cellulaire.',recall:'De quelle couche du disque bilaminaire dérivent les trois feuillets ?',answer:'De l’épiblaste, par les mouvements cellulaires de la gastrulation.',caseStudy:{prompt:'Une copie affirme que l’hypoblaste donne à lui seul l’endoderme définitif de l’embryon. Que corriger ?',answer:'L’endoderme définitif provient de cellules de l’épiblaste qui migrent pendant la gastrulation et remplacent l’hypoblaste dans le disque embryonnaire.'},sources:[['OpenStax · Développement embryonnaire',open('anatomy-and-physiology-2e','28-2-embryonic-development')]]},
{id:'embryo-placenta',title:'Placenta, annexes et circulation fœtale',category:'Embryologie',tag:'Annexes et échanges',objectives:['Distinguer composantes maternelles et fœtales','Expliquer les échanges sans mélanger les sangs','Suivre les dérivations de la circulation fœtale'],sections:[
['Deux composantes en interface','La partie fœtale dérive du chorion et la partie maternelle de l’endomètre transformé. Les villosités choriales augmentent la surface d’échange. Le sang fœtal circule dans des capillaires villositaires, tandis que le sang maternel baigne les espaces intervilleux. Les deux circulations sont proches mais normalement séparées par une interface.'],
['Échanger sélectivement','Gaz, nutriments, déchets, anticorps et certaines substances traversent selon des mécanismes différents. Le placenta possède aussi des fonctions endocrines et métaboliques. Une barrière n’est pas imperméable ; un échange n’est pas un mélange total. Les propriétés évoluent au cours de la grossesse avec l’organisation des villosités et des couches cellulaires.'],
['Amnios, chorion et cordon','L’amnios délimite la cavité amniotique. Le chorion participe à l’enveloppe externe et au placenta. Le cordon ombilical relie fœtus et placenta et contient normalement deux artères et une veine incluses dans un tissu conjonctif spécialisé. Le sens artère-veine se définit par rapport au cœur fœtal, pas par l’oxygénation.'],
['Dérivations fœtales','Le conduit veineux, le foramen ovale et le conduit artériel modifient les trajets par rapport à la circulation postnatale. Ils permettent de contourner en partie foie et poumons selon des chemins distincts. Les poumons reçoivent un débit mais n’assurent pas les échanges gazeux placentaires. Après la naissance, les changements de pressions et de débits favorisent les fermetures fonctionnelles.'],
['De la naissance aux vestiges','Le clampage du cordon supprime le circuit placentaire et la ventilation diminue les résistances pulmonaires. Les dérivations se ferment fonctionnellement puis peuvent évoluer vers des vestiges anatomiques. Fonctionnel ne signifie pas immédiatement anatomique. Les noms adultes doivent être reliés au trajet fœtal qu’ils remplacent.']
],glossary:[['Villosité choriale','Projection fœtale contenant des capillaires et baignant dans le sang maternel.'],['Veine ombilicale','Vaisseau ramenant vers le fœtus un sang relativement oxygéné depuis le placenta.'],['Foramen ovale','Communication fœtale orientant une partie du sang de l’atrium droit vers le gauche.'],['Conduit artériel','Dérivation fœtale entre tronc pulmonaire et aorte.']],trap:'La veine ombilicale est plus oxygénée que les artères ombilicales malgré son nom veineux.',recall:'Combien de vaisseaux contient normalement le cordon et lesquels ?',answer:'Deux artères ombilicales et une veine ombilicale.',caseStudy:{prompt:'Un étudiant dessine les sangs maternel et fœtal dans un conduit commun. Quelle représentation adopter ?',answer:'Dessiner deux compartiments séparés par l’interface placentaire, avec des échanges transplacentaires mais sans continuité vasculaire normale directe.'},sources:[['OpenStax · Développement fœtal',open('anatomy-and-physiology-2e','28-3-fetal-development')],['OpenStax · Adaptations maternelles',open('anatomy-and-physiology-2e','28-4-maternal-changes-during-pregnancy-labor-and-birth')]]},
{id:'embryo-organogenesis',title:'Organogenèse : plicature, bourgeons et périodes sensibles',category:'Embryologie',tag:'Organogenèse',objectives:['Expliquer la plicature embryonnaire','Relier bourgeons d’organes et tissus','Raisonner sur une période sensible'],sections:[
['Délimiter le corps','Les replis céphalique, caudal et latéraux transforment le disque en volume. Une partie de la vésicule vitelline est incorporée dans l’intestin primitif. La position du cœur, du diaphragme et des cavités évolue pendant ces mouvements. Une carte plane de feuillets ne suffit plus : il faut suivre déplacements et fermetures.'],
['Former l’intestin primitif','Intestins antérieur, moyen et postérieur sont des régions continues associées à des territoires vasculaires et à des dérivés. Le tube épithélial endodermique reçoit mésenchyme, muscle, vaisseaux et innervation d’autres origines. Les rotations et hernies physiologiques modifient les rapports digestifs. Le nom d’un segment précoce ne correspond pas à un seul organe adulte.'],
['Cœur et grands vaisseaux','Le tube cardiaque se forme, se courbe et se cloisonne progressivement. Les voies d’entrée et de sortie se réorganisent. Les crêtes neurales contribuent à certaines séparations du tractus de sortie. Le cloisonnement n’est pas une simple paroi ajoutée d’un coup ; des coussins, septa et alignements successifs coopèrent.'],
['Membres et face','Les bourgeons de membres associent ectoderme et mésenchyme avec des centres de signalisation. Les axes proximal-distal, antéro-postérieur et dorso-ventral sont coordonnés. La face résulte de la croissance et de la fusion de plusieurs proéminences. Une anomalie de fusion ne signifie pas absence complète de croissance des territoires concernés.'],
['Périodes sensibles','La vulnérabilité dépend du moment, de la dose, de la durée, du mécanisme et du contexte génétique. Une exposition très précoce n’a pas le même profil qu’une exposition pendant l’organogenèse ou la période fœtale. Une association temporelle ne suffit pas à établir une causalité. Le cours permet de raisonner, pas d’évaluer une exposition individuelle.']
],glossary:[['Plicature','Replis transformant le disque embryonnaire en organisation corporelle tridimensionnelle.'],['Intestin primitif','Tube embryonnaire incorporant une partie de la vésicule vitelline.'],['Coussin endocardique','Structure participant à plusieurs étapes du cloisonnement cardiaque.'],['Période sensible','Fenêtre durant laquelle un processus en cours est particulièrement vulnérable à une perturbation.']],trap:'Un organe complet ne dérive généralement pas d’un unique feuillet pris isolément.',recall:'Quel changement géométrique incorpore une partie de la vésicule vitelline ?',answer:'La plicature embryonnaire, notamment les replis céphalocaudal et latéraux.',caseStudy:{prompt:'Un tableau attribue le cœur entier au seul mésoderme sans distinguer ses composantes. Pourquoi est-ce insuffisant ?',answer:'Le muscle et de nombreux tissus sont mésodermiques, mais le développement cardiaque mobilise aussi des contributions et signaux de plusieurs populations, dont les crêtes neurales pour certaines régions.'},sources:[['OpenStax · Développement embryonnaire',open('anatomy-and-physiology-2e','28-2-embryonic-development')],['OpenStax · Organogenèse animale',open('biology-2e','43-6-embryonic-development')]]},
{id:'genetics-replication-repair',title:'Réplication, mutations et réparation de l’ADN',category:'Génétique',tag:'Stabilité du génome',objectives:['Décrire une réplication semi-conservative','Distinguer mutation et lésion','Associer grands mécanismes de réparation'],sections:[
['Copier de façon semi-conservative','Chaque molécule fille conserve un brin parental et synthétise un brin nouveau. Les ADN polymérases allongent dans le sens 5’ vers 3’ à partir d’une amorce. Les deux brins antiparallèles imposent une synthèse continue sur un brin et discontinue sur l’autre. Brin directeur et brin retardé dépendent de la fourche considérée.'],
['Ouvrir et coordonner la fourche','Hélicases, protéines liant l’ADN simple brin, primases, polymérases, pinces et topoisomérases coopèrent. Les fragments d’Okazaki sont maturés puis reliés. Une enzyme isolée ne réalise pas toute la réplication. Les origines multiples des chromosomes eucaryotes permettent de copier un grand génome pendant une phase S limitée.'],
['Télomères et extrémités','La réplication linéaire pose un problème à l’extrémité du brin retardé. Les télomères sont des séquences répétées associées à des protéines. La télomérase peut prolonger certaines extrémités dans des cellules particulières. Une forte activité télomérase ne rend pas une cellule immortelle à elle seule et son absence n’explique pas tout le vieillissement.'],
['Lésion ou mutation','Une lésion est une altération chimique ou structurale de l’ADN ; une mutation est une modification stable de séquence. Une lésion peut être réparée sans mutation ou être convertie en mutation lors de la réplication. Substitution, insertion, délétion et réarrangement ont des conséquences dépendant de leur position et du contexte.'],
['Réparer et contrôler','Relecture, réparation des mésappariements, excision de bases, excision de nucléotides et réparation des cassures couvrent des problèmes différents. Les points de contrôle peuvent ralentir le cycle ou favoriser l’apoptose. Réparer fidèlement une cassure et tolérer une lésion sont deux réponses distinctes.']
],glossary:[['Fourche de réplication','Zone où les brins parentaux sont séparés et copiés.'],['Fragment d’Okazaki','Segment synthétisé de manière discontinue sur le brin retardé.'],['Télomère','Structure répétée protégeant l’extrémité d’un chromosome linéaire.'],['Mutation','Modification stable de la séquence du matériel génétique.']],trap:'Une lésion de l’ADN n’est pas automatiquement une mutation permanente.',recall:'Dans quel sens une ADN polymérase allonge-t-elle un nouveau brin ?',answer:'Dans le sens 5’ vers 3’, en ajoutant un nucléotide à l’extrémité 3’.',caseStudy:{prompt:'Après exposition, une base est altérée puis restaurée avant la réplication. Parle-t-on obligatoirement de mutation ?',answer:'Non. Il y avait une lésion ; si la séquence est correctement restaurée avant sa fixation, aucune mutation stable ne subsiste.'},sources:[['OpenStax · Réplication',open('biology-2e','14-3-basics-of-dna-replication')],['OpenStax · Réparation',open('biology-2e','14-6-dna-repair')]]},
{id:'genetics-chromosomes',title:'Chromosomes, caryotype et anomalies génomiques',category:'Génétique',tag:'Cytogénétique',objectives:['Lire une formule chromosomique','Distinguer nombre et structure','Expliquer non-disjonction et mosaïcisme'],sections:[
['Compacter sans rendre l’ADN inactif','L’ADN s’associe aux histones dans la chromatine. Nucléosomes, boucles et territoires chromosomiques organisent le génome. Euchromatine et hétérochromatine décrivent des états relatifs d’accessibilité. La condensation mitotique facilite la séparation, mais la chromatine interphasique reste structurée et régulée.'],
['Chromosome et chromatide','Après phase S, un chromosome possède deux chromatides sœurs réunies jusqu’à leur séparation. Le nombre de chromosomes se compte par centromères, pas par quantité d’ADN. Une cellule peut donc conserver le même nombre chromosomique tout en ayant doublé son contenu en ADN. Cette distinction résout de nombreux exercices de cycle et méiose.'],
['Lire un caryotype','Le caryotype classe des chromosomes condensés selon taille, centromère et bandes. Il détecte surtout des variations de nombre et des remaniements suffisamment grands. Il ne séquence pas chaque gène et ne repère pas toutes les variants. La formule décrit l’observation et peut préciser mosaïque ou anomalie structurale.'],
['Non-disjonction','Une séparation incorrecte en méiose I touche les homologues ; en méiose II, elle touche les chromatides. Les gamètes produits n’ont pas les mêmes distributions. Après fécondation, une aneuploïdie peut en résulter. Une erreur mitotique postzygotique peut produire deux lignées et un mosaïcisme. Le moment de l’erreur influence donc la répartition cellulaire.'],
['Remaniements structuraux','Délétion, duplication, inversion et translocation décrivent des architectures différentes. Un remaniement équilibré peut préserver la quantité globale mais perturber un gène ou la méiose. Une variation de nombre de copies ne donne pas toujours un effet identique : taille, gènes concernés et contexte comptent.']
],glossary:[['Chromatide','Une des copies d’un chromosome répliqué avant leur séparation.'],['Aneuploïdie','Nombre anormal de chromosomes individuels sans changement de jeux complets.'],['Non-disjonction','Défaut de séparation de chromosomes homologues ou chromatides.'],['Mosaïcisme','Présence de plusieurs lignées génétiquement différentes issues d’un même zygote.']],trap:'Après réplication, le nombre de chromatides double mais le nombre de chromosomes comptés par centromère reste inchangé.',recall:'Quelle différence entre erreur méiotique et erreur mitotique postzygotique ?',answer:'La première peut toucher tous les descendants issus du gamète ; la seconde peut créer une mosaïque de lignées après la fécondation.',caseStudy:{prompt:'Une cellule humaine en G2 possède 92 chromatides. Combien de chromosomes compte-t-on ?',answer:'46 chromosomes, chacun formé de deux chromatides sœurs. Le comptage chromosomique se fait par centromères.'},sources:[['OpenStax · Chromosomes eucaryotes',open('biology-2e','10-2-the-cell-cycle')],['OpenStax · Erreurs de méiose',open('biology-2e','13-3-chromosomal-theory-of-inheritance')]]},
{id:'biochem-bioenergetics',title:'Bioénergétique : énergie libre, couplage et ATP',category:'Biochimie',tag:'Bioénergétique',objectives:['Interpréter le signe de ΔG','Expliquer un couplage énergétique','Distinguer équilibre et vitesse'],sections:[
['Énergie libre et sens spontané','À température et pression données, une variation de Gibbs négative indique qu’un processus est thermodynamiquement favorable dans les conditions considérées. Cela ne donne pas sa vitesse. Une réaction à ΔG positif peut avancer si elle est couplée à une réaction suffisamment favorable. Les concentrations réelles modifient ΔG par rapport à la valeur standard.'],
['Équilibre et quotient réactionnel','À l’équilibre, les flux microscopiques aller et retour se compensent et ΔG est nul. La constante d’équilibre décrit un rapport d’activités à l’équilibre ; le quotient réactionnel décrit l’état actuel. Une concentration stable dans une cellule n’implique pas l’équilibre : des apports et consommations peuvent maintenir un état stationnaire.'],
['Coupler par un mécanisme commun','Additionner deux équations favorables sur le papier ne suffit pas. Le couplage exige un intermédiaire ou une enzyme qui relie réellement les processus. Le transfert de phosphate depuis l’ATP peut modifier un substrat et rendre une étape possible. L’ATP n’est pas une énergie abstraite : sa transformation doit être reliée au mécanisme.'],
['Oxydoréduction et transporteurs','Oxydation et réduction se produisent ensemble. NAD⁺/NADH et FAD/FADH₂ transportent des électrons dans des contextes enzymatiques. Réduit ne signifie pas faible et oxydé ne signifie pas détruit. Le potentiel redox et les concentrations déterminent le sens favorable des transferts.'],
['Réguler les flux','Une voie dépend de la quantité et de l’activité des enzymes, des substrats, des produits, des compartiments et des signaux. Une étape très exergonique peut servir de point de contrôle, mais la régulation ne se résume pas à la réaction la plus lente. Flux, concentration et stock sont trois grandeurs différentes.']
],glossary:[['Énergie libre de Gibbs','Grandeur thermodynamique indiquant le caractère favorable d’un processus dans des conditions données.'],['Couplage','Lien mécanistique permettant à un processus favorable d’en entraîner un défavorable.'],['État stationnaire','État où une concentration reste stable malgré des flux entrants et sortants.'],['Oxydation','Perte d’électrons par une espèce au cours d’un transfert redox.']],trap:'Une réaction thermodynamiquement favorable peut être très lente sans catalyse.',recall:'Pourquoi l’hydrolyse de l’ATP ne suffit-elle pas à expliquer un travail cellulaire ?',answer:'Il faut préciser le couplage mécanistique qui transfère l’énergie ou un groupe chimique vers le processus concerné.',caseStudy:{prompt:'La concentration d’un intermédiaire reste stable pendant dix minutes. Peut-on conclure que sa voie est à l’arrêt ?',answer:'Non. Sa production et sa consommation peuvent être égales : la concentration est stationnaire alors que le flux est important.'},sources:[['OpenStax · Énergie et métabolisme',open('biology-2e','6-3-the-laws-of-thermodynamics')],['OpenStax · ATP',open('biology-2e','6-4-atp-adenosine-triphosphate')]]},
{id:'biochem-carbohydrate',title:'Glycolyse, pyruvate et cycle de Krebs',category:'Biochimie',tag:'Métabolisme des glucides',objectives:['Établir le bilan de la glycolyse','Suivre les carbones du glucose','Relier pyruvate, lactate et acétyl-CoA'],sections:[
['Investir puis récupérer','La glycolyse cytosolique transforme un glucose en deux pyruvates. Une phase d’investissement consomme de l’ATP, puis une phase de rendement en produit avec du NADH. Le bilan net est différent du nombre total d’ATP formés. Chaque réaction après le clivage se produit deux fois par glucose.'],
['Trois étapes de contrôle','Hexokinase ou glucokinase, phosphofructokinase-1 et pyruvate kinase catalysent des étapes fortement déplacées dans les conditions cellulaires. La PFK-1 intègre notamment l’état énergétique. Réguler une enzyme ne signifie pas arrêter toute la voie ; les effets dépendent des tissus et des apports.'],
['Le devenir du pyruvate','En présence d’une capacité oxydative suffisante, le pyruvate peut entrer dans la mitochondrie et devenir acétyl-CoA. La lactate déshydrogénase régénère du NAD⁺ en couplant pyruvate et NADH. Produire du lactate n’exige pas l’absence totale d’oxygène et le lactate peut être réutilisé.'],
['Cycle de l’acide citrique','L’acétyl-CoA apporte deux carbones qui se condensent avec l’oxaloacétate. Le cycle libère du CO₂ et produit des coenzymes réduits ainsi qu’un équivalent énergétique. Les carbones libérés au premier tour ne sont pas nécessairement ceux de l’acétyl entrant. Les intermédiaires servent aussi à des biosynthèses.'],
['Régénérer et anaplérotiser','Le cycle dépend de la régénération de l’oxaloacétate. Des réactions anaplérotiques restaurent des intermédiaires retirés. Dire que l’oxaloacétate est catalytique décrit sa régénération, pas son inutilité. Le flux mitochondrial dépend aussi de la chaîne respiratoire qui réoxyde NADH et FADH₂.']
],glossary:[['Glycolyse','Voie cytosolique transformant le glucose en pyruvate.'],['Phosphofructokinase-1','Enzyme régulée catalysant une étape engagée de la glycolyse.'],['Acétyl-CoA','Intermédiaire transportant un groupe acétyle vers plusieurs voies.'],['Anaplérose','Réaction qui restaure un intermédiaire d’un cycle métabolique.']],trap:'Le lactate n’est pas un déchet sans devenir et sa production n’indique pas forcément zéro oxygène.',recall:'Quel est le bilan net direct en ATP de la glycolyse par glucose ?',answer:'Deux ATP nets, avec deux NADH et deux pyruvates dans le bilan classique.',caseStudy:{prompt:'Une cellule retire du citrate pour une biosynthèse. Que doit-elle préserver pour maintenir le cycle ?',answer:'Elle doit compenser la perte d’intermédiaires par des réactions anaplérotiques, notamment pour maintenir l’oxaloacétate disponible.'},sources:[['OpenStax · Glycolyse',open('biology-2e','7-2-glycolysis')],['OpenStax · Oxydation du pyruvate et cycle',open('biology-2e','7-3-oxidation-of-pyruvate-and-the-citric-acid-cycle')]]},
{id:'biochem-oxidative-phosphorylation',title:'Chaîne respiratoire et phosphorylation oxydative',category:'Biochimie',tag:'Métabolisme des glucides',objectives:['Suivre les électrons vers l’oxygène','Expliquer le gradient protonique','Relier découplage et rendement'],sections:[
['Donner les électrons à la chaîne','Le NADH cède des électrons au complexe I et le FADH₂ les introduit par d’autres voies, notamment le complexe II. Ubiquinone et cytochrome c sont des transporteurs mobiles. Les électrons progressent vers des accepteurs de potentiel croissant jusqu’à l’oxygène, réduit en eau. L’oxygène ne fournit pas directement l’ATP.'],
['Pomper des protons','Les complexes I, III et IV couplent des transferts d’électrons à une expulsion de protons hors de la matrice. La membrane interne limite leur retour libre. Le gradient possède une composante chimique et électrique. Le nombre de protons pompés dépend du point d’entrée des électrons, ce qui contribue aux rendements différents.'],
['Faire tourner l’ATP synthase','Le retour des protons selon leur force proton-motrice entraîne des changements de l’ATP synthase et permet la phosphorylation de l’ADP. Chimiosmose désigne ce couplage par un gradient transmembranaire. L’enzyme ne pompe pas spontanément des protons tout en synthétisant de l’ATP dans le sens physiologique habituel.'],
['Navettes et rendements','Le NADH cytosolique ne traverse pas directement la membrane interne. Des navettes transfèrent ses équivalents réducteurs avec des bilans différents. Le nombre d’ATP par glucose n’est donc pas une constante universelle entière ; il varie avec navettes, fuites, transports et besoins cellulaires.'],
['Inhiber ou découpler','Un inhibiteur bloque une étape et peut réduire consommation d’oxygène et ATP selon son site. Un découplant augmente la fuite protonique : l’oxydation peut continuer tandis que la synthèse d’ATP devient moins efficace et que de l’énergie se dissipe en chaleur. Blocage de chaîne et découplage ont donc des profils opposés.']
],glossary:[['Chaîne respiratoire','Suite de transporteurs d’électrons de la membrane mitochondriale interne.'],['Force proton-motrice','Énergie liée aux gradients chimique et électrique de protons.'],['ATP synthase','Complexe utilisant le retour des protons pour synthétiser l’ATP.'],['Découplant','Agent qui dissipe le gradient et sépare en partie oxydation et synthèse d’ATP.']],trap:'L’oxygène est l’accepteur final d’électrons ; il ne phosphate pas directement l’ADP.',recall:'Quels complexes de la chaîne pompent directement des protons dans le modèle classique ?',answer:'Les complexes I, III et IV.',caseStudy:{prompt:'Après ajout d’un découplant, la consommation d’oxygène augmente mais l’ATP diminue. Est-ce contradictoire ?',answer:'Non. Le gradient fuit : la chaîne accélère pour tenter de le restaurer, mais l’ATP synthase récupère moins efficacement cette énergie.'},sources:[['OpenStax · Phosphorylation oxydative',open('biology-2e','7-4-oxidative-phosphorylation')]]},
{id:'phys-cardiac-cycle',title:'Cycle cardiaque, débits et régulation',category:'Physiologie',tag:'Cardiovasculaire',objectives:['Relier pressions, valves et volumes','Calculer débit et fraction d’éjection','Expliquer les régulations du débit'],sections:[
['Pressions et valves','Une valve s’ouvre lorsque le gradient de pression est favorable et se ferme lorsque ce gradient s’inverse. Pendant une contraction isovolumétrique, toutes les valves sont fermées et la pression monte sans changement de volume. L’éjection commence lorsque la pression ventriculaire dépasse celle de l’artère correspondante. Les valves ne tirent pas activement le sang.'],
['Volumes et débit','Le volume d’éjection systolique est la différence entre volume télédiastolique et télésystolique. La fraction d’éjection rapporte ce volume éjecté au volume télédiastolique. Le débit cardiaque est fréquence multipliée par volume d’éjection. Deux personnes peuvent avoir le même débit avec des combinaisons différentes.'],
['Précharge, postcharge, contractilité','La précharge se relie à l’étirement avant contraction, la postcharge à la charge contre laquelle le ventricule éjecte et la contractilité à la capacité intrinsèque de produire une force à conditions comparables. La loi de Frank-Starling relie dans certaines limites remplissage et volume éjecté ; elle ne signifie pas que toute dilatation améliore la pompe.'],
['Régulation intégrée','Le système autonome module fréquence, conduction et contractilité. Le retour veineux influence le remplissage. Baroréflexe, tonus vasculaire et hormones coordonnent cœur et vaisseaux. Une variation de pression artérielle ne permet pas à elle seule d’identifier le mécanisme : débit et résistances doivent être séparés.']
],glossary:[['Volume d’éjection systolique','Volume éjecté par un ventricule à chaque battement.'],['Débit cardiaque','Volume éjecté par minute, produit de la fréquence et du volume d’éjection.'],['Précharge','Condition d’étirement du ventricule avant la contraction.'],['Postcharge','Charge mécanique contre laquelle le ventricule doit éjecter.']],trap:'Fraction d’éjection et volume d’éjection ne sont pas la même grandeur.',recall:'Comment calculer le débit cardiaque ?',answer:'Fréquence cardiaque multipliée par volume d’éjection systolique.',caseStudy:{prompt:'Fréquence 75/min et volume d’éjection 70 mL : quel débit ?',answer:'75 × 70 = 5 250 mL/min, soit 5,25 L/min dans cet exemple.'},sources:[['OpenStax · Cycle cardiaque',open('anatomy-and-physiology-2e','19-3-cardiac-cycle')],['OpenStax · Débit cardiaque',open('anatomy-and-physiology-2e','19-4-cardiac-physiology')]]},
{id:'phys-gas-exchange',title:'Ventilation, diffusion et transport des gaz',category:'Physiologie',tag:'Respiration',objectives:['Distinguer ventilation alvéolaire et minute','Appliquer les gradients de pression partielle','Expliquer le transport de O₂ et CO₂'],sections:[
['Ventiler les alvéoles','La ventilation minute est volume courant multiplié par fréquence. La ventilation alvéolaire retranche l’espace mort de chaque cycle avant de multiplier par la fréquence. Une respiration rapide et superficielle peut donc maintenir la ventilation minute tout en diminuant la ventilation alvéolaire. Les volumes mobilisables et non mobilisables doivent être distingués.'],
['Diffuser à travers la barrière','Un gaz diffuse selon son gradient de pression partielle. Surface, épaisseur, coefficient de diffusion et temps de contact influencent le transfert. La ventilation apporte l’air et la perfusion apporte le sang ; leur adéquation régionale conditionne les échanges. Une alvéole ventilée mais non perfusée n’assure pas un échange efficace.'],
['Transporter l’oxygène','L’oxygène est principalement lié à l’hémoglobine, avec une petite fraction dissoute. La saturation dépend de la pression partielle et de l’affinité. pH, CO₂, température et 2,3-BPG déplacent la courbe. Une saturation élevée ne garantit pas un contenu normal si la quantité d’hémoglobine est faible.'],
['Transporter le dioxyde de carbone','Le CO₂ circule dissous, lié à des protéines et surtout sous forme de bicarbonate. Dans les globules rouges, l’anhydrase carbonique accélère l’interconversion. Le déplacement des chlorures contribue à l’équilibre électrique. Ventilation, production métabolique et tampons déterminent ensemble le pH ; le CO₂ n’est pas transporté par une seule voie.']
],glossary:[['Espace mort','Volume ventilé ne participant pas directement aux échanges alvéolaires.'],['Pression partielle','Contribution d’un gaz à la pression totale d’un mélange.'],['Saturation','Proportion des sites de liaison de l’hémoglobine occupés par l’oxygène.'],['Bicarbonate','Forme majeure de transport du CO₂ dans le plasma.']],trap:'Une saturation normale ne prouve pas que le contenu total en oxygène est normal.',recall:'Quelle différence entre ventilation minute et ventilation alvéolaire ?',answer:'La seconde retranche l’espace mort du volume courant avant de tenir compte de la fréquence.',caseStudy:{prompt:'Deux ventilations ont 6 L/min : 500 mL × 12 et 200 mL × 30, espace mort 150 mL. Sont-elles équivalentes ?',answer:'Non. Ventilation alvéolaire : 4,2 L/min contre 1,5 L/min. Le schéma rapide et superficiel ventile surtout l’espace mort.'},sources:[['OpenStax · Échanges gazeux',open('anatomy-and-physiology-2e','22-4-gas-exchange')],['OpenStax · Transport des gaz',open('anatomy-and-physiology-2e','22-5-transport-of-gases')]]},
{id:'phys-renal',title:'Filtration glomérulaire et fonctions tubulaires',category:'Physiologie',tag:'Équilibre hydrique',objectives:['Construire un bilan filtré-réabsorbé-sécrété','Expliquer la concentration urinaire','Relier rein, pression et hormones'],sections:[
['Filtrer au glomérule','La filtration dépend des pressions hydrostatiques et oncotiques à travers une barrière sélective. Le débit de filtration glomérulaire est un volume par temps, pas une fraction de plasma sans unité. Autorégulation, tonus des artérioles et signaux extrinsèques modifient les pressions. Cellules et grosses protéines sont normalement peu filtrées.'],
['Transformer le filtrat','La réabsorption ramène une substance du tubule vers le sang ; la sécrétion l’ajoute au tubule. Excrétion = filtration − réabsorption + sécrétion. Le tubule proximal traite une grande fraction de l’eau et des solutés, tandis que les segments suivants ajustent le bilan. Réabsorber une substance ne signifie pas toujours la conserver totalement.'],
['Créer un gradient médullaire','L’anse de Henle, l’organisation à contre-courant et le recyclage de l’urée contribuent à l’osmolarité médullaire. Le segment ascendant épais réabsorbe des solutés tout en étant peu perméable à l’eau. Le collecteur utilise ce gradient selon sa perméabilité, modulée notamment par l’ADH.'],
['Réguler volume et pression','Le système rénine-angiotensine-aldostérone, l’ADH, les peptides natriurétiques et le sympathique agissent sur des cibles différentes. L’aldostérone favorise notamment la réabsorption sodée distale ; l’ADH augmente la perméabilité à l’eau du collecteur. Sodium total, osmolarité et volume ne sont pas interchangeables.']
],glossary:[['DFG','Volume de filtrat glomérulaire formé par unité de temps.'],['Réabsorption','Transport du tubule vers le milieu intérieur.'],['Sécrétion','Transport du milieu intérieur vers le tubule.'],['ADH','Hormone augmentant notamment la perméabilité à l’eau du canal collecteur.']],trap:'L’aldostérone régule surtout le sodium ; l’ADH régule directement la perméabilité à l’eau.',recall:'Écrivez la relation entre filtration, réabsorption, sécrétion et excrétion.',answer:'Excrétion = filtration − réabsorption + sécrétion.',caseStudy:{prompt:'100 unités filtrées, 95 réabsorbées et 10 sécrétées : combien excrétées ?',answer:'100 − 95 + 10 = 15 unités.'},sources:[['OpenStax · Physiologie rénale',open('anatomy-and-physiology-2e','25-5-physiology-of-urine-formation')],['OpenStax · Régulation endocrine rénale',open('anatomy-and-physiology-2e','25-8-endocrine-regulation-of-kidney-function')]]},
{id:'phys-digestion',title:'Motricité, sécrétions et absorption digestives',category:'Physiologie',tag:'Digestion',objectives:['Ordonner les phases de digestion','Associer enzyme, substrat et produit','Comparer voies d’absorption'],sections:[
['Propulser et mélanger','La déglutition coordonne phases volontaire et réflexes. Le péristaltisme propulse ; la segmentation mélange surtout le contenu. Le système nerveux entérique coordonne des circuits locaux modulés par l’autonome et des hormones. Une contraction circulaire n’a pas le même effet selon sa position par rapport au bol et la coordination longitudinale.'],
['Sécréter dans l’estomac','Cellules pariétales, principales, muqueuses et endocrines ont des produits distincts. L’acide favorise dénaturation et activation de la pepsine mais la muqueuse se protège par mucus, bicarbonate, jonctions et renouvellement. Le facteur intrinsèque est nécessaire à l’absorption ultérieure de vitamine B12 ; il n’est pas une enzyme digérant cette vitamine.'],
['Coordonner duodénum, pancréas et bile','L’acidité et les nutriments du chyme déclenchent des réponses nerveuses et hormonales. Les bicarbonates neutralisent, les enzymes pancréatiques hydrolysent et la bile facilite l’émulsification et la formation de micelles. La bile n’est pas une lipase. Les zymogènes protéolytiques sont activés selon une cascade qui protège le pancréas.'],
['Absorber par des voies différentes','Glucides et acides aminés gagnent surtout les capillaires puis la veine porte. Les lipides longs sont réassemblés, intégrés aux chylomicrons puis passent par les lymphatiques avant la circulation. Les villosités augmentent la surface ; elles ne sont pas les microvillosités, qui appartiennent au pôle apical des entérocytes.']
],glossary:[['Péristaltisme','Contractions coordonnées contribuant à la propulsion du contenu.'],['Zymogène','Précurseur enzymatique inactif activé par transformation.'],['Micelle','Assemblage facilitant l’approche des produits lipidiques vers l’épithélium.'],['Chylomicron','Particule transportant des lipides absorbés depuis l’intestin.']],trap:'La bile émulsifie et facilite l’absorption des lipides mais ne les hydrolyse pas comme une enzyme.',recall:'Quelle voie empruntent d’abord la plupart des lipides alimentaires à longue chaîne ?',answer:'Les lymphatiques intestinaux sous forme de chylomicrons, avant de rejoindre la circulation veineuse.',caseStudy:{prompt:'Un étudiant confond villosité et microvillosité. Comment les emboîter ?',answer:'La villosité est un relief multicellulaire de la muqueuse ; chaque entérocyte porte des microvillosités apicales qui forment la bordure en brosse.'},sources:[['OpenStax · Processus digestifs',open('anatomy-and-physiology-2e','23-2-digestive-system-processes-and-regulation')],['OpenStax · Absorption',open('anatomy-and-physiology-2e','23-7-chemical-digestion-and-absorption-a-closer-look')]]},
{id:'phys-sensory-motor',title:'Voies sensitives, motricité et réflexes',category:'Physiologie',tag:'Neurophysiologie',objectives:['Suivre une voie afférente et efférente','Expliquer un arc réflexe','Distinguer neurone moteur supérieur et inférieur'],sections:[
['Transduire un stimulus','Un récepteur transforme une énergie physique ou chimique en signal électrique. Potentiel récepteur et potentiel d’action sont distincts. Intensité, durée et localisation sont codées par fréquence, recrutement et organisation des champs récepteurs. L’adaptation décrit une évolution de réponse pendant un stimulus maintenu, pas une disparition obligatoire de la sensation.'],
['Monter vers le système central','Les voies somesthésiques utilisent des relais et des décussations spécifiques. Colonnes dorsales et système antérolatéral ne transportent pas exactement les mêmes modalités. Une lésion située avant ou après un croisement n’a pas la même latéralité. Le thalamus relaie de nombreuses informations vers le cortex, sans être un simple câble passif.'],
['Commander le mouvement','Les voies descendantes influencent les motoneurones via des circuits spinaux. Un motoneurone inférieur relie le système central au muscle ; une unité motrice rassemble ce neurone et ses fibres. Cortex, tronc cérébral, cervelet et noyaux gris centraux contribuent différemment à planification, exécution et correction.'],
['Construire un réflexe','Un arc associe récepteur, afférence, intégration, efférence et effecteur. Un réflexe monosynaptique comporte une seule synapse centrale principale entre afférence et motoneurone, mais des circuits parallèles existent. Réflexe ne signifie pas absence de modulation cérébrale ni réponse toujours identique.']
],glossary:[['Transduction','Conversion d’un stimulus en signal cellulaire.'],['Afférence','Voie conduisant une information vers un centre.'],['Motoneurone inférieur','Neurone dont l’axone atteint directement le muscle squelettique.'],['Arc réflexe','Circuit transformant rapidement une information sensorielle en réponse.']],trap:'Un réflexe spinal peut être modulé par le cerveau même si sa boucle de base se ferme dans la moelle.',recall:'Quelles sont les cinq composantes fonctionnelles d’un arc réflexe ?',answer:'Récepteur, voie afférente, centre intégrateur, voie efférente et effecteur.',caseStudy:{prompt:'Une personne perçoit un étirement mais la contraction réflexe est absente. Où raisonner ?',answer:'Il faut distinguer branche afférente, synapse centrale, motoneurone inférieur, jonction neuromusculaire et muscle ; la perception seule ne teste pas toute la boucle.'},sources:[['OpenStax · Fonctions sensitives et motrices',open('anatomy-and-physiology-2e','14-3-motor-responses')],['OpenStax · Réflexes',open('anatomy-and-physiology-2e','14-3-motor-responses')]]},
{id:'immuno-innate',title:'Immunité innée : barrières, inflammation et complément',category:'Immunologie',tag:'Immunité innée',objectives:['Distinguer barrières et effecteurs internes','Ordonner une inflammation aiguë','Expliquer les fonctions du complément'],sections:[
['Barrières et surveillance','Peau, mucus, cils, pH, peptides antimicrobiens et microbiotes limitent l’entrée et la croissance des agents. Une barrière combine propriétés physiques, chimiques et biologiques. Lorsqu’elle est franchie, des cellules résidentes détectent des motifs de danger ou microbiens par des récepteurs dont la spécificité est différente de celle des récepteurs adaptatifs.'],
['Inflammation aiguë','Médiateurs locaux modifient débit, perméabilité et recrutement leucocytaire. Roulement, activation, adhérence puis diapédèse permettent aux cellules de quitter le sang. Les neutrophiles arrivent souvent rapidement ; monocytes et macrophages assurent d’autres fonctions. Rougeur, chaleur, douleur et gonflement ont des mécanismes liés mais distincts.'],
['Phagocytose et destruction','Reconnaissance, adhérence, ingestion, phagolysosome et destruction forment une séquence. Opsonines et anticorps peuvent faciliter la capture. La phagocytose ne garantit pas la destruction de tout microbe : certains échappent ou résistent. Les cellules présentatrices peuvent en parallèle fournir des antigènes aux lymphocytes.'],
['Complément','Les voies classique, lectine et alternative convergent vers des convertases. Les produits favorisent opsonisation, inflammation et complexe d’attaque membranaire. La voie classique peut utiliser des anticorps mais le complément appartient aux mécanismes effecteurs de l’inné. Des régulateurs protègent les cellules de l’hôte.']
],glossary:[['PRR','Récepteur inné reconnaissant des motifs moléculaires partagés.'],['Diapédèse','Passage d’un leucocyte à travers l’endothélium.'],['Opsonisation','Marquage facilitant la reconnaissance et la phagocytose.'],['Complément','Ensemble de protéines plasmatiques activées en cascade.']],trap:'La voie classique du complément implique souvent des anticorps sans devenir pour autant une voie lymphocytaire.',recall:'Quelles grandes fonctions assure le complément ?',answer:'Opsonisation, amplification inflammatoire et lyse de certaines cibles par le complexe terminal.',caseStudy:{prompt:'Une bactérie est couverte de C3b. Quel effet immédiat attendre ?',answer:'Une phagocytose facilitée par les récepteurs du complément : C3b agit comme opsonine.'},sources:[['OpenStax · Défenses innées',open('microbiology','17-introduction')],['OpenStax · Défenses internes',open('microbiology','17-3-cellular-defenses')]]},
{id:'immuno-adaptive',title:'Immunité adaptative : présentation, lymphocytes et mémoire',category:'Immunologie',tag:'Immunité adaptative',objectives:['Comparer CMH I et II','Distinguer réponses B et T','Expliquer expansion clonale et mémoire'],sections:[
['Présenter un antigène','Le CMH I présente des peptides issus du compartiment intracellulaire à des lymphocytes T CD8 ; le CMH II présente surtout des peptides captés dans le compartiment extracellulaire à des T CD4. Les cellules présentatrices professionnelles fournissent aussi co-stimulation et cytokines. Reconnaître un peptide sans contexte d’activation peut conduire à une absence de réponse.'],
['Sélectionner puis amplifier','Chaque lymphocyte porte un récepteur d’une spécificité donnée avant la rencontre. L’antigène ne fabrique pas le récepteur ; il sélectionne et active des clones compatibles dans un contexte approprié. Prolifération et différenciation produisent effecteurs et cellules mémoire. La diversité initiale vient des réarrangements des gènes de récepteurs.'],
['Réponse humorale','Un lymphocyte B peut reconnaître un antigène natif, l’internaliser et le présenter. Avec une aide T adaptée, il prolifère, commute de classe, améliore l’affinité et produit plasmocytes et mémoire. Fab porte la liaison à l’antigène ; Fc recrute des fonctions effectrices. Classe et spécificité sont deux propriétés différentes.'],
['Réponse cellulaire et mémoire','Les T CD8 activés peuvent détruire des cellules présentant leur peptide cible sur CMH I. Les T CD4 coordonnent plusieurs réponses par contact et cytokines. La mémoire permet une réponse secondaire souvent plus rapide et forte. Elle ne signifie pas protection absolue ni persistance identique pour tous les antigènes.']
],glossary:[['CMH I','Molécules présentant surtout des peptides intracellulaires aux lymphocytes T CD8.'],['CMH II','Molécules présentant surtout des peptides captés aux lymphocytes T CD4.'],['Expansion clonale','Prolifération des lymphocytes activés d’une spécificité.'],['Plasmocyte','Cellule différenciée sécrétant de grandes quantités d’anticorps.']],trap:'L’antigène sélectionne un clone préexistant ; il ne modèle pas un récepteur sur mesure.',recall:'Quelle association principale entre CMH, origine du peptide et lymphocyte ?',answer:'CMH I, peptide intracellulaire, T CD8 ; CMH II, peptide capté, T CD4.',caseStudy:{prompt:'Une cellule B reconnaît une protéine, mais ne reçoit aucun signal T ni co-stimulation suffisante. La mémoire est-elle garantie ?',answer:'Non. Une réponse T-dépendante complète nécessite plusieurs signaux ; reconnaissance seule ne garantit ni expansion ni mémoire.'},sources:[['OpenStax · Immunité adaptative',open('microbiology','18-1-overview-of-specific-adaptive-immunity')],['OpenStax · Présentation antigénique',open('microbiology','18-2-major-histocompatibility-complexes-and-antigen-presenting-cells')]]},
{id:'immuno-clinical',title:'Vaccination, hypersensibilités et tolérance',category:'Immunologie',tag:'Applications immunologiques',objectives:['Comparer immunité active et passive','Classer les hypersensibilités par mécanisme','Distinguer tolérance et immunodéficience'],sections:[
['Active, passive, primaire, secondaire','L’immunité active résulte de la réponse de la personne après infection ou vaccination ; la passive transfère des anticorps et protège sans construire la même mémoire. Une réponse secondaire mobilise des cellules mémoire et peut être plus rapide. Naturel ou artificiel décrit le mode d’acquisition, pas la qualité de la protection.'],
['Principes vaccinaux','Un vaccin expose le système immunitaire à un antigène ou à son information dans un contexte contrôlé. Vivant atténué, inactivé, sous-unitaire, conjugué et plateforme génétique ont des propriétés différentes. Rappels, adjuvants et voie d’administration modulent la réponse. Efficacité individuelle et effet populationnel ne sont pas la même mesure.'],
['Quatre hypersensibilités','Type I implique IgE et mastocytes ; type II des anticorps dirigés contre des structures cellulaires ou matricielles ; type III des complexes immuns ; type IV des mécanismes T cellulaires retardés. Le délai seul ne classe pas tout : il faut identifier effecteurs, cible et mécanisme de lésion.'],
['Tolérance et déficits','La tolérance centrale élimine ou modifie des clones autoréactifs pendant leur développement ; la tolérance périphérique contrôle ceux qui subsistent. Une auto-immunité est une réponse contre le soi, tandis qu’une immunodéficience correspond à une fonction insuffisante. Les deux situations peuvent parfois coexister mais ne sont pas synonymes.']
],glossary:[['Immunité active','Protection construite par la réponse adaptative de l’individu.'],['Immunité passive','Protection par transfert d’effecteurs, surtout des anticorps.'],['Hypersensibilité','Réponse immunitaire causant des lésions ou symptômes inadaptés.'],['Tolérance','Mécanismes limitant les réponses contre le soi ou certains antigènes.']],trap:'Un vaccin induit une immunité active ; une injection d’anticorps apporte une immunité passive.',recall:'Quels effecteurs dominent les types I et IV ?',answer:'IgE et mastocytes pour le type I ; lymphocytes T et effecteurs cellulaires pour le type IV.',caseStudy:{prompt:'Un traitement apporte directement des anticorps protecteurs. Produit-il la même mémoire qu’un vaccin ?',answer:'Non. Il confère une immunité passive immédiate et transitoire, sans entraîner nécessairement la mémoire adaptative d’une immunisation active.'},sources:[['OpenStax · Vaccins',open('microbiology','18-5-vaccines')],['OpenStax · Hypersensibilités',open('microbiology','19-1-hypersensitivities')]]},
{id:'stats-diagnostic-tests',title:'Tests diagnostiques : sensibilité, spécificité et Bayes',category:'Biostatistiques',tag:'Tests et décision',objectives:['Construire un tableau 2 × 2','Calculer les quatre indicateurs','Expliquer l’effet de la prévalence'],sections:[
['Partir des effectifs','Croisez condition présente ou absente avec test positif ou négatif. Vrais positifs, faux positifs, faux négatifs et vrais négatifs remplissent quatre cases. Sensibilité et spécificité conditionnent sur la condition de référence ; valeurs prédictives conditionnent sur le résultat du test. Écrire les dénominateurs avant le calcul évite l’inversion.'],
['Mesurer le test','Sensibilité = VP/(VP+FN) et spécificité = VN/(VN+FP). Elles dépendent du seuil et de la population étudiée, même si on les présente souvent comme propriétés du test. Diminuer un seuil peut augmenter la sensibilité et diminuer la spécificité. Une courbe ROC explore ce compromis sur plusieurs seuils.'],
['Passer au patient testé','VPP = VP/(VP+FP) et VPN = VN/(VN+FN). Elles changent avec la prévalence ou probabilité prétest. Dans une population où la condition est rare, de nombreux positifs peuvent être faux même avec une bonne spécificité. Bayes formalise ce passage d’une probabilité prétest à post-test.'],
['Rapports de vraisemblance','LR+ = sensibilité/(1−spécificité) et LR− = (1−sensibilité)/spécificité. Ils multiplient les cotes prétest pour obtenir des cotes post-test. Un LR proche de 1 modifie peu la probabilité. La décision finale dépend aussi des conséquences des erreurs et du contexte clinique ; le calcul seul ne prescrit rien.']
],glossary:[['Sensibilité','Proportion de tests positifs parmi les personnes ayant la condition.'],['Spécificité','Proportion de tests négatifs parmi les personnes sans la condition.'],['VPP','Proportion de personnes ayant la condition parmi les tests positifs.'],['Rapport de vraisemblance','Facteur reliant les cotes prétest et post-test.']],trap:'P(condition sachant test positif) n’est pas la sensibilité.',recall:'Quel indicateur utilise tous les tests positifs au dénominateur ?',answer:'La valeur prédictive positive.',caseStudy:{prompt:'90 VP, 10 FN, 180 FP et 720 VN : sensibilité et VPP ?',answer:'Sensibilité 90/100 = 90 %. VPP 90/270 = 33,3 %. Les dénominateurs répondent à deux questions différentes.'},sources:[['OpenStax · Probabilité conditionnelle',open('introductory-statistics-2e','3-3-two-basic-rules-of-probability')]]},
{id:'stats-study-design',title:'Plans d’étude, biais et causalité',category:'Biostatistiques',tag:'Méthodologie',objectives:['Reconnaître les principaux plans','Identifier biais et confusion','Séparer association et causalité'],sections:[
['Décrire avant de comparer','Un cas clinique décrit, une série rassemble des cas, une étude transversale mesure à un moment, une cohorte suit exposition puis événement et une étude cas-témoins part de l’événement pour comparer les expositions antérieures. Chaque plan utilise des dénominateurs et des mesures d’association adaptés. Aucun nom de plan ne garantit sa qualité.'],
['Intervenir ou observer','Un essai attribue une intervention, idéalement par randomisation lorsque cela est éthique et faisable. La randomisation équilibre les facteurs en moyenne, sans garantir des groupes identiques dans un petit échantillon. Dissimulation de l’allocation et aveugle répondent à d’autres biais. Une étude observationnelle peut être solide sans établir aussi directement la causalité.'],
['Biais et confusion','Biais de sélection, information, classement et attrition déplacent systématiquement l’estimation. Un facteur de confusion est associé à l’exposition et au résultat sans être un intermédiaire causal. Restriction, appariement, stratification et modèles peuvent aider. Ajuster sans modèle causal peut aussi introduire des erreurs.'],
['Interpréter la causalité','Temporalité, force et cohérence de l’association, relation dose-réponse, plausibilité et expérimentation contribuent au raisonnement sans constituer une checklist automatique. Taille d’effet, incertitude, validité interne et généralisabilité doivent être discutées séparément. Une valeur p faible ne corrige ni biais ni mauvaise mesure.']
],glossary:[['Cohorte','Étude comparant le devenir de groupes définis notamment par une exposition.'],['Cas-témoins','Étude comparant des expositions antérieures selon la présence d’un événement.'],['Biais','Erreur systématique dans la conception, la mesure ou l’analyse.'],['Confusion','Mélange d’effets lié à un facteur associé à l’exposition et au résultat.']],trap:'La randomisation n’empêche pas toute erreur de mesure et ne garantit pas des groupes exactement identiques.',recall:'Pourquoi une association statistique ne suffit-elle pas à prouver une causalité ?',answer:'Parce que hasard, biais, confusion, causalité inverse ou autres mécanismes peuvent produire l’association.',caseStudy:{prompt:'Une étude associe café et événement, sans mesurer le tabagisme lié aux deux. Quel problème ?',answer:'Le tabagisme peut être un facteur de confusion ; l’association brute peut mélanger son effet avec celui attribué au café.'},sources:[['OpenStax · Échantillonnage et données',open('introductory-statistics-2e','1-2-data-sampling-and-variation-in-data-and-sampling')],['OpenStax · Expériences',open('introductory-statistics-2e','1-4-experimental-design-and-ethics')]]},
{id:'pharma-receptors',title:'Récepteurs, agonistes et courbes dose-effet',category:'Pharmacologie',tag:'Pharmacodynamie',objectives:['Distinguer affinité, puissance et efficacité','Comparer agoniste et antagoniste','Lire une courbe concentration-effet'],sections:[
['Lier puis répondre','L’affinité décrit la tendance d’un ligand à se lier ; l’efficacité décrit sa capacité à produire une réponse après liaison. Un agoniste partiel peut occuper les mêmes récepteurs qu’un agoniste plein tout en produisant un maximum inférieur. Occupation et effet ne sont pas toujours proportionnels si des récepteurs de réserve ou des amplifications existent.'],
['Puissance et efficacité','EC50 est la concentration produisant la moitié de l’effet maximal dans un système donné. Une courbe déplacée vers la gauche traduit souvent une puissance apparente supérieure, pas forcément un meilleur bénéfice. Emax décrit l’effet maximal mesuré. Comparer des puissances sans comparer les conditions, cibles et effets n’a pas de sens.'],
['Antagoniser','Un antagoniste compétitif réversible peut déplacer la courbe de l’agoniste sans réduire Emax si une concentration suffisante d’agoniste surmonte la compétition. Un antagonisme insurmontable ou non compétitif peut diminuer le maximum. Un antagoniste n’est pas nécessairement l’opposé physiologique d’un agoniste : il agit sur une relation de cible.'],
['Fenêtre thérapeutique','Les relations dose-effet varient entre effets recherchés et indésirables. L’index thérapeutique est un repère populationnel, pas une garantie individuelle. Variabilité pharmacocinétique, comorbidités et interactions déplacent l’exposition et la réponse. Ces principes expliquent la surveillance mais ne donnent aucune posologie personnelle.']
],glossary:[['Affinité','Tendance d’un ligand à se lier à une cible.'],['Efficacité','Capacité d’un ligand lié à produire une réponse.'],['EC50','Concentration produisant la moitié de l’effet maximal observé.'],['Antagoniste compétitif','Ligand qui entre en compétition réversible avec un agoniste pour une cible.']],trap:'Plus puissant ne signifie pas plus efficace ni plus sûr.',recall:'Quel paramètre compare le maximum d’effet et lequel situe la demi-réponse ?',answer:'Emax compare le maximum ; EC50 situe la concentration de demi-effet.',caseStudy:{prompt:'Une courbe est déplacée à droite après ajout d’un antagoniste, mais Emax reste atteint. Quel mécanisme évoquer ?',answer:'Un antagonisme compétitif réversible, sous réserve que les autres conditions expérimentales soient identiques.'},sources:[['SFPT · Pharmacodynamie','https://pharmacomedicale.org/pharmacologie/pharmacodynamie/37-pharmacodynamie/75-recepteurs-pharmacologiques'],['SFPT · Relation dose-effet','https://pharmacomedicale.org/pharmacologie/pharmacologie-medicale-vue-d-ensemble/35-relation-dose-effet-clinique/69-les-notions-complementaires']]},
{id:'pharma-safety',title:'Effets indésirables, interactions et pharmacovigilance',category:'Pharmacologie',tag:'Sécurité du médicament',objectives:['Classer les mécanismes d’interaction','Distinguer effet indésirable et erreur','Comprendre le signal de pharmacovigilance'],sections:[
['Décrire un événement','Un événement après une prise n’est pas automatiquement causé par le médicament. Chronologie, mécanisme, évolution à l’arrêt, autres causes et données connues nourrissent l’imputabilité. Un effet indésirable peut survenir aux doses usuelles ; une erreur médicamenteuse concerne le processus d’utilisation. Gravité et intensité sont des notions distinctes.'],
['Interactions pharmacocinétiques','Absorption, enzymes, transporteurs et élimination peuvent modifier l’exposition. Une inhibition enzymatique peut augmenter rapidement certaines concentrations ; une induction nécessite souvent la synthèse de protéines et évolue plus lentement. Un médicament peut être substrat, inhibiteur ou inducteur selon le système. Les conséquences dépendent aussi de sa marge thérapeutique.'],
['Interactions pharmacodynamiques','Deux substances peuvent additionner ou opposer leurs effets sans modifier leurs concentrations. Sédation, saignement, pression ou rythme sont des exemples de fonctions où plusieurs mécanismes convergent. L’absence d’interaction métabolique n’exclut donc pas une interaction clinique. Il faut identifier la fonction partagée et le sens des effets.'],
['Détecter un signal','La pharmacovigilance collecte et analyse des signalements pour repérer des risques rares ou nouveaux. Un signal déclenche une évaluation ; il ne prouve pas seul une causalité ni une fréquence. Sous-notification et biais de notoriété limitent les taux bruts. Toute décision individuelle relève d’un professionnel et des recommandations officielles.']
],glossary:[['Imputabilité','Évaluation du lien possible entre un produit et un événement.'],['Induction enzymatique','Augmentation progressive de l’expression ou activité d’enzymes.'],['Interaction pharmacodynamique','Modification d’effet sans changement nécessaire des concentrations.'],['Signal','Information suggérant un risque nouveau ou modifié à évaluer.']],trap:'Un signal de pharmacovigilance est une alerte à étudier, pas une causalité déjà démontrée.',recall:'Quelle différence entre interaction pharmacocinétique et pharmacodynamique ?',answer:'La première modifie le devenir ou l’exposition ; la seconde modifie les effets sans changement nécessaire d’exposition.',caseStudy:{prompt:'Deux médicaments augmentent le risque de saignement par des cibles différentes, sans changer leurs concentrations. Type ?',answer:'Interaction pharmacodynamique additive sur l’hémostase.'},sources:[['ANSM · Pharmacovigilance','https://ansm.sante.fr/qui-sommes-nous/notre-perimetre/les-medicaments/p/organiser-les-vigilances'] ,['SFPT · Interactions','https://pharmacomedicale.org/pharmacologie/risque-des-medicaments/48-interactions-medicamenteuses']]},
{id:'public-epidemiology',title:'Épidémiologie : incidence, prévalence et mesures d’association',category:'Santé publique',tag:'Épidémiologie',objectives:['Choisir le bon dénominateur','Distinguer incidence et prévalence','Calculer risque relatif et différence de risques'],sections:[
['Compter dans une population','Un nombre de cas doit être rapporté à une population et une période. La prévalence décrit les cas présents à un moment ou sur une période. L’incidence mesure de nouveaux événements parmi les personnes à risque. Une maladie longue peut avoir une forte prévalence malgré une incidence stable ; guérison et mortalité modifient le stock de cas.'],
['Risque et taux','Un risque est une probabilité cumulée sur une période dans une cohorte définie. Un taux d’incidence utilise du temps-personne et possède une dimension inverse du temps. Les sujets ne contribuent pas nécessairement la même durée. Pour comparer, précisez début, fin, événement et critères d’entrée.'],
['Comparer des groupes','Le risque relatif est un rapport ; la différence de risques mesure un excès absolu. Un risque multiplié par deux peut correspondre à une différence faible ou forte selon le niveau initial. Les deux mesures répondent à des questions complémentaires et doivent être accompagnées d’incertitude.'],
['Standardiser','Deux populations d’âges différents peuvent avoir des taux bruts différents sans différence à âge égal. La standardisation directe applique des taux spécifiques à une structure commune ; l’indirecte compare des événements observés et attendus. Le résultat dépend de la population de référence et ne remplace pas les taux spécifiques.']
],glossary:[['Prévalence','Proportion de personnes présentant une condition dans une population définie.'],['Incidence','Survenue de nouveaux événements dans une population à risque.'],['Risque relatif','Rapport des risques entre deux groupes.'],['Standardisation','Méthode rendant certaines comparaisons moins dépendantes de structures de population différentes.']],trap:'Un taux d’incidence en personnes-années n’est pas une proportion sans unité.',recall:'Pourquoi incidence et prévalence peuvent-elles évoluer différemment ?',answer:'La prévalence dépend de l’entrée de nouveaux cas mais aussi de leur durée, des guérisons et des décès.',caseStudy:{prompt:'Risque 2 % exposés et 1 % non exposés : RR et différence ?',answer:'RR = 2 ; différence absolue = 1 point de pourcentage. Les deux mesures sont nécessaires.'},sources:[['OMS · Données de santé','https://www.who.int/data/gho/indicator-metadata-registry'],['OpenStax · Risque relatif','https://openstax.org/books/population-health/pages/4-3-measures-of-association']]},
{id:'public-screening',title:'Prévention, dépistage et décision collective',category:'Santé publique',tag:'Prévention et dépistage',objectives:['Distinguer les niveaux de prévention','Énoncer les conditions d’un dépistage','Expliquer bénéfices, risques et biais'],sections:[
['Trois niveaux classiques','La prévention primaire réduit la survenue, la secondaire cherche une condition avant ses manifestations habituelles et la tertiaire limite conséquences et récidives. Ces niveaux se chevauchent parfois selon l’événement choisi. Une action de dépistage n’est pas un diagnostic : un résultat positif nécessite une procédure de confirmation.'],
['Quand dépister','La condition doit représenter un enjeu, disposer d’une phase détectable, d’un test acceptable et d’une prise en charge dont l’anticipation apporte un bénéfice. Organisation, accès, qualité, participation et suivi comptent autant que la performance analytique. Détecter plus tôt n’est utile que si cela améliore un résultat pertinent.'],
['Biais de temps','Le biais d’avance au diagnostic allonge la survie mesurée depuis le diagnostic sans retarder le décès. Le biais de durée sélectionne davantage les formes lentes lors d’un dépistage périodique. Le surdiagnostic détecte des anomalies qui n’auraient pas causé de problème. Mortalité spécifique et qualité de vie répondent mieux au bénéfice que la seule survie après diagnostic.'],
['Évaluer collectivement','Un programme compare bénéfices, faux positifs, faux négatifs, examens, surtraitements, coûts et inégalités d’accès. L’information doit permettre un choix éclairé lorsque cela s’applique. Une recommandation populationnelle évolue avec les données et ne se transpose pas automatiquement à chaque situation personnelle.']
],glossary:[['Prévention primaire','Action réduisant la survenue d’un problème de santé.'],['Dépistage','Recherche organisée d’une condition chez des personnes sans diagnostic connu.'],['Biais d’avance','Augmentation artificielle de la survie mesurée par diagnostic plus précoce.'],['Surdiagnostic','Détection d’une anomalie qui n’aurait pas causé de conséquence clinique.']],trap:'Une meilleure survie après diagnostic ne prouve pas à elle seule que le dépistage réduit la mortalité.',recall:'Pourquoi un test de dépistage positif n’est-il pas encore un diagnostic ?',answer:'Parce que le dépistage trie une population ; une procédure diagnostique confirme ou infirme le résultat.',caseStudy:{prompt:'Le diagnostic est avancé de deux ans mais la date du décès ne change pas. La survie depuis le diagnostic augmente-t-elle ?',answer:'Oui, artificiellement de deux ans : c’est le biais d’avance, sans bénéfice réel sur la mortalité.'},sources:[['HAS · Dépistage et prévention','https://www.has-sante.fr/jcms/c_410171/fr/depistage-et-prevention'],['OMS · Promotion de la santé','https://www.who.int/health-topics/health-promotion']]},
{id:'chem-thermodynamics',title:'Thermodynamique et cinétique des réactions biologiques',category:'Chimie',tag:'Énergie et réactions',objectives:['Distinguer état, chemin et vitesse','Interpréter ΔH, ΔS et ΔG','Lire une loi de vitesse simple'],sections:[
['État et transformations','Une fonction d’état dépend des états initial et final, pas du chemin. Enthalpie, entropie et énergie libre décrivent des aspects différents. À température constante, ΔG = ΔH − TΔS. Le signe dépend des conditions et concentrations. Exothermique ne signifie pas automatiquement spontané, car le terme entropique intervient.'],
['Équilibre','La constante d’équilibre est reliée à l’énergie libre standard, tandis que le quotient réactionnel utilise les activités actuelles. À l’équilibre, la composition macroscopique est stable mais les réactions microscopiques continuent. Ajouter un catalyseur accélère l’approche de l’équilibre sans changer sa constante.'],
['Vitesse et ordre','Une loi de vitesse relie vitesse et concentrations selon des exposants déterminés expérimentalement. L’ordre ne se déduit pas toujours des coefficients de l’équation globale. La demi-vie est constante pour un premier ordre idéal, mais pas pour tous les ordres. Température et énergie d’activation influencent la constante de vitesse.'],
['Catalyse enzymatique','Une enzyme stabilise un chemin réactionnel de plus faible énergie d’activation. Elle accélère aller et retour et ne modifie ni ΔG ni équilibre. Saturation, pH, température et inhibiteurs modulent la vitesse. Une enzyme ne rend pas favorable une réaction défavorable ; le couplage peut le faire.']
],glossary:[['Enthalpie','Fonction d’état liée notamment aux échanges de chaleur à pression constante.'],['Entropie','Fonction d’état associée au nombre de configurations accessibles.'],['Énergie d’activation','Barrière énergétique séparant réactifs et état de transition.'],['Catalyseur','Agent accélérant une réaction sans déplacer son équilibre thermodynamique.']],trap:'Un catalyseur change la vitesse, pas la constante d’équilibre.',recall:'Pourquoi une réaction exothermique n’est-elle pas toujours spontanée ?',answer:'Parce que ΔG dépend aussi de la température et de la variation d’entropie.',caseStudy:{prompt:'Une enzyme est ajoutée à un mélange déjà à l’équilibre. La proportion produits/réactifs change-t-elle ?',answer:'Non. Les deux sens sont accélérés mais le rapport d’équilibre reste le même.'},sources:[['OpenStax · Énergie libre',open('chemistry-2e','16-4-free-energy')],['OpenStax · Cinétique',open('chemistry-2e','12-1-chemical-reaction-rates')]]},
{id:'chem-redox-organic',title:'Oxydoréduction et fonctions organiques du vivant',category:'Chimie',tag:'Chimie organique',objectives:['Attribuer un nombre d’oxydation','Reconnaître les fonctions principales','Relier structure et réactivité'],sections:[
['Transférer des électrons','Une oxydation perd des électrons et une réduction en gagne. Les demi-équations équilibrent matière et charge. L’oxydant est réduit ; le réducteur est oxydé. Les nombres d’oxydation sont un outil de comptabilité, pas toujours une charge physique portée par chaque atome.'],
['Potentiels redox','Une différence de potentiel favorable peut entraîner un transfert d’électrons. L’équation de Nernst relie potentiel et activités. Les conditions standard biologiques et chimiques ne sont pas toujours identiques. Un potentiel plus positif indique une plus grande tendance à recevoir des électrons dans les conditions précisées.'],
['Fonctions organiques','Alcools, carbonyles, acides carboxyliques, amines, amides, esters et phosphates confèrent des propriétés distinctes. Reconnaître la fonction guide polarité, acidité et réactions. Une même biomolécule peut en porter plusieurs, et le comportement global ne se réduit pas à un groupe isolé.'],
['Isomérie','Des isomères partagent une formule brute mais diffèrent par connectivité ou organisation spatiale. Les énantiomères sont images miroir non superposables ; les diastéréoisomères ne le sont pas. Les systèmes biologiques sont chiraux : deux stéréoisomères peuvent interagir différemment avec enzymes et récepteurs.']
],glossary:[['Oxydant','Espèce qui capte des électrons et se réduit.'],['Réducteur','Espèce qui cède des électrons et s’oxyde.'],['Groupe carbonyle','Fonction contenant une double liaison carbone-oxygène.'],['Énantiomère','Stéréoisomère image miroir non superposable d’un autre.']],trap:'L’oxydant est l’espèce qui se réduit.',recall:'Quelle différence entre isomères de constitution et stéréoisomères ?',answer:'Les premiers diffèrent par connectivité ; les seconds ont la même connectivité mais une organisation spatiale différente.',caseStudy:{prompt:'NADH cède des électrons à une réaction. Est-il oxydant ou réducteur ?',answer:'Réducteur : il donne des électrons et est lui-même oxydé en NAD⁺.'},sources:[['OpenStax · Oxydoréduction',open('chemistry-2e','17-1-review-of-redox-chemistry')],['OpenStax · Chimie organique',open('organic-chemistry','3-1-functional-groups')]]},
{id:'physics-membranes',title:'Diffusion, osmose et transports transmembranaires',category:'Biophysique',tag:'Transport et membranes',objectives:['Appliquer qualitativement la loi de Fick','Distinguer osmolarité et tonicité','Comparer diffusion et convection'],sections:[
['Diffusion','Un flux diffusif augmente avec surface, gradient et coefficient de diffusion, et diminue avec l’épaisseur. La loi de Fick décrit un modèle dont les hypothèses doivent être annoncées. À l’équilibre, le mouvement moléculaire persiste mais les flux opposés se compensent. Distance accrue ralentit fortement les temps de diffusion.'],
['Osmose et pression','L’eau répond aux différences de potentiel chimique et aux solutés effectivement retenus. L’osmolarité compte les particules ; la tonicité prévoit l’effet durable sur le volume cellulaire selon la perméabilité. Deux solutions iso-osmolaires peuvent ne pas être isotoniques si un soluté traverse rapidement la membrane.'],
['Perméabilité','La perméabilité associe propriétés de membrane et de soluté. Un canal augmente un passage passif selon le gradient électrochimique ; un transporteur peut saturer. Le transport actif primaire utilise directement une source d’énergie, tandis que le secondaire exploite un gradient créé ailleurs. Protéine membranaire ne signifie donc pas actif.'],
['Convection et filtration','La convection transporte des solutés avec un fluide sous l’effet d’une différence de pression. Dans les capillaires, pressions hydrostatique et oncotique contribuent aux mouvements d’eau, avec la perméabilité et le drainage lymphatique. Diffusion d’un gaz et filtration de liquide utilisent des forces motrices différentes.']
],glossary:[['Flux','Quantité traversant une surface par unité de temps ou de surface selon la définition.'],['Tonicité','Effet d’une solution sur le volume cellulaire à l’équilibre fonctionnel.'],['Perméabilité','Facilité avec laquelle une substance traverse une barrière.'],['Convection','Transport associé au mouvement global d’un fluide.']],trap:'Iso-osmolaire ne signifie pas toujours isotonique.',recall:'Quels paramètres de la loi de Fick favorisent un flux ?',answer:'Grande surface, grand gradient, coefficient élevé et faible épaisseur.',caseStudy:{prompt:'Une solution iso-osmolaire contient un soluté qui entre rapidement dans la cellule. Restera-t-elle isotonique ?',answer:'Pas nécessairement : le soluté pénètre, l’eau peut suivre et le volume cellulaire changer.'},sources:[['OpenStax · Transport membranaire',open('biology-2e','5-2-passive-transport')],['OpenStax · Échanges capillaires',open('anatomy-and-physiology-2e','20-3-capillary-exchange')]]},
{id:'physics-bioelectricity',title:'Électricité cellulaire et sécurité des courants',category:'Biophysique',tag:'Électricité biologique',objectives:['Relier tension, courant et résistance','Expliquer un potentiel d’équilibre','Distinguer signal biologique et énergie électrique'],sections:[
['Charge, courant, tension','Le courant est un débit de charge ; la tension représente une différence de potentiel. Dans un conducteur ohmique, U = RI. Puissance = UI. Les tissus ne sont pas de simples résistances constantes : membranes, ions, fréquence et géométrie introduisent capacitance et dépendances. Les unités doivent rester explicites.'],
['Membrane capacitive','La bicouche sépare des charges et se comporte comme une capacité. Un courant peut d’abord charger cette capacité avant de modifier la tension. La constante de temps dépend résistance et capacité. Une grande résistance membranaire limite les fuites ; une grande capacité ralentit les variations de potentiel.'],
['Potentiel d’équilibre','L’équation de Nernst donne le potentiel où gradient chimique et force électrique d’un ion se compensent. Le potentiel de membrane dépend de plusieurs perméabilités et gradients, pas seulement du potassium. Ouvrir un canal attire le potentiel vers l’équilibre de l’ion sans l’y fixer instantanément.'],
['Courants et organisme','Les effets d’un courant externe dépendent intensité, trajet, durée, fréquence, surface de contact et résistance des tissus. Une tension seule ne suffit pas à prévoir le risque. Ce chapitre explique des principes physiques ; toute situation électrique réelle exige les règles de sécurité et les services compétents, sans expérimentation sur le corps.']
],glossary:[['Courant','Débit de charge électrique.'],['Tension','Différence de potentiel électrique entre deux points.'],['Capacité','Aptitude d’un système à stocker des charges pour une différence de potentiel.'],['Potentiel de Nernst','Potentiel d’équilibre électrochimique d’un ion.']],trap:'Le potentiel de membrane n’est généralement pas égal au potentiel d’équilibre d’un seul ion.',recall:'Que devient le potentiel si la perméabilité à un ion augmente fortement ?',answer:'Il tend vers le potentiel d’équilibre de cet ion, selon les autres conductances présentes.',caseStudy:{prompt:'Deux cellules ont la même résistance mais l’une a une capacité double. Laquelle change le plus lentement de potentiel ?',answer:'Celle de capacité double, car sa constante de temps RC est plus grande.'},sources:[['OpenStax · Potentiel membranaire',open('anatomy-and-physiology-2e','12-4-the-action-potential')],['OpenStax · Circuits',open('college-physics-2e','20-2-ohms-law-resistance-and-simple-circuits')]]},
]

export const firstYearCourses:Course[]=drafts.map(course=>({
 id:course.id,title:course.title,category:course.category,tag:course.tag,structure:null,objectives:course.objectives,
 sections:course.sections.map(([title,text])=>({title,text})),glossary:course.glossary,trap:course.trap,recall:course.recall,answer:course.answer,caseStudy:course.caseStudy,
 minutes:Math.max(12,Math.ceil(course.sections.map(section=>section[1]).join(' ').split(/\s+/).length/150)+8),source:course.sources[0][1],sources:course.sources.map(([label,url])=>({label,url})),
}))
export const firstYearSupport=courseSupport(firstYearCourses)
