import type {Course} from './curriculum'

// Textes originaux : les liens de lecture servent à vérifier les notions,
// aucune illustration de manuel n'est redistribuée.
type Chapter = {prerequisites:string[];structure:string|null;sections:[string,string][];sources:[string,string][]}
const ap='https://openstax.org/books/anatomy-and-physiology-2e/pages/'
const mi='https://openstax.org/books/microbiology/pages/'
export const flagshipChapters:Record<string,Chapter>={
 'phys-cardiac-cycle':{structure:'FMA7088',prerequisites:['Circulations pulmonaire et systémique','Gradient de pression','Différence entre volume et débit'],sources:[['Cycle et valves',ap+'19-3-cardiac-cycle'],['Régulation de la pompe',ap+'19-4-cardiac-physiology']],sections:[
 ['Une pompe, deux circuits, trois grandeurs',`Le cœur droit envoie le sang vers les poumons ; le cœur gauche l’envoie vers les organes. En régime stable, leurs débits moyens sont égaux, car les deux pompes travaillent en série. Leurs pressions sont pourtant très différentes : la circulation systémique oppose une résistance plus élevée. Une pression élevée ne signifie donc pas automatiquement un débit plus élevé.

Avant chaque raisonnement, séparez volume, pression et débit. Le volume décrit ce que contient une cavité, en millilitres. La pression décrit une force par unité de surface, souvent en mmHg. Le débit indique un volume déplacé par unité de temps. Pour ouvrir une valve, comparez les pressions de part et d’autre ; pour calculer l’éjection, comparez les volumes avant et après la systole.`],
 ['Remplissage : de la relaxation à la précharge',`La diastole ventriculaire commence par la relaxation, alors que le ventricule contient encore le volume télésystolique. La mitrale s’ouvre seulement lorsque la pression de l’atrium gauche dépasse celle du ventricule gauche. Le sang entre d’abord rapidement, puis le flux ralentit lorsque le gradient diminue. La contraction atriale complète ce remplissage ; elle n’en assure pas la totalité.

Le volume télédiastolique, ou VTD, est le volume maximal juste avant la contraction ventriculaire. Il renseigne sur les conditions initiales d’étirement. La précharge désigne plus précisément la charge mécanique initiale des fibres : le VTD n’en est qu’un indicateur. Un ventricule peu compliant peut présenter une pression de remplissage élevée sans volume particulièrement grand. Pour comprendre ce cas, raisonnez avec la relation pression-volume et non avec une seule mesure.`],
 ['Contraction isovolumétrique : monter en pression',`Après la dépolarisation ventriculaire, les cardiomyocytes développent une force. Dès que la pression ventriculaire dépasse la pression atriale, la mitrale se ferme. La pression reste encore inférieure à celle de l’aorte : la valve aortique est donc également fermée. Dans ce modèle sans fuite valvulaire, le volume ne change pas pendant que la pression augmente.

C’est la contraction isovolumétrique. Le mot décrit le volume de la cavité, pas l’absence de travail cellulaire ou de consommation d’ATP. Sur une boucle pression-volume, cette phase se dessine par un segment vertical ascendant au VTD. Le premier bruit cardiaque est associé à la fermeture des valves atrioventriculaires et aux vibrations du système cardiohémique. Les valves orientent le flux ; la force de propulsion provient du myocarde.`],
 ['Éjection et relaxation : refermer le cycle',`Quand la pression ventriculaire devient supérieure à la pression aortique, la valve aortique s’ouvre. Le volume ventriculaire diminue : l’éjection débute rapidement, puis ralentit. Le ventricule ne se vide pas complètement. Le sang restant à la fin est le volume télésystolique, ou VTS. Le volume éjecté par battement vaut donc VTD moins VTS.

Au début de la relaxation, la pression ventriculaire devient inférieure à la pression aortique et la valve aortique se ferme. La mitrale reste encore fermée tant que la pression ventriculaire dépasse celle de l’atrium. Cette relaxation isovolumétrique est le segment vertical descendant au VTS. Lorsque la mitrale s’ouvre à nouveau, le remplissage recommence. L’ordre des événements se déduit ainsi des gradients de pression, sans mémoriser arbitrairement quatre positions de valves.`],
 ['Lire une boucle pression-volume',`L’abscisse représente le volume du ventricule gauche ; l’ordonnée représente sa pression. Le remplissage va de gauche à droite, la contraction monte à droite, l’éjection va de droite à gauche et la relaxation descend à gauche. Le sens de parcours est antihoraire. Les points de transition correspondent aux ouvertures ou fermetures valvulaires.

La largeur est le volume d’éjection systolique. L’aire de la boucle représente le travail mécanique externe fourni pendant un cycle, et non la consommation énergétique totale du myocarde. Une boucle plus haute n’est pas nécessairement plus large. Pour comparer deux situations, demandez-vous d’abord si VTD, VTS et pression d’éjection ont changé. Le dessin interactif ci-dessus utilise des coordonnées pédagogiques : il illustre ces relations et ne constitue pas un enregistrement clinique.`],
 ['Précharge, postcharge, contractilité : trois expériences',`À contractilité et postcharge comparables, augmenter modérément le remplissage peut augmenter le volume éjecté : c’est le mécanisme de Frank-Starling. Il aide les deux ventricules à adapter leur éjection au retour veineux. Il ne signifie pas que tout étirement supplémentaire améliore indéfiniment la fonction.

La postcharge est la contrainte que le ventricule doit surmonter pendant l’éjection. Si elle augmente isolément sur un battement, le ventricule peut laisser davantage de sang en fin de systole : VTS augmente et VES diminue. Une contractilité accrue produit au contraire une éjection plus efficace à charges comparables. Dans une expérience réelle, ces paramètres interagissent ; la consigne « toutes choses égales par ailleurs » est une hypothèse de travail qu’il faut citer avant de conclure.`],
 ['Calculer débit et fraction d’éjection',`Avec VTD = 120 mL et VTS = 50 mL, VES = 70 mL. À 75 battements par minute, le débit cardiaque est 70 × 75 = 5 250 mL/min, soit 5,25 L/min. La fraction d’éjection vaut 70/120, soit environ 58 %. Les unités vérifient le calcul : mL par battement multiplié par battements par minute donne mL par minute.

Une même fraction peut correspondre à des volumes éjectés différents. Deux ventricules ayant des VTD de 80 et 140 mL et une fraction de 50 % éjectent respectivement 40 et 70 mL. Une fréquence très rapide peut raccourcir le remplissage et réduire le VES : multiplier la fréquence ne multiplie donc pas toujours proportionnellement le débit. La fraction d’éjection seule ne suffit pas à décrire le fonctionnement circulatoire.`],
 ['Électricité, mécanique et raisonnement intégré',`L’ECG renseigne sur l’activité électrique : l’onde P concerne la dépolarisation atriale, le complexe QRS la dépolarisation ventriculaire et l’onde T la repolarisation ventriculaire. Les changements mécaniques suivent ces événements avec un délai. Une onde électrique ne mesure directement ni pression, ni débit, ni force.

Pour traiter un cas, procédez dans l’ordre : identifiez la perturbation, déduisez le gradient valvulaire, prévoyez la variation de volume, puis calculez le débit si la fréquence est connue. Par exemple, une hausse isolée de pression aortique augmente l’obstacle à l’éjection ; elle n’ouvre pas plus tôt la valve aortique. Terminez en distinguant votre prédiction immédiate des adaptations secondaires du système autonome, du retour veineux et des vaisseaux. Cette méthode limite les conclusions excessives tirées d’un seul paramètre.`]
 ]},
 'phys-renal':{structure:'FMA7204',prerequisites:['Compartiments liquidiens','Transport membranaire','Concentration et débit'],sources:[['Filtration',ap+'25-5-physiology-of-urine-formation'],['Réabsorption et sécrétion',ap+'25-6-tubular-reabsorption'],['Régulation hormonale',ap+'25-8-endocrine-regulation-of-kidney-function']],sections:[
 ['Deux trajets à suivre dans le néphron',`Le sang atteint les capillaires glomérulaires par l’artériole afférente et les quitte par l’artériole efférente. Le liquide filtré entre dans l’espace capsulaire puis parcourt tubule proximal, anse de Henle, tubule distal et système collecteur. Ces deux trajets échangent de la matière mais ne se confondent jamais.

La filtration va du plasma vers la capsule. La réabsorption ramène une substance du tubule vers le sang ; la sécrétion la fait passer du sang vers le tubule. L’excrétion correspond finalement à ce qui quitte le corps dans l’urine. Dessinez les flèches avant de calculer. Le schéma du néphron simplifie ses rapports tridimensionnels pour rendre ces directions visibles ; les volumes dessinés n’indiquent pas des proportions de débit.`],
 ['Filtration glomérulaire et charge filtrée',`Le filtre comporte endothélium fenestré, membrane basale et podocytes avec fentes de filtration. Eau et nombreux petits solutés traversent ; les cellules sanguines et la grande majorité des protéines restent dans le sang. La concentration d’un soluté librement filtré est proche de celle de l’eau plasmatique au départ du tubule, mais ce n’est pas vrai pour une substance fortement liée aux protéines.

La charge filtrée est une quantité par unité de temps : DFG multiplié par concentration plasmatique de la fraction filtrable. Un DFG de 100 mL/min et une concentration de 1 mg/mL donnent 100 mg/min. Ne confondez pas cette masse avec 100 mL/min de filtration. Les deux grandeurs utilisent des unités différentes et répondent à deux questions différentes.`],
 ['Forces de filtration et autorégulation',`La pression hydrostatique capillaire favorise la filtration ; la pression dans la capsule et la pression oncotique plasmatique s’y opposent. Le coefficient de filtration traduit la surface et la perméabilité disponibles. Une baisse du débit de filtration peut donc résulter de mécanismes différents, même si la conséquence mesurée paraît identique.

Les résistances artériolaires modifient pression et débit. L’autorégulation associe notamment une réponse myogène et le rétrocontrôle tubuloglomérulaire impliquant la macula densa. Elle limite certaines variations dans une plage de pression, sans rendre le rein indépendant de la circulation. Une vasoconstriction efférente ne doit pas être résumée à un effet constant en toute circonstance : son intensité modifie aussi le débit plasmatique et les forces oncotiques.`],
 ['Tubule proximal et saturation des transports',`Le tubule proximal récupère une grande part du sodium et de l’eau filtrés, ainsi que normalement presque tout le glucose filtré. La Na+/K+-ATPase basolatérale entretient le gradient qui alimente de nombreux transports apicaux. Un cotransport peut donc être actif secondaire sans consommer lui-même directement de l’ATP.

Les transporteurs ont une capacité limitée. Lorsque la charge filtrée de glucose dépasse la capacité de réabsorption, du glucose demeure dans la lumière puis apparaît dans l’urine. Sa présence n’implique pas que le glomérule se soit mis à filtrer sélectivement davantage de glucose. Il faut comparer apport filtré et capacité de récupération. L’eau peut suivre les solutés retenus dans la lumière, ce qui relie transport tubulaire et débit urinaire.`],
 ['Anse, médullaire et concentration de l’urine',`La branche descendante est perméable à l’eau ; la branche ascendante épaisse réabsorbe des sels tout en étant très peu perméable à l’eau. Le liquide tubulaire ne subit donc pas les mêmes échanges dans les deux branches. La répétition de ces différences le long de l’anse contribue à établir un gradient corticopapillaire.

Les vasa recta et l’urée participent au maintien de l’organisation médullaire. Le système collecteur utilise ce gradient lorsque sa perméabilité à l’eau augmente sous l’effet de l’ADH. L’ADH ne fabrique donc pas à elle seule le gradient : elle rend possible son utilisation pour récupérer davantage d’eau. Si le gradient manque ou si le collecteur ne répond pas, une forte concentration d’ADH ne garantit pas une urine concentrée.`],
 ['Clairance : une notion de volume virtuel',`La clairance d’une substance vaut U × V̇ / P : concentration urinaire multipliée par débit urinaire, puis divisée par concentration plasmatique. Le numérateur est un débit d’excrétion en masse par minute. Divisé par une masse par millilitre, il donne un volume de plasma virtuellement épuré par minute.

Pour un marqueur librement filtré, non réabsorbé, non sécrété et sans autre transformation rénale, la clairance estime le DFG. Une clairance plus basse peut traduire une réabsorption nette ; plus haute, une sécrétion nette, si les autres hypothèses sont respectées. La créatinine possède des limites, notamment une sécrétion tubulaire : son interprétation ne doit pas être identifiée à celle d’un marqueur idéal dans toutes les conditions.`],
 ['Eau, sodium, potassium et hormones',`L’ADH augmente notamment l’insertion d’aquaporines dans le collecteur et favorise la récupération d’eau. L’aldostérone agit sur des transports distaux de sodium et de potassium. Réabsorption de sodium et réabsorption d’eau sont liées, mais pas interchangeables : les perméabilités et les gradients déterminent ce qui accompagne effectivement le sodium.

Le système rénine-angiotensine-aldostérone répond à des signaux de perfusion, de sodium tubulaire et de commande sympathique. La concentration plasmatique de sodium représente un rapport entre solutés et eau ; elle n’est pas une mesure directe du stock sodé corporel. Face à une modification de diurèse, précisez si vous raisonnez sur une masse de sodium, un volume d’eau ou une concentration, car leurs variations peuvent différer.`],
 ['Bilan intégré et équilibre acide-base',`Le bilan d’une substance est : excrété = filtré − réabsorbé + sécrété. Si 100 mg/min sont filtrés, 80 réabsorbés et 5 sécrétés, l’excrétion est de 25 mg/min. Si l’urine contient 5 mg/mL de cette substance, ce débit de masse correspond à 5 mL/min d’urine. Cette seconde étape vérifie la distinction entre débit massique et débit volumique.

Le rein contribue aussi au bilan acide-base en récupérant le bicarbonate filtré et en permettant une excrétion nette d’acides, notamment sous forme d’ammonium et d’acidité titrable. Un pH urinaire faible ne mesure pas à lui seul la quantité totale d’acide excrétée : volume et tampons comptent. Devant un exercice, écrivez toujours substance, compartiment, durée et unités avant de choisir une formule.`]
 ]},
 'phys-gas-exchange':{structure:'FMA7309',prerequisites:['Pression et débit','Diffusion','Circulation pulmonaire'],sources:[['Mécanique ventilatoire',ap+'22-3-the-process-of-breathing'],['Échanges gazeux',ap+'22-4-gas-exchange'],['Transport des gaz',ap+'22-5-transport-of-gases']],sections:[
 ['Ventiler, diffuser et perfuser',`La ventilation renouvelle l’air alvéolaire ; la diffusion fait traverser les gaz à la barrière alvéolocapillaire ; la perfusion apporte le sang aux capillaires. Une unité doit recevoir les deux flux et posséder une interface d’échange fonctionnelle. La présence d’un poumon dans l’atlas ne renseigne pas directement sur ces fonctions.

Suivez une molécule d’oxygène : elle atteint une alvéole avec l’air inspiré, franchit la barrière selon un gradient de pression partielle, puis voyage dans le sang principalement liée à l’hémoglobine. Le dioxyde de carbone emprunte le trajet global inverse. Chaque étape peut être limitante indépendamment des autres ; dire « le poumon fonctionne mal » ne suffit donc pas à expliquer le mécanisme d’un exercice.`],
 ['Comment l’air entre dans le thorax',`À l’inspiration calme, le diaphragme se contracte et augmente le volume thoracique. La pression pleurale devient plus négative et favorise l’expansion pulmonaire. La pression alvéolaire devient légèrement inférieure à la pression atmosphérique, ce qui crée le gradient responsable de l’entrée d’air. Le diaphragme ne tire pas directement une colonne d’air jusqu’aux alvéoles.

À la fin de l’inspiration, le débit peut s’annuler alors que le volume pulmonaire est maximal pour ce cycle : les pressions alvéolaire et atmosphérique se sont équilibrées. L’expiration calme repose largement sur le recul élastique après relâchement des muscles inspiratoires. Volume pulmonaire et débit ne culminent donc pas nécessairement au même moment. Sur un tracé, commencez toujours par lire le nom de l’axe vertical.`],
 ['Pression transpulmonaire et compliance',`La pression transpulmonaire est la pression alvéolaire moins la pression pleurale. Elle représente une pression de distension du poumon. La compliance correspond à ΔV/ΔP pour les conditions considérées : à variation de pression identique, un système plus compliant change davantage de volume. La relation peut être non linéaire et dépendre du volume de départ.

La résistance, elle, relie gradient de pression et débit. Une résistance élevée gêne le passage d’air, tandis qu’une compliance faible limite l’expansion. Ces deux anomalies ne sont pas synonymes. Si 0,5 L sont mobilisés pour une variation de pression transpulmonaire de 5 cmH₂O, la compliance moyenne est 0,1 L/cmH₂O sur ce trajet ; ce résultat n’est pas une mesure de résistance bronchique.`],
 ['Surfactant et stabilité alvéolaire',`La surface air-liquide produit une tension qui tend à réduire l’aire de l’interface. Le surfactant, sécrété par les pneumocytes de type II, diminue cette tension et contribue à stabiliser les unités alvéolaires. Le raisonnement de Laplace relie pression, tension et rayon dans une sphère idéale ; une alvéole réelle n’est pas une bulle isolée parfaite.

Le surfactant réduit le travail nécessaire à l’expansion et limite la tendance à la fermeture des petites unités. Il n’agit pas comme un muscle et ne remplace pas la dépression créée par l’inspiration. Distinguez son rôle de celui des pneumocytes de type I, dont la surface fine participe à la barrière d’échange. Structure de la paroi et propriétés de l’interface contribuent à des fonctions complémentaires.`],
 ['Volume courant, espace mort et ventilation utile',`La ventilation minute vaut VT × f. Une partie de chaque volume courant reste dans les voies conductrices et ne renouvelle pas directement les alvéoles échangeuses. Avec un espace mort VD, la ventilation alvéolaire du modèle vaut (VT − VD) × f. Le calcul suppose que les volumes et l’espace mort choisis décrivent la situation étudiée.

Pour VT = 500 mL, VD = 150 mL et f = 12/min, la ventilation minute vaut 6 L/min et la ventilation alvéolaire 4,2 L/min. Avec VT = 250 mL et f = 24/min, la ventilation minute reste 6 L/min mais l’alvéolaire descend à 2,4 L/min. Respirer plus vite n’améliore donc pas nécessairement le renouvellement alvéolaire. Il faut garder le volume courant et l’espace mort dans le raisonnement.`],
 ['Diffusion et transport ne mesurent pas la même chose',`La diffusion dépend notamment du gradient de pression partielle, de la surface, de l’épaisseur de la barrière et des propriétés du gaz. Une barrière épaissie ou une surface réduite peut diminuer le transfert à gradient comparable. La pression partielle concerne le gaz dissous ; le contenu total en oxygène dépend surtout de la quantité d’hémoglobine et de sa saturation.

Une personne ayant moins d’hémoglobine peut donc avoir une pression artérielle en oxygène conservée avec un contenu en oxygène réduit. De même, la saturation est une proportion de sites occupés et non un nombre absolu de molécules transportées. Dans un cas d’anémie, ne concluez pas automatiquement à un défaut de diffusion : commencez par distinguer pression, saturation, concentration d’hémoglobine et contenu.`],
 ['Comprendre les déséquilibres ventilation-perfusion',`Une unité ventilée mais non perfusée contribue à un espace mort alvéolaire : l’air arrive sans débit sanguin suffisant pour les échanges. Une unité perfusée mais non ventilée se comporte comme un shunt intrapulmonaire dans le modèle limite. Les situations intermédiaires sont fréquentes et se décrivent par des rapports V/Q différents.

Un débit d’air total normal n’exclut pas une mauvaise distribution régionale. Additionner deux unités très différentes peut masquer leur inefficacité locale. Le schéma sépare donc arrivée d’air, interface et capillaire. Pour prévoir les conséquences, demandez quel flux manque, puis quel sang quitte l’unité. Ne confondez pas espace mort anatomique des voies conductrices et espace mort physiologique, qui inclut aussi les régions alvéolaires insuffisamment perfusées.`],
 ['Régulation et méthode de résolution',`Les réseaux du tronc cérébral organisent le rythme respiratoire et intègrent des signaux chimiques et mécaniques. La relation entre ventilation alvéolaire et dioxyde de carbone artériel dépend également de la production métabolique de CO₂. À production stable, diminuer la ventilation alvéolaire tend à augmenter la pression artérielle en CO₂. L’effort change plusieurs paramètres simultanément : cette hypothèse ne doit pas être oubliée.

Pour résoudre un exercice, séparez successivement mécanique, renouvellement, diffusion et transport. Écrivez les volumes dans la même unité avant de soustraire VD, puis multipliez par la fréquence. Si une mesure d’oxygène paraît discordante, vérifiez si elle représente pression, saturation ou contenu. Enfin, formulez votre conclusion dans les limites du modèle ; un résultat numérique d’entraînement ne constitue pas l’interprétation clinique complète d’une personne.`]
 ]},
 'embryo-weeks-one-three':{structure:null,prerequisites:['Méiose et fécondation','Polarité cellulaire','Plans anatomiques'],sources:[['Développement embryonnaire',ap+'28-2-embryonic-development'],['Fécondation et segmentation',ap+'28-1-fertilization']],sections:[
 ['Lire une chronologie sans mélanger les horloges',`Les jours utilisés ici sont comptés après la fécondation. Ils ne sont pas identiques aux semaines d’aménorrhée, comptées à partir du premier jour des dernières règles. Dans le modèle obstétrical usuel, les deux comptes diffèrent approximativement de deux semaines, avec une variabilité liée notamment à l’ovulation. Un énoncé doit donc préciser son origine temporelle.

Les étapes ne surviennent pas à la même heure chez tous les embryons. La chronologie sert à organiser les relations : segmentation avant implantation, disque bilaminaire avant gastrulation. Reconnaître l’architecture d’une coupe donne souvent une information plus robuste que mémoriser un jour isolé. Commencez par identifier cavités, couches et populations, puis proposez un stade compatible au lieu de forcer l’image à correspondre à une date exacte.`],
 ['Segmentation, compaction et blastocyste',`Après la fécondation, les divisions de segmentation augmentent le nombre de blastomères alors que le volume global contenu dans la zone pellucide varie peu. Les cellules deviennent donc plus petites. La compaction renforce les contacts et accompagne la distinction entre populations internes et externes. La morula est un ensemble compact ; le blastocyste possède une cavité.

Le blastocyste comporte une masse cellulaire interne, un trophoblaste périphérique et un blastocèle. Dire qu’il est « creux » ne signifie pas qu’il est vide de cellules internes. L’éclosion hors de la zone pellucide permet les interactions ultérieures avec l’endomètre. Dans le dessin, repérez d’abord la couche externe, puis le groupe interne et la cavité : ces positions résument mieux le stade qu’un comptage approximatif des cellules.`],
 ['Implantation et différenciation du trophoblaste',`Le blastocyste s’attache à un endomètre réceptif et s’y implante progressivement. Le trophoblaste se différencie en cytotrophoblaste cellulaire et syncytiotrophoblaste multinucléé. Ce dernier participe à l’invasion et aux interfaces précoces ; l’implantation est une interaction régulée avec les tissus maternels, pas un simple enfouissement mécanique.

Le trophoblaste contribue à des structures extraembryonnaires, notamment placentaires. Il ne constitue pas directement les trois feuillets de l’embryon proprement dit. Le conceptus désigne un ensemble plus large comprenant embryon et annexes. Sur une coupe, de grandes structures périphériques peuvent donc appartenir aux annexes et ne doivent pas être identifiées comme des organes embryonnaires. Cette distinction évite de confondre disque embryonnaire et volume total implanté.`],
 ['Deuxième semaine : deux couches et plusieurs cavités',`La masse interne s’organise en épiblaste et hypoblaste : le disque est bilaminaire. La cavité amniotique est du côté de l’épiblaste, tandis que l’hypoblaste est associé à la face tournée vers la vésicule vitelline. Le mésoderme extraembryonnaire et la cavité choriale complètent l’organisation des annexes.

Ces cavités ont des limites et des devenirs différents. La vésicule vitelline humaine ne doit pas être imaginée comme une réserve volumineuse de jaune comparable à celle d’un œuf d’oiseau. Dans un dessin simplifié, la taille des cavités est pédagogique. Pour vous orienter, nommez les deux faces du disque et rattachez chaque cavité à sa face avant d’apprendre ses transformations. Le disque bilaminaire ne possède pas encore les trois feuillets définitifs de la gastrulation.`],
 ['Gastrulation : suivre une cellule de l’épiblaste',`Au début de la troisième semaine, la ligne primitive organise des mouvements cellulaires. Des cellules de l’épiblaste ingressent ; certaines remplacent l’hypoblaste au niveau de l’embryon et forment l’endoderme définitif. D’autres se placent entre les couches et forment le mésoderme intraembryonnaire. L’épiblaste restant constitue l’ectoderme.

Les trois feuillets définitifs proviennent donc de l’épiblaste. Cette origine commune ne les rend pas équivalents après leur mise en place : position, signaux et interactions orientent leurs devenirs. Le schéma en coupe illustre les migrations et non un empilement de tissus adultes. Une flèche entre couches représente un déplacement de cellules à ce stade ; elle ne signifie pas qu’un organe mature se transforme spontanément en un autre. Distinguer origine, trajet et devenir rend le raisonnement beaucoup plus fiable.`],
 ['Axes, notochorde et mésoderme',`La ligne primitive et les structures axiales participent à l’organisation des axes du corps. La notochorde constitue un repère mésodermique axial et intervient dans des signaux adressés aux tissus voisins. Elle ne doit pas être confondue avec la moelle épinière ni avec le tube neural qui se forme à partir de l’ectoderme neural.

Le mésoderme s’organise notamment en régions para-axiale, intermédiaire et latérale. Le para-axial produit des somites ; l’intermédiaire contribue aux appareils urogénitaux ; le latéral participe aux parois et aux tissus des viscères selon ses subdivisions. Ces associations sont des repères de départ. Elles ne permettent pas d’attribuer un organe complet à une unique origine : épithélium, tissu conjonctif, muscle, vaisseaux et innervation peuvent provenir de populations différentes.`],
 ['Neurulation : plaque, gouttière, tube et crêtes',`L’ectoderme neural s’épaissit en plaque, se replie et forme une gouttière puis un tube. La fermeture progresse et se poursuit au-delà de la troisième semaine. Des cellules des bords constituent les crêtes neurales, se détachent et migrent vers de nombreux territoires. Tube et crêtes sont donc apparentés par leur origine mais distincts par leur trajectoire.

Le tube neural contribue au système nerveux central. Les crêtes neurales contribuent notamment à une grande partie du système nerveux périphérique et à d’autres tissus. La surface ectodermique se referme au-dessus. Sur une coupe, repérez les trois niveaux : surface, structure neurale, axe sous-jacent. Le dessin proposé est une simplification de formes transitoires, sans représentation exhaustive de tous les territoires. Son but est d’éviter la confusion fréquente entre notochorde, tube neural et crêtes neurales.`],
 ['Passer d’une coupe à un raisonnement de développement',`Une coupe unique ne représente qu’un plan et un moment. Deux profils séparés peuvent appartenir à une même structure courbe ; deux tissus voisins peuvent avoir des origines différentes. L’absence d’une structure sur une coupe ne démontre pas son absence dans tout l’embryon. Identifiez toujours le plan, l’orientation et le stade avant de déduire un devenir.

Exercice de méthode : épiblaste et hypoblaste sans ligne primitive évoquent un disque bilaminaire ; des cellules interposées après ingression évoquent la gastrulation. Pour tester une hypothèse, cherchez ensuite un second indice, comme les cavités ou les structures axiales. Les frises et schémas sont des aides de reconstruction, non des images à réciter. Une perturbation du développement s’interprète selon la population et la période affectées ; le seul nom d’un feuillet ne suffit pas à prévoir toutes ses conséquences.`]
 ]},
 'immuno-adaptive':{structure:null,prerequisites:['Cellules de l’immunité innée','Protéines et récepteurs','Communication cellulaire'],sources:[['Présentation et lymphocytes T',mi+'18-3-t-lymphocytes-and-cellular-immunity'],['Lymphocytes B et anticorps',mi+'18-4-b-lymphocytes-and-humoral-immunity'],['Vaccination et mémoire',mi+'18-5-vaccines']],sections:[
 ['Un répertoire avant la rencontre',`Le système adaptatif possède de nombreux clones de lymphocytes dont les récepteurs diffèrent. Leur diversité se construit avant la première rencontre avec un antigène donné, notamment par réarrangements de segments génétiques. L’antigène sélectionne des clones compatibles ; il ne dessine pas un nouveau récepteur sur mesure dans chaque cellule.

Un clone activé peut proliférer, augmentant le nombre de cellules portant une reconnaissance apparentée. Expansion clonale et diversification initiale sont donc deux phénomènes distincts. Cette diversité crée aussi la possibilité de reconnaître le soi, ce qui exige des mécanismes de tolérance. Pour comprendre une réponse, suivez successivement récepteur, antigène, signaux d’activation, multiplication puis fonction effectrice. Sauter directement du contact à l’élimination masque les étapes sur lesquelles portent de nombreux exercices.`],
 ['BCR et TCR ne voient pas la même cible',`Le récepteur B, ou BCR, peut reconnaître un antigène sous sa forme native, selon l’accessibilité de l’épitope. Le récepteur T, ou TCR, reconnaît classiquement un peptide associé à une molécule de CMH. Un antigène libre flottant près d’un lymphocyte T ne constitue donc pas, à lui seul, son mode habituel de reconnaissance.

Dans le schéma de base, les T CD4 reconnaissent des peptides associés au CMH II et les T CD8 des peptides associés au CMH I. Le corécepteur contribue à cette interaction sans remplacer le TCR. Il faut distinguer le peptide, la molécule qui le présente et le récepteur qui le reconnaît. Les formes colorées du dessin représentent ces rôles moléculaires ; leur taille et leur forme sont symboliques, pas des structures atomiques.`],
 ['Présenter un antigène et rejoindre un lymphocyte naïf',`Les cellules dendritiques captent des antigènes dans les tissus et peuvent rejoindre les organes lymphoïdes secondaires. Elles y présentent des peptides à des lymphocytes naïfs, avec des signaux liés au contexte de la capture. Le CMH I présente classiquement des peptides provenant de protéines intracellulaires ; le CMH II présente classiquement des peptides issus de matériel internalisé.

Ces règles générales admettent des mécanismes spécialisés, notamment la présentation croisée. Il est donc préférable de dire « voie classique » plutôt que « toujours et exclusivement ». La capture seule ne démontre pas que la cellule provoquera une réponse identique dans tous les contextes. Localisation, maturation de la cellule présentatrice et signaux inflammatoires influencent la rencontre. Le trajet tissulaire explique pourquoi reconnaissance et activation ne se produisent pas nécessairement au même endroit que l’agression initiale.`],
 ['Trois catégories de signaux d’activation',`La reconnaissance peptide-CMH fournit le signal antigénique. Des interactions de co-stimulation et des cytokines complètent l’activation et orientent la différenciation. Pour un lymphocyte T naïf, la reconnaissance isolée ne garantit pas une expansion productive. Selon le contexte, une absence de signaux appropriés peut favoriser un état de non-réponse ou d’autres mécanismes de tolérance.

Les cytokines ne sont pas des instructions indépendantes du récepteur : leur effet dépend des récepteurs exprimés et de l’état de la cellule. Le résultat se comprend donc comme une combinaison de signaux. Dans un exercice où une molécule de co-stimulation est bloquée, ne concluez pas que le TCR a forcément cessé de reconnaître le peptide. La reconnaissance peut persister alors que l’activation complète est perturbée.`],
 ['Du lymphocyte B au plasmocyte',`Après reconnaissance de l’antigène, un lymphocyte B peut l’internaliser et présenter des peptides. Dans de nombreuses réponses à des antigènes protéiques, une aide de lymphocytes T folliculaires favorise prolifération et différenciation. Une partie des cellules devient plasmocytes, spécialisés dans la sécrétion d’anticorps ; une autre contribue à la mémoire.

Un anticorps est une protéine, et non une cellule. Sa fixation peut neutraliser une cible, faciliter la phagocytose par opsonisation ou participer à l’activation du complément selon sa classe et le contexte. Il ne « mange » pas directement une bactérie. Pour chaque fonction, nommez le lien entre reconnaissance et mécanisme : la fixation identifie une cible, puis les parties effectrices et leurs partenaires réalisent l’action. Le dessin distingue ainsi la cellule sécrétrice des immunoglobulines qu’elle libère.`],
 ['Classe, affinité et fonctions des anticorps',`La commutation de classe modifie la région constante de la chaîne lourde et donc certaines fonctions effectrices, tout en conservant initialement la reconnaissance portée par les régions variables. La maturation d’affinité repose sur des variations des régions variables et une sélection des cellules présentant des propriétés de liaison avantageuses. Ces processus peuvent se produire dans un même contexte de réponse mais ne désignent pas la même opération.

Les IgM sont souvent importantes au début d’une réponse primaire ; les IgG participent à de nombreuses réponses systémiques, les IgA aux surfaces muqueuses et les IgE à des mécanismes particuliers impliquant notamment mastocytes et parasites. Ce tableau ne signifie pas qu’une classe possède une seule fonction exclusive. Devant un résultat, séparez quantité d’anticorps, classe, affinité et capacité fonctionnelle : aucune de ces mesures ne remplace toutes les autres.`],
 ['Effecteurs T et contrôle des cellules cibles',`Des lymphocytes T CD4 coordonnent les réponses par contacts et cytokines. Des T CD8 activés peuvent reconnaître des cellules présentant un peptide cible sur CMH I, puis diriger une réponse cytotoxique. Des voies impliquant perforine et granzymes, ou des récepteurs de mort, favorisent la mort de la cellule cible.

La cytotoxicité cellulaire ne se confond pas avec la neutralisation d’une particule extracellulaire par un anticorps. Une cellule infectée peut constituer une cible alors que le microorganisme est caché à l’intérieur. La spécificité du contact contribue à limiter les atteintes, mais la réponse immunitaire peut aussi causer des lésions. L’intensité utile dépend du contexte ; une réponse plus forte n’est pas automatiquement une réponse meilleure. Distinguez toujours destruction de la cible, recrutement d’autres cellules et contrôle de l’inflammation.`],
 ['Contraction, mémoire et tolérance',`Après élimination ou diminution de la stimulation, une grande partie des effecteurs disparaît : c’est la contraction. Des cellules mémoire et certains plasmocytes de longue durée persistent. Une réponse secondaire peut être plus rapide, plus intense ou de meilleure affinité, sans imposer un maintien permanent de tous les effecteurs au maximum.

La vaccination vise à préparer une protection et une mémoire contre une cible, avec une efficacité et une durée variables selon le vaccin et l’hôte. La tolérance centrale agit pendant le développement des lymphocytes ; la tolérance périphérique complète les contrôles après leur sortie. Pour résoudre un cas de rappel antigénique, distinguez ce qui persiste avant l’exposition, ce qui prolifère ensuite et ce qui réalise effectivement la protection. La présence d’une mémoire ne garantit ni une protection absolue ni une absence de toute infection.`]
 ]}
}

export function refineFlagship(course:Course):Course {
 const chapter=flagshipChapters[course.id];if(!chapter)return course
 const sections=chapter.sections.map(([title,text])=>({title,text}))
 const readingMinutes=Math.ceil(sections.map(s=>s.text).join(' ').split(/\s+/).length/180)
 return {...course,sections,structure:chapter.structure,prerequisites:chapter.prerequisites,readingMinutes,minutes:readingMinutes+12,sources:chapter.sources.map(([label,url])=>({label,url})),source:chapter.sources[0][1]}
}
