import type {Question} from './questions'
type Choice=[text:string,correct:boolean,reason:string]
type Exercise=[prompt:string,choices:Choice[]]
// QCM rédigés individuellement. Le rang des options et la correction restent stables.
const bank:Record<string,Exercise[]>={
 'phys-cardiac-cycle':[
 ['Pendant la contraction isovolumétrique du ventricule gauche :', [['La mitrale est fermée',true,'La pression ventriculaire a dépassé la pression atriale.'],['La valve aortique est ouverte',false,'Elle reste fermée tant que la pression ventriculaire est inférieure à la pression aortique.'],['Le volume ventriculaire est constant',true,'Dans le modèle sans fuite, les deux issues sont fermées.']]],
 ['Quels événements déclenchent normalement un mouvement valvulaire ?', [['La pression ventriculaire dépasse la pression aortique : ouverture aortique',true,'Le gradient devient favorable à l’éjection.'],['La pression ventriculaire passe sous la pression atriale : fermeture mitrale',false,'Ce gradient ouvre la mitrale et permet le remplissage.'],['La pression aortique dépasse la pression ventriculaire : fermeture aortique',true,'Le gradient inversé favorise la fermeture.']]],
 ['Sur une boucle pression-volume, identifiez les grandeurs.', [['La hauteur est le volume éjecté',false,'La hauteur correspond à un écart de pression.'],['La largeur est VTD moins VTS',true,'Cet écart de volume est le volume d’éjection systolique.'],['L’aire représente le travail mécanique externe par cycle',true,'Elle correspond à l’intégrale de pression par variation de volume.']]],
 ['À propos du remplissage ventriculaire :', [['Il dépend uniquement de la systole atriale',false,'Le remplissage passif précède et complète l’apport atrial.'],['La compliance influence la pression nécessaire pour recevoir un volume',true,'Une compliance faible implique une plus forte augmentation de pression.'],['Il commence lorsque la mitrale s’ouvre',true,'Le gradient atrioventriculaire autorise alors l’entrée de sang.']]],
 ['Distinguez activité électrique et mécanique.', [['Le QRS précède la contraction ventriculaire',true,'Il représente la dépolarisation qui déclenche le couplage mécanique.'],['L’onde P mesure directement la pression atriale',false,'Elle décrit une activité électrique, pas une pression.'],['L’onde T est associée à la repolarisation ventriculaire',true,'La relaxation mécanique suit les événements électriques.']]],
 ['Dans une circulation adulte stable :', [['Les ventricules droit et gauche ont le même débit moyen',true,'Ils sont disposés en série.'],['Ils doivent développer la même pression',false,'Les résistances pulmonaires et systémiques diffèrent.'],['Une pression plus élevée suffit à démontrer un débit plus élevé',false,'Le débit dépend aussi de la résistance du circuit.']]],
 ['Cas : VTD 140 mL, VTS 60 mL, fréquence 60/min. Quels résultats sont exacts ?', [['Le volume éjecté est 200 mL',false,'Il faut soustraire : 140 − 60 = 80 mL.'],['Le débit est 4,8 L/min',true,'80 × 60 = 4 800 mL/min.'],['La fraction d’éjection est environ 57 %',true,'80/140 × 100 ≈ 57 %.']]],
 ['Deux ventricules ont une fraction d’éjection de 50 %, avec VTD de 80 et 140 mL. À fréquence identique :', [['Ils éjectent le même volume',false,'Les volumes sont 40 et 70 mL.'],['Le second a un débit supérieur',true,'La fréquence identique multiplie un VES plus grand.'],['La fraction seule ne détermine pas le débit',true,'Il faut connaître volume et fréquence.']]],
 ['Sur un battement, la postcharge augmente isolément, à VTD et contractilité comparables.', [['Le VTS tend à augmenter',true,'Une plus grande contrainte s’oppose à l’éjection.'],['Le VES augmente obligatoirement',false,'Un VTS plus élevé à VTD constant réduit le VES.'],['La valve aortique s’ouvre à une pression ventriculaire plus élevée',true,'Le ventricule doit dépasser la nouvelle pression aortique.']]],
 ['Une tachycardie passe de 75 à 150/min et le VES de 70 à 35 mL. Quel raisonnement est juste ?', [['Le débit a doublé',false,'75 × 70 et 150 × 35 donnent tous deux 5 250 mL/min.'],['Le débit calculé reste identique',true,'La division du VES compense le doublement de fréquence.'],['La fréquence seule ne permettait pas de prévoir le débit',true,'Il fallait connaître le VES associé.']]],
 ['Une boucle conserve VTD 120 mL mais son VTS passe de 50 à 40 mL, fréquence inchangée.', [['La largeur augmente de 10 mL',true,'Le VES passe de 70 à 80 mL.'],['La fraction d’éjection diminue',false,'Elle passe d’environ 58 % à 67 %.'],['Cela prouve à lui seul une hausse de contractilité',false,'Un changement de charge peut aussi modifier le VTS.']]],
 ['Cas de raisonnement : ventricule peu compliant et pression de remplissage élevée.', [['Le VTD est forcément très grand',false,'Une pression élevée peut accompagner un volume modéré si la compliance est faible.'],['Il faut examiner la relation pression-volume',true,'Elle explique le coût en pression d’un volume reçu.'],['Précharge et pression de remplissage sont des concepts strictement interchangeables',false,'La pression est un indicateur dépendant aussi des propriétés de paroi.']]]
 ],
 'phys-renal':[
 ['Associez chaque transport à son sens.', [['Réabsorption : tubule vers sang',true,'Elle retire une substance du liquide tubulaire.'],['Sécrétion : tubule vers sang',false,'La sécrétion va du sang vers le tubule.'],['Filtration : capillaires glomérulaires vers capsule',true,'C’est l’entrée initiale du filtrat.']]],
 ['Concernant la charge filtrée :', [['Elle s’exprime nécessairement en mL/min',false,'C’est une quantité de substance par temps, par exemple mg/min.'],['Elle dépend du DFG et de la concentration filtrable',true,'Charge = DFG × concentration plasmatique filtrable.'],['Toute protéine plasmatique traverse librement',false,'La barrière retient la majeure partie des protéines.']]],
 ['Quel mécanisme explique l’apparition urinaire de glucose lorsque sa charge filtrée devient élevée ?', [['Une saturation de la récupération tubulaire peut intervenir',true,'Les transporteurs ont une capacité maximale.'],['Le glucose était totalement absent du filtrat normal',false,'Il est filtré puis normalement récupéré.'],['La seule glucosurie prouve une fuite de protéines glomérulaire',false,'Un défaut ou dépassement de transport tubulaire suffit.']]],
 ['Comparez les branches de l’anse de Henle.', [['La descendante est perméable à l’eau',true,'Le gradient interstitiel peut y attirer de l’eau hors du tubule.'],['La branche ascendante épaisse récupère des sels',true,'Elle contribue au gradient médullaire.'],['L’eau suit librement ces sels dans la branche ascendante épaisse',false,'Ce segment est très peu perméable à l’eau.']]],
 ['L’ADH et l’aldostérone :', [['Ont exactement la même cible moléculaire',false,'L’ADH module notamment les aquaporines ; l’aldostérone des transports ioniques distaux.'],['Peuvent coopérer sur les bilans hydrosodés',true,'Leurs mécanismes distincts participent à la régulation intégrée.'],['L’ADH augmente la perméabilité à l’eau du collecteur',true,'Son effet dépend également du gradient médullaire.']]],
 ['Pour qu’une clairance mesure le DFG d’un marqueur idéal :', [['Le marqueur doit être librement filtré',true,'La charge filtrée doit correspondre au produit DFG × concentration plasmatique.'],['Il doit être fortement sécrété',false,'Cela ferait dépasser le DFG à sa clairance.'],['Il ne doit être ni réabsorbé ni sécrété',true,'Son excrétion doit égaler sa filtration.']]],
 ['100 mg/min filtrés, 80 réabsorbés et 5 sécrétés. Choisissez les conclusions.', [['L’excrétion vaut 25 mg/min',true,'100 − 80 + 5 = 25.'],['L’excrétion vaut 15 mg/min',false,'La sécrétion doit être ajoutée, pas retranchée.'],['Le débit urinaire vaut obligatoirement 25 mL/min',false,'Il manque la concentration urinaire pour convertir masse en volume.']]],
 ['Ux = 30 mg/mL, Px = 2 mg/mL, débit urinaire = 2 mL/min.', [['La clairance est 30 mL/min',true,'30 × 2 / 2 = 30 mL/min.'],['Le débit excrété est 60 mg/min',true,'Ux × débit urinaire = 30 × 2.'],['La clairance est 2 mg/min',false,'Une clairance est un volume par temps, pas une masse par temps.']]],
 ['Un marqueur librement filtré a une clairance de 40 mL/min pour un DFG de 100 mL/min, sans métabolisme rénal.', [['Une réabsorption nette est compatible',true,'La quantité excrétée est inférieure à la quantité filtrée.'],['Une sécrétion nette isolée explique le résultat',false,'Elle augmenterait la clairance au-dessus du DFG.'],['Le rein ne filtre plus du tout',false,'Le DFG donné est de 100 mL/min.']]],
 ['L’urine reste diluée malgré une ADH élevée. Quel raisonnement convient ?', [['Une réponse insuffisante du collecteur est possible',true,'La présence de l’hormone ne garantit pas l’action sur la cible.'],['Un gradient médullaire insuffisant est possible',true,'La perméabilité seule ne crée pas un gradient osmotique.'],['L’ADH élevée impose nécessairement une urine concentrée',false,'Il faut une cible fonctionnelle et un gradient utilisable.']]],
 ['DFG 100 mL/min et glucose plasmatique librement filtrable 1 mg/mL.', [['La charge filtrée est 100 mg/min',true,'100 mL/min × 1 mg/mL.'],['Tout ce glucose est obligatoirement excrété',false,'La réabsorption modifie la quantité finale.'],['La filtration correspond à 144 L/jour',true,'100 × 1 440 = 144 000 mL/jour. Ce volume n’est pas la diurèse.']]],
 ['Deux urines ont le même pH mais des volumes et contenus en tampons différents.', [['Elles excrètent nécessairement la même quantité d’acide',false,'Le pH seul n’intègre ni volume ni acidité portée par les tampons.'],['L’ammonium contribue à l’excrétion acide',true,'C’est une voie importante d’excrétion nette d’acide.'],['Le débit et les tampons sont nécessaires au bilan',true,'Un bilan de quantité ne se déduit pas d’une seule concentration en protons libres.']]]
 ],
 ventilation:[
 ['Pendant une inspiration calme :', [['La pression pleurale devient plus négative',true,'La contraction inspiratoire augmente le volume thoracique.'],['L’air entre quand la pression alvéolaire dépasse l’atmosphère',false,'Il entre lorsque la pression alvéolaire est inférieure.'],['Le diaphragme participe à la variation de volume',true,'Sa contraction agrandit la cavité thoracique.']]],
 ['En fin d’inspiration calme, le débit peut être nul parce que :', [['Les pressions alvéolaire et atmosphérique sont égales',true,'Il n’y a plus de gradient entraînant le flux.'],['Le poumon ne contient plus d’air',false,'Le volume est élevé à ce moment du cycle.'],['Volume et débit sont des grandeurs distinctes',true,'Un volume présent n’implique pas un mouvement instantané.']]],
 ['La compliance pulmonaire :', [['Se calcule comme ΔV/ΔP',true,'Il s’agit d’une distensibilité dans les conditions mesurées.'],['Est identique à la résistance bronchique',false,'La résistance relie pression et débit.'],['Peut varier selon le volume initial',true,'La relation pression-volume peut être non linéaire.']]],
 ['Le surfactant :', [['Est produit notamment par les pneumocytes de type II',true,'Ces cellules assurent cette sécrétion.'],['Augmente la tension superficielle',false,'Il la diminue.'],['Remplace la contraction du diaphragme',false,'Il facilite l’expansion sans créer à lui seul le gradient ventilatoire.']]],
 ['Distinguez les mesures liées à l’oxygène.', [['La saturation est une proportion',true,'Elle décrit la fraction de sites de liaison occupés.'],['La pression partielle mesure tout l’oxygène lié à l’hémoglobine',false,'Elle concerne le gaz dissous.'],['Le contenu dépend de la concentration d’hémoglobine',true,'Une grande partie de l’oxygène sanguin y est liée.']]],
 ['À propos de ventilation et perfusion :', [['Une unité ventilée non perfusée contribue à l’espace mort',true,'L’air atteint une zone sans flux sanguin utile.'],['Une unité perfusée non ventilée correspond au modèle limite d’un shunt',true,'Le sang traverse sans renouvellement alvéolaire.'],['Une ventilation totale normale prouve une distribution régionale normale',false,'Des régions très différentes peuvent donner un total normal.']]],
 ['VT 400 mL, VD 150 mL et fréquence 20/min. Quels calculs sont justes ?', [['Ventilation minute : 8 L/min',true,'400 × 20 = 8 000 mL/min.'],['Ventilation alvéolaire : 5 L/min',true,'(400 − 150) × 20 = 5 000 mL/min.'],['Ventilation alvéolaire : 11 L/min',false,'Ce résultat ajoute l’espace mort au lieu de le soustraire.']]],
 ['Comparez A : VT 500, VD 150, f 12 ; B : VT 250, VD 150, f 24, volumes en mL.', [['Les ventilations minutes sont égales',true,'Les deux produits VT × f valent 6 L/min.'],['B renouvelle davantage les alvéoles',false,'B donne 2,4 L/min contre 4,2 pour A.'],['Le rythme plus rapide ne garantit pas une meilleure ventilation utile',true,'Le volume courant et l’espace mort modifient le résultat.']]],
 ['Un poumon gagne 0,5 L pour une augmentation de pression transpulmonaire de 5 cmH₂O.', [['La compliance moyenne vaut 0,1 L/cmH₂O',true,'0,5 / 5 = 0,1.'],['La résistance vaut 0,1 L/cmH₂O',false,'Aucun débit n’est fourni ; l’unité est celle d’une compliance.'],['Cette pente est forcément identique à tous les volumes',false,'La relation peut être non linéaire.']]],
 ['Cas : hémoglobine diminuée, pression artérielle en O₂ conservée.', [['Le contenu en O₂ peut être diminué',true,'Il dépend fortement de la quantité d’hémoglobine.'],['La pression conservée exclut un manque de transport d’O₂',false,'Pression et contenu sont distincts.'],['Cela prouve un épaississement de la barrière',false,'Une baisse d’hémoglobine n’est pas une mesure de diffusion.']]],
 ['La barrière alvéolocapillaire s’épaissit, à surface et gradients comparables.', [['La diffusion peut diminuer',true,'L’épaisseur est un obstacle au transfert.'],['La ventilation minute doit forcément être nulle',false,'La mécanique ventilatoire peut persister.'],['Diffusion et ventilation doivent être évaluées séparément',true,'Une atteinte d’interface n’identifie pas le débit d’air.']]],
 ['À production de CO₂ stable, la ventilation alvéolaire diminue.', [['La pression artérielle en CO₂ tend à augmenter',true,'L’élimination ventilatoire est moindre à production inchangée.'],['La production métabolique est sans importance pour ce raisonnement',false,'L’hypothèse de production stable est nécessaire.'],['Augmenter la fréquence suffit toujours à corriger la baisse',false,'Une diminution du volume courant peut annuler le gain de fréquence.']]]
 ],
 'embryo-weeks-one-three':[
 ['Au cours de la segmentation précoce :', [['Le nombre de blastomères augmente',true,'Les divisions subdivisent le volume initial.'],['Le volume global double à chaque division',false,'Il varie peu au début dans la zone pellucide.'],['La taille moyenne des cellules diminue',true,'Davantage de cellules partagent un volume global comparable.']]],
 ['Un blastocyste comporte :', [['Un trophoblaste périphérique',true,'Il est distinct de la masse cellulaire interne.'],['Une cavité appelée blastocèle',true,'C’est un repère du stade blastocyste.'],['Déjà les trois feuillets définitifs',false,'Ils apparaissent lors de la gastrulation.']]],
 ['Le disque bilaminaire :', [['Comprend épiblaste et hypoblaste',true,'Ces deux populations organisent la deuxième semaine.'],['Comprend seulement mésoderme et ectoderme',false,'Ce ne sont pas les deux couches initiales.'],['Précède la gastrulation',true,'La gastrulation établit ensuite les trois feuillets.']]],
 ['Les trois feuillets embryonnaires définitifs proviennent :', [['Du trophoblaste exclusivement',false,'Il contribue aux interfaces et annexes.'],['De l’épiblaste',true,'Ingression et maintien en surface répartissent ses cellules.'],['De la fusion de trois tissus adultes',false,'Les populations sont embryonnaires et se différencient ensuite.']]],
 ['Distinguez notochorde et tube neural.', [['La notochorde est un axe mésodermique',true,'Elle participe à l’organisation et aux signaux axiaux.'],['Le tube neural dérive de l’ectoderme neural',true,'La plaque se replie pour former le tube.'],['La notochorde devient directement la moelle épinière',false,'La moelle dérive du tube neural.']]],
 ['Concernant tube neural et crêtes neurales :', [['Les crêtes migrent vers plusieurs territoires',true,'Leurs devenirs dépassent une simple paroi du tube.'],['Le tube contribue au système nerveux central',true,'C’est un repère majeur de son devenir.'],['Leur fermeture et migration sont terminées avant toute gastrulation',false,'La neurulation s’engage après la mise en place des axes et se poursuit ensuite.']]],
 ['Une coupe montre deux couches, une cavité du côté épiblastique, sans ligne primitive. Quelle interprétation est fondée ?', [['Une organisation bilaminaire est compatible',true,'Épiblaste et hypoblaste précèdent le disque trilaminaire.'],['La gastrulation est démontrée par la seule présence d’une cavité',false,'Une cavité n’établit pas l’existence des trois feuillets.'],['Il faut chercher d’autres indices avant de donner un jour exact',true,'Plan de coupe et variabilité limitent une datation précise.']]],
 ['On suit une cellule épiblastique qui ingresse et remplace l’hypoblaste dans le disque.', [['Elle peut participer à l’endoderme définitif',true,'Ce trajet établit la couche endodermique embryonnaire.'],['Elle prouve que l’hypoblaste produit seul les trois feuillets',false,'La cellule suivie vient de l’épiblaste.'],['Son origine et sa position finale doivent être distinguées',true,'Le déplacement change ses relations aux autres cellules.']]],
 ['Un schéma numérote « troisième semaine après fécondation ». Un autre utilise les semaines d’aménorrhée.', [['Les numéros sont automatiquement interchangeables',false,'Les origines de comptage diffèrent.'],['Il faut vérifier l’origine temporelle',true,'L’une part de la fécondation, l’autre des dernières règles.'],['Un décalage approximatif de deux semaines est usuel',true,'C’est un repère conventionnel soumis à la variabilité de l’ovulation.']]],
 ['La notochorde n’apparaît pas sur une coupe latérale. Peut-on conclure ?', [['Elle est absente de tout l’embryon',false,'La coupe peut simplement ne pas traverser l’axe.'],['Il faut connaître le plan et la position de coupe',true,'La visibilité dépend de l’intersection avec la structure.'],['D’autres coupes peuvent tester l’hypothèse',true,'Une série permet de reconstruire une organisation volumique.']]],
 ['Un tableau attribue tout un organe digestif à l’endoderme.', [['Il peut être trop simplificateur',true,'L’épithélium, la paroi, les vaisseaux et les nerfs ont des contributions différentes.'],['Tous les vaisseaux de cet organe sont donc endodermiques',false,'L’origine de l’épithélium ne détermine pas celle de tout l’organe.'],['Il faut distinguer ses tissus constitutifs',true,'Les devenirs embryologiques portent sur des populations définies.']]],
 ['Des cellules des crêtes neurales migrent après leur détachement. Quelle conclusion est correcte ?', [['Elles sont nécessairement issues du trophoblaste',false,'Elles sont liées à la région ectodermique neurale.'],['Leur voisinage initial ne fixe pas leur position finale',true,'La migration modifie leurs rapports anatomiques.'],['Elles ne doivent pas être assimilées au tube neural entier',true,'Tube et crêtes ont des trajets et devenirs différents.']]]
 ],
 'immuno-adaptive':[
 ['Dans la sélection clonale :', [['Les récepteurs existent avant la rencontre considérée',true,'L’antigène sélectionne des clones compatibles dans un répertoire.'],['L’antigène dessine chaque nouveau récepteur',false,'Ce n’est pas le mécanisme de la sélection clonale.'],['Les clones activés peuvent proliférer',true,'L’expansion augmente le nombre d’effecteurs potentiels.']]],
 ['Associez reconnaissance et récepteur.', [['BCR : antigène natif accessible',true,'Le BCR peut reconnaître la forme native.'],['TCR classique : peptide associé au CMH',true,'Le peptide est présenté à la cellule T.'],['TCR : uniquement anticorps libre',false,'Le TCR ne reconnaît pas classiquement une immunoglobuline libre comme signal d’activation.']]],
 ['Dans le schéma classique de présentation :', [['CMH I avec T CD8',true,'CD8 accompagne la reconnaissance de peptide-CMH I.'],['CMH II avec T CD4',true,'CD4 accompagne la reconnaissance de peptide-CMH II.'],['CD4 remplace entièrement le TCR',false,'Le corécepteur ne remplace pas la spécificité du TCR.']]],
 ['Pour un lymphocyte T naïf :', [['Reconnaître un peptide garantit toujours une activation complète',false,'Co-stimulation et contexte cytokiniques interviennent.'],['Des cytokines orientent la différenciation',true,'Leur effet dépend des récepteurs et de l’état de la cellule.'],['Reconnaissance et co-stimulation sont deux notions distinctes',true,'On peut préserver l’une tout en perturbant l’autre.']]],
 ['Anticorps et plasmocytes :', [['Le plasmocyte est une cellule sécrétrice',true,'Il est issu de la différenciation de lymphocytes B.'],['Un anticorps phagocyte lui-même les bactéries',false,'Il peut favoriser la phagocytose réalisée par une cellule.'],['Un anticorps peut neutraliser une cible',true,'Sa fixation peut bloquer une interaction nécessaire à l’action de la cible.']]],
 ['Distinguez commutation de classe et maturation d’affinité.', [['La commutation modifie la région constante de la chaîne lourde',true,'Elle modifie certaines fonctions effectrices.'],['La maturation d’affinité implique sélection de propriétés de liaison',true,'Des modifications variables et une sélection contribuent au processus.'],['Ce sont deux noms de la même modification moléculaire',false,'Ils portent sur des régions et des conséquences différentes.']]],
 ['Une co-stimulation est bloquée alors que peptide-CMH et TCR peuvent encore se lier.', [['L’activation complète du T naïf peut diminuer',true,'Le signal antigénique seul peut être insuffisant.'],['La reconnaissance du peptide est forcément abolie',false,'Le cas précise qu’elle reste possible.'],['Les étapes du mécanisme doivent être distinguées',true,'Le blocage agit ici après ou avec la reconnaissance, pas nécessairement sur la liaison.']]],
 ['Une cellule infectée présente un peptide viral sur CMH I à un T CD8 activé.', [['Une réponse cytotoxique ciblée est possible',true,'C’est une fonction effectrice des T CD8.'],['Il s’agit obligatoirement d’une phagocytose par l’anticorps',false,'Ni la cellule effectrice ni le mécanisme ne correspondent.'],['Le pathogène doit toujours être libre hors de la cellule',false,'La présentation permet de repérer une infection intracellulaire.']]],
 ['Lors d’un rappel antigénique, une réponse est plus rapide que la première.', [['Une population mémoire peut contribuer',true,'Des cellules persistent après la réponse initiale.'],['Tous les effecteurs ont forcément été maintenus au maximum',false,'La mémoire persiste malgré la contraction d’une grande partie des effecteurs.'],['Cela démontre une protection absolue contre toute infection',false,'La mémoire n’implique pas une efficacité absolue.']]],
 ['Un anticorps passe d’une classe à une autre, avec reconnaissance variable conservée.', [['Ses fonctions effectrices peuvent changer',true,'Elles dépendent en partie de la région constante.'],['Sa cible doit forcément devenir entièrement différente',false,'La commutation ne remplace pas à elle seule les régions variables.'],['La classe seule décrit toute son affinité',false,'Classe et affinité sont des propriétés distinctes.']]],
 ['Une cellule dendritique capte un antigène dans un tissu puis migre vers un ganglion.', [['Capture et rencontre du T naïf peuvent être spatialement séparées',true,'La migration relie tissu et organe lymphoïde secondaire.'],['L’antigène capté garantit le même type de réponse dans tous les contextes',false,'Maturation et signaux associés modulent la réponse.'],['La présentation n’est qu’une étape de l’activation',true,'Il faut aussi prendre en compte co-stimulation et cytokines.']]],
 ['Après élimination de l’antigène, beaucoup d’effecteurs disparaissent.', [['C’est compatible avec une contraction normale de réponse',true,'La population effectrice diminue après la stimulation.'],['Cela prouve l’absence de toute mémoire',false,'Des cellules mémoire et plasmocytes durables peuvent subsister.'],['Les contrôles de tolérance restent utiles',true,'Ils limitent les réponses inappropriées contre le soi.']]]
 ]}

export const flagshipQuestions:Question[]=Object.entries(bank).flatMap(([course,exercises])=>exercises.map(([prompt,choices],i)=>({
 id:`revision2-${course}-${i+1}`,course,topic:'',prompt,options:choices.map(c=>c[0]),correct:choices.flatMap((c,index)=>c[1]?[index]:[]),why:choices.map(c=>c[2]),difficulty:i<6?'essentiel':'application'
})))
export const flagshipQuestionCourses=new Set(Object.keys(bank))
