import {breastSupport} from './breastCourse'
import {reasoningQuestions} from './reasoningQuestions'
import {chapterQuestions} from './chapterQuestions'
import {courses} from './curriculum'
import {skeletalQuestions} from './skeletalCourses'
import {systemQuestions} from './systemCourses'
import {regionalSupport} from './regionalCourses'
import {reproductiveSupport} from './reproductiveCourses'
import {regionalSystemSupport} from './regionalSystems'
import {scienceSupport} from './scienceCourses'
import {firstYearSupport} from './firstYearExpansion'
export type Question={id:string;course:string;topic:string;prompt:string;options:string[];correct:number[];why:string[];difficulty?:'essentiel'|'application';format?:'boolean'}
const questionCatalog:Question[]=[...reasoningQuestions,...chapterQuestions,...skeletalQuestions,...systemQuestions,...regionalSupport.questions,...reproductiveSupport.questions,...scienceSupport.questions,...firstYearSupport.questions,...regionalSystemSupport.questions,...breastSupport.questions,
 {id:'orientation-1',course:'orientation',topic:'Anatomie',prompt:'Quels plans sont correctement associés ?',options:['Sagittal : droite / gauche','Frontal : haut / bas','Transversal : avant / arrière','Frontal : avant / arrière'],correct:[0,3],why:['Le plan sagittal sépare les côtés.','Cette séparation est transversale.','Le transversal sépare le haut et le bas.','Le plan frontal est aussi appelé coronal.']},
 {id:'orientation-2',course:'orientation',topic:'Anatomie',prompt:'Concernant les repères anatomiques :',options:['La droite est celle du sujet','Distal signifie proche du tronc','Le coude est proximal au poignet','Médial signifie vers le plan médian'],correct:[0,2,3],why:['Le point de vue reste celui du sujet.','Distal signifie plus éloigné de l’attache.','Il est plus proche de l’attache.','Médial s’oppose à latéral.']},
 {id:'homeostasis-1',course:'homeostasis',topic:'Physiologie',prompt:'Une boucle de régulation comprend :',options:['Un capteur','Un centre intégrateur','Un effecteur','Obligatoirement un organe unique'],correct:[0,1,2],why:['Il détecte la variation.','Il organise la réponse.','Il réalise la réponse.','Plusieurs structures peuvent participer.']},
 {id:'homeostasis-2',course:'homeostasis',topic:'Physiologie',prompt:'À propos des rétrocontrôles :',options:['Le négatif limite l’écart','Le positif amplifie le changement','Négatif signifie dangereux','Une variable régulée ne varie jamais'],correct:[0,1],why:['La réponse s’oppose à la perturbation.','Il renforce le processus initial.','Le terme indique un sens.','L’équilibre est dynamique.']},
 {id:'membrane-1',course:'membrane',topic:'Biologie cellulaire',prompt:'La diffusion facilitée :',options:['Utilise une protéine','Est un transport passif','Impose une hydrolyse directe d’ATP','Se fait contre le gradient'],correct:[0,1],why:['Canal ou transporteur participe.','Elle ne requiert pas d’énergie directe.','Cela ne définit pas cette diffusion.','Cette diffusion suit le gradient.']},
 {id:'membrane-2',course:'membrane',topic:'Biologie cellulaire',prompt:'Quels énoncés sont exacts ?',options:['L’osmose concerne l’eau','La membrane est sélective','Tout transport est actif','La membrane contient des lipides'],correct:[0,1,3],why:['L’eau traverse une membrane sélective.','Sa perméabilité dépend du soluté.','La diffusion est passive.','Ils forment une bicouche.']},
 {id:'tissues-1',course:'tissues',topic:'Histologie',prompt:'Quelles sont des familles tissulaires ?',options:['Ventriculaire','Alvéolaire','Artérielle','Nerveuse'],correct:[3],why:['Ce terme ne désigne pas une famille.','Ce terme ne désigne pas une famille.','Ce terme ne désigne pas une famille.','Communication et traitement de l’information.']},
 {id:'tissues-2',course:'tissues',topic:'Histologie',prompt:'Quelles associations sont correctes ?',options:['Musculaire : contraction','Nerveux : communication','Organe : plusieurs tissus','Épithélial : exclusivement soutien'],correct:[0,1,2],why:['C’est une propriété fondamentale.','C’est une fonction majeure.','L’organisation associe des tissus.','Revêtement et sécrétion sont essentiels.']},
 {id:'heart-1',course:'FMA7088',topic:'Cardiovasculaire',prompt:'Dans la circulation normale adulte :',options:['Le ventricule droit éjecte vers les poumons','Les veines pulmonaires reviennent au cœur droit','L’aorte naît du ventricule droit','Les veines caves arrivent au cœur droit'],correct:[0,3],why:['Par le tronc et les artères pulmonaires.','Elles rejoignent l’atrium gauche.','Elle naît du ventricule gauche.','Elles rejoignent l’atrium droit.']},
 {id:'heart-2',course:'FMA7088',topic:'Cardiovasculaire',prompt:'À propos des valves cardiaques :',options:['La mitrale sépare atrium et ventricule gauches','La tricuspide est à droite','Elles s’ouvrent selon les pressions','Elles propulsent activement le sang'],correct:[0,1,2],why:['C’est la valve atrioventriculaire gauche.','C’est la valve atrioventriculaire droite.','Les gradients règlent ouverture et fermeture.','La contraction myocardique fournit la propulsion.']},
 {id:'lungs-1',course:'FMA7309',topic:'Respiratoire',prompt:'Les échanges alvéolaires :',options:['Apportent de l’oxygène au sang','Produisent de la bile','Se font principalement dans la trachée','Impliquent les capillaires'],correct:[0,3],why:['L’oxygène passe vers le sang.','La production de bile est hépatique.','La trachée conduit l’air.','Ils sont au contact des alvéoles.']},
 {id:'lungs-2',course:'FMA7309',topic:'Respiratoire',prompt:'Distinguez ventilation et perfusion :',options:['Ventilation : renouvellement de l’air','Perfusion : circulation sanguine','Ces termes sont synonymes','Leur adéquation contribue aux échanges'],correct:[0,1,3],why:['Elle renouvelle l’air alvéolaire.','Elle apporte le sang aux capillaires.','Air et sang sont deux flux distincts.','Les deux fonctions sont complémentaires.']},
 {id:'liver-1',course:'FMA7197',topic:'Digestif',prompt:'Le foie participe :',options:['Au traitement des nutriments','À la production de bile','À la filtration glomérulaire','Au métabolisme de substances'],correct:[0,1,3],why:['Il transforme et stocke des nutriments.','La bile est produite par le foie.','Cette filtration est rénale.','Le foie a des fonctions métaboliques.']},
 {id:'stomach-1',course:'FMA7148',topic:'Digestif',prompt:'L’estomac :',options:['Mélange les aliments','Produit la bile','Est le principal site d’absorption des nutriments','Précède l’intestin grêle'],correct:[0,3],why:['Ses mouvements brassent le contenu.','La bile est produite par le foie.','L’intestin grêle joue ce rôle majeur.','Le contenu rejoint le duodénum.']},
 {id:'pancreas-1',course:'FMA7198',topic:'Digestif',prompt:'Le pancréas possède :',options:['Une fonction endocrine','Une fonction exocrine','Un rôle dans la régulation glycémique','La fonction de stockage de la bile'],correct:[0,1,2],why:['Des hormones sont libérées dans le sang.','Des sécrétions rejoignent le tube digestif.','Notamment par l’insuline et le glucagon.','La vésicule biliaire stocke la bile.']},
 {id:'intestine-1',course:'FMA7200',topic:'Digestif',prompt:'L’intestin grêle :',options:['Comprend le duodénum','Comprend le jéjunum et l’iléon','Absorbe de nombreux nutriments','Est identique au côlon'],correct:[0,1,2],why:['C’est sa portion initiale.','Ce sont ses portions suivantes.','L’absorption y est majeure.','Le côlon appartient au gros intestin.']},
 {id:'kidney-1',course:'FMA7204',topic:'Urinaire',prompt:'Les reins contribuent :',options:['À l’élimination de déchets','À l’équilibre hydrique','À la formation de l’urine','À la production de bile'],correct:[0,1,2],why:['Des déchets sont excrétés dans l’urine.','Ils ajustent l’excrétion d’eau.','Filtration et transports tubulaires y participent.','Cette production est hépatique.']},
 {id:'kidney-2',course:'FMA7204',topic:'Urinaire',prompt:'Distinguez les voies urinaires :',options:['Les uretères relient vessie et extérieur','L’urètre conduit vers l’extérieur','Uretère et urètre sont synonymes','La vessie produit la bile'],correct:[1],why:['Ils transportent l’urine vers la vessie.','Il part de la vessie.','Ce sont deux conduits différents.','La bile est produite par le foie.']},
 {id:'brain-1',course:'FMA50801',topic:'Nerveux',prompt:'Le cerveau participe :',options:['À l’intégration sensorielle','À la commande de mouvements','À la mémoire','À la production de bile'],correct:[0,1,2],why:['Il traite des informations sensorielles.','Des réseaux commandent des mouvements.','Des réseaux soutiennent la mémorisation.','Cette fonction relève du foie.']},
 {id:'femur-1',course:'FMA24474',topic:'Locomoteur',prompt:'Le fémur :',options:['Est un os de la cuisse','Participe à la hanche','Participe au genou','Est un os de l’avant-bras'],correct:[0,1,2],why:['Il constitue le squelette de la cuisse.','Sa tête s’articule avec l’acétabulum.','Son extrémité distale participe au genou.','L’avant-bras comprend radius et ulna.']},
]
export const questions:Question[]=questionCatalog.map(q=>({...q,topic:courses.find(c=>c.id===q.course)?.category??q.topic}))
export function isCorrect(q:Question,answer:number[]){return answer.length===q.correct.length&&q.correct.every(i=>answer.includes(i))}
export function shuffled<T>(items:T[]):T[]{const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
