import type {Course} from './curriculum'
import {courseSupport} from './courseSupport'
const base='https://openstax.org/books/anatomy-and-physiology-2e/pages/'
type Draft={id:string;title:string;tag:string;objectives:string[];sections:[string,string][];glossary:[string,string][];trap:string;recall:string;answer:string;caseStudy:{prompt:string;answer:string};refs:string[]}
const drafts:Draft[]=[
{id:'anat-pelvis',title:'Os coxaux et bassin : construire l’anneau pelvien',tag:'Pelvis et périnée',objectives:['Orienter un os coxal','Reconstruire les articulations de l’anneau pelvien','Distinguer limites osseuses et contenu viscéral'],sections:[
['Trois pièces réunies','Chaque os coxal adulte réunit ilium, ischium et pubis. Ces trois territoires convergent dans l’acétabulum, cavité recevant la tête du fémur. L’ilium forme la large aile supérieure ; l’ischium occupe surtout la partie postéro-inférieure ; le pubis participe à la partie antérieure. L’os coxal n’est donc pas synonyme d’ilium. Le bassin osseux associe les deux coxaux, le sacrum et le coccyx. Pour orienter un coxal, placez l’acétabulum latéralement, la grande incisure ischiatique en arrière et la surface symphysaire en avant et médialement.'],
['Les reliefs de l’ilium','La crête iliaque relie les épines iliaques antérieure et postérieure supérieures. L’épine antérieure inférieure se situe sous la supérieure. Ces reliefs servent de repères et d’attaches ; ce ne sont pas des surfaces articulaires. La fosse iliaque regarde vers l’intérieur, tandis que la face glutéale regarde vers l’extérieur. La surface auriculaire médiale répond au sacrum. La ligne arquée contribue au détroit supérieur. Une vue latérale ne montre pas les mêmes reliefs qu’une vue médiale : l’absence de visibilité ne signifie pas l’absence d’une structure.'],
['Ischium et pubis','La tubérosité ischiatique constitue un appui en position assise et une zone d’origine de muscles postérieurs de la cuisse. L’épine ischiatique sépare les grandes et petites incisures. Les ligaments sacroépineux et sacrotubéral contribuent à transformer ces incisures en passages osseofibreux. Les branches pubiennes et ischiatiques entourent le foramen obturé, largement fermé par une membrane qui conserve un passage vasculonerveux. Les deux pubis se rejoignent à la symphyse pubienne, articulation cartilagineuse médiane : une symphyse n’est ni une suture ni une articulation synoviale.'],
['Transmettre les charges','Les charges transmises par la colonne rejoignent le sacrum, les os coxaux par les articulations sacro-iliaques, puis les fémurs par les hanches. Symphyse et ligaments contribuent à la cohésion de l’anneau. L’acétabulum comprend une surface articulaire périphérique et une fosse centrale. Le labrum approfondit son rebord. La stabilité de la hanche dépend des surfaces, de la capsule, des ligaments et des muscles. Elle ne se déduit pas simplement de la profondeur apparente d’une cavité sur un modèle simplifié.'],
['Détroits et variations pelviennes','Le détroit supérieur sépare conventionnellement grand et petit bassin. Le grand bassin prolonge la cavité abdominale ; le petit contient notamment des éléments urinaires, digestifs et reproducteurs. Le détroit inférieur constitue une autre limite osseoligamentaire. Les descriptions classiques comparent des tendances moyennes de bassins féminins et masculins, notamment l’ouverture sous-pubienne et les dimensions relatives. Les variations individuelles se chevauchent : une silhouette osseuse ne suffit pas à déterminer les organes d’une personne ni ses capacités obstétricales. Les modèles représentent des références particulières.'],
['Reconstruire une vue puis une coupe','En vue antérieure, retrouvez crêtes, acétabulums, foramens obturés et symphyse, puis replacez le sacrum en arrière. En coupe sagittale, séparez les limites osseuses de la succession des viscères : la vessie est antérieure au rectum ; les rapports intermédiaires dépendent notamment de l’appareil reproducteur. Dessinez ensuite un anneau avec les deux articulations sacro-iliaques et la symphyse. Ajoutez les deux hanches. Cette représentation de la transmission des charges complète l’étude des reliefs sans prétendre donner les dimensions réelles.']
],glossary:[['Ilium','Territoire supérieur et évasé de l’os coxal.'],['Ischium','Territoire postéro-inférieur portant la tubérosité ischiatique.'],['Pubis','Territoire antérieur participant à la symphyse.'],['Acétabulum','Cavité latérale recevant la tête du fémur.']],trap:'Le sacrum appartient au bassin mais n’est pas un os coxal.',recall:'Quelles trois pièces convergent dans l’acétabulum ?',answer:'L’ilium, l’ischium et le pubis.',caseStudy:{prompt:'Un coxal est placé avec son acétabulum médialement et sa surface symphysaire en arrière. Est-il correctement orienté ?',answer:'Non. L’acétabulum regarde latéralement ; la surface symphysaire se situe en avant et médialement. Ces deux repères doivent être corrigés avant d’attribuer un côté.'},refs:['8-3-the-pelvic-girdle-and-pelvis','9-6-anatomy-of-selected-synovial-joints']},
{id:'anat-knee',title:'Genou et patella : surfaces, ménisques et stabilité',tag:'Membre inférieur',objectives:['Identifier les articulations du genou','Orienter la patella','Relier ligaments et appareil extenseur'],sections:[
['Un ensemble articulaire','Le genou associe les contacts entre condyles fémoraux et surfaces supérieures du tibia, ainsi que le contact entre patella et surface patellaire du fémur. La fibula est proche mais ne porte pas la surface principale d’appui du fémur. Flexion et extension dominent, avec des rotations associées selon la position et les contraintes. Roulement et glissement se combinent : le mouvement ne correspond pas à une simple charnière géométrique. Il faut préciser quel segment est fixé avant de décrire les déplacements.'],
['Orienter la patella','La patella, ou rotule, est un os sésamoïde de l’appareil extenseur. Sa base regarde vers le haut et son apex vers le bas. Sa face antérieure est superficielle ; sa face postérieure comporte des facettes articulaires répondant au fémur. Le tendon quadricipital rejoint la patella, puis le ligament patellaire la relie à la tubérosité tibiale. Les rétinaculums contribuent à sa stabilisation. La facette latérale est habituellement plus étendue, mais un seul critère de taille ne remplace pas une orientation complète.'],
['Ménisques et contacts','Les ménisques médial et latéral sont des fibrocartilages interposés entre fémur et tibia. Ils contribuent à l’adaptation des surfaces et à la répartition des charges. Ils ne sont ni des os supplémentaires ni le cartilage hyalin recouvrant les surfaces articulaires. Le ménisque médial présente des attaches qui le rendent globalement moins mobile que le latéral. Une coupe montrant une corne méniscale ne représente pas toute la structure : il faut reconstruire sa forme et ses attaches à partir de plusieurs repères.'],
['Croisés et collatéraux','Le ligament croisé antérieur limite notamment l’avancée du tibia relativement au fémur ; le postérieur limite notamment son recul. Ces fonctions s’intègrent dans un contrôle tridimensionnel. Les ligaments collatéraux participent au contrôle des contraintes frontales. Les croisés sont intracapsulaires mais séparés de la cavité synoviale proprement dite par le revêtement synovial. Les mots intracapsulaire et intrasynovial ne sont donc pas interchangeables. Capsule, ligaments, ménisques et muscles contribuent ensemble à la stabilité.'],
['Transmission de la force','La contraction du quadriceps transmet une force par le tendon quadricipital, la patella et le ligament patellaire jusqu’au tibia. La patella modifie le bras de levier de cet appareil. Les muscles postérieurs de la cuisse participent à la flexion et au contrôle dynamique. Le gastrocnémien franchit également genou et cheville : sa fonction dépend de la position des deux articulations. Un raisonnement mécanique doit préciser l’origine de la force, son trajet et son point d’application, plutôt que simplement nommer un muscle.'],
['Méthode de lecture','Sur une vue antérieure, la patella masque une partie des surfaces fémorales. Les ménisques et croisés nécessitent une vue profonde ou une coupe adaptée. Une représentation osseuse seule ne permet pas d’évaluer les tissus mous. Pour réviser, associez chaque élément à une fonction : porter la charge, adapter les contacts, guider la patella ou limiter un déplacement. Tracez ensuite la chaîne d’extension du quadriceps jusqu’au tibia. L’atlas enseigne des rapports généraux ; il ne sert pas à interpréter un genou individuel.']
],glossary:[['Patella','Os sésamoïde intégré à l’appareil extenseur.'],['Ménisque','Fibrocartilage adaptant les contacts fémorotibiaux.'],['Ligament croisé antérieur','Ligament limitant notamment l’avancée relative du tibia.'],['Ligament patellaire','Élément reliant la patella à la tubérosité tibiale.']],trap:'La fibula ne s’articule pas directement avec le fémur.',recall:'À quel os s’attache le ligament patellaire en bas ?',answer:'Au tibia, sur sa tubérosité.',caseStudy:{prompt:'Un schéma transmet la force du quadriceps à la fibula par la patella. Quelle est l’erreur ?',answer:'Le ligament patellaire rejoint la tubérosité tibiale. L’attache distale de cet appareil est donc sur le tibia.'},refs:['8-4-bones-of-the-lower-limb','9-6-anatomy-of-selected-synovial-joints','11-6-appendicular-muscles-of-the-pelvic-girdle-and-lower-limbs']},
{id:'anat-leg',title:'Tibia, fibula et cheville : les deux os de la jambe',tag:'Membre inférieur',objectives:['Orienter tibia et fibula','Distinguer les rapports proximaux et distaux','Reconstruire la pince de la cheville'],sections:[
['La région de la jambe','La jambe anatomique se situe entre genou et cheville ; la cuisse est située entre hanche et genou. Le tibia est médial et plus volumineux ; la fibula, anciennement péroné, est latérale et plus grêle. Leur participation aux charges diffère, sans rendre la fibula inutile. La jambe contient aussi des loges musculaires, des vaisseaux et des nerfs. Une étude du squelette prépare l’étude de ces rapports, mais ne constitue pas une description complète de toute la région.'],
['L’extrémité supérieure du tibia','Les condyles tibiaux portent les surfaces participant au genou. La région intercondylaire reçoit des attaches méniscales et ligamentaires. La tubérosité tibiale, antérieure, donne attache au ligament patellaire. Une surface latérale répond à la tête de la fibula : elle est distincte des surfaces qui répondent au fémur. Le mot condyle doit toujours être associé au nom de l’os. Le condyle médial fémoral et le condyle médial tibial sont voisins, mais appartiennent à deux pièces différentes.'],
['Corps du tibia et membrane','La diaphyse tibiale présente un bord antérieur net et une face médiale largement sous-cutanée. Sa forme triangulaire aide à l’orientation. La face postérieure porte notamment la ligne du soléaire. Le bord interosseux fait face à la fibula ; la membrane interosseuse relie les deux os, participe à leur relation mécanique et reçoit des attaches musculaires. Cette organisation ne permet pas une pronation-supination comparable à celle de l’avant-bras. Une membrane de liaison ne doit pas être confondue avec une cavité synoviale.'],
['La fibula','La tête fibulaire est proximale, suivie du col ; le nerf fibulaire commun entretient un rapport étroit avec cette région. Le corps descend vers la malléole latérale. Proximalement, la fibula s’articule avec le tibia, pas avec le fémur. Elle reçoit des attaches musculaires et contribue à la stabilité de la cheville. Dans la description usuelle, la malléole latérale descend plus bas et se trouve plus en arrière que la médiale. Ces rapports complètent l’orientation fondée sur la position latérale de l’os.'],
['La pince tibiofibulaire','L’extrémité inférieure du tibia forme le plafond talocrural et la malléole médiale. La fibula forme la malléole latérale. L’union distale tibiofibulaire est une syndesmose, avec des tissus fibreux assurant la cohésion et de faibles ajustements. Le talus s’insère dans cette pince. Les mouvements dominants talocruraux sont flexion dorsale et plantaire. Inversion et éversion impliquent principalement d’autres articulations du pied. Attribuer tous les mouvements du pied à une unique articulation nommée cheville est donc imprécis.'],
['Reconstituer le trajet des contraintes','Placez tibia médial, fibula latérale, membrane entre les deux et talus dans la pince distale. Ajoutez la tubérosité tibiale en avant. Vous pouvez alors situer les loges antérieure, latérale et postérieure. Les charges venues du fémur passent principalement par le tibia vers le talus ; cela n’exclut pas toute contrainte fibulaire. Dans un QCM, distinguez une contribution principale d’une exclusion absolue. Les termes uniquement et jamais doivent être vérifiés avec soin plutôt qu’acceptés sur la base d’une fonction dominante.']
],glossary:[['Tibia','Os médial de la jambe portant l’essentiel de l’appui osseux.'],['Fibula','Os latéral de la jambe participant aux attaches et à la cheville.'],['Malléole médiale','Relief distal du tibia du côté médial de la cheville.'],['Syndesmose','Union fibreuse entre pièces osseuses, notamment tibia et fibula distalement.']],trap:'La malléole médiale appartient au tibia ; la latérale appartient à la fibula.',recall:'La fibula répond-elle directement au fémur ?',answer:'Non. Proximalement, elle s’articule avec le tibia.',caseStudy:{prompt:'Une légende place tibia latéralement et fibula médialement. Comment vérifier la correction ?',answer:'Placez le tibia du côté médial et la fibula latéralement, puis retrouvez leurs malléoles de part et d’autre du talus.'},refs:['8-4-bones-of-the-lower-limb','9-2-fibrous-joints','9-6-anatomy-of-selected-synovial-joints']},
{id:'anat-foot',title:'Le pied : les sept os du tarse, métatarse et orteils',tag:'Membre inférieur',objectives:['Nommer tous les os du tarse','Reconstituer les cinq rayons','Relier voûtes et mouvements'],sections:[
['Vingt-six os dans le décompte usuel','Un pied adulte comprend habituellement sept os du tarse, cinq métatarsiens et quatorze phalanges, soit vingt-six os hors sésamoïdes et os accessoires. L’hallux possède deux phalanges, chacun des autres orteils trois. L’arrière-pied comprend talus et calcanéus ; le médio-pied comprend notamment naviculaire, cuboïde et cunéiformes ; l’avant-pied comprend métatarsiens et phalanges. Ces subdivisions fonctionnelles organisent le cours. Elles ne signifient pas que les os forment trois rangées rectilignes et indépendantes.'],
['Talus et calcanéus','Le talus reçoit les contraintes de la pince tibiofibulaire par sa trochlée. Il comporte corps, col et tête ; sa tête répond au naviculaire. Il ne présente pas d’insertion musculaire directe habituelle. Le calcanéus forme le talon ; sa tubérosité postérieure reçoit le tendon calcanéen. Le sustentaculum tali est un relief médial soutenant une partie du talus. Les rapports talocalcanéens participent à l’adaptation du pied. Ces deux os ne doivent donc pas être confondus malgré leur appartenance commune à l’arrière-pied.'],
['Naviculaire, cuboïde et cunéiformes','Le naviculaire est situé en avant de la tête du talus, médialement. Les trois cunéiformes, médial, intermédiaire et latéral, se trouvent en avant de lui. Le cuboïde occupe le côté latéral, devant le calcanéus. Les cunéiformes répondent principalement aux premiers métatarsiens ; le cuboïde aux quatrième et cinquième. Construisez une chaîne médiale et une chaîne latérale plutôt qu’une rangée unique. Talus, calcanéus, naviculaire, cuboïde et les trois cunéiformes constituent bien les sept os du tarse.'],
['Métatarsiens et phalanges','Chaque métatarsien comporte base proximale, corps et tête distale. Les rayons sont numérotés I à V du gros orteil vers le petit. La base du cinquième possède une tubérosité latérale à distinguer de sa tête. Les articulations métatarsophalangiennes relient les têtes aux phalanges proximales. L’hallux n’a pas de phalange moyenne. Des sésamoïdes sont habituellement associés à sa région métatarsophalangienne. Tendons, capsules et plaques plantaires contribuent à la fonction ; les os ne sont pas des baguettes rigides simplement juxtaposées.'],
['Voûtes et mouvement','Les voûtes longitudinales médiale et latérale, ainsi que l’organisation transversale, participent à la répartition des contraintes. Leur maintien dépend de la forme des os, des ligaments, de l’aponévrose plantaire et des muscles. La flexion dorsale et plantaire se produit surtout à l’articulation talocrurale ; inversion et éversion impliquent les articulations du tarse. La marche associe réception de charge, adaptation puis propulsion. La position de l’hallux et la tension de l’aponévrose participent à cette coopération plutôt qu’à une action isolée.'],
['Une méthode pour retrouver les pièces','Repérez le talon en arrière et la tête du talus vers l’avant. Placez naviculaire médial, cuboïde latéral, puis les trois cunéiformes. Vérifiez cinq rayons et quatorze phalanges. Faites tourner le modèle : vues dorsale et plantaire ne montrent pas les mêmes reliefs. Restituez ensuite deux chaînes simplifiées, talus–naviculaire–cunéiformes et calcanéus–cuboïde. Ces chaînes aident à mémoriser la disposition, mais ne sont pas des circuits exclusifs de transmission des forces, qui se distribuent dans un ensemble déformable.']
],glossary:[['Talus','Os reçu dans la pince tibiofibulaire, articulé notamment au calcanéus et au naviculaire.'],['Calcanéus','Os du talon recevant le tendon calcanéen en arrière.'],['Naviculaire','Os médial situé entre tête du talus et cunéiformes.'],['Cuboïde','Os latéral situé en avant du calcanéus.']],trap:'Le pouce du pied, ou hallux, n’a pas de phalange moyenne.',recall:'Nommez les sept os du tarse.',answer:'Talus, calcanéus, naviculaire, cuboïde, cunéiformes médial, intermédiaire et latéral.',caseStudy:{prompt:'Un étudiant compte quinze phalanges en multipliant cinq orteils par trois. Quelle est l’erreur ?',answer:'L’hallux en a deux. Le total est quatorze, donnant vingt-six os avec le tarse et le métatarse, hors sésamoïdes et os accessoires.'},refs:['8-4-bones-of-the-lower-limb','9-5-types-of-body-movements','9-6-anatomy-of-selected-synovial-joints']},
{id:'anat-joints',title:'Articulations : classer les unions et décrire les mouvements',tag:'Principes',objectives:['Comparer les trois familles structurales','Identifier le dispositif synovial','Décrire les mouvements dans le bon référentiel'],sections:[
['Deux classifications complémentaires','La classification structurale distingue articulations fibreuses, cartilagineuses et synoviales selon les tissus et la présence d’une cavité. Une classification fonctionnelle considère la mobilité. Ces lectures se complètent, mais le nom d’un tissu ne donne pas à lui seul une amplitude précise. Une articulation n’est pas nécessairement un lieu de grand mouvement. Une même région, comme la colonne, comprend plusieurs types d’unions : disques entre corps vertébraux, articulations synoviales postérieures, ligaments et muscles participant ensemble à sa fonction.'],
['Les unions fibreuses','Les sutures réunissent les bords osseux par du tissu fibreux, notamment au crâne. Une syndesmose associe des pièces par ligaments ou membrane ; l’union tibiofibulaire distale en est un exemple. Une gomphose correspond à l’ancrage d’une dent dans son alvéole par le ligament parodontal. Ces termes décrivent l’organisation du tissu de liaison. Une suture n’est pas un os supplémentaire et une membrane interosseuse n’est pas une cavité articulaire. La mobilité dépend aussi de la région, des contraintes et de l’âge.'],
['Les unions cartilagineuses','Une synchondrose est une union par cartilage hyalin ; certaines sont transitoires, comme les cartilages de croissance avant fermeture. Une symphyse comporte du fibrocartilage entre des surfaces osseuses recouvertes de cartilage. La symphyse pubienne et les disques intervertébraux sont des exemples classiques. Le disque associe un anneau fibreux périphérique et un noyau central. Son fonctionnement dépend de sa composition, de son état et des autres éléments vertébraux : il ne porte pas seul toutes les contraintes de la colonne.'],
['Le dispositif synovial','Une articulation synoviale comporte une cavité, une capsule et des surfaces recouvertes de cartilage articulaire. La capsule associe couche fibreuse et membrane synoviale interne. La synovie contribue à la lubrification et aux échanges avec le cartilage. Selon l’articulation, on trouve aussi labrum, disque, ménisques ou bourses voisines. Ces éléments ne sont pas universels. Une bourse réduit les frottements entre structures et ne communique pas nécessairement avec la cavité. Intracapsulaire et intrasynovial sont également deux notions à distinguer.'],
['Forme, axes et stabilité','Les formes usuelles sont plane, trochléenne, trochoïde, ellipsoïde, en selle et sphéroïde. Elles indiquent des possibilités dominantes ; le mouvement réel dépend aussi de capsule, ligaments et muscles. Flexion-extension, abduction-adduction et rotations doivent être rapportées à la position de référence. La circumduction combine plusieurs mouvements et n’est pas simplement une rotation axiale de l’os. La pronation-supination relève des articulations radioulnaires ; l’opposition du pouce combine plusieurs composantes. Une silhouette ne suffit pas à identifier toutes les possibilités.'],
['Comparer avec une grille commune','Étudiez successivement surfaces en présence, type structural, moyens d’union, éléments d’adaptation et mouvements principaux. Ajoutez ensuite muscles moteurs et rapports vasculonerveux. Cette grille permet de comparer coude, hanche et genou sans apprendre des listes incompatibles. Dans les QCM, vérifiez les mots absolus : toutes les articulations ne sont pas synoviales et toutes les synoviales ne possèdent pas un ménisque. Précisez le segment fixé avant de décrire le déplacement relatif ; un même mouvement peut être présenté dans plusieurs référentiels.']
],glossary:[['Suture','Union fibreuse entre bords osseux, notamment au crâne.'],['Synchondrose','Union par cartilage hyalin.'],['Symphyse','Union cartilagineuse comprenant du fibrocartilage.'],['Articulation synoviale','Articulation comportant une cavité et un dispositif capsulosynovial.']],trap:'Ménisque, labrum et bourse sont différents ; leur présence n’est pas universelle.',recall:'Quelle caractéristique distingue la famille synoviale ?',answer:'La présence d’une cavité articulaire dans un dispositif capsulaire et synovial.',caseStudy:{prompt:'Peut-on classer la hanche et la symphyse pubienne parmi les articulations sphéroïdes ?',answer:'La hanche est synoviale sphéroïde. La symphyse pubienne est cartilagineuse : cette sous-classification ne lui est pas applicable.'},refs:['9-1-classification-of-joints','9-2-fibrous-joints','9-3-cartilaginous-joints','9-4-synovial-joints','9-5-types-of-body-movements']}
]
export const regionalCourses:Course[]=drafts.map(c=>({...c,category:'Anatomie',structure:null,sections:c.sections.map(([title,text])=>({title,text})),minutes:Math.ceil(c.sections.map(s=>s[1]).join(' ').split(/\s+/).length/150)+8,source:base+c.refs[0],sources:c.refs.map(ref=>({label:'OpenStax · '+ref.split('-').slice(0,2).join('.'),url:base+ref}))}))
export const regionalSupport=courseSupport(regionalCourses)
