import type {Course} from './curriculum'
import {courseSupport} from './courseSupport'
const base='https://openstax.org/books/anatomy-and-physiology-2e/pages/'
type Draft={id:string;title:string;tag:string;sections:[string,string][];glossary:[string,string][];recall:string;answer:string;trap:string;refs:string[]}
const drafts:Draft[]=[
{id:'anat-upper-muscles',title:'Muscles du membre supérieur : loges, mouvements et nerfs',tag:'Membre supérieur',sections:[
['De la ceinture au membre libre','La scapula et la clavicule forment une base mobile pour le membre supérieur. Trapèze, dentelé antérieur, rhomboïdes et élévateur de la scapula contribuent à sa position. Le mouvement de l’épaule associe donc articulation glénohumérale et déplacements de la ceinture. Une abduction du bras ne dépend pas d’un muscle unique. Pour raisonner, distinguez mouvement de la scapula, mouvement de l’humérus et position du tronc.'],
['Coiffe et muscles de l’épaule','La coiffe comprend supraépineux, infraépineux, petit rond et subscapulaire. Leurs tendons participent à la stabilisation dynamique de la tête humérale. Le deltoïde contribue notamment à l’élévation du bras ; grand pectoral et grand dorsal ont des actions dépendant de leurs directions de traction. Le petit rond appartient à la coiffe, contrairement au grand rond. Il faut relier chaque action à la position articulaire plutôt que traiter la liste des muscles comme une suite interchangeable.'],
['Loges du bras','La loge antérieure comprend biceps brachial, brachial et coracobrachial, avec une innervation principalement musculocutanée. Le biceps participe notamment à la flexion du coude et à la supination ; le brachial est un fléchisseur important. La loge postérieure comprend le triceps, principalement innervé par le radial, et participe à l’extension. La longue portion du triceps franchit l’épaule. Un muscle biarticulaire peut donc modifier son efficacité selon la position de l’articulation voisine.'],
['Avant-bras : fléchisseurs et pronateurs','Le groupe antérieur comprend notamment rond pronateur, fléchisseur radial du carpe, long palmaire, fléchisseur ulnaire du carpe et fléchisseurs des doigts. L’innervation est principalement médiane, avec des exceptions ulnaires, notamment le fléchisseur ulnaire et une partie du fléchisseur profond. Le long fléchisseur du pouce et le carré pronateur appartiennent au plan profond. Les tendons franchissant le poignet doivent être suivis jusqu’à leurs attaches : fléchir le poignet n’est pas fléchir une phalange.'],
['Avant-bras : extenseurs et supination','Le groupe postérieur comprend les extenseurs du poignet et des doigts ainsi que des muscles du pouce ; son innervation relève principalement du radial et de ses branches. Le supinateur agit sur la rotation radioulnaire. Le brachioradial, innervé par le radial, fléchit le coude : le nom du nerf ne suffit pas à déduire une action d’extension. Il faut distinguer loge anatomique, branche nerveuse et mouvement réalisé. Les tendons du pouce constituent des repères dorsolatéraux du poignet.'],
['Muscles intrinsèques de la main','Les éminences thénar et hypothénar, les interosseux et les lombricaux participent à la précision des prises. Les interosseux dorsaux écartent les doigts longs par rapport à l’axe du troisième ; les palmaires les rapprochent. Les lombricaux participent à la flexion métacarpophalangienne et à l’extension interphalangienne. Médian et ulnaire se partagent l’innervation selon les muscles. L’opposition du pouce combine plusieurs composantes. Pour apprendre, construisez une prise puis identifiez os, articulations, tendons extrinsèques et muscles intrinsèques qui y contribuent.']
],glossary:[['Coiffe des rotateurs','Ensemble des tendons du supraépineux, infraépineux, petit rond et subscapulaire.'],['Supination','Rotation de l’avant-bras orientant la paume vers l’avant en position anatomique.'],['Muscle intrinsèque','Muscle dont les attaches se trouvent dans la région considérée, ici la main.'],['Muscle biarticulaire','Muscle franchissant deux articulations et pouvant agir selon leur position.']],recall:'Le grand rond appartient-il à la coiffe ?',answer:'Non. La coiffe comprend le petit rond, avec supraépineux, infraépineux et subscapulaire.',trap:'Un muscle innervé par le radial n’est pas nécessairement extenseur : le brachioradial fléchit le coude.',refs:['11-5-muscles-of-the-pectoral-girdle-and-upper-limbs','9-6-anatomy-of-selected-synovial-joints']},
{id:'anat-lower-muscles',title:'Muscles du membre inférieur : hanche, cuisse, jambe et pied',tag:'Membre inférieur',sections:[
['La région glutéale et la hanche','Le grand fessier participe notamment à l’extension ; moyen et petit fessiers participent à l’abduction et à la stabilisation du bassin. En appui unipodal, leur fonction ne se limite pas à écarter la cuisse : ils contribuent au contrôle du bassin. L’iliopsoas participe à la flexion de hanche. Les muscles courts profonds ont notamment des actions de rotation dépendant de la position. La fonction doit être décrite avec un segment fixé et une direction de traction.'],
['La loge antérieure de cuisse','Le quadriceps associe droit fémoral et vastes. Il transmet la force d’extension vers le tibia par l’appareil patellaire et reçoit une innervation fémorale. Le droit fémoral franchit aussi la hanche. Le sartorius présente un trajet oblique et des actions combinées. L’extension du genou ne doit pas être confondue avec une extension de hanche. La position des articulations modifie longueur musculaire et efficacité mécanique, particulièrement pour les muscles biarticulaires.'],
['Loges médiale et postérieure','La région médiale comprend les adducteurs, le gracile et des muscles dont l’innervation et les actions demandent des nuances ; le nerf obturateur y joue un rôle important. La région postérieure comprend notamment semi-tendineux, semi-membraneux et biceps fémoral. Les ischiojambiers participent à la flexion du genou et, pour leurs portions biarticulaires, à l’extension de hanche. La courte portion du biceps ne franchit pas la hanche. Une action commune ne rend donc pas toutes les portions identiques.'],
['La loge antérieure de jambe','Tibial antérieur et extenseurs des orteils participent notamment à la flexion dorsale de cheville ; le nerf fibulaire profond innerve cette loge. Les mouvements des orteils dépendent de tendons spécifiques. Le tibial antérieur contribue aussi à l’inversion. Le nerf fibulaire commun se divise en branches profonde et superficielle : leurs territoires diffèrent. Ne déduisez pas l’innervation d’une loge d’après la proximité d’un seul nerf sur une vue simplifiée.'],
['Loges latérale et postérieure','La loge latérale contient les fibulaires long et court, innervés par le fibulaire superficiel, participant notamment à l’éversion. La loge postérieure reçoit le tibial ; gastrocnémien et soléaire contribuent à la flexion plantaire par le tendon calcanéen. Le gastrocnémien franchit le genou, contrairement au soléaire. Le plan profond comprend notamment tibial postérieur et longs fléchisseurs. Les tendons passent selon des trajets définis autour des malléoles, ce qui contribue à leur action.'],
['Le pied en appui et en propulsion','Les muscles intrinsèques du pied complètent les tendons venant de la jambe et participent au contrôle des orteils et des voûtes. Les nerfs plantaires distribuent leurs branches dans la plante. La marche nécessite une coopération entre stabilisation du bassin, contrôle du genou, adaptation de cheville et propulsion. Une liste d’actions isolées ne suffit pas à expliquer cette séquence. Pour réviser, choisissez une phase d’appui puis identifiez les articulations, les muscles et les nerfs dominants sans prétendre qu’un seul élément réalise toute la tâche.']
],glossary:[['Quadriceps','Ensemble comprenant droit fémoral et vastes, majeur dans l’extension du genou.'],['Triceps sural','Ensemble formé principalement par gastrocnémien et soléaire.'],['Nerf fibulaire profond','Branche innervant notamment la loge antérieure de jambe.'],['Nerf tibial','Nerf innervant notamment la loge postérieure de jambe.']],recall:'Quel muscle du triceps sural ne franchit pas le genou ?',answer:'Le soléaire.',trap:'La courte portion du biceps fémoral ne participe pas directement à l’extension de hanche.',refs:['11-6-appendicular-muscles-of-the-pelvic-girdle-and-lower-limbs','13-4-the-peripheral-nervous-system']},
{id:'anat-trunk-muscles',title:'Parois du tronc et diaphragme : respiration, posture et pression',tag:'Thorax',sections:[
['Une paroi active','La paroi thoracoabdominale protège, mobilise et participe aux variations de pression. Elle associe os, muscles, fascias et aponévroses. Une aponévrose est une lame tendineuse, pas un muscle supplémentaire. Les attaches orientent la traction ; les variations de position modifient les effets. Pour reconstruire une paroi, distinguez couches superficielles, plans profonds et cavités. Une image externe ne permet pas de voir simultanément toutes les couches.'],
['Diaphragme et dôme','Le diaphragme sépare thorax et abdomen. Ses fibres périphériques convergent vers un centre tendineux. Sa contraction abaisse ses coupoles et contribue à l’augmentation du volume thoracique. Le nerf phrénique, issu principalement de C3–C5, assure son innervation motrice. Le diaphragme ne pompe pas directement l’air comme un piston dans un tuyau : les variations de volume modifient les pressions et permettent les flux selon les gradients.'],
['Les passages diaphragmatiques','Des ouvertures permettent le passage de la veine cave inférieure, de l’œsophage et de l’aorte à des niveaux classiquement repérés T8, T10 et T12. Ces repères sont des approximations anatomiques usuelles. Les structures n’empruntent pas toutes un orifice organisé de la même façon. Les piliers et arcs diaphragmatiques participent aux rapports postérieurs. Il faut distinguer un passage à travers une zone tendineuse d’un passage situé en arrière sous une arcade.'],
['Muscles intercostaux et respiration','Les muscles intercostaux occupent les espaces entre les côtes avec des orientations de fibres différentes. Leur action dépend des faisceaux et de la situation respiratoire. La respiration forcée peut recruter des muscles supplémentaires. L’expiration calme repose largement sur le recul élastique, tandis que l’expiration active implique notamment les muscles abdominaux. Le volume thoracique dépend aussi du mouvement des côtes et du sternum : il ne varie pas uniquement par un déplacement vertical du diaphragme.'],
['Paroi abdominale','Oblique externe, oblique interne et transverse constituent des plans latéraux ; le droit de l’abdomen se situe en avant. Leurs aponévroses participent à la gaine du droit et à la ligne blanche, avec une organisation variable selon le niveau. Ces muscles contribuent aux mouvements du tronc et au contrôle de pression. Rotation, inclinaison et flexion doivent être décrites en précisant les côtés activés. Le canal inguinal est un passage oblique dans la paroi, pas un défaut universellement ouvert.'],
['Posture et coopération','Les muscles profonds du dos participent au contrôle segmentaire, tandis que les muscles plus étendus produisent et freinent des mouvements. Plancher pelvien, paroi abdominale et diaphragme coopèrent dans les variations de pression. Une stabilisation peut mobiliser des contractions sans mouvement visible important. Pour apprendre, reliez chaque muscle à ses attaches, son orientation et sa fonction dominante, puis replacez-le dans une tâche globale. Le modèle 3D montre des surfaces ; il ne simule pas la mécanique complète des pressions.']
],glossary:[['Centre tendineux','Région centrale tendineuse vers laquelle convergent les fibres diaphragmatiques.'],['Nerf phrénique','Nerf assurant notamment l’innervation motrice du diaphragme.'],['Aponévrose','Lame tendineuse participant à la transmission des forces.'],['Ligne blanche','Raphé aponévrotique médian de la paroi abdominale antérieure.']],recall:'La contraction diaphragmatique diminue-t-elle normalement le volume thoracique ?',answer:'Non. L’abaissement des coupoles contribue à son augmentation.',trap:'L’expiration calme n’exige pas la même activité musculaire que l’expiration forcée.',refs:['11-4-axial-muscles-of-the-abdominal-wall-and-thorax','22-3-the-process-of-breathing']},
{id:'anat-spinal-cord',title:'Moelle épinière, méninges et nerfs spinaux',tag:'Neuroanatomie',sections:[
['Moelle et colonne ne se confondent pas','La moelle se situe dans le canal vertébral mais ne l’occupe pas jusqu’au coccyx chez l’adulte. Son extrémité, le cône médullaire, se projette habituellement autour de L1–L2, avec des variations. Les racines inférieures descendent avant de sortir et forment la queue de cheval. Un niveau vertébral et un segment médullaire sont donc deux repères distincts. Cette différence est essentielle pour comprendre les coupes et les trajets des racines.'],
['Substance grise et substance blanche','En coupe, la substance grise occupe une région centrale en forme de H ; la substance blanche est périphérique. Les cornes dorsales participent notamment aux traitements sensitifs ; les cornes ventrales contiennent des neurones moteurs somatiques. Des régions intermédiaires comportent des neurones autonomes selon le niveau. La substance blanche contient des voies ascendantes et descendantes. Une couleur dans l’atlas n’est pas une coloration histologique : les termes décrivent une organisation tissulaire.'],
['Racines et nerf mixte','La racine dorsale est associée aux informations afférentes et porte un ganglion contenant des corps cellulaires sensitifs. La racine ventrale transporte des efférences. Leur réunion forme un nerf spinal mixte, qui se divise ensuite en rameaux. Un rameau dorsal n’est pas simplement une racine dorsale renommée : il contient des fibres de fonctions différentes après la réunion. Les mots racine, nerf et rameau doivent être appris comme des étapes successives du trajet.'],
['Plexus et territoires','Les rameaux ventraux participent à des plexus dans plusieurs régions, notamment cervicale, brachiale, lombaire et sacrale. Les nerfs périphériques qui en émergent réunissent des contributions de plusieurs segments. Un territoire cutané de nerf périphérique n’est donc pas identique à un dermatome. Les territoires se chevauchent et les schémas sont des repères. Les nerfs intercostaux illustrent une organisation différente de celle d’un plexus complexe du membre.'],
['Méninges et liquide cérébrospinal','Dure-mère, arachnoïde et pie-mère entourent le système nerveux central. L’espace subarachnoïdien contient le liquide cérébrospinal ; il ne faut pas le confondre avec l’espace épidural. Le sac dural se prolonge sous l’extrémité médullaire. Les enveloppes, les racines et les espaces ont des rapports différents. Une représentation d’une moelle nue n’enseigne donc pas à elle seule les limites de chaque espace méningé.'],
['Arc réflexe et voies longues','Un arc réflexe associe entrée sensorielle, intégration et sortie motrice. Des circuits locaux peuvent produire une réponse tout en transmettant l’information vers d’autres niveaux. Les voies longues relient moelle et encéphale ; certaines croisent à des niveaux spécifiques. Ne généralisez pas une règle de croisement à toutes les voies. Pour restituer un trajet, indiquez successivement récepteur, fibre, racine, relais, éventuel croisement et cible. Cette méthode relie anatomie et neurophysiologie sans confondre leurs niveaux de description.']
],glossary:[['Cône médullaire','Extrémité inférieure de la moelle épinière adulte.'],['Queue de cheval','Ensemble de racines descendant sous le cône médullaire.'],['Ganglion spinal','Ganglion de la racine dorsale contenant des corps cellulaires sensitifs.'],['Dermatome','Territoire cutané rattaché principalement à un segment spinal.']],recall:'Un rameau dorsal est-il exclusivement sensitif ?',answer:'Non. Après la réunion des racines, les rameaux des nerfs spinaux contiennent des fibres de plusieurs fonctions.',trap:'Un niveau vertébral ne correspond pas toujours au segment médullaire de même numéro.',refs:['13-2-the-central-nervous-system','13-3-circulation-and-the-central-nervous-system','13-4-the-peripheral-nervous-system']},
{id:'anat-cranial-nerves',title:'Les douze nerfs crâniens : noms, fonctions et trajets de référence',tag:'Neuroanatomie',sections:[
['Une numérotation ordonnée','Les douze paires sont numérotées I à XII. Leur classification fonctionnelle distingue contributions sensorielles, motrices somatiques et autonomes. Les nerfs olfactif et optique présentent des particularités par rapport à la plupart des autres nerfs crâniens. La numérotation ne classe pas les nerfs par importance ou par longueur. Pour réviser, associez à chaque numéro un nom, une fonction dominante et un repère de trajet avant d’ajouter les noyaux et foramens détaillés.'],
['I et II : olfaction et vision','I est le nerf olfactif, lié à l’olfaction. II est le nerf optique, lié à la voie visuelle depuis la rétine. Au chiasma, certaines fibres croisent selon leur origine rétinienne ; toutes les fibres d’un œil ne changent pas de côté. Une voie sensorielle comprend plusieurs relais au-delà du nerf. Il faut donc distinguer l’organe récepteur, le nerf et les centres de traitement.'],
['III, IV et VI : mouvements oculaires','III est l’oculomoteur ; IV le trochléaire ; VI l’abducens. Ils participent à l’innervation des muscles oculomoteurs. Le droit latéral relève du VI et l’oblique supérieur du IV ; la majorité des autres muscles extraoculaires moteurs relèvent du III. Le III possède aussi une composante parasympathique liée notamment à la pupille et à l’accommodation. Les actions musculaires dépendent de la position de l’œil : un nom de muscle ne résume pas tout son effet.'],
['V et VII : face et fonctions multiples','V est le trijumeau. Ses divisions ophtalmique, maxillaire et mandibulaire distribuent des territoires sensitifs ; la mandibulaire transporte aussi des fibres motrices de mastication. VII est le facial, participant notamment à la motricité de l’expression faciale, à une partie du goût et à des fonctions parasympathiques. La sensibilité de la face et sa motricité d’expression ne relèvent donc pas du même nerf principal. Un nerf mixte n’a pas une seule fonction.'],
['VIII, IX et X : audition, pharynx et viscères','VIII est le vestibulocochléaire, lié à l’audition et à l’équilibre. IX est le glossopharyngien ; X le vague. Ces derniers réunissent plusieurs modalités, avec des territoires pharyngés et viscéraux distincts. Le vague se prolonge dans thorax et abdomen ; son nom crânien n’implique pas un territoire limité à la tête. Les fonctions de déglutition, sensibilité et régulation autonome exigent une lecture par composantes plutôt qu’une étiquette unique.'],
['XI et XII, puis méthode de synthèse','XI est l’accessoire, associé notamment au sternocléidomastoïdien et au trapèze. XII est l’hypoglosse, moteur de la langue pour la plupart de ses muscles. Pour mémoriser les douze : olfactif, optique, oculomoteur, trochléaire, trijumeau, abducens, facial, vestibulocochléaire, glossopharyngien, vague, accessoire, hypoglosse. Vérifiez le décompte et l’ordre avec une grille I–XII ; les listes récitées trop vite omettent facilement un nerf.']
],glossary:[['Trijumeau V','Nerf majeur de la sensibilité faciale, avec une composante motrice mandibulaire.'],['Abducens VI','Nerf innervant le muscle droit latéral de l’œil.'],['Vestibulocochléaire VIII','Nerf des informations auditives et vestibulaires.'],['Vague X','Nerf mixte dont les territoires comprennent des viscères thoracoabdominaux.']],recall:'Quel nerf innerve le droit latéral de l’œil ?',answer:'L’abducens, VI.',trap:'Le facial n’assure pas à lui seul toute la sensibilité de la face.',refs:['13-4-the-peripheral-nervous-system','16-3-the-cranial-nerve-exam']},
{id:'anat-eye',title:'Œil et voies visuelles : enveloppes, milieux et rétine',tag:'Tête et cou',sections:[
['Trois enveloppes','Le globe associe une enveloppe fibreuse, une couche vasculaire et une couche nerveuse. La sclère et la cornée appartiennent à l’enveloppe fibreuse ; la choroïde, le corps ciliaire et l’iris participent à la couche vasculaire. La rétine contient le dispositif récepteur et de premiers traitements. Une coupe doit distinguer les parois des milieux transparents : une cavité n’est pas un tissu supplémentaire.'],
['Le trajet optique','La lumière traverse notamment cornée, humeur aqueuse, pupille, cristallin et milieu vitré avant d’atteindre la rétine. La pupille est une ouverture de l’iris, pas une lentille noire. Cornée et cristallin contribuent à la réfraction, avec des propriétés différentes. Le cristallin peut modifier sa forme pour l’accommodation. La quantité de lumière admise et la mise au point ne correspondent pas au même mécanisme.'],
['Humeur aqueuse et pression','L’humeur aqueuse est produite au niveau des procès ciliaires et circule entre des compartiments avant son drainage. Les voies d’écoulement participent à l’équilibre de pression. Le corps vitré est un milieu différent, occupant la grande cavité postérieure. Les termes chambre antérieure, chambre postérieure et cavité vitréenne ne doivent pas être utilisés comme synonymes. Situez l’iris et le cristallin pour reconstruire correctement leurs limites.'],
['La rétine','Les photorécepteurs transforment le signal lumineux en signal biologique. Bâtonnets et cônes ont des propriétés différentes. La fovéa est une région spécialisée de la rétine ; le disque optique correspond au départ du nerf optique et ne possède pas de photorécepteurs. Les cellules rétiniennes forment des circuits avant la sortie du signal. Voir une région dans l’atlas ne permet pas d’en reproduire les performances fonctionnelles.'],
['Voies visuelles','Les axones des cellules ganglionnaires constituent le nerf optique. Le chiasma organise un croisement partiel ; les voies se poursuivent vers des relais et le cortex visuel. Les hémichamps visuels ne correspondent pas simplement à œil droit et œil gauche. Pour raisonner, distinguez côté de l’objet, région rétinienne stimulée et trajet des fibres. Une règle mémorisée sans dessin conduit facilement à inverser le repère.'],
['Orbite et motricité','Les muscles extraoculaires orientent le globe ; III, IV et VI répartissent leur innervation motrice. Paupières et appareil lacrymal contribuent à la protection de la surface. Le globe n’occupe donc pas seul l’orbite. Pour apprendre une coupe, placez d’abord les enveloppes, puis les milieux, les muscles et les voies. L’atlas est une aide spatiale ; il ne remplace pas une étude histologique des couches rétiniennes ni un examen ophtalmologique.']
],glossary:[['Cornée','Partie antérieure transparente de l’enveloppe fibreuse.'],['Pupille','Ouverture de l’iris laissant passer la lumière.'],['Fovéa','Région rétinienne spécialisée dans la vision centrale fine.'],['Disque optique','Zone de départ du nerf optique dépourvue de photorécepteurs.']],recall:'La pupille est-elle une lentille ?',answer:'Non. C’est une ouverture de l’iris ; le cristallin est une lentille.',trap:'Chambre postérieure et cavité vitréenne sont deux espaces différents.',refs:['14-1-sensory-perception','16-3-the-cranial-nerve-exam']},
{id:'anat-ear',title:'Oreille : transmission du son, cochlée et équilibre',tag:'Tête et cou',sections:[
['Trois régions','L’oreille externe comprend pavillon et conduit auditif externe. Le tympan sépare ce conduit de la cavité de l’oreille moyenne. L’oreille interne contient des structures auditives et vestibulaires dans l’os temporal. Les trois régions n’assurent pas la même opération : recueillir, transmettre mécaniquement et convertir les signaux. Pour lire une coupe, partez de l’extérieur et reconstruisez les limites avant de nommer les cavités internes.'],
['Les trois osselets','Marteau, enclume et étrier forment la chaîne ossiculaire de l’oreille moyenne. Le marteau est lié au tympan ; l’étrier transmet des mouvements à la fenêtre vestibulaire, dite ovale. La chaîne contribue à l’adaptation de la transmission entre milieux. Les osselets sont de vrais os nommés, pas des prolongements de la membrane tympanique. La fenêtre cochléaire, dite ronde, possède un rôle complémentaire dans les déplacements des liquides.'],
['Cavité moyenne et trompe','La trompe pharyngotympanique relie l’oreille moyenne au nasopharynx et participe à l’équilibrage des pressions. Ce n’est pas un passage vers le conduit auditif externe. Les muscles de l’oreille moyenne modifient les propriétés de transmission dans certains contextes. La présence d’une communication aérienne ne signifie pas que la cochlée soit remplie d’air : l’oreille interne possède des compartiments liquidiens distincts.'],
['Cochlée et transduction','La cochlée comprend des compartiments séparés par des structures membranaires. Les mouvements mécaniques participent à la stimulation des cellules ciliées de l’organe spiral. Leur organisation permet un codage spatial des fréquences. La conversion du signal n’est donc pas un simple microphone placé au hasard dans une cavité. Les propriétés des membranes et des liquides comptent autant que la forme générale visible du labyrinthe.'],
['Vestibule et canaux','Utricule et saccule participent à la détection d’accélérations linéaires et de l’orientation par rapport à la gravité. Les canaux semicirculaires participent surtout à la détection de rotations. Leurs orientations complémentaires permettent une information tridimensionnelle. L’équilibre dépend aussi de la vision et des informations somatosensorielles. Une sensation de position n’est donc pas produite par un organe isolé sans intégration centrale.'],
['Le nerf VIII et les relais','Les composantes cochléaire et vestibulaire rejoignent le nerf vestibulocochléaire VIII puis leurs relais centraux. Les voies auditives comportent des traitements bilatéraux ; les circuits vestibulaires participent notamment au contrôle du regard et de la posture. Pour restituer le cours, suivez séparément un son et une rotation de la tête. Le premier parcours commence par le tympan et les osselets ; le second mobilise des récepteurs vestibulaires différents.']
],glossary:[['Marteau','Osselet lié au tympan dans la chaîne de transmission.'],['Étrier','Osselet transmettant le mouvement à la fenêtre vestibulaire.'],['Cochlée','Partie de l’oreille interne spécialisée dans l’audition.'],['Canal semicirculaire','Structure vestibulaire participant à la détection des rotations.']],recall:'Nommez les trois osselets dans l’ordre depuis le tympan.',answer:'Marteau, enclume, étrier.',trap:'La trompe pharyngotympanique ne relie pas le conduit auditif externe à la cochlée.',refs:['14-1-sensory-perception','16-3-the-cranial-nerve-exam']},
{id:'anat-lymphatic',title:'Réseau lymphatique, ganglions, rate et thymus',tag:'Thorax',sections:[
['Un réseau de retour','Les vaisseaux lymphatiques recueillent une partie du liquide interstitiel et participent à son retour vers la circulation veineuse. Les capillaires initiaux et les collecteurs ont des propriétés différentes. Le trajet traverse des territoires ganglionnaires selon la région. Un réseau lymphatique n’est pas un troisième circuit sanguin fermé doté d’une pompe centrale identique au cœur. Mouvements, gradients et valvules contribuent à la progression.'],
['Drainages régionaux','Les territoires cervicaux, axillaires, thoraciques, abdominaux, pelviens et inguinaux présentent des réseaux de drainage. Un groupe ganglionnaire se définit par sa position et ses afférences, pas par une fonction immunitaire totalement indépendante. Les communications et variations limitent les schémas trop rigides. Le drainage lymphatique d’un organe ne suit pas nécessairement le trajet le plus court visible sur une image superficielle.'],
['Conduits terminaux','Le conduit thoracique draine une grande partie du corps vers une jonction veineuse cervicale gauche. Le territoire supérieur droit possède une organisation de retour distincte, avec des variations. Les termes gauche et droit se rapportent au sujet. Une vue de face peut inverser l’intuition du lecteur. Pour mémoriser, commencez par les territoires globaux puis ajoutez les troncs ; n’inférez pas chaque petite branche à partir d’un seul conduit dessiné.'],
['Ganglion : architecture et circulation','Un ganglion reçoit des vaisseaux afférents et possède une voie efférente au niveau du hile. Cortex, paracortex et médulla organisent des compartiments cellulaires et des trajets. Les lymphocytes circulent selon des mécanismes de recrutement et de sortie. Le ganglion n’est pas seulement un filtre passif : il participe aux rencontres entre antigènes et cellules. Une coupe histologique permet d’étudier des zones que le volume externe de l’atlas ne montre pas entièrement.'],
['Rate et thymus','La rate est un organe lymphoïde associé à la circulation sanguine. Ses régions participent à la surveillance immunitaire et au traitement des éléments sanguins. Elle ne filtre pas la lymphe comme un ganglion placé sur un collecteur. Le thymus est un organe lymphoïde primaire lié à la maturation et à la sélection des lymphocytes T. Sa composition évolue avec l’âge. Position, circulation et rôle doivent être appris ensemble.'],
['Relier anatomie et immunologie','Les organes lymphoïdes primaires et secondaires contribuent à des étapes différentes de la vie des lymphocytes. Moelle osseuse, thymus, ganglions, rate et tissus lymphoïdes muqueux ne sont pas interchangeables. Dans ce cours d’anatomie, l’objectif est de les situer et de reconstruire leurs rapports. Les mécanismes de reconnaissance, d’activation et de mémoire restent étudiés dans la matière Immunologie, afin de garder deux parcours ordonnés plutôt que de mélanger les chapitres.']
],glossary:[['Vaisseau afférent','Vaisseau conduisant la lymphe vers un ganglion.'],['Vaisseau efférent','Vaisseau évacuant la lymphe d’un ganglion.'],['Thymus','Organe lymphoïde primaire participant à la maturation des lymphocytes T.'],['Rate','Organe lymphoïde connecté à la circulation sanguine.']],recall:'La rate filtre-t-elle la lymphe comme un ganglion ?',answer:'Non. Son organisation est associée à la circulation sanguine.',trap:'Anatomie du réseau et mécanismes immunitaires sont complémentaires mais ne constituent pas le même chapitre.',refs:['21-1-anatomy-of-the-lymphatic-and-immune-systems','21-3-the-adaptive-immune-response-t-lymphocytes-and-their-functional-types']}
]
export const regionalSystemCourses:Course[]=drafts.map(c=>({...c,category:'Anatomie',structure:null,minutes:Math.ceil(c.sections.map(s=>s[1]).join(' ').split(/\s+/).length/150)+8,objectives:c.sections.slice(0,3).map(s=>'Expliquer : '+s[0].toLocaleLowerCase('fr')),sections:c.sections.map(([title,text])=>({title,text})),caseStudy:{prompt:c.recall,answer:c.answer},source:base+c.refs[0],sources:c.refs.map(ref=>({label:'OpenStax · '+ref.split('-').slice(0,2).join('.'),url:base+ref}))}))
export const regionalSystemSupport=courseSupport(regionalSystemCourses)
