import type {Course} from './curriculum'
import {courseSupport} from './courseSupport'
const base='https://openstax.org/books/anatomy-and-physiology-2e/pages/'
const references=['27-1-anatomy-and-physiology-of-the-testicular-reproductive-system','27-2-anatomy-and-physiology-of-the-ovarian-reproductive-system','28-1-fertilization','28-6-lactation']
export const reproductiveCourses:Course[]=[
{id:'anat-female-pelvis',title:'Appareil reproducteur féminin : ovaires, trompes, utérus et vulve',category:'Anatomie',tag:'Pelvis et périnée',minutes:16,structure:'HRA-uterus',objectives:['Reconstruire les rapports pelviens','Distinguer ovaires, trompes, utérus, vagin et vulve','Relier organisation anatomique et cycles'],sections:[
{title:'Une organisation pelvienne à reconstruire',text:'En coupe sagittale, l’appareil urinaire se situe en avant et le rectum en arrière. L’utérus et le vagin occupent une position intermédiaire, avec des rapports dépendant de la position, de la réplétion des organes et des variations individuelles. Le plancher pelvien assure un soutien ; le péritoine se réfléchit entre les viscères et forme notamment les culs-de-sac vésico-utérin et recto-utérin. Ces espaces ne sont pas des organes supplémentaires. Le modèle féminin HRA est une référence composite à couverture partielle : il faut distinguer ce qu’il représente de l’ensemble des structures enseignées ici.'},
{title:'Ovaires et follicules',text:'Les ovaires sont des gonades associant une fonction gamétogène et une fonction endocrine. Le cortex contient des follicules à différents stades ; la médulla contient notamment des éléments vasculonerveux. Un follicule associe un ovocyte et des cellules de soutien. La folliculogenèse ne se confond pas avec la méiose de l’ovocyte. Après l’ovulation, les cellules du follicule transformé participent au corps jaune. Le ligament propre de l’ovaire le relie à l’utérus ; le ligament suspenseur contient le pédicule ovarien. Ces attaches ont des rapports différents et ne sont pas interchangeables.'},
{title:'Les trompes ne forment pas un conduit fermé avec l’ovaire',text:'Chaque trompe comporte un pavillon avec des franges, une ampoule, un isthme et une portion traversant la paroi utérine. Son extrémité latérale s’ouvre au voisinage de l’ovaire. L’ovocyte libéré est recueilli ; il ne passe pas directement dans un tuyau soudé à la gonade. Les mouvements ciliaires et musculaires contribuent au transport. La fécondation se produit habituellement dans l’ampoule, tandis que l’implantation se produit normalement dans l’endomètre utérin. Confondre lieu de fécondation et lieu d’implantation est une erreur de raisonnement fréquente.'},
{title:'Utérus, paroi et col',text:'L’utérus comporte un fond, un corps et un col. L’endomètre tapisse la cavité ; le myomètre constitue une importante couche musculaire ; le revêtement extérieur varie selon les faces. L’endomètre répond aux signaux hormonaux et subit des transformations cycliques. Le col comporte un canal reliant cavité utérine et vagin, avec des orifices interne et externe. Le ligament large est un double feuillet péritonéal : il ne constitue pas à lui seul tout le système de soutien. Fascias, ligaments et plancher pelvien contribuent aux rapports et à la stabilité.'},
{title:'Vagin, vulve et glandes mammaires',text:'Le vagin est un conduit fibromusculaire s’étendant du col vers le vestibule. La vulve désigne les structures génitales externes, notamment lèvres, vestibule et clitoris. L’orifice urétral est distinct de l’orifice vaginal. Le clitoris comporte des tissus érectiles dont seule une partie est directement visible extérieurement. La forme des structures externes varie : leur aspect ne permet pas de conclure à une histoire sexuelle. Les glandes mammaires associent unités sécrétrices, conduits, tissu adipeux et soutien conjonctif. La production et l’éjection du lait impliquent des mécanismes hormonaux distincts.'},
{title:'Relier cycle ovarien et cycle utérin',text:'Le cycle ovarien comporte une phase folliculaire, l’ovulation et une phase lutéale. Le cycle utérin décrit les changements de l’endomètre. Ces deux cycles sont coordonnés mais ne sont pas deux noms pour le même phénomène. Les gonadotrophines et les hormones ovariennes forment des boucles de régulation, avec un changement de rétrocontrôle autour de l’ovulation. Les durées varient ; un schéma à vingt-huit jours est un exemple pédagogique, pas une règle applicable à chaque personne. Pour restituer le mécanisme, reliez une structure, le signal qu’elle produit, sa cible et l’effet tissulaire.'}
],glossary:[['Follicule ovarien','Association d’un ovocyte avec ses cellules de soutien.'],['Ampoule tubaire','Partie élargie de la trompe où a habituellement lieu la fécondation.'],['Endomètre','Muqueuse tapissant la cavité du corps utérin.'],['Myomètre','Couche musculaire majeure de la paroi utérine.']],trap:'Vulve et vagin désignent des structures différentes ; l’urètre ne se termine pas dans le vagin.',recall:'Distinguez les sites habituels de fécondation et d’implantation.',answer:'La fécondation a habituellement lieu dans l’ampoule tubaire ; l’implantation normale se fait dans l’endomètre utérin.',caseStudy:{prompt:'Un schéma dessine ovaire, trompe et utérus comme un unique conduit continu. Que faut-il corriger ?',answer:'L’ovaire n’est pas directement soudé à la trompe par une lumière commune. Le pavillon s’ouvre à son voisinage et recueille l’ovocyte ; la trompe communique ensuite avec la cavité utérine.'},source:base+references[1],sources:references.slice(1).map(ref=>({label:'OpenStax · '+ref.split('-').slice(0,2).join('.'),url:base+ref}))},
{id:'anat-male-pelvis',title:'Appareil reproducteur masculin : testicules, voies et glandes',category:'Anatomie',tag:'Pelvis et périnée',minutes:16,structure:'FMA9600',objectives:['Suivre le trajet des spermatozoïdes','Situer prostate et glandes annexes','Distinguer gamétogenèse, sécrétions et transport'],sections:[
{title:'Du scrotum au pelvis',text:'Les testicules sont contenus dans le scrotum ; leurs voies excrétrices rejoignent le pelvis puis l’urètre. Le cordon spermatique contient notamment le conduit déférent et des éléments vasculonerveux. Il traverse le canal inguinal. Testicule et prostate ne sont ni voisins directs ni deux glandes de même fonction. La prostate est située sous la vessie, en avant du rectum. Les variations anatomiques et les modifications liées à l’âge doivent être distinguées de cette description de référence ; un modèle ne représente pas toutes les personnes.'},
{title:'Tubes séminifères, Sertoli et Leydig',text:'Les tubes séminifères hébergent les étapes de la spermatogenèse au sein d’un épithélium spécialisé. Les cellules de Sertoli soutiennent les cellules germinales et contribuent à l’organisation de leur environnement. Les cellules de Leydig, interstitielles, participent à la production de testostérone. Les spermatozoïdes ne sont donc pas fabriqués par la prostate ni par les glandes séminales. La méiose réduit le nombre de jeux chromosomiques ; la spermiogenèse transforme ensuite les cellules haploïdes sans constituer une nouvelle division méiotique.'},
{title:'Le trajet excréteur',text:'Les tubes séminifères se poursuivent vers les tubes droits, le rete testis et les ductules efférents. Ceux-ci rejoignent l’épididyme, où les spermatozoïdes poursuivent leur maturation et peuvent être stockés. Le conduit déférent remonte dans le cordon puis suit un trajet pelvien. Il rejoint le conduit d’une glande séminale pour constituer un conduit éjaculateur, qui traverse la prostate et débouche dans l’urètre prostatique. Chaque transition doit être apprise dans cet ordre, en distinguant le trajet des gamètes des sécrétions ajoutées en cours de route.'},
{title:'Glandes annexes et liquide séminal',text:'Les glandes séminales sont situées en arrière de la vessie et contribuent au liquide séminal. La prostate entoure une partie de l’urètre et ajoute également des sécrétions. Les glandes bulbo-urétrales participent à la lubrification de la voie. Le sperme associe spermatozoïdes et sécrétions : ces mots ne sont pas synonymes. Le rôle d’une glande doit être lié à son conduit de drainage et à sa position. Une coupe de la prostate peut montrer des voies qui la traversent sans signifier qu’elle produit les cellules transportées.'},
{title:'Urètre et tissus érectiles',text:'L’urètre masculin traverse plusieurs régions successives, notamment prostatique, intermédiaire et spongieuse. Il appartient au trajet urinaire et à la voie d’évacuation du sperme, avec une coordination fonctionnelle. Le pénis comprend deux corps caverneux et un corps spongieux entourant l’urètre spongieux et se poursuivant dans le gland. Érection, émission et expulsion du sperme sont des processus distincts, impliquant des mécanismes vasculaires, autonomes et somatiques. Les dimensions et formes individuelles varient et ne constituent pas un critère de fonction à partir du seul aspect.'},
{title:'Régulation et comparaison des références',text:'La commande gonadotrope implique hypothalamus, hypophyse et testicule. La LH agit notamment sur les cellules de Leydig ; la FSH participe à l’action des cellules de Sertoli et au soutien de la spermatogenèse. Testostérone et inhibine contribuent aux rétrocontrôles. Pour comparer les appareils reproducteurs, distinguez gonades, voies, glandes annexes et tissus externes plutôt que d’opposer deux listes sans logique. Les corps masculin BodyParts3D et féminin HRA proviennent de références différentes : leurs différences visuelles incluent des différences de donneurs, de couverture et de méthode de modélisation.'}
],glossary:[['Cellule de Sertoli','Cellule de soutien de l’épithélium séminifère.'],['Cellule de Leydig','Cellule interstitielle testiculaire participant à la production de testostérone.'],['Épididyme','Voie où les spermatozoïdes poursuivent leur maturation après les ductules efférents.'],['Conduit déférent','Conduit reliant la région épididymaire aux voies éjaculatrices pelviennes.']],trap:'Les glandes séminales et la prostate contribuent au liquide séminal mais ne produisent pas les spermatozoïdes.',recall:'Quel organe produit les spermatozoïdes et quelle voie leur permet ensuite de mûrir ?',answer:'Ils sont produits dans les tubes séminifères du testicule ; leur maturation se poursuit notamment dans l’épididyme.',caseStudy:{prompt:'Un étudiant explique que des spermatozoïdes produits par la prostate remontent ensuite jusqu’au testicule. Quelle chaîne faut-il reconstruire ?',answer:'Le trajet part du testicule, rejoint rete testis, ductules efférents, épididyme, déférent, conduit éjaculateur puis urètre. La prostate apporte des sécrétions à une voie traversante.'},source:base+references[0],sources:references.slice(0,2).map(ref=>({label:'OpenStax · '+ref.split('-').slice(0,2).join('.'),url:base+ref}))}
]
export const reproductiveSupport=courseSupport(reproductiveCourses)
reproductiveSupport.diagrams['anat-female-pelvis']={title:'De l’ovaire à l’utérus : des étapes différentes',caption:'Parcours fonctionnel simplifié. L’ovaire n’est pas soudé à la trompe ; fécondation et implantation ont des sites habituels différents.',kind:'flow',nodes:[{label:'Ovaire',detail:'Le follicule accompagne la maturation de l’ovocyte.'},{label:'Ovulation',detail:'L’ovocyte est libéré et recueilli au voisinage du pavillon.'},{label:'Trompe',detail:'Transport ciliaire et musculaire ; fécondation habituellement dans l’ampoule.'},{label:'Utérus',detail:'Lieu de l’implantation normale dans l’endomètre.'}]}
reproductiveSupport.diagrams['anat-male-pelvis']={title:'Suivre les voies spermatiques',caption:'Les glandes annexes ajoutent des sécrétions ; les spermatozoïdes sont produits dans le testicule.',kind:'flow',nodes:[{label:'Testicule',detail:'Production dans les tubes séminifères puis passage vers le rete testis et les ductules efférents.'},{label:'Épididyme',detail:'Maturation et stockage.'},{label:'Déférent',detail:'Transport vers le pelvis et les voies éjaculatrices.'},{label:'Conduit éjaculateur',detail:'Traverse la prostate et rejoint l’urètre.'},{label:'Urètre',detail:'Voie d’évacuation vers l’extérieur.'}]}
