import type {Course} from './curriculum'
import type {Diagram} from './diagrams'
import type {Question} from './questions'
import {courseSupport} from './courseSupport'

// Synthèses pédagogiques originales. Les liens permettent de vérifier les repères
// et d'approfondir ; aucun texte ni schéma de manuel n'est reproduit.
const base='https://openstax.org/books/anatomy-and-physiology-2e/pages/'
type Chapter={id:string;title:string;tag:string;objectives:string[];sections:[string,string][];trap:string;recall:string;answer:string;glossary:[string,string][];caseStudy:{prompt:string;answer:string};refs:string[]}
const chapters:Chapter[]=[
{
 id:'anat-bone',title:'Le tissu osseux : architecture, croissance et remodelage',tag:'Principes',
 objectives:['Distinguer os, tissu osseux, cartilage et moelle','Expliquer les deux voies d’ossification et la croissance','Relier architecture, contraintes et remodelage'],
 sections:[
 ['Un organe vivant et plusieurs échelles',`Un os est un organe : il associe tissu osseux, moelle, vaisseaux, nerfs et revêtements conjonctifs. Le tissu osseux est un tissu conjonctif dont la matrice est minéralisée. La moelle remplit certains espaces internes ; elle ne correspond pas au matériau rigide de l’os. Le cartilage articulaire recouvre des surfaces de contact, mais ne recouvre pas uniformément toute la pièce osseuse. Ces distinctions permettent de relier une image macroscopique à une coupe histologique.

La classification morphologique distingue notamment os longs, courts, plats, irréguliers et sésamoïdes. « Long » décrit une organisation avec une dimension dominante : une phalange est un os long malgré sa petite taille. La patella est un os sésamoïde intégré à l’appareil tendineux du quadriceps. Une vertèbre est un os irrégulier ; un os pariétal est un os plat.`],
 ['Diaphyse, épiphyses et enveloppes',`Dans un os long, la diaphyse constitue le corps entre deux épiphyses. Les métaphyses sont les régions de transition ; pendant la croissance, les cartilages de conjugaison séparent les territoires épiphysaires des territoires métaphysaires. La cavité médullaire occupe une partie de la diaphyse. Une coupe montre que cortex et espaces médullaires n’ont pas la même épaisseur partout : la géométrie participe aux propriétés mécaniques de l’ensemble.

Le périoste recouvre la surface externe hors cartilage articulaire. Il porte une couche fibreuse et des cellules contribuant à la formation osseuse. L’endoste tapisse les surfaces internes. Les vaisseaux pénètrent par des orifices nourriciers et suivent des réseaux internes ; l’os n’est donc pas nourri uniquement par diffusion depuis la peau. Le périoste est innervé, ce qui aide à comprendre que la minéralisation n’implique pas une absence de sensibilité.`],
 ['Matrice et populations cellulaires',`La matrice organique contient principalement du collagène de type I ; sa minéralisation implique des cristaux riches en calcium et phosphate. La composante organique contribue à la résistance en traction et à une certaine ténacité ; la composante minérale contribue à la rigidité et à la résistance à la compression. Réduire la solidité à la seule quantité de calcium ferait oublier la qualité de la matrice et sa distribution.

Les ostéoblastes fabriquent l’ostéoïde, matrice encore non minéralisée. Certains deviennent des ostéocytes, enfermés dans des lacunes mais reliés par leurs prolongements et les canalicules. Les ostéoclastes sont de grandes cellules de résorption, issues d’une lignée différente. Formation et résorption sont coordonnées : un ostéoclaste ne se transforme pas simplement en ostéoblaste après avoir creusé une surface.`],
 ['Os compact et os trabéculaire',`L’os compact forme des régions denses, particulièrement visibles dans le cortex diaphysaire. Dans l’os lamellaire compact, les ostéons comportent des lamelles organisées autour de canaux vasculaires. Des canaux transversaux ou obliques relient ces réseaux. Toutes les lamelles ne constituent cependant pas un ostéon complet : des lamelles interstitielles et circonférentielles participent aussi à l’organisation.

L’os trabéculaire forme un réseau de travées séparées par des espaces médullaires. Les travées contiennent une matrice minéralisée : « spongieux » ne signifie pas mou. Leur orientation et leur connectivité contribuent au transfert des contraintes. Une même épiphyse associe souvent cortex périphérique et réseau trabéculaire interne. La moelle rouge réalise l’hématopoïèse ; sa répartition évolue avec l’âge et ne coïncide pas avec tout l’espace disponible dans tous les os.`],
 ['Former un os puis le faire grandir',`L’ossification intramembraneuse produit de l’os directement dans un tissu mésenchymateux, sans modèle cartilagineux préalable. Elle intervient notamment dans une partie des os de la voûte. L’ossification endochondrale remplace progressivement un modèle cartilagineux et contribue à la formation de nombreux os, dont les os longs. Le cartilage n’est pas seulement une version non minéralisée de l’os : les cellules et la matrice diffèrent.

Dans le cartilage de croissance, les chondrocytes prolifèrent puis augmentent de volume ; les territoires cartilagineux sont progressivement remplacés du côté métaphysaire. La croissance en longueur dépend du maintien de cette organisation. La croissance en épaisseur procède par apposition à la surface, accompagnée de remaniements internes. La fermeture du cartilage de conjugaison termine la croissance longitudinale normale de cette région, mais ne met pas fin au renouvellement du tissu osseux.`],
 ['Remodeler sans confondre croissance et réparation',`Le remodelage renouvelle localement une portion d’os par une séquence associant résorption et formation. Il participe à l’adaptation mécanique et aux échanges minéraux. Les ostéocytes détectent des modifications de leur environnement et contribuent aux signaux organisant cette adaptation. La réponse dépend de la durée, de la répétition et de la direction des contraintes ; elle ne se résume pas à « toute pression fabrique immédiatement plus d’os ».

La réparation après une fracture implique une succession de phénomènes, dont inflammation locale, stabilisation par des tissus provisoires, formation osseuse puis remodelage. Ce déroulement ne se confond ni avec la croissance d’un enfant ni avec un simple remplissage minéral d’une fissure. Pour expliquer un schéma, identifiez d’abord la matrice, les cellules actives et les surfaces concernées ; décrivez ensuite ce qui est ajouté, retiré ou remplacé au cours du temps.`],
 ],
 trap:'L’os spongieux est minéralisé. La moelle située entre ses travées n’est pas le tissu osseux lui-même.',recall:'Comment un os adulte peut-il se renouveler sans s’allonger ?',answer:'Le remodelage remplace localement de la matrice par résorption puis formation ; la croissance longitudinale nécessitait un cartilage de conjugaison actif.',
 glossary:[['Ostéoïde','Matrice organique osseuse avant sa minéralisation.'],['Ostéon','Organisation lamellaire du tissu compact autour d’un canal central.'],['Métaphyse','Région de transition entre diaphyse et épiphyse.'],['Remodelage','Renouvellement coordonné par résorption et formation.']],
 caseStudy:{prompt:'Sur une coupe, des travées minéralisées entourent des espaces riches en cellules sanguines. Un étudiant appelle tout l’ensemble « moelle ». Quelle distinction manque ?',answer:'Les travées sont du tissu osseux trabéculaire. Les espaces qu’elles délimitent contiennent de la moelle, tissu distinct. L’ensemble participe à un même organe osseux.'},refs:['6-3-bone-structure','6-4-bone-formation-and-development']
},
{
 id:'anat-neurocranium',title:'Neurocrâne : les huit os, les sutures et les fosses',tag:'Tête et cou',
 objectives:['Nommer les huit os du neurocrâne et leur position','Relier les sutures aux os qu’elles unissent','Orienter la base interne et ses trois fosses'],
 sections:[
 ['Compter huit os sans compter huit noms',`Le neurocrâne entoure l’encéphale et comprend huit os : un frontal, deux pariétaux, deux temporaux, un occipital, un sphénoïde et un ethmoïde. Les six noms correspondent donc à huit pièces, puisque les pariétaux et les temporaux sont pairs. Ce décompte conventionnel adulte exclut les os de la face, les osselets de l’ouïe et l’os hyoïde. Il permet de distinguer une nomenclature de types d’os d’un nombre de pièces anatomiques.

La calvaria, ou voûte, constitue le toit et une partie des parois. La base possède un relief plus complexe, traversé par des passages vasculaires et nerveux. Certains os participent à plusieurs territoires : le frontal contribue à la voûte et au toit des orbites ; l’ethmoïde appartient au neurocrâne tout en contribuant aux cavités nasales. La classification n’empêche donc pas les rapports avec la face.`],
 ['Frontal et pariétaux : orienter la voûte',`Le frontal forme le front, une partie du toit orbitaire et du plancher de la fosse crânienne antérieure. Une vue antérieure permet de repérer les rebords supraorbitaires. Une vue supérieure montre sa jonction avec les pariétaux. Le sinus frontal, lorsqu’il est développé, est une cavité pneumatique du frontal et non une chambre située entre deux os séparés.

Les deux pariétaux forment une grande partie du toit et des parois supérolatérales. Ils se rejoignent sur la ligne médiane. Pour orienter un pariétal, il faut combiner ses bords, ses faces et ses rapports plutôt que sa seule convexité. La face externe est globalement convexe ; la face interne comporte des empreintes et sillons liés aux structures voisines. Sur une préparation, une suture correspond à une union entre os, tandis qu’un sillon vasculaire marque la surface d’un même os.`],
 ['Temporaux et occipital : côtés et charnière crânienne',`Chaque temporal participe à la paroi latérale et à la base. Sa partie squameuse est aplatie ; sa partie pétreuse, ou rocher, contient des structures de l’oreille. Le processus zygomatique rejoint l’os zygomatique pour former l’arcade. Le processus mastoïde constitue un repère postéro-inférieur, tandis que le processus styloïde est une projection plus fine. La fosse mandibulaire reçoit le condyle mandibulaire avec l’interposition d’un disque articulaire.

L’occipital forme la région postérieure et une grande partie de la base postérieure. Son foramen magnum assure une communication entre cavité crânienne et canal vertébral. De part et d’autre, les condyles occipitaux s’articulent avec l’atlas. Les lignes nuchales et la protubérance occipitale externe sont des zones de repérage et d’attache. Condyle, foramen et ligne d’insertion ont donc des rôles différents malgré leur appartenance au même os.`],
 ['Sphénoïde et ethmoïde : les os centraux',`Le sphénoïde occupe une position centrale dans la base. Son corps porte la selle turcique, dont la fosse hypophysaire loge l’hypophyse. Les petites ailes, les grandes ailes et les processus ptérygoïdes s’étendent dans des directions différentes. Les ailes participent à des limites crâniennes et orbitaires ; les processus ptérygoïdes se dirigent vers le bas et offrent notamment des attaches à des muscles masticateurs.

L’ethmoïde se situe plus en avant. Sa lame criblée est traversée par les filets olfactifs ; la crista galli s’élève sur la ligne médiane. La lame perpendiculaire contribue à la cloison nasale osseuse. Ses masses latérales participent à la paroi médiale de l’orbite et portent les cornets supérieur et moyen. Le cornet inférieur, en revanche, est un os facial distinct. Cette distinction est importante pour compter correctement les os et comprendre les parois des fosses nasales.`],
 ['Sutures et développement de la voûte',`La suture coronale unit le frontal aux pariétaux. La sagittale sépare les deux pariétaux. La lambdoïde les unit à l’occipital en arrière. Les sutures squameuses concernent la jonction des pariétaux avec les parties squameuses des temporaux. Apprendre une suture revient à nommer ses deux côtés ; le seul tracé d’une ligne sans identification des os ne suffit pas.

Chez le jeune enfant, les fontanelles sont des régions membraneuses situées entre plusieurs pièces osseuses en développement. Elles ne sont pas des articulations synoviales et ne constituent pas une absence de tout tissu protecteur. Leur évolution accompagne la croissance crânienne. La région du ptérion correspond à la rencontre du frontal, du pariétal, de la grande aile du sphénoïde et du temporal. C’est un repère topographique local ; il ne faut pas en faire un neuvième os.`],
 ['Lire la base interne en trois étages',`La fosse antérieure accueille principalement les régions frontales ; elle implique notamment les lames orbitaires du frontal et l’ethmoïde. La fosse moyenne, plus profonde, comporte des territoires du sphénoïde et des temporaux et reçoit notamment les lobes temporaux. La fosse postérieure contient notamment le cervelet et des parties du tronc cérébral. Les limites osseuses ne constituent pas des cloisons isolant totalement ces régions nerveuses.

Pour lire une base interne, placez d’abord l’avant, puis identifiez la crista galli, la selle turcique, les bords supérieurs des rochers et le foramen magnum. Ces repères ordonnent les détails. Un orifice osseux se décrit avec son os, ses communications et son contenu principal, sans déduire son contenu de sa taille. La fiche suivante approfondit les passages et la face ; cette séparation évite de mélanger l’inventaire de la boîte crânienne avec celui des cavités faciales.`],
 ],
 trap:'Les huit os du neurocrâne correspondent à six noms, car pariétaux et temporaux sont pairs.',recall:'Quels os se rencontrent à la suture coronale ?',answer:'Le frontal en avant et les deux pariétaux en arrière.',glossary:[['Calvaria','Voûte osseuse du crâne.'],['Rocher','Partie pétreuse du temporal.'],['Selle turcique','Relief sphénoïdal entourant la fosse hypophysaire.'],['Suture','Union fibreuse entre os du crâne.']],
 caseStudy:{prompt:'Une lame médiane descend vers la cloison nasale depuis un os portant une lame criblée. Faut-il classer cet os parmi les quatorze os faciaux ?',answer:'Il s’agit de l’ethmoïde, classé parmi les huit os du neurocrâne. Sa participation aux fosses nasales ne change pas ce classement conventionnel.'},refs:['7-2-the-skull','7-5-embryonic-development-of-the-axial-skeleton']
},
{
 id:'anat-face',title:'Face et base du crâne : os, cavités et passages',tag:'Tête et cou',
 objectives:['Retrouver les quatorze os de la face','Construire les parois orbitaires, nasales et palatines','Distinguer mandibule, hyoïde, osselets et passages crâniens'],
 sections:[
 ['L’inventaire des quatorze os faciaux',`La face comprend six paires et deux os impairs dans le décompte anatomique adulte usuel. Les paires sont les maxillaires, les zygomatiques, les nasaux, les lacrymaux, les palatins et les cornets nasaux inférieurs. Les deux os impairs sont la mandibule et le vomer. On obtient douze os pairs comptés individuellement, plus deux impairs, soit quatorze. Les dents ne sont pas des os supplémentaires.

Ces pièces construisent des parois communes à plusieurs cavités. Les maxillaires portent les dents supérieures, participent au plancher orbitaire et constituent une large partie du palais dur. Les zygomatiques forment le relief des pommettes et participent à l’orbite. Les nasaux forment le pont osseux du nez ; sa partie mobile est cartilagineuse. Les lacrymaux sont de petites pièces de la région médiale des orbites, liées au trajet d’évacuation des larmes.`],
 ['Cloison nasale, cornets et palais',`Le vomer est un os médian qui contribue à la partie postéro-inférieure de la cloison nasale. La lame perpendiculaire de l’ethmoïde forme un autre territoire osseux de cette cloison, complétée en avant par du cartilage. Une cloison n’est donc pas nécessairement un os unique. Sur les parois latérales, les cornets augmentent la complexité du trajet aérien et de la surface muqueuse ; les supérieur et moyen appartiennent à l’ethmoïde, l’inférieur constitue un os séparé de chaque côté.

Le palais dur sépare la cavité orale des cavités nasales. Ses territoires antérieurs viennent des processus palatins des maxillaires ; sa partie postérieure vient des lames horizontales des palatins. Le palais mou prolonge cet ensemble en arrière, mais n’est pas une lame osseuse. Pour orienter une base externe, retrouver le palais donne immédiatement un repère antérieur et inférieur, utile avant de rechercher les régions sphénoïdales et occipitales.`],
 ['Construire une orbite avec plusieurs os',`Chaque orbite associe sept os : frontal, sphénoïde, zygomatique, maxillaire, palatin, lacrymal et ethmoïde. Le toit comprend surtout le frontal ; le plancher comprend surtout le maxillaire. La paroi médiale implique notamment l’ethmoïde et le lacrymal ; la paroi latérale associe notamment le zygomatique et le sphénoïde. Ces contributions sont inégales : citer sept noms ne signifie pas partager la cavité en sept surfaces identiques.

Le canal optique, situé dans le sphénoïde, laisse passer notamment le nerf optique et l’artère ophtalmique. La fissure orbitaire supérieure est un autre passage, notamment emprunté par des nerfs de la motricité oculaire et des branches sensitives. Elle ne doit pas être confondue avec le canal optique. Les sinus paranasaux occupent des cavités du frontal, du maxillaire, du sphénoïde et de l’ethmoïde ; ils ne correspondent pas aux espaces occupés par les globes oculaires.`],
 ['Mandibule et articulation temporomandibulaire',`La mandibule possède un corps incurvé et deux branches montantes. L’angle marque leur jonction. Le processus alvéolaire porte les dents inférieures. Chaque branche se termine en haut par un processus coronoïde antérieur et un processus condylaire postérieur, séparés par l’incisure mandibulaire. Le coronoïde reçoit une insertion du muscle temporal ; le condyle participe à l’articulation temporomandibulaire avec le temporal.

Cette articulation associe rotation et translation, avec un disque qui organise les contacts. L’ouverture importante de la bouche ne se décrit donc pas comme une simple charnière autour d’un axe immobile. Le foramen mandibulaire se situe sur la face médiale de la branche ; il donne accès au canal mandibulaire. Le foramen mentonnier est visible sur la face externe du corps. Ces deux orifices appartiennent à un trajet osseux, mais ne sont pas deux noms interchangeables pour une même ouverture.`],
 ['Osselets de l’ouïe et os hyoïde',`Chaque oreille moyenne possède trois osselets : marteau, enclume et étrier. Les trois de droite et les trois de gauche donnent six pièces supplémentaires, exclues du décompte des vingt-deux os du crâne proprement dit. Le marteau reçoit les vibrations du tympan ; la chaîne les transmet vers l’étrier, dont la base est en rapport avec la fenêtre vestibulaire. Ces pièces sont des os véritables, malgré leur faible taille et leur position dans le temporal.

L’os hyoïde est situé dans la région cervicale antérieure. Il comprend un corps, deux grandes cornes et deux petites cornes. Il n’établit pas d’articulation osseuse directe avec un autre os : muscles et ligaments assurent ses liaisons. Il participe à l’organisation de la langue et de la région laryngée. Les cartilages du larynx, comme le cartilage thyroïde, ne doivent pas être ajoutés à l’inventaire des os sous prétexte qu’ils peuvent devenir plus calcifiés avec l’âge.`],
 ['Passages de la base : associer trajet et territoire',`Le foramen magnum occipital est en continuité avec le canal vertébral. Le canal carotidien traverse le temporal et accompagne l’artère carotide interne. Le foramen jugulaire se situe entre temporal et occipital ; il est distinct du canal de l’hypoglosse occipital. Dans le sphénoïde, les foramens rond et ovale livrent respectivement passage aux divisions maxillaire et mandibulaire du nerf trijumeau. Une même famille nerveuse utilise ainsi plusieurs portes osseuses.

Pour apprendre sans juxtaposer des listes, reliez chaque trajet à une origine et à une destination : cavité crânienne vers orbite, vers face ou vers cou. Distinguez ensuite une fissure, un canal et un foramen. Les passages ne sont ni tous symétriques dans leurs dimensions ni tous exclusivement nerveux. Une représentation de surface de l’atlas peut masquer certains conduits internes : l’absence d’un trou visible sur un angle de vue ne prouve pas l’absence anatomique de ce passage.`],
 ],
 trap:'Les cornets supérieur et moyen appartiennent à l’ethmoïde ; seuls les deux cornets inférieurs sont comptés comme os faciaux indépendants.',recall:'Pourquoi les osselets ne font-ils pas passer le décompte conventionnel du crâne proprement dit de 22 à 28 ?',answer:'Le décompte de 22 additionne 8 os du neurocrâne et 14 os faciaux. Les 6 osselets sont comptés séparément dans le squelette axial.',glossary:[['Vomer','Os médian de la cloison nasale osseuse.'],['Palais dur','Cloison osseuse entre cavités orale et nasales.'],['Condyle mandibulaire','Extrémité articulaire du processus condylaire.'],['Hyoïde','Os cervical suspendu par des attaches musculaires et ligamentaires.']],caseStudy:{prompt:'Un os porte un processus coronoïde, un condyle et des alvéoles dentaires. De quelle pièce s’agit-il, et quelle partie s’articule avec le temporal ?',answer:'La mandibule. Son condyle participe à l’articulation temporomandibulaire ; le processus coronoïde est surtout un site d’insertion musculaire.'},refs:['7-2-the-skull','9-6-anatomy-of-selected-synovial-joints','15-3-hearing-and-equilibrium']
},
{
 id:'anat-cervical',title:'Rachis cervical : C1 à C7 et charnière crânienne',tag:'Rachis et thorax',
 objectives:['Orienter une vertèbre cervicale typique','Distinguer atlas, axis et C7','Relier articulations, mobilité et passages nerveux'],
 sections:[
 ['Le plan commun d’une vertèbre',`Une vertèbre typique associe un corps en avant et un arc en arrière. Les pédicules et les lames constituent cet arc ; ils délimitent avec le corps le foramen vertébral. La succession de ces foramens forme le canal vertébral. Les processus épineux, transverses et articulaires sont des projections dont les fonctions diffèrent : levier musculaire, attache ou surface de contact. Confondre un processus articulaire avec tout l’arc empêche de comprendre les mouvements entre étages.

Les foramens intervertébraux se forment latéralement entre des vertèbres adjacentes. Ils ne sont pas le grand orifice central d’une vertèbre isolée. Pour orienter une pièce, cherchez le corps, placez l’épine en arrière et observez l’orientation des facettes. Le rachis cervical compte sept vertèbres, numérotées C1 à C7 du haut vers le bas. Cette numérotation des os ne se confond pas avec celle des huit paires de nerfs spinaux cervicaux.`],
 ['C3 à C6 : reconnaître le type cervical',`Les vertèbres cervicales moyennes possèdent un corps relativement petit, un foramen vertébral souvent large et triangulaire, et des processus transverses percés d’un foramen transversaire. Ce dernier caractérise la région mais ne remplace pas le canal vertébral. Les processus épineux de plusieurs vertèbres cervicales sont bifides ; il s’agit d’un caractère fréquent, pas d’une règle absolue pour toutes les pièces et tous les sujets.

Les articulations entre corps associent les plateaux vertébraux et les disques intervertébraux. Les articulations postérieures mettent en contact les processus articulaires des vertèbres voisines. Leur orientation contribue à la combinaison possible de flexion, extension, inclinaison et rotation. Les reliefs unciformes des corps cervicaux inférieurs participent à l’organisation latérale de ces étages. Décrire la mobilité exige donc de considérer le segment constitué de plusieurs pièces et de tissus interposés, pas seulement un os isolé.`],
 ['Atlas : soutenir l’occiput sans corps vertébral typique',`L’atlas, C1, présente deux masses latérales reliées par un arc antérieur et un arc postérieur. Il n’a pas le corps volumineux ni le processus épineux d’une vertèbre typique. Ses surfaces articulaires supérieures reçoivent les condyles occipitaux. Cette relation situe la tête au-dessus du rachis et participe aux mouvements de flexion-extension de la charnière crânienne, comme un mouvement de « oui » simplifié.

La face postérieure de l’arc antérieur porte une surface en rapport avec la dent de l’axis. Un ligament transverse maintient cette dent contre l’arc antérieur, en séparant ce territoire de celui du canal contenant les structures nerveuses. Le ligament ne transforme pas la dent en partie de l’atlas : celle-ci appartient à C2. L’identification repose sur l’organisation en anneau, les masses latérales et les facettes, plutôt que sur la présence d’une épine cervicale habituelle.`],
 ['Axis : un pivot appartenant à C2',`L’axis, C2, porte la dent, ou processus odontoïde, qui s’élève depuis son corps. La rotation de l’atlas et du crâne autour de cette région contribue fortement à tourner la tête. La charnière atlanto-axoïdienne comporte une articulation médiane liée à la dent et deux articulations latérales. Il ne s’agit donc pas d’un clou osseux fixé dans une pièce dépourvue d’autres contacts.

Les moyens d’union stabilisent le pivot tout en autorisant la mobilité. Les ligaments alaires relient la région de la dent à l’occipital et participent à la limitation des mouvements. Entre l’occiput et C1, puis entre C1 et C2, il n’existe pas de disque intervertébral typique. Le premier disque cervical habituel se trouve entre C2 et C3. Ce détail aide à distinguer la mécanique particulière de la charnière supérieure de celle des étages cervicaux inférieurs.`],
 ['C7, les foramens et les nerfs cervicaux',`C7 est dite vertèbre proéminente en raison de son processus épineux souvent long et non bifide. La palpation ne permet toutefois pas toujours d’identifier un étage avec certitude : les reliefs et les positions individuelles varient. C7 marque une transition vers le rachis thoracique sans devenir une vertèbre thoracique normale. Elle conserve généralement des foramens transversaires, souvent de petite taille.

L’artère vertébrale pénètre habituellement dans les foramens transversaires à C6 puis monte vers les étages supérieurs ; des variantes existent. Il serait donc faux d’affirmer qu’elle traverse normalement chaque foramen de C1 à C7. Les nerfs spinaux empruntent d’autres passages. Les nerfs cervicaux C1 à C7 émergent au-dessus de la vertèbre homonyme, tandis que C8 émerge entre C7 et T1. À partir de T1, le repérage suit l’émergence sous la vertèbre de même numéro.`],
 ['Raisonner sur les mouvements et les espaces',`La mobilité globale du cou résulte de contributions successives. Une rotation ne concerne pas exclusivement l’axis ; une flexion ne se limite pas à l’articulation atlanto-occipitale. Les disques se déforment, les facettes glissent et les ligaments se tendent de façon coordonnée. Les muscles produisent et contrôlent les mouvements tout en participant à la stabilité. Un squelette désarticulé montre les surfaces mais pas ces conditions de fonctionnement.

Sur une coupe, séparez trois espaces : le canal vertébral central, les foramens intervertébraux latéraux et les foramens transversaires des processus. Associez ensuite contenu et niveau avant de décrire une relation. Cette méthode évite de faire passer la moelle dans un foramen transversaire ou de confondre une artère vertébrale avec un nerf spinal. L’objectif de première lecture est une carte cohérente des structures normales, préalable aux variations anatomiques et aux applications cliniques enseignées ultérieurement.`],
 ],trap:'Il existe sept vertèbres cervicales mais huit paires de nerfs cervicaux. La dent appartient à C2, pas à C1.',recall:'Où se trouve le premier disque intervertébral cervical habituel ?',answer:'Entre C2 et C3. Les articulations occiput–C1 et C1–C2 ont une organisation différente.',glossary:[['Atlas','Première vertèbre cervicale, organisée en anneau.'],['Axis','Deuxième vertèbre cervicale, portant la dent.'],['Foramen transversaire','Orifice d’un processus transverse cervical.'],['Foramen intervertébral','Passage latéral entre vertèbres adjacentes.']],caseStudy:{prompt:'Une vertèbre en anneau, sans corps typique, porte deux facettes supérieures recevant les condyles occipitaux. Un autre os porte un pivot vertical. Identifiez-les.',answer:'L’anneau est l’atlas C1. Le pivot est la dent de l’axis C2 ; il participe à la rotation de la charnière supérieure.'},refs:['7-3-the-vertebral-column','9-6-anatomy-of-selected-synovial-joints','13-4-the-peripheral-nervous-system']
},
{
 id:'anat-spine',title:'Rachis thoracolombaire, sacrum et coccyx',tag:'Rachis et thorax',
 objectives:['Identifier les caractères thoraciques et lombaires','Décrire sacrum, coccyx et courbures normales','Relier disques, articulations et transmission des charges'],
 sections:[
 ['Les régions et le sens des courbures',`Sous les sept vertèbres cervicales se trouvent habituellement douze thoraciques, cinq lombaires, cinq sacrées fusionnées puis un coccyx dont le nombre de segments varie, souvent quatre. Les vertèbres mobiles sont donc habituellement vingt-quatre avant le sacrum. Les conventions de comptage distinguent des segments d’origine et des os adultes fusionnés ; dire que le sacrum est un os ne signifie pas qu’il n’a qu’un segment embryonnaire.

De profil, les régions thoracique et sacrée présentent une convexité postérieure, tandis que les régions cervicale et lombaire présentent une convexité antérieure. Ces courbures sagittales normales contribuent à l’organisation mécanique du tronc. Elles ne sont pas toutes pathologiques. Dans le plan frontal, une déviation ne se définit pas simplement en observant une rotation de la caméra : il faut un repère anatomique stable pour décrire l’axe du rachis.`],
 ['Vertèbres thoraciques : les relations avec les côtes',`Les vertèbres thoraciques portent des surfaces articulaires costales. Une côte typique s’articule par sa tête avec les corps vertébraux voisins et la région discale, et par son tubercule avec le processus transverse de la vertèbre correspondante. Cette organisation comporte des exceptions aux extrémités de la série ; les niveaux T1, T10, T11 et T12 ne doivent pas être forcés dans un modèle absolument identique.

Les processus épineux thoraciques sont souvent dirigés vers le bas, particulièrement aux étages moyens. Les corps deviennent globalement plus volumineux vers le bas, en relation avec les charges cumulées. L’orientation des articulations postérieures et l’union avec la cage thoracique influencent la mobilité. Une vertèbre thoracique n’est pas identifiée uniquement par la longueur de son épine : les facettes costales et l’ensemble des rapports fournissent des critères plus pertinents.`],
 ['Vertèbres lombaires : corps et éléments postérieurs',`Les vertèbres lombaires possèdent des corps volumineux et des processus épineux robustes. Elles ne portent normalement ni facettes costales thoraciques ni foramens transversaires cervicaux. Leurs articulations postérieures favorisent notamment la flexion-extension et limitent la rotation axiale, avec des différences selon le niveau. La mobilité d’un étage dépend aussi du disque et des ligaments, pas uniquement de la taille du corps.

L5 est en rapport avec la base inclinée du sacrum. Les charges descendantes ne suivent donc pas une pile de surfaces toutes horizontales. Les structures ligamentaires et articulaires participent à contrôler les composantes de cisaillement. Sur une vue postérieure, les processus articulaires et les lames peuvent masquer une partie des corps. Pour comprendre les contacts, il est utile de compléter la vue de dos par une vue latérale ou une coupe sagittale.`],
 ['Sacrum : une pièce de transmission au bassin',`Le sacrum est formé par la fusion habituelle de cinq segments. Sa base supérieure s’articule avec L5 ; son apex inférieur rejoint le coccyx. Le promontoire correspond au relief antérieur de la base sacrée. Les ailes s’étendent latéralement. Les surfaces auriculaires participent aux articulations sacro-iliaques avec les os coxaux. Le sacrum est donc à la fois la terminaison portante du rachis et une pièce de la ceinture pelvienne.

La face pelvienne, antérieure, est globalement concave et porte des lignes transversales ainsi que des foramens sacrés antérieurs. La face dorsale présente des crêtes issues des reliefs fusionnés et des foramens postérieurs. Le canal sacré prolonge le canal vertébral et se termine par le hiatus sacré, dont la morphologie varie. Les foramens antérieurs et postérieurs ne sont pas des trous d’un os sans organisation : ils témoignent des passages associés aux segments fusionnés.`],
 ['Disques, ligaments et structures nerveuses',`Un disque intervertébral associe un anneau fibreux périphérique et un noyau pulpeux central, en relation avec les plateaux adjacents. Il répartit des contraintes et autorise des déformations limitées. Les articulations entre processus articulaires sont synoviales, contrairement à l’union entre corps assurée par le disque. Un segment mobile associe donc plusieurs types de liaisons qui doivent fonctionner ensemble.

Les ligaments longitudinaux antérieur et postérieur suivent les corps, tandis que les ligaments jaunes unissent des lames adjacentes. D’autres ligaments relient notamment les processus épineux. Chez l’adulte, la moelle se termine habituellement vers L1–L2 ; les racines de la queue de cheval poursuivent leur trajet dans le canal plus bas. Le numéro d’une vertèbre n’est donc pas automatiquement le numéro du segment médullaire situé exactement à sa hauteur.`],
 ['Coccyx et lecture fonctionnelle du rachis',`Le coccyx correspond à plusieurs segments caudaux réduits, avec un degré de fusion variable. Il sert d’attache à des structures ligamentaires et musculaires du plancher pelvien. Sa petite taille ne signifie pas une absence de fonction. Il ne supporte pas les mêmes contacts articulaires ni les mêmes charges que L5, et ne doit pas être représenté comme une simple sixième vertèbre sacrée interchangeable.

Pour suivre les charges, partez du tronc vers les corps lombaires, la base sacrée, les articulations sacro-iliaques puis les os coxaux. Pour suivre une information nerveuse, utilisez une autre carte : moelle, racines, foramens et nerfs. Ces deux parcours partagent un territoire sans avoir les mêmes étapes. Lors d’une identification, annoncez d’abord la région, puis les critères visibles et enfin les limites de l’observation ; une variation du nombre ou de la fusion des segments exige davantage qu’une silhouette isolée.`],
 ],trap:'Le niveau d’une vertèbre n’est pas équivalent au niveau d’un segment médullaire ; la moelle ne se prolonge pas jusqu’au coccyx.',recall:'Quelles surfaces unissent le sacrum aux deux os coxaux ?',answer:'Les surfaces auriculaires participent aux articulations sacro-iliaques, renforcées par de puissants ligaments.',glossary:[['Promontoire','Relief antérieur de la base du sacrum.'],['Anneau fibreux','Partie périphérique du disque intervertébral.'],['Noyau pulpeux','Partie centrale déformable du disque.'],['Queue de cheval','Ensemble de racines descendant sous le cône médullaire.']],caseStudy:{prompt:'Une pièce fusionnée comporte une face antérieure concave, quatre paires d’orifices antérieurs et deux surfaces latérales en forme d’oreille. Où transmet-elle les charges ?',answer:'C’est un sacrum de morphologie habituelle. Il reçoit les charges via L5 et les transmet aux os coxaux par les articulations sacro-iliaques.'},refs:['7-3-the-vertebral-column','8-3-the-pelvic-girdle-and-pelvis','13-2-the-central-nervous-system']
},
]

chapters.push(
{
 id:'anat-thorax',title:'Cage thoracique : sternum, douze paires de côtes et respiration',tag:'Rachis et thorax',
 objectives:['Classer les douze paires de côtes selon leurs attaches','Orienter une côte typique et le sternum','Relier les mouvements costaux aux variations du thorax'],
 sections:[
 ['Une cage ouverte et déformable',`La cage thoracique associe en arrière le rachis thoracique, latéralement douze paires de côtes et leurs espaces intercostaux, en avant le sternum et les cartilages costaux. Il ne s’agit pas d’une boîte osseuse continue : les tissus intercostaux ferment les espaces, tandis que les ouvertures supérieure et inférieure la relient à d’autres régions. Le diaphragme participe à la séparation entre thorax et abdomen, mais n’est pas une pièce osseuse de la cage.

Cette architecture protège notamment des organes thoraciques, offre des attaches musculaires et accompagne la ventilation. Protection et mobilité sont donc complémentaires. Les cartilages antérieurs permettent des déformations que des ponts osseux rigides limiteraient. Le contour inférieur des côtes peut se projeter devant certains organes abdominaux ; la limite du squelette thoracique ne correspond pas à une ligne horizontale qui séparerait tous les organes thoraciques de tous les organes abdominaux.`],
 ['Le sternum, du manubrium au processus xiphoïde',`Le sternum comprend un manubrium supérieur, un corps et un processus xiphoïde inférieur. L’incisure jugulaire occupe le bord supérieur médian du manubrium ; les incisures claviculaires se situent de part et d’autre. Les clavicules s’y articulent, reliant le membre supérieur au squelette axial. La jonction entre manubrium et corps forme l’angle sternal, repère utile pour retrouver le deuxième cartilage costal.

Le corps porte des incisures pour les cartilages costaux. Le processus xiphoïde varie de forme et d’ossification ; son aspect n’est pas un modèle identique chez tous les sujets. Sur une vue antérieure, distinguez un cartilage venant au sternum d’une côte osseuse directement soudée au sternum. Les articulations sternocostales n’ont pas toutes la même organisation : la première est habituellement cartilagineuse, tandis que plusieurs suivantes possèdent une organisation synoviale. L’inventaire des surfaces précède donc la classification de leurs unions.`],
 ['Côtes vraies, fausses et flottantes',`Les côtes 1 à 7 possèdent chacune un cartilage rejoignant directement le sternum : elles sont dites vraies. Les côtes 8 à 10 rejoignent indirectement le sternum par les cartilages situés au-dessus et participent au rebord costal. Les côtes 11 et 12 n’ont pas d’attache sternale antérieure et sont dites flottantes. Dans une classification large, les côtes 8 à 12 sont des fausses côtes, dont 11 et 12 constituent le sous-groupe flottant.

« Flottante » ne signifie pas détachée du rachis : les attaches postérieures persistent. Toutes les paires sont numérotées du haut vers le bas. Les onze espaces intercostaux sont nommés d’après la côte qui les surplombe ; le territoire situé sous la douzième côte est subcostal. Ce système de repérage évite de confondre le numéro d’un espace avec celui de sa limite inférieure.`],
 ['Orienter une côte typique',`Une côte typique possède une tête postérieure, un col, un tubercule, un angle et un corps incurvé qui se termine en avant par une extrémité destinée au cartilage costal. La tête participe à l’articulation avec les corps vertébraux ; le tubercule participe au contact avec un processus transverse. La courbure ne doit pas faire inverser ces deux surfaces articulaires, proches mais fonctionnellement distinctes.

Le sillon costal longe une partie du bord inférieur de la face interne et entretient des rapports avec le paquet vasculonerveux intercostal. Pour déterminer le côté, placez tête et tubercule en arrière, orientez la concavité vers l’intérieur et vérifiez la situation inférieure du sillon. Une seule concavité sans repérage des extrémités ne suffit pas. Les muscles intercostaux occupent les intervalles ; les vaisseaux et nerfs ne cheminent pas librement au milieu d’une cavité osseuse fermée.`],
 ['Les particularités de certaines côtes',`La première côte est courte, large et aplatie ; sa face supérieure présente des rapports avec les vaisseaux subclaviers et une insertion du scalène antérieur. Son orientation diffère de celle d’une côte moyenne. La deuxième possède également des caractères propres. Les côtes 11 et 12 n’ont pas les mêmes articulations costotransversaires que les côtes typiques, puisqu’elles ne possèdent pas un tubercule articulaire comparable.

Une classification « typique » sert à apprendre une organisation commune, puis à identifier les exceptions. Elle ne doit pas effacer les différences aux extrémités de la série. La longueur des côtes n’augmente pas simplement de la première à la douzième. Lorsqu’une pièce est isolée, combinez sa tête, son corps, ses surfaces, son sillon et sa largeur. Les critères qui identifient une première côte ne sont pas ceux qui permettent de reconnaître une côte flottante.`],
 ['Mécanique respiratoire et lecture d’ensemble',`Lors de l’inspiration, l’élévation coordonnée des côtes contribue à augmenter les diamètres du thorax. Le mouvement dit en anse de seau décrit surtout l’augmentation transversale ; celui en poignée de pompe décrit surtout la composante antéropostérieure. Ce sont des modèles pédagogiques d’un mouvement tridimensionnel, et non deux articulations séparées, chacune limitée à un seul plan. Le diaphragme ajoute une contribution majeure à la variation du volume thoracique.

Les muscles déplacent les pièces autour de leurs articulations postérieures, tandis que les cartilages et les unions antérieures accompagnent le changement. Au repos, l’expiration calme repose largement sur le retour élastique, sans être une contraction obligatoire et symétrique de tous les muscles inspiratoires. Pour expliquer la cage thoracique, reliez les attaches à la direction du mouvement, puis au changement de volume ; évitez de déduire la ventilation du seul nombre de côtes visibles sur une projection.`],
 ],trap:'Les côtes flottantes gardent leurs attaches postérieures. Les cartilages costaux ne sont pas des os surnuméraires.',recall:'Pourquoi le deuxième cartilage costal est-il utile pour le repérage ?',answer:'Il rejoint le sternum au niveau de l’angle sternal, repère qui permet de commencer le comptage des côtes et espaces.',glossary:[['Manubrium','Partie supérieure du sternum.'],['Angle sternal','Relief de la jonction manubrium–corps sternal.'],['Sillon costal','Gouttière de la face interne, près du bord inférieur d’une côte.'],['Côte flottante','Côte 11 ou 12 sans attache sternale antérieure.']],caseStudy:{prompt:'Une côte se termine en avant sans rejoindre le sternum, mais sa tête s’articule au rachis. Est-elle nécessairement anormale ?',answer:'Non. C’est l’organisation normale des côtes flottantes 11 et 12 ; l’absence d’attache antérieure ne supprime pas leur articulation postérieure.'},refs:['7-4-the-thoracic-cage','22-3-the-process-of-breathing']
},
{
 id:'anat-shoulder-girdle',title:'Ceinture scapulaire : clavicule et scapula',tag:'Membre supérieur',
 objectives:['Orienter clavicule et scapula avec plusieurs repères','Identifier les articulations de la ceinture scapulaire','Expliquer le placement de la glène lors de l’élévation du bras'],
 sections:[
 ['Relier le membre supérieur au tronc',`La ceinture scapulaire associe une clavicule et une scapula de chaque côté. La clavicule forme une entretoise entre sternum et scapula ; la scapula porte la cavité glénoïdale qui reçoit la tête humérale. Cette organisation éloigne le membre supérieur du thorax et lui offre une grande amplitude. La mobilité de l’épaule ne résulte donc pas uniquement du contact entre humérus et scapula.

L’articulation sternoclaviculaire constitue la liaison articulaire osseuse du membre supérieur avec le squelette axial. La scapula repose sur le thorax par l’intermédiaire de muscles et de plans de glissement. Il n’existe pas, entre sa face antérieure et une côte, une articulation synoviale os contre os équivalente au coude. Le terme fonctionnel « scapulothoracique » décrit une contribution au mouvement sans imposer la présence d’une capsule articulaire classique.`],
 ['Clavicule : extrémités et courbures',`La clavicule est un os allongé en forme de S. Son extrémité sternale médiale est plus volumineuse ; l’extrémité acromiale latérale est plus aplatie. La partie médiale présente une convexité antérieure, tandis que la partie latérale présente une concavité antérieure. Pour déterminer le côté, associez ces courbures à l’aspect des extrémités et aux reliefs de la face inférieure ; une courbe observée isolément peut facilement être inversée.

La face supérieure est relativement lisse par rapport à la face inférieure. Le tubercule conoïde et la ligne trapézoïde appartiennent à la région latérale inférieure et reçoivent des attaches ligamentaires. Une empreinte médiale inférieure est liée au ligament costoclaviculaire. Le sillon du muscle subclavier concerne la face inférieure du corps. Ces reliefs rappellent qu’une clavicule n’est pas une barre passive : muscles et ligaments contrôlent sa position et transmettent des forces.`],
 ['Scapula : faces, bords et angles',`La scapula est un os plat triangulaire situé en arrière du thorax. Elle possède des bords supérieur, médial et latéral, ainsi que des angles supérieur, inférieur et latéral. La face costale, tournée vers les côtes, porte la fosse subscapulaire. La face postérieure est divisée par l’épine scapulaire en fosses supraépineuse et infraépineuse. Le mot « infraépineux » indique donc une position sous l’épine, pas sous toute la scapula.

Pour orienter l’os, placez la glène latéralement et l’épine en arrière. L’angle inférieur se dirige vers le bas. La forme triangulaire seule ne suffit pas à reconnaître droite et gauche. Les fosses offrent des surfaces d’origine musculaire, tandis que la glène est une surface articulaire. Un relief proéminent et une dépression ne sont pas automatiquement deux surfaces destinées à s’emboîter : leur rôle dépend de leurs rapports anatomiques.`],
 ['Glène, acromion et processus coracoïde',`La cavité glénoïdale se trouve à l’angle latéral. Elle est relativement peu profonde par comparaison avec la tête humérale, et son rebord est complété par un bourrelet fibrocartilagineux. Les tubercules supraglénoïdal et infraglénoïdal sont des repères d’attaches tendineuses. Ils doivent être distingués des tubercules de l’humérus, qui appartiennent à une autre pièce.

L’épine se prolonge latéralement par l’acromion, qui s’articule avec la clavicule. Le processus coracoïde se projette vers l’avant et reçoit plusieurs attaches musculaires et ligamentaires. Le ligament coracoacromial relie deux régions de la scapula et contribue à une arche au-dessus de la tête humérale. Les ligaments coracoclaviculaires, eux, relient le coracoïde à la clavicule. Une syllabe commune ne signifie donc pas que ces ligaments unissent les mêmes deux points.`],
 ['Les unions qui stabilisent une ceinture mobile',`L’articulation sternoclaviculaire possède un disque articulaire et permet les mouvements de la clavicule nécessaires à l’élévation et à la projection de l’épaule. L’acromioclaviculaire autorise des ajustements entre clavicule et scapula. Les ligaments conoïde et trapézoïde constituent le ligament coracoclaviculaire et jouent un rôle majeur dans la liaison entre ces deux os. La stabilité ne repose donc pas uniquement sur la petite surface de contact acromioclaviculaire.

Les muscles fixent et déplacent la scapula sur le thorax. Le trapèze, le dentelé antérieur et d’autres muscles participent à une action coordonnée. Un déplacement scapulaire peut comprendre élévation, abaissement, protraction, rétraction et rotation. Ces mouvements ne sont pas des synonymes : une scapula peut tourner de façon à orienter sa glène vers le haut sans simplement monter en bloc verticalement.`],
 ['Comprendre l’élévation du bras',`Élever le membre supérieur combine un mouvement glénohuméral et une rotation de la scapula, accompagnés de mouvements claviculaires. Cette coordination maintient une orientation utile de la glène et des structures périarticulaires. Le rythme scapulohuméral varie selon l’amplitude, le plan du mouvement et les individus ; un rapport numérique unique ne doit pas être présenté comme une loi rigide valable à chaque degré.

Pour analyser une image, identifiez séparément la position du sternum, la direction de la clavicule, l’orientation de la glène et celle de l’humérus. On peut ainsi distinguer une élévation du bras d’une simple hausse de l’épaule. Le modèle osseux donne les leviers et les contacts ; il faut ajouter mentalement muscles, capsule et ligaments pour comprendre le mouvement réel. Cette méthode prépare l’étude régionale de la coiffe des rotateurs sans la confondre avec un nouveau groupe d’os.`],
 ],trap:'La glène et le processus coracoïde appartiennent à la scapula ; la tête et les tubercules huméraux appartiennent à l’humérus.',recall:'Quelle articulation relie directement la ceinture scapulaire au squelette axial ?',answer:'L’articulation sternoclaviculaire, entre extrémité médiale de la clavicule et manubrium sternal.',glossary:[['Glène','Surface scapulaire recevant la tête humérale.'],['Acromion','Prolongement latéral de l’épine scapulaire.'],['Coracoïde','Processus scapulaire projeté vers l’avant.'],['Protraction','Déplacement de la scapula vers l’avant autour du thorax.']],caseStudy:{prompt:'Pendant l’élévation du bras, la glène regarde davantage vers le haut alors que l’humérus se déplace aussi par rapport à elle. Peut-on attribuer tout le mouvement à une seule articulation ?',answer:'Non. L’élévation associe glénohumérale, mouvements de la scapula sur le thorax et ajustements acromioclaviculaires et sternoclaviculaires.'},refs:['8-1-the-pectoral-girdle','9-6-anatomy-of-selected-synovial-joints']
},
{
 id:'anat-humerus',title:'Humérus et articulation glénohumérale',tag:'Membre supérieur',
 objectives:['Orienter un humérus et identifier ses extrémités','Relier les reliefs aux insertions et rapports','Expliquer mobilité et stabilité de l’épaule'],
 sections:[
 ['Le squelette du bras',`Le bras, au sens anatomique, s’étend entre épaule et coude et contient un seul os long : l’humérus. L’avant-bras contient radius et ulna. Employer « bras » pour tout le membre supérieur dans une conversation est courant, mais cette approximation devient source d’erreur lorsqu’il faut localiser une structure. L’humérus s’articule proximalement avec la scapula et distalement avec les deux os de l’avant-bras.

Sa tête regarde principalement en haut, en dedans et légèrement en arrière. L’extrémité distale possède des surfaces différentes pour radius et ulna. Pour latéraliser la pièce, combinez la tête médiale avec la fosse olécrânienne postérieure et la disposition des surfaces distales. La longueur du corps ne renseigne pas sur le côté. Une image vue de dos doit donc être orientée avant d’attribuer un repère à droite ou à gauche.`],
 ['Épiphyse proximale et deux cols',`La tête humérale est une surface articulaire arrondie, séparée des tubercules par le col anatomique. Le col chirurgical correspond à une région située plus distalement, à la transition vers le corps. Ces termes ne désignent pas deux synonymes d’un même sillon. Le tubercule majeur est principalement latéral ; le tubercule mineur est plus antérieur. Entre eux se trouve le sillon intertuberculaire.

Les tendons de la coiffe des rotateurs s’insèrent sur les tubercules : supraépineux, infraépineux et petit rond sur des territoires du tubercule majeur, subscapulaire sur le mineur. Le tendon du long chef du biceps chemine dans le sillon intertuberculaire après son trajet proximal. Un tendon qui longe un relief ne s’y insère pas nécessairement. Cette différence entre trajet et fixation est essentielle pour comprendre pourquoi un nom de sillon ne suffit pas à identifier l’action d’un muscle.`],
 ['Diaphyse et principaux rapports',`La diaphyse porte une tubérosité deltoïdienne sur sa région latérale, correspondant à l’insertion du deltoïde. Sur la face postérieure, le sillon du nerf radial est un rapport osseux notable. Le nerf radial et des vaisseaux associés cheminent près de cette région. Le nerf n’est pas contenu dans la cavité médullaire : il entretient un rapport avec la surface et les tissus voisins.

Les reliefs d’insertion orientent l’action des muscles et la transmission des forces vers l’os. Une tubérosité n’est pas une surface articulaire malgré sa saillie. Les bords distaux se prolongent vers les régions supracondylaires et les épicondyles. Pour lire le corps, partez des extrémités déjà orientées puis recherchez chaque relief à la bonne face. Cette démarche évite de déplacer mentalement le sillon radial sur la face antérieure ou de confondre insertion deltoïdienne et tubercule majeur.`],
 ['Extrémité distale : deux partenaires articulaires',`Le capitulum, latéral, s’articule avec la tête du radius. La trochlée, plus médiale, s’articule avec l’incisure trochléaire de l’ulna. La trochlée possède une forme de poulie ; elle ne doit pas être confondue avec un épicondyle. Les épicondyles médial et latéral sont des reliefs non articulaires où s’attachent notamment muscles et ligaments du coude.

En avant se trouvent les fosses radiale et coronoïdienne, en rapport avec les structures de l’avant-bras pendant la flexion. En arrière, la fosse olécrânienne reçoit l’olécrâne lors de l’extension. Le nerf ulnaire passe derrière l’épicondyle médial. Ainsi, « ulnaire » qualifie ici le nerf et son territoire de rapport ; cela ne transforme pas l’épicondyle médial en une partie de l’ulna. Les pièces et les structures voisines doivent conserver leurs identités dans la description.`],
 ['Mobilité glénohumérale et moyens de stabilité',`La glénohumérale est une articulation sphéroïde entre tête humérale et cavité glénoïdale. Elle permet flexion-extension, abduction-adduction et rotations, dont les combinaisons produisent une circumduction. La grande surface de la tête et la relative faible profondeur de la glène favorisent l’amplitude. La congruence osseuse seule fournit donc une stabilité limitée par comparaison avec une cavité beaucoup plus enveloppante comme l’acétabulum.

Le bourrelet glénoïdal augmente le rebord de la cavité. Capsule, ligaments et muscles contribuent à la stabilité. La coiffe des rotateurs participe au centrage de la tête pendant les mouvements ; elle ne correspond pas à une coque osseuse immobile. Le deltoïde élève le bras, mais son effet dépend des forces associées qui contrôlent la tête humérale. Un mouvement réussi exige une coordination plutôt qu’une simple traction isolée dans une direction.`],
 ['Articuler orientation, mouvement et voisinage',`L’abduction s’analyse par rapport au tronc et à un plan de référence ; elle associe l’humérus à la scapula au cours de l’élévation complète. Les rotations médiale et latérale font tourner l’humérus autour de son axe longitudinal. Lorsque le coude est fléchi, la main rend ces rotations plus visibles, mais le mouvement observé de la main ne signifie pas qu’il se produit exclusivement au poignet.

Pour reconstruire l’humérus, suivez un itinéraire : tête médiale, tubercules proximaux, corps et tubérosité deltoïdienne, puis capitulum latéral et trochlée médiale. Retournez ensuite la pièce pour identifier fosse olécrânienne et rapport radial. Cette double lecture sépare surface articulaire, insertion et passage voisin. Le modèle de surface ne montre pas automatiquement capsule, cartilages ou nerfs ; les rapports décrits dans le cours restent nécessaires même lorsqu’un relief osseux est clairement visible.`],
 ],trap:'Le capitulum répond au radius ; la trochlée répond à l’ulna. Les épicondyles sont des reliefs d’attache et non ces surfaces articulaires.',recall:'Quels repères permettent de reconnaître la face postérieure d’un humérus ?',answer:'La grande fosse olécrânienne distale et, sur le corps, le rapport du sillon radial permettent de confirmer l’orientation postérieure.',glossary:[['Col anatomique','Limite de la surface de la tête humérale.'],['Tubercule majeur','Relief proximal latéral recevant des tendons de la coiffe.'],['Capitulum','Surface distale latérale en contact avec le radius.'],['Trochlée humérale','Surface distale articulée avec l’ulna.']],caseStudy:{prompt:'Un étudiant identifie une surface arrondie distale latérale, puis affirme qu’elle reçoit l’olécrâne. Corrigez les deux associations.',answer:'La surface est le capitulum et reçoit la tête radiale. L’olécrâne appartient à l’ulna ; il entre dans la fosse olécrânienne postérieure pendant l’extension.'},refs:['8-2-bones-of-the-upper-limb','9-6-anatomy-of-selected-synovial-joints']
},
{
 id:'anat-forearm',title:'Radius, ulna et coude : flexion et pronosupination',tag:'Membre supérieur',
 objectives:['Reconnaître radius et ulna dans la position anatomique','Identifier les surfaces du coude et des articulations radio-ulnaires','Distinguer flexion-extension et pronosupination'],
 sections:[
 ['Deux os, une position de référence',`L’avant-bras s’étend du coude au poignet. En position anatomique, paume dirigée vers l’avant, le radius est latéral, du côté du pouce, et l’ulna est médial, du côté du petit doigt. Les deux os sont alors globalement parallèles. Pendant la pronation, le radius se déplace par rapport à l’ulna ; leur projection peut se croiser. Les noms « latéral » et « médial » pour leur identification se rapportent à la position de référence, pas à toute attitude possible de la main.

Leurs proportions diffèrent : l’ulna est particulièrement développé proximalement au niveau de son contact avec l’humérus, tandis que le radius s’élargit distalement au poignet. Cette complémentarité traduit des fonctions différentes dans les contacts articulaires et la transmission des charges. Il ne s’agit pas de deux copies symétriques d’un même os.`],
 ['Ulna proximal : l’incisure trochléaire',`L’ulna, anciennement appelé cubitus, porte proximalement l’olécrâne en arrière et le processus coronoïde en avant. Entre eux s’étend l’incisure trochléaire, qui reçoit la trochlée humérale. L’olécrâne constitue le relief postérieur du coude et reçoit l’insertion du triceps. Le processus coronoïde est distinct du processus homonyme de la mandibule : un nom descriptif peut exister sur plusieurs os.

Sur le côté latéral proximal se trouve l’incisure radiale, en contact avec la circonférence de la tête radiale. L’incisure radiale et l’incisure trochléaire reçoivent donc deux os différents. La tubérosité ulnaire, située plus distalement, reçoit une insertion musculaire. Pour orienter l’ulna, placez la grande incisure vers l’avant et l’incisure radiale vers le radius. L’épiphyse distale plus petite porte une tête et un processus styloïde, à ne pas confondre avec les reliefs proximaux.`],
 ['Radius : tête proximale et extrémité distale large',`La tête radiale est proximale. Sa cupule supérieure répond au capitulum huméral, tandis que sa circonférence participe à l’articulation radio-ulnaire proximale. Le col se situe sous la tête. La tubérosité radiale constitue une insertion du biceps ; la traction de ce tendon contribue à la supination et à la flexion du coude selon la position. Le rôle fonctionnel ne se déduit pas du seul fait que le tendon s’attache près du coude.

L’extrémité distale du radius est large et porte des surfaces articulaires pour des os du carpe. Son processus styloïde est latéral. Son incisure ulnaire, médiale, s’articule avec la tête distale de l’ulna. Une tête osseuse n’est donc pas forcément proximale : la tête du radius l’est, celle de l’ulna est distale. Cette inversion constitue un repère simple pour apprendre les deux pièces ensemble.`],
 ['Le coude associe trois contacts',`L’ensemble articulaire du coude comprend les contacts huméro-ulnaire, huméroradial et radio-ulnaire proximal. Une capsule commune associe leurs territoires. La flexion-extension se déroule principalement à travers les rapports de l’humérus avec l’avant-bras ; la rotation de la tête radiale appartient à la pronosupination. La présence de trois contacts n’implique pas trois mouvements indépendants que l’on pourrait tous réaliser séparément.

Les ligaments collatéraux contribuent à la stabilité latérale et médiale. Le ligament annulaire entoure la circonférence de la tête du radius et la maintient contre l’incisure radiale de l’ulna, tout en autorisant la rotation. Il ne doit pas être confondu avec la membrane interosseuse qui unit les corps des deux os sur une grande longueur. Les surfaces osseuses, les ligaments et les muscles constituent ensemble les conditions de mobilité.`],
 ['Pronation et supination : une mécanique à deux extrémités',`La supination ramène la paume vers l’avant en position anatomique, ou vers le haut lorsque le coude est fléchi et l’avant-bras horizontal. La pronation tourne la paume dans le sens opposé. Proximalement, la tête radiale tourne dans son anneau ligamentaire. Distalement, le radius se déplace autour de la tête ulnaire. Les articulations radio-ulnaires proximale et distale participent donc au même mouvement global.

La main suit principalement le radius au cours de ce déplacement. Faire tourner toute l’épaule peut produire un changement d’orientation visuellement proche, mais ne remplace pas anatomiquement la pronosupination. Pour les distinguer, observez aussi la position de l’humérus et du coude. L’ulna peut participer à des ajustements selon la tâche et la chaîne de mouvement ; le modèle du radius mobile autour d’un ulna fixe reste une simplification utile, à condition de l’annoncer comme telle.`],
 ['Poignet et transfert des contraintes',`Au poignet, le radius s’articule directement avec le scaphoïde et le lunatum. L’ulna est séparé de la rangée proximale du carpe par un complexe fibrocartilagineux comprenant un disque articulaire. Il serait donc inexact de dessiner un contact direct ordinaire entre tête ulnaire et os du carpe comme s’il reproduisait le contact radial. L’articulation radio-ulnaire distale reste distincte de l’articulation radiocarpienne.

La membrane interosseuse relie radius et ulna et participe au transfert de charges ainsi qu’aux attaches musculaires. Une force reçue par la main ne suit pas un trajet unique dans un radius totalement isolé jusqu’à l’humérus. Pour réviser, comparez systématiquement les deux extrémités de chaque os, puis les contacts entre os voisins. Ce raisonnement en réseau explique mieux la fonction que deux listes séparées de reliefs apprises sans partenaire articulaire.`],
 ],trap:'La tête du radius est proximale, celle de l’ulna est distale. Pronation et supination ne sont pas des flexions du poignet.',recall:'Quelles articulations doivent fonctionner ensemble pour la pronosupination ?',answer:'Les articulations radio-ulnaires proximale et distale, avec les structures de liaison de l’avant-bras.',glossary:[['Olécrâne','Processus proximal postérieur de l’ulna.'],['Incisure trochléaire','Surface ulnaire recevant la trochlée humérale.'],['Supination','Rotation de l’avant-bras orientant la paume vers l’avant en position anatomique.'],['Ligament annulaire','Anneau maintenant la tête radiale contre l’ulna proximal.']],caseStudy:{prompt:'Paume vers l’avant, identifiez l’os du côté du pouce. Pendant la pronation, cet os devient-il un ulna parce que sa projection change ?',answer:'Il s’agit du radius, qui garde son identité pendant la rotation. Le changement de position est précisément lié à la pronosupination.'},refs:['8-2-bones-of-the-upper-limb','9-5-types-of-body-movements','9-6-anatomy-of-selected-synovial-joints']
},
{
 id:'anat-hand',title:'Main : les huit os du carpe, métacarpiens et phalanges',tag:'Membre supérieur',
 objectives:['Nommer les huit os du carpe dans leurs rangées','Compter les métacarpiens et phalanges sans doubler le pouce','Relier les articulations à la préhension et à l’opposition'],
 sections:[
 ['Vingt-sept os dans la main habituelle',`La main comprend huit os du carpe, cinq métacarpiens et quatorze phalanges, soit vingt-sept os dans le décompte usuel, hors os sésamoïdes variables. Les rayons sont numérotés I à V du pouce au petit doigt. Les termes palmaire et dorsal désignent respectivement la face de la paume et son opposée. Radial renvoie au côté du pouce ; ulnaire au côté du petit doigt, dans le repère anatomique.

Le carpe constitue un ensemble de petites pièces organisées et reliées par des ligaments, pas un os unique nommé « poignet ». Les métacarpiens constituent le squelette principal de la paume ; les phalanges constituent celui des doigts. Un déplacement du doigt peut associer plusieurs articulations, et le mouvement observé de son extrémité ne permet pas à lui seul de déduire quelle articulation a bougé.`],
 ['Rangée proximale du carpe',`Du côté radial vers le côté ulnaire, la rangée proximale comprend le scaphoïde, le lunatum, le triquetrum et le pisiforme. On rencontre aussi les noms anciens semi-lunaire pour lunatum et pyramidal pour triquetrum. Le pisiforme se situe en avant du triquetrum, dans le tendon du fléchisseur ulnaire du carpe ; il ne se place pas simplement à la suite des trois autres sur une ligne plane.

Le scaphoïde contribue à relier fonctionnellement les deux rangées par ses contacts et ses ligaments. Le lunatum participe au contact avec le radius. Le triquetrum entretient notamment des rapports avec le complexe fibrocartilagineux ulnaire. La disposition est tridimensionnelle : une projection antérieure peut superposer des os et masquer une surface. Pour apprendre la rangée, associez l’ordre des noms à deux repères stables, le pouce et la face palmaire, plutôt qu’à la gauche de l’image.`],
 ['Rangée distale et canal carpien',`De radial à ulnaire, la rangée distale comprend le trapèze, le trapézoïde, le capitatum et l’hamatum. Les anciens termes grand os et os crochu correspondent respectivement au capitatum et à l’hamatum. Le trapèze s’articule avec le premier métacarpien ; il ne faut pas le confondre avec le trapézoïde, voisin mais distinct. L’hamatum porte un crochet, ou hamulus, projeté vers la paume.

Le carpe forme une concavité palmaire, complétée par le rétinaculum des fléchisseurs pour constituer le canal carpien. Ce passage contient notamment le nerf médian et des tendons fléchisseurs. Il ne contient pas les cinq métacarpiens et n’est pas une cavité médullaire. Le pisiforme et le crochet de l’hamatum servent aussi de repères à un passage ulnaire voisin, distinct du canal carpien. Deux tunnels proches ne partagent donc pas nécessairement le même contenu.`],
 ['Métacarpiens : bases, corps et têtes',`Chaque métacarpien comprend une base proximale articulée avec le carpe, un corps et une tête distale articulée avec la phalange proximale. Les têtes métacarpiennes forment les reliefs visibles lors de la fermeture du poing. Elles ne sont pas les extrémités des phalanges. Les articulations carpométacarpiennes n’ont pas toutes la même mobilité ; les rayons centraux sont relativement stables et servent de support à la préhension.

Le premier métacarpien est court, robuste et orienté différemment des autres. Son articulation avec le trapèze est en selle et contribue à l’opposition du pouce. Cette opposition rapproche la pulpe du pouce de celle des autres doigts en combinant plusieurs composantes, dont une rotation. Elle ne se réduit pas à une simple flexion du pouce vers la paume. La disposition du premier rayon explique une partie de la précision de la prise.`],
 ['Phalanges et mouvements digitaux',`Les doigts II à V possèdent chacun trois phalanges : proximale, moyenne et distale. Le pouce possède seulement une proximale et une distale. Le total est donc quatre fois trois, plus deux, soit quatorze. Chaque phalange est un os long avec base, corps et extrémité distale. Une phalange moyenne n’existe pas normalement dans le pouce et ne doit pas être inventée pour rendre les cinq rayons identiques.

Les articulations métacarpophalangiennes relient les têtes métacarpiennes aux bases des premières phalanges. Les interphalangiennes relient les phalanges entre elles et fonctionnent principalement en flexion-extension. Pour l’abduction et l’adduction des doigts longs, la référence est l’axe du troisième doigt. Cette référence locale diffère du plan médian du corps ; l’écartement des doigts se décrit donc avec le bon axe de la main plutôt qu’avec une règle générale appliquée sans adaptation.`],
 ['Relier l’architecture à la préhension',`La prise de force mobilise l’enroulement des doigts autour d’un objet, avec une stabilisation du poignet et l’opposition du pouce. La prise de précision met davantage en jeu les contacts entre pulpes et une coordination fine. Les os fournissent leviers et surfaces ; les tendons extrinsèques venant de l’avant-bras et les muscles intrinsèques de la main organisent les mouvements. Aucun os du carpe ne commande seul une forme de prise.

Pour réviser, construisez la main depuis le radius vers les deux rangées du carpe, puis les cinq rayons. Vérifiez le compte vingt-sept seulement après avoir placé les pièces. Sur une image, le pisiforme peut se superposer au triquetrum et les phalanges se masquer si les doigts sont fléchis. L’absence d’un nom lisible sur une vue ne doit pas être compensée par une supposée absence anatomique. Changez de vue et recoupez l’inventaire avec les rapports articulaires.`],
 ],trap:'Trapèze et trapézoïde sont deux os distincts. Le pouce n’a pas de phalange moyenne.',recall:'Nommez la rangée distale du carpe du pouce vers le petit doigt.',answer:'Trapèze, trapézoïde, capitatum et hamatum.',glossary:[['Lunatum','Os de la rangée proximale, anciennement semi-lunaire.'],['Triquetrum','Os proximal ulnaire, anciennement pyramidal.'],['Capitatum','Os central de la rangée distale, anciennement grand os.'],['Opposition','Mouvement combiné plaçant la pulpe du pouce face à d’autres pulpes.']],caseStudy:{prompt:'Un tableau attribue trois phalanges à chacun des cinq doigts et annonce vingt-huit os de la main. Comment corriger ce décompte ?',answer:'Le pouce en possède deux : il existe quatorze phalanges. En ajoutant huit os du carpe et cinq métacarpiens, on obtient vingt-sept os dans le décompte usuel.'},refs:['8-2-bones-of-the-upper-limb','9-4-synovial-joints','9-5-types-of-body-movements']
}
)

export const skeletalCourses:Course[]=chapters.map(c=>({id:c.id,title:c.title,category:'Anatomie',tag:c.tag,minutes:Math.ceil(c.sections.map(s=>s[1]).join(' ').split(/\s+/).length/150)+8,structure:null,objectives:c.objectives,sections:c.sections.map(([title,text])=>({title,text})),trap:c.trap,recall:c.recall,answer:c.answer,glossary:c.glossary,caseStudy:c.caseStudy,source:base+c.refs[0],sources:c.refs.map(ref=>({label:'OpenStax · Anatomie et physiologie 2e · '+ref.split('-').slice(0,2).join('.'),url:base+ref}))}))

const support=courseSupport(skeletalCourses)
export const skeletalDiagrams:Record<string,Diagram>=support.diagrams
export const skeletalQuestions:Question[]=support.questions
