import type {Structure} from '../types'

/** Existing course IDs ordered from the most specific chapter to a regional fallback. */
export function structureCourseCandidates(structure: Structure): string[] {
  const name = structure.name.toLocaleLowerCase('en').replace(/[_-]+/g, ' ')
  const has = (pattern: RegExp) => pattern.test(name)

  if (has(/third ventricle|fourth ventricle|lateral ventricle|brain ventricle/)) return ['FMA50801']
  if (has(/coronary|coronary sinus/)) return ['anat-coronary-vessels', 'anat-mediastinum', 'FMA7088']
  if (has(/purkinje|sino.?atrial|atrioventricular node|cardiac conduction/)) return ['anat-cardiac-conduction-nodes', 'anat-heart-chambers-valves', 'FMA7088']
  if (has(/atrium|ventricle|heart valve|mitral|tricuspid|aortic valve|pulmonary valve|papillary muscle of .*ventricle/)) {
    return ['anat-heart-chambers-valves', 'FMA7088']
  }
  if (has(/wrist|carpal tunnel|retinaculum of flexors|ulnar canal|canal of guyon/)) return ['anat-wrist-carpal-tunnel', 'anat-hand']
  if (has(/brachial plexus|plexus brachial/)) return ['anat-brachial-plexus', 'anat-upper-limb-nerves-trunks']
  if (has(/rotator cuff|supraspinatus|infraspinatus|teres minor|subscapularis/)) return ['anat-rotator-cuff', 'anat-upper-muscles']
  if (has(/femur/)) return ['FMA24474', 'anat-lower-muscles']
  if (has(/humerus|glenohumeral/)) return ['anat-humerus', 'anat-shoulder-girdle']
  if (has(/scapula|clavicle|acromion|shoulder girdle/)) return ['anat-shoulder-girdle', 'anat-humerus']
  if (has(/radius|ulna|olecranon|forearm/)) return ['anat-forearm', 'anat-upper-muscles']
  if (has(/carpal|metacarp|phalanges? of hand|hand|wrist/)) return ['anat-hand', 'anat-upper-muscles']
  if (has(/patella|knee|tibiofibular/)) return ['anat-knee', 'anat-lower-muscles']
  if (has(/hip joint|coxofemoral|acetabulum/)) return ['anat-coxofemoral-joint', 'anat-pelvis']
  if (has(/popliteal fossa/)) return ['anat-popliteal-fossa', 'anat-knee']
  if (has(/tibia|fibula|ankle|talus|calcaneus|tarsal|metatars|phalanges? of foot|foot/)) return ['anat-leg', 'anat-foot', 'anat-lower-muscles']
  if (has(/carotid|jugular/)) return ['anat-carotid-jugular-axes']
  if (has(/axillary artery|brachial artery/)) return ['anat-axillary-brachial-arteries']
  if (has(/radial artery|ulnar artery|palmar arch/)) return ['anat-radial-ulnar-arteries']
  if (has(/femoral artery|popliteal artery/)) return ['anat-femoral-popliteal-arteries', 'anat-popliteal-fossa']
  if (has(/saphenous vein|femoral vein|popliteal vein/)) return ['anat-lower-limb-veins']
  if (has(/cephalic vein|basilic vein|brachial vein/)) return ['anat-upper-limb-veins-lymph']
  if (has(/median nerve|radial nerve|ulnar nerve|axillary nerve|musculocutaneous nerve/)) return ['anat-upper-limb-nerves-trunks']
  if (has(/femoral nerve|obturator nerve|sciatic nerve/)) return ['anat-lumbosacral-plexus']
  if (has(/thoracic aorta|azygos|thoracic duct/)) return ['anat-thoracic-aorta-azygos']
  if (has(/celiac|coeliac|mesenteric|abdominal aorta/)) return ['anat-celiac-trunk-mesenteric-arteries']
  if (has(/iliac artery|iliac vein/)) return ['anat-iliac-vessels']
  if (has(/femoral triangle|sartorius|quadriceps|rectus femoris|vastus|adductor canal/)) return ['anat-femoral-triangle-scarpa', 'anat-lower-muscles']
  if (has(/gluteal|gluteus|hamstring|calf|gastrocnemius|soleus/)) return ['anat-gluteal-region-spaces', 'anat-lower-muscles', 'anat-leg']
  if (has(/leg compartment|tibialis|fibularis|peroneal|plantar muscle/)) return ['anat-leg-compartments', 'anat-lower-muscles']
  if (has(/biceps brachii|triceps brachii|deltoid|rotator cuff|brachial|forearm muscle/)) return ['anat-upper-muscles', 'anat-humerus']
  if (has(/vertebra|intervertebral|spinal|vertebral/)) return ['anat-spine', 'anat-cervical', 'anat-spinal-cord']
  if (has(/skull|cranium|cranial bone|suture/)) return ['anat-neurocranium', 'anat-face']
  if (has(/brain|cerebr|cerebell|thalam|hypothalam|hippocamp|ventricle/)) return ['FMA50801', 'anat-cranial-nerves']
  if (has(/cranial nerve|olfactory nerve|optic nerve|oculomotor|trochlear|trigeminal|abducens|facial nerve|vestibulocochlear|glossopharyngeal|vagus nerve|accessory nerve|hypoglossal/)) return ['anat-cranial-nerves', 'FMA50801']
  if (has(/pharynx|esophagus|oesophagus/)) return ['anat-pharynx-esophagus-cervical', 'anat-mediastinum']
  if (has(/larynx|thyroid|cervical trachea/)) return ['anat-larynx-trachea-thyroid', 'anat-cervical']
  if (has(/spleen|thymus|lymph node|lymphatic/)) return ['anat-lymphatic']
  if (has(/colon|cecum|caecum|appendix|rectum|large intestine/)) return ['anat-colon-rectum', 'FMA7200']
  if (has(/stomach|gastric/)) return ['FMA7148', 'anat-peritoneum']
  if (has(/pancreas/)) return ['FMA7198', 'anat-peritoneum']
  if (has(/biliary|gallbladder|gall bladder|cystic duct|common bile duct/)) return ['anat-biliary-tree-vesicle', 'FMA7197']
  if (has(/hepatic segment|liver lobe|hepatic pedicle/)) return ['anat-hepatic-segmentation-couinaud', 'FMA7197']
  if (has(/liver|hepatic/)) return ['FMA7197', 'anat-peritoneum']
  if (has(/kidney|renal|ureter|urinary bladder|urinary/)) return ['FMA7204', 'anat-urinary-pelvis']
  if (has(/bronch|trachea thoracic/)) return ['anat-tracheobronchial-tree', 'FMA7309']
  if (has(/lung|pulmonary/)) return ['FMA7309', 'anat-mediastinum']
  if (has(/heart|cardiac|aorta|mediastin|pericard/)) return ['anat-mediastinum', 'FMA7088']
  if (has(/oral|tongue|parotid|submandibular|sublingual|salivary/)) return ['anat-oral-cavity-salivary-glands', 'anat-face']
  if (has(/uter|ovary|vagina|vulva|breast|mammary/)) return ['anat-female-pelvis', 'anat-pelvis']
  if (has(/perine|pelvic floor|levator ani|ischiorectal/)) return ['anat-perineum-pelvic-floor', 'anat-pelvis']
  if (has(/prostate|testis|testicle|scrotum|seminal vesicle/)) return ['anat-male-pelvis', 'anat-pelvis']
  if (has(/pelvi|sacrum|coccyx|coxal|perine|ischiorectal/)) return ['anat-pelvis', 'anat-perineum-pelvic-floor']
  if (has(/artery|arterial|vein|venous|vascular|aortic/)) return ['anat-mediastinum', 'anat-celiac-trunk-mesenteric-arteries', 'anat-iliac-vessels']
  if (structure.group === 'skeleton') return ['anat-bone', 'anat-joints']
  if (structure.group === 'joints') return ['anat-joints', 'anat-bone']
  if (structure.group === 'muscles') return ['anat-trunk-muscles', 'anat-upper-muscles', 'anat-lower-muscles']
  if (structure.group === 'nerves') return ['anat-spinal-cord', 'anat-cranial-nerves']
  return []
}
